### ISSUE TITLE
Multiple curves plotting is too much work (feature request)

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#100]
I'm really content with my switch to ``Holoviews`` although I really mis the simplicity in which I can plot curves with ``matplotlib``.

In my +2000 lines script, the most used ``holoviews`` function that I use is a very simple function that I wrote:

```python
def plot(x, y, **kwargs):
    """
    A very general plotting function for HoloViews which give a similar
    output to plt.plot() for multiple lines and a single line.
    """
    if type(x) == list:
        x = np.array(x)
        
    if type(y) == list:
        y = np.array(y)
    
    if len(y.shape) == 1:
           return hv.NdOverlay({1: hv.Contours([zip(x, y)], **kwargs)}) #NdOverlay because it has square aspects by default.
    else:
        return hv.NdOverlay({i: hv.Contours([zip(x, y[:, i])], **kwargs) for i in range(y.shape[1])})
    
H1 = np.random.randn(10, 10)
H2 = np.random.randn(10, 10)
x = np.linspace(0, 1, 100)
eigenvals = [np.linalg.eigvalsh(H1 * alpha + H2 * (1 - alpha)) for alpha in x]
plot(x, eigenvals, label='Example')
```

![download](https://cloud.githubusercontent.com/assets/6897215/7783863/c1647706-0151-11e5-8fd2-c30afe7e161c.png)

We did discuss this in https://github.com/ioam/holoviews/issues/54, but now I feel like I'm a bit more experienced and writing out ``hv.NdOverlay({i: hv.Contours([zip(x, y[:, i])], **kwargs) for i in range(y.shape[1])})`` vs ``plt.plot(x,y)`` is just too much.

**Comment by philippjfr** [comment]
Do you need each Contour to be a different color? We did have some discussion about this a while ago but didn't come to any definite conclusions. If you do need every curve to be a different color then we might consider adapting either Contours for a purpose like this, while leaving Curve and Path the same as they are currently.

**Comment by jlstevens** [comment]
As we hope to beat matplotlib in terms of practicality (at least in the notebook), we will want to make this easier for you!

Looking at your function and thinking about how it fits into the design of HoloViews, I can imagine having some helper class methods to help make this sort of thing easier. Something we would definitely want to do if we think people will often want this!

I can imagine having an ``ndoverlay`` class method on ``Chart`` to help assist in the creation of NdOverlays using the sort of interface people are used to. For instance, something like:

```python
Contours.ndoverlay(x,y, group='Example', label='Test')
```

Or something like this for curves:

```python
Curve.ndoverlay(x,y, group='Example', label='Test')
```

The basic reasoning is as follows:

* ``NdOverlays`` only support collections of one type so having a class method on the relevant ``Element`` classes seems reasonable.
* Although the constructor of an individual element may expect input (typically a numpy array) of a certain format, such a class method could unpack a condensed representation of multiple elements into the appropriate ``NdOverlay`` for you.
* The class method could support multiple popular formats for specifying collections of elements without changing any part of the overall design.

Alternatively, maybe there is only one such a class method that exists on ``NdOverlay`` that takes the element type as an argument. The problem with this will necessarily be more verbose as a result and I am not sure how you could make such a method general enough to handle all the possible elements.

Thoughts?

**Comment by basnijholt** [comment]
@philippjfr they don't need to be different colours, usually I make them all black, but I wanted to give a minimal example.  

The class methods sounds like a reasonable implementation.

**Comment by jlstevens** [comment]
In the new issue referenced above (#102) I lay out some plans to make ``Contours`` more versatile. This may go some way towards alleviating this problem (i.e there would be no more need for an ``NdOverlay``) but it won't *necessarily* support the convient interface you are looking for. 

For this reason, I think these are still two separate (although related) issues for the time being.

**Comment by basnijholt** [comment]
Ah, by doing: ``hv.Contours([zip(x, y[:,i]) for i in range(y.shape[1])])``? Or can it be done more easily?

**Comment by philippjfr** [comment]
While we do want to make changes to Contours if you don't want different styles for each of the Contours anyway we'd suggest simply using a Path Element, both Path and Contours Elements support lists of Nx2 np.arrays. Taking your example from above you can do:

```
eigenvals = np.array([np.linalg.eigvalsh(H1 * alpha + H2 * (1 - alpha)) for alpha in x])
hv.Path([np.vstack((x, eigenvals[:, i])).T for i in range(eigenvals.shape[1])])
```

We could consider supporting a tuple of x-values and matching y-values of matching shape in the constructor of Path, which is then automatically expanded to the list format. Then you could just do

```python
x = np.linspace(0, 1, 100)
eigenvals = [np.linalg.eigvalsh(H1 * alpha + H2 * (1 - alpha)) for alpha in x]
hv.Path((x, eigenvals), label='Example')

**Comment by jlstevens** [comment]
I agree that from the sound of it, the ``Path`` element would suit you best. 

Philipp's suggestion of accepting two numpy arrays in a tuple (i.e ``(x,y)`` arrays) in the constructor of ``Path`` seems reasonable and very easy to implement.

**Comment by basnijholt** [comment]
The matching of x-values to the shape of y-values sounds like a great solution. 

``hv.Path((x,y))`` is short enough :)

**Comment by philippjfr** [comment]
I've implemented my suggestion from above and @jlstevens  has added #102 to detail the improvements we have in mind for Contours, so I think I can close this one now.

**Comment by jbednar** [comment]
Please put an example of the new functionality in the tutorials, since if this is something matplotlib plot() supports easily, lots of other people may be relying on it as well and get similarly frustrated.
