### ISSUE TITLE
Feature request: Topological Data Analysis for High dimensional data

### ISSUE THREAD

**Issue by datnamer** [ioam/holoviews#1000]
Pursuant to Holoviews mandate to provide general tools to obtain insight on high dimensional data sets, I think TDA would be a great addition. 

Intro: http://www.slideshare.net/paul_kyeong/topological-data-analysis-with-examples

More:
http://blog.revolutionanalytics.com/2014/01/topological-data-analysis-with-r.html
http://www.ayasdi.com/blog/bigdata/why-topological-data-analysis-works/

Code:
https://github.com/rosinality/knotter (MIT and responsive dev)
http://danifold.net/mapper/legal.html (GPL)
https://github.com/stephenhky/PyTDA

Opened a bokeh issue here: https://github.com/bokeh/bokeh/issues/3049

**Comment by jbednar** [comment]
HoloViews isn't normally meant to be a complete data analysis toolkit, but instead a way of working with your data that is instantly visualizable and can easily be transformed into other visual representations.  It sounds to me like TDA would be best implemented as a toolkit that is built on top of HoloViews, making it simple to build HoloViews objects that show the results of various types of analyses.  It's likely that some new HoloViews Elements would be needed along the way, but those should be easy to add where they are needed, and those could become part of HoloViews itself if appropriate (but can still be developed outside of HoloViews in this separate project just as easily).  So I personally would be happy to see a toolkit like this developed, but wouldn't see it as part of the main HoloViews library.

**Comment by jbednar** [comment]
You could also consider contributing a HoloViews interface to an external tool like the ones that you listed, which would allow those tools to generate HoloViews objects that people can use alongside the ones provided by HoloViews itself.

**Comment by jlstevens** [comment]
@datnamer Thanks for the references!  I hadn't heard of Topological Data Analysis before but it does look interesting.

I agree with @jbednar here: this work could definitely be done with HoloViews by adapting the appropriate python analysis package (i.e one that outputs suitable HoloViews objects).

In particular, it looks like lots of graphs are involved with this particular technique and although this type of visualization is already possible using paths and markers, it would probably be better handled by something like [networkx](https://networkx.github.io/). I prototyped a very simple HoloViews networkX in the past - perhaps something like that could help support running TDA with HoloViews in future?

**Comment by datnamer** [comment]
Ah ok. I understand.

**Comment by philippjfr** [comment]
I remember reading about TDA a while ago and it's definitely very interesting. As the others have indicated this isn't something that's going to make it into the core of HoloViews. The way I see it the another library should output networkx graphs, which can then be displayed in HoloViews. Here's a small (and very simplified) example of how a NetworkX HoloViews interface might look like: https://anaconda.org/philippjfr/network-x/notebook

**Comment by philippjfr** [comment]
I'm going to close this as being outside of the scope of core holoviews.

**Comment by philippjfr** [comment]
Note that there is now a nice Python implementation of these methods called [KeplerMapper](https://github.com/MLWave/kepler-mapper), I'm going to reopen because we could leverage in combination with our graph support.

**Comment by philippjfr** [comment]
Closing again since it's definitely out of scope but could be included in an extension library.

**Comment by jbednar** [comment]
I agree -- with our graph support something like this could very nicely be built on HoloViews, but shouldn't be part of the library itself.

**Comment by jbednar** [comment]
This looks like a great library for TDA: https://github.com/scikit-tda/scikit-tda

From what I can see at the SciPy 2019 talk about it, all of the plots involved can easily be generated with HoloViews, which would help make the Scikit-TDA plotting and exploration much more powerful.
