### ISSUE TITLE
Text annotation silently breaks y axis limits

### ISSUE THREAD

**Issue by llvilanova** [ioam/holoviews#1002]
Hi! I just took the second Bars example in [1] (the one with stacked bars) and added a text annotation at the end (`hv.Bars(...) * hv.Text(1, 10, "test")`). Unexpectedly, adding that annotation cuts the bars Y axis limit down to 10 (the Y position for the annotation), instead of keeping it at 120.

[1] http://holoviews.org/Tutorials/Elements.html#Bars

**Comment by jlstevens** [comment]
Thanks for reporting this!

I think it is a bug - annotations should not affect the plotted extents when they are overlaid on top of non-annotation elements. This would stop the addition of ``Text`` from affecting the y-axis.

**Comment by philippjfr** [comment]
This is probably related to the fact that the Bars x-coordinates are treated as categorical values, which causes various issues when overlaying them. There is an existing issues about adding categorical support for axes and cmaps which would address this: https://github.com/ioam/holoviews/issues/582

It's probably also worth considering whether there is something simple we can do in the meantime.

**Comment by philippjfr** [comment]
Cannot reproduce this anymore.
