### ISSUE TITLE
Check matplotlib 2.0 compatibility

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#1006]
Since matplotlib 2.0rc1 has been released we should check our compatibility and start on our own style overhaul.

**Comment by jlstevens** [comment]
I've assigned myself as I am happy to check  - not promising to fix anything though! ;-p

**Comment by jlstevens** [comment]
I've created a conda env with matplotlib 2.0.0rc2 and the new holoviews dev release (dev4) to see what happens. I'll post a zip archive of notebook snapshots for you to look at in a bit.

Skimming through the Element tutorial, I don't see too many problems! Here is what I did spot:

![image](https://cloud.githubusercontent.com/assets/890576/21853474/2b7ab322-d80f-11e6-8250-27adc6b03ffc.png)

(Problems with ErrorBars)

![image](https://cloud.githubusercontent.com/assets/890576/21853290/6e4d7a64-d80e-11e6-830e-fbb1d1297a3e.png)

(Appearance of Viridis)

![image](https://cloud.githubusercontent.com/assets/890576/21853568/92a62c2a-d80f-11e6-8ded-69da728bf553.png)

(Minor style changes for the 3D elements - namely the white outlines)

![image](https://cloud.githubusercontent.com/assets/890576/21853307/8334907a-d80e-11e6-846f-955d839f3faf.png)

(Warnings for HeatMap)

![image](https://cloud.githubusercontent.com/assets/890576/21853434/04294b62-d80f-11e6-863b-a0e125b13314.png)

(Some style changes for BoxWhisker)

![image](https://cloud.githubusercontent.com/assets/890576/21853670/ec1985ae-d80f-11e6-96df-2d0863058b4d.png)

(Font changes in tables)

The biggest issue so far seems to be the broken errorbars...

**Comment by jlstevens** [comment]
Matplotlib 2 is an improvement on the Hompage. You can see the legend better:

<img src="https://cloud.githubusercontent.com/assets/890576/21853866/9dc12ea6-d810-11e6-843d-55cc9e6f29f1.png" width="300px;"/>

Instead of:

<img src="https://cloud.githubusercontent.com/assets/890576/21854022/25be2782-d811-11e6-9df4-384951a51a99.png" width="300px;"/>

**Comment by jlstevens** [comment]
No issue with the containers tutorial except for #1052 which isn't related to the matplotlib version.

**Comment by jlstevens** [comment]
DynamicMap tutorial seems fine except for #1053 which is unrelated to matplotlib.

**Comment by jlstevens** [comment]
Couldn't spot any issues with the Exploring_Data tutorial...

**Comment by jlstevens** [comment]
The "Introduction", "Showcase", "Composing_Data", "Columnar_Data" and "Continous_Coordinates" tutorials seem fine too. 

In Introduction, there is the same change to a grey legend background as shown above for Homepage...

**Comment by jlstevens** [comment]
In Sampling Data, the point colors have changed:

![image](https://cloud.githubusercontent.com/assets/890576/21855651/165727a2-d817-11e6-8f16-3545a80c0ffb.png)

The "Options" and "Pandas Conversion" tutorials seem to be unchanged. I was surprised nothing changed in "Pandas Seaborn"! I spotted one difference but that is down to a change in HoloViews:

![image](https://cloud.githubusercontent.com/assets/890576/21855858/c57e5930-d817-11e6-9e27-e0ee228e928c.png)

The legend box outline is not on holoviews.org but is there on dev.holoviews.org.

**Comment by jlstevens** [comment]
That concludes my investigation of matplotlib 2.0.0rc2. We will need some PRs to fix some of the issues mentioned above, but overall it looks like not too much has changed (thankfully!). I suppose there may be lots of changes to the defaults in matplotlib 2 but we seem to keep our options under fairly tight control. :-)

**Comment by philippjfr** [comment]
Thanks for doing this, I'll summarize the issues:

* Need to fix ErrorBars
* Ensure Points has default cmap (as part of https://github.com/ioam/holoviews/pull/748)
* Figure out why HeatMap is raising NaN warnings. Have to pass masked array?
* Investigate why Scatter3D point coloring changed

**Comment by vascotenner** [comment]
There are some more api changes http://matplotlib.org/api/api_changes.html, including:

* The axisbg and axis_bgcolor properties on Axes have been deprecated in favor of facecolor.

This is used in two files:
* holoviews/plotting/mpl/element.py
* holoviews/plotting/mpl/chart3d.py

Currently, using  axis_bgcolor raises a userwarning (which is how I found this).

**Comment by philippjfr** [comment]
Perfect thanks @vascotenner. Should be a quick fix by whomever wants to do it. 

One other thing I've noticed that setting up ticks fails in some cases because we're not setting a dpi value on the figure until it's rendered. At least three of our unit tests are affected.

**Comment by philippjfr** [comment]
Remaining issues are:

* For some reason there are a lot of aspect warnings raised, these should be suppressed.
* Some tests are failing because no dpi is set
* spectral colormap is raising warnings
* as mentioned by @vascotenner ``bgcolor`` is now ``axis_bgcolor``

**Comment by philippjfr** [comment]
Final issues have been addressed, please reopen if any other warnings or issues crop up.
