### ISSUE TITLE
Bars breakdown with "incremental" values

### ISSUE THREAD

**Issue by llvilanova** [ioam/holoviews#1024]
I have some results with three "dimensions": benchmark, tool, part.

I want to plot bars grouped by benchmark and tool, and show a breakdown for each of the "parts" for each benchmark. The "part" results are incremental, in the sense that one part is program initialization, the other initialization + foo, and then initialization + foo + bar.

If we assume values 1, 2 and 3 for each part, using ``hv.Bars`` as in the tutorial plots a bar breakdown from 0 to 1 for the first part, 1 to 3 for the second. and 3 to 6 for the third, whereas I want each part to be 0-1, 1-2, 2-3.

If I instead use an overlay of a ``hv.Bars`` for each part, the bars have the right height but all have the same color and there is no legend for the part breakdown.

**Comment by philippjfr** [comment]
Sorry I never responded to this, without a minimal reproducible example it's very hard to address issues like this. It's also not clear to me whether you're referring to bokeh or matplotlib. The matplotlib implementation is very poorly implemented and doesn't match the bokeh version, which is on my roadmap to fix.

**Comment by philippjfr** [comment]
I'd encourage you to raise any issues in https://github.com/ioam/holoviews/issues/1407, I'll close this issue for now.
