### ISSUE TITLE
holoviews/geoviews notebook extension problem

### ISSUE THREAD

**Issue by khannaum** [ioam/holoviews#1028]
### When notebook extension is matplotlib values in holoviews table changes on selection
![image](https://cloud.githubusercontent.com/assets/7712413/21490499/f87361d0-cc16-11e6-993d-94e1562fd024.png)

### When notebook extension is bokeh and matplotlib, values in holoviews table does not changes and only geoviews points values changes . Help required  holoviews table and geoviews points values both changes upon selection.

![image](https://cloud.githubusercontent.com/assets/7712413/21490682/84a5f5fe-cc18-11e6-82f6-524311cee509.png)

**Comment by philippjfr** [comment]
Could you report the versions of holoviews and geoviews you are using. We fixed various issues with bokeh tables in https://github.com/ioam/holoviews/pull/851, so try updating to current master. Hopefully we'll have a new release with these fixes very soon.

**Comment by khannaum** [comment]
>>> holoviews.__version__
1.6.2
>>> import geoviews
>>> geoviews.__version__
1.1.0

**Comment by philippjfr** [comment]
As I indicated this has been fixed in master. You can either install holoviews and geoviews master straight from GitHub or install the latest dev releases with:

```
conda install -c ioam/label/dev holoviews geoviews
```

Hopefully we'll have a new release soon. I'll close the issue but if you need more assistance let me know.

**Comment by khannaum** [comment]
Now i install dev releases from above command and following error occurs.

![image](https://cloud.githubusercontent.com/assets/7712413/21599919/fa66cad4-d195-11e6-9aca-0bfe958744d2.png)

![image](https://cloud.githubusercontent.com/assets/7712413/21599925/143f4ada-d196-11e6-9c02-403f04d01777.png)


![image](https://cloud.githubusercontent.com/assets/7712413/21599931/3179b9fa-d196-11e6-8689-1f6e47c58d09.png)

![image](https://cloud.githubusercontent.com/assets/7712413/21599938/7494651e-d196-11e6-9f38-e6cef9113d93.png)
Suddenly 
![image](https://cloud.githubusercontent.com/assets/7712413/21599948/b957c02e-d196-11e6-8ba4-7f7a12e69457.png)

Kindly help

**Comment by philippjfr** [comment]
That looks correct to me. What version of bokeh are you on? It's possible you'll have to upgrade to 0.12.3.

**Comment by khannaum** [comment]
ok i will try

**Comment by khannaum** [comment]
Yes it works thanks for the support. Kindly guide how to enable save option on bokeh panel. As i am unable to save manually.

![image](https://cloud.githubusercontent.com/assets/7712413/21608519/cc3477b2-d1de-11e6-8725-df9cf99cadc8.png)

**Comment by philippjfr** [comment]
>Kindly guide how to enable save option on bokeh panel. As i am unable to save manually.

What exactly do you mean? Bokeh currently only supports manual export of plots using the save button in toolbar and even that only exports each plot individually as a png.

**Comment by khannaum** [comment]
Yes when i click to save option it some time allows and some time doesnot.
I want to ask where in bokeh it is enabled or disabled. because i does not
find in bokeh documentation.

**Comment by jbednar** [comment]
If the save icon is visible in the toolbar but it doesn't actually do anything, that would be a problem with Bokeh rather than with HoloViews.  If you are filing an issue with Bokeh about that, I'd recommend trying to reproduce the problem using one of the examples on the [bokeh site](http://bokeh.pydata.org/en/latest/docs/gallery.html), as the Bokeh maintainers do not generally work with HoloViews.
