### ISSUE TITLE
KeyError: none on import

### ISSUE THREAD

**Issue by brianmingus** [ioam/holoviews#1031]
```python3
import holoviews as hv
hv.notebook_extension(bokeh=True)
```

error: https://gist.github.com/brianmingus/0ac14c3feec1daf26c4da2a67d032c00

**Comment by brianmingus** [comment]
HoloViews 1.6.2, param 1.3.2, bokeh 0.12.3

**Comment by brianmingus** [comment]
Same error with bokeh, matplotlib and plotly backends.

**Comment by brianmingus** [comment]
Same error with:

```
%load_ext holoviews.ipython
%output backend='d3' holomap='widgets' size=75 dpi=150
```

**Comment by brianmingus** [comment]
This is due to using mpld3 independently in the Jupyter notebook. Restarting the kernel fixed. Closing.

**Comment by jlstevens** [comment]
Glad you managed to resolve this issue!

It might still be good to know about any bad interaction between HoloViews and other mpld3 usage. The error you reported sounds like HoloViews couldn't load the expected backend - I'm wondering if there might be a real issue for us to fix here.
