### ISSUE TITLE
Ensure arbitrary adjoined elements render correctly in matplotlib

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#1033]
Currently you can adjoin any element type to another and at least in bokeh they will render correctly in general. However in matplotlib the dimensions of the adjoined plots will often be wrong due to issues with aspects. Additionally many matplotlib plots do not correctly support ``invert_axes``, which leads to the data being plotted incorrectly in those cases. These two issues should be addressed.

**Comment by jbednar** [comment]
Will that require changes in matplotlib itself?  If so may be worth opening an issue there now so that they are aware of it, even if we don't plan to work on it at our end right away.

**Comment by philippjfr** [comment]
No, I think this will just require going through all matplotlib plotting classes and making sure that it behaves correctly when adjoined.

**Comment by jbednar** [comment]
How will that help fix ``invert_axes``?

**Comment by philippjfr** [comment]
The plotting classes should invert the data appropriately so ``invert_axes`` is respected.
