### ISSUE TITLE
Opts parser 0.5 vs .5

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#1035]
Works ```%%opts HLine (linewidth=1, color=(1,1,1,0.5))```
Not Works ```%%opts HLine (linewidth=1, color=(1,1,1,.5))```

```
ValueError: to_rgba: Invalid rgba arg "(1, 1, 1.5)"
number in rbg sequence outside 0-1 range
```

**Comment by jlstevens** [comment]
Thanks for reporting this! 

I wouldn't have noticed it myself as I am not used to using the .x float syntax...

**Comment by philippjfr** [comment]
Described this in the general issue about parser issues. Closing.
