### ISSUE TITLE
Support for bokeh tick formatters in Dimension value_format

### ISSUE THREAD

**Issue by jordansamuels** [ioam/holoviews#1039]
Discussed with @philippjfr on gitter.  Example use case is: x-axis = nanoseconds since epoch, and similar to (https://github.com/bokeh/datashader/blob/master/examples/tseries.ipynb), do ...

    formatter = DatetimeTickFormatter(formats = dict(
        microseconds=['%fus', '%H:%M %3fus', '%F %H:%M %3fus'],
        milliseconds=['%S.%3Ns', '%H:%M %3Nms', '%F %H:%M %3Nms'],
        seconds=['%Ss'],# '%H:%M:%S'],
        minsec=[':%M:%S', '%H:%M:%S'],
        hours=['%H:%M', '%F %H:%M'],
        days=['%F']))

    time_dim = hv.Dimension("Time", value_format=my_formatter, type=int)

**Comment by philippjfr** [comment]
Nothing ever happened with this because despite my comments before Dimension value_format will never accept a bokeh formatter since that breaks the fundamental assumption that the formatter can be applied in pure Python as well.

Closing in favor of https://github.com/ioam/holoviews/issues/2323.
