### ISSUE TITLE
Introduce standard point for enabling/disabling features

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#1041]
It would be good to have a convenient place to enable/disable particular holoviews features. This would help by allowing us to encourage uses to use new behavior (for instance the recently enabled changes to layouts) before they are on by default or to re-enable old behaviors for backwards compatibility.

This system should be tied to versions in some way. I've not thought through the API yet, but something like:

```python
hv.enable('1.6') # Enable legacy features from 1.6
hv.enable('1.8') # Enable available future defaults in 1.8
hv.enable({'1.6':['layout'], '1.8':['options_propagation']})
```
Maybe calling ``hv.enable()`` (i.e without arguments) could print a list of options to enable/disable. I think it would be good to introduce this system for 1.7.

**Comment by philippjfr** [comment]
Agree with the overall proposal, not entirely happy with ``hv.enable`` though. Don't think it needs to be in the top-level namespace and ``enable`` doesn't really say much. Think I would prefer something like ``hv.Store.legacy``.

**Comment by jlstevens** [comment]
I'm not particularly attached to the name ``enable`` but I do feel it should be in the top-level namespace as it applies settings that affect the whole project.

**Comment by jbednar** [comment]
This does seem like a top-level concept to me.

**Comment by philippjfr** [comment]
Sure, I'm overruled :smile:

**Comment by jlstevens** [comment]
Ok, any suggestions for the name of this thing?

**Comment by jbednar** [comment]
``hv.feature``?

**Comment by jlstevens** [comment]
I suppose a ``Feature`` could be some sort of fancy element, but as it is lower case, that isn't an issue. I would make it plural though so maybe ``hv.features``?

Even then I'm not 100% convinced as it sounds like it is enabling/disabling features whereas it is more about enabling/disabling versions of various features. Need to think about it more.

**Comment by jlstevens** [comment]
How about ``hv.config``? 

I quite like this as I can't think of anything else we want to configure other than backwards compatibility settings - everything notebook specific is done by the notebook extension.

**Comment by jbednar** [comment]
Fine by me.

**Comment by philippjfr** [comment]
Same here, ``hv.config`` seems fine.

**Comment by philippjfr** [comment]
This has now been added, closing.

**Comment by jlstevens** [comment]
Just to keep a record, ``hv.config`` was introduced in #1518.
