### ISSUE TITLE
cbar_ticks not working properly

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#1044]
cbar_ticks is not working properly:

```
img = hv.Image(np.random.rand(10,10))
```

Colorbar from 0 to 1
```
%%opts Image [xticks=3, colorbar=True]
img
```
![download](https://cloud.githubusercontent.com/assets/3776190/21814136/9c8d7fa2-d758-11e6-9c33-20b474b98286.png)

Now the labels are wrong:
```
%%opts Image [xticks=3, colorbar=True, cbar_ticks=2]
img
```
![download 1](https://cloud.githubusercontent.com/assets/3776190/21814166/ad5f06de-d758-11e6-84d4-5fc980e5e0d9.png)

Tries with supplying cbar_ticks a list with values, or a list with key,value pairs did not work as expected (strange results).

**Comment by philippjfr** [comment]
Not sure what did it but this appears to be fixed:

![bokeh_plot](https://user-images.githubusercontent.com/1550771/49051959-d77c8e00-f1e1-11e8-956d-8c77113517d3.png)
