### ISSUE TITLE
HoloMap issue in Containers tutorial

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#1052]
In the [Containers tutorial](holoviews.org/Tutorials/Containers.html) the frequency slider only does anything for phase=0:

![image](https://cloud.githubusercontent.com/assets/890576/21854536/f979812e-d812-11e6-8703-0017f8fa80ad.png)

Nothing updates if you try to use a non-zero phase. Maybe this is a floating point comparison issue?

**Comment by philippjfr** [comment]
So this is pretty odd, the precision of the key matching is currently set to 11 decimal places while the JS code is using 10 decimal places. Not quite sure how anything has been working, but setting it to 10 in Python seems to work.

**Comment by jlstevens** [comment]
Any mismatch seems problematic and I am also surprised anything worked! Is it possible to make this precision a global variable so we can make sure it stays matched between Python and JS?

**Comment by philippjfr** [comment]
Turned out to be my fault, I introduced a fix in Python to fix rounding outside the defined range on a DynamicMap (remember the issues with ``pi``), which wasn't mirrored on the JS end. Haven't worked out the correct fix yet though, as I suspect my approach to that issue was generally flawed.

**Comment by philippjfr** [comment]
Fixed in the PR referenced above.
