### ISSUE TITLE
`hv.help` ignores `hv.notebook_extension('bokeh')`

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#1057]
When working with the `bokeh` backend enabled by `hv.notebook_extension('bokeh')` calling `hv.help` shows me information about `matplotlib`.

**Comment by jlstevens** [comment]
This behavior is being fixed by #1051. I'll close this issue once that PR is merged.

**Comment by philippjfr** [comment]
Now merged and fixed, closing.
