### ISSUE TITLE
Rename mdims argument on .to method to groupby

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#1061]
The term ``mdims`` doesn't mean much and is not well defined, renaming this argument of the conversion interface to ``groupby`` would, I think, make it much clearer what it actually does.

I just started writing a gridded dataset tutorial and it struck me that this would be much clearer:

```python
dataset3d.to(hv.GridImage, kdims=['y', 'z'], vdims='Value', groupby='x')
```

than

```python
dataset3d.to(hv.GridImage, kdims=['y', 'z'], vdims='Value', mdims='x')
```

**Comment by philippjfr** [comment]
``mdims`` would of course go through a deprecation cycle.

**Comment by jlstevens** [comment]
I agree the ``groupby`` is a clearer name.

**Comment by philippjfr** [comment]
Now done.
