### ISSUE TITLE
Links on http://holoviews.org/Tutorials/Transforming_Data.html are broken

### ISSUE THREAD

**Issue by jordansamuels** [ioam/holoviews#1077]
http://holoviews.org/Tutorials/Transforming_Data.html has two broken links, for http://holoviews.org/Tutorials/Sampling_Data and http://holoviews.org/Tutorials/Exploring_Data .

**Comment by jordansamuels** [comment]
Note that http://holoviews.org/Tutorials/Transforming_Data.html is linked twice from http://holoviews.org/features.html .

**Comment by jlstevens** [comment]
Thanks for reporting this!

I'll assign myself to fix it.

**Comment by philippjfr** [comment]
Might be worth discussing what the Transforming Data tutorial should actually contain or whether we should just remove it entirely.

**Comment by jlstevens** [comment]
Addressed in the PR referenced above.

**Comment by jordansamuels** [comment]
Thanks guys!
