### ISSUE TITLE
Update FAQ example using Renderer

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#1078]
As described in http://stackoverflow.com/questions/41833766/how-to-use-a-matplotlib-backend-in-holoviews/41834171, the FAQ example should mention that you have to import the backend manually.

**Comment by jlstevens** [comment]
The 'having to import from plotting' to enable the backend thing has always bothered me a bit. The problem is I can't see a good alternative...

**Comment by jlstevens** [comment]
The new advice will be to simply use ``hv.renderer`` as that will do the import automatically and is much easier.

**Comment by jlstevens** [comment]
Address in the PR referenced above (#1586)
