### ISSUE TITLE
xextents of overlay of raster and HLine

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#1079]
When drawing a line outside the extents of an Raster/Image, the extents of the overlay grow such that the line is also visible.

**Works for VLine**
```hv.Raster(np.random.rand(100,100))*hv.VLine(x=120)```
![download](https://cloud.githubusercontent.com/assets/3776190/22283473/c2202b9e-e2e2-11e6-83a3-e3d0babc1abb.png)

**Does not work for HLine: xaxis extended instead of yaxis**
```hv.Raster(np.random.rand(100,100))*hv.HLine(y=120)```
![download 1](https://cloud.githubusercontent.com/assets/3776190/22283475/c4009a2a-e2e2-11e6-9d6c-71c74904ee5f.png)

**Comment by jlstevens** [comment]
Definitely seems to be a bug. Thanks for reporting this.

**Comment by philippjfr** [comment]
It seems the HLine and VLine plots classes have never implemented a custom ``get_extents`` method. Should be trivial to implement one.

**Comment by philippjfr** [comment]
Actually had we not decided that certain annotations should not be considered when computing the bounds? If that regressed then that would explain why we hadn't noticed this before.

**Comment by jlstevens** [comment]
We did discuss it before but I can't remember what we decided. Personally I would quite like for annotations to be included in the bounds calculation but there could be a good reason not to. I don't mind either way as long as we are consistent.

**Comment by jbednar** [comment]
There is certainly an argument for not considering line annotations when computing the bounds (though of course it would need to be both types of such annotations).  E.g. one may want to provide a red line to mark a danger threshold, and as long as that threshold is never reached, there's no reason to enlarge the display to include it.  But there are also other cases when one might want to include the location of the annotation, so maybe there should be a configuration option to determine whether annotations affect the extents.
