### ISSUE TITLE
Cycle is broken for Overlay

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#1081]
This used to work in v1.4.3
```
%%opts Curve (color=Cycle(values=['r', 'g', 'b', 'y']))
plot = [hv.Curve(np.random.rand(10)) * hv.HLine(0) for i in range(4)]
plot = hv.Overlay(plot)
plot
```

![download](https://cloud.githubusercontent.com/assets/6897215/22300838/1d89308e-e329-11e6-97c8-401a24c5450f.png)

However this:
```
%%opts Curve (color=Cycle(values=['r', 'g', 'b', 'y']))
plot = (hv.Curve(np.random.rand(10)) * hv.HLine(0) * 
        hv.Curve(np.random.rand(10)) * hv.HLine(0) *
        hv.Curve(np.random.rand(10)) * hv.HLine(0) *
        hv.Curve(np.random.rand(10)) * hv.HLine(0))
plot
```
produces:
![download 1](https://cloud.githubusercontent.com/assets/6897215/22300913/564c9906-e329-11e6-87dd-fe242632ed99.png)

**Comment by philippjfr** [comment]
This is high priority, I'll investigate tomorrow.

**Comment by philippjfr** [comment]
This seems pretty bad and I don't know how this hasn't gotten caught sooner. In 1.4.3 this:

```python
elements = [hv.Curve(np.random.rand(10)) * hv.HLine(0) for i in range(4)]
overlay = hv.Overlay(elements)
print(repr(overlay))
```

produces this:

:Overlay
   .Curve.I   :Curve   [x]   (y)
   .HLine.I   :HLine   [x,y]
   .Curve.II  :Curve   [x]   (y)
   .HLine.III :HLine   [x,y]
   .Curve.III :Curve   [x]   (y)
   .HLine.IV  :HLine   [x,y]
   .Curve.IV  :Curve   [x]   (y)
   .HLine.V   :HLine   [x,y]

In 1.7 it produces this:

```python
:Overlay
   .Overlay.I   :Overlay
      .Curve.I :Curve   [x]   (y)
      .HLine.I :HLine   [x,y]
   .Overlay.II  :Overlay
      .Curve.I :Curve   [x]   (y)
      .HLine.I :HLine   [x,y]
   .Overlay.III :Overlay
      .Curve.I :Curve   [x]   (y)
      .HLine.I :HLine   [x,y]
   .Overlay.IV  :Overlay
      .Curve.I :Curve   [x]   (y)
      .HLine.I :HLine   [x,y]
```

Somewhere along the line we broke how Overlays are nested 😱 I'll have to bisect tomorrow to see when this happened.

**Comment by philippjfr** [comment]
```python
2e801dabdc730f969734026f7dbccf664cad6c5f is the first bad commit
commit 2e801dabdc730f969734026f7dbccf664cad6c5f
Author: Philipp Rudiger <P.Rudiger@ed.ac.uk>
Date:   Wed Oct 26 00:07:42 2016 +0100

    Reimplemented Layout.from_values
```

**Comment by jlstevens** [comment]
Ah right..because ``Overlay`` inherits from ``Layout``. And it has been this way since the 26th of October! At least it is not an issue that made it into any non-dev release...

**Comment by philippjfr** [comment]
Finally fixed! Closing.
