### ISSUE TITLE
proxy setting  for download WMTS element in python program

### ISSUE THREAD

**Issue by khannaum** [ioam/holoviews#1095]
Kindly guide where to set the proxy setting in python program to load WMTS element,

**NoteBook:**
windows 64bit
SET http_proxy="proxy address"
SET https_proxy="proxy adress"
jupyter notebook
on notebook WMTS load easily it works fine

but it does not load WMTS elements directly from same python program
windows 64bit
SET http_proxy="proxy address"
SET https_proxy="proxy address"

python my_program.py
raise SkipRendering("No valid tile source URL found in WMTS "

SkipRendering: No valid tile source URL found in WMTS Element, rendering skipped.

**Comment by jbednar** [comment]
Closing in favor of [similar issue opened on GeoViews site](https://github.com/ioam/geoviews/issues/46).
