### ISSUE TITLE
holoviews bokeh backend broken with latest bokeh==0.12.4

### ISSUE THREAD

**Issue by blake-riley** [ioam/holoviews#1096]
I installed holoviews and bokeh through pip, which delivers the latest versions (1.6.2, and 0.12.4 respectively).
When holoviews is loaded with the bokeh backend, a simple sine-curve example from the docs crashes.
I have included the code and Jupyter notebook output below.

The fix: when I force pip to install `bokeh==0.12.3`, everything works as expected.

Bokeh [mentions that their API may have breaking changes](http://bokeh.pydata.org/en/latest/docs/releases/0.12.4.html) as they approach v1.0. It seems that you may be aware of the change (through #1036), and because the Travis build environment has fixed the version (in the `conda create` command) to `bokeh=0.12.3`.

I just wanted to make you aware of an issue that is apparent through current pip installs.
Perhaps a warning to users of holoviews could be added on `hv.notebook_extension('bokeh')`? Or perhaps a minor version bump to PyPI is imminent that includes #1036 (I believe this actually addresses the root cause of the problem)?

--

MWE:
```python
import holoviews as hv
hv.notebook_extension('bokeh')

>>> HoloViewsJS, BokehJS successfully loaded in this cell.
```

```python
points = [(0.1*i, np.sin(0.1*i)) for i in range(100)]
hv.Curve(points)

>>> AttributeError [Call holoviews.ipython.show_traceback() for details]
'Line' object has no attribute 'set'
```

Checking the traceback for more detail, I get:

```python
hv.ipython.show_traceback()

Traceback (most recent call last):

  File "~/.virtualenvs/py34/lib/python3.4/site-packages/holoviews/plotting/bokeh/element.py", line 511, in initialize_plot
    with abbreviated_exception():

  File "~/.virtualenvs/py34/lib/python3.4/site-packages/holoviews/plotting/bokeh/element.py", line 468, in _update_glyph
    print("Glyph Type: ", type(glyph))

AttributeError: 'Line' object has no attribute 'set'
```

**Comment by philippjfr** [comment]
We fixed this issue on master a while back. I'd suggest either downgrading to bokeh 0.12.3 for now or upgrading to holoviews master or one of the recent dev releases. We're also hoping to have a holoviews 1.7 release later this month.

**Comment by philippjfr** [comment]
Going to close this, since it is fixed in master.
