### ISSUE TITLE
Reenable some form of option validation

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#1101]
At some point we decided to remove validation for options that do not exist to make the transition between plotting backends less painful, however in the process we removed all validation whatsoever, in other words when I do this:

```python
%%opts Curve [xaxes=None foo=True bar=False]
hv.Curve(range(10))
```

I get no warning that none of those options apply whatsoever. What I would like to see is for it to search for the options on all available backends and warn when it doesn't match anything. Ideally we'd also have some form of fuzzy matching that suggests similar options when you misspell something, but that's an orthogonal issue.

**Comment by jlstevens** [comment]
I've assigned myself - it shouldn't be too hard to do but I'm not promising anything about the fuzzy matching option! For general fuzzy matching, you tend to need a 3rd party lib from what I've seen in other projects...

**Comment by philippjfr** [comment]
>For general fuzzy matching, you tend to need a 3rd party lib from what I've seen in other projects...

True, bokeh's fuzzy matching seems to work well but I haven't looked into what they are using.

**Comment by jlstevens** [comment]
Addressed in the PR referenced above.
