### ISSUE TITLE
Parser and divide

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#1105]
In python 2, the division of two integers leads to a new integer. In python three, this is relaxed (will yield float). This behaviour can be used in python2 also. However, the optspec parser does not do this:

```python
from __future__ import division
assert 0.75 == 3/4

%%opts Raster [aspect=3/4]
hv.Raster(np.random.randint((10,20))
```

Gives ```ZeroDivisionError```

**Comment by philippjfr** [comment]
Agreed, the parser module should simply import ``from __future__ import division``.

**Comment by jlstevens** [comment]
This has been fixed in the PR reference above. I'll close this issue once it is merged.

**Comment by jlstevens** [comment]
The PR has been merged.
