### ISSUE TITLE
holoviews.operation.ElementOperation.__call__ overwrites labels and groups for HoloMaps

### ISSUE THREAD

**Issue by drs251** [ioam/holoviews#1106]
When passing a `HoloMap` to an `ElementOperation`, the group and label are replaced with the one of the first contained `Element`, e.g. you get "Curve" as your group, if the Curves in the `HoloMap` have not been assigned a custom group.

**Comment by philippjfr** [comment]
A PR to fix this issue would be very much appreciated, this is clearly bad behavior and I see it all the time.

**Comment by philippjfr** [comment]
The fix has been merged.
