### ISSUE TITLE
setting clims forces colorbar with hat

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#1109]
When an image is plotted, with values that are not within the clims, the colorbar show a little hat on top/bottom.

However, when setting the ```clims``` to ```(None,None)```, the clims should be determined automatically and no hat should be shown:

**Works**
```
%%opts Image [colorbar=True]
tmp = np.random.rand(10,10)
tmp /= tmp.max()
hv.Image(tmp)
```
![download](https://cloud.githubusercontent.com/assets/3776190/22749564/142e74b2-ee2e-11e6-838d-134a1d775ec7.png)

**Works not**
```
%%opts Image [colorbar=True] (clims=(None,None)) 
hv.Image(tmp)
```
![download 1](https://cloud.githubusercontent.com/assets/3776190/22749567/15bf9d60-ee2e-11e6-9dad-b2b35c17f28c.png)

**Comment by philippjfr** [comment]
Fixed in #1211.
