### ISSUE TITLE
Toggle between value dimensions on HeatMap

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#1114]
Since HeatMaps can now have multiple value dimensions, which can currently only be revealed with a hover tool, I've got a suggestion for making it more flexible. The idea would be that when a HeatMap with multiple value dimensions is instantiated it will automatically add toggle buttons to the plot which lets the user switch between the different value dimensions. This could be implemented entirely as JS callback and therefore would work fine on static plots. Here's an example of what this might look like (in a non-HeatMap example):

![heatmap_toggle](https://cloud.githubusercontent.com/assets/1550771/22794280/8d5e97e2-eeea-11e6-8267-ab91a0426122.gif)

**Comment by jlstevens** [comment]
It seems like a nice idea but I am not sure about this being a HeatMap specific feature request. Why couldn't this idea apply to any element that can have multiple vdims? There are many ways of visualizing multiple vdims for many different elements and having a UI to select between them seems like a useful, general idea. Even if it only makes sense for HeatMaps right now, you can imagine wanting this for other, future elements.

You have suggested that this be pure JS which would be good. We would still want to think a little bit for how such functionality could fit into the planned widget refactor in a general way.

**Comment by philippjfr** [comment]
>There are many ways of visualizing multiple vdims for many different elements and having a UI to select between them seems like a useful, general idea.

True, perhaps all elements which support color mapping could have an option to bring up a toggle widget like this to toggle the colormapping between different dimensions.

>We would still want to think a little bit for how such functionality could fit into the planned widget refactor in a general way.

I don't think it's really related to that tbh. This is a purely JS-level thing that will never have to communicate via a comm or anything like that. It's simply the case that if you enable ``hover`` we're already sending all this data to the browser so adding these buttons will make better use of this data.

**Comment by jlstevens** [comment]
I suppose when I say 'widget refactor', I'm thinking about a refactor of *all* our JS e.g switch to using ES6 classes etc. :-)

**Comment by philippjfr** [comment]
>I suppose when I say 'widget refactor', I'm thinking about a refactor of all our JS e.g switch to using ES6 classes etc. :-)

Doubt we're switching bokeh callbacks to ES6 anytime soon, they're usually short and won't make use of classes.

**Comment by jlstevens** [comment]
I'm not sure how I feel about making this functionality work with bokeh only.

I do understand that using JS to add buttons like this is Bokeh only and that to make it work with matplotlib would require a fair bit more effort. Anyway, that is talking about implementation and I do think the idea behind this feature request is worthwhile.

**Comment by philippjfr** [comment]
For reference and before I lose track of it, the implementation in bokeh would look something like this:

```python
    args = dict(
        glyph = self.handles['glyph'],
        cmapper=self.handles['cmapper'],
        ds=self.handls['source'],
        ranges=ranges
    )

    callback = CustomJS(args=args, code="""
       var selection = cb_obj.labels[cb_obj.active];
       glyph.fill_color.field = selection;
       var range = ranges[selection];
       cmapper.low = range[0];
       cmapper.high = range[1];
       ds.trigger("change");
    """)

    radio_button_group = RadioButtonGroup(
        labels=element.dimensions('value', label=True], active=0)
    radio_button_group.callback = callback
    widgets = widgetbox(radio_button_group, width=300)
    return Column(widgets, self.state)
```

**Comment by jbednar** [comment]
I strongly vote for having these buttons where appropriate; not sure if they should go above the plot or over with the HoloMap slider widgets.  

I'm also not sure they are enough for the general case.  E.g. for Points, more than one value dimension at a time can be used, mapping onto size, color, and potentially other properties of points (see #). Would there then be multiple sets of these buttons?

I actually just this minute had a similar request from a user for this capability for datashader embedded in a HoloViews plot.  This person had a large, multidimensional data set, and wasn't sure what to map on to what axis, and even then expected to need to choose between various value dimensions to aggregate.  Datashader can actually do a whole slew of aggregations at once, and it would be nice to be able to select easily between them for display using this same mechanism.  Of course, a javascript-only mechanism would only be able to choose between these precomputed versions, but it still might make sense to use it for a coherent datashader/non-datashader user experience...

**Comment by philippjfr** [comment]
>I strongly vote for having these buttons where appropriate; not sure if they should go above the plot or over with the HoloMap slider widgets.

In this setup they would have to be part of the plot layout.

>I'm also not sure they are enough for the general case. E.g. for Points, more than one value dimension at a time can be used, mapping onto size, color, and potentially other properties of points (see #). Would there then be multiple sets of these buttons?

We can't currently compute sizes clientside but theoretically we could add this would work for any mappable property like alpha.

>Datashader can actually do a whole slew of aggregations at once, and it would be nice to be able to select easily between them for display using this same mechanism.

Yes, I was just thinking the same thing, we're already all set up to handle aggregation over multiple value dimensions since GridImage can contain stacks of arrays for any number of dimensions. You'd simply provide a list of datashader aggregators to the aggregate operation. Something we're not set up for is handling stacks of RGB images as output by the ``datashade`` operation, although https://github.com/ioam/holoviews/issues/550 combined with https://github.com/ioam/holoviews/pull/994 could get us there.

**Comment by philippjfr** [comment]
I'd also consider handling NdOverlays of Image and RGB types in this way.

**Comment by jbednar** [comment]
Sounds good to me.

**Comment by philippjfr** [comment]
I think we should sort out #768 before doing this so we can create a general system to control the mapping between dimensions and visual properties, which may then optionally be controlled with simple widgets.

**Comment by jbednar** [comment]
> I do understand that using JS to add buttons like this is Bokeh only and that to make it work with matplotlib would require a fair bit more effort.

For matplotlib, would supporting these buttons switch between entirely different sets of PNGs?  That seems reasonable, but then we'd definitely want a way to turn this behavior off (e.g. by having a parameter for the number of value dimensions to include (defaulting to maybe 10?) to keep a lid on the amount of PNGs generated for each plot.

**Comment by philippjfr** [comment]
I think this is basically duplicating the functionality of an interactive legend and could be implemented via a custom JS callback. I've come to the conclusion that I'd prefer exposing an easy way to attach CustomJS callbacks to do things like this rather than adding specific features like this to HoloViews itself.
