### ISSUE TITLE
Remove code to fetch images from NASA in Exploring Data

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#112]
We are hosting our own copy of the data that is smaller and more appropriate for the tutorial. The extra code isn't normally used and doesn't make the tutorial material any clearer.

We can keep the original fetching code elsewhere.

**Comment by philippjfr** [comment]
Done in 4163afcfebc59a3174393543a5b49341988cdf94.

**Comment by jlstevens** [comment]
Ok great! This is one thing that consistently put me off this particular tutorial...
