### ISSUE TITLE
Sankey diagram

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#1123]
It would be nice to offer a [Sankey diagram](https://en.wikipedia.org/wiki/Sankey_diagram).  MPL offers one (http://matplotlib.org/api/sankey_api.html), but a Bokeh-based one could work like the [d3 sankey](https://bost.ocks.org/mike/sankey/), where being interactive makes it much easier to follow.

![image](https://cloud.githubusercontent.com/assets/1695496/22851445/807ee4b6-efe7-11e6-8270-1de5c956acca.png)

**Comment by slamer59** [comment]
d3.js has plenty of example.
I'm using this combined with django:
[d3-sankey-diagram](https://github.com/ricklupton/d3-sankey-diagram)

To play with [some data](https://gist.githubusercontent.com/kunalb/4647670/raw/a4b180a30763b555c43a0979527e93dc4076d6ce/energy.json
)

And I have note tested yet but there is
[jupyter widget](http://nbviewer.jupyter.org/github/ricklupton/ipysankeywidget/)

**Comment by MatthewSteen** [comment]
+1

**Comment by philippjfr** [comment]
Here is my initial effort at porting d3-Sankey to HoloViews: https://anaconda.org/philippjfr/sankey/notebook

The remaining bits should be easy once the TriMesh and Chord PRs have been merged.

**Comment by jbednar** [comment]
Cool!!

**Comment by slamer59** [comment]
Really nice ! Tanks for your effort !

Le ven. 8 déc. 2017 16:57, Philipp Rudiger <notifications@github.com> a
écrit :

**Comment by jlstevens** [comment]
At a glance the approach Philipp uses in that notebooks looks reasonable (Sankey being a type of graph) so I would be happy to see a PR and maybe this new element can make it into the next release.

**Comment by dizhu1991** [comment]
@philippjfr Hi, I was trying to draw a sankey graph of visitor paths' starts and ends in a museum. So the left and right labels will come from the same set of elements. I tried holoview and there was an error "Sankey diagram only supports acyclic graphs". How should I solve this problem?

**Comment by denson** [comment]
@dizhu1991 Sankey is not for visualizing two way relationships as you describe.

You could try loading it into a networkx [MultiDiGraph](https://networkx.github.io/documentation/networkx-1.10/reference/classes.multidigraph.html) and then [draw the MultiDiGraph](https://stackoverflow.com/questions/49340520/matplotlib-and-networkx-drawing-a-self-loop-node).

 There is work being done to attempt to create something similar to Sankey that does allow cycles:

[http://data-analytics.net/cep/References_files/Enabling%20Loops%20in%20Sankey%20Diagrams.html](http://data-analytics.net/cep/References_files/Enabling%20Loops%20in%20Sankey%20Diagrams.html)

[http://bl.ocks.org/soxofaan/bb6f91d57dc4b6afe91d](http://bl.ocks.org/soxofaan/bb6f91d57dc4b6afe91d)

**Comment by TizianoGC** [comment]
@denson: Actually, plotting Sankey cyclic graphs are quite useful!
There are many [examples](http://www.sankey-diagrams.com/) which shows cycles; even [Sankey himself used them](https://en.wikipedia.org/wiki/Sankey_diagram#History).

Holoviews developers, could you please add this new feature? It would be a pity having to switch to another library just for that!

Thanks

**Comment by jbednar** [comment]
HoloViews users, please feel free to implement cyclic support and submit a PR! :-) If you find another library with an appropriate open-source license, maybe you can find the code involved and see if it can guide your implementation. I don't currently know of a need for cyclic Sankey from any of the core developers any time soon, and otherwise this is definitely a case where a user contribution would be able to make it happen!
