### ISSUE TITLE
Improve exceptions on data interface constructor

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#1127]
Currently we generate a fairly useless exception message if no interface is able to process the data:

```python
ValueError: None of the available storage backends were able to support the supplied data format.
```

There's a fairly good reason to have done this because we don't want to see exceptions from all the interfaces it tries, but when you're trying to debug what has gone wrong this output is just entirely unhelpful. We should find some way to summarize and report the exceptions raised by the individual interfaces.

**Comment by jlstevens** [comment]
We probably need some logic in the section of the code where the different data interfaces are tried  out to retain this information. Maybe we could keep this info on a hidden class attribute where you can see the exception and traceback for each interface tested.

Alternatively, maybe we could show the *real* exception but only if the length of the data interface list is one.  Having only one possible interface to try means there is no ambiguity about which interface should be used which means any exceptions and tracebacks generated should be shown - this seems like sensible behavior to implement whether or not we do anything else.

**Comment by philippjfr** [comment]
I have a new suggestion, how about when the data is one of the expected formats and all the interfaces fail to interpret the data it raises the exception for the prioritized interface, e.g. when passing in an xarray.Dataset you see the exception raised by the XArrayInterface and the same happens for dataframes, dictionaries, arrays and iris cubes. In case of passing in a list or tuple you still wouldn't see an error but at least the unambiguous data types could raise meaningful exceptions.

**Comment by jlstevens** [comment]
> ... it raises the exception for the prioritized interface

You mean you see the traceback from the interface that recognized the type/format but failed in some other way? What do you mean by ' prioritized interface'?

**Comment by philippjfr** [comment]
>You mean you see the traceback from the interface that recognized the type/format but failed in some other way?

Right.

**Comment by jlstevens** [comment]
Ok, in that case I have two questions:

1. What bit of an interface will state whether the data is recognized or not even if there is a later exception?
2. What happens if the data is really odd and nothing recognizes it?

**Comment by philippjfr** [comment]
I've introduced ``DataError``s which allow raising more informative error messages from within an interface, so I'll close this. Concrete suggestions for improvements should be filed in https://github.com/ioam/holoviews/issues/2101.
