### ISSUE TITLE
holoviews.util.Dynamic doesn't work without import

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#1134]
`holoviews.util.Dynamic(hv.HoloMap({i: hv.Image(np.random.rand(10,10)) for i in range(10)}))`

only works after 

`import holoviews.util `

**Comment by jlstevens** [comment]
I noticed a similar import problem recently whereby ``util`` wasn't the union of ``core.util`` and the top level ``util``. It is an annoying issue so I'll assign it to the 1.7 milestone.

**Comment by philippjfr** [comment]
>I noticed a similar import problem recently whereby util wasn't the union of core.util and the top level util.

Isn't that exactly the issue described here?

**Comment by jlstevens** [comment]
I think so, yes.

**Comment by basnijholt** [comment]
@jlstevens and @philippjfr 

I am on master now:
```
import holoviews as hv
hv.__version__
Version((1, 6, 2),'/opt/conda/lib/python3.5/site-packages/holoviews/__init__.py','c80f986')
```

And now `hv.util.Dynamic` is completely gone. Importing `holoviews.util` doesn't help.

Only `from holoviews.util import Dynamic` works.

**Comment by philippjfr** [comment]
Thanks @basnijholt, just double checked and I can reproduce it. I'm very confused now, but will look into it.
