### ISSUE TITLE
Speed and memory issues with bokeh backend and pandas datasets with 1.7 dev version

### ISSUE THREAD

**Issue by denglert** [ioam/holoviews#1138]
I experience severe speed and memory issues with the 1.7.0 dev version with the bokeh backend when dealing with pandas datasets compared to what I experience in 1.6.2.

The issues which might be related include:
- the selection of points (with `tools=['lasso_select']`) is much slower in 1.7.0
- returning to the notebook after a small break, and trying to edit cells (not execute) I suddenly experience large memory allocation by chrome. This can be prompted by the following: save the notebook, click on a cell (at this point you shouldn't experience any load), then try to edit the cell without executing (watch memory and processor usage at this stage).
This is not that troubling for the small notebook I prepared (see below), but is much worse when working with larger datasets and/or(?) more plots.

I don't experience any of these two phenomena with 1.6.2

I prepared two jupyter notebooks and a small dataset where you make a comparison:
- mwtc_xsec_scan_holoviews-1.6.2-benchmark.ipynb
- mwtc_xsec_scan_holoviews-1.7.0-benchmark.ipynb
- PS_-0.3_0.3_rs_-1.0_1.0_gt_1.0_9.0_mA_200_3000_all.dat
https://www.dropbox.com/sh/nnsjm5fwcrcx970/AABX-W24srXLKi0i62FQkFMRa?dl=0

Cheers,
David

**Comment by philippjfr** [comment]
I still do not think this is related to holoviews. I do remember having issues similar to the second issue you describe in earlier versions of Jupyter and bokeh but I can't recall what precisely was causing the issue. I can imagine the lasso_select thing might be a change in bokeh 0.12.4 but can't be certain. I'll try to reproduce it myself soon.

**Comment by philippjfr** [comment]
Unfortunately I've not been able to reproduce this and I suspect it's related to your particular set up. Please reopen if you can find a way to reproduce this reliably.
