### ISSUE TITLE
%opts magic doesn't tab-complete normalization options very well

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#114]
If I do this:

``` python
%%opts Curve (co[TAB]
```

The 'color' tab-completes nicely having typed the start of it. However, with normalization options, tab-completion options are only offered after typing '+':

``` python
%%opts Curve {+[TAB]
```

But starting to type '+axiswise' seems to prevent tab-completion from working:

``` python
%%opts Curve {+ax[TAB]
```

**Comment by philippjfr** [comment]
Closing, the completion machinery has proved to be too complex to improve and we are no longer recommending use of the magics.
