### ISSUE TITLE
gridplots for varying blend mode and vertical exaggeration

### ISSUE THREAD

**Issue by thoth291** [ioam/holoviews#1149]
Here is the link to the fairly complicated but very useful type of plots which might look simpler with holoviews.
http://matplotlib.org/examples/specialty_plots/topographic_hillshading.html
@jbednar,
I wonder how possible is to use holoviews here?
Another, more general question, is there any plans to replicate some images from the matplotlib gallery by holoviews - so that transition from matplotlib to holoviews would go smoother?

**Comment by philippjfr** [comment]
Here's my initial approach to implement that using holoviews: https://anaconda.org/philippjfr/hillshading/notebook. For a general approach I'd implement hillshading as an ElementOperation so you can apply simply apply it directly to images.

>Another, more general question, is there any plans to replicate some images from the matplotlib gallery by holoviews - so that transition from matplotlib to holoviews would go smoother?

Yes, we've discussed this a lot, but we haven't had the time. After the 1.7 release we really hope to focus heavily on improving the documentation and a gallery should be one of the first things to do.

**Comment by jbednar** [comment]
That sounds like an excellent way that a new user could contribute, by testing their knowledge -- implement the ones where it's clear how to do it, then ask good questions about the rest. :-)

**Comment by thoth291** [comment]
This is much more understandable than in the matplotlib version.
I also very appreciate an example for saving the images - it's very useful - was not aware of it!
One question - what version of packages I should use?
Thanks again!

**Comment by philippjfr** [comment]
>One question - what version of packages I should use?

I'd recommend working with the holoviews dev version available using:

>conda install -c ioam/label/dev holoviews

We're going to try to have a new dev release this week.

**Comment by philippjfr** [comment]
Going to close this, I've opened a PR on holoviews-contrib with various plot examples adapted from the matplotlib documentation. Hopefully over time we can accumulate a lot of examples. Here's the PR:

https://github.com/ioam/holoviews-contrib/pull/13
