### ISSUE TITLE
How to set the dpi and size in inches for an SVG or PNG renderer?

### ISSUE THREAD

**Issue by thoth291** [ioam/holoviews#1165]
I'm trying to modify the example here:
https://anaconda.org/jbednar/census-hv-mpl/notebook
to let it save picture of better quality and resolution.

But nothing works so far.
I'm getting fairly bad quality picture.

**I wonder if saving from datashader could be implemented so that one gets as much resolution as possible for the given size of the figure or dpi.**

May be it's already implemented this way - I just don't know how to make it work...

**Comment by philippjfr** [comment]
Two things, you'll want to set an explicit ``width`` and ``height`` when calling the ``datashade`` operation. Secondly you'll want to set a dpi on the renderer, something like this should work better:

```
race = datashade(points, x_sampling=10, y_sampling=10, cmap=color_key,
                 element_type=gv.Image, aggregator=ds.count_cat('race'), width=900, height=500)

renderer = hv.Store.renderers['matplotlib'].instance(fig='svg', holomap='gif', dpi=120)
renderer.save(race, 'race')
```

**Comment by philippjfr** [comment]
@thoth291 Did that solve your issue? Please reopen an issue if not.

**Comment by thoth291** [comment]
Hi, @philippjfr .
thank you for your reply!
Yes - it did helped!
