### ISSUE TITLE
%%opts doesn't seem to have any effect when using a Dataset (matplotlib backend)

### ISSUE THREAD

**Issue by benbovy** [ioam/holoviews#1166]
As an example, running the following cell in a notebook

```python
%%opts Image style(interpolation='bilinear', cmap='viridis') plot[colorbar=True]
hv_ds = hv.Dataset(xarray_dataset, vdims=['topographic__elevation'])
hv_ds.to.image(['x', 'y'])
```

still gives the default cmap and no colorbar:

<img width="845" alt="screen shot 2017-03-01 at 09 39 05" src="https://cloud.githubusercontent.com/assets/4160723/23452400/7cfd3898-fe64-11e6-82a1-236a8e2a270c.png">

(tested with holoviews 1.6.2, matplotlib 1.5 and 2.0 and xarray 0.9.1)

**Comment by philippjfr** [comment]
This is a bit confusing and is something that will hopefully be resolved soon. We currently have both an ``Image`` Element and a ``GridImage`` Element, the latter exists to have support for grid based datasets like xarray. They will be unified in #994, but for now you have to specifically refer to ``GridImage``.

**Comment by benbovy** [comment]
Works perfectly, thanks!!

I'm fine using `GridImage` instead of `Image`.

BTW, great package, good job!

**Comment by philippjfr** [comment]
>BTW, great package, good job!

Glad it's working for you, and thanks a lot. Feel free to ask any questions!
