### ISSUE TITLE
Implementing reverse sort

### ISSUE THREAD

**Issue by denglert** [ioam/holoviews#1167]
While trying to reverse sort a hv.Points object I came across there is no reverse sort implemented in hv.
https://github.com/ioam/holoviews/blob/master/holoviews/core/data/__init__.py#L206

Would be nice to see something like:
`hv.Points.sort('z', reverse=True)`

**Comment by philippjfr** [comment]
Thanks for filing this. It should be fairly straightforward since only columnar interfaces have to support this.

**Comment by philippjfr** [comment]
That should be straightforward enough for one column, not quite clear to me how that would work when you sort over multiple columns at once, but I think it makes sense.

**Comment by philippjfr** [comment]
Going to close as I think providing a sort function is out of scope, especially as I can't see how it would work.
