### ISSUE TITLE
New depth parameter in labeling HoloMap 

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#117]
This gives me a labeled ``HoloMap``:

```python
hv.HoloMap(ims, key_dimensions=['x']).relabel(label="test", depth=1) 
```

While I don't get what this will do (with default ``depth=0``):
```python
hv.HoloMap(ims, key_dimensions=['x']).relabel(label="test") 
```

Why isn't the ``depth=1`` default for relabeling a ``HoloMap``?

**Comment by jlstevens** [comment]
It seems to be working as we intended although it is possible that our default behavior isn't sensible!

```python
import holoviews as hv
import numpy as np

ims = {i:hv.Image(np.random.rand(10,10)) for i in range(3)}
hmap = hv.HoloMap(ims, key_dimensions=['x']).relabel(label="test")
hmap.label
```

The result is ``'test'`` as expected: with ``depth=0`` (i.e the default) only the label on the ``HoloMap`` is set and none of the elements are relabeled.

As you've discovered, ``depth=1`` does the job you want. What I am now wondering is whether:

* We should use ``depth=1`` everywhere by default.
* Whether (as you suggest!) the default depth should be 1 for HoloMaps (and maybe for some other elements) but 0 elsewhere. 

The former approach would be a a single character change in the source code whereas the second option means overriding the ``relabel`` method just to change the default depth value.

Anyway, I'll wait for Philipp to give us his input before making any suggestions as to which approach might be best. I do think that we should probably use a better default given that relabeling ``HoloMaps`` is going to be a very common operation...

**Comment by jbednar** [comment]
Is relabeling a HoloMap with depth=1 a destructive operation?  I.e. if you have a dozen elements that happen to appear in more than one HoloMap, will relabelling one HoloMap with depth=1 change the label of the elements in the other HoloMap?  If so I vote against a default of 1; I think people should be required to specify explicitly if they want an operation that could unintentionally be destructive of contained elements' metadata.  

If HoloMap does end up with a default of 1, it's worth thinking about whether there are other containers that should also have a default of 1.  Presumably Layout would not, because we want each plot to have a different label, and  Overlay (and NdOverlay?) probably shouldn't, or we won't be able to have a legend.  HoloMap does seem special in this regard, I guess, but I might have overlooked something.

**Comment by jlstevens** [comment]
> Is relabeling a HoloMap with depth=1 a destructive operation?

I've just double checked and this isn't the case. The relabelling operation creates a new object (without copying the data!) which means it isn't destructive.

> Presumably Layout would not, because we want each plot to have a different label, and Overlay (and NdOverlay?) probably shouldn't, or we won't be able to have a legend. 

That sounds about right but I will also have to think about it more...

**Comment by jbednar** [comment]
Ok, in that case I could support a default of depth=1 for a HoloMap.

As for whether that should be the default overall, it seems like it wouldn't matter either way for an Element (which has data only at depth=0), but I don't *think* you want the other Containers to be relabelling their contents (so that you can easily have a label for the overall plot separate from the labels of individual Layout or Overlay items).  So I don't *think* it would work as a shared default of 1; making it only HoloMap that would have this special case.

**Comment by philippjfr** [comment]
I think a default depth of 1 on a HoloMap might be sensible as their groups and labels have no effect beyond their names in a Layout, however I think there are other reasons why it's a bad idea. I definitely know that it would be terrible behavior for Layout and Overlay as they contain homogenous data, you should do that explicitly. 

Additionally there is the complication that if your data is deeply nested, e.g. HoloMap of NdOverlays, then depth=1 isn't sufficient anyway. In the end I'm not entirely convinced it's a good idea, we can't guess your nesting structure and a default other than 1 hides that problem from you only until you try to relabel a HoloMap of NdOverlays. If we do it, it should definitely be restricted to HoloMaps.

**Comment by jbednar** [comment]
Is there a downside to using depth=Infinity on a HoloMap?  I.e., if the HoloMap does copy its contents deeply, would such relabelling negatively affect the display of the data?  If not, should HoloMap by default have a depth of Infinity?  

I agree that there's no reason for HoloMap to have a special default if it won't really solve the problem.   But if using depth=Infinity would make nearly everyone never have to worry about depth at all, maybe it's worth it.

**Comment by philippjfr** [comment]
Terrible idea unfortunately, this would potentially rename all the paths in an Overlay. I vote we leave it as it is.

**Comment by jlstevens** [comment]
I have no strong opinion but I can't see why a *default* depth of 1 (which can always be overridden) would ever be harmful if applied to HoloMaps. This just renames the HoloMap elements to be the same as the HoloMap - which in fact was implicit in the behavior before we introduced the depth parameter! I agree with @philippjfr that a depth of infinity would not behave well.

I don't think we've found a case where having one group/label on the HoloMap and a different group/label on the elements is a particularly useful thing to have. If this change makes it easier for people to work with HoloMaps, I think I am probably in favor of implementing this just to avoid seeing ``depth=1`` everywhere.

**Comment by jbednar** [comment]
On further reflection, I don't quite understand why depth=1 won't work -- even if there is additional structure below it, why isn't relabelling at the depth=1 level sufficient to relabel the plots appropriately, even for a HoloMap of NdOverlays?

**Comment by jlstevens** [comment]
I think we can agree ``depth=1`` is a good working default for ``HoloMap``. My only question is whether we want to change the default depth anywhere else - I don't *think* so.

**Comment by philippjfr** [comment]
Right, my vote against it shouldn't be read as a strong objection. My two primary concerns are:

1) Inconsistency
2) You still need to use depth if your objects are more deeply nested.

However this was the default behavior before so if you guys think it's better this way then go ahead.

>On further reflection, I don't quite understand why depth=1 won't work -- even if there is additional structure below it, why isn't relabelling at the depth=1 level sufficient to relabel the plots appropriately, even for a HoloMap of NdOverlays?

It will obviously relabel the NdOverlays but from the way I've seen Bas and Vasco use groups and labels they use it to apply different existing style groups to their Elements and in the case of HoloMaps of NdOverlays depth=1 will still not relabel Elements.

**Comment by jbednar** [comment]
Ah, I see -- relabeling not for displayed titles, but for style grouping.  In that case I'm +1 on making the default depth 1 for a HoloMap, as it makes the set of people (and notebooks) who never need to worry about depth somewhat larger than the default of 0.  The people who do need it will still need to figure this out, but they'll be people with HoloMaps of nested structures, and thus probably more likely to be experienced enough to figure it out.

**Comment by jbednar** [comment]
It doesn't sound like there is any argument in favor of depth>0 by default for any object other than a HoloMap.

**Comment by jlstevens** [comment]
I agree... my only question now is whether this is annoying enough reason to consider a 1.2.1 release fairly soon? Bug fixes and small changes like this *only* though!

**Comment by jbednar** [comment]
I don't personally think it's worth a 1.2.1 release; we'll soon enough find some more serious issues!

**Comment by jlstevens** [comment]
HoloMap now has ``depth=1`` by default (see above commit). We can now remove ``depth=1`` from the notebook tutorials in a couple of places but we will probably want to address issue  #118 first.

**Comment by jlstevens** [comment]
The depth parameter has been updated for ``HoloMap`` objects as well as ``AdjointLayout`` (see #157).

I will now close this issue.
