### ISSUE TITLE
Our documentation needs to be version specific

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#118]
I am thinking about our tutorial notebooks in particular - we have occasionally added sections to the Tutorials based on what is available in the development version but not available in the pip version. This means people trying to follow our tutorials using the pip version might get stuck!

I propose that the main website links to a set of static pages that correspond to the released pip version. Perhaps we could have  ``ioam.github.io/holoviews/Tutorials/dev/index.html`` page that links to the notebooks that we rebuild nightly that we can update as development progresses. This would also be nice because we could stop worrying about publicly visible notebooks being broken every night...

This is probably a good time to fix this before we start adding new features to the next version!

**Comment by jbednar** [comment]
Usually people have the main documentation pointing to the released version, and a development version alongside it, in a different directory.  That way both are available for the people who need them, and indeed the development version can break without undue alarm.

**Comment by jlstevens** [comment]
Right. I think we should implement something along those lines before we update the reference-data again...

**Comment by philippjfr** [comment]
That's exactly what I've implemented now. The release version of our documentation is available via the main website and the dev version is available via http://ioam.github.io/holoviews/dev. This means I can now automate the website updating without having to worry about breaking stuff on the main website. 

Additionally we now have tags for the reference data and Tutorials submodules. Finally we have plans to automate squashing of the website, reference_data and Tutorial branches between releases, making sure we don't accumulate too much stuff.

**Comment by jbednar** [comment]
Sounds great!

**Comment by jlstevens** [comment]
Just a note, we might want to add a ``robots.txt`` to stop Google and friends from indexing the ``/dev`` portion of the website.
