### ISSUE TITLE
What should .layout() do on a Layout of HoloMaps?

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#1182]
If I take the Showcase notebook and reduce the number of samples in phase, freq space:

```
phases = np.linspace(0,2*np.pi,2)
freqs = np.linspace(50,150,2)
```

I can use `.layout()` on the individual holomaps from cell 8:

![image](https://cloud.githubusercontent.com/assets/1695496/23721234/c16bfb02-0406-11e7-830b-22e24a41e697.png)

![image](https://cloud.githubusercontent.com/assets/1695496/23721309/e40a7c9c-0406-11e7-9e52-66e2a470e8e0.png)

However, the result from calling `.layout()` on the layout itself is confusing (see above).  Should this have been an error?  I'm not sure what I would expect it to do (I guess maybe lay out the first holomap, then the second one?), but getting a bare ``Layout`` is surprising and confusing.

**Comment by philippjfr** [comment]
A ``Layout`` creates new leafs on attribute access, so you've added another ``Layout`` as a leaf and called it, which just resets non-existing plot options. I had thought this would raise an error though, because lower case paths aren't allowed.

**Comment by jbednar** [comment]
I wonder if there would be a way to provide more informative feedback for that situation in general, i.e., when one has accidentally created a new leaf merely be referring to a non-existent attribute.

**Comment by jlstevens** [comment]
> I wonder if there would be a way to provide more informative feedback for that situation in general, i.e., when one has accidentally created a new leaf merely by referring to a non-existent attribute.

I agree, but we haven't found a good solution yet. I'm starting to wonder if we should disable the ability of just setting paths on layouts but it was one of the core features of the design. Maybe there should be some attribute/method to toggle this type of mutability that is disabled by default?

I am also wary about changing Layouts as they are tricky to work with.

**Comment by jbednar** [comment]
Is there a legitimate use for an empty Layout(), in the final result?  If not, maybe we could have a warning when trying to do the repr of an empty Layout, explaining something about how this isn't useful and can come about from referring to a non-existent attribute on an existing Layout?

**Comment by philippjfr** [comment]
This will now appropriately raise an ``AttributeError``.
