### ISSUE TITLE
holoviews.streams.update is not embedded into HTML on save

### ISSUE THREAD

**Issue by thoth291** [ioam/holoviews#1183]
In the first cell I do this:
```python
%%opts Scatter3D [width=800 height=800 color_index=2] (cmap='Viridis')
import holoviews as hv
import numpy as np
from holoviews.plotting import plotly
hv.notebook_extension(plotly=True)
from holoviews.streams import PositionX
xs,ys = np.mgrid[-50:51, -50:51] * 0.07
N = 100
random_x = np.random.randn(N)
random_y = np.random.randn(N)
random_z = np.random.randn(N)
stream = PositionX()
hv.DynamicMap(lambda x: hv.Scatter3D((random_x, random_y, random_z*x)), kdims=[], streams=[stream])
```
And at the next cell I put this:
```python
stream.update(x=100)
```

Then I'm saving the resulted plot as HTML - but getting the plot before the update and not after the update.

Is it a bug in Plotly - or it's by design and there is no way to fix it?
Thanks!

**Comment by jlstevens** [comment]
I suspect this is because streams are currently integrated with the matplotlib and bokeh backends but not the plotly backend. I'll assign this issue to the 1.7 milestone as we need to investigate how plotly will work with streams before then.

**Comment by philippjfr** [comment]
I'm afraid there's nothing we can do about this and is not specific to the plotly backend. HoloViews will embed whatever is initially displayed and pushing updates to the plot with stream will not persist in an exported notebook.

**Comment by thoth291** [comment]
Thank you, @philippjfr 
I thought that `sampled=True` and wrapping with `HoloMap` might help to keep what was passed - but it didn't worked.

Do you think it worth to extend `sampled` functionality on this case?

**Comment by jlstevens** [comment]
> Then I'm saving the resulted plot as HTML

Sorry, I missed that bit. I do think we ought to check if streams will work with plotly, but unfortunately I don't think it will be possible to make it work as a static file as @philippjfr says.

**Comment by jlstevens** [comment]
@philippjfr That said, if you wanted to do this, could we consider re-enabling the DynamicMap cache with streams for cases like this which would let you then cast to a HoloMap would *would* be preserved on the output?

**Comment by philippjfr** [comment]
>I do think we ought to check if streams will work with plotly

We already use it in some of our projects.

>That said, if you wanted to do this, could we consider re-enabling the DynamicMap cache with streams for cases like this

DynamicMaps have a length 1 cache anyway so you can already do this by casting to a HoloMap.

**Comment by thoth291** [comment]
I did the cast but the plot disappeared...

**Comment by jlstevens** [comment]
> DynamicMaps have a length 1 cache anyway so you can already do this by casting to a HoloMap.

I meant expanding the cache size to be greater than 1 so you can capture a sequence of updates via streams.

**Comment by philippjfr** [comment]
>I did the cast but the plot disappeared...

You need to cast it after you've displayed it once.

>I meant expanding the cache size to be greater than 1 so you can capture a sequence of updates via streams.

The default cache size is 500 anyway, the example above use streams so by default the cache is fixed at length 1.  A user would have to explicitly declare key dimensions for the streams for the cache to work properly.
