### ISSUE TITLE
Linked crosshairs

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#1184]
It would be great if we could use streams and dynamic maps to provide plot elements that are linked across multiple plots.  For instance, if we have a stack of several related timeseries plots, each in a different subfigure, it would be very useful to be able to show a vertical crosshair in all of the plots to see how a particular time point is related across the plots.  The position of the crosshair would then be updated by the pointer position in whatever subfigure the pointer is currently hovering over.

@philippjfr indicated that in some cases this already works, but that having it work well with hover information is tricky, and depends on functionality in https://github.com/bokeh/bokeh/pull/5941 .

**Comment by philippjfr** [comment]
The current issue is that the PositionX/Y streams attach themselves to the HoverTool. When other plot elements also use the hover tool they are not appropriately merged. Making the PositionXY stream work using an event based callback will bypass this issue and make this work more generally.

**Comment by philippjfr** [comment]
This will require no implementation just documentation.

**Comment by philippjfr** [comment]
Here's a basic example, which will become part of the linked stream gallery:

```python
%%opts Curve [width=100]
x,y = np.meshgrid(np.linspace(-5,5,101), np.linspace(5,-5,101))
img1 = hv.Image(np.sin(x**2+y**2))
img2 = hv.Image(np.sin(x**2+y**3))
posx = hv.streams.PointerX()
crosshair = hv.DynamicMap(lambda x: hv.VLine(x or -100), streams=[posx])
crosssection1 = hv.DynamicMap(lambda x: img1.sample(x=x if x else 0), streams=[posx])
crosssection2 = hv.DynamicMap(lambda x: img2.sample(x=x if x else 0), streams=[posx])
((img1 << crosssection1) * crosshair) + ((img2 * crosshair) << crosssection2)
```

![linked_crosshair](https://cloud.githubusercontent.com/assets/1550771/25257740/0a5cbc82-2632-11e7-9eac-1dabcbd9e890.gif)

**Comment by jlstevens** [comment]
Very nice!

**Comment by jbednar** [comment]
Looks great!

**Comment by jlstevens** [comment]
Assigning to 1.7.1 milestone.

**Comment by philippjfr** [comment]
The above example has been added to ``examples/streams/bokeh``.
