### ISSUE TITLE
Support .collate for DynamicMaps?

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#1188]
The example on the holoviews.org home page shows how to use `.collate()` to turn the illegal "HoloMap of Layouts" construction into the displayable "Layout of HoloMaps", which is very convenient in practice.  However, `.collate()` does not seem to be supported for DynamicMaps.  

Here's an example of what I'd want to use that for:

```python
import numpy as np
import holoviews as hv
import imagen as ig
import imagen.transferfn as tf

from imagen.image import FileImage
from imagen.transferfn.sheet_tf import Convolve

hv.notebook_extension()

%opts Image (cmap="gray") {+axiswise}

FileImage.filename = "/Users/jbednar/imagen/doc/images/ellen_arthur.pgm"

kdims = [hv.Dimension('size',                   range=(0.1, 2)),
         hv.Dimension('positive_size',          range=(0.1, 2)),
         hv.Dimension('negative_size',          range=(0.3, 4)),
         hv.Dimension('positive_aspect_ratio',  range=(1.0,10)),
         hv.Dimension('negative_aspect_ratio',  range=(1.0,10))]
```

Right now, I can easily view one static image along with a slider-controlled dynamic map, but I have to pick a single HoloViews object to return from the callback:

```python
def filtered_images(size,positive_size,negative_size,positive_aspect_ratio,negative_aspect_ratio):
    convolver = Convolve(kernel_pattern=ig.DifferenceOfGaussians(**locals()))
    return FileImage(output_fns=[convolver])[:]

FileImage()[:] + hv.DynamicMap(filtered_images, kdims=kdims)
```

![image](https://cloud.githubusercontent.com/assets/1695496/23803067/efcb9c30-057a-11e7-8389-959e7318bc87.png)

```python
def filtered_images(size,positive_size,negative_size,positive_aspect_ratio,negative_aspect_ratio):
    convolver = Convolve(kernel_pattern=ig.DifferenceOfGaussians(**locals()))
    return convolver.kernel_pattern[:]

FileImage()[:] + hv.DynamicMap(filtered_images, kdims=kdims)
```

![image](https://cloud.githubusercontent.com/assets/1695496/23803077/fe95d668-057a-11e7-8b42-0619cee6a0d9.png)

But what I want is to make one single callback that returns a Layout of both the two dynamic plots above:

```python
def filtered_images(size,positive_size,negative_size,positive_aspect_ratio,negative_aspect_ratio):
    convolver = Convolve(kernel_pattern=ig.DifferenceOfGaussians(**locals()))
    return convolver.kernel_pattern[:] + FileImage(output_fns=[convolver])[:]

FileImage()[:] + hv.DynamicMap(filtered_images, kdims=kdims).collate()
```

Unfortunately, that doesn't work, whether I call `.collate()` (see output below) or not.  Of course, I can construct multiple DynamicMaps, using multiple callbacks, but they both need to share the same kernel_pattern state, so I'd also need to make a class to hold that state and change the callbacks to be methods on the object with the shared state.  That's ugly, a lot of code, and a pain to set up.  Can we just make `.collate()` work on DynamicMaps, and then people can write one callback to handle all the dynamic stuff in a given final Layout?

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-3c23b390e441> in <module>()
      3     return convolver.kernel_pattern[:] + FileImage(output_fns=[convolver])[:]
      4 
----> 5 FileImage()[:] + hv.DynamicMap(filtered_images, kdims=kdims).collate()

/Users/jbednar/holoviews_git/holoviews/core/spaces.pyc in collate(self, merge_type, drop, drop_constant)
    255         merge_type=merge_type if merge_type else self.__class__
    256         return Collator(self, merge_type=merge_type, drop=drop,
--> 257                         drop_constant=drop_constant)()
    258 
    259 

/Users/jbednar/holoviews_git/holoviews/core/element.pyc in __call__(self)
    592 
    593         components = ndmapping.values()
--> 594         accumulator = ndmapping.last.clone(components[0].data)
    595         for component in components:
    596             accumulator.update(component)

AttributeError: 'NoneType' object has no attribute 'clone'
```

**Comment by jlstevens** [comment]
A dynamic collate should be something we try to get ready for 1.7. I agree it is important and we can shift the assigned milestone if it turns out to be too tricky.

**Comment by philippjfr** [comment]
Now implemented, assigning to @jlstevens to document.

**Comment by jlstevens** [comment]
> Now implemented, assigning to @jlstevens to document.

Will do!

**Comment by philippjfr** [comment]
I'll try to come up with an example.

**Comment by jbednar** [comment]
As a start, can you show how to make the above code work?  I just tried with the latest master and the same code that didn't work above with or without ``.collate()`` still doesn't work with or without ``.collate()``, and it still doesn't give a very useful error message.   Are there now arguments that I need to pass to determine how the streams line up, and are there ways the error messages could guide me towards adding those?

**Comment by philippjfr** [comment]
This has now been implemented and I fixed a bug related to adding more plots to a collated Layout. Going to close this and will be adding some examples to our list of stream examples.
