### ISSUE TITLE
Support kwargs-based callbacks for DynamicMap?

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#1189]
Currently, DynamicMap requires that its callback use positional arguments, and it provides the values along each kdim in the order of the kdims, as in:

```python
import numpy as np
import holoviews as hv
import imagen as ig
import imagen.transferfn as tf
from imagen.image import FileImage
from imagen.transferfn.sheet_tf import Convolve
hv.notebook_extension()
%opts Image (cmap="gray") {+axiswise}

FileImage.filename = "/Users/jbednar/imagen/doc/images/ellen_arthur.pgm"

kdims = [hv.Dimension('size',                   range=(0.1, 2)),
         hv.Dimension('positive_size',          range=(0.1, 2)),
         hv.Dimension('negative_size',          range=(0.3, 4)),
         hv.Dimension('positive_aspect_ratio',  range=(1.0,10)),
         hv.Dimension('negative_aspect_ratio',  range=(1.0,10))]

def filtered_images(size,positive_size,negative_size,positive_aspect_ratio,negative_aspect_ratio):
    convolver = Convolve(kernel_pattern=ig.DifferenceOfGaussians(**locals()))
    return FileImage(output_fns=[convolver])[:]

FileImage()[:] + hv.DynamicMap(filtered_images, kdims=kdims)
```

Positional arguments work well for one or two arguments, but once there are a lot of them (and the above code shows only a small subset of the arguments that *could* be kdims in this example), keyword arguments can be much safer.  E.g. in the code above, if I add a kdim to that list, I need to be sure to add the appropriate argument to the `filtered_images` argument list, in precisely the right spot, or else everything will get jumbled.  If all I'm doing is passing the arguments down to some other object, as I am here, it's redundant and fragile to redeclare them in this way.

Can we make DynamicMap support calling its callback using keyword arguments instead, either by adding a parameter to it ``kwarg_callback=True`` or by inspecting the callback to determine whether it uses positional or keyword arguments?

**Comment by jlstevens** [comment]
I think this would be a very reasonable thing to support. I'm just wondering if we should consider using inspection to do the right thing automatically...

**Comment by jlstevens** [comment]
Addressed by the PR referenced above. Closing.
