### ISSUE TITLE
Indexed Tables when there is no explicit key dimension

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#120]
I've opened this issue is to discuss a feature I am working on that I've already introduced in commit 156f6d5.

When working on Lancet, I discovered that if you have no meaningful key dimension to add to your Table, you have to introduce one yourself anyway (because ``Tables`` are ``NdElements`` and therefore related to ``NdMappings``). This is awkward to do and could lead to different people using lots of inconsistent dimension names for the required 'pseudo' dimension: 'Row', 'Index', 'Unique Key', 'ID' etc. This seems like a problem that needs to be solved once at the ``Table`` level to keep things consistent.

It should always be possible to index your data out of a table so there is always *some* dimension to index by, whether you think of it that way or not. For instance, in Pandas, your dataframes always have an index and indexing by row in any system is indexing by a key dimension.

My solution is to rename the one key dimension from 'Default' to 'Index' and treat it a little differently if it is the only key dimension specified. An indexed table enforces that the key is simply the row index of that entry in the table. In addition, an indexed table (i.e if you don't change the key_dimensions) allows Table to have a more flexible constructor. Say I have a list of values, I can now put it in a table:

```python
table = hv.Table(data=[0,10,20,30])
```
This is now a two-column table where 'Index' is the first column. You can now index your values by position, allowing you to treat ``Table`` elements as fancy lists:

```python
>>> table[1]
10
```

Before, you would have had to decide yourself to index by row and then do something awkward like:

```python
hv.Table(data=enumerate([0,10,20,30]), key_dimension=['arbitrary-dimension-name'])
```

The only downside I can see with this approach is that *if* you want to use a single key dimension called 'Index' then that dimension must have the semantics we impose (i.e the row index). I think this is less of a restriction than making it hard to use Tables when you don't have your own meaningful key dimension to assign! 

**Edit:** Of course there are ways around this by introducing new parameters, e.g ``index_dimension_name`` but I would rather avoid complicating things! A class attribute could be ok if  people *really* want to use 'Index' as their key dimension name.

Note that I've implemented this in such a way that the old constructor works as before: the tests are passing after this commit was made and I didn't have to update the reference data.

I consider what I have committed as a working prototype and if you have any suggestions for improvement this is the right place to tell me what you think!

**Comment by jlstevens** [comment]
Before I forget, I should mention something I don't quite understand yet: in Python 3, I get an error in our ``python2sort`` utility function (python 2 compatible sorting) unless I first disable ``self._sorted``, add the data, set sorted back to true and then resort. 

I would rather avoid doing this if possible!

**Comment by jbednar** [comment]
It sounds reasonable to me.  Why not call it "row" rather than "Index", if it is specifically required to have the semantics of a row number?

**Comment by jlstevens** [comment]
'Row' was my initial name but then I thought 'Index' might be nicer for consistency with the terminology used in pandas.

I am perfectly happy to change it but I would first like to know what other people's preferences are. @philippjfr Which one do you prefer?

**Comment by jlstevens** [comment]
Added commits 74ea93a and 185c8be. The new format now seems to be working nicely in Lancet!

**Comment by jlstevens** [comment]
In 626e87a I switched from the name 'Index' to the name 'Row'. It is shorter and it might be better to not get things confused with pandas anyway.

**Comment by jlstevens** [comment]
I'm going to close this issue unless I hear some feedback suggesting other improvements....
