### ISSUE TITLE
Separate statistical elements into separate module

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#1200]
Based on discussion I had with @philippjfr, we think it might be worth splitting out statistical elements (e.g ``ErrorBars``, ``BoxWhisker``) into ``element.statistics``. This could include new statistical element types (e.g element types currently implicit in ``interface.seaborn`` such as ``Distribution`` and ``Regression``)

**Comment by jbednar** [comment]
And Violin?  And the outlier operation?

**Comment by jlstevens** [comment]
``Violin`` would also go there, yes. But operations don't go into the ``elements`` subpackage...

**Comment by ea42gh** [comment]
Add a constructor to produce a boxwhiskers plotfrom the relevant quantiles and IQR, but not the original data

**Comment by philippjfr** [comment]
>Add a constructor to produce a boxwhiskers plotfrom the relevant quantiles and IQR, but not the original data

@ea42gh If you still want that please reopen it as a separate feature request. ``element.stats`` and ``operation.stats`` now exist and we'll keep adding to them, so I'll close.
