### ISSUE TITLE
Replace compositor with plot transforms

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#1201]
The compositor system is a somewhat 'hidden' feature of holoviews that we have talked about generalizing and documenting in the past. Based on discussion with @philippjfr we have a proposal for a new system that could replace it and make new plot types easier to implement.

The core idea is to have a preprocessing step before the plot classes are created whereby you can apply operations to the (potentially nested) datastructure before it is rendered. Say we wanted to have our own implementation of [violin plots](https://en.wikipedia.org/wiki/Violin_plot) without relying on external support.

We could then implement a statistical ``Violin`` element that isn't processed by ``ViolinPlot`` but by ``ViolinTransform``. The implementation of this class wouldn't be dealing with plotting (i.e it would be matplotlib and bokeh-independent) because it would be more like an operation that converts the ``Violin`` element into some composition of the more primitive elements we already support (e.g ``Curve``, ``Points``, ``Spline``).

When rendering, the nested data structure would be traversed and all ``Violin`` elements would be fed to ``ViolinTransform`` to convert it into a set of elements holoviews already supports. As ``ViolinTransform`` would be a backend-independent operation, this would allow a single implementation to offer violin plots for both bokeh and matplotlib, helping ensure consistency.

The old compositor system would just be an example of a transform operating on ``Overlays`` - it would leave overlays alone (i.e act as the identity function) unless it matched a pattern of type.group.label between the layers, in which case it would apply a transformation.

As long as it is easy to add transforms, we could then replace the compositor system with something more general and deprecate the compositor magic (that almost no one knows about!).

**Edit:** I can't resist pointing out that in programming languages, these things are called 'macros'. Think of a nice language with proper macro support that works on trees and not strings...so don't think about C!

**Comment by jlstevens** [comment]
For reference #908 is the other issue discussing compositors - we should figure out how this proposal fits in.

**Comment by jbednar** [comment]
Sounds like a very useful facility to me.

**Comment by jlstevens** [comment]
One issue we would need to think about carefully is how this integrates with the ``%%opts`` magic and the option system. There is no reason ``Violin`` shouldn't have plot and style options even though it is generated by a transform/macro/whatever we end up calling these things!

**Comment by philippjfr** [comment]
So we never renamed Compositors but we have implemented exactly what's described here a while ago and put it in active use for ``Violin``, ``Distribution``, ``HexTiles`` and ``Sankey`` plots. I'll close but please reopen if you have a strong opinion on renaming Compositor, but I'm tentatively -1 on that because the actual transforms in the cases described above is done by an ``Operation`` and the ``Compositor`` simply ensures it is applied during plotting.
