### ISSUE TITLE
Better sizing of Table columns

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#121]
I know the support in matplotlib for tablulation is pretty poor, but I would love to improve the visual output of Tables (at least a little!). Consider:

```python
Table(['example-filename.png'])
```

If the first column is called ``'Row'`` and contains small integers (e.g. 0) then the first column could be made a lot narrower so that the second column (containing the filename) could then be wider. This would really help make Tables more legible (i.e bigger font size), addressing one of my biggest problems when working with this class.

**Comment by philippjfr** [comment]
Since commit be90a54bd43 Tables take into account the maximum number of characters in each column when computing widths. This should be an improvement but I'm not entirely sure how it interacts with font sizing, so there might be more scope for improvement.

**Comment by jlstevens** [comment]
I think we can close this issue now - the sizing is still not perfect but it is certainly a lot *better* than before!

If anyone has a better sizing policy to suggest, they can either comment below (and we can reopen the issue) or they can file a new issue...
