### ISSUE TITLE
Element.range should have option to return just data range

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#1212]
Currently the ``Element.range`` method offers a quick way to get the range along a dimension. It does so by computing the range of the data and then combining it with the ``soft_range`` and ``range`` defined on the corresponding Dimension. This is very useful but when operating on an Element it is usually more useful to know the actual range, rather than muddling it up with the ranges set on Dimensions. My suggestion would be that as part of the 2.0 release we change the semantics of the ``data_range`` argument on the ``range`` method from meaning "include the data range in the calculation" to "return just the data_range". The plotting code would then generally call ``.range(dim, data_range=False)`` while user code and operations would just use the default which is ``data_range=True``.

**Comment by jlstevens** [comment]
Makes sense.

**Comment by philippjfr** [comment]
This has been implemented `.range` now has data_range and dimension_range arguments.
