### ISSUE TITLE
Add support to disable memoization for streams 

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#1215]
As we have discussed previously certain types of streams, specifically those triggered by events like ``Tap`` and in future ``KeyPress`` events should prevent memoization ensuring that the event is actually processed.

**Comment by jlstevens** [comment]
Just to summarize our previous discussion, we just need something to mark streams that shouldn't be memoized and then we can add a hash e.g a uuid to make sure the memoization system never sees repeat keys (and therefore won't be able to memoize).

**Comment by philippjfr** [comment]
This has now been implemented in form of the ``transient`` option on streams.
