### ISSUE TITLE
Add support for unsorted NdMappings

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#1216]
In theory there is no reason why all our NdMapping types have to be sorted. Early on we thought it would be simpler forcing them to always be sorted but they use an OrderedDict internally and if we just gave them a sorted parameter the sorting order would persist when you clone the NdMappings. My suggestion would be to have a ``sort`` parameter on NdMappings, which is True by default maintaining backwards compatibility but if you want to create an NdMapping explicitly you can just set the parameter to False in the constructor and that ordering would be maintained even if you apply various methods or operations to the object.

**Comment by jlstevens** [comment]
Sounds good but I'm not sure ``sort=False`` makes sense with vanilla dictionaries as they have an undefined order anyway. Maybe it could warn if ``sort=False`` and the dictionary isn't an ordered dictionary.

**Comment by philippjfr** [comment]
Sure, could check that, valid constructors are dicts, lists of key, value tuples and OrderedDict. The latter two would behave correctly while dicts would warn.

I've assigned this to the 2.0 milestone, but as far as I can tell this requires nothing more than adding the parameter, adding one conditional check on the sorting, and the warning for dicts. Should we just do it now?

**Comment by jlstevens** [comment]
Given that the default behavior would be backwards compatible, I don't see why not!

**Comment by philippjfr** [comment]
Implemented in #1217.
