### ISSUE TITLE
Remove bokeh plots relying on bokeh matplotlib compat

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#1218]
As of https://github.com/bokeh/bokeh/pull/6008 mpl compatibility in bokeh is officially deprecated. We should remove the ``BokehMPLWrapper`` plot and the DistributionPlot, TimeseriesPlot and Bivariate plot that are hooked up. The examples of those plots in the ``Bokeh_Backend`` Tutorial. 

I'll open a separate issue to remove the ``TimeSeries`` Element because it's data format is strange and functionality is subsumed by other Elements. We should also consider implementing our own implementations for Distribution and Bivariate, which represent 1D and 2D KDEs respectively and would fit in among our statistics Elements. At that point I'd consider dropping our seaborn interface entirely.

**Comment by jlstevens** [comment]
Sounds good to me! Hopefully the seaborn functionality will be supported by the new statistical element types.

**Comment by philippjfr** [comment]
Bokeh matplotlib compatibility has now been removed and its functionality will be replaced with statistical Element types in 2.0 (see https://github.com/ioam/holoviews/issues/1200).
