### ISSUE TITLE
Combining HoloMaps of different lengths framewise fails

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#122]
Combining HoloMaps with different lengths fails if set to framewise:

```python
%%opts Image {+framewise}
import holoviews as hv
import numpy as np
hmap1 = hv.HoloMap({i:hv.Image(i*np.random.rand(10,10)) for i in range(20)})
hmap2 = hv.HoloMap({i:hv.Image(i*np.random.rand(10,10)) for i in range(30)})
hmap1 + hmap2
```
If you try this, you'll get an exception in the plotting code :``KeyError: (29,)``

**Comment by philippjfr** [comment]
Seems to be a bug I introduced when reimplementing the ``select`` method. I've now fixed it and added a unit test to make sure this bug doesn't reoccur. I'll close the issue now, please reopen if necessary.
