### ISSUE TITLE
notebook server die when using datashader support in holoviews

### ISSUE THREAD

**Issue by fzhang00** [ioam/holoviews#1221]
I'm brand new in Holoviews/datashader/bokeh, but loves them. I was trying to use datashader in Holoview, but constantly ran into "server has died" message. 

My setup:  
* conda distribution (Python 3.5) under Linux Mint virtual machine. 
* Originally installed Holoviews 1.6.2, and discovered my dataset is too large to plot and would like to use the datashader support.
* Then I clone the master branch, installed using python setup.py install,  and ran the example notebook: https://anaconda.org/philippjfr/holoviews_datashader/notebook

I got a server died message every time when executing any of the aggregate cell. Can anyone please provide some pointer on how to get this working? Greatly appreciated.

**Comment by jbednar** [comment]
Are there any messages on the terminal where you started Jupyter that seem relevant (or maybe in the JavaScript console, which is less likely to be relevant)?  When I've seen problems like that, I've found messages on my terminal from some dependencies of datashader (not datashader itself).  E.g. there is a message from an HDF5 library that comes up, which is basically saying that various different libraries installed have incompatible versions, but I don't recall the details.  If you could post such messages if there are any, we can probably give advice.

**Comment by fzhang00** [comment]
- The Jupyter notebook command line output:

Intel MKL FATAL ERROR: Cannot load libmkl_def.so.

- locate libmkl on console and returns:

/home/fz/anaconda3/lib/libmkl_avx.so
/home/fz/anaconda3/lib/libmkl_avx2.so
/home/fz/anaconda3/lib/libmkl_avx512.so
/home/fz/anaconda3/lib/libmkl_avx512_mic.so
/home/fz/anaconda3/lib/libmkl_core.so
/home/fz/anaconda3/lib/libmkl_def.so
/home/fz/anaconda3/lib/libmkl_intel_ilp64.so
/home/fz/anaconda3/lib/libmkl_intel_lp64.so
/home/fz/anaconda3/lib/libmkl_intel_thread.so
/home/fz/anaconda3/lib/libmkl_mc.so
/home/fz/anaconda3/lib/libmkl_mc3.so
/home/fz/anaconda3/lib/libmkl_rt.so
/home/fz/anaconda3/lib/libmkl_sequential.so
/home/fz/anaconda3/lib/libmkl_vml_avx.so
/home/fz/anaconda3/lib/libmkl_vml_avx2.so
/home/fz/anaconda3/lib/libmkl_vml_avx512.so
/home/fz/anaconda3/lib/libmkl_vml_avx512_mic.so
/home/fz/anaconda3/lib/libmkl_vml_cmpt.so
/home/fz/anaconda3/lib/libmkl_vml_def.so
/home/fz/anaconda3/lib/libmkl_vml_mc.so
/home/fz/anaconda3/lib/libmkl_vml_mc2.so
/home/fz/anaconda3/lib/libmkl_vml_mc3.so
/home/fz/anaconda3/pkgs/mkl-11.3.1-0/lib/libmkl_avx.so
/home/fz/anaconda3/pkgs/mkl-11.3.1-0/lib/libmkl_avx2.so
/home/fz/anaconda3/pkgs/mkl-11.3.1-0/lib/libmkl_avx512.so                                                           
/home/fz/anaconda3/pkgs/mkl-11.3.1-0/lib/libmkl_avx512_mic.so                                                       
/home/fz/anaconda3/pkgs/mkl-11.3.1-0/lib/libmkl_core.so                                                             
/home/fz/anaconda3/pkgs/mkl-11.3.1-0/lib/libmkl_def.so                                                              
/home/fz/anaconda3/pkgs/mkl-11.3.1-0/lib/libmkl_intel_ilp64.so                                                      
/home/fz/anaconda3/pkgs/mkl-11.3.1-0/lib/libmkl_intel_lp64.so                                                       
/home/fz/anaconda3/pkgs/mkl-11.3.1-0/lib/libmkl_intel_thread.so                                                     
/home/fz/anaconda3/pkgs/mkl-11.3.1-0/lib/libmkl_mc.so                                                               
/home/fz/anaconda3/pkgs/mkl-11.3.1-0/lib/libmkl_mc3.so                                                              
/home/fz/anaconda3/pkgs/mkl-11.3.1-0/lib/libmkl_rt.so                                                               
/home/fz/anaconda3/pkgs/mkl-11.3.1-0/lib/libmkl_sequential.so                                                       
/home/fz/anaconda3/pkgs/mkl-11.3.1-0/lib/libmkl_vml_avx.so                                                          
/home/fz/anaconda3/pkgs/mkl-11.3.1-0/lib/libmkl_vml_avx2.so                                                         
/home/fz/anaconda3/pkgs/mkl-11.3.1-0/lib/libmkl_vml_avx512.so                                                       
/home/fz/anaconda3/pkgs/mkl-11.3.1-0/lib/libmkl_vml_avx512_mic.so                                                   
/home/fz/anaconda3/pkgs/mkl-11.3.1-0/lib/libmkl_vml_cmpt.so                                                         
/home/fz/anaconda3/pkgs/mkl-11.3.1-0/lib/libmkl_vml_def.so                                                          
/home/fz/anaconda3/pkgs/mkl-11.3.1-0/lib/libmkl_vml_mc.so                                                           
/home/fz/anaconda3/pkgs/mkl-11.3.1-0/lib/libmkl_vml_mc2.so                                                          
/home/fz/anaconda3/pkgs/mkl-11.3.1-0/lib/libmkl_vml_mc3.so      

Any suggestions?

Thanks.

**Comment by jbednar** [comment]
Sounds like it is indeed issues with dependency libraries.  You could try `conda remove mkl`, as mkl should speed things up somewhere but shouldn't be strictly required by anything.

**Comment by fzhang00** [comment]
Thank you. I uninstalled mkl, and it works. I then conda install mkl again. It installed a newer version (2017.0.1-0) as well as downgrading a number of packages. Now it no longer complain about mkl

**Comment by jbednar** [comment]
Sounds good!
