### ISSUE TITLE
Combining framewise and axiswise seems to be broken

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#123]
Consider the following HoloMap - note that the random values are scaling up with the frame number:

```python
import holoviews as hv
import numpy as np
hmap = hv.HoloMap({i:hv.Image(i*np.random.rand(10,10)) for i in range(1,10)})
```

Now if you use the opts magic framewise with ``%%opts Image {+framewise}``, you get the expected result (namely the displayed intensity no longer appears to increase over time). But if you use ``%%opts Image {+framewise +axiswise}``, it no longer looks this way (i.e framewise) even though there is no other axis to consider!

The same problem occurs displaying two HoloMaps side by side:

```python
%opts Image {+axiswise +framewise}
hmap1 = hv.HoloMap({i:hv.Image(10*np.random.rand(10,10)) for i in range(10)})
hmap2 = hv.HoloMap({i:hv.Image(i*np.random.rand(10,10)) for i in range(10)})
hmap1 + hmap2
```

The values in the second holomap are scaling up but this shouldn't be visible in the display because ``+framewise`` is set (and the first holomap shouldn't be affecting this because of ``+axiswise`` is also set) .

**Comment by philippjfr** [comment]
Pushed a fix to this in 7fd0e81, the logic to compute the appropriate ranges for the +axiswise/+framewise condition was slightly wrong. We really need a normalization notebook with lots of examples to ensure this doesn't occur again. I'll try to gather all my examples in one place and then investigate how easy it is to add notebooks that are tested but won't show up on the website (should be straightforward).

**Comment by jbednar** [comment]
Isn't having a tested but unpublished notebook as simple as having any other notebook and just not including a link to it in the tutorials web pages?  It would still be public in some sense, i.e. with results that are put online, but that seems like a feature rather than a bug since we can then pass around links to the failing test's output if we wish...

**Comment by jlstevens** [comment]
That seems reasonable but it does mean the testing notebook will be run twice: once for nosetests and then for creating the HTML output. This is fine as long as the testing notebook runs quickly (which it should).

I am in favor of this because it is the least effort solution! My main concern now is getting the version specific documentation configured...

**Comment by philippjfr** [comment]
That's all true, although if we want to add a bunch of them it might be annoying for all of them to be built. Remember that the website building code runs the notebooks twice, once for the tests and a second time to convert them to HTML. You are right though initially we can definitely just not add a link so they will be tested and even publicly available just not easily accessible from the website.

**Comment by jlstevens** [comment]
I think that for now we should focus on having the release version of the docs being easily accessed from the main website and a ``/dev`` subpath for the nightly dev builds. As long as testing notebooks run quickly, I think that we can just skip linking them from anywhere (for now at least).

We can always put the links on the wiki for our convenience...
