### ISSUE TITLE
Traceback in testing infrastructure

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#1234]
In the Options tutorial:

![image](https://cloud.githubusercontent.com/assets/890576/24463597/187804d8-149f-11e7-9a35-8e9653c6a8da.png)

Looks like there is an occasional bug in the testing infrastructure.

**Comment by philippjfr** [comment]
Not occasional, this is persistent in py3 and not just during testing.

**Comment by jlstevens** [comment]
I meant 'occasionally' as the failure only seems to happen for one output in Options. I agree this traceback always happens once in the py3 builds.

**Comment by philippjfr** [comment]
I can't seem to reproduce this locally.

**Comment by philippjfr** [comment]
@jlstevens Could you check if you can reproduce it?
