### ISSUE TITLE
Number of digits in title of HoloMap insufficient for small number changes

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#126]
I have a ```HoloMap``` for a range of numbers that lie close to one another.

For example for ```B = np.linspace(1.45, 1.55, 100)```:

![screen shot 2015-06-03 at 11 06 37](https://cloud.githubusercontent.com/assets/6897215/7956571/ec9a0cdc-09e0-11e5-895b-63d4916dd7a1.png)

I can only see 2 or 3 digits in the title, which is not sufficient.

Could you implement something which prevents if from showing the same title for constituent plots?

**Comment by jlstevens** [comment]
The title in your HoloMap is formatted by a dimension formatter. The following uses the default formatting behavior: 

```python
import holoviews as hv
import numpy as np
hv.HoloMap({f:hv.Image(np.random.rand(10,10)) 
            for f in np.linspace(0,0.05, 20)},key_dimensions=[Dimension('B')])
```

But if you want to show more precision in the title, you can define your own formatter:

```python
hv.HoloMap({f:hv.Image(np.random.rand(10,10))  for f in np.linspace(0,0.05, 20)},
          key_dimensions=[Dimension('B', formatter=lambda f: '{:.8f}'.format(f))])
```

I think that should help! If you want to change the precision used everywhere, just ask and we can tell you how to change the default formatter.

**Comment by basnijholt** [comment]
Thanks, but couldn't it be possible to implement something that takes care of this automatically?

Something like:
```python
x = np.linspace(0, 0.1, 50)
xstr = [str(i) for i in x]
j = 2
x_doubles = [i[:j] for i in xstr]
while len(x_doubles)!=len(set(x_doubles)):
    j+=1
    x_doubles = [i[:j] for i in xstr]
print(j, x_doubles)
```

**Comment by jlstevens** [comment]
We've discussed some ideas about how a user could set their own code to get the sort of behavior you propose. 

The basic idea is that you would write a small formatter class that would could get initialized with the displayed ``HoloMap`` in order to inspect the keys and decide on a suitable precision before being used. This initialization would happen in the plot class constructor to avoid lots of pointless re-initializations of the formatter.

Although this is certainly an idea worth considering, this is a feature request and therefore not something that will end up in the next 1.2.1 bug-fix release unless we find ourselves with some extra time to implement and test it properly.

**Comment by philippjfr** [comment]
In my opinion automatically doing the formatting taking into account all the keys is too much magic for it to be handled directly in HoloViews. I'd suggest setting an appropriate formatter on the Dimension much like I suggested here:

https://github.com/ioam/holoviews/issues/251

You can even write a little function which will give you a formatter with the required amount of significant digits given a list of values. Handling this within HoloViews as suggested above does not seem very general to me as the suggested solution would only work for HoloMap titles, which leaves legends, axes, widgets etc.. If we can come up with a general system that would handle all these cases I would consider it.

**Comment by jlstevens** [comment]
I agree with @philippjfr : we cannot support all the ways users may want to format strings. Our job should be to make the simple, common case easy whenever possible and then to allow easy customization by the user otherwise.

**Comment by philippjfr** [comment]
Okay, I think I'll close this issue then. Reopen if necessary.
