### ISSUE TITLE
Document bokeh interactive legends

### ISSUE THREAD

**Issue by thoth291** [ioam/holoviews#1265]
In my issue #1261 you can see multiple curves on one plot.
Is it possible to adopt recently pushed Interactive Legends in bokeh (https://github.com/bokeh/bokeh/pull/5349) so that the "cases" would be clickable and I could switch one "on" and "off"?
![image](https://cloud.githubusercontent.com/assets/2971670/24874979/15cde4b8-1dec-11e7-9d54-5286dc6547a1.png)

Or may be there is a better way of doing it using holoviews?

Thanks!

**Comment by philippjfr** [comment]
>Is it possible to adopt recently pushed Interactive Legends in bokeh (bokeh/bokeh#5349) so that the "cases" would be clickable and I could switch one "on" and "off"?

This is already implemented and enabled by default, e.g.:

![interactive_legend](https://cloud.githubusercontent.com/assets/1550771/24875230/5396b4ae-1e1f-11e7-9ce7-bbd40952eef8.gif)

You can control the alpha of the disabled Curve with ``muted_alpha``. There appears to be an issue with legend positioning in 0.12.5 that I will look at now though.

**Comment by philippjfr** [comment]
Reopening to document this behavior in the Bokeh_Backend tutorial.

**Comment by thoth291** [comment]
Thank you, @philippjfr !
BTW, I'm having some issues with hover not appearing in my example... It seems to be a browser issue - but I'm not positive...

**Comment by thoth291** [comment]
Hi, I noticed that `Datetime axes` example is broken on the website: http://holoviews.org/Tutorials/Bokeh_Backend.html
<img width="533" alt="screen shot 2017-06-22 at 9 26 20 pm" src="https://user-images.githubusercontent.com/2971670/27464238-ddf5f154-5791-11e7-83c8-7db15ae20490.png">

```python
%%opts Overlay [width=600 legend_position='top_left'] Curve (muted_alpha=0.5 muted_color='black')
try:
    import bokeh.sampledata.stocks
except:
    import bokeh.sampledata
    bokeh.sampledata.download()

from bokeh.sampledata.stocks import GOOG, AAPL
goog_dates = np.array(GOOG['date'], dtype=np.datetime64)
aapl_dates = np.array(AAPL['date'], dtype=np.datetime64)
hv.Curve((goog_dates, GOOG['adj_close']), kdims=['Date'], vdims=['Stock Index'], label='Google') *\
hv.Curve((aapl_dates, AAPL['adj_close']), kdims=['Date'], vdims=['Stock Index'], label='Apple')
AttributeError [Call holoviews.ipython.show_traceback() for details] 
unexpected attribute 'muted_color' to Line, similar attributes are line_color
```

Thanks in Advance.

**Comment by philippjfr** [comment]
Thanks @thoth291 we'll be bringing our new website up soon and this should be fixed then. It's simply because the old website appears to have been built with an old version of bokeh.

**Comment by philippjfr** [comment]
Documented in the PR referenced above.
