### ISSUE TITLE
Strange behaviour with datashader and layouts of HoloMaps with normalization turned off

### ISSUE THREAD

**Issue by dpow1** [ioam/holoviews#1272]
Adapting the example HoloMap code from the Holoviews_Datashader notebook [here](https://anaconda.org/philippjfr/holoviews_datashader/notebook) to produce a layout of two datashaded HoloMaps gives the expected output:

```python
%%opts Layout plot[shared_axes=False, normalize=True]
hmap1 = hv.HoloMap({i: hv.Points(np.random.multivariate_normal((i*5,i*5), [[0.1, 0.1], [0.1, 1.0]], (100000,)))
                   for i in range(10)})
hmap2 = hv.HoloMap({i: hv.Points(np.random.multivariate_normal((i/2,i/2), [[0.1, 0.1], [0.1, 1.0]], (100000,)))
                   for i in range(10)})

aggregate(hmap1, x_range=hmap1.range('x'), y_range=hmap1.range('y')) + aggregate(hmap2, x_range=hmap2.range('x'), y_range=hmap2.range('y'))
```

![expected output](https://cloud.githubusercontent.com/assets/27284829/24910895/7baa919a-1ec9-11e7-857a-ea8364ce1e68.PNG)

However, attempting to zoom in on one or the other plot when the slider is set to anything other than the default value (1 in this example) causes the zoomed plot to disappear, and the non-zoomed plot to reset to the plot corresponding to the default slider value.

![zooming](https://cloud.githubusercontent.com/assets/27284829/24910513/4e465f82-1ec8-11e7-9a35-a67c677bb71a.png)

![plot disappears](https://cloud.githubusercontent.com/assets/27284829/24910519/4f3fc220-1ec8-11e7-8f90-e294bc3ad82f.png)

This problem only occurs with `normalization=False` set in the Layout opts.

**Comment by philippjfr** [comment]
Are you running on current master? I can't seem to reproduce this issue. Also what does the JS console in your browser say, that's usually the first thing to check. Apart from that the weird widget layout suggests to me you cleared the notebook cell which contains BokehJS and HoloViewsJS, which can cause all kinds of issues.

**Comment by philippjfr** [comment]
Okay nevermind, I can reproduce it now. It seems to occur if no data falls inside the current zoom region. Will have to think more about this.

**Comment by philippjfr** [comment]
Okay, I've tried this out and discovered some issues. Once https://github.com/ioam/holoviews/pull/1274 is merged this should work correctly although you can still get white frames when you select a region with no data in it. Your code will work fine if you don't want the slider to update the ranges, if you do want the slider to update the ranges you'll have to do this:

```
%%opts Layout plot[shared_axes=False normalize=False] Image {+framewise}
hmap1 = hv.HoloMap({i: hv.Points(np.random.multivariate_normal((i*5,i*5), [[0.1, 0.1], [0.1, 1.0]], (100000,)))
                   for i in range(10)})
hmap2 = hv.HoloMap({i: hv.Points(np.random.multivariate_normal((i/2,i/2), [[0.1, 0.1], [0.1, 1.0]], (100000,)))
                   for i in range(10)})

aggregate(hmap1, x_range=hmap1.range('x'), y_range=hmap1.range('y'),
         streams=[hv.streams.RangeXY(transient=True)]) +\
aggregate(hmap2, x_range=hmap2.range('x'), y_range=hmap2.range('y'),
         streams=[hv.streams.RangeXY(transient=True)])
```

Note the ``Image {+framewise}`` which tells the plot to update the ranges on each frame and the ``transient`` argument to the ``RangeXY`` streams, which makes the ``x_range`` and ``y_range`` on the stream reset to its default value, i.e. ``(None, None)``, and therefore forces the datashader operation to auto-range on the data. I'm still considering how to automate the ``transient`` part so a user doesn't have to declare those Streams themselves.

**Comment by dpow1** [comment]
Brilliant, can confirm it's working on both the example code and my actual project as expected. Thanks for your help.

**Comment by philippjfr** [comment]
Great to hear and thanks for reporting this, it helped me catch some crucial bugs at just the right time.
