### ISSUE TITLE
Initial flickering using JavaScript widgets

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#131]
The flickering is something that has annoyed us for a while so it is worth filing an Issue to remind us to try and finally get this sorted.

Once you have looked at all the frames, the flickering tends to cease - hopefully this means we'll  be able to find a workable JavaScript fix.

**Comment by philippjfr** [comment]
After a long night I've just pushed a complete refactor of the SelectionWidgets in fc7dd2b051, which should address this issue. When instantiating the widget all output is now cached inside the DOM and simply hidden or revealed appropriately. This should massively cut down on rendering times and avoid flicker in almost all cases.

It would be great if anyone who experienced the flickering issue before could report whether they're still experiencing the issue.

**Comment by jlstevens** [comment]
Sounds great!

I think the approach is sound: when exported, the base64 data is encoded in the file anyway (no difference in space consumed), and I cam sure browsers are sensibly optimized to skip over invisible nodes in the DOM.

That said, the browser *must* be doing a little more work when initially loading the widget in order for us to benefit from the improved performance on playback.

My three concerns are:

* Will this approach be usable for the upcoming dynamic map widgets? I think so but we might want some system to also *remove* DOM nodes as well to free up memory (e.g a limited cache size).
*  The widget code is the code I have the most difficulty understanding in the whole of HoloViews. Something to make it a bit clearer would be nice - maybe more comments in the file itself or maybe a wiki page outlining how these JavaScript widgets work...
* As always you have to worry whether these changes will work well across browsers. As long as behavior is improved in modern Firefox, Chrome and Safari, I am happy.

Definitely something we want to release before SciPy, assuming we build our presentation using IPython Notebook and HoloViews!

**Comment by philippjfr** [comment]
>* Will this approach be usable for the upcoming dynamic map widgets? I think so but we might want some system to also remove DOM nodes as well to free up memory (e.g a limited cache size).

This should be trivial to add, the Javascript slider class keeps track of all the cached DOM elements, so they can be destroyed by calling the ``remove`` method.

> * The widget code is the code I have the most difficulty understanding in the whole of HoloViews. Something to make it a bit clearer would be nice - maybe more comments in the file itself or maybe a wiki page outlining how these JavaScript widgets work...

Sure more documentation is always good. Eventually we'll actually want to ship an explicit ``js`` file containing just the widget classes so that the templates that are inserted into the notebook do not duplicate the widget classes each time. This would be a lot cleaner and give me a central place to write docstrings.

> * As always you have to worry whether these changes will work well across browsers. As long as behavior is improved in modern Firefox, Chrome and Safari, I am happy.

I've not used any particularly advanced functionality that relies on the latest browsers but as we all know there will be browsers (IE<9), where things will break. However I do believe it should work across all modern browsers.

**Comment by philippjfr** [comment]
I think my changes to the way the widgets work seem to have mostly resolved the flickering. If the flickering persists now we can only recommend using one of the latest versions of Chrome/Chromium. Any further bugs should be raised as a separate issue, so I'll close this now.
