### ISSUE TITLE
holoviews.notebook_extension() overrides %matplotlib inline

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#1314]
<img width="549" alt="screen shot 2017-04-18 at 20 44 55" src="https://cloud.githubusercontent.com/assets/6897215/25147471/f15c0032-2477-11e7-8a7f-4d897a1d750b.png">

```
%matplotlib inline 
import holoviews
import matplotlib.pyplot as plt
holoviews.notebook_extension()
```

**Comment by jlstevens** [comment]
Odd! Thanks for reporting this.

And everything is fine if you set ``%matplotlib inline`` after loading the extension?

**Comment by basnijholt** [comment]
It doesn't always work, I changed the order [here](https://gitlab.kwant-project.org/qt/topocm/commit/ec3ca877a89092ee05d26825d78c22dae5054b35), but the matplotlib plots are still missing [here](https://nbviewer.jupyter.org/url/test.topocondmat.org/notebooks/w3_pump_QHE/QHEedgestates.ipynb?flush_cache=true#Quantization-of-Hall-Conductance-from-edge-states).

Not sure if the same behaviour is reproduced by my simple example...

**Comment by philippjfr** [comment]
What's changed here is that the ``plt.switch_backend('agg')`` is now no longer executed when importing holoviews matplotlib backend instead it's executed when running ``hv.notebook_extension()``. I'd be very surprised if simply moving ``%matplotlib inline`` after the notebook extension didn't fix it. Indeed when I do this, it seems to work fine:

```python
import holoviews as hv
import numpy as np

hv.notebook_extension('matplotlib')
points = [(0.1*i, np.sin(0.1*i)) for i in range(100)]
hv.Curve(points)
```

And in a second cell:

```python
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

x = np.linspace(0, 1, 500)
y = np.sin(4 * np.pi * x) * np.exp(-5 * x)

fig, ax = plt.subplots()

ax.fill(x, y, zorder=10)
ax.grid(True, zorder=5)
```

Is there anything different about your setup?

**Comment by basnijholt** [comment]
The problem is the following:

<img width="1097" alt="screen shot 2017-04-19 at 10 04 27" src="https://cloud.githubusercontent.com/assets/6897215/25169532/a9f21ef0-24e7-11e7-98c7-54a2358bfd6e.png">


<img width="1097" alt="screen shot 2017-04-19 at 10 05 19" src="https://cloud.githubusercontent.com/assets/6897215/25169555/bbbf3ef6-24e7-11e7-95b8-82ff2e469f76.png">

You see that the order matters. So if a `holoviews` object is plotted first, the matplotlib object isn't plotted anymore.
