### ISSUE TITLE
Sorting table by column does not interpret scientific representation of number correctly

### ISSUE THREAD

**Issue by fzhang00** [ioam/holoviews#1317]
I'm was trying the sorting function of a hv.Table object, and noticed that the scientific representation of number is treated desperately from standard representation, and sorted in two trunk. Please see the screen capture attached. I was sorting the column "moment" from big to small, and notice the number jump from 70810 to 1.1466e+05

The backend is bokeh
Holoview version: 1.6.2

![image](https://cloud.githubusercontent.com/assets/4636221/25151749/c5414980-2454-11e7-82ec-e8e53f92029a.png)

**Comment by philippjfr** [comment]
A fix has now been merged.
