### ISSUE TITLE
A more convenient constructor for Curve

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#133]
People used to matplotlib may find the requirement to supply the x values to a ``Curve`` annoying. I don't see why the ``Curve`` constructor couldn't just take a list/array of y-values and automatically generate the x-values by the index.

**Comment by philippjfr** [comment]
I've added the new constructor in the commit above. All ``Chart`` Element types may now be instantiated with a simple iterable of y-values, e.g. this is now valid:

```python
hv.Curve(range(10))
```
![image](https://cloud.githubusercontent.com/assets/1550771/7982902/e40aedd4-0ab2-11e5-8aa6-6729ffad45c1.png)

I'll close the issue now.

**Comment by jlstevens** [comment]
Ok great!

Now we must remember that the reason for this change is so that ``Curve`` is just as usable for quick  plotting as ``plt.plot``.
