### ISSUE TITLE
Alias key_dimensions and value_dimensions to kdims and vdims

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#135]
When developing HoloViews, the long explicit names helped keep these two concepts straight. From a user perspective, they are far too long, even though they tab-complete. Being concise is one of the major features we are using to promote HoloViews!

Making aliases called ``kdims`` and ``vdims`` would be easy by looking for these keywords in the ``**params`` passed to the ``Dimensioned`` base class where we can pop them and set the full names appropriately.

If it weren't for pickling, I would prefer to rename the actual parameters to ``kdims`` and ``vdims`` and make the long versions the aliases for backwards compatibility. A separate pickle-hackery file called ``legacy.py`` is out of the question but I do think a few careful lines of  code in ``__getstate__`` and ``__setstate__`` could do the trick.

Alternatively, at a stretch, we could have a *small* class in ``core/dimension.py`` containing *a tiny bit* of pickle hackery to be accessed by ``__getstate__/__setstate__`` that we *promise* to keep to a minimum!

One very nice thing about the way HoloViews is designed (and something to mention in the SciPy paper!) is that the separation between the elements (that get pickled) and plotting code minimizes the API exposed to the pickling process. I am fairly confident that I am happy with the API used by our elements *except* for the names of these two parameters!

If pickle hacking is out of the question, we face the following problems:

* Documentation will be about ``key_dimensions`` and ``value_dimensions`` even though we hope to switch to ``kdims`` and ``vdims`` throughout.
* Tab-completion will tab complete the long versions without hacking the param generated class/``__init__`` docstrings. In other words, this needs hacking but only affecting a non-critical feature (and not the pickling itself).

Anyway, I would like this addressed by 1.2.1. I don't want to give a SciPy talk about how succinct HoloViews is with those long names showing!

**Comment by philippjfr** [comment]
This was a fairly major refactoring job but I definitely think it was worthwhile. We've also added a ``param_aliases`` function called in the ``__setstate__`` allowing old pickles to be loaded. Both the shorthand (e.g. kdims) and longhand (e.g. key_dimensions) form may now be used however we recommend using the short form and reserve the right to eventually deprecate the long version.
