### ISSUE TITLE
Update conda-forge recipe

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#1364]
This issue is a reminder to update the conda-forge recipe after every release.

**Comment by jlstevens** [comment]
I believe @basnijholt has kindly offered to be our conda-forge recipe maintainer and I think everything is currently up to date!

Reassigning to 1.7.1 as that is our next planned release...

**Comment by jlstevens** [comment]
Version 1.8 is released! 😄 

If @basnijholt isn't around, I'll look at updating the conda forge recipe myself. Bumping to the next milestone.

**Comment by basnijholt** [comment]
I am on my holidays, but return in three days, then I could do it. However,
it's also really trivial to do ;)

**Comment by jlstevens** [comment]
@basnijholt Thanks for the update!

I'll do it so you can enjoy the rest of your holidays!

**Comment by philippjfr** [comment]
Do we really want to bump this issue through every release? Surely it should just be part of the release instructions.

**Comment by jlstevens** [comment]
The feedstock still isn't updated: https://github.com/conda-forge/holoviews-feedstock/pull/8

**Comment by philippjfr** [comment]
Looks like there's no NumPy in the test environment:

>ImportError: No module named numpy
>Traceback (most recent call last):
>  File "C:\Miniconda\Scripts\conda-build-script.py", line 5, in <module>

**Comment by jlstevens** [comment]
As you say, I don't see why this would have changed.

**Comment by jakirkham** [comment]
Just trying to get context, is this still tracking a known issue or is this just part of the release process?

**Comment by jlstevens** [comment]
I guess it is a latter - an issue we keep open to remind us to update on conda-forge!

**Comment by jakirkham** [comment]
Cool. Just wanted to make sure that we hadn't missed some lingering issues. :)

**Comment by jlstevens** [comment]
Just a note that after PR #2528 and the new configuration for dev releases on conda-forge, a number of changes will be needed for this release, in addition to the usual version bump.

**Comment by philippjfr** [comment]
Can we close this? I'd really prefer for this to become part of some release checklist rather than having an issue that gets bumped from release to release.

**Comment by jlstevens** [comment]
> Can we close this? I'd really prefer for this to become part of some release checklist rather than having an issue that gets bumped from release to release.

I agree that this should be on a checklist instead of an issue though I would like to have pyct and the new workflow configured for holoviews before writing that checklist and closing this issue. Ideally the new checklist would have detailed steps on *how* to update conda forge e.g getting the rendered recipe to have the up-to-date dependencies etc.

In short I wouldn't close it *just* yet but yes, let us not bump it up again to the next release.

**Comment by philippjfr** [comment]
I'm closing this now, yes we want to switch to pyct but I think it's self-evident that conda-forge recipes need to be updated and this issue hasn't been reassigned since the last 3 micro releases.
