### ISSUE TITLE
Improved tick labels on Histograms

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#137]
This is an issue mentioned in in #124

**Comment by jlstevens** [comment]
I assume this has been improved since switching back to maplotlib's ticking behavior by default?

**Comment by philippjfr** [comment]
Yes we've now switched to the default matplotlib ticking behavior in most places but I've also pushed a fix for easily labeling the edges of a Histogram, which is the behavior it'll use when you supply an integer to the xticks plot options. I'll close this issue now.
