### ISSUE TITLE
Suggestion: ignore options if not used by backend

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#1373]
Right now the following happens:

<img width="1092" alt="screen shot 2017-04-26 at 12 58 50" src="https://cloud.githubusercontent.com/assets/6897215/25431265/23403c5e-2a80-11e7-9681-cb899025db3b.png">

Sometimes I change `hv.notebook_extension('matplotlib')` to `hv.notebook_extension('bokeh')` temporarily to zoom. 

Right now I need to comment out all the options that are incompatible.

It would be nice to still see the plots and just print a warning.

**Comment by philippjfr** [comment]
Just use ``hv.notebook_extension('matplotlib', 'bokeh')``, it will pick the first backend in the list but load all of them and validation applies to all **loaded** backends.

**Comment by jlstevens** [comment]
@basnijholt Are there any particular reasons why you wouldn't want to load both bokeh and matplotlib at the top, even if you only use one at a time?

Philipp's suggestion is correct and it should work once both backends are loaded. This issue might be something we can refer to if other people bump into this while we update the docs.

@philippjfr Have we documented this and if we haven't where should we?

**Comment by philippjfr** [comment]
>@philippjfr Have we documented this and if we haven't where should we?

No I don't think this has been properly documented, not sure where would be best.

**Comment by jbednar** [comment]
A release page would be a great idea.  I do think we can do a little bit just on the release notes, to fill in the "backwards compatibility" section with practical implications.

That said, I don't know why the plot isn't being shown even when there are incompatible options; why is that not just a warning?

**Comment by jlstevens** [comment]
> That said, I don't know why the plot isn't being shown even when there are incompatible options; why is that not just a warning?

It is probably too late to make it into a warning now - the behavior is similar to the validation we had previously before we turned it off.

The issue might be that the current message isn't quite clear enough. In @basnijholt screenshot above you have: 'Possible keywords in the currently active 'bokeh' backend are: ....

How can this be rephrased to make the correct fix easier to discover? The message is technically correct but it would have been better if it could have pointed to ``hv.notebook_extension('matplotlib', 'bokeh')`` as the solution.

Something along the lines of:

> Invalid keyword for the currently active 'bokeh' backend, please make sure that all the required backends are loaded in the notebook extension. Possible keywords in the loaded backends are: ....

The other thing I want to fix in the screenshot above is the ``repr`` - it is showing the raw repr and not being formatted correctly. I'll open an issue about that.

**Comment by jbednar** [comment]
> > That said, I don't know why the plot isn't being shown even when there are incompatible options; why is that not just a warning?
> It is probably too late to make it into a warning now - the behavior is similar to the validation we had previously before we turned it off.

@philippjfr, what do you think?  I personally don't see why anyone wouldn't want to see the plot, even if the option isn't valid.   We'll have the same issue if someone uses an old notebook with outdated options; people should know that the option is being ignored, but it's hard to see why people would want their plots not to appear at all!  This seems like a particularly acute issue for notebooks generated as reports or in other situations where it is difficult to re-run them.

**Comment by philippjfr** [comment]
>what do you think? I personally don't see why anyone wouldn't want to see the plot, even if the option isn't valid.

I completely agree, I think I already insisted on a warning rather than an error in a similar case.

**Comment by jlstevens** [comment]
Isn't the solution just to load all the required backends? I thought we discussed this already!

**Comment by jbednar** [comment]
No, like I said, the same issue will come up whenever someone uses an outdated option.  Even if it's just a typo, why should a typo cause there to be no output, e.g. in the middle of some long notebook that takes ages to run? Would you want your HTML page to just show an exception, or would you rather it show slightly wonky output but still show *something*?  I think the latter.

**Comment by philippjfr** [comment]
I also think this precisely the point of having the separation between data and options, even if some options fail to apply your data is central and should still display itself. The output of warning being ugly is something we can work around.

**Comment by jlstevens** [comment]
I've implemented the suggestion in the PR above.
