### ISSUE TITLE
Obscure case in which Bokeh option not ignored when both backends loaded

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#1376]
Usually, with the current hv master, options valid for at least one loaded backend are ignored, even if not valid for the current backend. However, in the complicated case below that does not seem to be true:

![image](https://cloud.githubusercontent.com/assets/1695496/25443447/7a899734-2a6d-11e7-8057-b06696ff33c8.png)

The error goes away when using the bokeh backend, or when removing various bits of the offending cell ("datashade", "HoloMap", etc.).  Seems to be happening for a HoloMap with an associated operation?

**Comment by jlstevens** [comment]
I believe this issue has been fixed in #1375. Closing.

@jbednar Can you confirm this is fixed? If it isn't I'm happy to reopen this issue.

**Comment by jbednar** [comment]
Looks good so far!
