### ISSUE TITLE
links to obsolete mpld3 on holoviews.org

### ISSUE THREAD

**Issue by jordansamuels** [ioam/holoviews#1378]
Given that mpld3 is no longer supported (discussion with @philippjfr), we should consider removing/modifying these locations/pages/links:

* http://holoviews.org/install.html?highlight=mpld3 (mentions mpld3 in middle of page)
* http://holoviews.org/Tutorials/Options.html?highlight=mpld3 (`style` options: mentions 'e.g. mpld3')
* http://holoviews.org/Examples/index.html?highlight=mpld3 (first link in **Extensions** links to http://philippjfr.com/blog/interactive-plots-with-holoviews-and-mpld3/)
* http://holoviews.org/features.html?highlight=mpld3 (Visualization features, last bullet)
* http://holoviews.org/Reference_Manual/holoviews.plotting.mpl.html?highlight=mpld3 (mentions hooks module)

**Comment by jbednar** [comment]
Can any of them be replaced with a link to nbagg?  I.e., is nbagg ever a good substitute?

**Comment by jlstevens** [comment]
> Can any of them be replaced with a link to nbagg? I.e., is nbagg ever a good substitute?

Personally, I think nbagg feels very different from what mpld3 offered. I would be in favor of removal as opposed to substitution.

**Comment by philippjfr** [comment]
Bokeh offers what mpld3 did before (except for the matplotlib conversion aspect), so where appropriate that's the correct substitution I think.

**Comment by jlstevens** [comment]
I agree. Though that means removing mentions of mpld3 and only mentioning bokeh instead if it is in relation to something that hasn't already been described as part of the bokeh backend.

**Comment by jlstevens** [comment]
Addressed in the PR referenced above.
