### ISSUE TITLE
HoloMaps broke, now stacking up all images.

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#138]
```python
test = {1: hv.Image(np.random.rand(10,10)), 2: hv.Image(np.random.rand(10,10))}
hv.HoloMap(test)
```

![screen shot 2015-06-05 at 17 13 43](https://cloud.githubusercontent.com/assets/6897215/8009056/48d7e6ec-0ba6-11e5-8853-b10059624ee0.png)

**Comment by jlstevens** [comment]
Can you pull and see if the issue persists? Philipp's commit above certainly prevents this bad behavior, at least in some cases (namely dragging the slider).

**Comment by basnijholt** [comment]
It works again!

**Comment by philippjfr** [comment]
Great news and thanks for confirming it that quickly, I was worried we'd not be able to reproduce it. I really need to find some solution to test the Javascript code across at least a few browsers and systems.
