### ISSUE TITLE
Problems with Stream

### ISSUE THREAD

**Issue by derCodemeister** [ioam/holoviews#1389]
I installed via conda (Ananconda3-4.3.1-Linux-x86_64) on Ubuntu 17.04 with
conda install -c ioam holoviews bokeh 
This installed holoviews 1.6.2-py36_0 ioam
Hoever, examples from holoviews-contrib will not run, since 
from holoviews.streams import Stream
will fail with a missing module streams.  

Checking within site-packages/holoviews reveals, that the files streams.py und util.py (as availaible on GitHub) are missing. If I copy them there manually from Github, then Stream fails with a missing "disable_constant" attribute in "holoviews.core.util".

**Comment by jlstevens** [comment]
You probably need to use the ioam channel. Try installing as follows to get the latest version (1.7):

```bash
conda install -c ioam holoviews
```

Then the examples should work.

**Comment by jbednar** [comment]
The post says that the ioam channel was used already, but yes, clearly an old version is installed, not anything recent like you should get from ioam.  Maybe post the output from doing the conda install command?

**Comment by jlstevens** [comment]
> The post says that the ioam channel was used already

Good point. I spotted ``1.6.2-py36_0`` and immediately gave the suggestion as that should be getting 1.7 installed, not 1.6 as you noted.

**Comment by derCodemeister** [comment]
The version mismatch was indeed the problem.
I did a clean reinstall with Anaconda3 4-3-1, followed by
conda update --prefix /opt/anaconda3 --all
conda install -c ioam holoviews
conda list holoviews 
gives
holoviews  1.7  py36_0  ioam

Without the update --all  conda seems to have pulled an older version of holoviews

**Comment by jlstevens** [comment]
> Without the update --all conda seems to have pulled an older version of holoviews

That is somewhat surprising but I'm glad you managed to resolve this issue!
