### ISSUE TITLE
Remove holoviews.interface subpackage

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#1394]
Everything in this subpackage is either deprecated or about to be deprecated with more solid support elsewhere in HoloViews.

**Comment by philippjfr** [comment]
We could move ``Collector`` somewhere now. Did we agree we'd move it to topographica?

**Comment by jlstevens** [comment]
> Did we agree we'd move it to topographica?

I think so.

**Comment by philippjfr** [comment]
Done.
