### ISSUE TITLE
Optimize static elements on both data and element id

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#1396]
Currently only the data id is used in this optimization. If both the element and the data id were used, I think it would still work where it needs to without causing confusing behavior when working with mutable data.

**Comment by jlstevens** [comment]
After discussing this with Philipp we decided we might want something like this:

```python
def plot_id(obj):
   if hasattr(obj, '_plot_id'): 
      return obj._plot_id
   else: 
      return id(obj)
```

And then the ``clone`` method can transfer the parent ``_plot_id`` to the clone output. With something like:

```python
   if self._plot_id is not None:
      clone._plot_id = self._plot_id
```
Hopefully this will allow the static source optimization to work better without worrying about the various uses of ``clone`` in the plotting code.

**Comment by philippjfr** [comment]
The fix described above has now been merged.
