### ISSUE TITLE
Added link_inputs switch to DynamicMap clone

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#1398]
In PR #1384 while reviewing the linked streams tutorial, I noticed that ``Dynamic`` was being used to effectively make a clone, the only reason being to set ``link_inputs=False``.

We could allow ``DynamicMap.clone`` to support this argument so ``Dynamic`` isn't used to make clones this way. We could also support this switch everywhere in ``clone`` and it would just do nothing for things that aren't dynamic.

**Comment by jlstevens** [comment]
@philippjfr Like the idea? Just add the switch to ``DynamicMap.clone``?

**Comment by philippjfr** [comment]
Yes, I think that's a good idea.

**Comment by jlstevens** [comment]
Addressed in the PR mentioned above (#1464). Closing.
