### ISSUE TITLE
Bokeh marker orientation API has changed

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#1403]
API for setting the marker orientation seems to have changed this no longer works:

```
hv.Points(([1,2],[3,4]))(style=dict(marker='^'))
```

>**AttributeError** [Call holoviews.ipython.show_traceback() for details]
unexpected attribute 'orientation' to Triangle, possible attributes are angle, angle_units, fill_alpha, fill_color, js_event_callbacks, js_property_callbacks, line_alpha, line_cap, line_color, line_dash, line_dash_offset, line_join, line_width, name, size, subscribed_events, tags, x or y

Presumably needs to be updated to use ``angle``.

**Comment by jlstevens** [comment]
The PR referenced above that fixes this has been merged. Closing.
