### ISSUE TITLE
Pandas 0.20.1 compatibility

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#1410]
Pandas 0.20.1 has been released with some [backward incompatible changes](http://pandas.pydata.org/pandas-docs/stable/release.html). Based on a quick scan of the changelog the deprecation of ``.ix`` stands out to me as we use it in ``.select``. This should be a trivial fix, but I'll have to do some testing to see if there's more issues.

**Comment by ea42gh** [comment]
Issue with holoviews/pandas/dask
--------------------------------------------------
----> 6 import holoviews as hv
/usr/lib/python3.5/site-packages/holoviews/core/__init__.py in <module>()
----> 2 from .data import *            # noqa (API import)
/usr/lib/python3.5/site-packages/holoviews/core/data/__init__.py in <module>()
---> 11 from ..dimension import redim
/usr/lib/python3.5/site-packages/holoviews/core/dimension.py in <module>()
---> 14 from ..core.util import (basestring, sanitize_identifier,
     15                          group_sanitizer, label_sanitizer, max_range,
     16                          find_range, dimension_sanitizer, OrderedDict,
/usr/lib/python3.5/site-packages/holoviews/core/util.py in <module>()
---> 32     import dask.dataframe as dd
/usr/lib/python3.5/site-packages/dask/dataframe/__init__.py in <module>()
      1 from __future__ import print_function, division, absolute_import
----> 3 from .core import (DataFrame, Series, Index, _Frame, map_partitions,
      4                    repartition, to_delayed)
/usr/lib/python3.5/site-packages/dask/dataframe/core.py in <module>()
---> 40 pd.computation.expressions.set_use_numexpr(False)
AttributeError: module 'pandas' has no attribute 'computation'

**Comment by ea42gh** [comment]
The problem was resolve by upgrading dask to version 0.14.3

**Comment by ea42gh** [comment]
holoviews/core/util.py:27: FutureWarning: pandas.tslib is deprecated

**Comment by jlstevens** [comment]
@philippjfr Is this purely a pandas/dask issue that we need to be aware of but otherwise has nothing to do with our end?

**Comment by philippjfr** [comment]
>Is this purely a pandas/dask issue that we need to be aware of but otherwise has nothing to do with our end?

That dask ``pandas.computation`` error is the remainder I've just opened a PR for.

**Comment by philippjfr** [comment]
All the required fixes were merged. Closing.
