### ISSUE TITLE
Output with bokeh exports faulty html file

### ISSUE THREAD

**Issue by jendas1** [ioam/holoviews#1411]
Hi,
I have tried outputing html file with jupyter magic:
```python
%%output filename="holoviews"
x = [1, 2, 3, 4, 5]
y = [6, 7, 2, 4, 5]
hv.Curve((x,y),label="Temp")
```
but the resulted file displays nothing.
After further investigation I was able to see an output by adding sources to bokeh.js and bokeh.css from cdn.
The faulty output html: https://pastebin.com/1eCSYaUn

**Comment by philippjfr** [comment]
Fixed by the PR referenced above. Closing.
