### ISSUE TITLE
Simplify core operation classes

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#1419]
In PR #1391 we finally started documented operations. While doing through this tutorial in #1384, we realized that we hardly *ever* use anything other than ``ElementOperation``.

``MapOperation`` has never been used to our knowledge and its definition is so light a user might as well just write their own ``param.ParameterizedFunction``. This just leaves ``TreeOperation`` which has only been used by the holoviews devs in a few places (in particular, one operation in featuremapper is a tree operation).

My recommendation is as follows:

* Remove ``MapOperation`` entirely
* Fold the current ``Operation`` baseclass into ``ElementOperation``
* Rename ``ElementOperation`` to ``Operation`` (a better name for users).
* Leave a ``class ElementOperation(Operation):`` definition just to issue a deprecation warning.
* Remove ``TreeOperation``, factoring any general and useful functionality into a utility.

This plan maintains backwards compatibility as we never used or documented ``MapOperation`` and ``TreeOperation`` is very unlikely to be used by users as it is needed for rare, more complex tasks (and was also undocumented).

Having a single ``Operation`` base class would simplify things a lot!

**Comment by jlstevens** [comment]
Everything suggested in this issue has been addressed by the PR referenced above (#1421) except for removing ``TreeOperation``.

@philippjfr Happy for me to just remove it from HoloViews and add it to featuremapper?

**Comment by philippjfr** [comment]
Sure, as long as you update the imports in topographica as well.

**Comment by jlstevens** [comment]
The final bit (removing ``TreeOperation``) was merged in the PR above. Closing.
