### ISSUE TITLE
Move plotting backend unit tests into plotting modules

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#1422]
Currently all our unit tests live in the top-level tests directly including various plotting unit tests in testplotinstantiation.py. In preparation for splitting the plotting backends out we should start moving these tests into the appropriate backend specific plotting modules, and organize them by plotting class with the eventual aim that all plotting classes have their own set of unit tests.

**Comment by jlstevens** [comment]
Absolutely agree with this. Assigning to the 1.8 milestone as that is when I would like to see the backends split out.
