### ISSUE TITLE
Bokeh Tab titles should use subplot title

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#1425]
Currently when you use the ``tab=True`` option for Layouts and Overlays it uses the group.label path of the object in the subplot as the title of tabs. Instead it should simply use the title of the subplot, so it can be controlled as normal via the ``title_format``.

**Comment by jlstevens** [comment]
Makes sense but what if you have lots of tabs and long titles? Truncate the titles?

**Comment by philippjfr** [comment]
>Makes sense but what if you have lots of tabs and long titles? Truncate the titles?

I'll see what the behavior is, tabs have a fixed width so it's probably truncated automatically.

**Comment by philippjfr** [comment]
The fix for this has now been merged.
