### ISSUE TITLE
Redimensioning a Histogram along the x-Axis doesn't work

### ISSUE THREAD

**Issue by tinloaf** [ioam/holoviews#1432]
I'm trying to increase the range of the x axis of a histogram like so:

hv.Histogram([5, 6, 7], [0, 1, 2]).redim.range(x=(0,100))

The expected result is a histogram in which the x axis ranges from 0 to 100, but it only goes to 2.5 for me.

I'm using HoloViews 1.7.0.

**Comment by philippjfr** [comment]
This should be fixed by the PR referenced above, and will soon be in the 1.8.0dev1 build
