### ISSUE TITLE
Axis are not updated when using DynamicMap and aggregate or datashade with bokeh backend

### ISSUE THREAD

**Issue by sebp** [ioam/holoviews#1434]
I'm using a `DynamicMap` that generates plots with varying x and y ranges. When used in combination with `aggregate` or `datashade` from the `holoviews.operation.datashader` module and the bokeh backend, changing the key dimension does not update the range of the axis. The notebook at https://anaconda.org/sebp/holoview_datashader_update_axis_issue demonstrates the problem.

I get the expected behaviour when not using the bokeh backend or not using `aggregate`/`datashade`, hence I assume it's a combination of both that causes this problem.

**Comment by philippjfr** [comment]
You correctly set the +framewise option, so it should definitely be working. I'll try to investigate asap.

**Comment by philippjfr** [comment]
Actually I realize what the issue is now, the ``aggregate/datashade`` operations attach a ``RangeXY`` stream which persists the ranges when you drag the slider. The solution is to explicitly create a ``RangeXY`` stream and initialize it as ``transient``, this means that while it's inactive it resets to None allowing it to auto-range. It will look like this:

```python
%%opts Image {+framewise}
aggregate(hmap, width=400, height=400, streams=[hv.streams.RangeXY(transient=True)])
```

**Comment by philippjfr** [comment]
I have to think about whether the RangeXY stream should be transient by default. The issue is definitely not obvious to a user so we should definitely do something (in addition to documenting this well) to make it clearer.

**Comment by sebp** [comment]
Thanks for the quick reply. I can confirm that adding the suggested parameter results in the expected behaviour. I probably don't understand the technical details, but in my opinion I should obtain the same results with each backend, which as far as I can tell can be achieved by setting the default value of transient to True.

**Comment by philippjfr** [comment]
This has been documented in the LinkedStreams tutorial which will probably become a user guide.
