### ISSUE TITLE
Make it easy to suppress linked stream parameters

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#1437]
Currently, when a linked stream has lots of stream parameters, the user is forced to handle them somehow, even if it means dumping extra arguments into ``**kwargs`` in their callback.

Instead of forcing users to use ``**kwargs`` for stream values they aren't interested in, it might be nice to allow explicit suppression of these  parameters. Here is one suggestion I think is reasonable:

```python
Drag(x=0,y=0).rename(drag_count=None) # Ignore the drag_count parameter
```

The way this could work would be to set the parameter precedences on the stream so they get ignored before passing the values to the callback. Using rename for this purpose overloads this method *slightly* but I think the semantics are reasonable and it makes more sense than introducing another method.

Note that in theory this could be used to remove ``PointerX`` and ``PointerY`` (and just have ``PointerXY``) but I think having those is still a nice convenience.

**Comment by jlstevens** [comment]
This should be easy to implement. The only thing is setting to ``None`` should set the precedence to something negative, say ``-1`` but restoring the parameter (e.g renaming again with a string) should restore the precedence. Any original precedence value would be lost so I guess it would just restore to param's default precedence.

**Comment by jbednar** [comment]
You could do `-abs(precedence)`, or `-precedence-1`, I guess, since that would be invertible...

**Comment by jlstevens** [comment]
Good idea!

**Comment by philippjfr** [comment]
Has this been documented? If so I'll close this.

**Comment by jlstevens** [comment]
I can put a stub in one of the user guides but it isn't documented currently anywhere else.

**Comment by jlstevens** [comment]
I've added a paragraph about this feature to the correspond user guide in #1537. Closing.
