### ISSUE TITLE
Cannot export plots

### ISSUE THREAD

**Issue by marianotepper** [ioam/holoviews#1441]
I am trying to understand how the exporting system works. I run the following cell in the Jupyter notebook:
```
import holoviews as hv
import numpy as np

hv.notebook_extension()
hv.archive.auto()

hv_im = hv.Image(np.random.randn(100, 100))
hv_im
```
I see a nice random image and the message:

> Automatic capture is now enabled. [2017-05-15 17:07:55]

I then run

```
hv.archive.contents()
hv.archive.export()
hv.archive.last_export_status()
```

and nothing happens. I just get the message
> Image.svg : image/svg+xml
> Image.hvz : application/zip
> Export name: '{notebook}'
> Directory    '/Users/mtepper/'
> 
> If no output appears, please check holoviews.archive.last_export_status()

No directory nor files are created.

Sorry for the very basic question!

**Comment by jlstevens** [comment]
Thanks for reporting this!

What you stated should work so I'll have to test. What version of notebook are you using?

**Comment by marianotepper** [comment]
I'm running 4.3.0 (everything installed via anaconda on a macbook pro).

**Comment by jlstevens** [comment]
I'm assigning this to 1.7.1 to make sure I have a look at this soon. I'll reassign if it turns out to be a lot of work (e.g latest jupyter notebook has broken the javascript).

**Comment by fvivian** [comment]
Something related to this issue led me here. But regarding this particular issue: For me it seems to work (notebook 4.4.1 and holoviews 1.7). I get a folder containing Image.hvz, Image.svg, index.html and index.ipynb.

My actual problem is somewhat different, though... I couldn't find any related topic anywhere, so I just ask here if you don't mind. I create a DynamicMap (for an RGB image) with two variables and accordingly two sliders. I.e. the variables change the RGB values of every pixel. Once the I chose the value of the variables via the sliders, I would like to use/be able to store the RGB values for further analysis. Is there any possiblity? If so, I would be happy to post my code so somebody could look at it.

**Comment by jlstevens** [comment]
@fvivian 

> For me it seems to work (notebook 4.4.1 and holoviews 1.7). I get a folder containing Image.hvz, Image.svg, index.html and index.ipynb.

That is useful to know, thanks!

As for your issue, I recommend you chat with us on our [gitter channel](https://gitter.im/ioam/holoviews) so you can tell us more about your problem. Then we can help you out straight away or file a new issue if there is a bug we need to fix.

**Comment by xysmas** [comment]
I'm having the exact same problem:

```
import holoviews as hv
import numpy as np
hv.__version__
1.7.0


hv.notebook_extension()
hv.archive.auto()

hv_im = hv.Image(np.random.randn(100, 100))
hv_im

hv.archive.contents()
hv.archive.export()
hv.archive.last_export_status()


Image.svg : image/svg+xml
Image.hvz : application/zip
Export name: 'Untitled1'
Directory    '/Users/agonzales/Dropbox/random_notebooks/aclum_mapping'

If no output appears, please check holoviews.archive.last_export_status()
Status of the last call to holoviews.archive.export is unknown.
(Re-execute this method once kernel status is idle.)
```

```
Server Information:

You are using Jupyter notebook.

The version of the notebook server is 5.0.0 and is running on:
Python 3.5.3 | packaged by conda-forge | (default, May 12 2017, 15:35:12) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]

Current Kernel Information:

DEPRECATED: IPython.core.usage.default_gui_banner is deprecated and will be removed
Python 3.5.3 | packaged by conda-forge | (default, May 12 2017, 15:35:12) 
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
```

**Comment by jlstevens** [comment]
@marianotepper 

Using Python 2.7 and notebook 4.3.1 seems to work for me:

![image](https://cloud.githubusercontent.com/assets/890576/26286847/6608dee8-3e66-11e7-9a41-06cd66a4f3a2.png)

I got the same results after downgrading to 4.3.0. From this line:

> Export name: '{notebook}'

It seems that the JavaScript failed to get the notebook name on your system. What browser are you using? I'll now test with Python 3.6 and then I'll try with the configuration described by @xysmas.

**Comment by jlstevens** [comment]
It turned out to be a Python 3 specific issue. The fix will make its way onto master as soon as the PR referenced above (#1471) is merged.

**Comment by jlstevens** [comment]
The PR mentioned above has been merged. @marianotepper @xysmas if either of you encounter this issue on current master, please tell me so I can reopen the issue.

**Comment by marianotepper** [comment]
Will let you know if I encounter any problems. Thanks!

**Comment by xysmas** [comment]
Thank you!  I will test it out when I get a chance and report back if there are any issues.
