### ISSUE TITLE
Bokeh Holoviews: cannot control tools per glyph

### ISSUE THREAD

**Issue by thoth291** [ioam/holoviews#1449]
Here is the code:
```python
from bokeh.models import HoverTool
hover = HoverTool(
        tooltips=[
            ("index", "$index"),
            ("(x,y)", "(x=$x{0[.]00000}, y=$y{0[.]00000})"),
        ]
    )
%%output backend='bokeh'
%%opts Curve [height=300 width=600] Points (size=10 alpha=0.3)
dpicks=hv.DynamicMap(callback=find_methods2_rel_peaks,
                     kdims=[hv.Dimension('order',values=range(3,100)),
                            hv.Dimension('method',values=methods2),
                            hv.Dimension('box',values=range(3,100)),
                            hv.Dimension('k',values=[1,3,5]),
                            hv.Dimension('rank',values=np.linspace(len(xs),20*len(xs),20))
                           ]
                    )
dpicks({'Curve':dict(plot={'tools':[hover]})})
```
Here is what I get when my mouse is over the Curve:
![over_the_curve](https://cloud.githubusercontent.com/assets/2971670/26119249/3f559f80-3a32-11e7-8957-9a932fc09349.PNG)
And when I'm over the point:
![over_the_point](https://cloud.githubusercontent.com/assets/2971670/26119269/4cd7165c-3a32-11e7-986f-fc372996f9c5.PNG)
So I actually would like to disable Hover for the Points - as I don't need them at all.
The field of interest is index on the Curve.

**Could you please help me to figure out how to enable/disable tools per Element?**

P.S. Here is how I do the plotting:
```python
def find_methods2_rel_peaks(order=3,method=methods[0],box=3,k=1,rank=100):
    #.... Some other code: implementation details...
    curve=hv.Curve({'data':ldata,'x':lxs},kdims=['x'],vdims=['data'],extents=extents)
    peaks=hv.Overlay([hv.Points((lxs[peak], ldata[peak])) for peak in peakind[good]])
    return curve*peaks
```
Thanks in Advance!

**Comment by philippjfr** [comment]
The plotting code should be attaching the appropriate renderer to the tool so this appears to be a bug.

**Comment by philippjfr** [comment]
This should now be fixed, please reopen if you encounter any further issues.
