### ISSUE TITLE
Rasters should not flip because they are in an Overlay

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#147]
The raster here...

```python
data = np.flipud(np.load('mandelbrot.npy'))
hv.Raster(data)
```

Is flipped about the horizontal relative to this overlay:

```python
data = np.flipud(np.load('mandelbrot.npy'))
hv.Raster(data) * hv.HLine(y=200)
```

The labelling seems right so the result is not *wrong* just a bit unexpected...

**Comment by philippjfr** [comment]
Clearly didn't quite think this through. RasterPlot inverts Rasters by automatically enabling ``invert_yaxis``, when in an Overlay the OverlayPlot handles the axes settings, so it just gets ignored. Should be a straightforward fix.

**Comment by philippjfr** [comment]
This was a terrible nightmare last night mainly because I was tired and kept missing failing notebook tests but axis inversions finally seem to be working correctly. I'll close the issue now.
