### ISSUE TITLE
adjoined VLine doesn't rotate

### ISSUE THREAD

**Issue by majidaldo** [ioam/holoviews#1475]
```
import holoviews as hv
import  numpy as np

curve= hv.Curve(np.random.normal(size=100))
hist=curve.hist().right
hist_vline = hist* hv.VLine(x=1) # want to rotate this
#hist_vline = hist* hv.HLine(y=1)

curve << hist_vline # vline doesn't rotate
# but commented out line  gives the desired result
```
![image](https://cloud.githubusercontent.com/assets/3588248/26322372/ce5821b0-3ef8-11e7-864a-6a4f0ffeb648.png)

**Comment by jlstevens** [comment]
Thanks for reporting this!

@philippjfr Ideally *everything* would just rotate when adjoined like this. I guess it isn't that easy to implement?

**Comment by philippjfr** [comment]
>@philippjfr Ideally everything would just rotate when adjoined like this. I guess it isn't that easy to implement?

No I think this is just a bug, ``invert_axes`` either not being passed through from the OverlayPlot correctly or being ignored.

**Comment by philippjfr** [comment]
Now fixed, closing.

**Comment by majidaldo** [comment]
still plot options like width/height and  xaxis/yaxis are not swapped.

**Comment by philippjfr** [comment]
>still plot options like width/height and xaxis/yaxis are not swapped.

They aren't expected to be.
