### ISSUE TITLE
top adjoint doesn't work in bokeh

### ISSUE THREAD

**Issue by majidaldo** [ioam/holoviews#1478]
```
import holoviews as hv
hv.notebook_extension('bokeh')
hv.AdjointLayout([hv.Curve([0,1,1,2,3]), hv.Empty() ,hv.Curve([0,1,1,0,1])])
```
flawed with mpl backend but with bokeh it's not even trying.

![image](https://cloud.githubusercontent.com/assets/3588248/26335764/1f1e11fc-3f3c-11e7-8c1a-ada4f947000c.png)

**Comment by philippjfr** [comment]
We never tested AdjointLayouts with empty plots, this could be a HoloViews issue but it might very well be the bokeh layout solver getting into a weird state. Will have to investigate.

**Comment by philippjfr** [comment]
This has been fixed by the PR referenced above. Please reopen if you encounter any other issues.
