### ISSUE TITLE
Add bokeh server tests

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#1488]
We should some tests for bokeh server, a server can easily be started programmatically and using a client we can perform various tests to ensure it is working correctly.

**Comment by philippjfr** [comment]
These are getting more and more crucial as there have been some high-profile regressions. The main things to test are:

- [ ] Stream callbacks are processed correctly
- [ ] Bokeh models are updated appropriately
- [ ] Ranges are processed correctly

**Comment by jlstevens** [comment]
I agree this is very important but we should get regular notebook tests running on the improved testing infrastructure before we tackle this. We don't want to tackle too much testing infrastructure at once as it is a right pain to set up.

Ideally we would also have a way of testing linked streams in live notebooks independent of bokeh server...

**Comment by philippjfr** [comment]
>Ideally we would also have a way of testing linked streams in live notebooks independent of bokeh server...

Notebook based callbacks do not use the same codepaths as server based ones, so those are independent problems.

**Comment by jlstevens** [comment]
Right, I am just mentioning another type of test I would *also* like...

**Comment by philippjfr** [comment]
We now have a number of bokeh server tests.

**Comment by jlstevens** [comment]
Happy to see this closed but maybe a new issue should be opened suggested tests for linked streams in notebooks?
