### ISSUE TITLE
Give plot instances rich display in the display hooks

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#1490]
I believe you can now do something like:

```python
plot = BokehRenderer.get_plot(obj)
```

To get a plot instance - note, I would like this renamed to something like ``plotobj`` instead of ``get_plot`` before 1.8!

If ``plot`` were registered with the display hooks, you could just view it as normal in the notebook:

```python
plot = BokehRenderer.get_plot(obj)
plot
```

The advantage of this is that with a handle on the plotting object you can use the ``Plot`` API, e.g to call ``.refresh()``. This would be useful for advanced use-cases where you might want to control plotting updates directly.

**Comment by philippjfr** [comment]
Just tested it and this works:

```python
from holoviews.plotting import Plot
def plot_display(plot):
    return plot.renderer.html(plot)

html_formatter.for_type(Plot, plot_display)
```

**Comment by jlstevens** [comment]
@philippjfr Want me to just add this to the display hooks so I can close this issue?
