### ISSUE TITLE
Matplotlib output broken with OSX backend

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#1496]
Using the OSX backend the fix for adjusting aspects in a LayoutPlot seems to break with this error:

![image](https://cloud.githubusercontent.com/assets/1550771/26562244/909de872-44bc-11e7-94d9-1a5e9c453ac6.png)

**Comment by philippjfr** [comment]
Don't think I'll get to look into this for this release, so I'll assign to 1.9.

**Comment by jlstevens** [comment]
I thought switching backends to agg stopped this warning from appearing?

**Comment by philippjfr** [comment]
Sure but that's a workaround not a fix. No reason why the matplotlib OSX backend shouldn't be supported.
