### ISSUE TITLE
confuse on aspect, how to make it right ?

### ISSUE THREAD

**Issue by dindom999** [ioam/holoviews#1498]
as follow, Out:141 is right , out:140  is not what I want, what did I miss?

![_004](https://cloud.githubusercontent.com/assets/5274818/26619310/768fba00-4610-11e7-8143-46fa49772b3e.png)

**Comment by philippjfr** [comment]
@dindom999 Which version of holoviews are you on? It should be giving you the expected behavior since 1.7.0.

**Comment by dindom999** [comment]
hi, @philippjfr ! sorry, it's my mistake, I am running v1.6 on an old anaconda pkg. It works after I upgrade to v1.7
Thinks!!!
