### ISSUE TITLE
BoundingBox's `script_repr` has old signature 

### ISSUE THREAD

**Issue by ceball** [ioam/holoviews#15]
For something with a ``script_repr`` attribute, param's ``script_repr`` expects to be able to call ``something.script_repr()`` with certain kw args: 

```python
elif hasattr(val,'script_repr'):
    rep=val.script_repr(imports=imports, prefix=prefix+" ",qualify=True, unknown_value=unknown_value)
```

BoundingBox doesn't support all of those kw args:

https://github.com/ioam/holoviews/blob/master/holoviews/core/boundingregion.py#L106
```python
def script_repr(self, imports=[], prefix="    "):
```

```python
topo_t000000.00_c1>>> from param.parameterized import script_repr
topo_t000000.00_c2>>> from holoviews.core.boundingregion import BoundingBox
topo_t000000.00_c3>>> script_repr(BoundingBox(),[])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/home/ceball/code/ioam/topographica/topographica in <module>()
----> 1 script_repr(BoundingBox(),[])

/home/ceball/code/ioam/topographica/external/param/param/parameterized.pyc in script_repr(val, imports, prefix, settings, unknown_value, qualify)
    817 
    818         rep=val.script_repr(imports=imports, prefix=prefix+"    ",
--> 819                             qualify=True, unknown_value=unknown_value)
    820 
    821     else:

TypeError: script_repr() got an unexpected keyword argument 'qualify'
```

Unfortunately I didn't at least say in the param release notes that anything with a ``script_repr`` method would need some changes, because I didn't actually notice the interface had changed (although now I look at the PR's diff it is very obvious). (I suppose we could modify param's ``script_repr`` to support the old signature of script_repr methods too, but it doesn't seem worth it.)

P. S. While debugging, I was so happy to find that boundingregion and sheetcoords are in holoviews rather than topographica - and hence no longer my problem, so I can throw away my piece of paper with 100 to-do items about Slice on it - that I almost wanted to commit the changes myself ;)

**Comment by jbednar** [comment]
I think we should make script_repr have a compatible signature if we still call it script_repr, and change to pprint for anything incompatible.

**Comment by ceball** [comment]
Yes, that seems very obvious now you've said it. I'll do that.

**Comment by ceball** [comment]
This won't be a problem with param 1.3.1 (see https://github.com/ioam/param/commit/42718e8f77d71d54fd867c7fb635b5d5c496df0b), but at some point we'll remove the old script_repr interface.

```python
topo_t000000.00_c1>>> from param.parameterized import script_repr
topo_t000000.00_c2>>> from holoviews.core.boundingregion import BoundingBox
topo_t000000.00_c3>>> script_repr(BoundingBox(),[],'',[])
               Out[4]:'BoundingBox(radius=0.5)'
```

**Comment by jlstevens** [comment]
Our first issue!

Did anything change in HoloViews for this or does anything need to change? If not, I'll close this issue.

**Comment by jbednar** [comment]
I think it's fine now that param 1.3.1 is out.
