### ISSUE TITLE
histogram of an empty array

### ISSUE THREAD

**Issue by ea42gh** [ioam/holoviews#1506]
```
%%opts Points [color_index=2 size_index=2 scaling_factor=10]
np.random.seed(10)
data = np.random.normal(size=(200,4))

points = hv.Points(data, vdims=['z'])(plot=dict(color_index=3,size_index=2))
points.hist() + points[0.:0.1, 0.:0.1].hist()
```
ValueError: zero-size array to reduction operation fmin which has no identity

**Comment by jbednar** [comment]
What to do in such a situation is not obvious, but I'd vote for this producing a plot with all bars zero, over some nominal range, just because it may not be practical to ensure that it's never called with an empty array.

**Comment by jlstevens** [comment]
Probably just a flat histogram (all bars at zero) with nbins with a 0-1 range would do it.

**Comment by jlstevens** [comment]
Tentatively assigning to 1.8.1. Can be bumped back to 1.9 if it can't be fixed quickly.

**Comment by ea42gh** [comment]
More generally, I think all elements with empty data should return an empty plot that can be composed with other plots. Nominal plot ranges would need to be discounted for shared_axes

**Comment by jlstevens** [comment]
@ea42gh Empty data tends to need special handling (which is sometimes missing) but our intention is for all elements to work the way you suggest.

**Comment by ea42gh** [comment]
One failure mode is documented in issue #1800
