### ISSUE TITLE
Selecting of a Path doesn't work in an Overlay with a HoloMap

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#151]
Correct:
```python
%%opts Path {+axiswise} Path.Barrier (color='k') [aspect='square']
hv.Path((x, V_x), group='Barrier').select(x=(-98, 97), y=(0, 1))
```

![screen shot 2015-06-14 at 13 48 09](https://cloud.githubusercontent.com/assets/6897215/8148398/4fcb8678-129c-11e5-8077-dfbcee11a880.png)

Incorrect:
```python
%%opts Path {+axiswise} Path.Barrier (color='k') [aspect='square']
hv.HoloMap(ani_psix, kdims=['t']) * hv.Path((x, V_x), group='Barrier').select(x=(-98, 97), y=(0, 1))
```
![screen shot 2015-06-14 at 13 49 09](https://cloud.githubusercontent.com/assets/6897215/8148399/5455dc0c-129c-11e5-837a-dfc44b150123.png)

**Comment by philippjfr** [comment]
Works fine for me, think you meant:

```python
(hv.HoloMap(ani_psix, kdims=['t']) * hv.Path((x, V_x), group='Barrier')).select(x=(-98, 97), y=(0, 1))
```

In your "broken" example (note the extra parentheses). Will close the issue, please reopen if you can still replicate the bug and please provide a self contained example.
