### ISSUE TITLE
Not possible to pass options to Datashader 'shade' function

### ISSUE THREAD

**Issue by bjfar** [ioam/holoviews#1510]
I am trying to write a simple custom version of the `holoviews.operation.datashader.datashade` class, to handle my custom coloring and aggregation preferences. I managed to insert the colormap and aggregation method that I want, like this:

```
import param
import holoviews as hv
from holoviews.operation.datashader import datashade

class my_datashade(datashade):
    """Custom datashade class to do my projection and colormap"""
    aggregator = param.ClassSelector(class_=ds.reductions.Reduction,
                                     default=ds.min('z'))
    cmap = my_cmap

my_data = hv.Points(df[['x', 'y', 'z']]) #point data from a Pandas dataframe
my_datashade(my_data)
```
 but I cannot find a way to set the absolute normalisation of the colormap. Usually I would pass a 'span' parameter to `datashader.transfer_functions.shade`, but I cannot find a good way to do this without reimplementing the entire `_process` function in the `holoviews.operation.datashader.shade` class, because there seems to be no way to feed information into `shade_opts`, defined on line 391 in datashader.py (https://github.com/ioam/holoviews/blob/master/holoviews/operation/datashader.py)

Perhaps a good solution would be to add a member variable `shade_opts` to the shade class, from which options were grabbed and which could be overridden in the derived `my_datashader` class as I do for `aggregator` and `cmap`.

**Comment by jlstevens** [comment]
Good timing! 

This PR should be merged very soon #1508 allowing you to pass ``span``.

**Comment by bjfar** [comment]
Ahh, cool, that's very nice. Just in case anyone else reads this, I also was fretting that I need to pass the 'how' parameter to the datashader 'shade' function, but it seems you call this 'normalization' in holoviews. So to produce what I want I now do this:

```
class chi2_datashade(hvds.datashade):
    """Custom datashade class to do our projection and colormap"""
    aggregator = param.ClassSelector(class_=ds.reductions.Reduction,
                                     default=ds.min('dchi2'))
    cmap = chi2cmap
    normalization = 'linear'
    span = [mn,mx] # this requires https://github.com/ioam/holoviews/pull/1508 to work, which I just hacked in to holoviews for now
```

**Comment by philippjfr** [comment]
You can now pass in ``clims`` to specify the color range, the offset bug should be fixed in datashader. Secondly instead of subclassing the operation the way you did just use:

```python
custom_datashade = datashade.instance(aggregator=ds.min('dchi2'), cmap=chi2cmap, normalization='linear', clims=(mnx, x))
```

This will create custom instance of the datashade function that you can use.
