### ISSUE TITLE
GeoViews maps: dimensions.range() not respected

### ISSUE THREAD

**Issue by ea42gh** [ioam/holoviews#1527]
```
%%opts WMTS [height=250 width=300 xaxis=None yaxis=None show_grid=True]
e2 = (-10883929.253839944, 3529155.1707309242,
         -10875802.931012034, 3542170.6276430194)
#e2=lonlat_corners_to_extents([-97.772,30.199],[-97.699,30.300], to=ccrs.GOOGLE_MERCATOR)
h=gv.WMTS( CARTODBPOSITRON, extents=e2, crs=ccrs.GOOGLE_MERCATOR)
h+h.redim.range(x=(-10903929.253839944, -10875802.931012034))
```
Redim affect the map to the left rather than the map to the right.
Rerunning this code shows bizarre cycling behaviour:
run once, empty map on the left, run twice two maps, run 3 times, empty map on the left

Modifying the values in the range triggers a bokeh zoom level bug and my yield different behaviour

**Comment by philippjfr** [comment]
This should be addressed once https://github.com/bokeh/bokeh/pull/7294 is merged.

**Comment by jlstevens** [comment]
Should this issue be closed here and a corresponding one opened for the geoviews repo?

Alternatively, if there is an underlying holoviews issue, the title and issue should be updated to reflect the real problem here.

**Comment by philippjfr** [comment]
I've fixed the underlying issue in bokeh, so this can now be closed. We'll see the benefit in bokeh 0.12.14.
