### ISSUE TITLE
Plotting very small numbers doesn't work well.

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#153]
Both the numbers overlap and the ``sample`` method doesn't work correctly.

```python
((im1.Image * im1.Scatter * hv.VLine(B_min)).hist(0) + im1.Image.I.sample(B=B_min)
+(im1.Image * im1.Scatter * hv.HLine(k_min)).hist(0) + im1.Image.I.sample(Momentum=k_min)).cols(2)
```

![download 3](https://cloud.githubusercontent.com/assets/6897215/8180844/57d1def4-1421-11e5-9681-b6bba65c8481.png)

**Comment by jlstevens** [comment]
I would suggest trying a dimension formatter that presents the small numbers to a small number of significant figures. The sampling issue is something that needs looking into though...

**Comment by philippjfr** [comment]
Yes, specifying a ``dimension_formatter`` on the ``Dimension`` is the correct solution here, there is no sensible I can think of that will let us deal with this ourselves. Will close this issue.
