### ISSUE TITLE
Bokeh reset button does not trigger recalculation of datashaded plot

### ISSUE THREAD

**Issue by mrksr** [ioam/holoviews#1530]
When rendering a plot using Bokeh and the data shader, Pressing the reset-button (in the Bokeh interface) does not trigger a recalculation of the plot boundaries. Basically any operation like zooming or panning wil fix the issue. A simple plot to test things with:
```python
import numpy as np
import holoviews as hv
from holoviews.operation.datashader import datashade

hv.notebook_extension('bokeh')
points = hv.Points(np.random.multivariate_normal((0,0), [[0.1, 0.1], [0.1, 1.0]], (1000000,)), label="Points")
datashade(points)
```

Here is a screenshot taken just after pressing the reset button after zooming in on the still-visible rectangle:
![reset_bokeh](https://user-images.githubusercontent.com/5184063/27039156-6a8d1870-4f8d-11e7-9d6f-7c50db005f31.png)

The issue exists using the current master (5aa7aebc43af439456d325a2551b47a17c835f0d) and using bokeh version 0.12.4.

**Comment by philippjfr** [comment]
I would suggest updating to bokeh 0.12.5 or even 0.12.6 which is going to be released tomorrow. I filed the bug report and made sure this was fixed in 0.12.5.
