### ISSUE TITLE
datashader on bokeh server

### ISSUE THREAD

**Issue by stevievb** [ioam/holoviews#1536]
I'm trying to using holoviews, bokeh server, and datashader based somewhat on the example in issue #959. I'm getting the following error and I'm not sure how to debug it:

ERROR:bokeh.server.protocol.server_handler:error handling message Message 'PATCH-DOC' (revision 1): AttributeError("'NoneType' object has no attribute '_session_callbacks'",)

The plot shows up and looks correct but the datashading aspect on zoom does not seem to be working and throws that error.

My bokeh application code is ---
```
import numpy as np
import holoviews as hv
from holoviews.operation.datashader import datashade
import holoviews.plotting.bokeh # noqa (Activate backend)
from bokeh.layouts import row
from bokeh.plotting import curdoc

doc = curdoc()

renderer = hv.Store.renderers['bokeh'].instance(mode='server', holomap='server')
options = hv.Store.options(backend='bokeh')

y = np.random.standard_normal(size = 2000000)
x = np.arange(len(y)) / 200000.0

curve = hv.Curve((x, y))
datashaded = datashade(curve, cmap=["blue"])

plot = renderer.get_plot(datashaded)

layout = row(plot.state)

doc.add_root(layout)
```

conda env ---
```
dependencies:
- !!python/unicode
  'colorcet=0.9.1=py35_0'
- !!python/unicode
  'datashader=0.5.0=py35_0'
- !!python/unicode
  'bleach=1.5.0=py35_0'
- !!python/unicode
  'bokeh=0.12.5=py35_1'
- !!python/unicode
  'bzip2=1.0.6=vc14_3'
- !!python/unicode
  'cloudpickle=0.2.2=py35_0'
- !!python/unicode
  'colorama=0.3.9=py35_0'
- !!python/unicode
  'cycler=0.10.0=py35_0'
- !!python/unicode
  'dask=0.14.3=py35_1'
- !!python/unicode
  'datashape=0.5.4=py35_0'
- !!python/unicode
  'decorator=4.0.11=py35_0'
- !!python/unicode
  'entrypoints=0.2.2=py35_1'
- !!python/unicode
  'freetype=2.5.5=vc14_2'
- !!python/unicode
  'h5py=2.6.0=np111py35_2'
- !!python/unicode
  'hdf5=1.8.15.1=vc14_4'
- !!python/unicode
  'holoviews=1.7.0=py35_0'
- !!python/unicode
  'html5lib=0.999=py35_0'
- !!python/unicode
  'icu=57.1=vc14_0'
- !!python/unicode
  'ipykernel=4.6.1=py35_0'
- !!python/unicode
  'ipython=6.1.0=py35_0'
- !!python/unicode
  'ipython_genutils=0.2.0=py35_0'
- !!python/unicode
  'ipywidgets=6.0.0=py35_0'
- !!python/unicode
  'jedi=0.10.2=py35_2'
- !!python/unicode
  'jinja2=2.9.4=py35_0'
- !!python/unicode
  'jpeg=9b=vc14_0'
- !!python/unicode
  'jsonschema=2.6.0=py35_0'
- !!python/unicode
  'jupyter=1.0.0=py35_3'
- !!python/unicode
  'jupyter_client=5.0.1=py35_0'
- !!python/unicode
  'jupyter_console=5.1.0=py35_0'
- !!python/unicode
  'jupyter_core=4.3.0=py35_0'
- !!python/unicode
  'libpng=1.6.27=vc14_0'
- !!python/unicode
  'libtiff=4.0.6=vc14_3'
- !!python/unicode
  'llvmlite=0.18.0=py35_0'
- !!python/unicode
  'locket=0.2.0=py35_1'
- !!python/unicode
  'markupsafe=0.23=py35_2'
- !!python/unicode
  'matplotlib=2.0.2=np111py35_0'
- !!python/unicode
  'mistune=0.7.4=py35_0'
- !!python/unicode
  'mkl=11.3.3=1'
- !!python/unicode
  'multipledispatch=0.4.9=py35_0'
- !!python/unicode
  'nbconvert=5.2.1=py35_0'
- !!python/unicode
  'nbformat=4.3.0=py35_0'
- !!python/unicode
  'networkx=1.11=py35_0'
- !!python/unicode
  'notebook=5.0.0=py35_0'
- !!python/unicode
  'numba=0.33.0=np111py35_0'
- !!python/unicode
  'numpy=1.11.2=py35_0'
- !!python/unicode
  'odo=0.5.0=py35_1'
- !!python/unicode
  'olefile=0.44=py35_0'
- !!python/unicode
  'openssl=1.0.2l=vc14_0'
- !!python/unicode
  'pandas=0.20.1=np111py35_0'
- !!python/unicode
  'pandocfilters=1.4.1=py35_0'
- !!python/unicode
  'partd=0.3.8=py35_0'
- !!python/unicode
  'path.py=10.3.1=py35_0'
- !!python/unicode
  'pickleshare=0.7.4=py35_0'
- !!python/unicode
  'pillow=4.1.1=py35_0'
- !!python/unicode
  'pip=9.0.1=py35_1'
- !!python/unicode
  'prompt_toolkit=1.0.14=py35_0'
- !!python/unicode
  'pygments=2.2.0=py35_0'
- !!python/unicode
  'pyparsing=2.1.4=py35_0'
- !!python/unicode
  'pyqt=5.6.0=py35_2'
- !!python/unicode
  'python=3.5.2=0'
- !!python/unicode
  'python-dateutil=2.6.0=py35_0'
- !!python/unicode
  'pytz=2017.2=py35_0'
- !!python/unicode
  'pyyaml=3.12=py35_0'
- !!python/unicode
  'pyzmq=16.0.2=py35_0'
- !!python/unicode
  'qt=5.6.2=vc14_4'
- !!python/unicode
  'qtconsole=4.3.0=py35_0'
- !!python/unicode
  'requests=2.12.4=py35_0'
- !!python/unicode
  'scipy=0.18.1=np111py35_0'
- !!python/unicode
  'setuptools=27.2.0=py35_1'
- !!python/unicode
  'simplegeneric=0.8.1=py35_1'
- !!python/unicode
  'sip=4.18=py35_0'
- !!python/unicode
  'six=1.10.0=py35_0'
- !!python/unicode
  'sqlalchemy=1.1.6=py35_0'
- !!python/unicode
  'testpath=0.3.1=py35_0'
- !!python/unicode
  'tk=8.5.18=vc14_0'
- !!python/unicode
  'toolz=0.8.2=py35_0'
- !!python/unicode
  'tornado=4.4.2=py35_0'
- !!python/unicode
  'traitlets=4.3.2=py35_0'
- !!python/unicode
  'vs2015_runtime=14.0.25123=0'
- !!python/unicode
  'wcwidth=0.1.7=py35_0'
- !!python/unicode
  'wheel=0.29.0=py35_0'
- !!python/unicode
  'widgetsnbextension=2.0.0=py35_0'
- !!python/unicode
  'win_unicode_console=0.5=py35_0'
- !!python/unicode
  'xarray=0.9.6=py35_0'
- !!python/unicode
  'zlib=1.2.8=vc14_3'
- !!python/unicode
  'param=1.5.1=py35_0'
- pip:
  - aiofiles==0.3.0
  - aiohttp==1.2.0
  - aiohttp-cors==0.5.0
  - aiohttp-jinja2==0.13.0
  - aiopg==0.13.0
  - alembic==0.9.0
  - async-timeout==1.1.0
  - asyncpg==0.9.0
  - asyncpgsa==0.8.2
  - bkcharts==0.1
  - certifi==2017.4.17
  - chardet==3.0.3
  - freezegun==0.3.8
  - idna==2.5
  - ipython-genutils==0.2.0
  - jupyter-client==5.0.1
  - jupyter-console==5.1.0
  - jupyter-core==4.3.0
  - mako==1.0.6
  - multidict==2.1.4
  - prompt-toolkit==1.0.14
  - psycopg2==2.6.2
  - py==1.4.32
  - pyserial==3.2.1
  - pyserial-asyncio==0.3
  - pytest==3.0.6
  - pytest-aiohttp==0.1.3
  - python-editor==1.0.3
  - rx==1.5.8
  - urllib3==1.21.1
  - win-unicode-console==0.5
  - yarl==0.8.1
```

**Comment by jlstevens** [comment]
Thanks for filing this issue!

My first suggestion is you update to Bokeh 0.12.6 which just released [a few hours ago](https://bokeh.github.io/blog/2017/6/13/release-0-12-6/) to see if the problem persists.

I think you might also want to try the holoviews dev version that you can get with:

```
conda install -c ioam/label/dev holoviews
```

**Comment by stevievb** [comment]
Upgrading both of those packages as you instructed did not seem to help.

**Comment by philippjfr** [comment]
@stevievb Very simple fix, I'll have a user guide up to explain this stuff soon, simply change this line by passing the doc in:

```
plot = renderer.get_plot(datashaded, doc=doc)
```

**Comment by philippjfr** [comment]
That said the simpler thing to do all around is this:

```python
import numpy as np
import holoviews as hv
from holoviews.operation.datashader import datashade
import holoviews.plotting.bokeh # noqa (Activate backend)

y = np.random.standard_normal(size = 2000000)
x = np.arange(len(y)) / 200000.0

curve = hv.Curve((x, y))
datashaded = datashade(curve, cmap=["blue"])

doc = hv.renderer('bokeh').server_doc(datashaded)
```

**Comment by stevievb** [comment]
Hey that all worked. Thanks for your help.

**Comment by jlstevens** [comment]
@philippjfr Think you'll be able to add something to the docs about this for 1.8?

**Comment by loc1978** [comment]
How are you running this along with Bokeh server? If the application is called app.py, are you using:

bokeh serve app.py

Is this correct?

**Comment by jlstevens** [comment]
@loc1978 That's right. You can try some of our examples [here](https://github.com/ioam/holoviews/tree/master/examples/apps/bokeh) though you'll probably need a dev version of holoviews to run them.

**Comment by loc1978** [comment]
Thanks for the quick reply. Unfortunately I'm having a lot of trouble getting a simple example to work. When I try to run this one:

https://github.com/ioam/holoviews/blob/master/examples/apps/bokeh/selection_stream.py

I get: AttributeError: module 'holoviews' has no attribute 'renderer'

I'm currently using the latest holoviews version 1.8.dev1 -- Is this the correct version?

**Comment by philippjfr** [comment]
>I'm currently using the latest holoviews version 1.8.dev1 -- Is this the correct version?

There is currently no release that includes ``hv.renderer`` function, we'll try to releasing a 1.8dev3 asap.

**Comment by loc1978** [comment]
Thanks. I'm very interested in the ability to do run this code (i.e. Plotting many points with the ability to sample/unsample while zooming):

https://github.com/ioam/holoviews/pull/959

Is there a an older version of holoviews that this code snippet will work? Also, what versions of bokeh and datashader are necessary?

**Comment by stevievb** [comment]
Somewhat related - Is it possible to pass plot or style options with this setup? 

For example, is something like this supported?:

curve = hv.Curve((x, y))(plot=dict(yaxis=None))
datashaded = datashade(curve, cmap=["blue"])

I see towards the bottom of this page (https://anaconda.org/jbednar/holoviews_datashader/notebook) an example of passing width and height parameters to the datashade function but in my testing it seems to have no effect. What is the correct way to set the width/height?

datashaded = datashade(curve, cmap=["blue"], width=800, height=800)

**Comment by jbednar** [comment]
The arguments to the `datashade()` operations determine the *initial* width and height of the rasterized array, which is important in that example because a static .HTML export uses only this initial value.  If not for that one detail, those values can safely be omitted in normal usage.

After the initial rendering, by default the value is set dynamically by the size of the bokeh plot in which the datashader plot is embedded.  In this case you can use the normal HoloViews mechanisms to set the Bokeh plot size.

**Comment by philippjfr** [comment]
Something like this should work:

```python
datashaded = datashade(curve, cmap=["blue"])
datashaded(plot={'RGB': dict(width=800, height=800)})
```

**Comment by stevievb** [comment]
@philippjfr I gave that a try but it didn't seem to have any effect.

**Comment by stevievb** [comment]
@philippjfr Thanks that seemed to work with a slight modification. 

```
datashaded = datashade(curve, cmap=["blue"])
datashaded = datashaded(plot={'RGB': dict(width=800, height=800)})
```

**Comment by philippjfr** [comment]
Ah sorry, what I did was for interactive notebook usage, in a script you definitely have to define the variable. I've also made another mistake, we recently introduced ``.opts`` which we recommend instead of the ``__call__`` version so that should be:

```
plot_opts = {'RGB': dict(width=800, height=800)}
datashaded = datashade(curve, cmap=["blue"]).opts(plot=plot_opts)

**Comment by loc1978** [comment]
Hello all again,

I'd like the user to be able to filter the data and most Bokeh examples use ```ColumnDataSource``` to achieve this task (ex. https://github.com/bokeh/bokeh/blob/master/examples/app/weather/main.py). Is there a way to use this function with holoviews/datashader/bokeh? Or is there another way to filter the data that will trigger a plot update?

Something like this?

```
import numpy as np
import holoviews as hv
import holoviews.plotting.bokeh
from holoviews.operation.datashader import datashade
from bokeh.models import ColumnDataSource

hv.Store.current_backend = 'bokeh'
renderer = hv.Store.renderers['bokeh'].instance(mode='server', holomap='server')
d = np.random.multivariate_normal((0,0), [[0.1, 0.1], [0.1, 1.0]], (1000000,))
source = ColumnDataSource(d)
points = hv.Points(source)
datashaded = datashade(points, x_sampling=0.01, y_sampling=0.01)
doc, _ = renderer(datashaded)

```

**Comment by jlstevens** [comment]
@philippjfr Should this issue be closed or bumped to the next milestone?

**Comment by philippjfr** [comment]
Closing this as it seems to have been addressed.
