### ISSUE TITLE
Improve error message for missing Callable keywords

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#1551]
The current error message is this:

>KeyError: 'Callable missing keywords to accept boundsx stream parameters'

which doesn't let the user make the association between the Callable (which is rather opaque) and the actual function they supplied to the DynamicMap.

**Comment by jlstevens** [comment]
Just to clarify, we want to show the function name which we have utilities to get.

**Comment by philippjfr** [comment]
Thanks somehow forgot to put that in there.

**Comment by jlstevens** [comment]
Addressed in the PR referenced above (#1577). Closing.
