### ISSUE TITLE
Improve contours, fix fill colors for contours

### ISSUE THREAD

**Issue by ea42gh** [ioam/holoviews#1558]
```
%%output backend='bokeh'
%%opts Polygons (cmap='hot')
from holoviews.operation import contours as hv_contours

x,y = np.meshgrid(np.linspace(-5,5,101), np.linspace(5,-5,101))
z=np.sin(x**2+y**2)*np.exp(-0.3*x)
hv.Image(z)+hv_contours(hv.Image(z), levels=[.2,.4,.6,.7,.85], filled=True, overlaid=False)
```
Suggestions:
- [x] make `overlaid=False` the default
- [x]  autocompute n levels with levels=n
- [x]  allow overlaid=True while setting an alpha level for the image
- [x]  fix the colors of the fill between levels
    (a simpler plot showing the issue uses `z = np.sin(x**2+y**2)`
- [x] ensure contour lines are not overlaid by the color fill

**Comment by ea42gh** [comment]
* colorbar does not display the full range of the contour levels, e.g.,
```
%%opts Polygons [colorbar=True colorbar_position='left' ] (alpha=0.5 cmap='viridis')
hv_contours(hv.Image( (x_vals,y_vals, radii ) ),levels=[radii.min(), 20., 50., 70., radii.max()],overlaid=False,filled=True )
```
shows a colorbar running from 0(?) to 70 rather than radii.max()?
* the radii.max() level must be included, since otherwise the corresponding Polygon will not be filled

**Comment by jlstevens** [comment]
> A uniform API for both holoviews and geoviews seems desirable

I agree. The contour operation needs some thought especially now the multi-interface PR is merged improving contour/path elements. I'm just not sure when we will get round to improving it...

**Comment by philippjfr** [comment]
Until we support ``holes`` in our polygons this will likely not be fixed. I do think we can support using the DictInterface eventually but it likely won't be in the next release.

**Comment by philippjfr** [comment]
As far as I can all the issues here have now been addressed by https://github.com/ioam/holoviews/pull/3092. Please reopen if you encounter issues.
