### ISSUE TITLE
backend='d3', KeyError 'd3'

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#156]
When I do:
```python 
%%output backend='d3'
```
I get a error ```KeyError 'd3'```. 

I suppose it's part of the refactoring, but opened it just to be sure.

**Comment by jlstevens** [comment]
Yes, this stuff will be broken until the current refactor is complete.

**Comment by philippjfr** [comment]
Should be working again now but you'll have to use this instead:

```python
%%output backend='matplotlib:d3'
```

Will close the issue.

**Comment by jlstevens** [comment]
I might automatically allow 'd3' and 'nbagg; to be support for backward compatibility. At least for a while..
