### ISSUE TITLE
Find better alternative for website search feature

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#1562]
Since switching to the new theme based on bokeh we are now relying on Google Custom Search Engine to search our website. This has benefits over the inbuilt Sphinx search, which ignores anything but the first keyword you give it, but it's also supported by ads which is kind of awful. If we can find a better alternative we should use it.

**Comment by jlstevens** [comment]
Low priority, tentatively assigning to 1.8.1.

**Comment by philippjfr** [comment]
Removing milestone, unlikely to happen anytime soon.

**Comment by philippjfr** [comment]
Closing, it works fine and I don't know of decent alternatives.
