### ISSUE TITLE
height/width style options for Table/ItemTable are broken

### ISSUE THREAD

**Issue by jordansamuels** [ioam/holoviews#1583]
The `hv.help(hv.Table)` shows
```
-------------
Style Options
-------------

	editable, fit_columns, height, row_headers, selectable, sortable, width
```

However, using `height` or `width` results in an error.  E.g.
```
hv.Table(pd.DataFrame({'hello': ['world']}))(style=dict(height=50))
```
or
```
hv.ItemTable([('hello','world')])(style=dict(height=50))
```

will result in `TypeError: MetaModel object got multiple values for keyword argument 'height'`.

Using e.g. `%%opts Table [height=50]` is insufficient for use cases where the user desires two tables of different height in the same cell.

**Comment by philippjfr** [comment]
Sorry I never got to this ``height`` and ``width`` are ``plot`` not ``style`` options. I'm not sure why they are even allowed as style options so I'll remove that now. The correct usage is this:

```
hv.Table(pd.DataFrame({'hello': ['world']})).opts(plot=dict(height=50))
```

**Comment by philippjfr** [comment]
Will close this now that the confusing style options have been removed.
