### ISSUE TITLE
Legend doesn't show

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#159]
With none of the options I tried it worked.

```python
%%opts OverlayPlot [show_legend=True] Contours [show_legend=True] NdOverlay [show_legend=True] Overlay [show_legend=True] 
x = np.linspace(0, 10)
hv.Contours((x, x**2), level=0, label="1") * hv.Contours((x, x**3), level=1, label="2")
```

![download 2](https://cloud.githubusercontent.com/assets/6897215/8204742/025d297c-14eb-11e5-99c9-5bc0c7812cab.png)

**Comment by philippjfr** [comment]
Paths and Polygons didn't actually ever set their label as part of the legend. I've fixed it in f21373c70cf3d56e204aa802d0b4b638b5607dac. Will close the issue.
