### ISSUE TITLE
Scrubber doesn't show after nbconvert

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#161]
@philippjfr yesterday you fixed the HoloMap widgets to work correctly with ``nbconvert``.

I didn't check the scrubber, which you fixed to work in the notebook  https://github.com/ioam/holoviews/issues/158

Unfortunately the scrubber widget still doesn't work with nbconvert.

**Comment by philippjfr** [comment]
Fixed in 193a54202da0dfc. Closing.
