### ISSUE TITLE
Interpolation of Image is suddenly activated

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#162]
Before:
![download-_9_](https://cloud.githubusercontent.com/assets/6897215/8230748/658fd070-15c3-11e5-9857-8243cd8073b8.png)

After:
![download 11](https://cloud.githubusercontent.com/assets/6897215/8230753/69c36210-15c3-11e5-9da9-1255a7e76d12.png)

Maybe it's not completely clear that this is unwanted here, but take a look at this guy that used to be beautiful:
![download 8](https://cloud.githubusercontent.com/assets/6897215/8230776/9e833750-15c3-11e5-9244-e790cba77fcf.png)

**Comment by basnijholt** [comment]
@jlstevens helped me on Gitter. It was because I used the rc file like in this example: https://github.com/ioam/holoviews/issues/92#issuecomment-104900298

**Comment by jlstevens** [comment]
I think this is due to changes in the options system and it all works if the new system is used (see #141).
