### ISSUE TITLE
Animated gif always shows frame zero

### ISSUE THREAD

**Issue by jordansamuels** [ioam/holoviews#1621]
The following code is a repro:
```
import holoviews as hv
import numpy as np
hv.extension('matplotlib')
%output holomap='gif' 
xs = np.linspace(0,1)
hv.HoloMap([(p, hv.Curve(zip(xs,(2 + np.sin(p)) * xs * (1-xs)))) for p in np.linspace(0,2*np.pi)])
```
![image](https://user-images.githubusercontent.com/610909/27600020-93f872b6-5b38-11e7-9626-f70f77f063e9.png)

**Comment by jordansamuels** [comment]
Also true with `Points` element, so I'm guessing it's not specific to `Curve`.

**Comment by jlstevens** [comment]
I suspect it is to do with how the plotting code handles initialization in general.

**Comment by jordansamuels** [comment]
As per discussion on https://gitter.im/ioam/holoviews, this also shows the issue (slightly simplified):

```
import holoviews as hv
import numpy as np
hv.extension('matplotlib')
```
and then
```
%%output holomap='gif' fps=2
from holoviews.operation import contours
x = np.arange(-3.0,3.0,0.1)
y = np.arange(-3.0,3.0,0.1)
X,Y = np.meshgrid(x, y) 
def g(x,y,c,d=2):
    return d*((x-y)**2/(x**2+y**2)) + np.exp(-(np.sqrt(x**2+y**2)-c)**2)
h = hv.HoloMap([(t, hv.Image(g(X,Y, 4 * np.sin(t))).opts(style=dict(cmap='fire'))) for t in np.linspace(0,2*np.pi,5)])
contours(h,levels=[.5]) 
```
This will result in this image at some point:
![image](https://user-images.githubusercontent.com/610909/27718649-55091922-5d1b-11e7-9cba-4b3f3a2e5ca7.png)

However, using `widgets` you can see that this never actually occurs.  E.g.
```
%%output holomap='widgets'
contours(h, levels=[.5])
```
