### ISSUE TITLE
Default color of hv.Bounds changed

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#163]
Probably other elements also changed color, but ``hv.Bounds`` went from ``c`` to ``b``.

EDIT: just checked, ``Path`` changed too.

**Comment by basnijholt** [comment]
This was fixed by the same fix as in #162 and #164 .

"@jlstevens helped me on Gitter. It was because I used the rc file like in this example: https://github.com/ioam/holoviews/issues/92#issuecomment-104900298"

**Comment by jlstevens** [comment]
Same issue as #162 and should now be resolved.
