### ISSUE TITLE
Histogram doesn't show borders around bars anymore

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#164]
See before after images in https://github.com/ioam/holoviews/issues/162

**Comment by basnijholt** [comment]
This was fixed by the same fix as in #162.

"@jlstevens helped me on Gitter. It was because I used the rc file like in this example: https://github.com/ioam/holoviews/issues/92#issuecomment-104900298"

**Comment by jlstevens** [comment]
Same as #162 and #163. Should be resolved now.
