### ISSUE TITLE
Figure out setup.py example packaging bug

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#1643]
When running setup.py since https://github.com/ioam/holoviews/pull/1368 we now pull all the examples into the holoviews module. This seems to raise a directory not found error that resolves itself when running setup.py twice. We should track this down at some point.

**Comment by jlstevens** [comment]
I agree with the label 'minor-bug' - if we can't fix this for 1.8.1, nevermind.

**Comment by philippjfr** [comment]
@jlstevens Was this fixed?

**Comment by jlstevens** [comment]
I had no problem running ``python setup.py sdist`` on the first go for the 1.8.4 release. I think this issue can now be closed.
