### ISSUE TITLE
holoviews --install-examples doesn't work with pip

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#1659]
The examples directory is in the archive directory uploaded to pypi but doesn't seem to install anywhere when pip installing.

**Comment by jlstevens** [comment]
This is a closely related issue to #1643.

**Comment by jlstevens** [comment]
Another pypi/pip issue: numpy and param aren't being fetched automatically for some reason...

**Comment by jlstevens** [comment]
At least not if you do ``pip install holoviews``. At least ``pip install holoviews[all]`` (the recommended thing) works correctly.

**Comment by ipfans** [comment]
v1.8.1 also not working with pip install:

```
$ pip install holoviews
Collecting holoviews
  Using cached holoviews-1.8.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/g9/m3cmg0m10cl80xt362wpsld00000gn/T/pip-build-7crrhg0l/holoviews/setup.py", line 131, in <module>
        package_assets(example_path)
      File "/private/var/folders/g9/m3cmg0m10cl80xt362wpsld00000gn/T/pip-build-7crrhg0l/holoviews/setup.py", line 117, in package_assets
        import holoviews
      File "/private/var/folders/g9/m3cmg0m10cl80xt362wpsld00000gn/T/pip-build-7crrhg0l/holoviews/holoviews/__init__.py", line 10, in <module>
        import param
    ModuleNotFoundError: No module named 'param
```

I think ```pip install holoviews[all]``` should be clarify in the docs.

**Comment by jlstevens** [comment]
Right now``holoviews[all]`` or ``holoviews[recommended]`` is the best thing for pip installs and it is mentioned in the docs [here](http://holoviews.org/user_guide/Installing_and_Configuring.html). 

The pip installer will correctly pull in param and numpy in 1.8.2 so you won't see the stated error anymore though ``pip install holoviews`` still won't be pulling in bokeh/matplotlib.

**Comment by ipfans** [comment]
sorry，I missed that informatiin. Thx for your reply.

**Comment by tdsmith** [comment]
Adding extras like `[all]` should not actually help; if it appeared to help, it may have been because you had successfully installed holoview using pip in the past, and pip had cached the built holoview wheel. Installing from a cached wheel does not run setup.py and so does not produce the bug.

**Comment by tdsmith** [comment]
e.g. if you `rm -rf ~/.cache/pip` (on Linux), you should observe `pip install holoviews[all]` failing.

**Comment by jlstevens** [comment]
The PR reference above should have fixed the issue with installing the examples (and fixed pip installation generally). Closing.
