### ISSUE TITLE
Improving Chart and Path constructors

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#166]
Currently we have a few different main types of Elements each accepting data in a specific format. We should have a general discussion about the signatures we want to support for each Element type for consistency and ease of use, while keeping the behavior well defined. I'll outline what is supported for each type of Element and the extension that we're proposing. All this is distinct from the conversion interfaces which allow casting between Element types.

## Chart Elements

Data structure is a ``NxD`` array where N is the number of samples and D the number of dimensions.

Constructors:

1) ``NxD`` array supplied directly
2) Iterator of tuples of the form [(x1, y1, z1, ...), (x2, y2, z2...), ...], usually constructed by zipping x/y/z coordinates.
3) Iterator of length N, e.g. np.random.rand(10) assumed to be y-values, and x-values are auto-generated as indices.

Proposed constructor:

4) Tuple of iterators, of the form (xs, ys, zs....). Internally the xs, ys, zs etc. are vstacked to become a ``NxD`` array.

## Path Elements

Includes: Path, Contours, Polygons

The data is stored as a list of Nx2 arrays.

1) List of Nx2 arrays.
2) List of lists of tuples, i.e. same as the Chart 2) but nested in a list.

 Proposed constructor:

3) Same as proposed new Chart constructor but nested in a list, i.e. [(xs1, ys1), (xs2, ys2)].

I think anything more than this will start getting to confusing but I think supplying xs and ys as separate iterators is a very useful format that should be supported.

**Comment by jbednar** [comment]
Just to clarify, if you mean for the proposed constructors to be additional options, can you renumber them  to start at one more than the list of existing constructors?  Or just state that all of them are meant to be in addition, not to replace the existing ones?

**Comment by philippjfr** [comment]
They'd be addition to the existing constructors. Changed the numbering accordingly.

**Comment by philippjfr** [comment]
Looking at the code I just realized that as part of Issue #100 we implemented another constructor for Path, where a single tuple of the form (xs, ys) of shapes xs=(N,) and ys=(N, M) with N samples and M paths expands to ``[(xs, ys[:, 0]), (xs, ys[:, 1]), ... (xs, ys[:, M-1]) ]``. If we continue to support this as well we'll be supporting 4 constructors for both Chart and Path types.

**Comment by jlstevens** [comment]
I'm in favor of the new constructor - it keeps the data together as a tuple which is fine for ``.data``. It removes the unnecessary zipping which does get annoying (though I think it is good to maintain that format as an option).

**Comment by philippjfr** [comment]
I've added the new constructors along with documentation and unit tests in https://github.com/ioam/holoviews/commit/922b5734410a11a52d008b4bb2bde4929b5ce243 and https://github.com/ioam/holoviews/commit/6692028ab31cfc862aee4e19673dc0d82372df79. I'll close the issue now.
