### ISSUE TITLE
Bokeh server warning message

### ISSUE THREAD

**Issue by ea42gh** [ioam/holoviews#1660]
the code server = renderer.app(dmap, show=True, new_window=True)
results in a warning message
WARNING:root:BokehServerWidgets24371: Setting non-parameter attribute display_options={'fps': 20} using a mechanism intended only for parameters

**Comment by jlstevens** [comment]
Should be a trivial fix.

**Comment by ea42gh** [comment]
Is there a way to suppress warnings such as

INFO:bokeh.server.server:Starting Bokeh server version 0.12.6 (running on Tornado 4.5.1)

**Comment by philippjfr** [comment]
>Is there a way to suppress warnings

That's a log message and is therefore not easily suppressed but I'm wondering if this is a bad interaction between the param logger and bokeh's logger. I don't think INFO level log messages should be visible to a user by default (might be wrong though).
