### ISSUE TITLE
Colorbar issues

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#167]
Image size changes with asymmetric bounds and a colorbar.
```
%%opts Image [colorbar=True] 
hv.Image(np.random.rand(10,10), bounds=(0,0,2,2))
```
![download](https://cloud.githubusercontent.com/assets/6897215/8271293/b0a9e0ac-180f-11e5-8ed9-2bc9e8709936.png)

```
%%opts Image [colorbar=True] 
hv.Image(np.random.rand(10,10), bounds=(0,0,2,35))
```
![download 1](https://cloud.githubusercontent.com/assets/6897215/8271296/bb1a29a2-180f-11e5-874f-0d4e6d2f0be7.png)

**Comment by basnijholt** [comment]
One other colorbar issue when I try two use two colormaps in one ``Image``:

```
%%opts Image.neg (cmap='binary') [colorbar=False] Image.pos (cmap='gist_heat_r') [colorbar=False] 
dat = np.random.rand(10,10) * 2 - 1
pos = np.ma.masked_array(dat, dat<0)
neg = np.ma.masked_array(dat, dat>=0)
hv.Image(pos, group='pos') * hv.Image(neg, group='neg')
```

![download 6](https://cloud.githubusercontent.com/assets/6897215/8271693/30b833d8-1825-11e5-8f43-36bb118bf046.png)

But with:

```
%%opts Image.neg (cmap='binary') [colorbar=True] Image.pos (cmap='gist_heat_r') [colorbar=True] 
```
![download 7](https://cloud.githubusercontent.com/assets/6897215/8271697/46966242-1825-11e5-8f0b-ce3b107b4b2e.png)

**Comment by philippjfr** [comment]
The second example isn't surprising, you're overlaying two Images, which results in two colorbars. We could consider allowing multiple colorbar positions but I'm not sure how common it is to overlay two Images anyway. The bounds issue I'll have to look into as there is definitely something going wrong there.

**Comment by philippjfr** [comment]
Colorbars should now behave correctly independent of the plot aspect ratio and multiple colorbars are now also supported. Please test it but as it seems to work on my end I'll close the issue.

**Comment by jbednar** [comment]
Colorbar sizing now works properly on my example notebook, thanks!

**Comment by basnijholt** [comment]
It still doesn't work for me.

```python
%%opts Image [colorbar=True] [aspect='square']
hv.Image(np.random.rand(100,100), bounds=(0,0,2,10))
```

![download](https://cloud.githubusercontent.com/assets/6897215/9155312/6636949a-3eb4-11e5-8314-89f11d05dbe6.png)
