### ISSUE TITLE
Consider looking for "local" rc file before "global" one

### ISSUE THREAD

**Issue by ceball** [ioam/holoviews#1689]
HV looks for an rc file in this order:
```
for rcfile in [os.environ.get("HOLOVIEWSRC", ''),
               "~/.holoviews.rc",
               "~/.config/holoviews/holoviews.rc",
               os.path.abspath(os.path.join(os.path.split(__file__)[0],
                                            '..', 'holoviews.rc'))]:
```

Would it make more sense to look for the local (to the particular hv being used)/dev rc file before the ones in home directory?

**Comment by jlstevens** [comment]
I am happy to make this change but haven't thought too deeply about the implications. I *think* the sensible order might be: environment variable, local holoviews.rc, ~/.holoviews.rc then the one in ``~/.config``. 

@jbednar @philippjfr Any objections if I switch to that order? Do you agree it is more sensible than the current ordering?

**Comment by jlstevens** [comment]
The PR referenced above (#1700) has been merged. Closing.
