### ISSUE TITLE
The hidden_labels parameter can be eliminated using xaxis and yaxis options

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#169]
In the development branch since the last release (I think!) a new plot option has appeared called ``hidden_labels`` which is needed to get shared axes to work.

I believe there is no need for a new parameter when we have ``xaxis`` and ``yaxis`` as object selectors already. I can imagine adding a 'bare' mode to these parameters as follows:

```python
xaxis = param.ObjectSelector(default='left', 
        objects=['left', 'right', 'left-bare', 'right-bare', None], ...
```
And then:

```python
yaxis = param.ObjectSelector(default='bottom', 
         objects=['bottom', 'top', 'bottom-bare', 'top-bare', None], ...
```

I would prefer extending the objects accepted by these two existing parameters over adding a new parameter.

**Edit**: I would also consider how ``show_frame`` interacts with this and think a bit about whether it is really needed...

**Comment by philippjfr** [comment]
This was addressed by https://github.com/ioam/holoviews/commit/269ed7f0f55c53dd051ac907bc01d6873eea5d71. ``hidden_labels`` has been eliminated in favour of the suggestion for xaxis and yaxis above.
