### ISSUE TITLE
rcParams are not overwritten everywhere

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#170]
With holoviews the following thing doesn't work:

```
from holoviews.plotting.mpl import MPLPlot
MPLPlot.fig_rcparams['text.usetex'] = True
MPLPlot.fig_rcparams['text.latex.preamble'] = [r'\usepackage{siunitx}']
hv.Image(np.random.rand(10,10), label=r'$\num{12345,67890}$')
```

But it does work when I set it in matplotlib directly.
```
import matplotlib as mpl
mpl.rcParams['text.usetex'] = True
mpl.rcParams['text.latex.preamble'] = [r'\usepackage{siunitx}']
hv.Image(np.random.rand(10,10), label=r'$\num{12345,67890}$')
```

**Comment by philippjfr** [comment]
As part of fec1680b97e11ace1350d8b3eb8ac3c8e105d46d I introduced a system to handle global backend state and since 751210fc11927e6410d4a2a26ba6da2c6132fc89 rcParams are now being applied and reset correctly. The above example now works for me so I'll close the issue.
