### ISSUE TITLE
Getting Started Customization shows Plots when saying shows text

### ISSUE THREAD

**Issue by hsparra** [ioam/holoviews#1703]
In the Getting Started section of the documentation, the second cell that creates the curve and spike show two plots but the text right afterwards states

*Notice that the representation for this object is purely textual;*

The next two cells then goes on to load the plotting systems and then display the plots and then the text states:

*As you can see, we can immediately appreciate more about this dataset than we could from the textual representation*

![holoviews doc issue](https://user-images.githubusercontent.com/7515105/27987437-3ffd863a-63d3-11e7-9f91-0f73a73b2c3d.png)

**Comment by ceball** [comment]
Well spotted! This doesn't happen when you execute the notebook yourself, which is how I went through the getting started guide.

I guess the documentation building system must have loaded a plotting system before it executes the notebook.

(There's a collection of website problems in #1661.)

**Comment by hsparra** [comment]
See #1696 for documentation typos

**Comment by jlstevens** [comment]
Thanks for reporting this!

It was an oversight on our part, we forgot that we are loading the extension ahead of time in the documentation building process. Definitely want to fix this for 1.8.2 and we'll try to fix this on the website before then.

**Comment by philippjfr** [comment]
Just have to remove the extension loading from the nbpublisher ipython profile.

**Comment by jlstevens** [comment]
I'll make a PR on nbpublisher now. I *think* this is safe to do because none of our current docs *should* be relying on the extension being loaded. I'm not 100% sure though and you never know!

**Comment by philippjfr** [comment]
Don't anticipate any issues, closing.
