### ISSUE TITLE
redim.step only works for float dimensions, not integers

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#1707]
```
import numpy as np
import holoviews as hv
hv.extension('bokeh')

def fm_modulation(f_carrier=110, f_mod=110, mod_index=1, length=0.1, sampleRate=3000):
    x = np.arange(0, length, 1.0/sampleRate)
    y = np.sin(2*np.pi*f_carrier*x + mod_index*np.sin(2*np.pi*f_mod*x))
    return hv.Curve((x, y), kdims=['Time'], vdims=['Amplitude'])

dmap = hv.DynamicMap(fm_modulation, kdims=['f_carrier', 'f_mod'])
dmap = dmap.redim.range(f_carrier=((10, 110)), f_mod=(10.0, 110.0))
dmap = dmap.redim.step(f_carrier=10).redim.step(f_mod=10)
dmap
```

![image](https://user-images.githubusercontent.com/1695496/28038600-6558f05a-65b7-11e7-97b1-2f0f1e4288de.png)

**Comment by jlstevens** [comment]
I didn't realize it in the tutorial but the issue was the declaration of ranges as ints, not floats. What is wrong here is that using a float step value should be respected even if the the ranges were set using integers.

**Comment by jbednar** [comment]
We may be talking about different things here, because in the code above I'm telling both dims to have an integer step of 10, but f_carrier is ignoring the step, even though it's defined to have an integer range, whereas f_mod is respecting the step.  So this is not an example of using a float step value, right?

**Comment by jlstevens** [comment]
Seems like there may be two related problems here.
