### ISSUE TITLE
Holoviews stacked bar chart broken for mix of positive and negative values

### ISSUE THREAD

**Issue by jdargent** [ioam/holoviews#1709]
Following the logic to use Holoviews for high level charts going forward I tried to create a stacked bar chart which work great when all values are either positive or negative. However, there are a few issues:

1. Stacking is breaking if it's a mix of positive and negative value. 
2. Hover tools is not working on negative values (even when they are all negative and the stacking does work then)

The deprecated "Bar" in Bokeh worked well and give you expected stacked bars (all positive stacking > 0 and all negatives stacking below 0). 

![bokeh](https://user-images.githubusercontent.com/3827405/28042462-5a93e4b6-659b-11e7-8a60-2a283a3ea9e3.PNG)

Switching to Holoviews, it does not stack up properly using same code example as provided in the demos: http://holoviews.org/gallery/demos/bokeh/bars_economic.html#bokeh-gallery-bars-economic

![holoviews](https://user-images.githubusercontent.com/3827405/28042489-74ad6016-659b-11e7-93c0-2b3b8b94dcc3.PNG)

It is also wrong using code provided under http://holoviews.org/reference/elements/bokeh/Bars.html

![holoviews2](https://user-images.githubusercontent.com/3827405/28042519-9f533994-659b-11e7-8181-1bd69048d7db.PNG)

I have also added the sample data I used. Value 1 column is all positive, Value 2 column is all negative values, Value 3 is a mix of positive and negative and the one failing. 

[stacked_bars.xlsx](https://github.com/ioam/holoviews/files/1137235/stacked_bars.xlsx)

PS: the stacked bar provided in http://dev.holoviews.org/Tutorials/Columnar_Data.html does not work for me.

**Comment by jlstevens** [comment]
Thanks for reporting this!

Looking at the sort of example you are trying to recreate, we realize we hadn't considered using negative values for stacking. We see no problem fixing the plotting code to account for negative values correctly.

**Comment by jdargent** [comment]
Great, thanks Jean Luc. 

To give you a little more background my goal is to create standalone HTML file with multiple graphs and customJS callback. I hope to be able to mix Holoviews and Bokeh charts. I know that I won't be able to use ColumnData in Holoviews (it would be great) but I assume I can use a similar CustomJS script.

**Comment by philippjfr** [comment]
Now fixed, closing.
