### ISSUE TITLE
Overlay of Path and HLine doesn't work with LaTeX label.

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#171]
Works fine:
```
x = np.linspace(-10, 10)
y = x**2
im = hv.Path((x, y))
im * hv.HLine(0)
```
![download 17](https://cloud.githubusercontent.com/assets/6897215/8273310/05ac9876-1868-11e5-8c56-531b00d76a4f.png)

Doesn't properly plot:
```
x = np.linspace(-10, 10)
y = x**2
im = hv.Path((x, y)).relabel(label=r"$\mathbf{B}=0.5\hat{x}$ T")
im * hv.HLine(0)
```

![download 15](https://cloud.githubusercontent.com/assets/6897215/8273303/dcd61d3c-1867-11e5-8ef0-a4c54751fbf7.png)

**Comment by philippjfr** [comment]
Can confirm that I can replicate the bug. The Overlay seems to once again be dropping the object due to it's label. Thought it might be hitting a maximum attribute length or something because the sanitized version of the label is:

```
'reverse_over_mathbf_left_curly_bracket_B_right_curly_bracket_equals_0_full_stop_5_reverse_over_hat_left_curly_bracket_x_right_curly_bracket_T'
```

But that seems to work just fine as an attribute. Will have to investigate further tomorrow.

**Comment by basnijholt** [comment]
Not sure whether is has anything to do with the sanitised version being to long, because this also doesn't work:

```
x = np.linspace(-10, 10)
y = x**2
im = hv.Path((x, y)).relabel(label=r"\hat{x}$")
im * hv.HLine(0)
```

**Comment by philippjfr** [comment]
No it's definitely not, attribute names can be any length. Something going wrong on  ``Overlay`` or its baseclass ``AttrTree``.

**Comment by philippjfr** [comment]
This has been fixed in https://github.com/ioam/holoviews/commit/5b3f40b265c8b0204a949df30d81a5a14f1d379d. The trees weren't properly capitalizing all paths. It should actually be fixed in general this time so I'll close the issue.
