### ISSUE TITLE
Missing dask.array import?

### ISSUE THREAD

**Issue by ceball** [ioam/holoviews#1710]
While running https://github.com/ioam/scipy-2017-holoviews-tutorial/blob/master/notebooks/05-working-with-gridded-data.ipynb, a Canopy user reported the following:

```
In []: mri = hv.Dataset(mri_xr)
In []: mri
Out []: :Dataset   [y,x,z]   (MR)

In []: mri.to(hv.Image, groupby='z', dynamic=True)
Out []:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/Users/UserX/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/IPython/core/formatters.pyc in __call__(self, obj)
   305                 pass
   306             else:
--> 307                 return printer(obj)
   308             # Finally look for special method names
   309             method = get_real_method(obj, self.print_method)

/Users/UserX/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/holoviews/ipython/display_hooks.pyc in pprint_display(obj)
   257     if not ip.display_formatter.formatters['text/plain'].pprint:
   258         return None
--> 259     return display(obj, raw=True)
   260
   261

/Users/UserX/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/holoviews/ipython/display_hooks.pyc in display(obj, raw, **kwargs)
   243     elif isinstance(obj, (HoloMap, DynamicMap)):
   244         with option_state(obj):
--> 245             html = map_display(obj)
   246     else:
   247         return repr(obj) if raw else IPython.display.display(obj, **kwargs)

/Users/UserX/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/holoviews/ipython/display_hooks.pyc in wrapped(element)
   129         try:
   130             html = fn(element,
--> 131                       max_frames=OutputSettings.options['max_frames'])
   132
   133             # Only want to add to the archive for one display hook...

.... [ trace is too long] ...

/Users/UserX/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/holoviews/core/data/__init__.pyc in range(self, dim, data_range)
   261         elif dim in self.dimensions() and data_range:
   262             if len(self):
--> 263                 drange = self.interface.range(self, dim)
   264             else:
   265                 drange = (np.NaN, np.NaN)

/Users/UserX/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/holoviews/core/data/xarray.pyc in range(cls, dataset, dimension)
    99             data = dataset.data[dim]
   100             dmin, dmax = data.min().data, data.max().data
--> 101             if dask and isinstance(dmin, dask.array.Array):
   102                 dmin, dmax = dmin.compute(), dmax.compute()
   103             dmin = dmin if np.isscalar(dmin) else dmin.item()

AttributeError: 'module' object has no attribute 'array'
```

I'm not sure why they'd be seeing this error when others (conda users) don't, but core/data/xarray.py does seem to only import ``dask`` - so how do lines like ``if dask and isinstance(dmin, dask.array.Array)`` work?

**Comment by jlstevens** [comment]
Thanks for reporting this! We now think there is a simple fix.

**Comment by ceball** [comment]
Do you know why the error was not appearing for conda users?

**Comment by jbednar** [comment]
No idea, but I have noticed many occasions not to do with conda where things mistakenly work without proper importing. I suspect python is just lax about this.

**Comment by ceball** [comment]
I'd guess something along the lines of: conda users (i.e. people who installed the recommended set of packages plus their dependencies, according to conda) have some package that allows some optional code to run in some part of holoviews that results in dask.array being imported before. Or some package (not holoviews) causes dask.array to be imported. Something like that.

> I suspect python is just lax about this
(Not sure what you mean.)

**Comment by philippjfr** [comment]
>conda users have some package that allows some optional code to run in some part of holoviews that results in dask.array being imported before

That seems likely. Since we now import it explicitly I'll close this but at some point we'll probably profile our imports because HoloViews is getting fairly slow to import when you have the various data backends installed.

**Comment by ceball** [comment]
Sorry, didn't realize that my comment reopened the issue.

My next comment was actually going to be that holoviews is slow to import, and do you know why? But you predicted it :) I was going to write the same on datashader, too. But I think I will give you guys a break from the trivial stuff for a bit now.

**Comment by jlstevens** [comment]
> My next comment was actually going to be that holoviews is slow to import

I think it *mostly* comes down to holoviews importing multiple things that are themselves slow to import!
