### ISSUE TITLE
Datetime axis numeric formatting

### ISSUE THREAD

**Issue by linar-jether** [ioam/holoviews#1713]
When trying to plot a simple time series for multiple nodes, the time axis (X) shows numeric format instead of datetime formatting

```python
%%opts Curve [width=1100 height=500 ]

# Wide df
df = pd.concat([pd.util.testing.makeTimeSeries(100, 'H', x).tz_localize('America/Chicago') for x in ['A', 'B', 'C']], axis=1)

# Change to long
df.columns.name = 'pid'
df.index.name = 'ts'
df = df.stack().to_frame('price')

hv.Dataset(df.reset_index()).to(hv.Curve, 'ts', 'price',).overlay()
```

First solution found was to use :
```python
from bokeh.models import DatetimeTickFormatter
def apply_formatter(plot, element):
    plot.handles['xaxis'].formatter = DatetimeTickFormatter()

%%opts Curve [width=1100 height=500 finalize_hooks=[apply_formatter]]
```
It works, but seems overkill...

![localhost-8888-notebooks-untitled2 ipynb](https://user-images.githubusercontent.com/11908736/28120037-e45118dc-66e4-11e7-888f-b5affb4db7da.png)

**Comment by jlstevens** [comment]
Thanks for reporting this!

Date formatting should happen automatically for appropriate date types so we'll need to investigate. Glad the finalize hook works for you for the time being, but you shouldn't need it!

**Comment by philippjfr** [comment]
It appears this is related to datetimes with a particular timezone.

**Comment by jlstevens** [comment]
> It appears this is related to datetimes with a particular timezone.

I believe I saw a bokeh issue where @bryevdv said that timezones cause a lot of headaches and aren't supported. I might be misremembering though!

**Comment by bryevdv** [comment]
Bokeh sends datetime values timedone-naive. I.e. they are displayed “as is”. If something else is desired, a custom formatted or extension is an option.

**Comment by philippjfr** [comment]
This is definitely a bug in holoviews, we just have to add ``pd.core.dtypes.dtypes.DatetimeTZDtypeType`` to the list of recognized datetime_types. This is a temporary workaround:

```python
hv.core.util.datetime_types = hv.core.util.datetime_types + (pd.core.dtypes.dtypes.DatetimeTZDtypeType,)
```
