### ISSUE TITLE
Messy x-axis when using a dictionary to make a curve

### ISSUE THREAD

**Issue by drs251** [ioam/holoviews#1714]
I know I could use a tuple of lists or a list of tuples to avoid it, but IMO this behavior is still pretty annoying:

```python
import numpy as np
import holoviews as hv
hv.notebook_extension()
x = np.linspace(0, 6, 11)
y = {xval: np.sin(xval) for xval in x}
hv.Curve(y)
```

![download](https://user-images.githubusercontent.com/25608220/28134410-2e8e1fc2-6743-11e7-8cf9-2e5b14a2a4e8.png)

It seems obvious that this is caused by the unordered nature of dictionaries, and that holoviews does not order the values for you. Looking at the above graph, I think it would be reasonable to order the data by the keys somewhere in holoviews before plotting. IMO, the result of passing a dictionary to `Curve` should be like this (out of the box):

```python
hv.Curve([(x, y[x]) for x in sorted(y.keys())])
```

![download 1](https://user-images.githubusercontent.com/25608220/28134558-996ee09c-6743-11e7-8d1d-6d29a8d0fcf9.png)

Any thoughts?

**Comment by jlstevens** [comment]
I think this is a reasonable suggestion. 

My only worry is there may some instances where curve is abused to plot things that aren't *quite* functions. That said, given (regular) dictionary ordering is undefined it is probably good, predictable behavior to always sort. Thinking about it, I support this proposal.

**Comment by jbednar** [comment]
I agree, but only for plain Python dictionaries. Ordereddict and any of the list or dataframe objects should never sort, because everything but dictionaries preserves the order already, and I think it's reasonable for users to be relying on that behavior.

**Comment by drs251** [comment]
I agree with you both: if an order of points is specified by the user, it should be respected. Automatic sorting should only apply to plain Python dictionaries, where there is no intrinsic order.

**Comment by philippjfr** [comment]
Now implemented.
