### ISSUE TITLE
Make it easy to derive grouped histograms from Dataset

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#1716]
Right now it is difficult to derive histograms from ``Dataset`` as frequencies are derived from the raw data and are a function of all the various bin widths. The best suggestion seems to be to support a ``group_by`` argument to the ``hist`` method that does the grouping and returns the output as an ``NdOverlay``.

**Comment by philippjfr** [comment]
This has now been added along with some gallery examples.
