### ISSUE TITLE
Issues found in the bokeh deployment in SciPy17 tutorial

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#1721]
This issue is to record two issues I noticed in the [bokeh deployment notebook](https://github.com/ioam/scipy-2017-holoviews-tutorial/blob/master/notebooks/08-deploying-bokeh-apps.ipynb) of the SciPy tutorial:

* Some of the plot options don't seem to be applying properly in the apps launched as scripts with ``bokeh serve``.
* Using 'Run All' stops the display of the app using the ``periodic`` parameter to update the taxi dataset.

**Comment by philippjfr** [comment]
I'm going to close this, the first issue is too unspecific to be useful and the second no longer applies to the PyViz tutorials. If these issues occur again they should be re-raised with a specific example
