### ISSUE TITLE
Tabular Dataset user guide has a bug in table display

### ISSUE THREAD

**Issue by thoth291** [ioam/holoviews#1722]
As you can see http://holoviews.org/user_guide/Tabular_Datasets.html
The table X has only 0-s while it should have some ones too (check the X axis of the plot below the table).
<img width="746" alt="screen shot 2017-07-14 at 12 11 32 am" src="https://user-images.githubusercontent.com/2971670/28199221-b3638e6c-6829-11e7-8a30-45fed5e5b012.png">

**Comment by philippjfr** [comment]
It's just the way it's sorted, if you scroll down all the way you can see the 1s.
