### ISSUE TITLE
holoviews.org website 404 errors

### ISSUE THREAD

**Issue by alexey-petrenko** [ioam/holoviews#1726]
There are multiple broken links on the holoviews.org website:

Almost all links on the tutorial page (http://holoviews.org/Tutorials/index.html)
like:
http://holoviews.org/Tutorials/Bokeh_Backend.html
http://holoviews.org/Tutorials/Showcase.html
etc.

http://holoviews.org/Tutorials/Linked_Streams.html -- this was a useful tutorial, I wonder why it disappeared even before the website upgrade.

It would be very nice to keep the old website alive for some time, while the new version is under deployment.

Thanks!

**Comment by jlstevens** [comment]
Thanks for reporting this!

We are aware of a number of these (see #1661 #1650) and we'll check to make sure all the broken links you mentioned are fixed for 1.8.2. 

As for the Linked Streams tutorial, that material has now moved to the [Custom Interactivity](http://holoviews.org/user_guide/Custom_Interactivity.html) user guide.

**Comment by alexey-petrenko** [comment]
Please also note that Linked Streams tutorial are mentioned (using this broken link: http://holoviews.org/user_guide/Linked_Streams.html) in some other tutorials. Here for example: http://holoviews.org/user_guide/Responding_to_Events.html

**Comment by michaelaye** [comment]
Is there any other way to get to the tutorials?

**Comment by jlstevens** [comment]
The tutorials are now in the user guide. You can still find them in ``doc/Tutorials`` for the time being. Note that this issue is related to #1750.
