### ISSUE TITLE
None of the streams in 'Custom Interactivity' -guide works when copypasted to live notebook.

### ISSUE THREAD

**Issue by leevei** [ioam/holoviews#1736]
I've copypasted the entire thing in jupyter live notebook, and the pictures are printed just fine, but nothing happens when I move the mouse or click or do anything.

**Comment by leevei** [comment]
Same thing with this example: [Tap](http://holoviews.org/reference/streams/bokeh/Tap.html)

**Comment by jlstevens** [comment]
Thanks for reporting this!

Which HoloViews version are you using?

```python
import holoviews as hv
print(hv.__version__)
```

**Comment by jlstevens** [comment]
Just to say I tested the ``Tap`` example by copying it into a live notebook and it worked fine for me. I assume the issue is down the version differences: you'll need to latest stable holoviews and bokeh versions.

**Comment by leevei** [comment]
I had versions 1.8.1.something of holoviews and 0.12.4 of bokeh. I installed with 'conda install -c ioam holoviews bokeh' assuming it would get me latest stable releases. Now I have hv 1.6.2 and bokeh 0.12.4, and cant even import streams.

**Comment by leevei** [comment]
OK. Seems like datashader and bokeh 0.12.6 cant be at the same time. Have to use decimate from now on until this is fixed. Seems like the problem has nothing to do with holoviews, except that holoviews users really want to use both datashader and bokeh 0.12.6..

**Comment by jlstevens** [comment]
> Seems like datashader and bokeh 0.12.6 cant be at the same time.

@jbednar I'm hoping the next datashader release will be soon to fix this!

Glad you figured it out, I think using the bokeh channel is the best bet right now.
