### ISSUE TITLE
NdLayout opts undoes cols

### ISSUE THREAD

**Issue by jordansamuels** [ioam/holoviews#1738]
It appears that calling `.opts()` on an `NdLayout` will undo the effects of `.cols()`.  E.g.
```
c = hv.Curve(np.arange(3))
hv.NdLayout([(n,c) for n in range(5)]).cols(2).opts(plot=dict(title_format="> 2 columns"))
```

results in

![image](https://user-images.githubusercontent.com/610909/28437096-01b4252e-6d5f-11e7-87ac-e635b10a6131.png)

The does not appear to be a problem with `Layout`.

**Comment by jlstevens** [comment]
I suspect ``NdLayout`` needs a clone method that preserve ``cols``, the way ``Layout`` does it:

```
    def clone(self, *args, **overrides):
        """
        Clone method for Layout matches Dimensioned.clone except the
        display mode is also propagated.
        """
        clone = super(Layout, self).clone(*args, **overrides)
        clone._max_cols = self._max_cols
        clone.id = self.id
        return clone
```

Not sure why the ``id`` isn't propagated by the ``super`` call here but that is separate from what is important for this issue, namely transferring the value of``_max_cols``.

**Comment by philippjfr** [comment]
Now fixed, closing.
