### ISSUE TITLE
Get rid of xticker and yticker parameters

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#174]
The ``xticks`` and ``yticks`` parameters are being improved to be more useful in a way that I think makes the ``xticker`` and ``yticker`` parameters redundant.

We want to avoid redundant options so I think these ticker parameters should be removed.

**Comment by philippjfr** [comment]
As part of commit https://github.com/ioam/holoviews/commit/62bb488836d1d006278bbf3a21370638bd376704 I folded the x/y/zticker in with the x/y/zticks plot option. This breaks backward compatibility for this options and should be noted prominently in the changelog. I'll close this issue now.
