### ISSUE TITLE
label/group don't work for Table/ItemTable

### ISSUE THREAD

**Issue by jordansamuels** [ioam/holoviews#1741]
These show no label/group text:
```
hv.ItemTable([('hello','world')], label='label', group='group') 
hv.Table({'hello': ['world']}, kdims=['hello'], label='label', group='group')
```

One can work around this by wrapping in a `Layout` but unfortunately nesting doesn't work.  

This shows text **label group**:
```
hv.Layout([hv.ItemTable([('hello','world')])], label='label', group='group')
```

But this does not:
```
hv.Layout([hv.Layout([hv.ItemTable([('hello','world')])], label='label', group='group')])
```

**Comment by jlstevens** [comment]
Note, ``group`` and ``label`` do work with the matplotlib backend which means this seems to be a limitation of the bokeh TablePlot implementation. I presume this is because bokeh uses a third party JS library to display tables, making them a bit different from other bokeh plots.

**Comment by philippjfr** [comment]
Could also just be an oversight on the ``TablePlot`` implementation in the bokeh backend, will have to investigate.

**Comment by philippjfr** [comment]
Turns out you are right, it's not just an oversight. Bokeh's ``DataTable`` indeed does not support titles.
