### ISSUE TITLE
Any way to change bar width and add grid lines?

### ISSUE THREAD

**Issue by Jerryzhuht** [ioam/holoviews#1747]
I use %%opts Bars. It seems that we don't have these attributes.

**Comment by jlstevens** [comment]
As you say, I don't see a bars width plot option on ``BarPlot``. 

I don't understand what do you mean by 'and add inline' though...

**Comment by Jerryzhuht** [comment]
Sorry. I mean gird.

**Comment by jlstevens** [comment]
To enable the grid you can use:

```
%%opts Bars [show_grid=True]
```

**Comment by Jerryzhuht** [comment]
Thanks.

**Comment by Jerryzhuht** [comment]
BTW is there any way to remove the boarder line of the bars?

**Comment by philippjfr** [comment]
>BTW is there any way to remove the boarder line of the bars?

``%%opts Bars (line_width=0)``

or

``%%opts Bars (line_alpha=0)``

should both work.

Also width is a style option so you should be able to do ``%%opts Bars (width=0.8)``, where a value of 1 would leave no padding and anything lower than that increases the amount of padding.

**Comment by jlstevens** [comment]
@Jerryzhuht If you can confirm this works for you, I think we can close this issue.

**Comment by Jerryzhuht** [comment]
@jlstevens Sure. It works well for me. Thanks!

**Comment by jlstevens** [comment]
Great! Closing the issue.
