### ISSUE TITLE
drop down menus from docs not appearing

### ISSUE THREAD

**Issue by michaelaye** [ioam/holoviews#1749]
The documentation here:

http://holoviews.org/getting_started/Tabular_Datasets.html

says that when plotting the diseases like so:

```python
%%opts Curve [width=600 height=250] {+framewise}
(ds.to(hv.Curve, 'Year', 'measles') + ds.to(hv.Curve, 'Year', 'pertussis')).cols(1)
```

that a drop-down menu for the states choice should appear.
This is not the case on my system, the state is just a printed text.

* macOS 10.12.5
* python 3.6 via conda-forge (all versions up-to-date as of today)
* ipywidgets 6.0.0 
* notebook GH master (commit: f81fb46ff68323f9652d638a325e9ccc46f62e83)
* Chrome Version 59.0.3071.115 (Official Build) (64-bit)

**Comment by jlstevens** [comment]
Thanks for reporting this!

Could you show an example of what this printed text looks like?

**Comment by michaelaye** [comment]
Sorry, didn't see that the dropdown is on the right, was using small laptop screen. All good and thanks for this library!
