### ISSUE TITLE
Passing function to dynamic map with annotations keyword-only parmeters

### ISSUE THREAD

**Issue by GProtoZeroW** [ioam/holoviews#1753]
Trying to pass in a keyword-only and with annotation function to DynamicMap Resulting in ValueError and telling me to use the inspect getfullargspec: 

the function being passed in help string is 
><lambda> lambda I_S:'I_S'=1e-10, T_C:'T_C'=25, n:'n'=1.1, v_D:'v_D'=0.1
>    I_S*(exp(11604.522060401*v_D/(n*(T_C + 273))) - 1)

also, a bit more clarity on how to set the dimension and range would be beneficial
right now the cell to make the dynamic map looks like:
```
Min=-273.0; Max=2500
TempRange=np.linspace(Min, Max, int(np.abs(Max-np.abs(Min)))*2 )
#create hv diminsion for temp
TempC = hv.Dimension('TempC', label='Tempture', unit='C', values=TempRange)
#create hv didmintion for thermal voltage
ThermV = hv.Dimension('VoltT', label='Thermal Voltage (V_T)', unit='V')
RevSatRange=np.logspace(-6, -11)
Isat=hv.Dimension('Isat', label='Reverse Sat. Current', unit='A')
nRange=np.arange(1.0, 2.0+.01, .01)
ideFac=hv.Dimension('n', label= 'ideality factor')
VDDiff=hv.Dimension('vd', label='Anode-Cathode Voltage', unit='V')
VD_dmap=hv.DynamicMap(ShockleyDiodeTcEQN)
```

Reading the docs last night indicates that the above can be simplified greatly
end goal of above would be to have function ouput on vert, v_D on horz and T_C, n, I_S on slider widgets

thanks

**Comment by jlstevens** [comment]
> lambda I_S:'I_S'=1e-10, T_C:'T_C'=25, n:'n'=1.1, v_D:'v_D'=0.1
I_S*(exp(11604.522060401v_D/(n(T_C + 273))) - 1)

I'm a little confused: if this is the callback you are using in DynamicMap, it isn't returning an element to visualize. Is this correct?

**Comment by GProtoZeroW** [comment]
Yeah, I was a bit confused on what holoviews sees as storage. I thought it would run the lambda function to something like a numpy Structured array internaly for every call and then the rest of the dynamic map arguments would tell it how I wanted that data outputted to displays that then get +* to make the final form

I managed to get it working by wrapping the lambda in another function that built and returned hv.Curve; but, feel the issues that caused this whole misunderstanding is that hv.Curve is a representation of data in some internal like a pandas.dataframe.plot(). And this misconception seems to be reinforced by hv.Dimension and that holoviews support xarray. 

So does holoviews have a data holding object like an xarray that I can set all the dimensions then call those to hv.Curve for example or is hv.Curve((x, y). kdims, vdims) the end all be all data storage unit

Also, you lot did a lot of doc improvements; but where should I be posting for things that need some more clarification or quick examples. on issues, stack exchange, ect. This isnt a just for holoview; it seems to be an issue with both open source and closed source and it's getting out of hand

**Comment by philippjfr** [comment]
If you need help I'd recommend our [Gitter](https://gitter.im/ioam/holoviews) flow. 

>I thought it would run the lambda function to something like a numpy Structured array internaly for every call and then the rest of the dynamic map arguments would tell it how I wanted that data outputted to displays that then get +* to make the final form

This is a good idea and we have separately opened an issue for it: https://github.com/ioam/holoviews/issues/1930.

>So does holoviews have a data holding object like an xarray that I can set all the dimensions then call those to hv.Curve for example or is hv.Curve((x, y). kdims, vdims) the end all be all data storage unit

HoloViews objects are merely wrappers around your data, when you declare ``hv.Curve((x, y))`` various interfaces will try to read the data and then store it in a common format, supported formats include NumPy arrays, dataframes, xarray datasets, and a few more.

 I'm going to close this but do feel free to ask questions on Gitter.
