### ISSUE TITLE
show function is not working in holoviews

### ISSUE THREAD

**Issue by nagnath006** [ioam/holoviews#1754]
error showing no module is named as show but previouysly its working in bokeh.

`import pandas as plt
import sqlite3
import holoviews as hv
from datetime import datetime,date
from dateutil import parser
hv.extension('bokeh')

con = sqlite3.connect("database.sqlite",isolation_level=None)
cur = con.cursor() 	 	
age_set = {}
name = '%iniesta%'
#today = date.today()
cur.execute('select short_passing,long_passing,strength,vision,dribbling,balance,positioning from Player inner join Player_Attributes on Player.player_api_id = Player_Attributes.player_api_id where player_name like ? group by player_name',(name,))

i = list(cur.fetchone())
iniesta_attrib = {"short_passing":i[0],"long_passing":i[1],"strength":i[2],"vision":i[3],"dribbling":i[4],"balance":i[5],"positioning":i[6]}
#labels = ["short_passing","long_passing","strength","vision","dribbling","balance","positioning"]
df = plt.DataFrame.from_records([iniesta_attrib])
p_val = list(iniesta_attrib.values())
p_key = list(iniesta_attrib.keys())
print p_val
xv = plt.DataFrame({'val':p_val,'keyt':p_key})
y_v = df.columns
p = hv.Curve(xv,kdims=['keyt'],vdims=['val'],label='Iniesta')
hv.show(p)
 
`

**Comment by jbednar** [comment]
HoloViews provides a Bokeh backend to implement its plotting, but the HoloViews API is independent of Bokeh's, so there is no `show()` command in HoloViews (and no `figure()`, etc.).  If you're using Jupyter, `p` alone is sufficient to show a holoviews object "p".  Outside of Jupyter, see [Deploying Bokeh Apps](http://holoviews.org/user_guide/Deploying_Bokeh_Apps.html) for the syntax needed.

**Comment by nagnath006** [comment]
Thank you james..! @jbednar

**Comment by jlstevens** [comment]
There is ``hv.ipython.display`` which is the nearest thing to ``show`` that HoloViews has though as @jbednar pointed out, you shouldn't need it for normal HoloViews usage.
