### ISSUE TITLE
WARNING:root:Warning: Ignoring keyword pair that fails to evaluate:

### ISSUE THREAD

**Issue by opalbert** [ioam/holoviews#1755]
Hi, I tried to produce a simple timeseries graph in holoview and I get this error that makes my options not working on the graph.

WARNING:root:Warning: Ignoring keyword pair that fails to evaluate: 'width=1200'
WARNING:root:Warning: Ignoring keyword pair that fails to evaluate: 'height=450'
WARNING:root:Warning: Ignoring keyword pair that fails to evaluate: 'tools=['hover']'

Below is my entire code:
import numpy as np
import holoviews as hv
hv.extension('bokeh', width=95)
import pandas as pd
from bokeh.models import DatetimeTickFormatter
from holoviews.operation import gridmatrix
import pickle
with open('sample.pkl', 'rb') as f:
    (dates, values) = pickle.load(f)

dict = {'dates':dates, 'values':values}
df=pd.DataFrame(dict)

df["date"] = pd.to_datetime(df['dates']) 
df
![image](https://user-images.githubusercontent.com/6060244/28639087-efc10f98-7214-11e7-9f5c-dd06a32d4903.png)

vdims = [('values', 'Number of Articles')]
ds = hv.Dataset(df, kdims=['date'], vdims=vdims)

ds
:Dataset   [date]   (values)

%%opts Curve [width=1200 height=450 tools=['hover']] {+framewise}
art=ds.to(hv.Curve, 'date','values' )
art

![image](https://user-images.githubusercontent.com/6060244/28639107-04ba1c82-7215-11e7-9158-77bddd52c6b8.png)

Thanks!

**Comment by jbednar** [comment]
> dict = {'dates':dates, 'values':values}

Here you have redefined Python's in-built dictionary type `dict`, after which nothing you do is going to work. So don't do that, and you should be ok. :-)  (Just call it "d" instead of "dict", or something like that.)

**Comment by opalbert** [comment]
Thanks, it worked!
