### ISSUE TITLE
SyntaxError %%opts

### ISSUE THREAD

**Issue by nwaftp23** [ioam/holoviews#1756]
When running the bars economic example I receive the following error:

%%opts Bars [stack_index=1 xrotation=90 legend_cols=7 show_legend=False  show_frame=False tools=['hover']]
    ^
SyntaxError: invalid syntax

where the arrow belongs below the second percent sign. Please help.

**Comment by jlstevens** [comment]
On a hunch, try installing pyparsing:

```
conda install pyparsing
```

or

```
pip install pyparsing
```

And see if that resolves the issue.

**Comment by nwaftp23** [comment]
No luck, 

# All requested packages already installed.
# packages in environment at /home/stats/anaconda3:
#
pyparsing                 2.1.4                    py36_0

**Comment by jlstevens** [comment]
Very odd! And I assume the ``%%opts`` is all on one line and the newline I see above is just GitHub wrapping your comment?

**Comment by jlstevens** [comment]
An I presume you are working in the notebook? Do other magics work on for you? E.g try:

```
%%HTML
<b>Hello</b>
```

**Comment by ea42gh** [comment]
Just to rule out the obvious, is %%opts the first line in the cell?
If there is any statement above it, you would see the error described

**Comment by nwaftp23** [comment]
When running it in the notebook everything worked as expected, just when running it from the command line do I encounter that error. Here is the exact code I am running,

import numpy as np
import pandas as pd
import holoviews as hv
hv.extension('bokeh','matplotlib')


macro_df = pd.read_csv('http://assets.holoviews.org/macro.csv', '\t')
key_dimensions   = [('year', 'Year'), ('country', 'Country')]
value_dimensions = [('unem', 'Unemployment'), ('capmob', 'Capital Mobility'),
                    ('gdp', 'GDP Growth'), ('trade', 'Trade')]
macro = hv.Table(macro_df, kdims=key_dimensions, vdims=value_dimensions)


%%opts Bars [stack_index=1 xrotation=90 legend_cols=7 show_legend=False  show_frame=False tools=['hover']]
%%opts Bars (color=Cycle('Category20'))
macro.to.bars([ 'Year', 'Country'], 'Trade', [])

Thanks.

**Comment by philippjfr** [comment]
Closing as the magics will never work outside a notebook/IPython context.
