### ISSUE TITLE
Bokeh text_align doesn't work, always centered

### ISSUE THREAD

**Issue by jordansamuels** [ioam/holoviews#1757]
While http://holoviews.org/user_guide/Plotting_with_Bokeh.html does show some `text_align='center'`, it turns out this can't be overridden. 

```
hv.Text(.5, .5, "here is some text").opts(style=dict(text_align='left'))
```

behaves the same as 

```
hv.Text(.5, .5, "here is some text").opts(style=dict(text_align='center'))
```

namely:

![image](https://user-images.githubusercontent.com/610909/28645504-5aee5146-7223-11e7-84ef-69b2defbc73a.png)

**Comment by philippjfr** [comment]
This is because this option is specified directly on the ``Text`` Element. I really don't like that tbh, and would like to remove these styling options from the Element itself.

**Comment by jlstevens** [comment]
The line between element attributes and plot options has always been blurry with annotations. I have always thought of annotations as a way to capture plot options along with the element, at least for things like text. That said, I'm happy to reconsider the boundaries between plot options and element data as annotations have never had much attention paid to them.

**Comment by philippjfr** [comment]
>I have always thought of annotations as a way to capture plot options along with the element, at least for things like text.

It just seems very inconsistent. I favor adding deprecation warnings for these in v1.10.

**Comment by jlstevens** [comment]
In that case we would need a more element-like text annotation before we can start deprecating these things...

**Comment by philippjfr** [comment]
Yes, let's get back to this when adding the ``MultiText`` element or whatever we'll end up calling it.
