### ISSUE TITLE
Show %output holomap='widgets' in the tutorials

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#176]
The tutorials are compiled this way when building the website. We should add this line explicitly (e.g in ``Introduction.ipynb``) to make sure users don't get scrubbers when they are expecting sliders.

**Comment by jbednar** [comment]
But shouldn't the default just be changed to be scrubbers, rather than systematically overriding the setting? Seems like the same effect, more efficiently.

**Comment by jlstevens** [comment]
I've wondered this myself. Sliders are certainly more fun to play around with but scrubber also has its uses when you want to play through a parameter space automatically.

The default behavior is to switch to scrubber is there is a single key dimension, otherwise sliders are used. This means, we need to worry about this potential confusion in the documentation whenever we have a single dimension.

I am on the fence but I can the argument that we should have 'widgets' by default (so there is no switching in interface, no matter how many key dimensions there are). Then we would just need to make sure people are aware of the 'auto' and 'scrubber' options (the default behavior will automatically expose people to the different options).

**Comment by philippjfr** [comment]
I think we should default to 'widgets' they're usually what you want to use. I only really use the scrubber widget when the dimension I'm dealing with is actually time. I've also noticed that several people seem to have gotten confused about the 'auto' behavior.

**Comment by jlstevens** [comment]
I've made 'widgets' the default mode in 609f859

I would close this issue now but I do have one question: is it still worth keeping 'auto' as an option (other than for backward compatibility)?

**Comment by philippjfr** [comment]
Don't see any harm in keeping it but I also wouldn't mind seeing it go.

**Comment by jlstevens** [comment]
Ok, I don't see any harm in keeping it either so I'll close this issue now.
