### ISSUE TITLE
Tutorials not working

### ISSUE THREAD

**Issue by sachinruk** [ioam/holoviews#1761]
None of the links on http://holoviews.org/Tutorials are working. Would be great if this could be updated.

Thanks!

**Comment by ceball** [comment]
Oh no, not sure what's gone wrong there! If you want to see a version of the tutorials right now, you can try http://build.holoviews.org/Tutorials/ (these are supposed to correspond to the most recent git version of holoviews, I think).

**Comment by ceball** [comment]
Actually, there's already an issue for this: #1726. The tutorials are now in the user guide (https://github.com/ioam/holoviews/issues/1726#issuecomment-317906417) at http://holoviews.org/user_guide/index.html.
