### ISSUE TITLE
Dataset: add better validation of dimensions?

### ISSUE THREAD

**Issue by ceball** [ioam/holoviews#1762]
In the example below, I

1. create a Dataset from an array (getting no dims?) (``In [79]:``)
2. create a Dataset from a DF with numeric columns but forget to use string column names or supply dimension names (``In [81]:``)

<img width="979" alt="screen shot 2017-07-26 at 10 00 35 pm" src="https://user-images.githubusercontent.com/1929/28664956-fe9fd71a-72b9-11e7-8a86-7a73ecba1ba4.png">

I'm not sure why 1 is allowed. For 2, suggestions include:

(a) a clearer error (including maybe an error message saying that the names need to be strings, and that you could do df.columns = df.columns.astype(str) to just make it usable, but that you should instead choose reasonable names or provide explicit dimension names).

(b) maybe have some version of numerical column names used for dims (auto-name to string, e.g 0 -> 'd0' and warn about the new names)

**Comment by jlstevens** [comment]
I vote for option a) where we generate a better exception message asking for string column labels. @philippjfr ?

**Comment by philippjfr** [comment]
It should now raise the following error:

>DataError: pandas DataFrame column names used as dimensions must be strings not integers.

>PandasInterface expects tabular data, for more information on supported datatypes see http://holoviews.org/user_guide/Tabular_Datasets.html
