### ISSUE TITLE
format changed when converting into HTML

### ISSUE THREAD

**Issue by Jerryzhuht** [ioam/holoviews#1769]
Whenever I use `hv.extension('bokeh')` in Jupyter notebook and downloaded as HTML, there is a huge gap under the cell with that code, and the content blow are no longer inside the box.

In notebook:
![1](https://user-images.githubusercontent.com/30041733/28769476-43252c3a-760e-11e7-8634-a2dee54431e3.png)

When use: File -- Download as HTML:
![2](https://user-images.githubusercontent.com/30041733/28769498-6160ad8c-760e-11e7-9b15-457c7dd4c7f2.png)

**Comment by jlstevens** [comment]
Oh wow, I just reproduced this and thank you for reporting this problem!

This must be down to the additional logos added in 1.8.1 and probably down to how the divs are structured there (which looks fine in normal notebooks but is wrong after nbconvert). This is a priority fix for 1.8.2.

**Comment by Jerryzhuht** [comment]
Yeah.. the divs messed the HTML all up..

**Comment by philippjfr** [comment]
Note the divs are also messing up the rendering of notebooks exported to anaconda.org, e.g. have a look [at this notebook](https://anaconda.org/philippjfr/graphs/notebook). Unlike older notebooks it scrolls.

**Comment by Jerryzhuht** [comment]
BTW, are we going to release the new patch recently, like this month?

**Comment by jlstevens** [comment]
> Unlike older notebooks it scrolls.

I noticed that but didn't make the link to the logo.

> BTW, are we going to release the new patch recently, like this month?

Yes, this is a good reason to have 1.8.2 very soon, I estimate we can release that early next week.

**Comment by Jerryzhuht** [comment]
> Yes, this is a good reason to have 1.8.2 very soon, I estimate we can release that early next week.
That would be great +1:

**Comment by jlstevens** [comment]
The fix for this issue has now been merged. Closing.
