### ISSUE TITLE
Deprecating AdjointLayouts

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#177]
AdjointLayouts are in many ways a bad solution to the problem we were trying to solve at the time. The main reason they are a bad idea:

1.) They add additional level of nesting, making it harder to access and operate on your Elements.
2.) To get around 1. they have to implement wrapper methods for common operations on the data.
3.) They are not very flexible, allowing at most two ancillary Elements to be adjoined.
4.) Sideplots can easily become outdated and no longer reflect the data in the main plot.

Fundamentally ancillary data should be derived from the main set of data you're adjoining it to. Currently when calling `.hist` it adjoins a `Histogram` to the main plot. However if you now continue to work with this object not only is it awkward but it can actually give you misleading output. Say you add a histogram to an Image, now if you slice the `Image` with a `.select`  call on the `AdjointLayout`, the derived Histogram will be wrong as it no longer reflects the actual data.

Instead I would propose a system to specify ancillary information to be plotted along with the data. Jean-Luc suggested this could be done with a new options group. Calling `.hist` or `.stats` (doesn't exist yet) would then simply defer their computation to plot time. The data doesn't become wrapped in the useless AdjointLayout container object and the ancillary plots are always guaranteed to be up to date.

The beauty of this is that internally we could continue using the AdjointLayout while we figure out a way to get rid of it altogether. That means for the time being the plotting code wouldn't have to change, and things like adjoining grids of CFs (like we do in Topographica) would continue to be supported, while the user wouldn't have to deal with the problems listed above in most cases.

One objection is that the data wouldn't be easily accessible but the `.hist` method could have an option to return the Histogram directly and the user can always call the operation directly.

This is not an urgent proposal and maybe we'll decide this is not a good idea after all but since we were just discussing it I wanted to get a record of it.

**Comment by jlstevens** [comment]
Right, I guess the idea is you call ``hist`` to tell the plotting you want a side-histogram (if that is the case) or ask for an actual histogram (which you will no longer be able to adjoin with anything because that concept would go away).

Note that although in principle it might be better to keep the side-element 'live' (so it reflects the actual data) there is at least one problem: we won't be able to join CFs as shown in the 'OR map and weights over development' section of the [GCAL Collector Tutorial](http://ioam.github.io/topographica/Tutorials/GCAL_Collector.html) (for instance).

**Comment by jbednar** [comment]
How will you handle the presence of multiple histograms for the same plot?  E.g. a Points plot could easily need 3 histograms (x values, y values, and z values), and could even have more if there are additional value dimensions.  What would .hist mean in that case?  Seems like a histogram is associated with a dimension for the plot, not with the plot itself.  

Having the data remain live is indeed an important consideration, but I agree that it's not always possible for it to be live, which shouldn't be an error.

**Comment by philippjfr** [comment]
I agree, hence why I'd retain the AdjointLayout at least until we have more powerful Layouts, which could be used to replace AdjointLayouts in cases like adjoined CFs. If really needed AdjointLayout can still be used directly but for the most common case, i.e. ``.hist`` you'd no longer have to put up with the extra nesting and all annoyances that entails. Methods like ``.hist`` would simply be registering themselves to be executed just before plotting and store all their arguments including the dimensions. But just like .hist does now it could just assume default positions with an optional argument to override the position. That way you could still do this:

```python
Points(data).hist(dimension='y').hist(dimension='x')
```

to get a Layout of with the y histogram on the right and x histogram on the top but can also do this:

```python
Points(data).hist(dimension='x', position='top')
```

To get just the 'x' histogram at the top.

**Comment by jbednar** [comment]
So you'd define some default positional ordering, apparently counterclockwise, that would work for the first four histograms, and abort after that?  Can people decide that both should go to the right, and would that still work (one after the other)?

**Comment by philippjfr** [comment]
AdjoinLayouts are useful and this is no longer something we're planning to do. Closing.
