### ISSUE TITLE
Bokeh Elements html doc page giving 404

### ISSUE THREAD

**Issue by timothydmorton** [ioam/holoviews#1771]
Trying to access [this page](http://build.holoviews.org/user_guide/Bokeh_Elements.html) (linked to from the User Guide in several places) gives me a 404 not found error.

**Comment by jlstevens** [comment]
Thanks for reporting this. I will grep and replace those links as they are outdated.

**Comment by jlstevens** [comment]
I have grepped the user guide notebook and it looks like this has now been fixed (probably in #2509). Closing.
