### ISSUE TITLE
Change size of the Distribution Plot

### ISSUE THREAD

**Issue by gkirlik** [ioam/holoviews#1772]
Hi All,

Is there any way to change size of the distribution plot? I tried to change the size with the following command but it did not work. 

```python
%%opts Distribution [width=600 height=400] 
```

I also attached a simple Distribution plot example for the jupyter notebook. 

```python
import numpy as np
import holoviews as hv
hv.notebook_extension()
```

```python
%%opts Distribution (rug=True hist=False kde_kws=dict(shade=True))
d1 = np.random.randn(500)
hv.Distribution(d1, label='Blue')
```

Best,
Gokhan

**Comment by gkirlik** [comment]
I put this command top of the cell and it worked! 

```python
%output fig='png' dpi=100 size=150
```

**Comment by philippjfr** [comment]
Sorry for not getting back to you earlier, ``%%opts Distribution [fig_size=150]`` should work too.
