### ISSUE TITLE
hv.Text cause axes issue with Matplotlib

### ISSUE THREAD

**Issue by courcelm** [ioam/holoviews#1774]
holoviews==1.8.1

Here is the visual problem:

Before adding text to B:
![image](https://user-images.githubusercontent.com/1862936/28828384-9670565e-769e-11e7-8d18-55c74676eb87.png)

After adding text to B:
![image](https://user-images.githubusercontent.com/1862936/28828423-c02c39c2-769e-11e7-9c79-43a5ee2f6d55.png)

This issue only apply to matplotlib backend, bokeh is ok.

Here is the code to reproduce:

```
import matplotlib.pyplot as plt
%matplotlib inline
import holoviews as hv
hv.notebook_extension()
import numpy as np
hv.extension('matplotlib')


plots = list()

min_ = 2.5
max_ = 9

x_values = np.array([4, 8, 3])
y_values = np.array([4, 8, 8])

points = zip(x_values, y_values)

label = 'log10(Normalized Area)'


diag = hv.Curve([(min_, min_), (max_, max_)],
               kdims=['x1'],
               vdims=['y1'])


plot = hv.Points(points)
plot = plot[min_:max_, min_:max_] * diag * hv.Text(min_ + 0.5, max_ - 1, 'text', halign='left')

plots.append(plot)


ratio = abs(x_values/y_values)

plot = hv.Curve(zip(np.sort(ratio), np.array(range(len(ratio)))/float(len(ratio))),
               kdims=['x2'],
               vdims=['y2'])
plot = plot * hv.Text(0.6, 0.2, 'hey', halign='left')   # Line that cause the problem

plots.append(plot)



layout = hv.Layout(plots).cols(2)
layout
```

**Comment by courcelm** [comment]
Adding kdims  to Text fixed the problem.
plot = plot * hv.Text(0.6, 0.2, 'hey', halign='left',
               kdims=['x2', 'y2']) 

How kdims are merged when an overlay is created?

**Comment by jlstevens** [comment]
Glad you figured out the problem!

Essentially, overlays expect to place different elements in the same space, as defined by the dimensions and their ranges. The default kdims for ``Text`` are 'x' and 'y' which as incompatible with the 'x1,'x2','y1','y2' names you were using.

Perhaps this is a good example of why the suggestion in #1751 is a good idea.
