### ISSUE TITLE
Make default dimension name of a histogram be less generic

### ISSUE THREAD

**Issue by timothydmorton** [ioam/holoviews#1776]
Because a y-axis of a histogram gets the generic name "Frequency", two axes in the same layout end up linked by default, even if that doesn't make sense.  It might be better to have the frequency dimension named after the name of the dimension being histogrammed; e.g., "x Frequency" or "x Count".

**Comment by jlstevens** [comment]
I am in favor of this change as an 'x Frequency' dimension is not the same as a 'y Frequency' dimension.

**Comment by jbednar** [comment]
Sounds like a straightforward change; if you want to make a PR it would force us to do it soon! :-)

**Comment by philippjfr** [comment]
Here is where you'd have to define a value dimension (vdim): https://github.com/ioam/holoviews/blob/master/holoviews/operation/element.py#L555

**Comment by timothydmorton** [comment]
So I can change the name of the vdim and it works as hoped for (axes are not linked), but testing it out, I notice that the axes seem to be linked based on the *label* of the dimension, not its short name.  That is, if I say `vdims=[(selected_dim + '_frequency', 'Frequency')]`, then an x-histogram and y-histogram in the same layout still get linked, presumably because they have the same label, despite having different names.  Is this intentional?  It would seem to me that axes should be linked if the dimensions match in name, rather than label.

I'm asking because I'd actually like the axis labels to just say "Frequency," because that's nice and clean, and when I see "x Frequency" and "y Frequency" it just looks awkward. 

Should I create a different issue for automatic linking based on dimension name rather than label?

**Comment by jlstevens** [comment]
> It would seem to me that axes should be linked if the dimensions match in name, rather than label.

The identity of a dimension is defined by the name *and* label. This is a deliberate choice as one dimension should not have two longer descriptions of what it is!

Although a dimension name is expected to have a unique label, what you should be able to do here is ``hv.Dimension('x_frequency', label='Frequency')`` and ``hv.Dimension('y_frequency', label='Frequency')``. Then these are considered two distinct dimensions which happen to have the same label...even though they are frequencies of two different types of thing.

If that doesn't work then I would consider it a bug - linking dimensions should not be done on the label alone.

**Comment by timothydmorton** [comment]
Yes, this is what is happening for me-- the two axes are linked when the labels are the same, but the names are not.  Any suggestions where I should look for this, so I can include a fix to this on the PR if possible?

**Comment by jlstevens** [comment]
@philippjfr Any suggestions?

**Comment by philippjfr** [comment]
Both the normalization system and bokeh axis linking code long precede the introduction of separate name and label attributes and therefore likely work based on the final axis label. This won't be a straightforward change as it involves changing a fair amount of the plotting code, but I agree it should be done at some point.

**Comment by jlstevens** [comment]
We agree in principle then. Shame it will be a bigger job than I hoped and I think this should be the semantics for version 2.0. I'll assign that milestone to issue #1783.

**Comment by philippjfr** [comment]
Just merged https://github.com/ioam/holoviews/pull/1836 so this has now been addressed.
