### ISSUE TITLE
Bounds example doesn't work with BoundsXY

### ISSUE THREAD

**Issue by timothydmorton** [ioam/holoviews#1789]
Trying to use the [bounds example](http://holoviews.org/reference/streams/bokeh/Bounds.html) for reference and holoviews is telling me I should use `BoundsXY` because `Bounds` is deprecated. But when I do that replacement in the demo code, it doesn't work.  No error as far as I can tell, but it doesn't work.

**Comment by philippjfr** [comment]
Looks like the ``BoundsXY`` callback was never registered:

https://github.com/ioam/holoviews/blob/master/holoviews/plotting/bokeh/callbacks.py#L767

A straightforward workaround until we fix this is to register the callback yourself:

```python
from holoviews.plotting.bokeh.callbacks import BoundsCallback
callbacks[hv.streams.BoundsXY]      = BoundsCallback
```

**Comment by timothydmorton** [comment]
ok, so that worked on an example, but it doesn't seem to work on a datashaded image.  That is, I get the persistent black box when I use `Bounds` but not `BoundsXY`.  Is there something additional that needs to be registered for an `RGB` or something?

**Comment by timothydmorton** [comment]
oh wait, maybe this is not related to this; I'm getting IOPub data rate errors from my notebook, so maybe that's why it's not working properly.

**Comment by timothydmorton** [comment]
OK, my code is working with `BoundsXY` now.

**Comment by philippjfr** [comment]
Added the stream in the PR above. Closing.
