### ISSUE TITLE
Plotting empty figure after loading matplotlib

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#179]
My colleague found a bug:

Execute cells in this order
```
import holoviews as hv
import numpy as np
from matplotlib import pyplot
%load_ext holoviews.ipython
```

```
%matplotlib inline
pyplot.plot([1,2,3])
```

```
%opts Image [colorbar=True]
im = hv.Image(np.random.rand(10,10))
im * hv.operation.contours(im, levels=[0, 0.8])
```

This will produce:
![screen shot 2015-06-24 at 15 10 16](https://cloud.githubusercontent.com/assets/6897215/8330660/298a8bfa-1a83-11e5-97d9-87385345706c.png)

**Comment by philippjfr** [comment]
Fixed in a0de291bf4be29ae6568b8c8ff992e7445d2bc49. Turns out closing the same figure multiple times will reopen it again somehow. Closing.
