### ISSUE TITLE
Automate sdist archive fix for PyPI

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#1791]
Unfortunately, I need to fiddle with the archive output by ``python setup.py sdist`` to make the example directories work correctly when installing with pip from PyPI. In particular, I need to move the ``examples/`` directory up one level before uploading to PyPI with twine.

It would be good if this could be automated after  ``setup(**setup_args)`` by checking for an archive with the appropriate version if the 'sdist' command was used.

**Comment by jlstevens** [comment]
To be honest I wouldn't have closed this issue until I was sure it was really working when pip installing from PyPI!

Hope I don't have to reopen this issue....

**Comment by philippjfr** [comment]
Merging the PR auto-closed it. I hope so too.

**Comment by jlstevens** [comment]
It worked!
