### ISSUE TITLE
HTML format

### ISSUE THREAD

**Issue by Jerryzhuht** [ioam/holoviews#1797]
Hi. Under the new release, there's still a minor problem of the HTML formatting. When rendering from Jupyter to HTML, there's an extra ending tag `</div>` in the tag of container which contains `hv.extension('Bokeh')`. The outcome would be the rest of content cannot be inside the container.
 Just a minor one.
![capture](https://user-images.githubusercontent.com/30041733/29066549-174dac0e-7c62-11e7-9384-f1007956a468.PNG)

**Comment by jlstevens** [comment]
Are you using version 1.8.2 which was released Friday last week?

Here is what I am currently seeing:

![image](https://user-images.githubusercontent.com/890576/29074448-3a232d50-7c47-11e7-8994-25a52acc8187.png)

I recently removed the divs to fix HTML export (see #1769) so I think if you upgrade using:

```
conda install -c conda-forge holoviews
```

it should work properly. Note, you can also pip install if you wish.

**Comment by Jerryzhuht** [comment]
@jlstevens Thanks for your reply.
I already updated to the latest 1.8.2. It looks nice in Jupyter notebook, but when using File -- Download as --HTML(.html), the problems shows up in the html file(text outside container).
I believe using nbconvert gives the same outcome.

**Comment by jlstevens** [comment]
Nightmare! I thought I had fixed this. :-(

**Comment by jlstevens** [comment]
Ah, I just verified this is only an issue when ``logo=False`` so it isn't as bad as I first thought! Thanks for reporting this and it shouldn't be too hard to fix in the end...

**Comment by Jerryzhuht** [comment]
Exactly! Thanks.

**Comment by philippjfr** [comment]
This was fixed and has now made it into the latest release. Closing.
