### ISSUE TITLE
Publishing DynamicMaps 

### ISSUE THREAD

**Issue by gkirlik** [ioam/holoviews#1802]
On DynamicMaps documentation page (http://dev.holoviews.org/Tutorials/Dynamic_Map.html), following statement is noted. 
> DynamicMaps require a live notebook server and cannot be fully exported to static HTML.

Still, is there any way to publish DynamicMaps and share the interactive figures?

**Comment by jlstevens** [comment]
For static export, the only option is to cast to HoloMap which you can do from DynamicMap. See the 'Converting from DynamicMap to HoloMap' section in the [Live Data](http://holoviews.org/user_guide/Live_Data.html) user guide.

**Comment by philippjfr** [comment]
The other option is [deploying a bokeh server](http://holoviews.org/user_guide/Deploying_Bokeh_Apps.html). You can also see some examples in the [gallery](http://holoviews.org/gallery/index.html) and [reference gallery](http://holoviews.org/reference/index.html).
