### ISSUE TITLE
plotting/bokeh/util.py depends on matplotlib even for bokeh backend

### ISSUE THREAD

**Issue by cnblevins** [ioam/holoviews#1807]
This is interesting because I can get hv.Table to work, but hv.Bars is throwing the following exception:
> Traceback (most recent call last):
> File "/app/.heroku/python/lib/python3.6/site-packages/holoviews/plotting/bokeh/util.py", line 120, in mpl_to_bokeh
> v = colors.ColorConverter.colors.get(v, v)
>AttributeError: 'NoneType' object has no attribute 'ColorConverter'
and
> File "/app/.heroku/python/lib/python3.6/site-packages/holoviews/core/options.py", line 165, in __exit__
> raise AbbreviatedException(etype, value, traceback)
> holoviews.core.options.AbbreviatedException: AbbreviatedException: AttributeError: 'NoneType' object has no attribute 'ColorConverter'

The exception traces back to the following line in my code:
`graph = hv.renderer('bokeh').server_doc(df3)`

Details:

from requirements.txt:
> bokeh==0.12.6
> holoviews==1.8.2

from app.py:
```
import holoviews as hv
hv.extension('bokeh')
```
and
```
def graph_alpha(dataframe):
    # function to create a graph for the alpha cash flow dataframe
    df1=dataframe 
    df1['date'] = df1.date.astype('datetime64[ns]')

    k_dims = [('date','Date')]
    val_dims = [('netincome', 'EBITDA')]

    plot_opts = dict(fill_color='#00AA00')

    df2 = hv.Table(df1,kdims=k_dims, vdims=val_dims)
    df3 = hv.Bars(df1,kdims=k_dims, vdims=val_dims)
    #df3 = hv.Bars(df1,kdims=k_dims, vdims=val_dims).opts(plot=plot_opts)
    #df3 = hv.Bars(df2).opts(plot=plot_opts)
    #df3 = hv.Bars(df2).opts(style=plot_opts)
    graph = hv.renderer('bokeh').server_doc(df3)

    return graph 
```

Any thoughts on this?

I looked through all the open and closed issues, and didn't see this one. 
Hope we can figure it out.

Chad

**Comment by jbednar** [comment]
Looks like there is a dependency on matplotlib being installed.  Table might not need the colors module from matplotlib, but bars apparently does.  Try conda installing matplotlib?  We've eliminated most dependencies on matplotlib from the bokeh code, but I think there are still a few, deliberate or not.

**Comment by cnblevins** [comment]
That was it.
Installed matplotlib 2.0.2 and hv.Bars now works.

Thanks.

**Comment by jbednar** [comment]
Good. I'll leave this open, because it looks like we need to do some more tidying to avoid that requirement.

**Comment by philippjfr** [comment]
This has now been fixed.
