### ISSUE TITLE
BokehRenderer.get_plot should use curdoc in server mode

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#1808]
Currently you manually have to pass a bokeh ``Document`` to ``BokehRenderer.get_plot`` to ensure that streams can communicate correctly. It's possible we could just always attach the ``curdoc`` to the holoviews plot if the renderer is in server mode avoiding surprising errors with linked streams. That said I'll have to investigate if there's ever a reason to pass a manually created ``Document`` in, in which case we'd at least have to leave the ``doc`` argument.

**Comment by jlstevens** [comment]
I am in favor of anything that simplifies our story when it comes to bokeh apps - the simplest approach should support streams and you shouldn't have to do something different for streams to work. On that basis I approve of this suggestion and I have no problem leaving a ``doc`` argument and an optional thing for truly advanced usage - if there can be valid reasons to use a custom document!

**Comment by philippjfr** [comment]
This was done in https://github.com/ioam/holoviews/pull/1810, closing.
