### ISSUE TITLE
Plotly backend crashes Chrome tabs

### ISSUE THREAD

**Issue by gbrener** [ioam/holoviews#1812]
When using the plotly backend, executing a cell with the `hv.Trisurface` class causes Chrome browser tabs to crash. This is with the latest version of Chrome, Python 3.5, latest version of Jupyter, and the `pip`-installed master branch of Holoviews. Happy to provide more info if necessary.

**Comment by philippjfr** [comment]
Never been able to reproduce this, if this issue occurs again it should probably be raised with plotly directly because we're not doing anything special when displaying their plots.
