### ISSUE TITLE
Hover tool only displays informations of the first group of curves 

### ISSUE THREAD

**Issue by slamer59** [ioam/holoviews#1815]
Hello,
When a list of curve is given to hv.Overlay(), hover tool displays only information of the first group of curves. 
Version run is **1.8.2** with python 3.6 (conda)

In jupyter,

```
import pandas as pd
import numpy as np
import holoviews as hv
hv.extension('bokeh')

aDict={'Iso': 'T', 'IsoVal':0.5,'Pressure': np.linspace(1., 20.0, 6),'Enthalpy': np.linspace(1., 4., 6)}
bDict={'Iso': 'T', 'IsoVal':0.5,'Pressure': np.linspace(1., 10.0, 6),'Enthalpy': np.linspace(1., 4., 6)}
cDict={'Iso': 'X', 'IsoVal':0.0,'Pressure': np.linspace(14., 18.0, 6),'Enthalpy': np.linspace(1., 4., 6)}
dDict={'Iso': 'X', 'IsoVal':0.5,'Pressure': np.linspace(22., 25.0, 6),'Enthalpy': np.linspace(1., 4., 6)}

df1 = pd.DataFrame.from_dict(aDict)
df2 = pd.DataFrame.from_dict(bDict)
df3 = pd.DataFrame.from_dict(cDict)
df4 = pd.DataFrame.from_dict(dDict)

dfTest = pd.concat([df1,df2,df3,df4], ignore_index=True)
```

```
%%opts Curve [tools=['hover']]
# Define some custom options for bokeh

ds = hv.Table(dfTest)
isos = [('X', 'black'), ('T', 'red')]
hv.Overlay([ds.select(Iso=iso).to(hv.Curve, 'Enthalpy', 'Pressure').overlay().opts(style={'Curve': dict(color=color)}) for iso, color in isos])
```

Regards,
Thomas

**Comment by philippjfr** [comment]
Could you try using these options in your more complex example. It seems to work for the toy example, ensuring that all the groups are batched:

```python
%%opts Curve [tools=['hover']] Overlay [legend_limit=0]
...
```

**Comment by philippjfr** [comment]
The PR above should have fixed this. If you have time it would be great if you could try it out. It'll be in the 1.8.3 release that will be uploaded shortly.

**Comment by slamer59** [comment]
Hello,
I tested it on this example.
Without `legend_limit=0`, red curves doesn't show.
![image](https://user-images.githubusercontent.com/25283272/29554009-e3898156-871d-11e7-81d7-08b17abb7583.png)

with `Overlay [legend_limit=0]`
![image](https://user-images.githubusercontent.com/25283272/29554220-96fdc300-871e-11e7-9754-c72523308597.png)

Black and red curves shows informations but not all. kdims informations are not shown anymore.
The legend box does not appear anymore. Is it the normal behavior ?

**Comment by philippjfr** [comment]
>I tested it on this example.

Could you just confirm which version you tested with? The behavior you described for ``legend_limit=0`` is correct, however without it you should see things working if you're using 1.8.3 now.

**Comment by slamer59** [comment]
I used 1.8.2 for this test.

I will update to 1.8.3 and test.

**Comment by jlstevens** [comment]
Glad this is now resolved! Closing.
