### ISSUE TITLE
Additional install options for HoloViews

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#182]
I think we should add at least one new install option. Currently we support:

* ``pip install holoviews``: Minimal, just numpy and param required.
* ``pip install holoviews[extras]``: Everything (jinja2, matplotlib, mpld3, pandas, seaborn, cyordereddict,  nose).

Given that most people will be using notebook, I think there is a case to make for an installation option that supports notebook users (and reproducible science!) without installing everything. 

In particular, pandas, seaborn and mpld3 are relatively large dependencies and definitely optional even for notebook users. In addition, mpld3 currently requires the development version which makes things tricky..

Anyway, here is my proposed change to ``setup.py`` that is currently outstanding:

```python
install_requires = ['param>=1.3.2', 'numpy>=1.0']
extras_require = {'recommended': ['matplotlib', 'ipython', 'jinja2', 'lancet-ioam'],
                  'extras':['pandas', 'seaborn', 'mpld3']}
extras_require['all'] = (extras_require['recommended']
                         + extras_require['extras']
                         + ['cyordereddict', 'nose'])
```

Thoughts?

**Comment by jbednar** [comment]
Seems fine, but it might be clearer as:

``python
install_requires = ['param>=1.3.2', 'numpy>=1.0']                                                                                                      
extras_require={}                                                                                                                                      
extras_require['recommended'] = ['matplotlib', 'ipython', 'jinja2', 'lancet-ioam']                                                                     
extras_require['extras'] = ['pandas', 'seaborn', 'mpld3']                                                                                              
extras_require['all'] = (extras_require['recommended'] + extras_require['extras']                                                                      
                         + ['cyordereddict', 'nose'])                                                                                                  
``

Does this actually ensure that IPython Notebook is installed?  I don't see that specified.

**Comment by jlstevens** [comment]
> Does this actually ensure that IPython Notebook is installed? I don't see that specified.

No, unfortunately! Last time I checked, trying to specify ``'ipython[notebook]'`` doesn't work in the ``extra_require`` dictionary. If it did work, I would rename 'recommended' to 'notebook' so you could do ``pip install holoviews[notebook]``.

I also agree your version of this code is clearer. Is there anything else we want to change?

**Comment by jbednar** [comment]
Based on our discussion, we agreed to add another extras option, something like 'ipython-dependencies' (or shorter if you can think of one), and then 'recommended' included that as well.  It's annoying, since those are really ipython's dependencies, not ours, but it's the only way we can see to do it for now, and eventually we can remove this once Jupyter is distributed separately from ipython (at which point we should be able to depend on both ipython and Jupyter and be done).

**Comment by jlstevens** [comment]
I would call it ``'notebook-dependencies' ``. Anyway, I gave up trying to read their impenetrable ``setup.py`` and just installed dependencies till it worked:

```bash
pip install pyzmq jinja2 tornado jsonschema ipython
```

This won't let you export notebooks though (fairly essential). In addition, I needed:

```bash
pip install pygments
```

As a result, I think this is what we want in ``setup.py``:

```python
install_requires = ['param>=1.3.2', 'numpy>=1.0']
extras_require={}            

# Notebook dependencies of IPython 3
extras_require['notebook-dependencies'] = ['pyzmq', 'jinja2', 'tornado',
                                           'jsonschema',  'ipython', 'pygments']

extras_require['recommended'] = (['matplotlib', 'ipython', 'jinja2', 'lancet-ioam']
                                 + extras_require['notebook-dependencies')

extras_require['extras'] = ['pandas', 'seaborn', 'mpld3']                                                                                              
extras_require['all'] = (extras_require['recommended'] 
                       + extras_require['extras']                                                                      
                       + ['cyordereddict', 'nose'])
```

Thoughts?

**Comment by jlstevens** [comment]
According to [this page](https://ipython.org/ipython-doc/dev/install/install.html) sphinx is also needed for nbconvert. I don't seem to have needed this but maybe it is actually required? I guess it might be needed to export to formats other than HTML...

**Comment by jlstevens** [comment]
I've pushed my changes in 109b7ed and tested that the recommended option works in a clean virtualenv:

```bash
pip install -e .[recommended]
```

As soon as the homepage is updated (important!) I think this issue can be closed.

**Comment by jlstevens** [comment]
If anyone one else wants to test the new installation options, that would also be helpful...

**Comment by jbednar** [comment]
Looks good.  Are you sure that you don't want extras to also include recommended?  I'm not sure myself.  Including sphinx seems fine.

**Comment by jlstevens** [comment]
Well spotted! I'll fix that now...

In addition, you may like to improve the re-written installation instructions section 602e443 ([full page](https://github.com/ioam/holoviews/blob/602e443cd650909989d5bc55304fb4386a78680e/doc/index.rst))

**Comment by jlstevens** [comment]
I think I can close this issue now

**Comment by jbednar** [comment]
Ok, I tweaked the installation instructions slightly.  But now that we support conda install, I'm not sure how to describe that here.  Presumably we won't want to mention all these different options again, in conda form?  Should the conda packages just install everything always?  Maybe we could switch to a much more succinct description of the differen install options, if we need to describe them both for conda and for pip.

**Comment by jlstevens** [comment]
Right now I don't know if conda supports the bracket syntax (e.g 'ipython[notebook]') but I don't think so - I had to specify that dependency as 'ipython-notebook'. This means that (for now!) there is only a single conda installation procedure (``conda install -c ioam holoviews``) that is equivalent to the 'recommended' option with pip.

Maybe something you could find out for us is how to get the package installable directly with ``conda install holoviews`` because I wasn't able to figure this out...
