### ISSUE TITLE
Renderer - docs error or bug?

### ISSUE THREAD

**Issue by byezy** [ioam/holoviews#1822]
Running the example code found in:
http://holoviews.org/reference/elements/matplotlib/Histogram.html

Receiving this exception:

    2017-08-24 10:01:27,016 Error running application handler <bokeh.application.handlers.script.ScriptHandler object at 0x2b6fba49a940>: module 'holoviews' has no attribute 'renderers'
    File "hvapp.py", line 5, in <module>:
    renderer = hv.renderers('matplotlib') Traceback (most recent call last):
      File "/home/byed/venv36/lib/python3.6/site-packages/bokeh/application/handlers/code_runner.py", line 81, in run
        exec(self._code, module.__dict__)
      File "/home/byed/job/fire/hvapp.py", line 5, in <module>
    renderer = hv.renderers('matplotlib')
    AttributeError: module 'holoviews' has no attribute 'renderers'

API change?

**Comment by byezy** [comment]
Also,

(venv36) byed@irsdev01:~> pip install 'holoviews[all]'
    Requirement already satisfied: holoviews[all] in ./venv36/lib/python3.6/site-packages
    Requirement already satisfied: param<2.0,>=1.5.1 in ./venv36/lib/python3.6/site-packages (from holoviews[all])
    Requirement already satisfied: numpy>=1.0 in ./venv36/lib/python3.6/site-packages (from holoviews[all])
    Requirement already satisfied: ipython in ./venv36/lib/python3.6/site-packages (from holoviews[all])
    Requirement already satisfied: pyzmq in ./venv36/lib/python3.6/site-packages (from holoviews[all])
    Requirement already satisfied: jinja2 in ./venv36/lib/python3.6/site-packages (from holoviews[all])
    Requirement already satisfied: tornado in ./venv36/lib/python3.6/site-packages (from holoviews[all])
    Requirement already satisfied: jsonschema in ./venv36/lib/python3.6/site-packages (from holoviews[all])
    Requirement already satisfied: notebook in ./venv36/lib/python3.6/site-packages (from holoviews[all])
    Requirement already satisfied: pygments in ./venv36/lib/python3.6/site-packages (from holoviews[all])
    Requirement already satisfied: matplotlib in ./venv36/lib/python3.6/site-packages (from holoviews[all])
    Requirement already satisfied: lancet-ioam in ./venv36/lib/python3.6/site-packages (from holoviews[all])
    Requirement already satisfied: pandas in ./venv36/lib/python3.6/site-packages (from holoviews[all])
    Requirement already satisfied: seaborn in ./venv36/lib/python3.6/site-packages (from holoviews[all])
    Requirement already satisfied: bokeh>=0.12.6 in ./venv36/lib/python3.6/site-packages (from holoviews[all])
    Requirement already satisfied: cyordereddict in ./venv36/lib/python3.6/site-packages (from holoviews[all])
    Requirement already satisfied: nose in ./venv36/lib/python3.6/site-packages (from holoviews[all])
    Requirement already satisfied: decorator in ./venv36/lib/python3.6/site-packages (from ipython->holoviews[all])
    Requirement already satisfied: simplegeneric>0.8 in ./venv36/lib/python3.6/site-packages (from ipython->holoviews[all])
    Requirement already satisfied: pexpect; sys_platform != "win32" in ./venv36/lib/python3.6/site-packages (from ipython->holoviews[all])
    Requirement already satisfied: prompt-toolkit<2.0.0,>=1.0.4 in ./venv36/lib/python3.6/site-packages (from ipython->holoviews[all])
    Requirement already satisfied: setuptools>=18.5 in ./python3/lib/python3.6/site-packages (from ipython->holoviews[all])
    Requirement already satisfied: jedi>=0.10 in ./venv36/lib/python3.6/site-packages (from ipython->holoviews[all])
    Requirement already satisfied: pickleshare in ./venv36/lib/python3.6/site-packages (from ipython->holoviews[all])
    Requirement already satisfied: traitlets>=4.2 in ./venv36/lib/python3.6/site-packages (from ipython->holoviews[all])
    Requirement already satisfied: MarkupSafe>=0.23 in ./venv36/lib/python3.6/site-packages (from jinja2->holoviews[all])
    Requirement already satisfied: jupyter-client in ./venv36/lib/python3.6/site-packages (from notebook->holoviews[all])
    Requirement already satisfied: ipykernel in ./venv36/lib/python3.6/site-packages (from notebook->holoviews[all])
    Requirement already satisfied: nbconvert in ./venv36/lib/python3.6/site-packages (from notebook->holoviews[all])
    Requirement already satisfied: terminado>=0.3.3; sys_platform != "win32" in ./venv36/lib/python3.6/site-packages (from notebook->holoviews[all])
    Requirement already satisfied: ipython-genutils in ./venv36/lib/python3.6/site-packages (from notebook->holoviews[all])
    Requirement already satisfied: nbformat in ./venv36/lib/python3.6/site-packages (from notebook->holoviews[all])
    Requirement already satisfied: jupyter-core in ./venv36/lib/python3.6/site-packages (from notebook->holoviews[all])
    Requirement already satisfied: six>=1.10 in ./venv36/lib/python3.6/site-packages (from matplotlib->holoviews[all])
    Requirement already satisfied: cycler>=0.10 in ./venv36/lib/python3.6/site-packages (from matplotlib->holoviews[all])
    Requirement already satisfied: pytz in ./venv36/lib/python3.6/site-packages (from matplotlib->holoviews[all])
    Requirement already satisfied: python-dateutil in ./venv36/lib/python3.6/site-packages (from matplotlib->holoviews[all])
    Requirement already satisfied: pyparsing!=2.0.0,!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 in ./venv36/lib/python3.6/site-packages (from matplotlib->holoviews[all])
    Requirement already satisfied: requests>=1.2.3 in ./venv36/lib/python3.6/site-packages (from bokeh>=0.12.6->holoviews[all])
    Requirement already satisfied: PyYAML>=3.10 in ./venv36/lib/python3.6/site-packages (from bokeh>=0.12.6->holoviews[all])
    Requirement already satisfied: bkcharts>=0.2 in ./venv36/lib/python3.6/site-packages (from bokeh>=0.12.6->holoviews[all])
    Requirement already satisfied: ptyprocess>=0.5 in ./venv36/lib/python3.6/site-packages (from pexpect; sys_platform != "win32"->ipython->holoviews[all])
    Requirement already satisfied: wcwidth in ./venv36/lib/python3.6/site-packages (from prompt-toolkit<2.0.0,>=1.0.4->ipython->holoviews[all])
    Requirement already satisfied: testpath in ./venv36/lib/python3.6/site-packages (from nbconvert->notebook->holoviews[all])
    Requirement already satisfied: pandocfilters>=1.4.1 in ./venv36/lib/python3.6/site-packages (from nbconvert->notebook->holoviews[all])
    Requirement already satisfied: bleach in ./venv36/lib/python3.6/site-packages (from nbconvert->notebook->holoviews[all])
    Requirement already satisfied: entrypoints>=0.2.2 in ./venv36/lib/python3.6/site-packages (from nbconvert->notebook->holoviews[all])
    Requirement already satisfied: mistune!=0.6 in ./venv36/lib/python3.6/site-packages (from nbconvert->notebook->holoviews[all])
    Requirement already satisfied: urllib3<1.23,>=1.21.1 in ./venv36/lib/python3.6/site-packages (from requests>=1.2.3->bokeh>=0.12.6->holoviews[all])
    Requirement already satisfied: certifi>=2017.4.17 in ./venv36/lib/python3.6/site-packages (from requests>=1.2.3->bokeh>=0.12.6->holoviews[all])
    Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./venv36/lib/python3.6/site-packages (from requests>=1.2.3->bokeh>=0.12.6->holoviews[all])
    Requirement already satisfied: idna<2.7,>=2.5 in ./venv36/lib/python3.6/site-packages (from requests>=1.2.3->bokeh>=0.12.6->holoviews[all])
    Requirement already satisfied: html5lib>=0.99999999 in ./venv36/lib/python3.6/site-packages (from bleach->nbconvert->notebook->holoviews[all])
    Requirement already satisfied: webencodings in ./venv36/lib/python3.6/site-packages (from html5lib>=0.99999999->bleach->nbconvert->notebook->holoviews[all])
    (venv36) byed@irsdev01:~>

**Comment by jlstevens** [comment]
> AttributeError: module 'holoviews' has no attribute 'renderers'

Thanks for pointing this out! It should be ``renderer`` (singular). That said, I don't see any mention of it on the page you linked to. Are you sure it is the page you meant?

**Comment by byezy** [comment]
You are right, sorry mate I buggered that up. Been going around in circles on Bokeh n hv for a couple days now.... anyway I probably hacked a bit and forgot, perhaps from this code:

    import numpy as np
    import holoviews as hv
    import holoviews.plotting.bokeh

    renderer = hv.renderers('bokeh')

    points = hv.Points(np.random.randn(1000,2 ))(plot=dict(tools=['box_select', 'lasso_select']))
    selection = hv.streams.Selection1D(source=points)

    def selected_info(index):
        arr = points.array()[index]
        if index:
            label = 'Mean x, y: %.3f, %.3f' % tuple(arr.mean(axis=0))
        else:
            label = 'No selection'
        return points.clone(arr, label=label)(style=dict(color='red'))

    layout = points + hv.DynamicMap(selected_info, streams=[selection])

    doc = renderer.server_doc(layout)
    doc.title = 'HoloViews App'

Which was from this page:
http://holoviews.org/user_guide/Deploying_Bokeh_Apps.html
in the section Deploying Apps using *bokeh serve*

**Comment by philippjfr** [comment]
This has been fixed, so I'll close.
