### ISSUE TITLE
Select function for points not working for non-numeric

### ISSUE THREAD

**Issue by dwervin** [ioam/holoviews#1823]
In the SciPy2017 presentation using parameters and widgets, there was a select statement to get points based on passenger_count:

_selected = points.select(passenger_count=self.passengers)_

Is this function limited to only accept numeric arguments.  I tried the select statement that I was expecting would pick points based upon an event type in my dataset, but it did not select the data.  All data was selected.  It wasn't limited to just "Sag" data.

_plot        = param.ObjectSelector(default="Sag", objects=["Sag","Swell"])_
_selected = points.select(points.EventType=self.plot )_

Also, does this select function allow multiple conditions?  For example, if I wanted to select "Sag" data with an event count range, would the select function handle that?

**Comment by philippjfr** [comment]
Not sure if this  a typo but could you try simply:

```python
selected = points.select(EventType=self.plot )
```

where ``EventType`` should match a column in your data.

>For example, if I wanted to select "Sag" data with an event count range, would the select function handle that?

Yes you can select ranges by supplying a tuple, e.g. this selects values between 0 and 10:

```python
points.select(EventType=self.plot, Sag=(0, 10))
```

**Comment by dwervin** [comment]
It doesn't seem to select based upon the EventType.  It includes every point no matter the EventType that is specified in the select.  

The EventType field is a string that can be "Sag" or "Swell".

**Comment by philippjfr** [comment]
Can you paste the exact line of code you were trying and the output of ``print(points)`` because the code you posted above contains a syntax error so can't be what you actually tried.

**Comment by dwervin** [comment]
Below is what I had, but your question made me realize I only had EVENT_COUNT defined under vdims. I added the EventType to vdims and it works great.

Thanks for pointing me in the right direction.

class SagSwellExplorer(hv.streams.Stream):
    
    alpha       = param.Magnitude(default=0.75, doc="Alpha value for the map opacity")
    plot        = param.ObjectSelector(default="Sag", objects=["Sag","Swell"])
    colormap    = param.ObjectSelector(default=cm["fire"], objects=cm.values())
    numEvents  = param.Range(default=(1, 300), bounds=(1, 300), doc="""Filter for event count""")
    
    def make_view(self, x_range=None, y_range=None, **kwargs):
        map_tiles = tiles.opts(style=dict(alpha=self.alpha), plot=options) 

        points = hv.Points(df, kdims=['X_CORD', 'Y_CORD'], vdims=['EVENT_COUNT'])
        selected = points.select(EventType=self.plot,EVENT_COUNT=self.numEvents )
        SagSwellPts = datashade(selected, x_sampling=1, y_sampling=1, cmap=self.colormap,
                               dynamic=False, x_range=x_range, y_range=y_range,
                               width=800, height=475)
        return map_tiles * SagSwellPts

**Comment by jlstevens** [comment]
Glad you figured it out!

I'll close this issue now but that doesn't mean we can't continue discussion here if necessary.
