### ISSUE TITLE
HLine and VLine when one axis is categorical

### ISSUE THREAD

**Issue by ea42gh** [ioam/holoviews#1828]
I would find the following feature useful:
the ability to draw a line across a figure
when an axis is categorical 
```
%%opts Curve [invert_axes=False]
hv.Curve( zip(['a','b','c'],[1,3,2]) ) * hv.HLine(2)
```

**Comment by ea42gh** [comment]
Expanding on the above, I have wanted to draw lines across plots before (a generalization of HLine, VLine, allowing an arbitrary slope: e.g., line through (0,0) with slope 85 degrees from window boundary to window boundary.

**Comment by ea42gh** [comment]
Found a way to sort of do what I wanted:
`%%opts Curve [show_grid=True]`   Hmmm, wonder if I can force a grid with just one line in some position?

**Comment by philippjfr** [comment]
@ea42gh The gridlines are linked to the ticks, so you set one tick but that's not a good solution. I'm about to push a fix for your example. Drawing a line with arbitrary slope is a feature request in bokeh, but it would be great if you could file a separate one in HoloViews.
