### ISSUE TITLE
Is there a documented list of %%opts and %%output keywords and their use?

### ISSUE THREAD

**Issue by gcbgit** [ioam/holoviews#1830]
I'm not able to find a list of available keywords for the plot and style options of %%opts or for %%output.  I can find the keywords when I hit tab in a cell, but I'm not able to find documentation on what they mean or how they're used.

For example, it's not clear how I would rotate a plot 90° (such as making the histogram bars horizontal), or set the x and y axis ranges.

Is there a page somewhere that better documents how to use %%opts and %%options?

**Comment by jlstevens** [comment]
The style options are defined by the underlying plotting library (i.e either matplotlib or bokeh) but the plot options are documented. Have a look at the ``hv.help`` utility which can list the plot options (with docstrings) and the available style options for a given element.

**Comment by gcbgit** [comment]
Thanks!  Got what I need.  I hadn't realized that hv.help was different and so much richer than the standard help mechanisms.
