### ISSUE TITLE
Provide a colormap to `Raster`?

### ISSUE THREAD

**Issue by wmayner** [ioam/holoviews#1831]
Hi,

Is there a way to change the default colormap of a `Raster`? It seems that it doesn't accept a `cmap` argument. Sorry if this is obvious from the documentation, but I had a look and couldn't find anything on it.

**Comment by wmayner** [comment]
Ugh. Just found that this can be done by passing `cmap` through to Bokeh.

One thing I've found confusing in reading the Holoviews docs is which params are available to pass through in this way—not sure if it's worth the duplication between Bokeh and Holoviews, but adding something extra about this (maybe just a link) to the various `Element` docs would be helpful.

**Comment by jlstevens** [comment]
Try using ``hv.help(hv.Raster)`` and look at the docstring for ``hv.help`` - it should give you a better idea of the available options, both for the elements themselves and the possible style options.

**Comment by wmayner** [comment]
Awesome! Thanks, didn't know about `hv.help`. May I suggest that `hv.help` be mentioned in the API for each `Element` (*e.g.* [here](http://holoviews.org/reference/containers/bokeh/HoloMap.html#bokeh-gallery-holomap))?

**Comment by jlstevens** [comment]
I think that is a good idea as a number of recent issues would have been resolved if people knew about ``hv.help`` earlier. What do you think @philippjfr ?

**Comment by philippjfr** [comment]
I think adding ``hv.help`` where ever possible is a good idea. I think we should indeed add it to all reference notebooks.

**Comment by jbednar** [comment]
Mentioning hv.help is one thing, but should we actually show the output of ``hv.help`` for that object in each reference gallery notebook?

**Comment by jlstevens** [comment]
> Mentioning hv.help is one thing, but should we actually show the output of hv.help for that object in each reference gallery notebook?

Only if we find a way to exclude such output from notebook tests (once they are set up). Updating notebook tests every time a parameter is changed/added/removed - or even if a typo is fixed in a parameter docstring is a nightmare we already had with the old options notebook.

**Comment by philippjfr** [comment]
Wouldn't be opposed to adding the hv.help output separately to the end of each reference notebook. Need not even be inside the reference notebooks themselves.

**Comment by jlstevens** [comment]
That seems reasonable but would probably need another sphinx directive unless an existing one for running python code can be used.

**Comment by philippjfr** [comment]
@jlstevens You recently added a blurb about ``hv.help`` to all the element notebooks right? If I'm not misremembering please close this issue.

**Comment by jlstevens** [comment]
That's right, all the elements now mention ``hv.help``. Closing this issue now.
