### ISSUE TITLE
Two VLines applied to a Distribution in matplotlib result in reduction of the x axis range

### ISSUE THREAD

**Issue by ea42gh** [ioam/holoviews#1833]
```
%%output backend='matplotlib'
hv.Distribution( np.random.uniform(size=1000) ) * hv.VLine(0.25) * hv.VLine(0.75)
```

reduces the x axis of the histogram to the range (0.25, 0.75)
Removing one of the VLines keeps the axis at full range

**Comment by philippjfr** [comment]
This seems to have been resolved. Please reopen if you still see this.

![image](https://user-images.githubusercontent.com/1550771/33777152-a25f24ba-dc3b-11e7-8775-cfdfc6fee3d1.png)
