### ISSUE TITLE
Add a vectorized Text Element

### ISSUE THREAD

**Issue by jordansamuels** [ioam/holoviews#1837]
The following example works well for `n=10`, but e.g. `n=100` the re-rendering on zoom stops working (on MacBook Pro at least).
```
%%opts RGB [width=800, height=800]
n=100
clusters = np.random.uniform(low=(0,0,0),high=(1,1,.005),size=(n,3))
scatter = hv.Scatter(np.concatenate([scale *  np.random.randn(1000, 2) + (x,y) for x,y,scale in clusters]))
boxes = hv.Path([hv.Box(x,y,scale*6).data[0] for x,y,scale in clusters])
texts = hv.NdOverlay({i: hv.Text(x, y, text=f'{np.round(scale*100, 1)}') for i, (x, y, scale) in enumerate(clusters)}, kdims=['i'])
datashade(scatter) * datashade(boxes) * texts
```

If we take out the `* texts` then high e.g. `n=1000` zoom works fine.

**Comment by philippjfr** [comment]
We discussed this yesterday and we'd like to either make the Text Element vectorized or add a new vectorized Text Element. I've already written an implementation, which you can view here:

https://anaconda.org/philippjfr/multitext/notebook

So we only have to decide what to call it or whether to replace the existing ``Text`` Element.
