### ISSUE TITLE
BoxWhisker documentation could be improved

### ISSUE THREAD

**Issue by gcbgit** [ioam/holoviews#1838]
The current documentation on BoxWhisker states: "BoxWhisker represent data as a distributions highlighting, the median, mean and various percentiles."  I don't see the mean represented on the plot, and it's not clear from the documentation which percentiles are shown.  I presume that the box is the first and third quartiles, but that should be stated in the documentation for clarity.  There isn't an established convention on where the whiskers should be, so that should also be described in the documentation.

Also, the link in the reference gallery to "Columnar Data Tutorial" is broken.  The reference gallery states that the BoxWhisker represents data through their quartiles, which is true for the box, but the examples on that page show outliers so the whiskers aren't quartile related (they'd have to be 0 and 4, which would capture the full extent of the data, leaving no outliers).

**Comment by jlstevens** [comment]
The PR referenced above has been merged. Closing.
