### ISSUE TITLE
Example code will not run bk 0.12.7

### ISSUE THREAD

**Issue by byezy** [ioam/holoviews#1846]
Last code stanza from this page:

http://holoviews.org/user_guide/Deploying_Bokeh_Apps.html

Pasted and ran:
```
C:\Data\firevis\venv\Scripts\python.exe C:/Data/firevis/hvbkex.py
Traceback (most recent call last):
  File "C:/Data/firevis/hvbkex.py", line 67, in <module>
    show(app, notebook_url='localhost:8888')
  File "C:\Data\firevis\venv\lib\site-packages\bokeh\io.py", line 387, in show
    return _run_notebook_hook(_state.notebook_type, 'app', obj, _state, notebook_url)
  File "C:\Data\firevis\venv\lib\site-packages\bokeh\core\state.py", line 91, in notebook_type
    return self._notebook_type
AttributeError: 'State' object has no attribute '_notebook_type'

Process finished with exit code 1
```

![capture](https://user-images.githubusercontent.com/4742942/30008474-61908b2c-9163-11e7-8cd2-80eec9c1168d.PNG)

![capture1](https://user-images.githubusercontent.com/4742942/30008473-618a4730-9163-11e7-896d-d1ef1c2ed024.PNG)

**Comment by philippjfr** [comment]
Looks like this is an upstream bug in bokeh. Would you mind opening an issue there and link this one?

**Comment by byezy** [comment]
Sure thanks mate.

**Comment by philippjfr** [comment]
This is now working fine for me using bokeh 0.12.9 so I'll close. Please reopen if you can still reproduce it.
