### ISSUE TITLE
how can I put the y-axis on the right?

### ISSUE THREAD

**Issue by maajdl** [ioam/holoviews#1847]
Hello,
I could not find out how to make the y-axis of a Curve chart appear on the right instead of on the left.
Is that possible?
Thanks,
Michel

**Comment by philippjfr** [comment]
Using ``hv.help`` you can find out what options apply to an Element. To position the axis to the right you can do something like:

```python
%%opts Curve [yaxis='right']
hv.Curve([1, 2, 3])
```

or using the ``.opts`` syntax:

```python
hv.Curve([1, 2, 3]).opts(plot=dict(yaxis='right'))
```
