### ISSUE TITLE
hv.Image(arr, kdims=['x-axis', 'y-axis'])  writes along the x and y axes

### ISSUE THREAD

**Issue by maajdl** [ioam/holoviews#1854]
Hello,

I am reading the [holoviews tutorial](https://github.com/ioam/scipy-2017-holoviews-tutorial).
From the [first chapter](https://github.com/ioam/scipy-2017-holoviews-tutorial/blob/master/solutions/01-introduction-to-elements-with-solutions.ipynb), I tried this code:

     hv.Image(arr, kdims=['x-axis', 'y-axis'])

and nothing was written along the x and y axis.
I used hv 1.8.2 and tested the same on a windows laptop and on notebooks.azure .

Is that by design, or did I miss something?

Thanks,

Michel

**Comment by jlstevens** [comment]
Do you mean the axis labels aren't showing up? It looks like it is working for me with both bokeh and matplotlib:

![image](https://user-images.githubusercontent.com/890576/30162724-db06128a-93cd-11e7-9ae9-dcfdba356b55.png)

Which plotting extension are you using (i.e bokeh or matplotlib?)

**Comment by maajdl** [comment]
Thanks for the clear answer!
I tested that again on my laptop and on Azure notebooks.
In both case, it worked with:

    arr= np.random.rand(10,10)

but, in both case, it didn't work with

    arr= np.random.rand(500,500)

Therefore, it looks like a memory problem!

Would there be some fine tuning to allow more memory?

Anyway, thanks a lot,

Michel

**Comment by jlstevens** [comment]
> The image appeared, but without x and y axis labels.
Therefore, it looks like a memory problem!

That is rather odd! 

Are you using bokeh? It is possible bokeh starts struggling with larger images...

**Comment by maajdl** [comment]
Yes, I was using bokeh.
I now tried with matplotib, and there was no problem.
Thanks,
Michel

**Comment by jlstevens** [comment]
Ok great! 

It does sound like a memory issue when using bokeh - I'm afraid there isn't much that can be done about that (that said, I have opened a related [bokeh issue](https://github.com/bokeh/bokeh/issues/6896). For now I can only recommend using matplotlib when the arrays get large.

Based on this, I think I'll close the issue now but that doesn't mean we can't continue the discussion either here or on [gitter](https://gitter.im/ioam/holoviews).

**Comment by philippjfr** [comment]
>It does sound like a memory issue when using bokeh

Seems highly unlikely to me, since axis labels have nothing to do with memory. As he indicated it was an issue with the Jupyter iopub_data_rate_limit, but I suspect the axis labels disappearing is completely separate issue.

**Comment by jlstevens** [comment]
If it wasn't a memory error why would ``np.random.rand(10,10)`` be ok but ``np.random.rand(500,500)`` fail?

**Comment by philippjfr** [comment]
I still suspect it was the iopub_data_rate_limit. I don't see how memory errors could have anything to do with this.

**Comment by philippjfr** [comment]
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.
