### ISSUE TITLE
Use discrete colorbars for contours and polygons

### ISSUE THREAD

**Issue by rabernat** [ioam/holoviews#1856]
If I take the simple [contour example](http://holoviews.org/reference/elements/bokeh/Contours.html) from the docs and add a `filled=True` option, the `%%opts` seem to have no effect. I can no longer change the cmap or add a colorbar:

```python
%%opts Contours [show_legend=False colorbar=True width=325] (cmap='fire')
x,y = np.mgrid[-50:51, -50:51] * 0.05
img = hv.Image(np.sin(x**2+y**3))
z0, z1 = img.range('z')
hv.operation.contours(img, levels=np.linspace(z0, z1, 5), overlaid=False, filled=True)
```

![image](https://user-images.githubusercontent.com/1197350/30166831-899c8ee4-93b2-11e7-9e06-a8852c39b482.png)

Holoviews version is 1.8.3-x-ga66181c36 via conda-forge.

Possibly related to #1558

**Comment by philippjfr** [comment]
This is probably somewhat confusing but at least with latest master this works correctly if you set the options on Polygons, Contours is just used for the non-filled case:

```python
%%opts Polygons [show_legend=False colorbar=True width=325] (cmap='fire')
x,y = np.mgrid[-50:51, -50:51] * 0.05
img = hv.Image(np.sin(x**2+y**3))
z0, z1 = img.range('z')
hv.operation.contours(img, levels=np.linspace(z0, z1, 10), overlaid=False, filled=True)
```

**Comment by jlstevens** [comment]
That looks pretty! Might be one to add to the gallery...

**Comment by rabernat** [comment]
Great work!

My only comment would be that, with contour plots with discrete levels, we like to see discrete colorbars. This helps to read the precise values from the plot.

In matplotlib it looks like this:
![contours](https://matplotlib.org/_images/contourf_demo_021.png)

**Comment by philippjfr** [comment]
Good point, we need to improve our handling for discrete colormaps in general.

**Comment by jlstevens** [comment]
Perhaps we should repurpose this issue to be about discrete colormaps?

**Comment by philippjfr** [comment]
We now support a ``color_levels`` argument for discrete color mapping.
