### ISSUE TITLE
datashader -> regrid problem with RGB images

### ISSUE THREAD

**Issue by zbarry** [ioam/holoviews#1857]
Hi guys,

I encountered an error when using the master of holoviews.operation.datashader post-addition of the regrid class: https://github.com/ioam/holoviews/pull/1773. While this works perfectly fine for hv.Image, it croaks when trying to regrid hv.RGB objects. 

Simple code example:

```python
import numpy as np
import holoviews as hv
hv.extension('bokeh')
import datashader as ds
from holoviews.operation.datashader import regrid

image_rgb = np.random.randint(256, size=(512, 512, 3), dtype=np.uint8)
image_rgb_dict = {1: hv.RGB(image_rgb)}
image_rgb_holomap = hv.HoloMap(image_rgb_dict, kdims=['frame'])
regrid(image_rgb_holomap)
```
Results in the following error:
```
~~ snip ~~

~/Dropbox (MIT)/deep learning/DeepScope/src/holoviews/holoviews/operation/datashader.py in _process(self, element, key)
    401             if len(arrays) > 1:
    402                 array = np.dstack(arrays).transpose([2, 0, 1])
--> 403                 coords['layer'] = range(len(arrays))
    404                 dims = ['layer'] + dims
    405             else:

TypeError: 'tuple' object does not support item assignment
```
While the reason behind this particular error is clear (`coords = tuple(element.dimension_values(d, expanded=False) for d in [x, y])`), it is much less clear to me how to fix this problem, as I'm not quite sure just how HoloViews and xarray play together. Could someone shed some insight on how to possibly fix this problem?

Thanks so much!

**Comment by philippjfr** [comment]
Thanks for catching this. I'll try to push a fix up asap.

**Comment by zbarry** [comment]
Great! Thanks for looking into this. I appreciate it.
