### ISSUE TITLE
(help) DynamicMap: the final touch (duplicate hover tool, title, redim.range, ... )

### ISSUE THREAD

**Issue by maajdl** [ioam/holoviews#1858]
Hello,
I just used a DynamicMap to sketch a psychrometric chart [as explained earlier](https://github.com/ioam/holoviews/issues/1855).
Below is how I did it and the result.
I have some questions for the final touch:

- why do I get two hover tools instead of one ?
- why do I need to disable the left hover tool to get hover_line_alpha working?
- how could I specify a list of values to .redim.range  instead of a continuous range?
- how could I specify an initial value for the DynamicMap  parameters rh, hm, ... ?
- how could I remove the text boxes showing the values of DynamicMap parameters rh, hm, ... ?
- is it possible to move the parameters toolbox somewhere else (left)?
- how could I remove the automatic title showing the values of the parameters?

Thanks for your suggestions,

Michel

![image](https://user-images.githubusercontent.com/7543475/30208143-70b05d62-9492-11e7-8cb4-ad8ac1860adc.png)

**Comment by philippjfr** [comment]
>why do I get two hover tools instead of one ?

Sounds like a potential bug, I'd have to investigate.

>why do I need to disable the left hover tool to get hover_line_alpha working?

Probably related to the previous point.

>how could I specify a list of values to .redim.range instead of a continuous range?

Use ``.redim.values`` instead.

>how could I remove the text boxes showing the values of DynamicMap parameters rh, hm, ... ?

You can't (except for hacky means of changing the CSS). We're working on making widgets more flexible/customizable.

>is it possible to move the parameters toolbox somewhere else (left)?

Part of the plan to improve widgets, but currently not easily possible.

>how could I remove the automatic title showing the values of the parameters?

You should be able to change the ``title_format`` plot option.

**Comment by maajdl** [comment]
Thanks a lot for this FTL answer !!!

**Comment by jbednar** [comment]
You should be able to move the widgets and the widget text boxes by using ParamNB or ParamBokeh to control those parameters, instead of having them generated by HoloViews as here. That will require more work, but it basically lets you define arbitrary parameters and then generate a single HoloViews plot instead of defining a space of them as you do here.  Not that I would recommend it, but if you really do need control over those aspects, you can have it.

**Comment by maajdl** [comment]
I tried to remove the DynamicMap title in this way:

    hv.core.dimension.title_format = ''

The strange thing is that I get now a title with two comas in it,
and these commas remain if I relabel the plot.
Any clue?
Thanks again!

**Comment by philippjfr** [comment]
Sorry, I should have been clearer, that's not what I meant. Here's what I mean:

```python
%%opts Curve [title_format='']
hv.HoloMap({i: hv.Curve([]) for i in range(5)})
```

**Comment by maajdl** [comment]
Hello.
I just tried the code shown below.
With or without the option " title_format='' "  it gives the same result: 4 parameters displayed.
Any suggestion?
Thanks,
Michel

```python
%%opts Curve [title_format='' width=675  height=556  show_grid=True   tools=['hover']  toolbar='above'  yaxis='right']

import numpy as np

o = hv.Curve({}, kdims=['Dry bulb temperature  [°C]'], vdims=['Humidity ratio  [kg/kg]'])
p = hv.Overlay( [hv.Curve(v) for (k,v) in rh_curve.items()] )
q = hv.Overlay( [hv.Curve(v) for (k,v) in hm_curve.items()] )
r = hv.Overlay( [hv.Curve(v) for (k,v) in tw_curve.items()] )
s = hv.Overlay( [hv.Curve(v) for (k,v) in vs_curve.items()] )

def psychart(rh,hm,tw,vs):
    pcolor = {'Curve':{'style': {'line_width':0, 'color':'red'  , 'alpha':rh, 'hover_line_alpha':1}}}
    qcolor = {'Curve':{'style': {'line_width':0, 'color':'blue' , 'alpha':hm, 'hover_line_alpha':1}}}
    rcolor = {'Curve':{'style': {'line_width':0, 'color':'green' , 'alpha':tw, 'hover_line_alpha':1}}}
    scolor = {'Curve':{'style': {'line_width':0, 'color':'grey', 'alpha':vs, 'hover_line_alpha':1}}}
    g = (o * p(pcolor) * q(qcolor) * r(rcolor) * s(scolor))
    g = g.redim(x={'range': (0, 50)}, y={'range': (0, 0.030)})         #.relabel("Psychrometric Chart")
    return g

dmap = hv.DynamicMap(psychart, kdims=['rh','hm','tw','vs'], )
vls = np.arange(0,1.1,0.1)
dmap.redim.values(rh=vls).redim.values(hm=vls).redim.values(tw=vls).redim.values(vs=vls)
```

**Comment by philippjfr** [comment]
Looks like you need to set it on the Overlay in this case, this works:

```python
%%opts Overlay [title_format='']
```

I'll file an issue to fix that.

**Comment by maajdl** [comment]
Thanks a lot, this does now what I wish:
```
%%opts Overlay [ title_format='Psychrometric Chart']
```

**Comment by philippjfr** [comment]
Looks like this was addressed? I'll close please reopen if there was something I missed.
