### ISSUE TITLE
HoloMap could generate more useful messages when supplied Layouts

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#186]
If a ``HoloMap`` is given ``Layout`` objects, we probably can't collate it in a useful way but we could at least generate a more helpful exception message.

At least, it could suggest that user use the ``Layout.collate`` method which would be compatible with the intended semantics of the user.

**Comment by jlstevens** [comment]
We quickly came up with an even better approach: we give supply the user a helpful message suggesting the use of ``collate`` with a pointer to the documentation.

Implemented in fbd89c3.

We should now improve the Composing Data tutorial given that people will be directed to it via this message.

**Comment by jlstevens** [comment]
The Composing Data tutorial was improved for this purpose in 2c0a615

In ac745de I added a displayable predicate function and b645b2d adds a helper to generate helpful messages for undisplayable objects. Finally, 3162e3c generalizes the display hooks to handle all possible undisplayable objects.

Lastly, 985d275 makes sure the appropriate exception is raised if people supply undisplayable objects to ``MPLRenderer``.

**Comment by jlstevens** [comment]
A few points to add before I forget them:

* We might want to update the homepage example to use a ``HoloMap`` instead of ``Layout.collate``.  I think this might be less obscure to people...

* Philipp and I discussed the name and think ``Layout.collate`` may not be necessary anymore and if we *do* keep it, it should be ``Layout.merge``. The difference is that merge is a classmethod always returns an object of the same type as the class it is on whereas ``collate`` is an instance method that can give you an type of valid object. Both use ``Collator`` behind the scenes.

* We also discussed renaming ``Collator`` to ``MergeTable`` and decided on an appropriate tabular representation for it. I personally think that ``Directory`` would be an excellent name for ``FileCollator``.

**Comment by jlstevens** [comment]
Two more comments:

* I think ``NdOverlay`` could also have ``collate`` and allow any type of element in it. As far as I can see, this is the only other place ``collate`` could exist.

* I think we've decided to put a deprecation warning in ``Layout.collate`` and remove it in the next release (we'll then have to update the homepage). Here is what would be the new, equivalent version:

```python
%%opts Points [scaling_factor=50] Contours (color='w')
dots = np.linspace(-0.45, 0.45, 19)

HoloMap({y: (fractal * fractal.sample([(i,y) for i in dots]).to.points(['x','y'], 'z') +
       fractal.sample(y=y) +
       operation.threshold(fractal,  level=np.percentile(fractal.sample(y=y).data, 90)) +
       operation.contours(fractal, levels=[np.percentile(fractal.sample(y=y).data, 60)]))
     for y in np.linspace(-0.3, 0.3, 21)}).collate().cols(2)
```

I like it! Firstly ``Layout`` doesn't need to be introduced (implicit in +) and you don't even need to specify the key dimensions when collating...

**Comment by basnijholt** [comment]
Maybe I should make a separate issue for this, but other things that frequently go wrong and deserve a good error message are:
* Trying to ``.select`` a value dimension of a ``Curve`` element.
* Thinking ``Path`` and ``Curve`` accept the same data inputs, i.e. ``hv.Curve([1,2,3])`` works, ``hv.Path([1,2,3])``, doesn't.

**Comment by jlstevens** [comment]
Thanks! That is very useful feedback for us to consider...

**Comment by jbednar** [comment]
I like the new version for the home page; please do change it to be like that!

**Comment by jlstevens** [comment]
We now automatically collate in some (potentially) common cases while issuing a warning. Here is the warning generated for a ``HoloMap`` containing ``GridSpaces`` or ``Layouts``:

```bash
 Warning: Call the collate method on HoloMap to get the data into recommended format.
Please consult the nesting hierarchy diagram of the Composing Data tutorial (http://git.io/vtIQh)
```

And here is the warning for ``Layouts`` containing undisplayable ``HoloMaps``:

```bash
Warning: Call the collate method on component HoloMap(s) to get the data into recommended format.
Please consult the nesting hierarchy diagram of the Composing Data tutorial (http://git.io/vtIQh)
```

I think this is the best we can do to support whatever the user tries while also trying to get the user to use the data-structures in the appropriate way. I hope the warnings will convince people to do the right thing!

**Comment by jlstevens** [comment]
The homepage example is updated in 1024276.

I note that there is one other reason people will use ``.collate()`` - they can't set ``cols(2)`` on a HoloMap!

**Comment by jlstevens** [comment]
Are we happy with the new behavior and the warning messages? I certainly think it is an improvement over disallowing the user from building these sorts of data structures with an unfriendly exception message!

I hope this changes achieves three things:

* Helps the user work in whatever way is more natural.
* Help the user do the sensible thing without forcing them to refactor their code.
* Direct the user to the documentation to get a better understanding of HoloViews.

Anyway, if we agree this is done now, I would like to close this issue.

**Comment by philippjfr** [comment]
Yep, definitely think this is preferable. Go ahead and close the issue.

**Comment by jbednar** [comment]
I'd say "Warning: nesting Layouts within a HoloMap makes it difficult to access your data or control how it appears; we recommend calling .collate() on the HoloMap to nest the HoloMaps within a Layout instead (see the nesting ...) ".

**Comment by jlstevens** [comment]
Ok, a bit long but also helps explain the situation a bit better. @philippjfr ?

**Comment by philippjfr** [comment]
That seems fine, but it's only for the simple case right? We also need one for the other unrecommended ways objects can be nested.

**Comment by jbednar** [comment]
Wherever they is a clearly correct thing to do, then a similar message telling people that for their specific situation is very helpful. I don't know what that would be in the other cases.

**Comment by jlstevens** [comment]
Warning messages improved along the lines you suggested in 187107c.
