### ISSUE TITLE
Support bokeh themes

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#1861]
It would be good to support bokeh's [theme feature](http://bokeh.pydata.org/en/latest/docs/reference/themes.html) which I don't think we currently do.

One issue is that the documented way of applying a theme is to use ``doc.theme = Theme(...)`` and it isn't clear how that would be applied in holoviews.

**Comment by philippjfr** [comment]
This has been implemented and also documented.

**Comment by kcpevey** [comment]
@philippjfr  Would you mind linking to the docs? I can't seem to find this via searching.

**Comment by jlstevens** [comment]
@kcpevey The website is due to be updated soon for the 1.10 release. The docs about theming are currently only in the [Plotting with Bokeh](https://github.com/ioam/holoviews/blob/master/examples/user_guide/Plotting_with_Bokeh.ipynb) notebook which you should be able to view on GitHub.
