### ISSUE TITLE
norm{-axiswise +framewise} not working for Bars

### ISSUE THREAD

**Issue by Jerryzhuht** [ioam/holoviews#1862]
Use the example from:

> http://holoviews.org/gallery/demos/bokeh/dropdown_economic.html

> 

`%%opts Bars [width=600 height=600](width=0.5 line_alpha=0) norm{-axiswise +framewise}`
`gdp_bars = macro.to.bars('Year', 'GDP Growth')`
`gdp_bars`
Y-axis do not change when changing the country.

While curves and scatters works:
`%%opts Curve [width=600 height=600](color='k') norm{-axiswise +framewise}`
`gdp_curves = macro.to.curve('Year', 'GDP Growth')`
`gdp_curves`

**Comment by philippjfr** [comment]
This has been fixed in master, closing.
