### ISSUE TITLE
Eliminate remaining instances of kernel.execute

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#1863]
This has been something we have been meaning to do for a long time but I don't think an issue was assigned till now. In some places, we still use ``kernel.execute`` for instance [here](https://github.com/ioam/holoviews/blob/656e42f21271e487fa3ad520e6b2eff333a79335/holoviews/plotting/widgets/widgets.js#L72).

We should eliminate any remaining uses of ``kernel.execute`` and make sure everything uses our ``Comms`` classes.

**Comment by philippjfr** [comment]
This has been done in the JupyterLab refactor.
