### ISSUE TITLE
uninformative error when creating dataset from nameless xarray.DataArray

### ISSUE THREAD

**Issue by rabernat** [ioam/holoviews#1867]
I tried to create a holoviews Dataset as follows
```python
data = xr.DataArray(np.random.rand(20,30,40),
                    dims=['z', 'y', 'x'],
                    coords={'z': np.arange(20),
                            'y': np.arange(30),
                            'x': np.arange(40)})
ds = hv.Dataset(data)
```
I got the error
```
ValueError: None of the available storage backends were able to support the supplied data format.
```

Finally I figured out that I needed to provide a name to the dataarray
```python
data = xr.DataArray(np.random.rand(20,30,40),
                    dims=['z', 'y', 'x'],
                    coords={'z': np.arange(20),
                            'y': np.arange(30),
                            'x': np.arange(40)},
                    name='testdata')
ds = hv.Dataset(data)
```
...and it worked fine.

If the error had said something like "xarray dataarrays must have a name to convert to holoviews datasets", it would have saved me some considerable headache.

**Comment by philippjfr** [comment]
We need to improve exception handling around the ``Dataset`` constructor in general. I've got a proposal around this, which I will describe in detail in a new issue as soon as I get some time to flesh it out.

**Comment by jlstevens** [comment]
Agreed. We really want better exception messages so I am assigning this issue (tentatively) to the 1.9 milestone.

**Comment by philippjfr** [comment]
This should now raise the following error:

>DataError: If xarray DataArray does not define a name an explicit vdim must be supplied.

>XArrayInterface expects gridded data, for more information on supported datatypes see http://holoviews.org/user_guide/Gridded_Datasets.html

**Comment by maxibor** [comment]
I'm not sure this is related, but I'm getting the same error message here: https://github.com/maxibor/panel-holoviews-volcano/issues/1
