### ISSUE TITLE
key_dimensions (and similar) should still work in methods calls

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#187]
We recently renamed  the parameters``key_dimensions`` to ``kdims`` and similarly for value and constant dimensions (while maintaining support for the full names). This much all works fine...

My worry is that we did the same thing for the argument names in methods. While I do prefer the short names, I would be happier if we could still support the long names in methods while issuing deprecation warnings (if we really want to get rid of the long names eventually).

I don't want to break users code with this kind of API change (trivial though it might be) without having at least one release that issues deprecation warnings so that the necessary code can be updated.

**Comment by jlstevens** [comment]
As it turns out, ``Layout.collate`` was the only place this is an issue.

In commit 477cbed I fix this and also add a deprecation warning because we want to eventually remove ``Layout.collate`` entirely.

**Comment by basnijholt** [comment]
I remember yesterday you implemented an error message that pointed people to ``Layout.collate``, maybe you should remove that recommendation if it's going to disappear?

**Comment by jlstevens** [comment]
That error message should be pointing people to ``HoloMap.collate`` not ``Layout.collate``. I agree this should be made clear!
