### ISSUE TITLE
redim.range with doesn't work with QuadMesh

### ISSUE THREAD

**Issue by rabernat** [ioam/holoviews#1870]
It appears like `redim.range` has no effect with QuadMesh objects. I will use a slightly modified example from the  [QuadMesh docs](http://holoviews.org/reference/elements/bokeh/QuadMesh.html)

```python
n = 8  # Number of bins in each direction
xs = np.logspace(1, 3, n)
ys = np.linspace(1, 10, n)
zs = np.arange((n-1)**2).reshape(n-1, n-1)
qmesh = hv.QuadMesh((xs, ys, zs))
print(qmesh.range('z'))
qmesh.redim.range(z=(1,2))
print(qmesh.range('z'))
```
prints
```
(0, 48)
(0, 48)
```

Looking closely at the the [example](http://holoviews.org/reference/elements/bokeh/QuadMesh.html), you can see this bug is at work there as well. The third figure calls redim to "set the z-dimension range to maintain the full color range of the colormap". There is no colorbar, but it is clear that the redim did not have an effect, since the colormap is saturated.

**Comment by rabernat** [comment]
I don't think `redim.label(x='lat', y='depth')` works either.

**Comment by philippjfr** [comment]
>I don't think qmesh.redim.label(x='lat', y='depth') works either.

Are you sure? Seems to work for me. Do not that redim (like most other operations in holoviews) is not an inplace operation.

**Comment by rabernat** [comment]
The inplace issue would also apply to my original example with `redim.range`, no?

However, if I rewrite it as
```
qmesh = hv.QuadMesh((xs, ys, zs))
print(qmesh.range('z'))
newmesh = qmesh.redim.range(z=(1,2))
print(newmesh.range('z'))
```
it gives the same result

**Comment by philippjfr** [comment]
Yes, sorry for the confusion, ``redim.range`` is not working, ``redim.label`` is. The PR above will fix the issue with ``redim.range``.

**Comment by philippjfr** [comment]
PR now merged. Thanks for making me look into this, it let me standardize the ``range`` implementations a lot.
