### ISSUE TITLE
datashader -> regrid: overlaying curves on a regridded image

### ISSUE THREAD

**Issue by zbarry** [ioam/holoviews#1880]
Hello again. Seems like I might have found another problem with image regridding. This appears to happen when you overlay (* operator) a holomap of overlays, each containing different numbers of curves, on top of a regridded image:

```2017-09-11 21:12:35,058 OverlayPlot03756: Some Elements returned by the dynamic callback were not initialized correctly and could not be rendered.```

It *seems* like what is happening is if, for example, you have 5 curves in the first "frame" of the overlay, only the first 5 curves of the next frames to come are able to be drawn. I.e., the number of elements in the first overlay dictates the maximum number of elements able to be rendered in the following overlays. Here's code that replicates this issue (happens in notebook too, but you don't see the warning message) [I use ```bokeh serve file``` to run]. There are three plotted layouts: 1) a constant 5 contours overlaid on top of a regridded white image, 2) (5+frame) number of contours that increase with the slider. No regridded image. 3) the previous overlaid on a regridded image. Theoretically, (3) should look identical to (2), but you'll see that more curves are not being added.

```
import holoviews as hv
from holoviews.operation.datashader import regrid
import numpy as np

renderer = hv.renderer('bokeh')

#####

image_style = {'cmap': 'gray'}
image_plot = {'width': 450, 'height': 450}

#####

image = np.ones((512,512,50))

bounds = (0, 0, image.shape[1]-1, image.shape[0]-1)

image_dict = {frame_idx+1:hv.Image(image[:,:,frame_idx],bounds=bounds)(style=image_style, plot=image_plot)
              for frame_idx in range(image.shape[2])}

image_hmap = hv.HoloMap(image_dict, kdims=[hv.Dimension(('frame','frame'), range=(1,image.shape[2]), step=1)])

##########################

def circle(radius, x=0, y=0):
    angles = np.linspace(0, 2*np.pi, 100)
    arr = np.array(list(zip(x + radius * np.sin(angles), y + radius * np.cos(angles))))
    arr += 5 * np.random.randn(*arr.shape)
    return arr

###

contour_overlays_all = []

for frame_idx in range(image.shape[2]):
    contour_overlays_all.append(hv.Overlay([hv.Contours([circle(i + 0.05, x=255, y=255)],
                                                        level=i) for i in np.linspace(0, 200, 5)]))

contour_dict = {frame_idx+1: contour_overlays_all[frame_idx]
                for frame_idx in range(image.shape[2])}

contour_hmap = hv.HoloMap(contour_dict, kdims=[hv.Dimension(('frame','frame'), range=(1,image.shape[2]), step=1)])

###

contour_overlays_changing_all = []

for frame_idx in range(image.shape[2]):
    contour_overlays_changing_all.append(hv.Overlay([hv.Contours([circle(i + 0.05, x=255, y=255)], level=i) 
                                                     for i in np.linspace(0, 200, frame_idx+5)])(plot=image_plot))

contour_changing_dict = {frame_idx+1: contour_overlays_changing_all[frame_idx]
                        for frame_idx in range(image.shape[2])}

contour_changing_dict = hv.HoloMap(contour_changing_dict, kdims=[hv.Dimension(('frame','frame'), 
                                   range=(1,image.shape[2]), step=1)])

##########################

layout = regrid(image_hmap) * contour_hmap
doc = renderer.server_doc(layout)

layout = contour_changing_dict
doc = renderer.server_doc(layout, doc=doc)

layout = regrid(image_hmap) * contour_changing_dict
doc = renderer.server_doc(layout, doc=doc)

doc.title = 'Contour + regrid problem demonstration'
```
Thanks for your assistance. Sorry if the code looks weird, or is not how you'd normally do things. I'm extremely new to HV/Bokeh, so I'm kind of just figuring it out as I go. (It's a seriously cool framework, by the way!)

Versions:
HoloViews: latest GitHub master (also tested 1.8.3)
Bokeh: latest GitHub master (also tested 0.12.7)
Datashader: 0.6.0 (the latest GH-M seems to be completely broken for panning and zooming regridded images, though I haven't looked into this much)

**Comment by philippjfr** [comment]
This is a known limitation that should be documented better and should eventually go away. What you can do is replace the ``Overlay`` with an ``NdOverlay`` and set the following option on the object:

```python
.opts({'NdOverlay': {'plot': dict(legend_limit=0)}})
```

Let me know if you need additional help implementing that.

**Comment by zbarry** [comment]
It works! Thanks so much. :)

**Comment by philippjfr** [comment]
Great, I'll close since there are other issues about documenting this problem.
