### ISSUE TITLE
conda install holoviews

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#189]
We should make holoviews available at anaconda.org (formerly binstar) before we announce 1.3, and certainly before SciPy.  That means making param installable that way as well.

**Comment by jlstevens** [comment]
I agree... I'll look into the process now.

**Comment by jlstevens** [comment]
Ok, I've learnt a lot about preparing packages for conda!

Firstly, we have a new ioam account on anaconda: https://anaconda.org/ioam/

Secondly, I have created both conda packages and pypi packages for param, lancet and holoviews. Generally, you seem to have to install as follows:

```bash
conda install -c ioam holoviews
```

Note this version of holoviews is still 1.2.0 but now I know the process releasing 1.3.0 will be easy!

**Comment by jlstevens** [comment]
For completeness I add imagen too.

**Comment by jbednar** [comment]
Great!

**Comment by philippjfr** [comment]
As far as I can tell this has all been done. Will close the issue.
