### ISSUE TITLE
BoundsXY example doesn't work with v.1.8.4/Bokeh 0.12.9

### ISSUE THREAD

**Issue by timothydmorton** [ioam/holoviews#1890]
Box selection doesn't seem to do any action in this example, using holoviews 1.8.4 + Bokeh 0.12.9:

http://holoviews.org/reference/streams/bokeh/Bounds.html

**Comment by philippjfr** [comment]
I believe this is related to: https://github.com/bokeh/bokeh/issues/6921

**Comment by timothydmorton** [comment]
To be specific, the bounds tutorial referenced above doesn't work if the `streams.BoundsXY` stream is used (as the deprecation warning suggests).  It does seem to work fine using the deprecated `streams.Bounds` object instead.  Again, this is with hv=1.8.4/bokeh=0.12.9

**Comment by jlstevens** [comment]
> It does seem to work fine using the deprecated streams.Bounds object instead.

That does sound like a hv bug to me...

**Comment by philippjfr** [comment]
The bug has been fixed for a while but for some reason the fix didn't make it into the 1.8.3 and 1.8.4 releases. Separately there is the bokeh issue mentioned above.

**Comment by philippjfr** [comment]
This has been fixed in master and the bokeh issue was addressed.
