### ISSUE TITLE
shall  "legend_example" work on Jupyterlab-0.27.0, holoviews-1.8.4, bokeh-0.12.9 ? 

### ISSUE THREAD

**Issue by stonebig** [ioam/holoviews#1891]
this example works on Notebook, but not in jupyterlab-0.27.0.
Is it normal (could be me ?)
https://github.com/ioam/holoviews/blob/master/examples/gallery/demos/bokeh/legend_example.ipynb

![holo1](https://user-images.githubusercontent.com/4312421/30512579-10459b74-9af3-11e7-8ccf-4f4c6c0fd3e4.PNG)

**Comment by philippjfr** [comment]
We still haven't done any testing or compatibility work on JupyterLab. Have you tested other examples or is it specific to this example?

**Comment by stonebig** [comment]
well, now testing the same on "notebook" with matplotlib-2.1.0rc1, it doesn't go very much better

![holo2](https://user-images.githubusercontent.com/4312421/30512608-c7a28304-9af3-11e7-99d8-f46819fb74ef.PNG)

**Comment by stonebig** [comment]
well, it's just that now that I have bokeh and ipyleaflet working on jupyterlab, I tried to be a little more adventurous, and tried your most recent example.

**Comment by philippjfr** [comment]
It looks like you're running the bokeh example in matplotlib, does the corresponding matplotlib version of the notebook work?

**Comment by stonebig** [comment]
heu I did run the exampl  in matplotlib/boke h * notebook/jlab. apparently only the notebook/bokeh example works

**Comment by philippjfr** [comment]
What I mean is that it looks like you simply ran the bokeh version and switched to the matplotlib extension. There are backend specific versions of each notebook, e.g. notice how the example exists in:

``` 
examples/gallery/demos/bokeh/legend_example.ipynb
```

There is an equivalent example for matplotlib in, which should work:

```
examples/gallery/demos/matplotlib/legend_example.ipynb
```

**Comment by stonebig** [comment]
oups!  I didn't notice the last cell was different. so Matplotlib*Notebook is ok

**Comment by philippjfr** [comment]
Going to close this since we have an existing issue for JupyterLab compatibility.
