### ISSUE TITLE
Improve legend position defaults

### ISSUE THREAD

**Issue by ea42gh** [ioam/holoviews#1898]
hv.plotting.bokeh.element.LegendPlot.legend_specs
```
legend_specs = {'right': dict(pos='right', loc=(5, -40)),
                           'left': dict(pos='left', loc=(0, -40)),
                           'top': dict(pos='above', loc=(120, 5)),
                          'bottom': dict(pos='below', loc=(60, 0))}
```
leaves insufficient space (especially top).
left/right y position might be improved to lign up baseline of string representation with plot elements

**Comment by philippjfr** [comment]
Since https://github.com/ioam/holoviews/pull/1989 the legend positions now align properly again and a new ``legend_offset`` plot option was added to apply small adjustments to the legend positions.
