### ISSUE TITLE
Sanitization issue in sample method

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#190]
This generates an exception:

```python
hv.Image(np.random.rand(10,10), kdims=[r'$B$', r'$E$']).sample(B=0)
```

Whereas this works:

```python
hv.Image(np.random.rand(10,10), kdims=[r'$B$', r'$E$']).sample(**{'$B$':0})
```

The fundamental  issue seems to be with the ``get_dimension_index`` method:

```python
im,get_dimension_index('B')  # Doesn't work but '$B$' does...
```

**Comment by philippjfr** [comment]
Fixed in https://github.com/ioam/holoviews/commit/6685633d2ffd6e48d59c4a7e7a3603287b9f3856. It was also affecting ``.reduce`` so that's been fixed as well.
