### ISSUE TITLE
changing grid lines color, alpha, ...

### ISSUE THREAD

**Issue by maajdl** [ioam/holoviews#1903]
Hello,

Is there a way to change the color of the grid lines, and eventually other attributes?
I guess this should be lines for Curves, HLines, ...
I just don't see how I can access the grid lines ...

Thanks,

Michel

**Comment by jlstevens** [comment]
If you are using bokeh, we will be adding support for [bokeh themes](https://bokeh.pydata.org/en/latest/docs/reference/themes.html#bokeh-themes) soon which will let you customize anything that we haven't exposed. 

In this particular case, I don't know whether we expose a way to change the gridline color offhand but @philippjfr might...

**Comment by philippjfr** [comment]
We now expose a gridstyle option which is described in the plotting with bokeh user guide.
