### ISSUE TITLE
Make plot class get_extents method into classmethods

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#1917]
As a first step towards generalizing the normalization system the ``get_extents`` method on ElementPlots should all be made into classmethods, allowing them to be called before the class is instantiated.

**Comment by jlstevens** [comment]
I'll never say no to a sensible classmethod!

**Comment by philippjfr** [comment]
While this seemed like a good idea in principle certain element types do need plotting class state to compute the extents so this is not feasible in practice.
