### ISSUE TITLE
Latest Holoviews master seems to have a conflict with networkx

### ISSUE THREAD

**Issue by stonebig** [ioam/holoviews#1920]
the networkx example seems not working any more with latest Holoviews github master:
https://github.com/ioam/holoviews/blob/master/examples/user_guide/Network_Graphs.ipynb

````
import numpy as np
import pandas as pd
import holoviews as hv
import networkx as nx

hv.extension('bokeh')

%opts Graph [width=400 height=400]
````
gives:
````
---------------------------------------------------------------------------
SystemError                               Traceback (most recent call last)
<ipython-input-1-7f1b468611bc> in <module>()
      2 import pandas as pd
      3 import holoviews as hv
----> 4 import networkx as nx
      5 
      6 hv.extension('bokeh')

C:\WinPython\basedir36\buildQt5\winpython-64bit-3.6.x.1\python-3.6.2.amd64\lib\site-packages\networkx\__init__.py in <module>()
     72 
     73 # Release data
---> 74 from networkx import release
     75 
     76 __author__ = '%s <%s>\n%s <%s>\n%s <%s>' % \

C:\WinPython\basedir36\buildQt5\winpython-64bit-3.6.x.1\python-3.6.2.amd64\lib\site-packages\networkx\release.py in <module>()
    223     'Topic :: Scientific/Engineering :: Physics']
    224 
--> 225 date, date_info, version, version_info, vcs_info = get_info()
    226 
    227 if __name__ == '__main__':

C:\WinPython\basedir36\buildQt5\winpython-64bit-3.6.x.1\python-3.6.2.amd64\lib\site-packages\networkx\release.py in get_info(dynamic)
    155         # sys.path.insert(0, basedir)
    156         try:
--> 157             from version import date, date_info, version, version_info, vcs_info
    158         except ImportError:
    159             import_failed = True

C:\WinPython\basedir36\buildQt5\winpython-64bit-3.6.x.1\python-3.6.2.amd64\lib\site-packages\param\version.py in init param.version (param\version.c:7238)()
     81 __author__ = 'Jean-Luc Stevens'
     82 
---> 83 import os, subprocess
     84 
     85 def run_cmd(args, cwd=None):

SystemError: Parent module 'version' not loaded, cannot perform relative import
````

**Comment by stonebig** [comment]
it goes better if I invert  the order of imports, but it's not that good in general case:
````
import numpy as np
import pandas as pd
import networkx as nx
import holoviews as hv

hv.extension('bokeh')

%opts Graph [width=400 height=400]
````

**Comment by philippjfr** [comment]
@stonebig Thanks for reporting this, I'll try to figure out what's going on.

**Comment by philippjfr** [comment]
@jlstevens Any idea what's going on here? ``from version import ...`` in networkx seems to be calling into ``param.version``.

**Comment by stonebig** [comment]
I use networkx-2.0.0, 4 days old release.

**Comment by jlstevens** [comment]
> Any idea what's going on here? from version import ... in networkx seems to be calling into param.version.

That is very odd behavior and I have no idea what is going on. There is no reason for networkx to touch our ``__version__`` variables in any way.

**Comment by stonebig** [comment]
I don't have it on a networkx-2.0 / python-3.5 / bokeh-0.12.9 / day before holoviews, not cython-0.27.0.  so supects could be:
- a cython-0.27.0 bug,
- a python-3.6 bug,
- or something in last 48 hours of holoviews,
- or something completly different.

**Comment by stonebig** [comment]
hum, it bugs on idle too...

**Comment by stonebig** [comment]
this "from version import version" may favorise a strange bug ?

**Comment by stonebig** [comment]
I think this suffice to trigger the issue/
````
import holoviews as hv
from version import version
````

**Comment by jlstevens** [comment]
Param does have a [version.py](https://github.com/ioam/param/blob/master/param/version.py) but I don't see anywhere where it is imported to cause such a conflict. HoloViews uses [param.Version](https://github.com/ioam/holoviews/blob/master/holoviews/__init__.py#L12) without ever importing ``version``.

**Comment by stonebig** [comment]
````
Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> import holoviews as hv
>>> version
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    version
NameError: name 'version' is not defined
>>> import version
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    import version
  File "param\version.py", line 83, in init param.version (param\version.c:7238)
    import os, subprocess
SystemError: Parent module 'version' not loaded, cannot perform relative import
>>> 
````

**Comment by stonebig** [comment]
or also:
````
Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> import version
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import version
ModuleNotFoundError: No module named 'version'
>>> import holoviews as hv
>>> import version
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    import version
  File "param\version.py", line 83, in init param.version (param\version.c:7238)
    import os, subprocess
SystemError: Parent module 'version' not loaded, cannot perform relative import
>>> 
````
if you don't reproduce, then it may be the way I created the wheel.

**Comment by philippjfr** [comment]
Sounds like an issue with Cython. How did you install param? I thought we hadn't enabled that by default.

**Comment by stonebig** [comment]
param comes from there : http://www.lfd.uci.edu/~gohlke/pythonlibs/#param.

you think I may recompile it ?

**Comment by stonebig** [comment]
i will downgrade to previous cython, to check

**Comment by philippjfr** [comment]
Oh wow, I didn't even know that was still in there. Will push a PR removing that regardless. Hopefully that fixes it.

**Comment by jbednar** [comment]
> Sounds like an issue with Cython. How did you install param? I thought we hadn't enabled that by default.

I believe that param uses Cython when installed with pip, and since wheels are mentioned above, I assume param is indeed being installed with pip.  I have no idea why that difference between conda and pip installations happened; seems backwards if anything!

**Comment by jlstevens** [comment]
> Oh wow, I didn't even know that was still in there

Me neither! That should have gone away a *long* time ago!

**Comment by philippjfr** [comment]
Not clear this has actually been fixed by that change so I'll leave it reopen until @stonebig can confirm.

**Comment by stonebig** [comment]
It works now as intended. Many thanks to @cgohlke to have made us look in the right direction.

**Comment by philippjfr** [comment]
Yes, thanks for looking into this for us @cgohlke!
