### ISSUE TITLE
hv.Text(0.5,0.5, "test", fontsize=40)   fontsize has no effect  (Bokeh)

### ISSUE THREAD

**Issue by maajdl** [ioam/holoviews#1921]
Hello,

I realized that the fontsize parameter had no effect in this statement when using Bokeh:

`hv.Text(0.5,0.5, "test", fontsize=40)`

Any idea how I could work around this?

Thanks,

Michel

**Comment by philippjfr** [comment]
Marking as a bug, for now you can do this:

```python
hv.Text(0.5,0.5, "test").opts(style=dict(text_font_size='40pt'))
```
