### ISSUE TITLE
Default=0.3 instead of y=0.3 on homepage

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#193]
The homepage notebook used to have a slider and title labelled "y", but now the slider and title are labeled "default".  Y was much better!  Presumably this is from the changes to collate?

**Comment by philippjfr** [comment]
Right, thanks for catching that. It has nothing to do with the collate itself, it's just that the HoloMap doesn't have any dimension declared.

**Comment by jlstevens** [comment]
Philipp's updated the notebook and now we just need to refresh the website. 

I'll close the issue now...
