### ISSUE TITLE
hover information not fully shown in bar chart

### ISSUE THREAD

**Issue by weichm** [ioam/holoviews#1939]
When hovering over the chart, '???' appears for `atomic radius`, see below.

![holoviews](https://user-images.githubusercontent.com/6342556/31026684-97bb18f0-a547-11e7-98cc-7a229cfdd065.png)

I also tried in vain:
```python
import pandas as pd
import holoviews as hv
hv.extension('bokeh')
from bokeh.sampledata.periodic_table import elements as df

%%opts Bars [width=1024 height=400 tools=['hover']]
ds = hv.Dataset(df, kdims=['atomic number'], vdims=['electronegativity', 'atomic radius'])
ds.to(hv.Bars)
```

It seems to work for `hv.HeatMap` though: http://holoviews.org/reference/elements/bokeh/HeatMap.html (see bottom of page).
However, I am not able to transfer the code to `hv.Bars`.

**Comment by philippjfr** [comment]
Should be fixed now, closing.

**Comment by weichm** [comment]
Thanks a lot!
