### ISSUE TITLE
Suggested interface for bokeh linked plots

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#194]
I've discussed this issue with Philipp and we've come up with a solution I think we like.

Here are the constraints we want to satisfy for linked plotting:

* We want to keep the compositional nature of HoloViews so you can easily generate a layout containing linked plots with ``+``.
* Bokeh (or any other system supporting linked plots) needs to know which plots are actually showing data from some shared source.

This seems to be conflicting constraints but I think numpy offers a fairly elegant solution: the ``.data`` of the different elements could be numpy array *views* of some underlying data. Slices are examples of easily generated views and you can check the 'base' of the views.

Here are some arrays and slices:

```python
import numpy as np
a = np.array([1,2,3,4])
slice1 = a[0:2]
slice2 = a[2:4]
slice3 = np.array([3,4])
```

Now you can check which slices are from the shared data as follows:

```python
>>> slice1.base is slice2.base, slice1.base is slice3.base
(True, False)
```

Using this method you can find out which elements are linked without changing anything else in HoloViews! However, doing all possible pairwise base comparisons for many elements could get rather expensive: for bokeh plots we could consider a ``bases`` plot option to declare the source bases to check.

**Comment by jbednar** [comment]
I'm only starting to come to terms with what Bokeh offers, but based on what I understand so far, there are two sorts of linking to consider: linking of axes, for panning and zoom, and linking of data points.  I would think that our default behavior should be to link all axes with the same Dimension label, for panning and zooming.  They might be presenting quite different measurements, from different data structures, but if the user has declared them to be in the same dimensions, and put them in the same Layout, that seems like sufficient indication that they are linked, to me.

So I assume your proposal above is for selecting individual data points and ranges by brushing, in which case, yes, it does seem to be important to ensure that they really are the same values across the different plots.  But I'm not sure whether it's safest and most useful to do that in terms of their Numpy-based identity (as above), or in terms of some string label that we've applied to them.  Really not sure about that at all -- Numpy-based array identity seems safe, but I can easily imagine cases where the array data has been copied to some other location in memory but is still the same underlying data.  I would think that we should allow the user an easy way to declare (i.e., state declaratively) that the data is the same (which would allow us to deduce that they should be linked).  You guys are probably thinking more clearly about this than I am, though, and can perhaps explain the nuances involved.

**Comment by jlstevens** [comment]
> I would think that our default behavior should be to link all axes with the same Dimension label, for panning and zooming.

This is very easy to do and Philipp already has a protoype.

You are right this proposal is about linked brushing. I can imagine there are several other ways to declare the linked elements in addition to the suggestion above. Perhaps the best, explicit alternative would be to use type.group.label  match specifications to specify groups that have shared data.

**Comment by jbednar** [comment]
Yes, I thought about type.group.label, but I'm not sure how that would be done.  Just linking any elements that match for all three of those is easy enough, but doesn't seem useful -- e.g. one might have a curve and a bar plot of the same data, which of course you would want to link, but they'll have different types.  And people will often use the label to disambiguate different plots in the same Layout, which again would mess up such linking.  So I imagine you're saying that we could explicitly set up some sort of list of things that we declare are linked, as in link({type1.group1.label1,type2.group2.label2} ), but I'm not sure how that would work in practice.

**Comment by philippjfr** [comment]
To be honest I think it should be controlled as a plot option on the container object you're working with. If ``linked`` or whatever we decide to call it is enabled, it tries to find all the plots that could potentially linked. Doing so by checking whether they are views of the same underlying array is merely the easiest way for the container plot type to detect whether two plots are actually linked but it could do so more robustly by actually comparing the data in each Element. There should probably also be some explicit way to enable this linking but I think generally this will be far too verbose.

I will probably be introducing a new Grid type, which allows heterogenous content fairly soon and I'd suggest this would automatically look for linked data. Once we've got that worked out we could consider expanding this behavior to regular Layouts and Grids. Here is the first prototype of this new grid type, although I will probably not keep the name and all the stuff to construct this grid easily will become an operation:

http://philippjfr.com/work/work-in-progress/gridmatrix/

**Comment by jbednar** [comment]
Personally, I want all such linking to be on by default, for whatever we can discover automatically that should be linked, but if possible to allow users some non-horrible way to specify additional linking we didn't discover, and possibly to turn off specific links we erroneously discovered.  So yes, a plot option to turn the linking on or off, preferably on by default, but that doesn't really address the issue of precisely what to link to what.

The new Grid type looks great. Is this something that was previously possible only using Seaborn (and without linking or interactivity)?

BTW, the Reset button for the new Grid doesn't seem to reset resizing, which seems surprising to me, but that's probably Bokeh rather than HoloViews behavior.

**Comment by philippjfr** [comment]
I think we pretty much agree then.

>The new Grid type looks great. Is this something that was previously possible only using Seaborn (and without linking or interactivity)?

That's correct, this was pandas/seaborn only. It did animate but there was no cross-frame normalization so it was pretty messy to work with.

> BTW, the Reset button for the new Grid doesn't seem to reset resizing, which seems surprising to me, but that's probably Bokeh rather than HoloViews behavior.

Definitely a Bokeh thing, and I agree, reset should reset everything.

**Comment by jlstevens** [comment]
The suggestion to check for numpy views using ``.base`` should enable the automatic behavior we want. As type.group.label is to restrictive, it seems fairly tricky to link elements without adding state to them (which we want to avoid). 

One suggestion is that you could have a ``link`` helper function in plotting that uses the Python ``id`` of the elements to link them. ``link(el1, el2)`` could be equivalent to ``{id(el1):id(el2)}``. This isn't a particularly good solution as it involves memory addresses which won't be consistent across sessions...

Although I agree having an explicit way of defining links would be good, I don't think it would be too much trouble in practice. Linked plots would probably be generated by operations that would make sure numpy slices/views are used appropriately.

**Comment by philippjfr** [comment]
Linking now occurs if two objects draw data from the same object. I'm don't really see the need for adding an explicit link function as it's very straightforward to make sure two Elements draw from the object. Disabling linking can be done very simply via the ``shared_datasource`` plot option. Unless anyone has any objections I'll close this issue.
