### ISSUE TITLE
cant create an area chart with multiple lists

### ISSUE THREAD

**Issue by ajanaliz** [ioam/holoviews#1941]
I'm trying to create an area chart with multiple signals where the number of signals is dynamic and is passed unto the draw function:

here is the code I wrote:

```
import numpy as np

def draw(matrix, indices):
    import numpy as np
    import holoviews as hv
    hv.extension('bokeh')
    dims = dict(kdims=['X'], vdims=['Y'])
    mat = matrix[indices]
    overlay = []
    for i in range(len(indices)):
        overlay.append(hv.Area(mat[i], label=str(i), **dims))
    style = dict(fill_alpha=0.5)
    temp = overlay[0]
    overlays = (temp * overlay[i] for i in range(1,len(overlay)))(style={'Area': style})
    overlays.relabel("Area Chart") + hv.Area.stack(overlays).relabel("Stacked Area Chart")


matrix = np.load("asd.npy")
index = [4, 5, 12]

draw(matrix=matrix, indices=index)
```

this is the error i get:
```
Traceback (most recent call last):
  File "C:/Users/J/PycharmProjects/stockprediction/holoview.py", line 24, in <module>
    draw(matrix=matrix, indices=index)
  File "C:/Users/J/PycharmProjects/stockprediction/holoview.py", line 17, in draw
    overlays = (temp * overlay[i] for i in range(1,len(overlay)))(style={'Area': style})
TypeError: 'generator' object is not callable
```
I would be forever grateful if someone could help me out with this problem.
I was using this guide:
 http://holoviews.org/gallery/demos/bokeh/area_chart.html

Thanks so much
Ali J.

**Comment by jbednar** [comment]
That's some seriously obscure code you've come up with there!  You probably meant something like this?

```
import numpy as np
import holoviews as hv
hv.extension('bokeh')

matrix = np.load("asd.npy")
indices = [4, 5, 12]

style = dict(fill_alpha=0.5)
overlay = hv.Overlay([hv.Area(row) for row in matrix[indices]]).opts(style={'Area': style})
overlay.relabel("Area Chart") + hv.Area.stack(overlay).relabel("Stacked Area Chart")
```

**Comment by jbednar** [comment]
Some suggestions for future work:

- hv.extension should be done once, early in the file; it will get confusing if you do it inside a function.
- Your ``overlays =`` expression created a generator expression because of the parentheses, whereas here you'd want square brackets to create a list comprehension.
- You don't normally need ``for i in range`` unless you're working with numbers directly; instead use a list comprehension as shown here.
