### ISSUE TITLE
colorbar_position=top (or bottom) is badly positioned with bokeh 0.12.9 

### ISSUE THREAD

**Issue by ceball** [ioam/holoviews#1943]
<img width="1169" alt="screen shot 2017-10-01 at 10 26 08 am" src="https://user-images.githubusercontent.com/1929/31053324-f7864254-a692-11e7-8bcc-e90f26823674.png">

Seems to happen with bokeh 0.12.9 for hv 1.8.3, 1.8.4, master (`1.8.4-57-g96ecb1a`). Doesn't happen with bokeh 0.12.7.

Positions left and right seem to be ok, though.

**Comment by philippjfr** [comment]
Thanks, not sure what's going on here, this seems like a regression but I'll have to put together a pure bokeh example to confirm.

**Comment by ceball** [comment]
@philippjfr, have you started that? If not, would you be willing to rephrase your reply to:

> not sure what's going on here, this seems like a regression - could you put together a pure bokeh example to confirm?

**Comment by philippjfr** [comment]
Sure, although it requires some background. Currently we define a number of pre-defined positions for both legends and colorbars, which are declared on ``LegendPlot.legend_specs`` and ``ColorbarPlot.colorbar_specs``. It seems like something changed, causing the colorbar and legend to be shifted compared to where they were in previous versions. While it would be good to track down why this happened it would be nice if bokeh provided a way to set absolute positions for colorbars and legends rather than specifying an offset in pixels.

**Comment by ceball** [comment]
Thanks for the background. I could probably track down what changed, and maybe fix that - but probably no more for now.

**Comment by ceball** [comment]
I think it's a change in bokeh, so I ought to move over to the bokeh issue tracker; do you agree?

0.12.7:
<img width="640" alt="screen shot 2017-10-01 at 4 28 43 pm" src="https://user-images.githubusercontent.com/1929/31056193-c4e265a2-a6c5-11e7-9117-1e0787edc8b5.png">


0.12.9:
<img width="642" alt="screen shot 2017-10-01 at 4 29 01 pm" src="https://user-images.githubusercontent.com/1929/31056198-cda6e456-a6c5-11e7-82a2-9893368bb557.png">


Master:
(will try at some point!)


For this code (minor adaptation from https://bokeh.pydata.org/en/latest/docs/user_guide/annotations.html#color-bars):

```python
import numpy as np

from bokeh.plotting import figure, output_file, show
from bokeh.models import LogColorMapper, LogTicker, ColorBar

output_file('color_bar.html')

def normal2d(X, Y, sigx=1.0, sigy=1.0, mux=0.0, muy=0.0):
    z = (X-mux)**2 / sigx**2 + (Y-muy)**2 / sigy**2
    return np.exp(-z/2) / (2 * np.pi * sigx * sigy)

X, Y = np.mgrid[-3:3:100j, -2:2:100j]
Z = normal2d(X, Y, 0.1, 0.2, 1.0, 1.0) + 0.1*normal2d(X, Y, 1.0, 1.0)
image = Z * 1e6

color_mapper = LogColorMapper(palette="Viridis256", low=1, high=1e7)

plot = figure(x_range=(0,1), y_range=(0,1), toolbar_location=None)
plot.image(image=[image], color_mapper=color_mapper,
           dh=[1.0], dw=[1.0], x=[0], y=[0])

color_bar = ColorBar(color_mapper=color_mapper, ticker=LogTicker(),
                     label_standoff=12, border_line_color=None, location=(0,0), 
                      orientation="horizontal")

plot.add_layout(color_bar, 'above')

show(plot)
```

**Comment by philippjfr** [comment]
Yes, I agree and thanks for chasing that up. I can confirm the same is true using bokeh master.

**Comment by ceball** [comment]
https://github.com/bokeh/bokeh/issues/6993

**Comment by philippjfr** [comment]
Seems fine in 0.12.10, which is what we'll be requiring from now on.

![screen shot 2017-10-27 at 6 47 42 pm](https://user-images.githubusercontent.com/1550771/32117763-5fe2b6c0-bb47-11e7-860f-5d231b5c03c7.png)
