### ISSUE TITLE
colorbar_position=right obscures bokeh tools

### ISSUE THREAD

**Issue by ceball** [ioam/holoviews#1945]
<img width="1155" alt="screen shot 2017-10-01 at 10 37 04 am" src="https://user-images.githubusercontent.com/1929/31053411-86a21368-a694-11e7-9dc8-e26e4fb8ef0a.png">

**Comment by philippjfr** [comment]
Same is true for legends I think. IMO bokeh should automatically shift the toolbar to the top, but that probably won't happen so we should detect if the legend_position or colorbar_position is ``'right'`` and move the toolbar appropriately.

**Comment by jlstevens** [comment]
This has been an annoyance for a long time. I now think it is aggravating enough that a hackish short term fix would be welcome - moving the toolbar doesn't seem *too* hackish as long as we can compute where it should go in a sensible way. 

Of course, the ideal solution would be to improve bokeh: I can't see any situation where having the toolbar appear over the plot is desirable behavior and it would be nice if bokeh could adjust the toolbar position automatically.

**Comment by philippjfr** [comment]
I think this will be fixed for us once https://github.com/bokeh/bokeh/pull/7008 is merged.

**Comment by jlstevens** [comment]
Great! Looking forwards to seeing that.

**Comment by philippjfr** [comment]
Now fixed.

<img width="303" alt="screen shot 2018-06-01 at 6 44 52 pm" src="https://user-images.githubusercontent.com/1550771/40855234-eb061cb8-65cb-11e8-9c3f-7f71a8b42fed.png">
