### ISSUE TITLE
Cant change width and height of output html

### ISSUE THREAD

**Issue by ajanaliz** [ioam/holoviews#1948]
The default overlay size is 300px by 300px but i want something like 800x500.
here is my code:
```
import numpy as np


def draw(matrix, indices):
    import numpy as np
    import holoviews as hv
    hv.extension('bokeh')
    dims = dict(kdims=['X'], vdims=['Y'])
    mat = matrix[indices]
    style = dict(fill_alpha=0.5,width=500,height=500)
    overlay = hv.Overlay([hv.Area(matrix[i], label=str(i)) for i in indices]).opts(style={'Area': style})
    overlay.relabel("Area Chart") + hv.Area.stack(overlay).relabel("Stacked Area Chart")
    doc = hv.renderer('bokeh').server_doc(overlay)


matrix = np.load("asd.npy")
index = [4, 5, 12]

draw(matrix=matrix, indices=index)

```
asd.npy is a 2-D array, and I'm just drawing area plots of some of its indices.
the output I get is 300x300.
also if u could help me simply save the output file as an HTML by simply running the code I would be forever grateful.

**Comment by philippjfr** [comment]
@ajanaliz We make a distinction between ``style`` and ``plot`` options. The style options usually control the look of an element and are passed directly to the plotting extension (in this case bokeh), while plot options control the axes and other options. Try this:

```
style = dict(fill_alpha=0.5)
overlay = hv.Overlay([hv.Area(matrix[i], label=str(i)) for i in indices]).opts(style={'Area': style}, plot=dict(width=500,height=500))
```

**Comment by ajanaliz** [comment]
there is no plot parameter available in hv.overlay.opts(). and I ran this code and it isn't working
