### ISSUE TITLE
operation.contours and Raster

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#195]
Creating contours on a Raster object results in mirrored contours:
![screenshot-1](https://cloud.githubusercontent.com/assets/3776190/8456185/08c760aa-200a-11e5-958a-0b6d11495db9.png)

For an Image, it works ok:
![screenshot-2](https://cloud.githubusercontent.com/assets/3776190/8456209/2ae7fbae-200a-11e5-8f59-9b479c833d6e.png)

version 1.3.0

**Comment by philippjfr** [comment]
Fixed in commit above, closing.
