### ISSUE TITLE
Tap example doesnt update DynamicMap

### ISSUE THREAD

**Issue by pranav0091** [ioam/holoviews#1955]
Source/Example: http://holoviews.org/reference/streams/bokeh/Tap.html#bokeh-gallery-tap

My setup:
Holoviews: 1.8.4
Bokeh: 0.12.4
python: 3.6.0, 3.6.2

The heatmap renders and Curve is initialised correctly, but there is no dynamic update of the associated hv.Curve object. 

It seems that the callback is not getting executed, because if I put a simple print statement within the tap_histogram function, there is only one print seen - the one corresponding to the initial curve (1951, New York)

Please let me know if you need more info or anything else...

Thanks for the great tool, btw :)

**Comment by philippjfr** [comment]
>Bokeh: 0.12.4

Could you try updating to a more recent version of bokeh? We've only recently started declaring the required version, but I recommend just upgrading to 0.12.9 with:

```
conda install -c bokeh bokeh=0.12.9
```

**Comment by pranav0091** [comment]
Thanks for the quick response Philipp.

Updating to the latest bokeh is the firs thing I tried, but for some reason I am not able to. I am using Anaconda. I tried updating past 0.12.4 both automatically (mark for upgrade via GUI) and forcefully (select specific version number) - but both times I get a Dependency-Unsatisfiable error. 

I tried the same steps on python 3.5, 3.6.0, 3.6.2 and on a fresh virtual env, and the issue persisted.

**Comment by pranav0091** [comment]
Actually, I notice that you want me to try the `bokeh` channel. Let me do that. I was using the default channels + conda-forge so far.

**Comment by pranav0091** [comment]
Okay, that installed successfully :) 

And I was even able to get the demo to work, but only after the following ugly edits. 
1. Change the y param in the stream-initialization from a string (name of the state) to a number
``posxy = hv.streams.Tap(source=heatmap, x=23, y=25)``

2. Change the y param for the dataset.select to also handle numeric input
`def tap_histogram(x, y):
    return hv.Curve(dataset.select(State=list(set(dataset['State']))[int(y)], Year=int(1928+x)), kdims=['Week'],
                   label='Year: %s, State: %s' % (x, y))`


I did this because I saw from the DynamicMap title that the x.y to the callback were being passed as floats, and that wasnt working... 

I'm new to Holoviews, so that select looks ugly, will look at this again in the evening to try make it better. :)

**Comment by philippjfr** [comment]
Strange, I suspect the axis was originally categorical and isn't in the latest version for some reason. I'll mark it as a bug and investigate.

**Comment by philippjfr** [comment]
@pranav0091 Thanks for reporting this, I can reproduce. It seems the behavior of tap events on a categorical axis changed in recent versions of bokeh.

**Comment by VolkerH** [comment]
I also ran into this error today and spent several hours trying to figure it out before I found this issue. 
With bokeh version 0.12.7 and holoviews version 1.8.3 I get the following behaviour:

1. The Dynamic map updates exactly once when I click on a box in the heatmap
2. The dynamic map callback receives floating point x and y coordinates rather than years and states (categorical).
 
Before I found the  example notebook I had been playing around with a Selection1D stream on heatmap, hoping that this gives me an index that I can use to get to the correct data source row. 

I want to implement some functionanlity similar to what is presented in the notebook example. As a quick fix is there a combination of holoviews/bokeh versions where the example is known to work ?  Maybe I can downgrade.

**Comment by VolkerH** [comment]
Just upgraded to bokeh version 0.12.9 from the conda bokeh channel. Now the callback doesn't happen at all for me anymore (not even once).

**Comment by philippjfr** [comment]
@VolkerH You need holoviews 1.8.4 for compatibility with bokeh 0.12.9. There's been a lot of API churn in bokeh recently which we've had to keep up with.

**Comment by philippjfr** [comment]
>Maybe I can downgrade.

Unfortunately I think you may have to go all the way back to bokeh 0.12.6. That should work with all recent versions of holoviews in the 1.8.x series.

**Comment by VolkerH** [comment]
Hi Phillip,

thanks for the quick answer.

just upgraded to holoviews 1.8.4 from conda-forge.

Initially I had the same behaviour - the callback only worked once.

Now that I implemented the changes mentioned by @pranav0091 the callback works multiple times. My naive view is that if initialized with a string the callback function somehow breaks after receiving a number - but I don't see any error messages. However, I don't know anything about the inner workings of holoviews and bokeh. 

Might roll back to bokeh 0.12.6. and give that a try.

**Comment by philippjfr** [comment]
>My naive view is that if initialized with a string the callback function somehow breaks after receiving a number

That's exactly right.

>but I don't see any error messages

You only get exceptions for errors that occur during initialization, errors that occur when interacting with a plot end up in the browser JS console. We've debated making these louder somehow but haven't come up with a good solution yet.

**Comment by philippjfr** [comment]
I've now merged a fix in HoloViews that addresses this issue, which will land in 1.9.

**Comment by VolkerH** [comment]
@philippjfr Thanks a lot !
