### ISSUE TITLE
Polygons limited to 1 vdim

### ISSUE THREAD

**Issue by jvivian** [ioam/holoviews#1963]
The bounds on `vdims` for `hv.Polygons` is (1, 1) which I don't quite understand as other plots like `hv.Scatter` have no upper bound.

I'm recreating the [texas choropleth example](http://holoviews.org/gallery/demos/bokeh/texas_choropleth_example.html) but I need more than 1 vdim so that when a user hovers over a Polygon they can see raw values that contextualize the normalized value I'm using for the heatmap levels.  I might just be using `hv.Polygons` wrong, so if there is a way to add more visual dimensions let me know and I'll close this issue.

Thanks!

**Comment by philippjfr** [comment]
We've recently refactored the data interface behind Path/Polygons and can now support multiple dimensions. Supporting this is one of the major outstanding features for the 1.9 release, so hopefully I'll have an update on this soon.

**Comment by jvivian** [comment]
@philippjfr — You rule! I guess close this if you feel its resolved or wait until 1.9.

**Comment by philippjfr** [comment]
If you're plotting choropleths, then using the [geopandas interface](https://github.com/ioam/geoviews/pull/88) that I'm working in geoviews on will probably the easiest thing.

**Comment by philippjfr** [comment]
The PR was just merged Path, Contours and Polygon now support arbitrary numbers of value dimensions.
