### ISSUE TITLE
Bokeh grid lines

### ISSUE THREAD

**Issue by rymurr** [ioam/holoviews#1967]
Not sure if bokeh has changed the default way they draw grid lines but I noticed that `show_grid=True` in opts no longer has any effect for me (holoviews 1.8.4 and bokeh 0.12.6). The following change fixes it but I wanted to make sure I wasn't crazy first and confirm that someone else is having this problem. This doesn't give much control over the grid shown though 😞 

in `holoviews/plotting/bokeh/element.ElementPlot._update_plot` change

```python         
if not self.show_grid:
            plot.xgrid.grid_line_color=None
            plot.ygrid.grid_line_color=None
```
to

```python         
if self.show_grid:
            plot.xgrid.grid_line_color='black'
            plot.ygrid.grid_line_color='black'
```

Thoughts? Is there a better/easier way to get grid lines or should I raise a PR?

**Comment by carlodri** [comment]
I can confirm that `show_grid=True` does nothing for me as well with bokeh backend.

**Comment by philippjfr** [comment]
Sorry I never replied to this, I'll investigate now and we should have a fix for 1.9.2. For the 1.10 release we can brainstorm an approach that provides some more control over the gridlines.

**Comment by philippjfr** [comment]
@rymurr @carlodri Could you provide an example? I can't seem to reproduce an issue with ``show_grid`` using holoviews 1.9.1 and bokeh 0.12.11.

**Comment by jlstevens** [comment]
I had a go at reproducing this issue and failed:

![image](https://user-images.githubusercontent.com/890576/33852900-043ea49c-deb4-11e7-9e6e-f06f8a2f8c4e.png)

I tried various elements and gridlines always seemed to work as expected.

There might well still be a bug though without a simple example to try and reproduce, it is hard to track down. For this reason I'm bumping this issue to the next milestone.

**Comment by rymurr** [comment]
It has been a while since I looked at this but it was only happening on the bokeh server. Worked fine in the notebook. This was on bokeh 0.12.6

**Comment by philippjfr** [comment]
Thanks, that's helpful!

**Comment by philippjfr** [comment]
It is now possible to set an explicit gridstyle which is documented in the plotting with bokeh user guide.
