### ISSUE TITLE
Sum across an axis

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#197]
I think this was covered in the Transforming Data tutorial, but since that's not yet up on the website, can you please show how to make a Curve out of an Image by summing across a specified axis?

**Comment by philippjfr** [comment]
I'll be uploading an initial draft of Transforming Data I and II tonight. However as a quick summary:

```python
img = hv.Image(np.random.rand(10,10))
img + img.reduce(x=np.mean).to.curve() + img.reduce(['x'], np.mean).to.curve()
```

The two reduce signatures there are equivalent.

**Comment by jbednar** [comment]
Thanks!  Conversely, is there a way to combine multiple Curve or Image objects so that they are not overlaid, but instead their data sums (or is combined via some other operator)?

**Comment by philippjfr** [comment]
Yes, that's the ``collapse`` operation on a HoloMap, e.g.:

```python
(hv.HoloMap({i: hv.Image(np.random.rand(10,10)) for i in range(5)},
           kdims=['A']).collapse(['A'], np.mean) +
hv.HoloMap({i: hv.Curve(np.linspace(0,1,11)) for i in range(5)},
           kdims=['A']).collapse(['A'], np.add))
```

**Comment by jbednar** [comment]
Thanks.  But what if they are not in a HoloMap, just three separate Image or Curve objects I've created independently (but with the same dimensions)?  Do I have to create a HoloMap with some dummy dimension (just an index?) for each element, and then collapse across it?  That seems a bit awkward, but maybe it's ok in practice.

**Comment by philippjfr** [comment]
Currently no way around it unfortunately. I could probably write a simple ``collapse`` operation that would do the equivalent for an ``Overlay`` of arbitrary Elements. Then you could just do:

```python
collapse(img1 * img2 * img3)
```

**Comment by jbednar** [comment]
Ok, that would be good, even if it just creates a temporary HoloMap and then collapses it.  Of course, it should accept the same operator argument that HoloMap.collapse() does.

**Comment by jbednar** [comment]
Is there a reason to prefer the version you listed above:

``
results.reduce(['A'], np.mean).to.curve())
``

 to:

``
hv.Curve(results.reduce(['A'], np.mean))
``

The second version seems more explicit and obvious, to me.

**Comment by philippjfr** [comment]
True, the second version is probably preferable now, it's new so I didn't think of it right away. The ``.to``  based conversion interface is useful when you want to shuffle the dimensions.

**Comment by jbednar** [comment]
Ok, thanks.  I guess this can be closed once operator.collapse() is implemented.

**Comment by jbednar** [comment]
I guess the homepage example should now use Points(...) instead of to.points() as well?  That would seem clearer, but maybe in that case you do need to shuffle the dimensions.

**Comment by vascotenner** [comment]
philipppfjr: 
> Notice The problem is that currently it does not know how to use binary operators like np.add. If you use a numpy ufunc, in this case you'd want to use np.sum, this should work.

**Comment by vascotenner** [comment]
Better do:
```hv.Curve(results.reduce(A=np.mean))```

**Comment by vascotenner** [comment]
@philippjfr : Do you have any plans for uploading the transforming data tutorials in the near future?

**Comment by philippjfr** [comment]
Yes, got a bit swamped recently and that tutorial has now been split in two. I can upload the first half about selecting, sampling etc. very soon as it's mostly ready. The second half about reduce, collapse and operations still needs some work though and the API also needs some tweaking to make it consistent too (mostly based on your helpful feedback).

**Comment by philippjfr** [comment]
Just added a general ``collapse`` operation that will apply collapse to an Overlay or NdOverlay.

hv.operation.collapse(img1 * img2 * img3, fn=np.mean)

That should work for any Element type that implements it now.

**Comment by jbednar** [comment]
Thanks!  Please update any place this usage appears in the tutorials, so that people are aware of the new and better way to do it.

**Comment by philippjfr** [comment]
It doesn't currently appear anywhere, probably falls within the scope of the Transforming Data tutorial that still doesn't exist.
