### ISSUE TITLE
User guide 14-Dashboards.ipynb fails with ActiveHTMLWidget AttributeError: object has no ... 'name'

### ISSUE THREAD

**Issue by ivarzap** [ioam/holoviews#1974]
From the holoviews/examples/user_guide/15-Dashboards.ipynb,
the last cell fails when executed as:
![image](https://user-images.githubusercontent.com/25571178/31288826-c7141a50-aac6-11e7-99d6-97ce75511680.png)

**Comment by philippjfr** [comment]
Thanks for reporting this @ivarzap. Probably an issue with ipywidgets 7.0, I'd recommend downgrading to 6.0 for the time being.

**Comment by victor302** [comment]
@philippjfr: Thanks for your advice. I was trying to follow it and downgraded ipywidgets to 6.0.1. However then I got another error: AttributeError: 'BokehRenderer' object has no attribute 'figure_data':

`AttributeError                            Traceback (most recent call last)
<ipython-input-9-2bd39c91d6f6> in <module>()
      1 explorer = AdvancedStockExplorer()
----> 2 paramnb.Widgets(explorer, continuous_update=True, callback=explorer.event, on_init=True)

/usr/local/lib/python3.5/dist-packages/param/parameterized.cpython-35m-x86_64-linux-gnu.so in param.parameterized.ParameterizedFunction.__new__()

/usr/local/lib/python3.5/dist-packages/paramnb/__init__.py in __call__(self, parameterized, **params)
    163 
    164         if self.p.on_init:
--> 165             self.execute()
    166 
    167 

/usr/local/lib/python3.5/dist-packages/paramnb/__init__.py in execute(self, changed)
    282         if self.p.callback is not None:
    283             if get_method_owner(self.p.callback) is self.parameterized:
--> 284                self.p.callback(**changed)
    285             else:
    286                 self.p.callback(self.parameterized, **changed)

<ipython-input-8-e79a92dc6c46> in event(self, **kwargs)
      7     def event(self, **kwargs):
      8         if self.output is None or 'variable' in kwargs:
----> 9             self.output = self.view()
     10         else:
     11             super(AdvancedStockExplorer, self).event(**kwargs)

/usr/local/lib/python3.5/dist-packages/paramnb/view.py in __set__(self, obj, val)
     22         obj_id = id(obj)
     23         if obj_id in self.callbacks:
---> 24             self.callbacks[obj_id](self.renderer(val))
     25 
     26 

<ipython-input-7-678eafbd2705> in render(obj)
      3     plot = renderer.get_plot(obj)
      4     size = renderer.get_size(plot)
----> 5     return renderer.figure_data(plot), size

AttributeError: 'BokehRenderer' object has no attribute 'figure_data'`

**Comment by philippjfr** [comment]
I'll have to update the tutorial, try changing that to ``renderer._figure_data(plot)``.

**Comment by victor302** [comment]
Thank you. Now it works.

**Comment by philippjfr** [comment]
Fixed in https://github.com/ioam/holoviews/pull/2122.
