### ISSUE TITLE
Can't control Bokeh toolbar for Layouts

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#1977]
![image](https://user-images.githubusercontent.com/1695496/31304516-46b888b0-aae8-11e7-9620-f296fc834983.png)
![image](https://user-images.githubusercontent.com/1695496/31304518-4bcee556-aae8-11e7-96a3-3c8be4fcbfa7.png)

@philippjfr suggests the same issue may also apply to Grids.

**Comment by ceball** [comment]
I edited the title, because it's also not possible to specify that e.g. the toolbar should be to the left.

**Comment by philippjfr** [comment]
Now implemented.
