### ISSUE TITLE
Update link to IPython notebook on homepage

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#198]
The homepage's link to ipython.org/notebook is broken.  I thought there was now automatic link checking to catch such things?

**Comment by jlstevens** [comment]
Fixed in d2db703

I'll run the link checker now. Sadly this isn't an automatic step yet, just a recommended check after release. That said, I am hoping that with the new version string handling, we should have far fewer broken links in future!

**Comment by philippjfr** [comment]
This should now link to Jupyter notebooks.

**Comment by jlstevens** [comment]
Fixed in the PR referenced above. Closing.
