### ISSUE TITLE
Better exception handling for Dataset types

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#1986]
I've been thinking about how we can improve validation and exception handling for ``Dataset`` types for quite a while and have come up with a proposal that I think will work. First let me outline what the current issues are and then suggest how to address them.

The current approach iterates over the defined interfaces, if the type of the data matches the type of one of the declared interfaces it will prioritize that interface and then try all the other interfaces one by one. Since it goes through each interface one by one we can't raise the exception raised by any particular interface.

My proposal is that we add pre-validation that can raise exceptions before actually trying to initialize an interface. The ``Interface`` baseclass will implement pre-validation for all the basic literal types (tuples, dictionaries, lists of coordinates) and concrete interfaces implements pre-validation for any other types.

**Comment by jbednar** [comment]
I think [this SO issue](https://stackoverflow.com/questions/46666629/holoviews-gridded-dataset-example-how-to-create-dataset-from-2d-image-numpy-a/46695072) is an example of why we need something like this approach.

**Comment by philippjfr** [comment]
Going to close this as it is superseded by a simpler approach implemented in https://github.com/ioam/holoviews/pull/2041.
