### ISSUE TITLE
Aspect differs for Images in Layouts

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#199]
If I have an Image with a non-square bounds, it is plotted as a square when it's embedded in a Layout, but as a rectangle when it's on its own:

``` python
import numpy as np
from holoviews import Image

x,y = np.mgrid[-50:51, -50:51] * 0.1
bounds=(-1,0,1,1) 

ims = (Image(np.sin(x**2+y**2),   bounds=bounds) 
       + Image(np.sin(x**2+y**2), bounds=bounds)[-0.5:0.5, -0.5:0.5])

ims
```

![image](https://cloud.githubusercontent.com/assets/1695496/8465649/72c5ed44-2011-11e5-9474-20423cacc826.png)

``` python
ims.Image.I
```

![image](https://cloud.githubusercontent.com/assets/1695496/8465659/8c06118a-2011-11e5-96bb-1ae3a7fea25a.png)

Is that deliberate?  It was very surprising.

**Comment by philippjfr** [comment]
No, I think Layouts still set Elements to be square by default, will have to remove that.
