### ISSUE TITLE
Normalization and overlays

### ISSUE THREAD

**Issue by nbren12** [ioam/holoviews#1990]
This is related to #1720 and #1906.

I have been trying to figure out how to change the ylimits of individual elements in a layout to match the observed range of the data automatically, and I am having a lot of difficulty figuring out how "normalization" and the `shared_axes` options interact. Is there an equivalent of  the `sharex` and `sharey` matplotlib options?

I was able to get to independently scaled axes using `+axiswise` and `shared_axes=False`, but when I try to make a layout of overlayed elements the axes are not scaled properly anymore. Please see [this notebook](http://nbviewer.jupyter.org/urls/gist.githubusercontent.com/nbren12/bfd39af3a7bfc82415c78fee656cd9cb/raw/ad5be3f3c2c96c32c4bccb3219d58c5afafd8d9d/normalization.ipynb). 

Edit: updated link

**Comment by nbren12** [comment]
After more fiddling it appears this problem only occurs with bokeh.

**Comment by philippjfr** [comment]
As far as I can tell this issue no longer occurs on master. Not quite sure why yet though, so I'll keep this open.

**Comment by nbren12** [comment]
I think you are right. After `pip install --upgrade git+https://github.com/ioam/holoviews@master` it worked as expected.

**Comment by jlstevens** [comment]
Glad to hear it is now working for you!

I'll go ahead and close the issue but if you have any further problems, I'm happy to re-open it. We have issue #1720 to remind us to improve the documentation regarding normalization.
