### ISSUE TITLE
Labels not inherited from Element conversions

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#200]
Shouldn't converting one element type to another inherit the label (and presumbly group, though I haven't tested that)?

```python
import numpy as np
from holoviews import Curve, Scatter
%load_ext holoviews.ipython
points = [(0.1*i, np.sin(0.1*i)) for i in range(100)]
c=Curve(points,label="The data")
s=Scatter(c)
c+s
```

It doesn't, at least not for Scatter(Curve()) or Surface(Image()):

![image](https://cloud.githubusercontent.com/assets/1695496/8487518/298398e0-20d2-11e5-80a7-7b7ecea8639c.png)

**Comment by philippjfr** [comment]
Fixed in d05ff2e. Closing.
