### ISSUE TITLE
Compatibility with bokeh 0.12.10

### ISSUE THREAD

**Issue by fgoinai** [ioam/holoviews#2005]
I followed the instruction on [here](http://holoviews.org/#installation), and copy the code in examples to a separate file to do some testing, however it only shows:
```
WARNING:root:notebook_extension: HoloViews bokeh backend could not be imported, ensure bokeh is installed.

Traceback (most recent call last):
  File ".../holoview_test/just_test/test.py", line 4, in <module>
    hv.extension('bokeh')
  File "...\AppData\Local\Continuum\Anaconda3\envs\holoviews\lib\site-packages\param\parameterized.py", line 1888, in __new__
    return inst.__call__(*args,**params)
  File "...\AppData\Local\Continuum\Anaconda3\envs\holoviews\lib\site-packages\holoviews\ipython\__init__.py", line 109, in __call__
    super(notebook_extension, self).__call__(*args, **params)
  File "...\AppData\Local\Continuum\Anaconda3\envs\holoviews\lib\site-packages\holoviews\util\__init__.py", line 248, in __call__
    raise ImportError('None of the backends could be imported')

ImportError: None of the backends could be imported
```
My env:
**OS**: Win7 Pro SP1 x64
**Python**: 3.5.4
**Package**:
- alabaster==0.7.10
- anaconda-client==1.6.5
- anaconda-navigator==1.6.8
- anaconda-project==0.8.0
- asn1crypto==0.22.0
- astroid==1.5.3
- astropy==2.0.2
- babel==2.5.0
- backports.shutil-get-terminal-size==1.0.0
- beautifulsoup4==4.6.0
- bitarray==0.8.1
- bkcharts==0.2
- blaze==0.11.3
- bleach==2.0.0
- bokeh==0.12.10
- boto==2.48.0
- Bottleneck==1.2.1
- CacheControl==0.12.3
- certifi==2017.7.27.1
- cffi==1.10.0
- chardet==3.0.4
- click==6.7
- cloudpickle==0.4.0
- clyent==1.2.2
- colorama==0.3.9
- comtypes==1.1.2
- contextlib2==0.5.5
- cryptography==2.0.3
- cycler==0.10.0
- Cython==0.26.1
- cytoolz==0.8.2
- dask==0.15.2
- datashape==0.5.4
- decorator==4.1.2
- distlib==0.2.5
- distributed==1.18.3
- docutils==0.14
- entrypoints==0.2.3
- et-xmlfile==1.0.1
- fastcache==1.0.2
- filelock==2.0.12
- Flask==0.12.2
- Flask-Cors==3.0.3
- gevent==1.2.2
- glob2==0.5
- greenlet==0.4.12
- h5py==2.7.0
- heapdict==1.0.0
- holoviews==1.8.3
- html5lib==0.999999999
- idna==2.6
- imageio==2.2.0
- imagesize==0.7.1
- ipykernel==4.6.1
- ipython==6.1.0
- ipython-genutils==0.2.0
- ipywidgets==7.0.0
- isort==4.2.15
- itsdangerous==0.24
- jdcal==1.3
- jedi==0.10.2
- Jinja2==2.9.6
- jsonschema==2.6.0
- jupyter-client==5.1.0
- jupyter-console==5.2.0
- jupyter-core==4.3.0
- jupyterlab==0.27.0
- jupyterlab-launcher==0.4.0
- lazy-object-proxy==1.3.1
- llvmlite==0.20.0
- locket==0.2.0
- lockfile==0.12.2
- lxml==3.8.0
- MarkupSafe==1.0
- matplotlib==2.0.2
- mccabe==0.6.1
- menuinst==1.4.8
- mistune==0.7.4
- mpmath==0.19
- msgpack-python==0.4.8
- multipledispatch==0.4.9
- navigator-updater==0.1.0
- nbconvert==5.3.1
- nbformat==4.4.0
- networkx==1.11
- nltk==3.2.4
- nose==1.3.7
- notebook==5.0.0
- numba==0.35.0+10.g143f70e
- numexpr==2.6.2
- numpy==1.13.1
- numpydoc==0.7.0
- odo==0.5.1
- olefile==0.44
- openpyxl==2.4.8
- packaging==16.8
- pandas==0.20.3
- pandocfilters==1.4.2
- param==1.5.1
- partd==0.3.8
- path.py==10.3.1
- pathlib2==2.3.0
- patsy==0.4.1
- pep8==1.7.0
- pickleshare==0.7.4
- Pillow==4.2.1
- pkginfo==1.4.1
- plotly==2.1.0
- ply==3.10
- progress==1.3
- prompt-toolkit==1.0.15
- psutil==5.2.2
- py==1.4.34
- pycodestyle==2.3.1
- pycosat==0.6.2
- pycparser==2.18
- pycrypto==2.6.1
- pycurl==7.43.0
- pyflakes==1.5.0
- Pygments==2.2.0
- pylint==1.7.2
- pyodbc==4.0.17
- pyOpenSSL==17.2.0
- pyparsing==2.2.0
- PySocks==1.6.7
- pytest==3.2.1
- python-dateutil==2.6.1
- pytz==2017.2
- PyWavelets==0.5.2
- pywin32==221
- PyYAML==3.12
- pyzmq==16.0.2
- QtAwesome==0.4.4
- qtconsole==4.3.1
- QtPy==1.3.1
- requests==2.18.4
- rope==0.10.5
- ruamel-yaml==0.11.14
- scikit-image==0.13.0
- scikit-learn==0.19.0
- scipy==0.19.1
- seaborn==0.8
- simplegeneric==0.8.1
- singledispatch==3.4.0.3
- six==1.10.0
- snowballstemmer==1.2.1
- sortedcollections==0.5.3
- sortedcontainers==1.5.7
- Sphinx==1.6.3
- sphinxcontrib-websupport==1.0.1
- spyder==3.2.3
- SQLAlchemy==1.1.13
- statsmodels==0.8.0
- sympy==1.1.1
- tables==3.4.2
- tblib==1.3.2
- testpath==0.3.1
- toolz==0.8.2
- tornado==4.5.2
- traitlets==4.3.2
- typing==3.6.2
- unicodecsv==0.14.1
- urllib3==1.22
- wcwidth==0.1.7
- webencodings==0.5.1
- Werkzeug==0.12.2
- widgetsnbextension==3.0.2
- win-inet-pton==1.0.1
- win-unicode-console==0.5
- wincertstore==0.2
- wrapt==1.10.11
- xlrd==1.1.0
- XlsxWriter==0.9.8
- xlwings==0.11.4
- xlwt==1.3.0
- zict==0.1.2

**Comment by philippjfr** [comment]
@fgoinai Thanks for reporting this. The recent bokeh release introduced some changes which are incompatible with 1.8.4. We will be releasing a 1.8.5 hotfix release asap, in the meantime you can downgrade to bokeh 0.12.9 or upgrade to holoviews 1.9.0dev3.

**Comment by fgoinai** [comment]
Thanks a lot, it works on bokeh==0.12.9

**Comment by stonebig** [comment]
where is  holoviews-1.9.0dev3 ? I don't see it on github tags

**Comment by jlstevens** [comment]
We have a new release process for dev releases coming up where we will be making such tags. In the meantime, you can grab it using:

```
conda install -c ioam/label/dev holoviews
```

**Comment by ispmarin** [comment]
Having the same issue. Is there a way to install the dev version using Pip?

**Comment by jakirkham** [comment]
So is this fixed in `master`? Meaning is `bokeh` 0.12.10 now fully supported in `master`. I tried downgrading to `bokeh` 0.12.9 and got a message telling me that I needed at least `bokeh` 0.12.10.

**Comment by philippjfr** [comment]
That's right, 0.12.10 is now supported and required on master. Bokeh has tightened declared a fair amount of their API as stable so we decided it was a good point to drop our backward compatibility.

**Comment by makn87** [comment]
When I try  to install with conda using
 conda install -c ioam/label/dev holoviews

I get the message that bokeh will be downgraded to 12.9
This happens for both 2.7 and 3.6

**Comment by philippjfr** [comment]
@makn87 I should have closed this issue now, version 1.9 of holoviews has been released so just install that using:

    conda install -c ioam holoviews

OR

    conda install -c conda-forge holoviews

**Comment by StrausMG** [comment]
Hi! It seems that on the "ioam" channel it's still 1.8.4, so I have just accomplished the whole quest from the official documentation to this issue. Probably it's worth fixing?
P.S. On the "conda-forge" it's 1.9.1 and I had no problems with bokeh.

**Comment by StrausMG** [comment]
Oh, sorry, you're right. I usually use pip and I didn't know that conda needed to be up-to-date.

**Comment by philippjfr** [comment]
No problem at all, this also confused me frequently. Technically older versions of conda also work but you have to explicitly declare the version you need.

**Comment by StrausMG** [comment]
Probably, it's worth mentioning in the installation instructions on the start page of HoloViews?
