### ISSUE TITLE
Allow setting the Bokeh title color

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#2008]
Unfortunately, it seems to be forced to black which means this option isn't exposed in HoloViews and can't be rectified by setting a Bokeh style..

**Comment by philippjfr** [comment]
I think this should be done as in the context of a general``fontstyle`` option, which has already been suggested in https://github.com/ioam/holoviews/issues/526. So I'll close this as a duplicate and punt to v1.11.
