### ISSUE TITLE
Invalid options should warn instead of preventing display

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#201]
Now that we can switch backends, there is a problem with how invalid options supplied to the ``%opts`` magic are handled (actually this affects how ``OptionTrees`` are processed in general). Currently, an HTML message is generated to inform the user that a supplied option was invalid.

Now, if the backend is changed, the valid style/plot options are also likely to change. This means, that many plots won't display at all due to the invalid option messages. The proposed solution is to ignore the options that are invalid, generate a warning about the options which were ignored and still show the available display output.

Note that this issue mostly applies to style options: I think we should highly recommend that plot options stay as consistent as possible between backends as we implement them!

**Comment by jbednar** [comment]
I strongly support this change.  It would be good if the message listing the ignored options could include a statement of how to use the logging module to supress the warnings, in case people want to happily put in hints that are useful for some backends but not known for others.

I agree that it would be good practice to support the same plot options (and to clarify that the principle is not just highly recommended (which sounds like it's up to external users to ensure) but is something that is true as far as we can make it (i.e., it's up to the backend maintainers).

**Comment by jlstevens** [comment]
I've finally gotten round to implementing this improvement in dc66a8b.

As typical when working with ``OptionTrees``, even this simple change exposed some incorrect behavior that was fairly tricky to debug (namely lack of keyword validation when building custom option trees). That particular issue has now been fixed in 58b8a26.

> It would be good if the message listing the ignored options could include a statement of how to use the logging module to supress the warnings, in case people want to happily put in hints that are useful for some backends but not known for others.

I agree this would be a nice feature but I don't think the logging module will offer much granularity - if you match on the start of the warning message (i.e 'Invalid option ...') you'll suppress all such warnings. Any more specific string matching is bound to be extremely brittle. 

This suggests that ``skip_and_warn``  is not as flexible as it should be and should be split into two flags which I'll do now...

**Comment by jlstevens** [comment]
Since 6bc4543 there are now two boolean parameters on ``Options`` (only settable at the class level to avoid limiting the set of possible keywords): ``skip_invalid`` and ``warn_on_skip``. The former is now enabled by default so invalid keywords are skipped instead of raising an exception. The latter is useful to disable all such warnings if you are switching backends a lot:

```python
hv.Options.warn_on_skip=False
```

**Comment by jbednar** [comment]
Sounds great, thanks!  I'll try it out on various notebooks and reopen the issue if I have problems.
