### ISSUE TITLE
ImportError: cannot import name '_event_for_attribute_change'

### ISSUE THREAD

**Issue by rnsaway** [ioam/holoviews#2010]
from bokeh.document.util import _event_for_attribute_change
ImportError: cannot import name '_event_for_attribute_change'

source code, bokeh 12.10 imported...

'''
```
import matplotlib as mpl
import holoviews.plotting.bokeh
import holoviews as hv
hv.extension('bokeh')
```

'''
doing this via django...

**Comment by philippjfr** [comment]
The recent bokeh release introduced some changes which are incompatible with 1.8.4. We will be releasing a 1.8.5 hotfix release asap, in the meantime you can downgrade to bokeh 0.12.9 or upgrade to holoviews 1.9.0dev3. See #2005 for more detail.
