### ISSUE TITLE
Dimension re-ordering in gridded data

### ISSUE THREAD

**Issue by agvaughan** [ioam/holoviews#2016]
I was playing around with gridded datasets, and found a bug that seems to reverse-index the dimensions of any 3D array passed as data.  The result is either a weird re-ordering of dimensions (if dimension sizes are equal), or failure (if dimension sizes are not equal).

To reproduce, here's code adapted from http://holoviews.org/getting_started/Gridded_Datasets.html
```
import numpy as np
import pandas as pd
import bokeh
import holoviews as hv
hv.extension('matplotlib','bokeh')

#data = np.random.rand(10,10,10)    # This works!
data = np.random.rand(11,11,10)     # This doesn't!

ds = hv.Dataset( 
    (np.arange(data.shape[0]),
     np.arange(data.shape[1]),
     np.arange(data.shape[2]),
     data),
    kdims=['x','y','z'], vdims=['Fluorescence'])

%opts Image (cmap='viridis')
ds.to(hv.Image, ['x', 'y'])
```

Two changes seem to fix this problem:

(1) xarray.py
```
- 76            coords = [(kd.name, data[kd.name]) for kd in kdims][::-1]
+ 76            coords = [(kd.name, data[kd.name]) for kd in kdims]
```

This alleviates an issue in dataarray.py (line 87) where we generate new_coords from a zip(dims,coords).  Here dims is in the original order, and coords is reversed becasue of the [::-1] above.

(2) grid.py
```
- 336        int_inds = [np.argwhere(v) for v in value_select] [::-1]
+ 336       int_inds = [np.argwhere(v) for v in value_select]  
```

This alleviates an error at 
`340            data[vdim.name] = dataset.data[vdim.name][index]`
where int_inds will index via the wrong dimensions.

With both of these changes, the plot succeeds.  I'm reluctant to file this as a simple pull request, because I assume that the list reversals above had some purpose.  

But the current behavior seems sub-optimal. Thoughts?

**Comment by philippjfr** [comment]
Perhaps the documentation is not quite clear on this but the array should be indexed in the reverse order in which dimensions are defined matching the numpy convention of indexing first by ``row`` and then by ``column`` (corresponding to the y- and x-axis of an Image for instance). If you invert the coordinate arrays, everything works out fine:

```
import numpy as np
import pandas as pd
import bokeh
import holoviews as hv
hv.extension('matplotlib','bokeh')

data = np.random.rand(11,11,10)

ds = hv.Dataset( 
    (np.arange(data.shape[2]),
     np.arange(data.shape[1]),
     np.arange(data.shape[0]),
     data),
    kdims=['x','y','z'], vdims=['Fluorescence'])

%opts Image (cmap='viridis')
ds.to(hv.Image, ['x', 'y'])
```

**Comment by agvaughan** [comment]
Gotcha, thanks!

**Comment by philippjfr** [comment]
This now appropriately raises an informative error message:

>DataError: Key dimension values and value array Fluorescence shapes do not match. Expected shape (10, 11, 11), actual shape: (11, 11, 10)

So I think we can close.
