### ISSUE TITLE
can't find matplotlib renderer with HoloViews 1.3.1

### ISSUE THREAD

**Issue by lebedov** [ioam/holoviews#202]
Using HoloViews 1.3.1 installed via conda with Python 2.7.10 and matplotlib 1.4.3 already installed, I was unable to run the [Style I example](https://github.com/ioam/holoviews/wiki/HoloViews-without-IPython#style-i-applying-your-chosen-options-while-saving) of using HoloViews without IPython because `Store.renderers['matplotlib']` evidently was empty. Was there some change in how to render HoloViews-generated graphics without IPython in the latest version?

**Comment by lebedov** [comment]
(I can manually create and use an instance of `holoviews.plotting.mpl.renderer.MPLRenderer`.)

**Comment by philippjfr** [comment]
Thanks for reporting this. The problem was that without importing from plotting none of the plotting backends are registered, I've updated the Wiki to fix this issue.

**Comment by lebedov** [comment]
Looks good - thanks.
