### ISSUE TITLE
issue with fractal example on Windows, Python3.4, scipy 0.16.0rc1 , numpy 

### ISSUE THREAD

**Issue by stonebig** [ioam/holoviews#203]
If It try this example on Windows, Python3.4, scipy 0.16.0rc1 , numpy  1.9.2, pandas 0.16.2 ... I get an error (on holoviews 1.3.1)
````
# http://ioam.github.io/holoviews/
from holoviews import *
%load_ext holoviews.ipython
fractal = image

((fractal * HLine(y=0)).hist() + fractal.sample(y=0))
````

````
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-2435340733f0> in <module>()
      3 fractal = Image(np.load(r'D:\result_tests\winpython-3.4.3.3\notebooks\docs\mandelbrot.npy'))
      4 
----> 5 ((fractal * HLine(y=0)).hist() + fractal.sample(y=0))

D:\WinPython\basedir34\build\winpython-3.4.3.5build1.amd64\python-3.4.3.amd64\lib\site-packages\holoviews\core\overlay.py in hist(self, index, adjoin, **kwargs)
     49             raise TypeError("Please supply a suitable index or label for the histogram data")
     50 
---> 51         hist = self.get(index).hist(adjoin=False, **kwargs)
     52         if adjoin:
     53             layout = self << hist

D:\WinPython\basedir34\build\winpython-3.4.3.5build1.amd64\python-3.4.3.amd64\lib\site-packages\holoviews\core\overlay.py in get(self, identifier, default)
    113             values = self.data.values()
    114             if 0 <= identifier < len(values):
--> 115                 return self.data.values()[identifier]
    116             else:
    117                 return default

TypeError: '_OrderedDictValuesView' object does not support indexing

````

**Comment by stonebig** [comment]
seems a python 3 problem:
http://stackoverflow.com/questions/17431638/get-typeerror-dict-values-object-does-not-support-indexing-when-using-python

**Comment by philippjfr** [comment]
Great thanks for reporting this. I've just pushed the fix and we'll be releasing v1.3.2, which will include this fix, in the next hour or so.

**Comment by stonebig** [comment]
and how do you generate that mandelbrot.npy ?

**Comment by philippjfr** [comment]
Sorry should have addressed that, it's available [here](https://github.com/ioam/holoviews/raw/master/doc/mandelbrot.npy) and we've added a link to it on the main website, which will appear once it's rebuilt.

**Comment by stonebig** [comment]
the code I mean, not the (heavy for a disribution) result file

**Comment by jbednar** [comment]
You can get it from https://github.com/ioam/holoviews/blob/master/doc/mandelbrot.npy , and it is included with the downloadable set of tutorials (currently at http://ioam.github.io/holoviews/Tutorials/notebooks-1.3.1.zip).

**Comment by jbednar** [comment]
The code is in a comment in https://raw.githubusercontent.com/ioam/holoviews/master/doc/index.rst .

**Comment by jbednar** [comment]
BTW, I've suggested before that we distribute it as .npz, not .npy, which should be a lot smaller.

**Comment by stonebig** [comment]
thanks, trying to see how many minutes it means

**Comment by jlstevens** [comment]
I should warn you that this code originally came from a numpy recipe that isn't optimized at all. It may take a minute or two to run.

I actually have a blog post about how this was generated for the personal website I have been working on (under construction!): [My blog post](http://jlstevens.github.io/introducing-holoviews.html)

**Comment by jbednar** [comment]
The blog post looks great.  It should be linked from the Examples section of the HoloViews site...

**Comment by stonebig** [comment]
this is 10 seconds on my old pc, by removing 40x computations + using numba.
I guess I could use my previous mandelbrot and cython with some tweaks, as numba is not everybody's taste
````
`import numpy as np
from numba import autojit
@autojit
def mandelbrot( h,w, maxit=200 ):
   y,x = np.ogrid[ -1.4:1.4:h*1j, -2:0.8:w*1j ]
   c = x+y*1j
   z = c
   divtime = maxit + np.zeros(z.shape, dtype=int)
   for i in range(maxit):
       z  = z**2 + c
       diverge = z*np.conj(z) > 2**2
       div_now = diverge & (divtime==maxit)
       divtime[div_now] = i
       z[diverge] = 2
   return divtime
# Wait a long time..., then normalize
arr = mandelbrot(2000,2000, maxit=20)[200:400, 1250:1450]
````

**Comment by stonebig** [comment]
ok, solved my stupid issue on my existing mandelbrots, so I wil not compute 3 times a mandelbrot
