### ISSUE TITLE
operation.contours and labels

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#205]
I like to create a plot with contours, and show a legend that indicates which levels are used for the contours.

operation.contours returns a nice NdOverlay. However, it does not set the labels of the separate curves.

Is there an easy way to set the labels for the curves and create a legend? I cannot figure this out from the tutorial, nor in the manual.

**Comment by jlstevens** [comment]
This is definitely a bug and we can reproduce the problem. We should be able to fix this soon...

**Comment by philippjfr** [comment]
We've identified the problem now. We could apply a temporary workaround but we've come up with a more consistent way of doing NdOverlay legends, which will require a little bit of refactoring. May be able to do it shortly after SciPy.

**Comment by philippjfr** [comment]
I've pushed a fix for this, so it should work now. I'll file a new issue to refactor the legend system more generally and close this issue for now.
