### ISSUE TITLE
NdMapping indexing could pad extra dimensions automatically

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#206]
This feature is backward compatible with the current behaviour and could be fairly useful. Currently, if you have a two dimensional HoloMap with key dimensions ``A`` and ``B``, if you want to select where ``A`` is say ``2.0`` you need to specify a index or slice for each dimension:

```python
holomap[2.0,:]
```

The extra slice is not really necessary and this could be made to work:

```python
holomap[2.0]
```

In other words, we can assume that the full ranges are selected for the remaining dimensions. Note that this already works if you use a slice instead of an index!

```python
holomap[2.0:2.5]
```

**Comment by philippjfr** [comment]
This has now been implemented, I'll close the issue now.
