### ISSUE TITLE
Step function, support for datetime x-axis 

### ISSUE THREAD

**Issue by douglasmacdonald** [ioam/holoviews#2060]
Step function does not currently work with datetime.

Gitter quote

douglasmacdonald @douglasmacdonald 14:02
Is it possible to use dates as the x-axis for step plots (http://holoviews.org/gallery/demos/bokeh/step_chart.html)? When I try I get `File "C:\Anaconda3\lib\site-packages\holoviews\operation\element.py", line 641, in pts_to_midstep steps[0, 1:-1:2] = steps[0, 2::2] = (x[:-1] + x[1:]) / 2 TypeError: ufunc add cannot use operands with types dtype('<M8[ns]') and dtype('<M8[ns]')`

Philipp Rudiger @philippjfr 14:06
@douglasmacdonald Apparently not, it probably wouldn't be too hard to extend `interpolate_curve` to support datetimes though. Both a feature request and a PR would be very welcome.
I'd probably just convert datetimes to floats, apply the stepping interpolation and then convert back to datetimes.

**Comment by douglasmacdonald** [comment]
I might have a solution, however, there is a problem. I am changing the return and adding a new classmethod then registering it with `INTERPOLATE_FUNCS ` and `interpolation = param.ObjectSelector` in `element.py` and `chart.py`
 
`element.py`

    @classmethod
    def pts_to_midstep_dates(cls, x, y):
        x_array = np.zeros(2 * len(x), dtype='datetime64[ns]')
        y_array = np.zeros(2 * len(x))

        x = x.astype('datetime64[us]')
        x_array[1:-1:2] = x_array[2::2] = x[:-1] + (x[1:] - x[:-1])/2
        x_array[0], x_array[-1] = x[0], x[-1]
        y_array[0::2] = y
        y_array[1::2] = y_array[0::2]
        return x_array, y_array

My problem is that, despite adding 

        INTERPOLATE_FUNCS = {'steps-pre': self.pts_to_prestep,
                             'steps-mid': self.pts_to_midstep,
                             'steps-post': self.pts_to_poststep,
                             'steps-mid-dates': self.pts_to_midstep_dates
                             }
and 

       interpolation = param.ObjectSelector(objects=['steps-pre'
          , 'steps-mid', 'steps-post', 'steps-mid-dates', 'linear'],
        default='steps-mid', doc="""
        Controls the transition point of the step along the x-axis.""")

(also to chart.py)

I am still getting an error.

    ValueError: steps-mid-dates not in Parameter interpolation's list of possible objects, valid options include [linear, steps-mid, steps-pre, steps-post]

I can not figure out where the list of objects is being picked up from.

Note:

* I do not think that there should be a list in `chart.py`.

**Comment by philippjfr** [comment]
I think you're probably running into the ``interpolation`` parameters defined in ``holoviews.plotting.bokeh.chart.CurvePlot`` and ``holoviews.plotting.mpl.chart.CurvePlot``. I think all these parameters should get the list of valid methods from the same place though.

**Comment by philippjfr** [comment]
Step now supports datetimes.
