### ISSUE TITLE
Deprecate Dataset dictionary mapping format

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#2068]
In #2065 I had to add various ugly checks to ensure data was not wrongly ingested, which was largely due to one of the formats we still accept in the interfaces, here's what I wrote about it there:

>Once this is merged I'm going to make an issue about eventually dropping the dictionary mapping format that has clung on since NdElement, examples include {0: 1}, {('A', 'B'): 1}, {('A', 'B'): (1, 2)}, here both keys and values represent dimension values. It's terrible to validate and just not a great format. The only time it's semi-useful is for specifying HeatMaps.

Either we should deprecate it or clean up the code that detects and handles it right now.

**Comment by jlstevens** [comment]
I agree it should be deprecated but if we are worried about backwards compatibility, maybe 1.9 should just warn people about this format so we can remove it in 1.10?
