### ISSUE TITLE
Slicing and ellipsis

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#208]
In numpy one can do ```np.array[...,2]```

Can this functionality be implemented in hv?

**Comment by jlstevens** [comment]
I've discussed this suggestion with Philipp and I don't see why this couldn't be supported. It might even be quite easy to implement!

I'll have a look into it and if it is simple enough to do, I'll implement it for the upcoming 1.4 release. If not, I think this would be something to add shortly after...

**Comment by jlstevens** [comment]
I'll tentatively assign this to 1.4 and assign it to myself to make sure I have a look at it before the release. If it is tricky, I'll move it to the next milestone...

**Comment by jlstevens** [comment]
I've made a new PR #317 that I hope can address this and a few other issues...

**Comment by jlstevens** [comment]
The PR has now been merged so I think I can now close this issue. 

@vascotenner If you get a chance to try it out and have any feedback, I would love to hear it!

**Comment by vascotenner** [comment]
This works nice now!
