### ISSUE TITLE
trouble importing holoviews after update

### ISSUE THREAD

**Issue by ceh-creare** [ioam/holoviews#2089]
Hi there,

I've been working with holoviews/bokeh in the jupyter notebook, and finally got around to making some updates to my working environment. I updated the jupyter notebook, bokeh, holoviews, and pandas (using conda). I restarted everything, and went back to a notebook I had been working on, and got an attribute error on the line where I `import holoviews as hv`.

The tail end of the error says:
C:\Users\ceh\AppData\Local\Continuum\Anaconda3\lib\site-packages\dask\dataframe\core.py in <module>()
     38 if PANDAS_VERSION >= '0.20.0':
     39     from pandas.util import cache_readonly
---> 40     pd.core.computation.expressions.set_use_numexpr(False)
     41 else:
     42     from pandas.util.decorators import cache_readonly

AttributeError: module 'pandas.core.computation' has no attribute 'expressions'

Pandas v 0.21
Bokeh v 0.12.10
Holoviews v.1.9.0

Any thoughts? Did I screw something up when updating.

**Comment by philippjfr** [comment]
You will need a more recent version of dask.

**Comment by jbednar** [comment]
Do we need to pin the dask version, using pinning for optional imports if need be?

**Comment by ceh-creare** [comment]
Bingo! That seemed to do it. 
I used conda to update dask to 0.15.4. Thank you for the prompt assistance!

**Comment by philippjfr** [comment]
Going to close, I think this should be fixed when datashader pins dask.
