### ISSUE TITLE
HoloMap and %%opts

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#209]
When displaying a holomap, it look likes it ignores ```%%opts Raster.Near (clims=(0,1))```

However, it respects ```%%opts Raster.Near [colorbar=True]```

```python
alles = hv.HoloMap(
    {(power,int(exp)): Raster(dat, group='Near')
             for d,power in zip(data, powers)
             for dat,exp in zip(d,exposure_times) }, 
            kdims=[hv.Dimension('Power',unit='mW'),hv.Dimension('Exposure',unit='ms')])

%%opts Raster.Near [colorbar=True] (clims=(0,1))
alles[10:,:]
```
![screenshot](https://cloud.githubusercontent.com/assets/3776190/8551110/e5747b72-24d4-11e5-9d56-f22e32996589.png)

**Comment by philippjfr** [comment]
Fixed in a62cc92a, the RasterPlot.update method was ignoring the style options. Note that we recommend setting the clims on the value dimension of the Raster or Image type.
