### ISSUE TITLE
Image + regrid issues with data arrangements.

### ISSUE THREAD

**Issue by mforbes** [ioam/holoviews#2094]
Applying `regrid` to an image fails when the data is not oriented in a particular way:

```python
import holoviews as hv
import numpy as np
import xarray as xr
from holoviews.operation.datashader import regrid

xs = np.linspace(-5, 5, 256)[None, :]
ts = np.linspace(0, 10, 100)[:, None]
ns = np.exp(-(xs-2*np.cos(ts))**2/2.0)
data = xr.DataArray(ns, name='n', dims=('t', 'x'), 
                    coords=dict(x=xs.ravel(), t=ts.ravel()))

im1 = hv.Image(data, ['t', 'x'])
im2 = hv.Image(data.T, ['t', 'x'])

(im1 
  + regrid(im1)   # This is poorly behaved
  + im2 
  + regrid(im2)
).cols(2)
```
<img width="605" alt="screen shot 2017-11-04 at 10 36 43 pm" src="https://user-images.githubusercontent.com/1028433/32412308-adc5c7c8-c1b0-11e7-9622-dc97fc6148f9.png">

```python
hv.__version__, ds.__version__
(1.9.0,
 '0.6.1')
```

**Comment by jbednar** [comment]
Can you try this with the current 0.6.2 datashader release, just in case?

**Comment by mforbes** [comment]
Still an issue with 0.6.2.

**Comment by philippjfr** [comment]
Thanks, there's definitely something going wrong here, will have to investigate whether it's a holoviews or datashader issue. It seemingly works when you flip the kdims:

```python
im1 = hv.Image(data, [ 'x', 't',]) # Works
im2 = hv.Image(data, ['t', 'x']) # This doesn't work
```

**Comment by mforbes** [comment]
I think it is a holoviews issue:  The following code also has problems:

```python
import numpy as np
import holoviews as hv
hv.notebook_extension('bokeh')

xs = np.linspace(-5, 5, 64)
ts = np.linspace(0,10,100)
ns = np.exp(-(xs[None, :]-2*np.cos(ts[:, None]))**2/2.0)
hv.Image((ts, xs, ns))
```

![Uploading Screen Shot 2017-11-11 at 10.38.59 PM.png…]()

The displayed image has incorrect axes.  For example, the `x` axis now goes from 0 to 10, but this corresponds to `size=64` dimension of the image.  My guess is that Image is not actually checking that the size of the dimensions match properly.  Passing `ns.T` works.

One might argue that the bug is in the previous code since the dimensions do not match given that Image interprets everything in "cartesian" coordinates like`meshgrid`, but it is really puzzling when using a `DataArray` as above which has proper dimension labels etc.  This can cause `image.sample()` to fail, even when referring to coordinate by name.

**Comment by philippjfr** [comment]
There was a missing bit of error handling in one of the interfaces that allowed invalid coordinate and value array combinations to be allowed. Additionally the regrid code was not checking the xarray had the correct orientation before applying the regridding, both are now fixed and I'll add some unit tests.

**Comment by philippjfr** [comment]
Thanks again for providing a reproducible example, really helped figuring out the issues.
