### ISSUE TITLE
Exporting mp4 with Matplotlib: empty documentation

### ISSUE THREAD

**Issue by drs251** [ioam/holoviews#2095]
When I export a HoloMap of Images as an mp4 video with the Matplotlib backend, the colorbar seems to be stuck at the setting for the first frame, ignoring the fact the it may be different for following frames, e.g. when using framewise normalization. This code shows the problem:

```python
import numpy as np
import holoviews as hv
hv.notebook_extension("matplotlib")
from holoviews.plotting.mpl import MPLRenderer
```

```python
%%opts Image {+framewise} [colorbar=True]

t = np.linspace(0, 30, 101)
x = np.linspace(0, 10, 101)
y = np.linspace(0, 10, 101)
xx, yy, tt = np.meshgrid(x, y, t)
intensity = {time: hv.Image((np.cos(xx + time) + np.sin(yy)) * (1 + np.sin(time/10))) for time in t}

hmap = hv.HoloMap(intensity, kdims=["time"])
hmap
```

```python
renderer = MPLRenderer.instance(holomap="mp4")
with open("test.mp4", "wb") as file:
    file.write(renderer(hmap)[0])
```

In addition, I've noticed that the corresponding page in the documentation is currently empty: http://holoviews.org/user_guide/Plotting_with_Matplotlib.html I think there used to be some instructions on how to render videos, it would be nice to have something like this on the website again (it took me longer to figure this out than I would care to admit...).

**Comment by philippjfr** [comment]
@drs251 Thanks I had forgot we indeed had some material in Plotting with Matplotlib before. I'll try to fix that build asap. That said could you confirm your holoviews version, I fixed a bug related to this in the last release and your snippet works fine for me at least.

**Comment by drs251** [comment]
@philippjfr Yes, switching to version 1.9.0 from the conda ioam channel solved the problem (it doesn't seem to be in the main channel yet).

**Comment by philippjfr** [comment]
Updated the docs and added sections about gif and mp4 rendering.
