### ISSUE TITLE
greek letter in a title looses the second plot

### ISSUE THREAD

**Issue by ea42gh** [ioam/holoviews#2096]
```
th_1 = np.linspace(0,19,20)
th_2 = np.linspace(0,19,20)

hv.Curve((th_2,th_1))\
     .relabel('𝜗_1 vs th_2')+hv.Curve((th_1,th_2))
```
removing hv.Curve((th_1,th_2)) or removing the greek letter results in the expected plots.
inserting a printable character in front of '𝜗_1' also works

**Comment by philippjfr** [comment]
Looks like the sanitizer is not escaping the unicode character:

```
> hv.core.util.group_sanitizer('𝜗_1 vs th_2')
'𝜗_1_vs_th_2'
```

**Comment by jlstevens** [comment]
```
> hv.core.util.group_sanitizer('𝜗_1 vs th_2')
'𝜗_1_vs_th_2'
```

This is the correct behavior on Python 3 as `𝜗_1_vs_th_2` is a perfectly valid identifier. I can reproduce the original issue though i.e:

```
hv.Curve((th_2,th_1))\
     .relabel('𝜗_1 vs th_2')+hv.Curve((th_1,th_2))
```
I think there may be an issue with the sanitizer (as the unicode character causes issues) but I suspect it is in plotting (maybe `LayoutPlot`).

**Comment by jlstevens** [comment]
I suspect it is the layout as this is fine:

![image](https://user-images.githubusercontent.com/890576/51207113-83338780-18cf-11e9-91ab-1497e652aa9b.png)

**Comment by philippjfr** [comment]
Yes as I said it's the layout check for isupper. The sanitizer is meant to capitalize the first letter but isn't in this case which is why it gets dropped.
