### ISSUE TITLE
updating labels does not work in a DynamicMap

### ISSUE THREAD

**Issue by ea42gh** [ioam/holoviews#2097]
using `hv.Curve(...,label='%f'%v)` in an hv.DynamicMap does not update the label

**Comment by philippjfr** [comment]
Just to be clear, by label is the legend entry meant here?

**Comment by philippjfr** [comment]
As far as I can tell this is resolved but please reopen  if you find it's not.

**Comment by philippjfr** [comment]
Closing in favor of https://github.com/ioam/holoviews/issues/2497
