### ISSUE TITLE
Image and bounds

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#210]
The image object does not respect bounds. It  always takes bottom lower than top, even if specified different.

This does not work as expected:
```
extents=(1,2,3,-4)
hv.Image(np.log(dets), bounds=extents, kdims=key_dimensions)
```
![screenshot-1](https://cloud.githubusercontent.com/assets/3776190/8572253/b5cd2dda-258b-11e5-91a6-337fa92cebac.png)

This works as expected (bottom<top)
```
extents=(1,2,3,4)
hv.Image(np.log(dets), bounds=extents, kdims=key_dimensions)
```
![screenshot-2](https://cloud.githubusercontent.com/assets/3776190/8572264/ca0494b4-258b-11e5-9f0a-e46c13a5111f.png)

**Comment by philippjfr** [comment]
The bounds should always be specified as ``(xlower, ylower, xupper, yupper)``, if you want to invert the axes in your plot just use the ``invert_xaxis`` and ``invert_yaxis`` plot options.

**Comment by vascotenner** [comment]
Image now silentlty ignore the bounds. Can it raise a warning when the bounds are not valid?

A second concern is that I now should think about the order of the data, instead of giving holoviews a complete description and do the thinking for me.
