### ISSUE TITLE
Add support for datetime.date

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#2100]
While we handle most other datetime types, datetime.date is currently not handled, e.g. when you try the example below you get an error:

```python
hv.Scatter(zip(pd.DatetimeIndex(start='2017-01-01', end='2017-01-04', freq='1d').date, np.linspace(0,1,4)))
```

**Comment by bacalfa** [comment]
That'd be great! For Area as well.

`hv.Area(zip(pd.DatetimeIndex(start='2017-01-01', end='2017-01-04', freq='1d').date, np.linspace(0,1,4)))`

**Comment by philippjfr** [comment]
Now supported.
