### ISSUE TITLE
Legend entries with `hv.Area`

### ISSUE THREAD

**Issue by PeterDSteinberg** [ioam/holoviews#2118]
Currently it is not apparent how to add legend entries for `hv.Area` items

I created the figure below with 3 `hv.Curve` items that show up in legend but the 2 `hv.Area` items are plotted without legend labels.
<img width="893" alt="screen shot 2017-11-12 at 8 40 09 am" src="https://user-images.githubusercontent.com/1445602/32701636-38c67c68-c78e-11e7-98f6-c7492a2c2e5e.png">

```
mx = ds.data.flow.values.max()
s = lambda c: c.opts(style={'Area': {'fill_alpha': 0.3}})
f,t,c,i,w = (hv.Curve(ds.data.flow, label='Flow (GPM)'),
           hv.Curve(ds.data.temp, label='Temperature (F)'),
           hv.Curve(ds.data.cond, label='Conductivity (uS/cm)'),
           s(hv.Area(ds.data.is_illicit * mx * 0.4, label='Has Illicit Discharge (1=Yes)')),
           s(hv.Area(ds.data.did_warning * mx * 0.6, label='Created a warning (1=yes)')))
```

Note from @philippjfr on solving this:
> The Areas are drawn using bokeh's Band glyph which does not currently support legend entries. Would you mind filing an issue with holoviews about this and then I'll try to follow up with bokeh to see if there's something we can do about that?

**Comment by philippjfr** [comment]
This should now be fixed by #2225.
