### ISSUE TITLE
tap streams dont work when a dimension is a datetime

### ISSUE THREAD

**Issue by suvarchal** [ioam/holoviews#2124]
%%opts Curve [tools=['tap','hover']]
    a=hv.Curve((list(pd.date_range('2017-08-01', '2017-08-31')), range(31)))
    b=hv.Curve((range(60,91), range(31)))
    tap_a=streams.SingleTap(source=a) 
    tap_b=streams.SingleTap(source=b)
    a
    b
    
tapping on plots a,b ; `tap_a` always returns `None` 
where as `tap_b` returns a value of x and y. 

not only hv.Curve, it is also evident when using hv.Points.

if it is a limitation atleast should be warned?

**Comment by jlstevens** [comment]
Sounds like a limitation that can and should be addressed...

**Comment by jlstevens** [comment]
I believe this is now addressed by the PR above which has now been merged.
