### ISSUE TITLE
Dataset only takes 2 arguments?

### ISSUE THREAD

**Issue by lowell112** [ioam/holoviews#2136]
I was initially attempting to wrap some of my own data in a Dataset, and was getting the following error:

`TypeError: __init__() takes exactly 2 arguments (4 given)`

So I opened the Gridded_Datasets example code in Jupyter Notebook and I get a similar error when I get to the Dataset line:
`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-b99fc66d5811> in <module>()
      1 ds = hv.Dataset((np.arange(50), np.arange(111), np.arange(62), calcium_array),
----> 2                 ['Time', 'x', 'y'], 'Fluorescence')
      3 ds

TypeError: __init__() takes exactly 2 arguments (4 given)`

My apologies if I am missing something obvious, but considering it didn't work with the example Jupyter Notebook, I hope that's not the case.

Running:
python                    2.7.14 
holoviews                 1.8.3  
pandas                    0.21.0
numpy                     1.13.3 
on Mac OS Sierra 10.12.6

**Comment by philippjfr** [comment]
@lowell112 Only recent versions of HoloViews allow passing the ``kdims`` and ``vdims`` as positional arguments so try upgrading to HoloViews >=1.9.x with:

     conda install -c conda-forge holoviews
