### ISSUE TITLE
Add Chord Diagram

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#2137]
The bokeh charts library used to ship with a [chord diagram](https://bokeh.pydata.org/en/0.12.3/docs/gallery/chord_chart.html) and I have had multiple people request this feature. A chord diagram is a useful way of displaying the inter-relationships between data in a matrix and we should be able to reuse the implementation in bokeh charts. It also fits in with our new ``Graph`` support.

**Comment by DGMichael** [comment]
Would be great to have a Python implementation Phillipp.  Thanks for considering it!

**Comment by philippjfr** [comment]
Now merged.
