### ISSUE TITLE
Hover problem in BoxWhisker chart

### ISSUE THREAD

**Issue by pierdom** [ioam/holoviews#2142]
The hover does not work in BoxWhisker chart. Here an example:

![boxwhisker_hoover_problem](https://user-images.githubusercontent.com/4760986/33126265-2fac71a2-cf84-11e7-8cc4-a9f736e9954b.png)

**Comment by philippjfr** [comment]
Should be fixed by #2187, the hover should now report the median.

**Comment by jlstevens** [comment]
The PR referenced above should fix this issue and it has been merged. Closing.
