### ISSUE TITLE
Events are pinging back and forth in multiple subplots

### ISSUE THREAD

**Issue by ivek1312** [ioam/holoviews#2146]
When having multiple subplots with code like this:
```
range_stream = RangeX()
self.output = hv.DynamicMap(hv.Callable(load_data, stream_mapping={0: [range_stream]}), streams=[self, range_stream])
```
then events are pinging back and forth between the subplots causing the resets. 
If load_data returns only one plot (in layout) everything works fine.
Link to video: [https://drive.google.com/open?id=1WwAzmmDJ6ZBHmE-Rk1ltYeTQ2Jw4exOL](url)
Link to example notebook:  https://github.com/ivek1312/example/blob/master/interactive_visualisation-Copy1.ipynb

**Comment by philippjfr** [comment]
@ivek1312 You mentioned you couldn't reproduce this using 1.9.1? Can you confirm that again? If so I'll close.

**Comment by ivek1312** [comment]
It works perfectly on 1.9.1.
