### ISSUE TITLE
xarray backend crashesh on hv.Image if theres a 'z'-dimension on xarray.

### ISSUE THREAD

**Issue by leevei** [ioam/holoviews#2147]
This works:
```
arr = np.random.rand(3,3)
cube = xr.DataArray(arr, dims=['c', 'x'], coords={'c':[1,2,3], 'x':[1,2,3]})
hv.Image(cube)
```
This also works:
```
arr = np.random.rand(3,3)
cube = xr.DataArray(arr, dims=['c', 'x'], coords={'c':[1,2,3], 'x':[1,2,3]})
hv.Image(cube, vdims=['aaaa'])
```
 This crashes: 
```
arr = np.random.rand(3,3)
cube = xr.DataArray(arr, dims=['z', 'x'], coords={'z':[1,2,3], 'x':[1,2,3]})
hv.Image(cube)
```
This is because there is 'z' in xarray coords and dims, and holoviews uses 'z' as a hv.Dimension if vdims is not defined. I think better solution would be for example make vdims from other dimensions, like this:

`cube = xr.DataArray(arr, dims=['z', 'x'], coords={'z':[1,2,3], 'x':[1,2,3]})` ==> `hv.Image(cube)` has dimensions 'z', 'x' and 'zx'. 

Then it would be impossible to get a duplicate hv.Dimension, since the name of the new hv.Dimension is guaranteed to be longer than any other dimension. 

I imagine this problem could be for more than just hv.Images, that it would be same for all structures that use `vdims`, but I havent really tested it.

**Comment by philippjfr** [comment]
> I think better solution would be for example make vdims from other dimensions, like this:

This seems like a reasonable suggestion, it will still try to use the default value dimension name (which in the case of an Image is 'z') but if that's not valid it will fall back to your suggestion.

**Comment by philippjfr** [comment]
Okay thinking about this again I think that behavior would be a little bit weird, because you could end up with really long composite names. Better to raise a more informative error message and make the user supply a name.

**Comment by philippjfr** [comment]
I went with the improved error message.
