### ISSUE TITLE
possible ['matplotlib'] issue in Options.ipynb ? 

### ISSUE THREAD

**Issue by stonebig** [ioam/holoviews#215]
on my pc, there is not choice of renderers ?

![holo_options_issue](https://cloud.githubusercontent.com/assets/4312421/8634247/1ead5ace-27f2-11e5-9818-c417a808029e.GIF)

**Comment by philippjfr** [comment]
Have you loaded the IPython extension via:

```python
%load_ext holoviews.ipython
```

If so could you try this import and report any errors (if there are any):

```python
from holoviews.plotting import mpl
```

**Comment by stonebig** [comment]
no I didn't, I just executed the notebook... maybe add this at the start of the notebook, not to see th issue coming back from another person.

it's now ok after pre-executing
````python
%load_ext holoviews.ipython
````

**Comment by philippjfr** [comment]
Yep, that's it. Thanks for reporting it!

**Comment by razvanc87** [comment]
This isn't fixed in the documentation. Why is it closed? In the [web page about the options](http://holoviews.org/Tutorials/Options.html), there should be
```python
from holoviews.plotting import mpl
```
if we want to use these things with regular `Python`, which is the more general option I guess...

**Comment by philippjfr** [comment]
Ah the main website isn't automatically updated, only the holoviews.org/dev page is, I can update it tonight when I have access to a computer.

**Comment by razvanc87** [comment]
:+1:
