### ISSUE TITLE
Center HeatMap colors around zero

### ISSUE THREAD

**Issue by apahl** [ioam/holoviews#2150]
Hi, thanks for this awesome library!!

I am plotting a heatmap with positive and negative values, but the ranges in the two directions can differ, e.g. they might go from -5 ... 0 ... +3.

For the bwr colormap, the plots then show a *shift* to red, where zero values are shown as pale red.
![heatmap](https://user-images.githubusercontent.com/9406836/33220787-3d66f0ce-d14b-11e7-97b3-9de68586165a.png)

Is it possible to center the colormap around zero so that zero values are always shown as white?

These are my currently used options:
```
hm_opts = dict(width=950, height=40 + 27 * df_len, tools=['hover'], invert_yaxis=invert_y,
                xrotation=90, labelled=[], toolbar='above', colorbar=True, xaxis=None,
                colorbar_opts={"width": 10})
hm_style = {"cmap": "bwr"}
opts = {'HeatMap': {'plot': hm_opts, "style": hm_style}}
heatmap = hv.HeatMap(df_heat)
```

Many thanks for your help.

Kind regards,
Axel

**Comment by philippjfr** [comment]
Hi Axel, I'm glad you're enjoying the library. You can absolutely define a symmetric range, the easiest way to achieve is  probably the ``.redim.range`` method. Try something like this:

```
heatmap = hv.HeatMap(df_heat).redim.range(z=(-5, 5)).opts(plot=hm_opts, style=hm_style)
```

You will have to switch out ``z`` for the name of the column that defines the values of your HeatMap.

**Comment by apahl** [comment]
Hi Philipp, thanks for the very fast answer.

A question to your comment regarding replacing `z`:  
My input to the hv.HeatMap is a DataFrame with (in the above case) 6 rows and more than 630 columns, defining the individual bars in the heatmap.  
How would I transfer that to the correct `z`?

Many thanks,  
Axel

**Comment by apahl** [comment]
No, sorry, I got it.

I use melt on the DataFrame and only have one `Value`.

It now works, thanks a lot for quick help!!
