### ISSUE TITLE
exchanging the  x  and   y  axis

### ISSUE THREAD

**Issue by maajdl** [ioam/holoviews#2153]
Hello.

Just a question in case that would be possible ...

Let's assume that a method returns a full graph with a few overlays.
Would it be possible to transform this graph, in such a way that  x  and  y  axis are interchanged?

Of course, it should not be too difficult to re-write the method for the same result.
But a simple way to exchange  x  and  y  would be a nice shortcut.

Thanks,

Michel

**Comment by jlstevens** [comment]
I think the standard way would be to use the ``reindex`` method:

![image](https://user-images.githubusercontent.com/890576/33853488-0bccc3fe-deb6-11e7-88a4-5f11c39253a5.png)

Perhaps this issue should be repurposed to remind us to improve the documentation of ``reindex``?

**Comment by maajdl** [comment]
Thanks JL!

One more question!
What about reversing an axis, plotting it in reverse order?

Thanks,

Michel

**Comment by jlstevens** [comment]
For that you can set the ``Dimension`` range (e.g y-axis flipped):

![image](https://user-images.githubusercontent.com/890576/34101217-e987bcaa-e3dc-11e7-8ccc-973be23c5f09.png)

or you can use ``redim`` (e.g x-axis flipped):

![image](https://user-images.githubusercontent.com/890576/34101263-13790316-e3dd-11e7-8211-f70b1848c496.png)

For this kind of question I recommend you chat to us on [gitter](http://gitter.im/ioam/holoviews) before filing issues. Hope that helps and I will close this issue now.
