### ISSUE TITLE
Explain facets

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#216]
Various other projects use the term _facets_ to describe some portion of what HoloViews provides with its GridSpace and NdLayout objects.  It would be very helpful if our documentation could clarify exactly how that term would map onto HoloViews objects, so that new users can clearly see the relationships between these related ideas.

**Comment by philippjfr** [comment]
I've taken faceting to be more encompassing to refer to all our dimensioned containers and have used the term throughout the corresponding user guide. Finally closing this one.
