### ISSUE TITLE
Legend for hv.Dimension disappears when [filled=True]

### ISSUE THREAD

**Issue by jvivian** [ioam/holoviews#2163]
I couldn't find an existing issue and was unsure if this was intended or not. 

## Reproduction Code
Using code from [Legend example](http://holoviews.org/gallery/demos/bokeh/legend_example.html)
```
%%opts Distribution.Distribution.Not_filled [filled=False] (line_color=Cycle())
%%opts Distribution.Distribution.Filled [filled=True] (line_color=Cycle())
normal = np.random.randn(1000)
filled = hv.NdOverlay({bw: hv.Distribution(normal, label='Filled').opts(plot=dict(bandwidth=bw)) for bw in [0.05, 0.1, 0.5, 1]})
not_filled = hv.NdOverlay({bw: hv.Distribution(normal, label='Not_filled').opts(plot=dict(bandwidth=bw)) for bw in [0.05, 0.1, 0.5, 1]})

filled + not_filled
```

![image](https://user-images.githubusercontent.com/7576256/33405479-63c76fac-d51d-11e7-8abe-7ed326ef1d05.png)

Versions:
Python 2.7 (Anaconda 4.3.30)
holoviews (1.9.1)
Ubuntu 15.04

Thanks!

**Comment by philippjfr** [comment]
This is related to https://github.com/ioam/holoviews/issues/2118, hopefully we will have a fix soon, but it probably requires a change in bokeh.

**Comment by jlstevens** [comment]
If this requires a fix in bokeh, are the bokeh team aware of it? Is there a bokeh issue we can reference?

**Comment by philippjfr** [comment]
This should now be fixed by the PR referenced above.
