### ISSUE TITLE
Distributions, Histograms and Labels Feature Request

### ISSUE THREAD

**Issue by ea42gh** [ioam/holoviews#2170]
```
np.random.seed(1213)
data_1 = np.random.normal(size=1000)+ np.random.uniform(0,15,size=1000)
data_2 = np.random.normal(size=1000)+ np.random.uniform(-5,10,size=1000)
hv.Distribution(data_1,label='s1')*hv.Histogram(np.histogram(data_1,bins=50,density=True),label='s1')\
*hv.Distribution(data_2,label='s2')*hv.Histogram(np.histogram(data_2,bins=50,density=True),label='s2')
```
I wanted two overlaid Distributions with legends.
I ended up overlaying them with hv.Histograms (with the idea of setting alpha=0).

Since Curves can be turned on and off by clicking on the legends
* can legends be enabled for hv.Distribution?
* can the turn on/off behavior be extended to hv.Distribution and hv.Histogram?

**Comment by jlstevens** [comment]
I believe this is a feature request and right now I am *assuming* the issue is with support at the bokeh level. I might be wrong about that though!

**Comment by philippjfr** [comment]
>can legends be enabled for hv.Distribution?

This is now supported.

>can the turn on/off behavior be extended to hv.Distribution and hv.Histogram?

@ea42gh Would you mind opening a PR adding ``muted_alpha=0.2`` [here](https://github.com/ioam/holoviews/blob/master/holoviews/plotting/bokeh/__init__.py#L158) and [here](https://github.com/ioam/holoviews/blob/master/holoviews/plotting/bokeh/__init__.py#L234). That should be sufficient to get the on/off behavior you want.

**Comment by ea42gh** [comment]
that's quick and easy!
Teaching me more about how your code works is likely to prove dangerous :)

**Comment by philippjfr** [comment]
>Teaching me more about how your code works is likely to prove dangerous :)

No, it's long overdue! I'll try to pump out some developer guides this month, we really need to become more developer friendly.

**Comment by ea42gh** [comment]
oh yes!!!  Once you do, I'll revisit some of my old notebooks with pending problems.
I'll be asking questions then!

In the mean time, hope I got it right this time arouns.

**Comment by philippjfr** [comment]
Thanks for the contribution @ea42gh!
