### ISSUE TITLE
Bounds example

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#218]
I've been staring at the Bounds example in the Elements tutorial and scratching my head:

```
Bounds((0.45, 0.45, 0.2, 0.2))
```

The documentation says that Bounds accepts a tuple (l,b,r,t), and so does the code, but how can 0.45 be to the left of 0.2?  In the plot the left and bottom both seem like 0.2, and the top and right are both 0.45 (which is confusing in its own right due to symmetry).   So it seems to work fine without being l,b,r,t.  I guess the example should either use l,b,r,t properly or explain what's really the constraint on these values?

**Comment by jlstevens** [comment]
Looking at the code, the values supplied become a specification for a closed, box shaped ``Path`` object.  This means that the starting point for the box can be at any corner and you can define the values going clockwise or anti-clockwise (i.e anything consistent).

I am not sure this is something worth explaining but I do agree the tutorial should be fixed to obey ``(l,b,r,t)`` !

**Comment by jlstevens** [comment]
Fixed in the issue above. You can still define ``Bounds`` as before but the new way is less likely to cause confusion.

**Comment by jlstevens** [comment]
Actually, I've reverted this change 7575399 as it was causing the notebook tests to fail. I'll reinstate it when we update all the test data before release but for now we want to have the tests passing as we implement a few last changes.
