### ISSUE TITLE
Plotting multiple curves with legend using datashader

### ISSUE THREAD

**Issue by papahabla** [ioam/holoviews#2182]
The following is an attempt at combining two HoloViews examples for using [Ndoverlay](http://holoviews.org/reference/containers/bokeh/NdOverlay.html), and the section for adding  [legend by adding a suitable collection of labeled points](http://holoviews.org/user_guide/Large_Data.html).

The issue I'm having is that the legend doesn't correctly match the label/color of the correct curve plotted through datashader. It would also be nice if the legend order was maintained. 

* The green:1/1 indicated in the legend should match the red curve
* The red:1/2 indicated in the legend should match the blue curve
* The blue:3/4 indicated in the legend should match the green curve

![bokeh_plot 1](https://user-images.githubusercontent.com/10580407/33779444-c9fbf8e8-dc01-11e7-94ec-c77317ddaeb7.png)

```python
import numpy as np
import holoviews as hv
import datashader as ds
from holoviews.operation.datashader import datashade, dynspread
hv.extension('bokeh')
dynspread.max_px=20
dynspread.threshold=0.5
```

```
%%opts NdOverlay  [height=256 width=1024 show_grid=True]
%%opts Curve  [height=256 width=1024 show_grid=True]

from datashader.colors import Sets1to3
from holoviews import OrderedDict

channel_keys = ['1/2', '3/4', '1/1', '5/4']
frequencies = [0.5, 0.75, 1.0, 1.25]
color_key = list(enumerate(Sets1to3[0:len(frequencies)]))
def sine_curve(phase, freq, label):
    xvals = [0.1* i for i in range(100)]
    return hv.Curve((xvals, [np.sin(phase+freq*x) for x in xvals]), label=label)
curve_dict = OrderedDict()
legend_dict = OrderedDict()
for i in range(len(frequencies)):
    c = channel_keys[i]
    f = frequencies[i]
    curve_dict[c] = sine_curve(0, f, c)
    legend_dict[c] = hv.Points([0,0], label=str(c)).opts(style=dict(color=color_key[i][1]))
overlay = hv.NdOverlay(curve_dict, kdims='channel_keys')
curve_plot = dynspread(datashade(overlay, aggregator=ds.count_cat('channel_keys')))
curve_plot * hv.NdOverlay(legend_dict)
```

**Comment by philippjfr** [comment]
You can define a ``color_key`` as a dictionary and pass it to datashade:

```python
%%opts NdOverlay  [height=256 width=1024 show_grid=True]
%%opts Curve  [height=256 width=1024 show_grid=True]

from datashader.colors import Sets1to3
from holoviews import OrderedDict

channel_keys = ['1/2', '3/4', '1/1', '5/4']
frequencies = [0.5, 0.75, 1.0, 1.25]
color_key = {k: c for k, c in zip(channel_keys, Sets1to3[0:len(frequencies)])}
def sine_curve(phase, freq, label):
    xvals = [0.1* i for i in range(100)]
    return hv.Curve((xvals, [np.sin(phase+freq*x) for x in xvals]), label=label)
curve_dict = OrderedDict()
legend_dict = OrderedDict()
for i in range(len(frequencies)):
    c = channel_keys[i]
    f = frequencies[i]
    curve_dict[c] = sine_curve(0, f, c)
    legend_dict[c] = hv.Points([0,0], label=c).opts(style=dict(color=color_key[c]))
overlay = hv.NdOverlay(curve_dict, kdims='channel_keys')
curve_plot = dynspread(datashade(overlay, aggregator=ds.count_cat('channel_keys'), color_key=color_key))
curve_plot * hv.NdOverlay(legend_dict)
```

**Comment by papahabla** [comment]
Thanks @philippjfr, that works!

I suppose the example, [Multidimensional plots](http://holoviews.org/user_guide/Large_Data.html) makes the assumption that numerical dictionary key will maintain the order between the datashader module to plot data, and holoviews APIs used for the legend.

**Comment by kawairine** [comment]
Hi,

```
legend_dict = OrderedDict()
for i in range(len(cl)): 
    legend_dict[c] = hv.Points([0,0], label=c).opts(style=dict(color=z_proto_col[c]))

```

And I got:

legend_dict = 
```
OrderedDict([('H', :Points   [x,y]),
             ('M', :Points   [x,y]),
             ('AT', :Points   [x,y]),
             ('AB', :Points   [x,y]),
             ('O', :Points   [x,y]),
```
 which is in the order I want, but when I do hv.NdOverlay(legend_dict), the legend is in alphabetical order again. I thought OrderedDict would keep the order of a dict? Is there something I have missed such that when I did hv.NdOverlay, the order is lost? 

Thank you!

**Comment by jlstevens** [comment]
@kawairine Sorry for the late reply. I was just wondering if you tried setting `sort=False` in the `NdOverlay` constructor?

**Comment by RiccardoGiro** [comment]
> Hi,
> 
> ```
> legend_dict = OrderedDict()
> for i in range(len(cl)): 
>     legend_dict[c] = hv.Points([0,0], label=c).opts(style=dict(color=z_proto_col[c]))
> ```
> 
> And I got:
> 
> legend_dict =
> 
> ```
> OrderedDict([('H', :Points   [x,y]),
>              ('M', :Points   [x,y]),
>              ('AT', :Points   [x,y]),
>              ('AB', :Points   [x,y]),
>              ('O', :Points   [x,y]),
> ```
> 
> which is in the order I want, but when I do hv.NdOverlay(legend_dict), the legend is in alphabetical order again. I thought OrderedDict would keep the order of a dict? Is there something I have missed such that when I did hv.NdOverlay, the order is lost?
> 
> Thank you!

I confirm that the problem still exists. The order is unfortunately lost.

**Comment by RiccardoGiro** [comment]
> @kawairine Sorry for the late reply. I was just wondering if you tried setting `sort=False` in the `NdOverlay` constructor?

Does not work either.

**Comment by RiccardoGiro** [comment]
> You can define a `color_key` as a dictionary and pass it to datashade:
> 
> ```python
> %%opts NdOverlay  [height=256 width=1024 show_grid=True]
> %%opts Curve  [height=256 width=1024 show_grid=True]
> 
> from datashader.colors import Sets1to3
> from holoviews import OrderedDict
> 
> channel_keys = ['1/2', '3/4', '1/1', '5/4']
> frequencies = [0.5, 0.75, 1.0, 1.25]
> color_key = {k: c for k, c in zip(channel_keys, Sets1to3[0:len(frequencies)])}
> def sine_curve(phase, freq, label):
>     xvals = [0.1* i for i in range(100)]
>     return hv.Curve((xvals, [np.sin(phase+freq*x) for x in xvals]), label=label)
> curve_dict = OrderedDict()
> legend_dict = OrderedDict()
> for i in range(len(frequencies)):
>     c = channel_keys[i]
>     f = frequencies[i]
>     curve_dict[c] = sine_curve(0, f, c)
>     legend_dict[c] = hv.Points([0,0], label=c).opts(style=dict(color=color_key[c]))
> overlay = hv.NdOverlay(curve_dict, kdims='channel_keys')
> curve_plot = dynspread(datashade(overlay, aggregator=ds.count_cat('channel_keys'), color_key=color_key))
> curve_plot * hv.NdOverlay(legend_dict)
> ```

This does not work, as the legend is still messed up (at least to this date). After spending an insane amount of time struggling with correct legend ordering, I have finally found a solution (demonstrated in a notebook [here](https://github.com/RiccardoGiro/Main_repository/blob/0fba2c2c62789cccdad9bd961253e21f938b3b6b/How%20to%20draw%20legends%20properly%20using%20HoloViews%20%2B%20Datashader.ipynb)). Maybe @philippjfr and @jbednar could find this information useful.
