### ISSUE TITLE
Curve of reduced Image is mirrored

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#219]
When I make a curve of a reduced Image, the y axis is mirrored
```python
dat = np.mgrid[:4,:2][0]
img = hv.Image(dat)
img + img.sample(x=0) + img.reduce(x=np.mean).to.curve()
```
![screenshot-1](https://cloud.githubusercontent.com/assets/3776190/8748068/3c13fabe-2c98-11e5-9e38-5a3c920efe57.png)

**Comment by jlstevens** [comment]
Certainly looks like a bug to me! Thanks for reporting this...

**Comment by philippjfr** [comment]
Yep definite bug, will look at it tomorrow.

**Comment by philippjfr** [comment]
Fixed in the commit referenced above, closing.
