### ISSUE TITLE
type object 'BlockLexer' has no attribute 'default_rules'

### ISSUE THREAD

**Issue by dartdog** [ioam/holoviews#22]
After new install (IPython notebook version 3+) Python 2+ I get the above error  (Suspect IPython 3 issue)

    from holoviews import *
    %load_ext holoviews.ipython

:0: FutureWarning: IPython widgets are experimental and may change in the future.  
then   
type object 'BlockLexer' has no attribute 'default_rules'

30 @undoc
     31 class MathBlockLexer(mistune.BlockLexer):
---> 32     default_rules = ['block_math', 'latex_environment'] + mistune.BlockLexer.default_rules
     33 
     34     def __init__(self, rules=None, **kwargs):

**Comment by jlstevens** [comment]
We are aware of the ``FutureWarning`` (which can safely be ignored) but we will need to look into the error regarding `BlockLexer`. An initial search does suggest that it is something specific to IPython 3, see this issue for example: https://github.com/ipython/ipython/issues/7135

From the sound of it the mistune library might need upgrading. Maybe running ``pip install mistune --upgrade`` will help?

Thank you for reporting this!

**Comment by dartdog** [comment]
Thanks for the quick response that did it,, 
I Had   Found existing installation: mistune 0.4.1
and upgraded to   Found existing installation: mistune 0.4.1
FYI..
don't know if the following warning is an issue or not? /usr/local/lib/python2.7/dist-packages/matplotlib/animation.py:727: UserWarning: MovieWriter ffmpeg unavailable
  warnings.warn("MovieWriter %s unavailable" % writer)

Something else I need to install?

**Comment by philippjfr** [comment]
We need to work on suppressing these messages. ffmpeg isn't actually a requirement, it's only needed to generate h264 video using matplotlib. If you're only working with our widgets you won't need it.

**Comment by dartdog** [comment]
Great, Appreciate the help, can't wait to get into the useage of what looks so good!
