### ISSUE TITLE
Tuples as a convenient way to specify slices

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#220]
Defining slices in `__getitem__` from some pre-defined region can be awkward as you have to unpack each slice appropriately. A simple alternative would be to have `__getitem__` support tuples such as `(l,b,r,t)`.

In general, the tuple would be twice the length of the number of applicable key dimensions and would be used to specify a region with a finite extent along every key dimension. The general semantics of the tuple is that the first two values in the tuple specify the min and max of the first key dimension, the second pair of values specify the limits of the second key dimension and so on.

This should be very easy to implement in a general way. One potential pitfall is that `NdMappings` accept tuple keys (to specify the value along multiple dimensions at once). This shouldn't be a problem however, as the number of key dimensions is known - an indexing tuple will have exactly that number of elements whereas a slicing tuple will have double the length.

**Comment by jbednar** [comment]
l,b,r,t doesn't fit with the specified semantics; as you describe it it would be l,r,b,t.   lrbt makes good sense, but isn't what the Bounds object accepts, which would make it more difficult to go between Bounds and such slicing (which is a common use case, to annotate an Image with a box to show an area enlarged elsewhere).  So I'm not sure what the best approach is.

**Comment by jbednar** [comment]
l,b,r,t doesn't fit with the specified semantics; as you describe it it would be l,r,b,t. lrbt makes good sense, but isn't what the Bounds object accepts, which would make it more difficult to go between Bounds and such slicing (which is a common use case, to annotate an Image with a box to show an area enlarged elsewhere). So I'm not sure what the best approach is.

**Comment by jlstevens** [comment]
> l,b,r,t doesn't fit with the specified semantics; as you describe it it would be l,r,b,t.

Good point! Sounds like this issue is related to #218 in terms of what ``Bounds`` accepts. I am now thinking that using ``(l,b,r,t)`` was a mistake for ``Bounds`` in the first place - I would consider renaming it to ``BoundsLBRT`` and implementing a new ``Bounds`` object that fits in nicely with the proposed semantics. 

This would be an API change which isn't backwards compatible so I am not certain this is the best approach either.

**Comment by jbednar** [comment]
That would be a very confusing API change, which I vote against.  I'm not sure of the best approach, then.

**Comment by jlstevens** [comment]
To be honest, the fundamental issue is that the whole concept of ``(l,b,r,t)`` isn't properly consistent with the rest of HoloViews. This is an accident of history (inherited ``BoundingBox`` and ``SheetCoordinateSystem``  from Topographica/Imagen) meaning it is probably too difficult to fix properly now. :-(

**Comment by jbednar** [comment]
Right. lbrt makes sense as a list of points (as in Path), but its design predates Numpy's slicing semantics, and doesn't match it.  Nowadays l:r,b:t (approximated as l,r,b,t as a tuple) is much more reasonable.   Where is lbrt exposed to the user?  If it's just Bounds, you could deprecate Bounds and introduce a new object BoundingBox to replace it (and rename the current core.BoundingBox, as it's probably not used by users) or maybe just Box.

**Comment by jlstevens** [comment]
I wish it were just ``Bounds``! Unfortunately, you specify the ``(l,b,r,t)`` to define ``Image`` objects as well.

If we could get rid of lbrt in those two places, I would be really happy. Your suggestion makes sense but we cannot use the name ``Box`` as that already exists. 

There must be a way to make things consistent, but I'll have to think carefully about it. Maybe supporting ``BoundingBox`` as a way of specifying things in lbrt format. 

That said, ``BoundingBox``  doesn't actually accept ``lbrt`` itself but something called ``points`` (or ``radius`` of course)! That could be easily fixed though by supporting ``BoundingBox(lbrt=lbrt)``.

**Comment by jlstevens** [comment]
The best solution I can come up with right now is to give ``Image`` two behaviors such that it can either treat the bounds parameter as an ``lbrt`` or the suggested, more consistent format. 

One possible approach is to have two classes:  rename the existing ``Image`` class to ``ImageLBRT`` and then the remaining ``Image`` class would implemented the new desired behavior. Existing users that need the old behavior can then alias  appropriately using ``from holoviews import ImageLBRT as Image`` or add the appropriate line to their ``holoviews.rc`` once (clear instructions would be supplied in the CHANGELOG). Existing users could then take as much time as they need to switch to the improved format (which we would encourage!).  We would also need to make sure that pickle compatibility isn't broken.

For Imagen/FeatureMapper/Topographica, would then continue to use ``ImageLBRT`` for backwards compatibility. Together with your suggestion of slowly deprecating ``Bounds``, I think this could eliminate ``lbrt`` for new users while continuing to support it for other IOAM projects. That said, I'm still hoping we can  find a better solution that requires less work!

**Comment by philippjfr** [comment]
I'd be happy to consider changing ``Image`` and even ``SheetCoordinateSystem`` to use the more sensible format. Ensuring pickle compatibility is the major issue though as we don't want to add further legacy stuff. I have no great solution for that, all I can suggest is that we envision a backwards compatibility breaking release to make changes just like this, along with the suggested changes for the data format of ``Chart`` Elements.

I'm not sure if the suggestion of supporting tuples twice the length of the key dimensions is still being proposed but to me it seems a bit weird but I could live with it if it was ``(l, r, b, t)`` for a 2D object since ``((l, r), (b, t))`` is already valid.

**Comment by jbednar** [comment]
What do you mean by "((l, r), (b, t)) is already valid"?  It doesn't seem to be accepted by either Bounds() or [] slicing.  If both Bounds() and slicing would accept the same single format for specifying a region, there'd be no need to consider other conventions like those suggested above.

**Comment by philippjfr** [comment]
You're right ``((l, r), (b, t))`` indeed isn't supported, ``.select`` does support expanding tuples into slices so  ``__getitem__`` could do the same but you're right, that is optional. I'm in favour of going ahead with @jlstevens  suggestion.

**Comment by jbednar** [comment]
I looked back above, but am not sure which jlstevens suggestion you mean.  My vote is that we either keep our existing convention and make it work in more places, or we add an entirely new convention that is clearly automatically distinguished from all previous ones, and use that consistently from now on in all our materials, while still supporting the old ways.  Either way I don't think we need to break backwards compatibility, and I don't think we should consider it in this case.

**Comment by jlstevens** [comment]
I think supporting ``((l, r), (b, t))`` would be sensible as it doesn't involve any actual slices and is probably more consistent than the flat format i.e ``(l,r,b,t)``. It is an easy enough Python literal to define and get a handle on so that you can re-use it.

I don't even think this feature needs to replace anything we are doing now though the documentation should be updated where appropriate. That said, even if this format is backwards compatible, this doesn't fix the fact that ``Bounds`` and sheet coordinate systems use ``l,b,r,t`` (namely ``points=((l,b), (r,t))``) which is inconsistent with the proposed syntax. I don't really know how this inconsistency can be fixed - maybe ``Bounds`` could accept an ``lrbt`` keyword argument?

**Comment by philippjfr** [comment]
I don't quite understand the proposal laid out here. Our objects can be any dimensionality so any slicing API that is specific to a particular dimensionality (e.g. (l, b, r, t) seems odd to me). The ``((l, r), (b, t))`` approach seems okay although it seems like it should just be this ``img[(l, r), (b, t)]`` without the additional bracketing. Overall though I'd prefer not to overload the slicing semantics any more. Depending on how attached you are to this idea I'd be okay with accepting a PR implementing what I described but I don't see a huge need for it.

**Comment by philippjfr** [comment]
That said it's worth considering how this fits into the Image/GridImage discussion. As part of https://github.com/ioam/holoviews/pull/994 I've started implementing ``Image`` using the lbrt bound specification as a data interface, if we still want to move away from that, that PR is the time to do it.

**Comment by jlstevens** [comment]
I need to get my head around these issues again before I can make an in-depth comment. What I do know is that the (l,b,r,t) format is really annoying, if only because slices work ``[l:r, b:t]``. I'll have a look at the new PR and read through this issue properly to see if I can think of something better!

**Comment by philippjfr** [comment]
So the three proposals here are:

1. Support ``img[(l, r), (b, t)]``: This is already supported as a side-effect of select expanding tuples to slices
2. Support ``img[(l, b, r, t)]`` strong -1 from me because adding special semantics for a corner case seems like a bad idea
3. Allow Image to accept ``bounds=((l, r), (b, t))``: I'd be okay with this but also don't see a pressing need.

So unless someone really wants to implement 3. I don't think there's any action to be taken. Therefore I'm going to close, please open a new issue with an appropriate title if you think accepting ``bounds=((l, r), (b, t))`` is a good idea.
