### ISSUE TITLE
Clean up top-level namespace

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#2202]
I'd like to clean up the top-level namespace, here's what I don't think belongs there:

Element, Element2D, Element3D, Dimensioned, AttrTree, NdMapping, Overlayable, StoreOptions, BoundingBox, UniformNdMapping,  ViewableElement, Overlayable, CompositeOverlay

If possible I'd also like to suppress these from showing up on the module level dir:

 absolute_import, f, pydoc, print_function, hv, np, os, param, warnings

**Comment by jlstevens** [comment]
I think I agree with that list.
