### ISSUE TITLE
For Bars plots, xrotation rotates only one of multiple levels on the x axis

### ISSUE THREAD

**Issue by Gerenuk** [ioam/holoviews#2204]
When trying to rotate x-labels of a Bars plot with multiple levels, only the inner-most label is rotated.

```
import holoviews as hv

%%opts Bars [xrotation=90]
hv.Bars((["a"], ["b"], 1), kdims=["A", "B"])
```

In this case `"a"`  is not rotated, which is probably not what the user expects.

**Comment by philippjfr** [comment]
Agreed, it's not quite clear to me yet whether this is a limitation in bokeh's categorical axes or whether we're simply not using it correctly.

**Comment by 365perspectives** [comment]
Are there any updates on that matter?
The rotation feature for multiple levels would be highly appreciated.

**Comment by philippjfr** [comment]
This is now possible in bokeh so I'll try to expose it for the next release.

**Comment by philippjfr** [comment]
Duplicate of https://github.com/ioam/holoviews/issues/2515, still planning to implement this for 1.11.
