### ISSUE TITLE
Curve plot disappears for Bokeh for large zooming

### ISSUE THREAD

**Issue by Gerenuk** [ioam/holoviews#2208]
It seems when box-zoom or using other range limits like redim.range, plots may just disappear for Bokeh even though there should be points to display

```
import holoviews as hv
import numpy as np
hv.notebook_extension("bokeh")

hv.Curve(np.linspace(-10, 10, 100)**10).redim.range(y=(-10,1000))   # this will work with y=(-10,10000)
```

**Comment by philippjfr** [comment]
Cannot reproduce using master and latest bokeh.
