### ISSUE TITLE
holoviews   and  JupyterLab

### ISSUE THREAD

**Issue by maajdl** [ioam/holoviews#2212]
Hello,

I just tried some holoviews graph with  JupyterLab.
I used a Jupyter Notebook that worked perfectly.
Using it from JupyterLab, nothing was displayed.

Would you have any suggestion?
Would that be a JupyterLab issue, or an Holoviews issue?

Thanks,

Michel

**Comment by jlstevens** [comment]
We will be getting HoloViews working with JupyterLab once we figure out how to update the code using the Jupyterlab comms. As this issue is a duplicate of #687, I'll close this one and we can continue discussion there.
