### ISSUE TITLE
Release to conda-forge and defaults simultaneously

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#2217]
For 1.10 the plan is to to update the recipe on conda-forge and then immediately get that recipe onto anaconda ``defaults`` channel so ``conda install holoviews`` works without specifying a channel. The goal is to move away from using the ioam channel and maybe use the holoviews channels for 'nightlies' (actually automated packages for PRs merged to master).

**Comment by ceball** [comment]
Is the plan that 'latest master' conda packages for param (+gui toolkits) would also be uploaded to the holoviews channel?

**Comment by jlstevens** [comment]
I'm not sure how much of that is 'holoviews', so maybe we should make a general 'pyviz' channel?

**Comment by jbednar** [comment]
A pyviz channel seems like an excellent idea.

**Comment by jbednar** [comment]
_Instead_ of a holoviews channel.

**Comment by jlstevens** [comment]
That would be fine by me..the holoviews channel never really got used.

**Comment by ceball** [comment]
Yes, fine with me. I asked because I'm keen for there to be as few channels as possible...ideally just one even...

**Comment by jlstevens** [comment]
I've registered pyviz on anaconda.org so we can start using that...

**Comment by jakirkham** [comment]
Would there be any interest in doing dev releases on conda-forge? Just noticed 1.10.0a1 got tagged so figured I'd ask. ;)

**Comment by jlstevens** [comment]
@jakirkham I'm not against this idea, especially if it can be automated. 

If it can't be automated, then it means these releases are more work to do which means they are more likely to be infrequent (something we are currently trying to get away from!)

**Comment by jlstevens** [comment]
Or alternatively, if someone else is willing to update conda-forge for dev releases. :-)

**Comment by jakirkham** [comment]
There's been some work on an autoupdate bot. It's very new and docs are scarce. That said, most maintainers don't need to do anything with it per se. However it could learn a few things like how to update the dependencies or other recipe metadata. Though it's pretty good for being around a little over 1wk. :)

Was asking as this particular dev release was interesting to me. That said, can't promise that I'll always be able to update all dev releases. Hope you understand. :)

**Comment by jlstevens** [comment]
Looks like the autoupdate bot will ignore alphas: https://github.com/conda-forge/holoviews-feedstock/pull/25

Shame as dev builds from ``-c conda-forge/label/dev`` would have been nice!

**Comment by jakirkham** [comment]
Yeah I agree.

It's a little complicated as handling every projects' dev releases likely comes with a significant burden resource-wise and maintenance-wise. OTOH it's a really nice service to provide to developers and users. Not sure the right way to untangle it ATM, but did [leave a note along these lines]( https://github.com/regro/cf-scripts/issues/86#issuecomment-372406868 ).

**Comment by jlstevens** [comment]
Dev builds are now configured on conda-forge for holoviews:

```
conda install -c conda-forge/label/dev holoviews
```

This is just a reminder for myself to update the source correctly in ``meta.yaml`` on the feedstock master when 1.10 is released.

**Comment by philippjfr** [comment]
I've closed the other conda-forge related issue and would like to close this one too. @jlstevens If you want to record anything here, I'd prefer opening a packaging meta-issue to describe anything we need to remember during our migration to pyct.

**Comment by philippjfr** [comment]
On second thought, please do open such a issue if you think it's a good idea but this issue seems to be specifically about 1.10 and mentions long outdated plans about a holoviews channel so I'm closing as I'm cleaning up in anticipation for a 1.11 release and reassigning issues to the 1.11.x release series.
