### ISSUE TITLE
Difficulty installing examples

### ISSUE THREAD

**Issue by relativistic** [ioam/holoviews#2230]
Hi,

After installing holoviews using conda on OSX, I wanted to install the holoviews examples. However, there was not holoviews command available after installing from the ioam channel. 

```log
 % conda install -c ioam holoviews bokeh
... install proceeds as normal...
% holoviews --install-examples
zsh: command not found: holoviews
```

Interestingly, if I install holoviews without specifying the ioam channel, I get a holoviews command, but it crashes:

```log
% conda install holoviews bokeh
Solving environment: done

## Package Plan ##

  environment location: /Users/cpl29573/anaconda3

  added / updated specs:
    - bokeh
    - holoviews


The following packages will be UPDATED:

    holoviews: 1.6.2-py36_0 ioam --> 1.9.1-py36h11923e7_0

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

% holoviews --install-examples
Traceback (most recent call last):
  File "/Users/cpl29573/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 664, in _build_master
    ws.require(__requires__)
  File "/Users/cpl29573/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 981, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/cpl29573/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 872, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (param 1.4.2 (/Users/cpl29573/anaconda3/lib/python3.6/site-packages), Requirement.parse('param<2.0,>=1.5.1'), {'holoviews'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cpl29573/anaconda3/bin/holoviews", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/Users/cpl29573/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3138, in <module>
    @_call_aside
  File "/Users/cpl29573/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3122, in _call_aside
    f(*args, **kwargs)
  File "/Users/cpl29573/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3151, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/cpl29573/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/Users/cpl29573/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 679, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/Users/cpl29573/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 867, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'param<2.0,>=1.5.1' distribution was not found and is required by holoviews
```

**Comment by jlstevens** [comment]
Thanks for reporting this. 

I'm using OSX and I check the holoviews command installs examples after each release, but it looks like it might work for me and not for other people (despite testing in a clean conda environment). 

It looks like the required param version might not be on the defaults conda channel. My only other suggestion right now is to try ``conda-forge``, does the version installed using ``conda install -c conda-forge holoviews`` work?

**Comment by relativistic** [comment]
Hi,

So,  is the ioam channel not the correct way to install holoviews? Should it be done by the default channel instead?

In any case, your suggestion worked, although I also had to explicitly do:  `conda install -c conda-forge param`. Installing just holoviews from conda-forge did not seem to update param.

I should mention, I have only recently migrated from a Canopy enthought/edm installation, so I am somewhat new to conda. I might be doing something subtly wrong on my end.

Thanks!
Caleb

**Comment by jlstevens** [comment]
> So, is the ioam channel not the correct way to install holoviews?

Yes, it should work properly although ``conda-forge`` is now an equally valid way to get HoloViews. As it is a different channel, I figured it might avoid the param dependency issue you encountered.

> Installing just holoviews from conda-forge did not seem to update param.

I find that rather surprising, what conda version do you have?

Anyway, to double check, I just created a fresh conda environment and installed holoviews from the ioam channel and the examples install fine (I am also on OSX). I am reluctant to close this issue in case there is a real issue that needs addressing that I can't reproduce on on my system.

**Comment by relativistic** [comment]
I'm reluctant to alter my production system further, but I'll try doing a clean install of this on a separate system in the near future, to see if I can reproduce it.

**Comment by ceball** [comment]
> It looks like the required param version might not be on the defaults conda channel

The latest version of param is "on the defaults conda channel": if you `conda install param` you'll get 1.5.1. However, if you `conda install holoviews`, you will get an older version of param (at least on macos - not sure about elsewhere).

**Comment by jlstevens** [comment]
Thanks for looking into this @ceball.

> if you conda install param you'll get 1.5.1. However, if you conda install holoviews, you will get an older version of param (at least on macos - not sure about elsewhere).

That is rather odd, as the package on the 'defaults channel' is supposed to be built off the [conda-forge recipe](https://github.com/conda-forge/holoviews-feedstock/blob/master/recipe/meta.yaml) which works correctly (on conda-forge at least) and does not pin anything to older versions. I'll have to find out why it tries to downgrade param...

**Comment by jlstevens** [comment]
The issue is the lancet dependency that has now been removed. I got 1.9.2 onto defaults so this should no longer be a problem.

@relativistic Can you confirm that it now works without needing to use conda-forge? You should get version 1.9.2 and if that works I can close this issue.

**Comment by relativistic** [comment]
Sorry, not a github frequenter, and missed the message. Yes, I get 1.9.2, and examples get installed correctly.

**Comment by philippjfr** [comment]
Thanks for getting back to us in any case!
