### ISSUE TITLE
QuadMesh bin edges getting munged?

### ISSUE THREAD

**Issue by txlouder** [ioam/holoviews#2232]
Hi,

QuadMesh seems to be altering/adjusting/munging the bin edges supplied.  See trivial example below where I create a QuadMesh with one set of bin edges.  When I subsequently read out the edges, they are a completely different set.  Only the first and last bin edges are unaltered. 

import numpy as np
import pandas as pd
import holoviews as hv

x = np.array(sorted(1000*np.random.random(10)))
​
for i in range(len(x)):  print('%20.6f' % x[i])

          156.398070
          283.736783
          390.115061
          552.175220
          554.453313
          554.784756
          610.334261
          813.045554
          959.768363
          999.989470

y = np.ones(10)
​z = np.ones([10,10])
​qm = hv.QuadMesh((x, y, z), ['x', 'y'], ['z'])
​
for i in range(len(x)):  print('%20.6f %20.6f' % (x[i], qm['x'][i]))

          156.398070           156.398070
          283.736783           278.496674
          390.115061           404.035531
          552.175220           512.229703
          554.453313           553.966650
          554.784756           568.589271
          610.334261           647.124708
          813.045554           799.048433
          959.768363           933.142938
          999.989470           999.989470`

**Comment by ea42gh** [comment]
```
np.random.seed(123)
x = np.array(sorted(1000*np.random.random(10)))
y = np.linspace(0,9,10)
z = np.random.normal(size=(n,n))
```
yields even more puzzling y-values
and white stripes, e.g., at x=600 and x=800

**Comment by jlstevens** [comment]
Thanks for reporting this.

``QuadMesh`` has recently been given a new data interface so it looks like there may be some issues there. I agree explicitly supplied bin edges should not be changed if possible.

**Comment by philippjfr** [comment]
Could you confirm which version you are using?

**Comment by philippjfr** [comment]
After #2237 everything mentioned in this issue is now behaving like I'd expect.
