### ISSUE TITLE
Points size options affecting color?

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#224]
I'm trying to use Points with scaling of both size and color from the same dimension, but running into problems:

http://nbviewer.ipython.org/url/homepages.inf.ed.ac.uk/jbednar/gdelt-bug.ipynb

The first plot seems to work fine, using color to represent the tone (ranging over +/- 30).  In the second plot, what I wanted to do was to have the point size increase for large absolute values of the tone, such that points with a tone of 10 or of -20 would show up much larger than the others that are clustered around tone=0, so that these points would be more noticeable.  The point size does increase when I do this, but for some reason all of the cooler colors have disappeared (the blues)!  Am I right in thinking that even if negative "size" values were to cause some problem with the *size* calculations, they shouldn't be causing problems with the *color* of the points?

**Comment by philippjfr** [comment]
Strange, will have to look into it.

**Comment by philippjfr** [comment]
Well if the negative sizes are causing issues then the points might not show up at all, which would explain this effect. I suppose there's different ways of computing sizes including taking the absolute values as you are wanting to do or normalize them beforehand. Is that another plot option do you think?

**Comment by jbednar** [comment]
Good point; those points might be getting truncated at size zero, and thus not showing up.   I guess that's one of three potentially useful size options: absolute value, normalize, and truncate.   I guess one might reasonably wish for the ability to accept any function there, so should we just have it accept a function that we'll assume works like a numpy ufunc?  There are already ufuncs np.abs and np.trunc, and we've got various normalization functions in imagen that could be supplied here.  I'd vote for something other than trunc to be the default, since trunc's behavior is to cover up values while holoviews is meant for revealing the data.

**Comment by philippjfr** [comment]
This has now been implemented, both the matplotlib and bokeh implementations now support a ``size_fn`` to process the values before they are scaled, this has been set to ``np.abs`` by default. I'll close the issue now.
