### ISSUE TITLE
Warnings in the Live Data user guide

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#2250]
I am seeing the following warnings:

![image](https://user-images.githubusercontent.com/890576/34723878-e93c1f84-f543-11e7-82b7-d78ad70b45e9.png)

It seems to be a zero division error (the warnings disappear if ``0`` isn't the first argument) although the warnings don't say that. For some reason, the error seems to originate from ipykernel instead of from the callback...

**Comment by jlstevens** [comment]
I didn't look closely enough..it does say it is zero division - I had expected a dedicated exception. Apparently this is how numpy always raises such errors. In that case, the question is why the warning doesn't say it is issues from the callback. Anyhow, the notebook does need updating.

**Comment by philippjfr** [comment]
Maybe just change the alpha value not to be zero.
