### ISSUE TITLE
Adjoining with Empty fails when using DynamicMap

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#2274]
With a simple ``Image``, I can do:

![image](https://user-images.githubusercontent.com/890576/35453968-fdebe3f0-02c3-11e8-9ab3-da341d55913d.png)

But if I use a ``DynamicMap`` it fails, for instance using ``regrid``:

```python
im = hv.Image(np.random.rand(100,100))
dmap = regrid(im)
dmap << hv.Empty() << dmap.hist(adjoin=False)
```

The exception says 'TypeError: Cannot append Empty to a AdjointLayout':

![image](https://user-images.githubusercontent.com/890576/35454024-3ac252b4-02c4-11e8-8fe5-6942f9cde41b.png)

**Comment by philippjfr** [comment]
Closed via #2275
