### ISSUE TITLE
Buffering

### ISSUE THREAD

**Issue by issler92** [ioam/holoviews#2297]
In this page: http://holoviews.org/user_guide/Streaming_Data.html
There is this bit code:

> %%opts Curve [width=500 show_grid=True]
source_df = streamz.dataframe.Random(freq='5ms', interval='100ms')
sdf = (source_df-0.5).cumsum()
raw_dmap = hv.DynamicMap(hv.Curve, streams=[**Buffer(sdf.x)**])
smooth_dmap = hv.DynamicMap(hv.Curve, streams=[**Buffer(sdf.x.rolling('500ms').mean())**])
raw_dmap.relabel('raw') * smooth_dmap.relabel('smooth')

used to stream a random series and its mean to a graph.

How can I create my own buffer? I already have a function, let's call it 'getBuffer(input)', that returns me the values which I want to feed my buffer (as int). How can I invoke streamz.Stream.buffer() along with my custom getBuffer() function to get what I want (namely a streamz buffer)? I know I would have to feed a '**Streamz Buffer**' type in the boldfaced area, but _I don't know how to call streamz.Stream.buffer()_.

**Comment by issler92** [comment]
ps: I'm completely new to streamz and holoviews.

**Comment by philippjfr** [comment]
Apologies for the delay in replying. I suggest you skip ``streamz`` and just use ``Buffer``directly, which is documented in that tutorial. Since this is a support question I'll close the issue but you can join us on Gitter: https://gitter.im/ioam/holoviews
