### ISSUE TITLE
Errors when nesting Overlays and DynamicMaps

### ISSUE THREAD

**Issue by shenker** [ioam/holoviews#2298]
The stacktraces below were from `master` (as of last night), but I first ran into all these problems on the latest stable.

Following up on some questions I asked on gitter. I start with a analysis function that dynamically generates holoviews objects, possibly Overlays/Layouts, that include large Images and/or Curves. My goal is to regrid all Images (and datashade all Curves). For the following minimal test case, I precompute these holoviews plots and store them in dicts (dat1 and dat2); in my production code, these may be cached in a dict or dynamically generated (so `z` needs to be a kdim of a DynamicMap, not a HoloMap).

Set up the plots:
```python
import numpy as np
import holoviews as hv
from holoviews.operation.datashader import datashade, regrid
hv.notebook_extension('bokeh')
dat1 = {}
dat2 = {}
for z in range(10):
    dat1[z] = hv.Image(np.random.random((1000,1000)), bounds=(0,0,10,10)) * hv.HLine(z)
    dat2[z] = hv.Curve((np.random.random(1000) - 0.5).cumsum()) * hv.VLine(z*100)
```

With no datashader, this works as expected:
```python
def cb(z):
    return dat1[z]
dmap = hv.DynamicMap(cb, kdims=['z']).redim.values(z=range(10))
dmap
```
It shows a slider for `z`, and I can easily browse around.

It would be great to be able to write `dmap.map(regrid, hv.Image)` and have that work. Maybe one day? :) I assumed I needed to call `.map()` before I combine all the z-slices into a DynamicMap, like this:
```python
def cb(z):
    return dat1[z].map(regrid, hv.Image)
dmap = hv.DynamicMap(cb, kdims=['z']).redim.values(z=range(10))
dmap
```

This fails. Stacktrace: https://gist.github.com/shenker/16b66fda15093544e9d86d69a60a12af

Heeding the warning message about `.collate()`, I try:
```python
def cb(z):
    return dat1[z].map(regrid, hv.Image).collate()
dmap = hv.DynamicMap(cb, kdims=['z']).redim.values(z=range(10))
dmap
```

This also fails, with the same error. With either of these, if instead of displaying `dmap`, I display, e.g., `dmap[4]`, I get an individual image and the dynamic regridding works just fine (obviously, no scroll bar for `z`).

I was wondering if this issue was specific to `hv.Image`, so I also tried the above substituting `dat1` with `dat2` and `regrid` with `datashade`, but this failed in similar ways.

Returning to the original working example without datashader,
```python
def cb(z):
    return dat1[z]
dmap = hv.DynamicMap(cb, kdims=['z']).redim.values(z=range(10))
```

If I try simply `dmap.collate()`, I get this [stacktrace](https://gist.github.com/shenker/8d6bcf93706c689dd9b7030be4a54577) when I use `dat1` (with Images) and this [stacktrace](https://gist.github.com/shenker/c2020c134ed215d815be8e01b74eaa36) when I use `dat2` (with Curves).

**Comment by shenker** [comment]
I tried playing around `split_overlays` having applied PR #2286.
```python
dmaps = dmap.split_overlays()
dmaps
```
gives me
```
([('Image', 'I'), ('HLine', 'I')], [:DynamicMap   [z]
     :Image   [x,y]   (z), :DynamicMap   [z]
     :HLine   [x,y]])
```

If I then try `regrid(dmaps[1][0])`, the initial (z=0) data regrids properly (I can zoom/pan around), but when I move the z-slider to any value besides 0 the plot is blank.

**Comment by philippjfr** [comment]
The main issue here is that the ``regrid`` operation is ``dynamic`` by default which allows it to respond to zoom events on the axes, but you cannot nest DynamicMaps. So the appropriate solution is either to restructure your code or use the ``regrid`` operation in non-dynamic mode.

The first approach would look like this:

```python
dat1 = {}
dat2 = {}
for z in range(10):
    dat1[z] = hv.Image(np.random.random((1000,1000)), bounds=(0,0,10,10))
    dat2[z] = hv.Curve((np.random.random(1000) - 0.5).cumsum())

hlines = hv.DynamicMap(lambda z: hv.HLine(z), kdims='z')
images = hv.DynamicMap(lambda z: dat1[z], kdims='z')
(regrid(images) * hlines).redim.values(z=range(10))
```

Alternatively the approach of using a non-dynamic ``regrid`` and supplying the RangeXY stream yourself would look like this:

```python
dat1 = {}
dat2 = {}
for z in range(10):
    dat1[z] = hv.Image(np.random.random((1000,1000)), bounds=(0,0,10,10)) * hv.HLine(z)
    dat2[z] = hv.Curve((np.random.random(1000) - 0.5).cumsum()) * hv.VLine(z*100)

def cb(z, x_range, y_range):
    return dat1[z].map(regrid.instance(dynamic=False, x_range=x_range, y_range=y_range), hv.Image)
dmap = hv.DynamicMap(cb, kdims=['z'], streams=[hv.streams.RangeXY()]).redim.values(z=range(10))
dmap
```

If you don't need dynamic regridding you can skip that part entirely:

```
dmap = hv.DynamicMap(cb, kdims=['z'], streams=[hv.streams.RangeXY()]).redim.values(z=range(10))
dmap.map(regrid.instance(dynamic=False), hv.Image)
```

**Comment by philippjfr** [comment]
If you're working with a small set of elements and declaring them ahead of time I'd recommend just using a HoloMap btw. Here's how I'd write your example:

```
dat1, hlines = {}, {}
for z in range(10):
    dat1[z] = hv.Image(np.random.random((1000,1000)), bounds=(0,0,10,10))
    hlines[z] = hv.HLine(z)
    
regrid(hv.HoloMap(dat1, 'z')) * hv.HoloMap(hlines, 'z')
```

**Comment by philippjfr** [comment]
Going to close this as I think everything is behaving as expected and this is mostly a usage question. If there's something that's not clear enough in the docs or you think something should behave differently please reraise a more specific issue.

**Comment by jbednar** [comment]
> The main issue here is that the regrid operation is dynamic by default which allows it to respond to zoom events on the axes, but you cannot nest DynamicMaps. 

Would it be possible to detect nested DynamicMaps and raise an error with your suggestions above?  It sounds like the current behavior is very confusing, i.e. that it gives a blank plot rather than some more direct indication that something that *seems* reasonable is not supported.
