### ISSUE TITLE
holomap with kdims fails

### ISSUE THREAD

**Issue by resenganalytics** [ioam/holoviews#2302]
Hi,

I am trying to run your following example on bokeh server. It fails with dimension error for kdims parameter in HoloMap: 
> Dimensions  specified as a tuple must be a tuple consisting of the name and label not: (Dimension('phase'), Dimension('frequency'))

```python
import numpy as np
import holoviews as hv
import pandas as pd
from bokeh.io import curdoc


frequencies = [0.5, 0.75, 1.0, 1.25]
phases      = [0, np.pi/2, np.pi, 3*np.pi/2]
def sine_curve(phase, freq):
    xvals = [0.1* i for i in range(100)]
    return hv.Curve((xvals, [np.sin(phase+freq*x) for x in xvals]))

curve_dict_2D = {(p,f):sine_curve(p,f) for p in phases for f in frequencies}
hmap = hv.HoloMap(curve_dict_2D, kdims=['phase', 'frequency'])
doc = hv.renderer('bokeh').server_doc(hmap, doc=curdoc())
```
I tried all 1.8.? versions of Holoviews. My bokeh version is 0.12.13 and am running on Ubuntu 16.04
Any idea why it is failing to show the interactive plot using Holomap?
Thanks

**Comment by philippjfr** [comment]
See https://github.com/ioam/holoviews/issues/2301, this is fixed in master and we should have a new release soon.
