### ISSUE TITLE
Matplotlib raster based plots should ignore origin

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#2303]
As a user had to figure out through a lot of pain, the raster plots in matplotlib use the global origin setting which can be overwritten in the matplotlibrc. The plots should not respect this option since it results in wrong plots. (See https://github.com/ioam/holoviews/issues/2258 for more detail)

**Comment by laleph** [comment]
This should overwrite the matplotlibrc setting for raster, rgb, hsv and image.

**Comment by laleph** [comment]
Why is class ImagePlot unused? Is it orphaned?

**Comment by philippjfr** [comment]
>Why is class ImagePlot unused? Is it orphaned?

Looks like it, thanks for the contribution! Really appreciated.
