### ISSUE TITLE
Tables and mpld3

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#231]
When using the mpld3 backend, Tables are not shown as HTML table, but as empty axes object.

**Comment by philippjfr** [comment]
Yes, mpld3 does not support rendering of matplotlib tables and probably won't do so in the near future. There's already an issue on the topic on mpld3 (https://github.com/jakevdp/mpld3/issues/281). There's nothing we can do to make this work I'm afraid so I'm closing this issue.
