### ISSUE TITLE
VectorField get_min_distance functionality very slow

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#2313]
When plotting a VectorField it tries to find the minimum distance between vectors to find an appropriate value to scale the vector size by. This operation is incredible slow taking up 10 seconds for a 200x200 field. There must be some way to make it faster or at least it should be possible to disable (it currently runs even when it's unused).

**Comment by jlstevens** [comment]
Lots and lots of distance calculations will be slow. There must be a less computationally expensive approach...

**Comment by jbednar** [comment]
Whoa, that does need some attention!
