### ISSUE TITLE
Allow dictionaries as Dimension specs

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#2315]
When constructing an element and you want to supply explicit dimension ranges (or values, or any of the other Dimension attributes) you currently have to supply explicit ``Dimension`` objects or use ``redim`` after the fact:

```python
hv.Image(..., vdims=hv.Dimension('Temperature', range=(0, 30)))

hv.Image(..., vdims='Temperature').redim.range(Temperature=(0, 30))
```

Being able to define Dimensions with dictionaries in the constructor can in some cases be nicer and more readable:

```python
hv.Image(..., vdims={'name': 'Temperature', 'range': (0, 30)})
```

and also just matches what is already valid in ``redim``:

```python
hv.Image(...).redim(z={'name': 'Temperature', 'range': (0, 30)})
```

**Comment by jlstevens** [comment]
I don't have any strong objection to this really. My main concern is that there may be too many ways of doing the same thing already and that impacts readability.
