### ISSUE TITLE
Conversions should accept Dimension objects not just strings

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#232]
In the conversion from a table to a curve, one can select which vdim has to be used. However, this can only be a string, not a dimension. This will not work:
```
hv.Layout([params.to.curve(kdims='Power',vdims=vdim)  for vdim in params.vdims])
```
But this works:
```
hv.Layout([params.to.curve(kdims='Power',vdims=vdim.name)  for vdim in params.vdims])
```

**Comment by philippjfr** [comment]
True, this is the case almost everywhere. This would be a fairly straightforward project for someone new to HoloViews development to tackle. It's not a priority for me so if you or anyone else wants to make this work please submit a PR.

**Comment by philippjfr** [comment]
Addressed in the commit referenced above. Closing.
