### ISSUE TITLE
hv.Cycle() does not cycle through the entire list of colors

### ISSUE THREAD

**Issue by ahuang11** [ioam/holoviews#2333]
After the 5th color, it starts from the first.

``` python
color_cycle = hv.Cycle([
                   'red',
                   'yellow',
                   'orange',
                   'green',
                   'blue',
                   'gray',
                   'black',
                   'brown',
                   'purple',
                   'pink'
                   ])

%%opts Curve (line_color=color_cycle)
ds.to.curve('target', 'valid_z', ['lead']).overlay()
```

![image](https://user-images.githubusercontent.com/15331990/36068554-ca6111b4-0e9d-11e8-9438-508b444ce10d.png)

**Comment by philippjfr** [comment]
I believe this is because all cycles get tied together and since there is already a Cycle on ``color`` that one defines the length. I'd be strongly in favor of changing that behavior.

**Comment by ahuang11** [comment]
A hack would be to just to double/triple the length `color` by repeating it. That way, the length would also be doubled/tripled without the default color list changed?

i.e if `color` was defined like this:
```
color = ['red', 'yellow',  'orange', 'green', 'blue'] * 2
```

Also is there a workaround for cycling through more than 5 colors?

**Comment by philippjfr** [comment]
In this case I'd just override the default color cycle like this ``color`` is an alias for ``line_color`` in this case, with the latter taking precedence:

```python
%%opts Curve (color=color_cycle)
ds.to.curve('target', 'valid_z', ['lead']).overlay()
```

**Comment by ahuang11** [comment]
Oh, awesome; that worked. Is there a workaround for box-whisker plots?

`Unexpected style option 'color' for BoxWhisker in loaded backend 'bokeh'.`

**Comment by jlstevens** [comment]
I agree..the shortest cycle shouldn't determine the length of the overall cycle. It should be the opposite and loop to match the longest cycle definition...

**Comment by ahuang11** [comment]
To answer my own question, the style options `cmap` works for box-whisker plots.
