### ISSUE TITLE
Updating Tutorials to new notebook format

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#234]
IPython 3.0 has now been out for quite a while and I expect most people will have upgraded. Now that Jupyter has been released we should therefore definitely consider upgrading the Tutorials to the newer notebook format, IPython 3 and Jupyter users are always confronted with the conversion notice. Also even if someone is stuck with IPython 2, they backported an automatic conversion functionality so they will still be able to use it. Therefore my vote is to upgrade the Tutorials asap.

**Comment by jlstevens** [comment]
> Also even if someone is stuck with IPython 2, they backported an automatic conversion functionality so they will still be able to use it. Therefore my vote is to upgrade the Tutorials asap.

This was definitely true between IPython 2 and 3 - each version could open notebooks generated in the other. I may be mistaken but when trying Jupyter recently, I do think I saw some notebooks that would not open properly in one of the two versions I was testing (IPython 2 vs Jupyter).

Although it is probably worth double checking,  it matters too much as I agree that we should be switching to the new format regardless.

**Comment by jbednar** [comment]
There are definitely many combinations of versions that won't work; it's only the latest IPython 2 that works, which doesn't help people who have IPython from a canned distribution without a new enough IPython 2.  In any case, we tell everyone to use Anaconda now, and so should have it set up to work smoothly with what they'll get from that (Jupyter).

**Comment by philippjfr** [comment]
This has been done as of commit https://github.com/ioam/holoviews/commit/9cc09d0f637dc9d240421bd964397efbe97850df. Closing.
