### ISSUE TITLE
Unable to create independent axes for each subplot in any grid layout

### ISSUE THREAD

**Issue by rtmatx** [ioam/holoviews#2343]
I created a grid layout for 9 different tags of a pandas dataframe (time series data) with x-axis as timestamp and y-axis as the tag value. Time range is constant across all the columns as they are different measurements in the same timeframe. 

After creating the plot, I noticed that the y-axis and x-axis are share across all the plots. Is there any parameter to stop sharing axis (x/y/both). 

I used the following code to create subplots with the help of  `hv.Layout` function. Is there any other method to create these subplots using datashader without sharing axes.

```
def apply_formatter(plot, element):
    plot.handles['xaxis'].formatter = DatetimeTickFormatter()

def f(tag_list, start, end):  # functions takes in list of tags (length 9), star & end time of the plot
    
    %%opts RGB [finalize_hooks=[apply_formatter] width=500 height=300 show_grid=False]
    
    def ds_plot(tag):
        time = df.loc[start:end].index.values.astype('int64')/10**6 # df index is time 
        tag_to_plot = df.loc[start:end][tag]  
        plot = hv.Scatter((time, tag_to_plot))
        d = datashade(plot))
        return d
    
    ds_dict = {tag:ds_plot(tag) for tag in tag_list}
    
    first_row = [ ds_dict[i] for i in tag_list[:3]]
    second_row = [ ds_dict[i] for i in tag_list[3:6]]
    third_row = [ ds_dict[i] for i in tag_list[6:9]]
      
    layout = hv.Layout(first_row + second_row + third_row).cols(3)  # plot in 3 rows and 3 columns
    
    return layout
```

**Comment by philippjfr** [comment]
The easiest way to stop them from being shared is by labeling the dimensions on your scatter, in your case you would do:

```python
plot = hv.Scatter((time, tag_to_plot), 'Time', tag)
```

Alternatively you can disable shared axes as a normalization option using so called normalization options, which you can set using the ``%%opts`` magic with ``%%opts RGB {+axiswise}`` or using ``.opts`` like this:

```python
d = datashade(plot)).opts(norm={'axiswise': True})
```

**Comment by rtmatx** [comment]
Thanks. Both of the methods worked. Using first method, I can share just x-axis (time) while keeping y-axis(tag values) independent for each subplot.
