### ISSUE TITLE
cannot redim the range of an Overlay

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#2347]
```python
(hv.Path([]) * hv.Scatter([])).redim.range(x=(-1, 2))
```
doesn't set the x-axis to (-1, 2).

**Comment by jlstevens** [comment]
This is almost certainly due to the lack of data in the elements, but it ought to work.

**Comment by philippjfr** [comment]
Yes I suspect it's this line https://github.com/ioam/holoviews/blob/master/holoviews/plotting/plot.py#L951

``if layer and subplot.apply_ranges:`` should be ``if layer is not None and subplot.apply_ranges:``

**Comment by basnijholt** [comment]
Do you know if there is a way to "hack around" this bug?

In `adaptive` we already [know the xlims when plotting a 1D line/scatter](https://github.com/python-adaptive/adaptive/blob/master/adaptive/learner/learner1D.py#L292).

Now if you plot when there is no data yet, and the data arrives later, you would need to zoom out to find that out.
