### ISSUE TITLE
Columnar Data

### ISSUE THREAD

**Issue by WolframStrauss** [ioam/holoviews#2356]
Both tables are not equal. Is this behaviour wanted?

xs = range(10)
ys = np.exp(xs)

table = hv.Table((xs, ys), kdims=['x'], vdims=['y'])
table2 = hv.Table([xs, ys], kdims=['x'], vdims=['y'])
table + table2

**Comment by philippjfr** [comment]
This is indeed expected, tuples are interpreted as column while lists are interpreted as rows. At this point it seems very unlikely that we can change this but I'll let others chime in before closing this outright.
