### ISSUE TITLE
[Request] Changing default Pallete in hv.Curve().groupby()

### ISSUE THREAD

**Issue by andrethrill** [ioam/holoviews#2365]
I am plotting a melted dataframe wich contains different signals. I am using `Bokeh` backend and  `hv.Curve` with `.groupby`. This works great!

But I can't find a way of changing the plotting default colors... I tried to use `cmap`, `color` and `colors` keywords for plot_opts and style_opts to apply different `Palletes` but nothing seems to work...

*I'm including full code for reproducibility.*

# Versions

- numpy==1.14.0
- pandas==0.22.0
- holoviews==1.9.2
- bokeh==0.12.13

***

<details>
<summary>Init code</summary>

# Imports

```python
import numpy as np
import pandas as pd
import random
import holoviews as hv
hv.extension('bokeh')
```

# Generation and plotting functions

```python
#generate dummy df
def generate_df(size):
    d = {
        'dates':
        pd.date_range('1980-01-01', periods=size, freq='1T'),
        'signal1':
        np.random.normal(0, 0.3, size=size).cumsum() + 50,
        'signal2':
        np.random.normal(0, 0.3, size=size).cumsum() + 50,
        'signal3':
        np.random.normal(0, 0.3, size=size).cumsum() + 50,
    }

    df = pd.DataFrame(d)

    return df.melt(id_vars=['dates'])
```

</details>

***

# Generate df

Let's generate a small df:

```python
df = generate_df(1000)
df.head()
```

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>dates</th>
      <th>variable</th>
      <th>value</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1980-01-01 00:00:00</td>
      <td>signal1</td>
      <td>49.774098</td>
    </tr>
    <tr>
      <th>1</th>
      <td>1980-01-01 00:01:00</td>
      <td>signal1</td>
      <td>49.649267</td>
    </tr>
    <tr>
      <th>2</th>
      <td>1980-01-01 00:02:00</td>
      <td>signal1</td>
      <td>49.356741</td>
    </tr>
    <tr>
      <th>3</th>
      <td>1980-01-01 00:03:00</td>
      <td>signal1</td>
      <td>49.185726</td>
    </tr>
    <tr>
      <th>4</th>
      <td>1980-01-01 00:04:00</td>
      <td>signal1</td>
      <td>49.608141</td>
    </tr>
  </tbody>
</table>
</div>

```python
df.tail()
```

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>dates</th>
      <th>variable</th>
      <th>value</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>2995</th>
      <td>1980-01-01 16:35:00</td>
      <td>signal3</td>
      <td>48.086035</td>
    </tr>
    <tr>
      <th>2996</th>
      <td>1980-01-01 16:36:00</td>
      <td>signal3</td>
      <td>47.618977</td>
    </tr>
    <tr>
      <th>2997</th>
      <td>1980-01-01 16:37:00</td>
      <td>signal3</td>
      <td>47.801533</td>
    </tr>
    <tr>
      <th>2998</th>
      <td>1980-01-01 16:38:00</td>
      <td>signal3</td>
      <td>48.021422</td>
    </tr>
    <tr>
      <th>2999</th>
      <td>1980-01-01 16:39:00</td>
      <td>signal3</td>
      <td>48.272128</td>
    </tr>
  </tbody>
</table>
</div>

# Plot signals

```python
plot_opts=dict()
plot_opts['show_grid'] = True
plot_opts['width'] = 600
plot_opts['height'] = 400
plot_opts['legend_limit'] = 1000


curve_1 = hv.Curve( df,
             kdims=['dates'],
             vdims=['value', 'variable'],
             label='title').groupby('variable')


curve_1.overlay().opts(plot=plot_opts)
```

![unknown](https://user-images.githubusercontent.com/25300892/36489114-1da0633e-171d-11e8-831c-81ff6f0bb2a6.png)

# Questions

1. Is there a way to change the default `Pallete` and I am missing it?
2. If not, can it be implemented?

Thanks!

**Comment by ahuang11** [comment]
I think this works:
`curve_1.opts(style={'Curve': dict(color=hv.Cycle('RdBu'))})`

```
x = [1, 2, 3]
y1 = [3, 4, 5]
y2 = [3, 7, 4]
y3 = [6, 7, 2]

df = pd.DataFrame(x, y1)
df[1] = y2
df[2] = y3
df.columns = ['y1', 'y2', 'y3']
ds = hv.Dataset(df.melt().reset_index())
curves = ds.to.curve('index', 'value', 'variable').overlay()

curves.opts(style={'Curve': dict(color=hv.Cycle('RdBu'))})
```
![image](https://user-images.githubusercontent.com/15331990/36562973-532255dc-17de-11e8-9d3e-bbbf600a17c4.png)

**Comment by andrethrill** [comment]
Thanks @ahuang11  that worked great! Closing now.
