### ISSUE TITLE
Move common Bokeh options to BokehPlot

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#2369]
Right now, some Bokeh options like `toolbar` are defined in several locations, including `ElementPlot`, `GridPlot`, and `LayoutPlot`.  This works fine, but if you want to change the options globally, for all Bokeh plots, you have to figure out everywhere they are defined, and change each one:

```
from holoviews.plotting.bokeh import ElementPlot, GridPlot, LayoutPlot
ElementPlot.toolbar=None
GridPlot.toolbar=None
LayoutPlot.toolbar=None
```

I think we should look through the options defined and see if there are others like `toolbar` that are currently duplicated like this, and move them into a base class like `BokehPlot` where appropriate.

**Comment by jlstevens** [comment]
If there are any other common parameters (other than ``toolbar``) they should also be moved up if possible.
