### ISSUE TITLE
How to apply opts without using %% magic command

### ISSUE THREAD

**Issue by rtmatx** [ioam/holoviews#2376]
Hi,

Most of the tutorials that are available about holoviews uses `%%opts` command to change options. How can I change the options without using the magic commands but by using the function itself. I can see some tutorials using `.opts(opts_dict)` for `hv.Scatter, hv.Curve` methods. 

But how can I do it for something like `datashade` mentioned below. I am confused about the usage of these opts using functions. Is there any link to documentation or code where can I find the correct methods and options available for different methods?

```
def apply_formatter(plot, element):
    plot.handles['xaxis'].formatter = DatetimeTickFormatter()

def f(tag_list, start, end):  # functions takes in list of tags (length 9), star & end time of the plot
    
    %%opts RGB [finalize_hooks=[apply_formatter] width=500 height=300 show_grid=False]
    
    def ds_plot(tag):
        time = df.loc[start:end].index.values.astype('int64')/10**6 # df index is time 
        tag_to_plot = df.loc[start:end][tag]  
        plot = hv.Scatter((time, tag_to_plot))
        d = datashade(plot))
        return d
```

**Comment by jbednar** [comment]
`datashade` is an ["operation"](http://holoviews.org/user_guide/Transforming_Elements.html), which is a function that accepts a HoloViews Element and generally returns one, possibly of a different type.  Such functions have Parameters, and you can find out which Parameters it supports using ``hv.help(datashade)``.  HoloViews options are for Elements only, not operations, so you can't use the options syntax to set the parameters of an operation.  Instead, you can set them as arguments to the function (``datashade(...,width=500``), or as class attributes (to set the defaults for all subsequent calls to that operation (``holoviews.operation.datashader.datashade.width=500``).

But note that it's not always the parameters of the operation that you will want to set.  Instead, some things you might want to change are (or can be) done on the Element that gets *returned* from the operation.  For instance, ``datashade()`` returns an Element of type RGB, and you can set RGB options the same whether you are using datashade or not, i.e. either for a whole notebook (``%opts RGB [...]``, for a single cell (``%%opts RGB [...]`` at the *top* of the cell (only!)), or using ``.opts(...)`` (on the *result* of datashade).  Your RGB example above suggests that those are the types of settings you want to change, in which case just move that line to the start of the cell containing your plot (assuming you are in Jupyter).

Note that by default the result of ``datashade()`` is actually a `DynamicMap` that returns an ``RGB``,  if ``dynamic=True``, which might matter in some cases for option setting but shouldn't matter for the line and cell magic ``opts`` commands.

**Comment by rtmatx** [comment]
Thanks for the detailed comment. 

I can understand it quite clearly now. I have noticed that `hv.RGB` has couple of options( style and plot). so used `.opts(plot=)` to input some of the options like `width` and `height`.

The links also helped to look at more information regarding RGB and other options available for `hv.Scatter` and `hv.Curve`
