### ISSUE TITLE
Stack two images with np.nan

### ISSUE THREAD

**Issue by mlaprise** [ioam/holoviews#2387]
I'm not sure if it's an issue or the expected behaviour, but here my problem. Using datashader directly I can stack two images together using two colormaps where the top image is a "sparse" image, most value are np.nan (except the center square), the result looks like this: 

    agg1 = cvs.raster(img1_xr, upsample_method='linear')
    agg2 = cvs.raster(img2_xr, upsample_method='linear')

    img1 = tf.shade(agg1, cmap=viridis, how='linear')
    img2 = tf.shade(agg2, cmap=Hot, how='linear')

    img = tf.stack(img1, img2, how='over')
    tf.dynspread(img, threshold=0.5, max_px=4)

![screen shot 2018-03-02 at 8 49 32 am](https://user-images.githubusercontent.com/112564/36902294-fa27d374-1df7-11e8-97dc-def491797f76.png)

I tried to replicate this in holoviews but it's doesn't work:

    hv_image1 = hv.Image(np.flip(img1, axis=0).astype('float32'))(style={'cmap': 'viridis'})
    hv_image2 = hv.Image(np.flip(img2, axis=0).astype('float32'))(style={'cmap': 'hot'})

    hv.util.opts('Image [width=512 height=512 shared_axes=False logz=False] {+axiswise}')
    regrid(hv_image1) * regrid(hv_image2)
    # also try regrid(hv_image2) * regrid(hv_image1)

![screen shot 2018-03-02 at 9 01 52 am](https://user-images.githubusercontent.com/112564/36902416-616827f0-1df8-11e8-88c0-1caacae7fb41.png)

May be it's the expected result, I don't know. How could I replicate the first behaviour ?

holoviews version: 1.9.4-x-g73c2735e7
bokeh: 0.12.10

**Comment by philippjfr** [comment]
The datashader code you showed can be replicated exactly in HoloViews:

```python
from holoviews.operation.datashader import regrid, stack, shade, dynspread
from matplotlib.cm import get_cmap

viridis, hot = get_cmap('viridis'), get_cmap('hot')

img1 = np.random.rand(10, 10)
img2 = np.random.rand(10, 10)

hv_image1 = hv.Image(np.flip(img1, axis=0).astype('float32'))
hv_image2 = hv.Image(np.flip(img2, axis=0).astype('float32'))
shaded1 = shade(regrid(hv_image1), cmap=viridis)
shaded2 = shade(regrid(hv_image2), cmap=hot)
dynspread(stack(shaded1*shaded2, compositor='over'))
```

Alternatively you could set the NaN color for Images using the clipping_colors plot option: ``clipping_colors={'NaN': (0, 0, 0, 0)} ``.

**Comment by jbednar** [comment]
Note that `dynspread` isn't likely to do anything useful for raster/image data.

**Comment by mlaprise** [comment]
ahh now it's working. I didn't realized I could simply use directly the datashader "api".
