### ISSUE TITLE
Improve exception message when nesting DynamicMaps

### ISSUE THREAD

**Issue by xeich123** [ioam/holoviews#2392]
Hi!

I am new to Python/Holoviews and have a question regarding a way of how a DynamicMap can be used together with datashaded data. What I am trying to do is develop a tool that would allow to measure a slope by moving a straight line with a known slope over a datahaded source of data. 

Here is a simplified example of what I am trying to do

```python
import holoviews as hv
import pandas as pd
import holoviews.operation.datashader as hd
from holoviews import streams

hv.extension('bokeh')

# --------------- Test Source Data -----------------------------------
#----------------in real case that would be millions points ---------
x1=[]
y1=[]

for i in range(1,300):
    x1.append(i)
    y1.append(0.5*i)
    
dataset = list(zip(x1, y1))

df = pd.DataFrame(data = dataset, columns=['x_values', 'y_values'])
points = hv.Curve(df)
datashaded = hd.datashade(points) 

# --------------------------------------------------------------------
pointer = streams.PointerXY(x=0, y=0)

def StraighLine(x,y):
    xvals = [-1000, 1000]   
    curve_with_known_slope=hv.Curve((xvals, [(0.5*x1+y) for x1 in xvals]))
    return (curve_with_known_slope * datashaded)

hv.DynamicMap(StraighLine, streams=[pointer])
```

The above sample code does not work because of the " return (curve_with_known_slope * datashaded)", but once I replace "datashaded" with "points" it works.  Can you please let me know how i can fix this? I have to use shaded data as the source contains millions of points.

**Comment by philippjfr** [comment]
@xeich123 The issue is that ``datashaded`` is already a ``DynamicMap`` and returning a DynamicMap from a DynamicMap is not allowed. The solution is very straightforward however, simply compose overlay the datashaded object with your ``StraightLine`` DynamicMap:

```python
def StraightLine(x,y):
    xvals = [-1000, 1000]   
    return hv.Curve((xvals, [(0.5*x1+y) for x1 in xvals]))

line = hv.DynamicMap(StraightLine, streams=[pointer])
datashaded * line
```

**Comment by philippjfr** [comment]
Since we've gotten this question a few times now I've repurposed this issue to improve the error message when a nested DynamicMap is found.
