### ISSUE TITLE
Better example documentation of using Pandas Dataframes?

### ISSUE THREAD

**Issue by dartdog** [ioam/holoviews#24]
The current example shows using Seaborn and Pandas and describes wrapping the Pandas dataframe with the holoviews Dframe. Unfortunately I find it confusing..  

I'd appreciate a simple pd.dataframe to Dframe description with plotting example? Where it is clear how to reference the Pandas data as input to plotting methods. I'm currently exploring a horrendous DataFrame but can split it down into manageable pieces.... Maybe it is clear and it is just me,, But I suspect that there will be a lot of us trying to apply pandas data since we already have it ready to go...

**Comment by philippjfr** [comment]
Thanks for the feedback. I had actually planned on splitting the Pandas/Seaborn tutorial into two separate notebooks. The first will focus on the Pandas conversion interface, which allows you to convert a Pandas pd.dataframe of any number of columns into HoloViews objects (and the reverse). While the second will focus on the specialized plots that pandas and seaborn provide. I'll try to get that uploaded by tomorrow.

**Comment by philippjfr** [comment]
I finally added a [new Pandas conversion tutorial](http://ioam.github.io/holoviews/Tutorials/Pandas_Conversion), which takes a more step-by-step approach to working with dataframes in HoloViews. Note that the API for conversion isn't necessarily fixed and could certainly use some improvements. Any and all feedback of how to improve the API itself or to make the Tutorial clearer is welcome. 

I'll also be updating the [Pandas and Seaborn](http://ioam.github.io/holoviews/Tutorials/Pandas_Seaborn) in the near future to provide a reference to the additional conversion types and make it a bit clearer how to use the DFrame Element to visualize some of the Seaborn Grid types, e.g. FacetGrid and PairGrid, directly. For now I'll close this issue, if you have any specific questions or problems feel free to open another issue.

**Comment by dartdog** [comment]
That looks great! Will dig into it..

On Tue, Mar 24, 2015 at 9:36 AM, Philipp Rudiger <notifications@github.com>
wrote:

> Closed #24 <https://github.com/ioam/holoviews/issues/24>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ioam/holoviews/issues/24#event-263572156>.
>



-- 
Tom Brander
http://tombrander.com -Real Estate
http://oswco.com -Open Software
3763 West Jackson Blvd.
Birmingham, AL 35213
Phone 205-267-1089
@dartdog

**Comment by dartdog** [comment]
I downloaded the notebook and all ran as expected except the 1st  Multiple Keys Dimensions example:
Other subsequent example run fine..

%%opts Bars [aspect=3 figure_size=400 category_index=2 stack_index=0 group_index=1 color_by=['stack']] (color=Palette('Dark2'))
macro.bars(['country', 'year'], 'trade', reduce_fn=np.mean)

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/holoviews/ipython/display_hooks.py", line 190, in wrapped
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/holoviews/ipython/display_hooks.py", line 220, in element_display
    **opts(element, get_plot_size(element, size)))()
  File "/usr/local/lib/python2.7/dist-packages/holoviews/plotting/chart.py", line 779, in __call__
    self.handles['bars'], xticks = self._create_bars(axis, element)
  File "/usr/local/lib/python2.7/dist-packages/holoviews/plotting/chart.py", line 866, in _create_bars
    for cg in self.color_by if indices[cg] < ndims]
IndexError: list index out of range

**Comment by philippjfr** [comment]
Yes, thanks for reporting back. There was a bug in the Bar plotting code, which I only just fixed. If you're using a Git clone simply pull the latest commits, otherwise we'll be uploading a bugfix release to PyPi later tonight.

**Comment by dartdog** [comment]
I was just browsing the commits and saw you working in the area, and that you are planning to update to pypi,, I did try to do a pip install update from github just now and got.. (on two attempts)
FWIW...
sudo pip install -U https://github.com/ioam/holoviews.gitDownloading/unpacking https://github.com/ioam/holoviews.git

    return fp.read().decode('utf-8')
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x8b in position 1: invalid start byte

**Comment by philippjfr** [comment]
When pip installing directly from git you'll need to prepend git+ to the url, so the working command is as follows:

```
sudo pip install -U git+https://github.com/ioam/holoviews.git
```

Note that this may take a while as it's pulling in our testing reference_data, which is fairly large.

**Comment by dartdog** [comment]
All set now, except using IPython NB 3:
%output holomap='widgets'
ERROR: Line magic function `%output` not found.
Although everything looks and works fine now...

**Comment by philippjfr** [comment]
We'll investigate why it takes so long, but we'll also try to upload frequent minor and bug fix releases to PyPI, so it can be downloaded quickly. The %output line was my fault, it should be moved to after the ``%load_ext holoviews.ipython`` line, pushed that fix to git.

**Comment by dartdog** [comment]
Awesome product, can't wait to use, thanks for the help.
