### ISSUE TITLE
hv.Text in an empty axis element

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#240]
When only hv.Text is show, axes are drawn. However, they are not scaled to the extend of the text. I think this is strange behaviour, however, dispalying such an empty plot with only text is not common, so not much need to fix this.

![screenshot](https://cloud.githubusercontent.com/assets/3776190/9437695/69059c84-4a58-11e5-983f-f82482647a60.png)

**Comment by philippjfr** [comment]
Very strange behavior, but as you point out it's not a priority.

**Comment by philippjfr** [comment]
This has been fixed as can be confirmed by running:

```python
hv.Scatter(((1,2,3),(1,10,100))) * hv.HLine(y=10) * hv.HLine(y=0.1,extents=(0,-1,1,2))\
* hv.Text(4,205,'test') * hv.VLine(x=4)*hv.Arrow(2.5,100,'Arr','v')
```
