### ISSUE TITLE
kdim,vdim specification for pd.DataFrame simplification

### ISSUE THREAD

**Issue by ea42gh** [ioam/holoviews#2400]
`hv.Scatter(pd.DataFrame({'x':[1,2,3,2,1]}),'n','foo')`,
but now requires
`hv.Scatter(pd.DataFrame({'x':[1,2,3,2,1]}),('index','n'),('x','foo'))`

**Comment by philippjfr** [comment]
To be totally clear, did this really used to work:

>hv.Scatter(pd.DataFrame({'x':[1,2,3,2,1]}),'n','foo')

This definitely should have errored in the past and will do so in future, 'n' will be defined by adding an automatic index but 'foo' does not exist and will trigger an error.

**Comment by ea42gh** [comment]
I'll need to go through my notebooks when I get the chance,
but think I may have been using Series:
```
df=pd.DataFrame({'x':[1,2,3,2,1]})
hv.Scatter( df['x'],'n','foo')
```

**Comment by philippjfr** [comment]
Okay, that should work ``df['x']`` a pd.Series and therefore not the same as the example you posted above.

**Comment by philippjfr** [comment]
Nevermind it is the same, I don't really see an option to continue supporting that since it is wrong. I'm going to go back to figure out why that ever worked.

**Comment by philippjfr** [comment]
Okay, while that seems to not have raised an error in HoloViews 1.9.0, it's also definitely not working:

```
In [7]: hv.Scatter( df['x'],'n','foo').data
Out[7]:
Empty DataFrame
Columns: [n, foo]
Index: []
```
