### ISSUE TITLE
Drawing the node labels in holoviews Graph?

### ISSUE THREAD

**Issue by mjkvaak** [ioam/holoviews#2402]
Hi,

Would it be possible to add a feature to make the node label annotations visible in holoviews Graph-plots, or is it possible already? I mean the same information that pops up when you hover the mouse over the node in a network. In another words, I'm looking a feature similar to draw_networkx_labels in networkx, see e.g. [here](https://networkx.github.io/documentation/networkx-1.9/examples/drawing/labels_and_colors.html). This would become extremely handy when you want to check the connections between different nodes in a large network so that you don't have to hover and inspect each node separately. 

Furthermore, would it be possible to add this into a similar style option such as e.g. node fill, alpha, color, selection_alpha, nonselection_alpha, etc? 

Cheers!

**Comment by philippjfr** [comment]
>Furthermore, would it be possible to add this into a similar style option such as e.g. node fill, alpha, color, selection_alpha, nonselection_alpha, etc?

I think that's a reasonable suggestion although it would likely be a plot option.

**Comment by davideBbk** [comment]
Is there any news on this? I am trying exactly the same thing but I am not finding the right way

**Comment by mjkvaak** [comment]
Hi @davideBbk!
The answer is: yes! You can (nowadays) do it with hv.Labels: http://holoviews.org/reference/elements/matplotlib/Labels.html

Here's an example code - hope it helps:
```
import holoviews as hv ## version 1.10.7
import networkx as nx
import numpy as np
hv.extension('bokeh')

## See 1st example in: http://holoviews.org/user_guide/Network_Graphs.html
N = 8
node_indices = np.arange(N, dtype=np.int32)
source = np.zeros(N, dtype=np.int32)
target = node_indices
label = ['label']*len(target)
padding = dict(x=(-1.2, 1.2), y=(-1.2, 1.2))
simple_graph = hv.Graph(((source, target),)).redim.range(**padding)
simple_graph ## This plots a graph without labels


## Define the labels
labels = hv.Labels(
    {('x', 'y'): simple_graph.nodes.array([0, 1]), 'text': 'label'}, ## 'label' can be an array: has to be correct size!
    ['x', 'y'], 'text'
)

simple_graph*labels ## This plots a graph with labels

```

**Comment by mjkvaak** [comment]
Oh btw @philippjfr, I vote that this issue can be closed, as the functionality I was originally inquiring can be exactly implemented with hv.Labels.

**Comment by philippjfr** [comment]
I'm thinking, maybe we should add an example of this to the gallery.

**Comment by philippjfr** [comment]
I'll be adding this example shortly, so I'll close:

![bokeh_plot](https://user-images.githubusercontent.com/1550771/47957691-a9c17200-dfb2-11e8-8243-79f2dc2b31a5.png)
