### ISSUE TITLE
Trouble after updating pandas to 0.22

### ISSUE THREAD

**Issue by louvetg** [ioam/holoviews#2406]
Working on jupyter notbook, after updating pandas I have got a bug when I import holoview.

Traceback after "import holoviews as hv" command:

AttributeError                            Traceback (most recent call last)
<ipython-input-1-919cd75f141d> in <module>()
     10 import pyarrow as pa
     11 import pyarrow.parquet as pq
---> 12 import holoviews as hv
     13 import pandas as pd
     14 import numpy as np

~\Documents\Mes Outils Personnels\Anaconda\lib\site-packages\holoviews\__init__.py in <module>()
      9                             commit="39fe834be", reponame='holoviews')
     10 
---> 11 from .core import archive, config                        # noqa (API import)
     12 from .core.dimension import OrderedDict, Dimension       # noqa (API import)
     13 from .core.boundingregion import BoundingBox             # noqa (API import)

~\Documents\Mes Outils Personnels\Anaconda\lib\site-packages\holoviews\core\__init__.py in <module>()
      1 from datetime import date, datetime
      2 
----> 3 from .boundingregion import *  # noqa (API import)
      4 from .data import *            # noqa (API import)
      5 from .dimension import *       # noqa (API import)

~\Documents\Mes Outils Personnels\Anaconda\lib\site-packages\holoviews\core\boundingregion.py in <module>()
     10 import param
     11 from param.parameterized import get_occupied_slots
---> 12 from .util import datetime_types
     13 
     14 

~\Documents\Mes Outils Personnels\Anaconda\lib\site-packages\holoviews\core\util.py in <module>()
     44 
     45 try:
---> 46     import dask.dataframe as dd
     47 except ImportError:
     48     dd = None

~\Documents\Mes Outils Personnels\Anaconda\lib\site-packages\dask\dataframe\__init__.py in <module>()
      1 from __future__ import print_function, division, absolute_import
      2 
----> 3 from .core import (DataFrame, Series, Index, _Frame, map_partitions,
      4                    repartition, to_delayed, to_datetime, to_timedelta)
      5 from .groupby import Aggregation

~\Documents\Mes Outils Personnels\Anaconda\lib\site-packages\dask\dataframe\core.py in <module>()
     38 if PANDAS_VERSION >= '0.20.0':
     39     from pandas.util import cache_readonly
---> 40     pd.core.computation.expressions.set_use_numexpr(False)
     41 else:
     42     from pandas.util.decorators import cache_readonly

AttributeError: module 'pandas.core.computation' has no attribute 'expressions'

Have you got an idea for solve this problem ?

In advance thank you.

**Comment by philippjfr** [comment]
I'd recommend updating to a recent version of dask.

**Comment by louvetg** [comment]
Great ! Sorry for that, I thinked that Dask 0.15 was up to date. --'
Thank you very much !

**Comment by philippjfr** [comment]
No worries, anytime.
