### ISSUE TITLE
Incomplete or confusing .options() support

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#2408]
When going over the examples at pyviz.org, I tried to simplify each use of .opts() (and some cell magics) to use .options() instead.  I could easily have been confused, but I *think* that it didn't work in a number of situations that I thought it should.  In particular:

```
hv.BoxWhisker(economic_data, 'country', 'growth').options(xrotation=45, width=600, height=400)
subset.to(hv.Curve, 'year', 'unem').layout().options(width=200, height=200)
```

and possibly some GeoViews objects.  I won't have time today to try to reproduce the problems, but the symptom is that the ``.opts(plot=...)`` version does work, but the `.options()` version gives an error (I think, in the first case) or ignores the option (in the second case). It should be possible to find that code in the pyviz.org tutorials and see if it happens on a fresh copy.

**Comment by jbednar** [comment]
Also, is there a cell-magic version of .options() yet? Apologies if it's mentioned in the docs already.

**Comment by philippjfr** [comment]
That will never work, declaring options without explicitly declaring what type to set it on will set it on the outermost object in this case an NdLayout, which does not have ``width`` and ``height`` options.

**Comment by jbednar** [comment]
I believe I also tried moving it before the .layout() call with the same effect, which would then be a HoloMap.

**Comment by philippjfr** [comment]
>I believe I also tried moving it before the .layout() call with the same effect, which would then be a HoloMap.

Same issue.

**Comment by jbednar** [comment]
And .options() can't go down into the underlying Element to set the option?

**Comment by philippjfr** [comment]
In the case of HoloMap I'd be in favor of that yes, but not on an NdLayout/GridSpace/NdOverlay since they have options of their own.

**Comment by jbednar** [comment]
@jlstevens ?

**Comment by jlstevens** [comment]
Given we already do some option propagation, I suppose ``HoloMap`` could support things like ``width`` and ``height``. I'm not a huge fan of options on containers generall but I can see it would help usability. I agree with Philipp that those other containers (NdLayout/GridSpace/NdOverlay) should not support this propagation...

**Comment by jlstevens** [comment]
> Also, is there a cell-magic version of .options() yet?

There isn't yet. Making the magic parser support new syntax is unlikely to be trivial.

**Comment by philippjfr** [comment]
>Given we already do some option propagation, I suppose HoloMap could support things like width and height. I'm not a huge fan of options on containers general but I can see it would help usability.

Should have been clearer here, I'm not talking about option propagation in the sense you are thinking of here. In the case of DynamicMap the .opts and .options methods literally just forward the options directly to the elements, rather than letting the plot handle the propagation at a later stage.

**Comment by jlstevens** [comment]
Ah, I suppose I am also in favor of making ``HoloMap`` more consistent with ``DynamicMap`` then...
