### ISSUE TITLE
Using deprecated classes from streamz

### ISSUE THREAD

**Issue by dcferreira** [ioam/holoviews#2409]
Hi,

It seems holoviews imports `streamz.dataframe.StreamingDataFrame` and `streamz.dataframe.StreamingSeries`:
https://github.com/ioam/holoviews/blob/12a95de53c3d1a8d152a7c9fcdbc8ad3c83445dd/holoviews/streams.py#L430-L437

However, these classes have been deprecated and no longer exist in version streamz 0.3.0.

To reproduce, use the examples given in http://holoviews.org/user_guide/Streaming_Data.html that use such classes. They do not work with streamz==0.3.0.

**Comment by philippjfr** [comment]
Thanks for raising this issue, I've been meaning to file it myself. The code does indeed need to be updated so for now I'd recommend sticking to 0.2.0 or manually connecting the streamz.DataFrame to the Buffer using the ``.sink`` method.
