### ISSUE TITLE
Plot and style option name clashes

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#2411]
The new .options method relies on unique names for plot and style options. At least in one case that is currently not true, namely the width option on Bars is both a plot options (controlling the width of the plot) and a style option (setting the width of the bars). We need to validate that these do not clash, and in the case of width rename the width style option to ``bar_width``.

**Comment by jlstevens** [comment]
I hope this is the only example of a clash we find.

**Comment by philippjfr** [comment]
There's a few more, but it's not too bad:

```python
from itertools import combinations

def option_intersections(backend):
    options = hv.Store.options(backend)
    for k, opts in options.items():
        if len(k) > 1: continue
        eltype = k[0]
        valid_options = {k: set(o.allowed_keywords)
                         for k, o in opts.groups.items()}
        for g1, g2 in combinations(['plot', 'style', 'norm'], 2):
            intersection = valid_options[g1] & valid_options[g2]
            if intersection:
                print('%s element %s and %s %s backend options intersect on: %s'
                      % (eltype, g1, g2, backend, intersection))
       
for backend in hv.Store.renderers:
    option_intersections(backend)
```

Bars element plot and style **bokeh** backend options intersect on: {'width'}
BoxWhisker element plot and style **bokeh** backend options intersect on: {'width'}

Arrow element plot and style **matplotlib** backend options intersect on: {'fontsize'}
Text element plot and style matplotlib backend options intersect on: {'fontsize'}

Curve element plot and style **plotly** backend options intersect on: {'width'}
ErrorBars element plot and style **plotly** backend options intersect on: {'width'}

**Comment by jlstevens** [comment]
Maybe for ``Arrow`` it could be called ``textsize``. Not sure about all the others though.

**Comment by philippjfr** [comment]
Bokeh Bars: width -> bar_width
Bokeh BoxWhisker: width -> box_width
Matplotlib Arrow: fontsize -> textsize
Matplotlib Text: fontsize -> textsize
Plotly Curve/ErrorBars: delete width as a style option

**Comment by jlstevens** [comment]
Those suggestions seem reasonable enough. The problem then is retaining the old names (and therefore the clashes) for backwards compatibility...

**Comment by philippjfr** [comment]
Okay, I've come up with a plan for this, I'm going to make sure that plot options take precedence over style options in the ``expand_options`` method, since those are more common. For now we will leave the clashing style options registered, which means that they can still be set using ``opts`` or the magic but I will also register the new non-clashing names as aliases. Eventually we can deprecate the clashing options.

**Comment by philippjfr** [comment]
>Matplotlib Arrow: fontsize -> textsize
>Matplotlib Text: fontsize -> textsize

These two were actually never used since the element defines that parameter.

**Comment by jbednar** [comment]
I'd consider those options deprecated immediately; deprecated just means "don't use in new code", right?  So as soon as we know they shouldn't be in new code, shouldn't they be deprecated?

**Comment by philippjfr** [comment]
>So as soon as we know they shouldn't be in new code, shouldn't they be deprecated?

True, I wasn't sure whether to add warning, but I suppose we should.

**Comment by jbednar** [comment]
Whether to add a warning is a different matter than deprecating them.  I'd say the thing to do immediately is to mark them deprecated in the release notes.  Then in the *following* release, there can be a warning.

**Comment by philippjfr** [comment]
>I'd say the thing to do immediately is to mark them deprecated in the release notes. Then in the following release, there can be a warning.

Sounds good.
