### ISSUE TITLE
Where to find documentation on plot- and style-options of various hv Elements & backends?

### ISSUE THREAD

**Issue by SebastianRiedel** [ioam/holoviews#2413]
From the user guide on http://holoviews.org/user_guide/Customizing_Plots.html:
* on style options: `For whichever backend has been selected, HoloViews can tell you which options are supported[...]`
* on plot options: `HoloViews documents these options fully in its online help and in the Reference Manual .`

Where, how :)? E.g. `hv.help(hv.Curve)` does not list them. The Reference Manual doesn't seem to list them either (at least not directly?).

**Comment by philippjfr** [comment]
``hv.help`` should list them once the ``hv.extension()`` has been loaded, initializing the active backend.

**Comment by SebastianRiedel** [comment]
Perfect, thanks. I saw now that the FAQ mentions the general `hv.help(obj)`-pattern as well, but I'd vote for adding basically your comment as close as possible to the sentences I quoted above. I can do a quick doc PR for that if you want?

**Comment by philippjfr** [comment]
Yes that would be great, thanks!
