### ISSUE TITLE
heatmap shows no image at all when hover tool is used

### ISSUE THREAD

**Issue by scaine1** [ioam/holoviews#2419]
I have a some sample scripts that used to work previously and now dont show anything on the screen when loaded. 
These scripts are a bit long so I have tried to make a simple example that captures the behaviour.
From what I can tell it happens only with bokeh plots and when certain widgets are included.
The example below fails when the hover tool is included.

```python
import numpy as np
import xarray as xr
import holoviews as hv

def create_data():
    """
    create fake example data
    """
    x = np.arange(0, 10, 1.)
    y = np.arange(0, 10, 1.)

    dims = ('x', 'y')
    shape = (len(x), len(y))
    coords = {'x':x, 'y':y}
    field = np.zeros(shape)
    field[3:5, 3:5] = 10
    field[3:5, 3:5] = 20
    field_xr = xr.DataArray(field, dims=dims, coords=coords)
    xr_ds = xr.Dataset({'x': x, 'y': y,  'field': (dims, field)})
    return xr_ds

hv.extension('bokeh', 'matplotlib')
renderer = hv.renderer('bokeh')
hv.output('size=200')

xr_ds = create_data()
vdims = ['field']
kdims= ['x', 'y']
ds = hv.Dataset(xr_ds, kdims=kdims, vdims=vdims)

opts = "HeatMap [tools=['hover']]"
hm = ds.to(hv.HeatMap, ['x', 'y'])
renderer.save(hm, 'heatmap_works')
renderer.save(hm.opts(opts), 'heatmap_fails')
```

**Comment by jlstevens** [comment]
Seems important enough that it should be investigated before 1.10...

**Comment by philippjfr** [comment]
This bug is specifically due to the value dimension name ``'field'`` which has special meaning for bokeh and seems to cause issues with the HoverTool.

**Comment by scaine1** [comment]
oh wow nice find!
Is it worth disallowing the use of 'field' (and perhaps outs), or putting a warning?

**Comment by jbednar** [comment]
I think so, and/or renaming it to something safe automatically.

**Comment by philippjfr** [comment]
This appears to have been fixed at the bokeh level.
