### ISSUE TITLE
Nonlocal behaviour of %%opts

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#242]
%%opts options should only change behaviour in the cell where they are executed. However, setting the y-axis to logscale for a curve element does influence the next cell:
![screenshot-1](https://cloud.githubusercontent.com/assets/3776190/9441055/082d2c44-4a74-11e5-9b9e-72f98d0151c7.png)

**Comment by basnijholt** [comment]
I noticed the same thing, we went over it on Gitter some time ago.
This is the behaviour that was wanted.

**Comment by jlstevens** [comment]
This comes down to what is more useful - customizing the display of one particular cell or customizing the *object* shown in a particular cell? We decided the latter is more useful as if you re-use your objects, you probably don't want to repeat the customization.

You can clear the customization using ``__call__`` without arguments. In ``In [7]`` try ``curve()`` to go reset the customization to the default settings. If that doesn't work, then there is a bug for me to fix!

**Comment by vascotenner** [comment]
It turns out that %%opts sets the style for the DISPLAY of the object in that cell. If the same display is shown in the next cell, the same %%opts are applied. When a new display is created, it uses only the global %opts. This new display can be created by slicing, or by creating a copy:

![screenshot-3](https://cloud.githubusercontent.com/assets/3776190/9442014/98539970-4a79-11e5-9ce1-ab405aaa96d8.png)

This is somehow logical behaviour. I propose to not change this behaviour. This issue can serve as reference.
