### ISSUE TITLE
15-Streaming_Data.ipynb doesn't work fully with streamz-0.3.0 (on holoviews-1.10.0 alpha1)

### ISSUE THREAD

**Issue by stonebig** [ioam/holoviews#2430]
https://github.com/ioam/holoviews/blob/master/examples/user_guide/15-Streaming_Data.ipynb

fails there, don't guess why. using holoviews-1.10.0 alpha1
````
%%opts Curve [width=500 show_grid=True]
sdf = (simple_sdf-0.5).cumsum()
hv.DynamicMap(hv.Curve, streams=[Buffer(sdf.x)])
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-19-00a71850e3cf> in <module>()
      1 sdf = (simple_sdf-0.5).cumsum()
----> 2 hv.DynamicMap(hv.Curve, streams=[Buffer(sdf.x)])

C:\WinP\bd36\buQt5\winp32-3.6.x.0\python-3.6.4\lib\site-packages\holoviews\streams.py in __init__(self, data, length, index, **params)
    434                 loaded = False
    435             if not loaded or not isinstance(data, (StreamingDataFrame, StreamingSeries)):
--> 436                 raise ValueError("Buffer must be initialized with pandas DataFrame, "
    437                                  "streamz.StreamingDataFrame or streamz.StreamingSeries.")
    438             elif isinstance(data, StreamingSeries):

ValueError: Buffer must be initialized with pandas DataFrame, streamz.StreamingDataFrame or streamz.StreamingSeries.
````

**Comment by stonebig** [comment]
I see tthe patch https://github.com/ioam/holoviews/pull/2420/files is in the alpha

**Comment by stonebig** [comment]
works again If I dowgrade from streamz-0.3.0-py2.py3-none-any.whl to streamz-0.2.0-py2.py3-none-any.whl

**Comment by philippjfr** [comment]
@stonebig I cannot reproduce this, it works for me with streamz 0.2.0  and 0.3.0.

**Comment by philippjfr** [comment]
Based on your traceback you don't seem to be using the alpha, the line numbers do not match up.

**Comment by stonebig** [comment]
oups! rechecking.

**Comment by stonebig** [comment]
well, this is your fault:
-  `pip install holoviews-1.10.0a2.zip` creates an invalid  wheel name `holoviews-None-py3-none-any.whl`
- then further install based on requirement.txt file ignores this wheel.

**Comment by philippjfr** [comment]
^@jlstevens

**Comment by stonebig** [comment]
do i need to create an issue for this other problem ?

**Comment by philippjfr** [comment]
@jlstevens can respond here and then raise the issue in the appropriate place. I don't remember at all how ``autover`` handles git archives but it absolutely must work since that's also what the conda-forge builds are built from.

**Comment by stonebig** [comment]
now , it gets better, except at the last cell. maybe my Pc is too small
````
WARNING:root:dynamic_operation: Exception raised in callable 'dynamic_operation' of type 'function'.
Invoked as dynamic_operation(height=245, scale=1.0, width=522)
````

**Comment by philippjfr** [comment]
Yeah, there appears to be an issue in the datashaded plot. I'll handle that.

**Comment by jlstevens** [comment]
I think I just need to update the .gitattributes. I'll test git archive and ping you when I got it working again.

**Comment by jlstevens** [comment]
@stonebig I had missed an entry in the .gitattributes file:

![image](https://user-images.githubusercontent.com/890576/37308620-8055386a-2636-11e8-87a2-8ed69c8a7d65.png)

This shows the version information available via git archive which unfortunately doesn't include the tag. The way I recommend using pip+git is this way which has access to the full version infromation:

```
pip install git+https://github.com/ioam/holoviews.git
```

![image](https://user-images.githubusercontent.com/890576/37308796-f3f74f56-2636-11e8-8c04-6a6a65b530e3.png)
