### ISSUE TITLE
The map attribute of Plot classes should be renamed

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#244]
Currently all plot classes have a ``map`` attribute that should be renamed for the following reasons:

* ``map`` is a Python built-in (at least in Python 2)
* ``map`` is not a  method or function as might be expected but a ``HoloMap`` datastructure.

This should be a simple search-and-replace operation and I propose renaming the variable to ``hmap``.

**Comment by philippjfr** [comment]
This should happen after the bokeh branch merge as it affects both backends.

**Comment by jlstevens** [comment]
Agreed. No need to let this hold up the merge.

**Comment by philippjfr** [comment]
I've just made this change in fd9f278, the map attribute on ElementPlot types is now called hmap. Will close the issue.

**Comment by jlstevens** [comment]
Great! No need for anymore confusion and I didn't even mention the extra confusion due to the ``map`` method on HoloMaps....
