### ISSUE TITLE
trying to create an html file for the app example CrossFilter

### ISSUE THREAD

**Issue by euacar** [ioam/holoviews#2451]
At the end of the example http://holoviews.org/gallery/apps/bokeh/crossfilter.html#bokeh-gallery-crossfilter

I added two more lines.
output_file("xx.html")
save(curdoc())

File gets generated but it has multiple graphs in it ,no colors  no drop downs do not work.

What Am I missing?
Thx
Ercan

**Comment by philippjfr** [comment]
The example defines an interactive bokeh app which has to be served using ``bokeh serve crossfilter.py`` or embedded into a web server in some other way, exporting to a static file will loose all interactivity.
