### ISSUE TITLE
Inclusion of a 3d lines functionality ?

### ISSUE THREAD

**Issue by thejasvibr** [ioam/holoviews#2453]
The Scatter3d function allows users to plot separate points in 3d space. - which is useful for many kinds of data visualisation. However, in the case of trajectory visualisation or to visualise overlayed data - it would be useful to be connect these points with lines. 

In addition to Scatter3d would it be possible to include something like a 'Line3d' option in the Holoviews library ?

**Comment by philippjfr** [comment]
This should be a fairly straightforward addition and seems worthwhile.

**Comment by jlstevens** [comment]
What would it be called ``Path3D`` seems like the most consistent match?

**Comment by philippjfr** [comment]
I think I'd prefer Line3d or Curve3d, Path has specific connotations in HoloViews which differs from a simple line.

**Comment by jbednar** [comment]
Seems like this is the 3D extension of hv.Curve, so it should be hv.Curve3d, right?

**Comment by philippjfr** [comment]
Agreed, I'm wondering whether we should slowly migrate to Curve -> Line, in which case Line3D would be more consistent and future compatible.

**Comment by jbednar** [comment]
Ah.  Coincidentally, Gus just brought that up again, and we do need a way for people to find "Line" plots, so maybe indeed Line3d.

**Comment by ea42gh** [comment]
All of this brings up the question of interpolation between Points.
In 2D, hv.Curve has a (limited) number of interpolation options.
In 3D, the options are even more interesting...

**Comment by jlstevens** [comment]
Honestly, I don't mind the name ``Line`` or ``Line3D``. The problem is maintaining backwards compatibility nicely and I don't really want to documented different 'elements' that are essentially aliases of each other.

**Comment by philippjfr** [comment]
Matplotlib and plotly implementations of a 3D line were added in 1.11.

**Comment by jewfro-cuban** [comment]
Was this eventually merged? I can't find Line3D in 1.13.2

**Comment by jbednar** [comment]
To clarify, this was added as [Path3D](http://holoviews.org/reference/elements/plotly/Path3D.html).
