### ISSUE TITLE
Python files with trailing whitespace

### ISSUE THREAD

**Issue by jbampton** [ioam/holoviews#2457]
Hello all, I wrote this small Ruby script that can check files for trailing whitespace and then print the file path and line number where the trailing whitespace occurs.  I ran the script against the python files in this repository and found a list of files with trailing whitespace as seen below.  I did not check every file, but for the ones I did check the trailing whitespace does occur.  PEP 8 -> https://www.python.org/dev/peps/pep-0008/#other-recommendations  says we should avoid trailing whitespace.  Are we interested in getting this whitespace removed ? 

tests/operation/testoperation.py: 82
tests/operation/testoperation.py: 96
tests/operation/testoperation.py: 110
tests/operation/testdatashader.py: 277
tests/core/testtree.py: 53
tests/core/testtree.py: 61
tests/core/testtree.py: 77
tests/core/testdimensioned.py: 143
tests/core/data/testbinneddatasets.py: 240
tests/teststreams.py: 411
tests/teststreams.py: 471
tests/element/testgraphelement.py: 93
tests/element/testgraphelement.py: 118
tests/element/testelementconstructors.py: 182
tests/element/teststatselements.py: 95
tests/element/teststatselements.py: 138
tests/plotting/bokeh/testpathplot.py: 59
tests/plotting/bokeh/testlayoutplot.py: 133
tests/plotting/bokeh/testlayoutplot.py: 182
tests/plotting/bokeh/testpointplot.py: 20
tests/plotting/bokeh/testpointplot.py: 130
tests/plotting/bokeh/testpointplot.py: 156
tests/plotting/bokeh/testelementplot.py: 30
tests/plotting/bokeh/testgraphplot.py: 120
tests/plotting/bokeh/testoverlayplot.py: 82
tests/plotting/bokeh/testcallbacks.py: 93
tests/plotting/bokeh/testcallbacks.py: 129
tests/plotting/bokeh/testcallbacks.py: 134
tests/plotting/bokeh/testwidgets.py: 233
tests/plotting/testplotutils.py: 435
examples/gallery/apps/bokeh/gapminder.py: 74
doc/nbpublisher/profile_docs/ipython_notebook_config.py: 33
doc/nbpublisher/profile_docs/ipython_notebook_config.py: 35
doc/nbpublisher/profile_docs/ipython_notebook_config.py: 37
doc/nbpublisher/profile_docs/ipython_notebook_config.py: 79
doc/nbpublisher/profile_docs/ipython_notebook_config.py: 84
doc/nbpublisher/profile_docs/ipython_notebook_config.py: 119
holoviews/operation/datashader.py: 124
holoviews/operation/datashader.py: 687
holoviews/operation/element.py: 447
holoviews/operation/element.py: 582
holoviews/core/spaces.py: 1157
holoviews/core/data/pandas.py: 127
holoviews/core/data/dask.py: 129
holoviews/core/data/xarray.py: 207
holoviews/core/data/xarray.py: 325
holoviews/core/dimension.py: 334
holoviews/element/comparison.py: 498
holoviews/plotting/bokeh/chart.py: 58
holoviews/plotting/bokeh/chart.py: 566
holoviews/plotting/bokeh/path.py: 72
holoviews/plotting/bokeh/path.py: 108
holoviews/plotting/bokeh/path.py: 126
holoviews/plotting/plot.py: 452
holoviews/plotting/util.py: 568
holoviews/plotting/renderer.py: 457
holoviews/plotting/plotly/chart.py: 96
holoviews/plotting/plotly/chart.py: 100
holoviews/plotting/mpl/chart3d.py: 188
holoviews/plotting/mpl/chart.py: 618
holoviews/plotting/mpl/path.py: 14
holoviews/plotting/mpl/path.py: 101
holoviews/plotting/widgets/__init__.py: 361

**Comment by jlstevens** [comment]
> Are we interested in getting this whitespace removed ?

Yes! I hate trailing whitespace myself as I have it highlighted in my editor. Thanks for the list of files, I'll go through them and remove that unnecessary whitespace (except in nbpublisher as that isn't actually part of holoviews)
