### ISSUE TITLE
Bokeh backend should support updating via the set method

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#246]
After discussing the implementation of the Bokeh backend with Philipp, we came to the following agreement on how things should be implemented:

* All options that can be dynamically updated should be updated via the ``set`` method offered by Bokeh in the ``_update_plot`` method.
* Only options that can be initialized once and cannot be mutated should be supplied to the ``_init_plot`` method.

This should help make the Bokeh backend more dynamic than the matplotlib one. For instance,  modifying attributes such as font sizes across the elements of a HoloMap should update appropriately. If done properly, this could help eliminate the use of ``**self.style`` in the ``init_glyph`` method that is used to implement specific Bokeh plots.

On a related note, it should be possible to use the ``set`` mechanism to simplify the implementation of ``ElementPlot._update_plot``.

**Comment by philippjfr** [comment]
This has now been completed. For every type of plot object we have a method to supply the updateable properties, an initialization method and optionally an update method, currently these methods include:

    1) figure/plot object: ``_init_plot``, ``_update_plot``, ``_plot_properties``
    2) axis objects: ``_init_axes`` and ``_axis_properties``
    3) glyph objects: ``_init_glyph`` and ``_glyph_properties``

The glyphs and axes cannot currently be updated but everything is in place for that to happen once we figure out if bokeh can or will support it.

**Comment by jlstevens** [comment]
Ok. I think the branch is ready for a merge.
