### ISSUE TITLE
The get_extents method of plotting classes could supplied as a utility

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#247]
As discussed with Philipp, the `get_extents` methods of the `SpreadPlot` and similar uses of `get_extents` could be moved to `plotting.util`. The code here is not specific to the Bokeh backend in any way and we hope to avoid duplicating code between backends as much as possible.

Such a refactor could simplify the implementation of both the matplotlib and the bokeh backends.

**Comment by philippjfr** [comment]
Turns out that particular ``get_extents`` method wasn't needed. However possibly there are a few ``get_extents`` in the matplotlib implementation that should be factored out. I'll leave the issue open but it shouldn't hold up the bokeh merge.

**Comment by philippjfr** [comment]
Closing in favor of https://github.com/ioam/holoviews/issues/1917.
