### ISSUE TITLE
hv.Points(df) with duplicate columns in dataframe

### ISSUE THREAD

**Issue by lioumens** [ioam/holoviews#2476]
The [user guide](http://holoviews.org/user_guide/Tabular_Datasets.html) says dataframes are supported, but I'm having trouble in cases with duplicate columns. The error message is also not very helpful in pinpointing what is going wrong.

Also, [API documentation for element.chart.Chart](http://holoviews.org/Reference_Manual/holoviews.element.html#holoviews.element.chart.Chart) does not mention dataframes, not sure if it should.

```python
import numpy as np
import pandas as pd
import holoviews as hv
data = pd.DataFrame(np.random.randint(-100,100, size=(100, 2)), columns=list("AB"))

# Dataframe with non-duplicate columns works
hv.Points(data[["A", "B"]])

# Dataframe with duplicate columns does not work.
hv.Points(data[["A", "A"]])

# Converting to the numpy array works
hv.Points(data[["A", "A"]].as_matrix())
```
The last part of the traceback: 
![image](https://user-images.githubusercontent.com/35322700/37790903-c9456148-2dd5-11e8-9fb0-9153267c670e.png)

```python
print(hv.__version__) # 1.9.4-x-g73c2735e7
print(pd.__version__) # 0.20.3
```

**Comment by philippjfr** [comment]
Actually duplicated columns are indeed not supported but the usage you outline isn't recommended in general. Rather than selecting the columns that you need from your data I would suggest declaring the dimensions instead, e.g.:

```python
# non-duplicate columns
hv.Points(data, ['A', 'B'])

# Duplicate.
hv.Points(data, ['A', 'A'])
```

We could probably support actually duplicated columns, but it doesn't seem like a scenario I'd ever recommend.

**Comment by jbednar** [comment]
Me either!

**Comment by philippjfr** [comment]
>We could consider putting in a warning if we detect that happening, though?

Good idea, but I think it should be an exception tbh, there is no way we'll be able to resolve which column is meant if it's duplicated.

**Comment by philippjfr** [comment]
I'd even go further and say that duplicate column names is a recipe for disaster and if I were a pandas developer I'd have argued that it should not be allowed at all.

**Comment by jbednar** [comment]
Sure. It's certainly difficult for me to think of a valid use for a dataframe like that, unless there is no name at all for the columns involved.

**Comment by jlstevens** [comment]
I agree that an exception makes sense. 

Frankly, I had no idea that duplicate columns were even allowed!

**Comment by philippjfr** [comment]
Having read up on the history a bit, I can sort of understand why pandas allows this. When reading in csv files with duplicate columns you don't want it to fail or mutate your columns automatically. Anyway adding the exception in holoviews should be easy.
