### ISSUE TITLE
Specifying port for server does not make any difference

### ISSUE THREAD

**Issue by ambodi** [ioam/holoviews#2477]
In the documentation, you guys say that if you mention a port, it will override the default port=0. I am getting different results:
```python
from bokeh.server.server import Server

hmap = hv.HoloMap(curve_dict, kdims='Sample Number')
app = renderer.app(hmap, show=True)
server = Server({'/': app}, port=8888)
server.start()
```
Everytime I run the above, I end up with a new port.

**Comment by philippjfr** [comment]
Note that when you set ``show=True`` it already constructs a ``Server`` instance for you, so what's happening here is that you are wrapping a Server instance in another ``Server``. This works fine:

```python
from bokeh.server.server import Server

hmap = hv.HoloMap(curve_dict, kdims='Sample Number')
server = Server({'/': renderer.app(hmap)}, port=8888)
server.start()
```
