### ISSUE TITLE
Improvements to the bokeh API

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#248]
I've reviewed the bokeh branch and it is nearly ready to merge once this issue and issues #243  #246 are resolved. Here I would like to propose improvements to the plot options to make the bokeh backend as consistent as possible with matplotib:

* ``title_size`` should use the ``font_sizes`` parameter described in #72 
* Similarly I eliminated ``title_color`` in commit 979a9b4 but I would be happy to see an analogous ``font_colors`` parameter introduced to both the matplotlib and bokeh backends.
* The same convention should be applied to ``title_font`` which I also removed in commit 0c0a930. I am not sure what this should be called as ``font_families`` might not be specific enough to refer to an actual font.

Otherwise, the API seems fairly consistent with current matplotlib implementation: only ``shared_axes`` and ``tools`` seem to be plot options that only Bokeh can support.

Once this is all fixed (and a warning added to mark Bokeh support as experimental and incomplete), I would be happy to see the bokeh branch merged with master.

**Comment by jbednar** [comment]
Sounds good to me.

**Comment by philippjfr** [comment]
The immediate issues here have been addressed, namely making font_sizes consistent and adding a warning for bokeh. We should add a new issue about creating ``font_colors`` and ``font_families`` parameters for both backends.

**Comment by jlstevens** [comment]
Looks good! I'll open a new issue as you suggest and close this one.
