### ISSUE TITLE
Keyword completion in options

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#2485]
Given that we want to reduce the use of the ``%%opts`` magic, it would be good if the ``.options`` method could tab-complete the available keywords.

This is possible to do in IPython but it will involve some hackish dynamic updates of docstrings. I'm wondering if this could be done by a safe utility in the constructor, ideally in one place at the ``Dimensioned`` level...

**Comment by jlstevens** [comment]
I'll assign this to 1.10 as it would be nice to have a replacement for ``%%opts`` that can be recommended even for notebooks.

**Comment by philippjfr** [comment]
An alternative to docstring hackery to make this work would be to replace ``.options`` with a property which returns an object which would provides a ``__call__`` method which provides the tab-completion. We could for instance dynamically create a ``ParameterizedFunction`` which defines the valid options as parameters.

**Comment by jlstevens** [comment]
Maybe I am misremembering but that approach is essentially piggy-backing off param to set the docstrings for you.

**Comment by philippjfr** [comment]
Right, I think that's preferable over re-implementing custom docstring hackery for this particular case, but I'll leave that up to whoever implements this.

**Comment by jlstevens** [comment]
I'm fine with this (and happy to implement it) though if I remember right, you were objecting to callable objects that look like methods at one point. :-)

**Comment by philippjfr** [comment]
>I'm fine with this (and happy to implement it) though if I remember right, you were objecting to callable objects that look like methods at one point. :-)

No I was objecting to using nested APIs like redim everywhere, ``obj.options()`` will appear to work just like any other method, something like ``obj.options.style()`` is what I would object to.

**Comment by jlstevens** [comment]
Sure though simply by being parameterized means nested things like ``obj.options.params()`` will now exist even if not really part of the holoviews API.

**Comment by philippjfr** [comment]
>Sure though simply by being parameterized means nested things like obj.options.params() will now exist even if not really part of the holoviews API.

True, not ideal I guess, maybe a custom solution is preferable.

**Comment by philippjfr** [comment]
Implemented in https://github.com/ioam/holoviews/pull/3173
