### ISSUE TITLE
Annotations and plot extents

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#249]
Quite often, I use the HLine and VLine elements to draw a line in my plot, to indicate a certain value. Sometimes, these values lie outside the extents of the original plot. The *Lines are not displayed in that case.

I want to display these lines also. Is there a simple workaround? Setting extents on the Line element does not work.

For other annotations the logic used is a bit different:
*  Arrows are only displayed when the endpoint of the arrow is in the extents of the plot. Extra space is created for the arrow and text.
* Text is always displayed, and extra space is created, see #240 

Some code and output:
```
hv.Scatter(((1,2,3),(1,10,100))) * hv.HLine(y=10) * hv.HLine(y=0.1,extents=(0,-1,1,2))\
* hv.Text(4,105,'test') * hv.VLine(x=4)*hv.Arrow(2.5,100,'Arr','v')
```
![screenshot](https://cloud.githubusercontent.com/assets/3776190/9467337/3a23fb52-4b3b-11e5-92d4-78a6fc29b920.png)

**Comment by jlstevens** [comment]
I agree that extents should be respected in annotations and hopefully I'll have a chance to fix this soon...

**Comment by vascotenner** [comment]
There is a comparable issue with errorbars:
![screenshot](https://cloud.githubusercontent.com/assets/3776190/9521576/f01c8bfa-4ccf-11e5-9194-694e48599468.png)

**Comment by philippjfr** [comment]
Both issues mentioned here have now been fixed. Note that Arrows and text may still go beyond the axis limits as there is no easy way to compute where it will be positioned. However their position is at least included when computing the axis extents.
