### ISSUE TITLE
xbox_select with a pandas DateTimeIndex is not passing the correct times

### ISSUE THREAD

**Issue by Dr-Irv** [ioam/holoviews#2505]
If you have a time indexed Series that is plotted as a curve and you use the `xbox_select` tool, the times passed into the handler are incorrect.  Seems to be related to a time zone issue, as times are shifted by the time zone offset amount.

```python
import pandas as pd
import numpy as np
import holoviews as hv
hv.extension('bokeh', 'matplotlib')

rng = pd.date_range('4/1/2018', periods=24*12, freq='5min').rename('DateTime')
x = np.sin([8*np.pi*i/(len(rng)) for i in range(len(rng))])
df = pd.DataFrame({'x' : x}, index=rng)

######## New cell in notebook

%%opts Curve [height=300 width=600 tools=['xbox_select']]
%%opts Table [width=800]

from holoviews import streams

def make_from_boundsx(boundsx):
    sub = df.loc[boundsx[0]:boundsx[1]]
    tdf = pd.DataFrame({'bounds': [boundsx[0], boundsx[1]]})
    return hv.Table(tdf, [], 'bounds')

curve = hv.Curve(df.reset_index(), kdims='DateTime', vdims=['x'])

hv.Layout([curve, hv.DynamicMap(make_from_boundsx, 
                               streams=[streams.BoundsX(source=curve,
                                                        boundsx=(df.index.min(),df.index.max()))])
]).cols(1)
```

This is set up so that the table shows the bounds that are passed into `make_from_boundsx`.  If I select from 6AM to 10AM, then I get times that are from 1AM to 5AM (approximately).

**Comment by philippjfr** [comment]
Sounds like a timezone issue, are you on EST by any chance?

**Comment by Dr-Irv** [comment]
@philippjfr Yes, I am in EST.  I have HoloViews 1.9.5.

**Comment by philippjfr** [comment]
I suspect it might be fixed in master, we should have a dev release for you to try out soon.

**Comment by Dr-Irv** [comment]
@philippjfr I can confirm.  I was able to get the master from git, point my environment to that, and the problem goes away.

**Comment by philippjfr** [comment]
Fabulous, thanks for testing!
