### ISSUE TITLE
Add arrows to edges for directed network graphs

### ISSUE THREAD

**Issue by cacti77** [ioam/holoviews#2521]
I see an example of a network graph at http://holoviews.org/gallery/demos/bokeh/network_graph.html but the edges between the nodes are missing arrowheads.  Is it possible (and preferably easy!) to display the edges as arrows in HoloViews?

I really want to be able to draw directed graphs like the D3 examples at https://bl.ocks.org/cjrd/6863459 and http://bl.ocks.org/rkirsling/5001347. But I'm struggling to find a Python visualization library that will allow me to do this.

**Comment by jlstevens** [comment]
I think this would be a very valuable feature.

Briefly, I was wondering if you could overlay a vectorfield to achieve this. Unfortunately, even if you were to try such a desperate workaround, I don't think you would have access to the concrete layout of the edges to put the little vectors in the right places...

**Comment by philippjfr** [comment]
I considered something similar, namely that VectorField already implements code to draw arrows using the ``multi_line`` glyph so we could easily port that code and use it to draw directed edges in ``Graph``.

**Comment by philippjfr** [comment]
Graphs now support a directed plot option which adds arrows indicating the directionality.

**Comment by cacti77** [comment]
Thanks very much!
