### ISSUE TITLE
Tutorial about Collector

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#253]
One interesting feature of Holoviews is the Collector object, that can be used to harvest results from a simulation at several time steps. From the current documentation I cannot figure out how it works, and how it can be used. I want to use it for a slightly different purpose: I want regularly to check a certain directory if there are new files with measurements available, and if, to plot them together with the old measurements. Writing this code in python is relatively easy, but I have the feeling that the collector object can do this.

Probably this is also done somewhere in lancet,  but I could not figure out yet. Is there an example somewhere that shows something like this?

**Comment by philippjfr** [comment]
``Collector`` has moved to ``featuremapper`` so I'll close this.
