### ISSUE TITLE
Overview of holomap

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#254]
Quite often, I just want to have an overview of my holomap. For that I use the layout or overlay or grid method. Most of the time, I want to show all dimensions (often 1). Typing in that dimension is much work. I propose that the default behaviour of these functions is to show all elements of the holomap.

**Comment by jlstevens** [comment]
Yes, I completely agree! I've checked the signature of both these methods and this should be trivial to implement.

**Comment by philippjfr** [comment]
Just merged your PR. Will close this issue.
