### ISSUE TITLE
Control the text update of chart and slider in holomap

### ISSUE THREAD

**Issue by ambodi** [ioam/holoviews#2563]
I have an interactive time series (so to say) that works like the following:

```
curve_dict = {s: make_curve(s, preds, trues,
                            nordpool) for s in time_refs_range}
hmap = hv.HoloMap(curve_dict, kdims='Reference Time')
```

Just to be clear, curve_dict is an overlay of three curves. Now my problem is that I do not want holomap to update the values based on the time_range since time range is [0, 10] but I want to look up the actual time from a dictionary, can I do that? If so, how?

**Comment by jlstevens** [comment]
I'm not entirely sure I follow the question but you can index the holomap with a key from your dictionary as follows:

```
hmap[1]
```

Assuming the key ``1`` is in the dictionary, this will look up the corresponding value by that time.

**Comment by philippjfr** [comment]
I'm also having trouble understanding what exactly you're asking for. Since this is a usage question I'm going to encourage you to ask us on the [Gitter channel](https://gitter.im/ioam/holoviews) or preferably file a question on StackOverflow.
