### ISSUE TITLE
Multiple `Curve` vdims for changing line properties

### ISSUE THREAD

**Issue by toddrjen** [ioam/holoviews#2567]
With the `Scatter` plot with the Bokeh backend, we can change things like point thickness and color across the points by supplying multiple vdims, as shown in the [documentation](http://holoviews.org/reference/elements/bokeh/Scatter.html#bokeh-gallery-scatter):

```Python
%%opts Scatter [color_index=2 size_index=3 scaling_factor=50]
np.random.seed(10)
data = np.random.rand(100,4)

scatter = hv.Scatter(data, vdims=['y', 'z', 'size'])
scatter
```

It would be nice if we could do the same thing to alter `Curve` properties like line color and thickness across the curve.  This currently doesn't seem to work:

```Python
%%opts Curve [color_index=2 size_index=3 scaling_factor=50]
np.random.seed(10)
data = np.random.rand(100,4)

curve = hv.Curve(data, vdims=['y', 'z', 'size'])
curve
```

Gives:

```
Unexpected plot option 'color_index' for Curve in loaded backend 'bokeh'.

Possible keywords in the currently active 'bokeh' renderer are: ['apply_extents', 'apply_ranges', 
'bgcolor', 'border', 'default_tools', 'finalize_hooks', 'fontsize', 'gridstyle', 'height', 'interpolation', 
'invert_axes', 'invert_xaxis', 'invert_yaxis', 'labelled', 'lod', 'logx', 'logy', 'normalize', 'projection', 
'shared_axes', 'shared_datasource', 'show_frame', 'show_grid', 'show_legend', 'show_title', 
'sizing_mode', 'title_format', 'toolbar', 'tools', 'width', 'xaxis', 'xrotation', 'xticks', 'yaxis', 'yrotation', 
'yticks']
```

I don't see anything there that would suggest it support such options.

**Comment by jlstevens** [comment]
Changing properties along the curve is something we discussed in the past and should be doable. Originally, we considered this for ``Path``/``Contour`` and not ``Curve`` but now I don't see why things couldn't be generalized the way you suggest.

**Comment by philippjfr** [comment]
It is now possible to color line segments using the Path element:

```python
np.random.seed(10)
data = np.random.rand(100,4)
path = hv.Path([data], vdims=['y', 'z', 'size']).options(color='z', line_width=hv.dim('size'))
path
```
