### ISSUE TITLE
Investigate throttling behavior of scrubber widget

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#2571]
It seems that in certain scenarios at least the throttling behavior of the scrubber widget is not behaving very well at all causing large backlogs of events to accumulate and thereby clogging up the kernel execution queue. This was originally encountered in https://github.com/pyviz/EarthSim/issues/32.

**Comment by jbednar** [comment]
I believe the scrubber widget also needs to be documented somewhere on the website, unless that was done recently.

**Comment by kcpevey** [comment]
Got it. Looks good!
