### ISSUE TITLE
Switch to %reload_ext in the tutorials

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#258]
We should use ``%reload_ext holoviews.ipython`` instead of ``%load_ext holoviews.ipython`` as it behaves more predictably, reloading the extension without showing the message about the extension already being loaded.

This is particularly important for the next release as the HoloViews IPython extension now loads the necessary javascript and CSS into the cell - rerunning ``%load_ext`` removes this cell which then breaks the widgets in the notebook.

Of course ``%load_ext`` does still work but you need to be careful not to reload the extension! We could tell the user to use ``%reload_ext`` (our current welcome message is 'HoloViewsJS successfully loaded.')  but that might be awkward. Finally, we might need to make sure notebook testing works with this approach and we will probably have to regenerate all our reference data.

**Comment by philippjfr** [comment]
The notebook testing did not seem to mind the Logo + 'HoloViewsJS successfully loaded' + JS + CSS being added to the output so it might not cause any issues.

**Comment by jlstevens** [comment]
> The notebook testing did not seem to mind the Logo + 'HoloViewsJS successfully loaded' + JS + CSS being added to the output so it might not cause any issues.

I guess that is because it isn't a HoloViews object and isn't normal standard output either meaning this particular type of display output isn't captured and compared. Phew!

**Comment by jbednar** [comment]
I'd personally avoid putting any message by default, just to be nicer to people who want things to display without extra busyness.  Telling people to uniformly use reload_ext seems fine to me.

**Comment by philippjfr** [comment]
Just so you know what we're talking about, ``%load_ext`` and ``%reload_ext`` now display the following output:

![image](https://cloud.githubusercontent.com/assets/1550771/9634238/9f59899e-5188-11e5-81bb-9eed049def6f.png)

This message is important because it tells users that if they clear that cell the widgets will break.

**Comment by jbednar** [comment]
It doesn't tell *me* that in any way!

**Comment by philippjfr** [comment]
It simply mirrors what Bokeh have done, as you said I didn't want anything too "busy". Here's what it looks like in bokeh:

![image](https://cloud.githubusercontent.com/assets/1550771/9635118/b119ae08-518c-11e5-83a0-e823c41393b7.png)

Happy to change it though.

**Comment by jbednar** [comment]
I don't like it in Bokeh either; I find it intrusive if a package I've loaded interferes with the contents of my notebook without my permission.  If I wanted to know if BokehJS was loaded, I'd issue some command at the prompt explicitly.  Explicit is better than implicit, right?  :-)

**Comment by philippjfr** [comment]
How about allowing our own parameterized version of %load_ext while still supporting the old syntax?

**Comment by jlstevens** [comment]
> How about allowing our own parameterized version of %load_ext while still supporting the old syntax?

That seems fine to me although this isn't a concrete example. Perhaps you are thinking of something like this?

```python
hv.load_extension() # Basically same as %load_ext *without* injecting javascript
hv.load_extension(javascript=True) # Explicitly used to just inject javascript
```

**Comment by jlstevens** [comment]
Implementing this could also help address other issues such as #283

**Comment by jbednar** [comment]
I agree-- can we just have a normal function that loads the extension, with arguments, and then we can handle both re-execution (which should simply be a no-op the second time, not a warning or an error) and changing defaults (e.g. width to 100%)?

**Comment by philippjfr** [comment]
If we make it a ParameterizedFunction, we can have a css parameter, then if you want to always change the width, you can just set this in your notebook config:

```python
hv.ipython.load_notebook.css = """
div.container {
    width: 100%;
}"""
```

**Comment by jbednar** [comment]
That sounds good for the general case, but I'd want something very simple in addition so that a one-liner could be used in all our examples and tutorials, e.g.:

```
hv.load_extension(width=100)
```
instead of ``%load_ext holoviews`` which would then inject the appropriate CSS for this one very commonly desired case (and others if we find extremely common idioms that we find ourselves putting into the css parameter).

**Comment by philippjfr** [comment]
The new hv.notebook_extension function has now been merged. Closing this issue.
