### ISSUE TITLE
Uninformative error when creating Chord diagram

### ISSUE THREAD

**Issue by gmontamat** [ioam/holoviews#2581]
I was trying to create a Chord diagram based on https://github.com/ioam/holoviews/blob/master/examples/gallery/demos/bokeh/route_chord.ipynb
I assumed it should work on my dataframes since they were very similar to the ones in the examples. I got the error:

> ValueError: None of the available storage backends were able to support the supplied data format.

The actual issue was that I had loop edges (connecting nodes to themselves) which doesn't happen on the sample airport routes dataset. Removing those loops fixed the issue but a more clear error message would have saved me a couple hours.

**Comment by philippjfr** [comment]
Thanks for filing this issue, that would indeed be helpful. It's not quite clear to me why loop edges shouldn't be supported so this might in fact be a bug but for now I've labeled the issue as an enhancement request.

**Comment by philippjfr** [comment]
Would you happen to have a small example to reproduce this?

**Comment by philippjfr** [comment]
Nevermind, this is sufficient:

```python
hv.Chord([('A', 'B', 2), ('B', 'A', 3), ('A', 'A', 2)])
```

**Comment by philippjfr** [comment]
@gmontamat It will be once the PR above is merged.

**Comment by gmontamat** [comment]
@philippjfr great news! Thanks.

**Comment by garfield2020** [comment]
What data structure is needed for holoview chord diagrams?
I am trying to feed the center_path dataframe (screenshots
![screen shot 2019-03-08 at 10 03 51 am](https://user-images.githubusercontent.com/48362072/54043364-a8cf6580-4189-11e9-8871-67a113ac646e.png)
 attached) with 
hv.Chord(center_path)
and it gives me the error:
Number of samples, -1, must be non-negative.

**Comment by philippjfr** [comment]
@garfield2020 Could you provide a full traceback, and preferably a reproducible example?

**Comment by garfield2020** [comment]
Heres the full traceback, thanks philipp!
![screen shot 2019-03-08 at 10 58 12 am](https://user-images.githubusercontent.com/48362072/54046427-804b6980-4191-11e9-89cb-856761c736d3.png)

**Comment by philippjfr** [comment]
Are there any negative values in your ``value`` column?

**Comment by garfield2020** [comment]
That worked!  I filtered out the negative values, and no more error.
But now I run the code and still don't get a chord chart output:
![screen shot 2019-03-08 at 11 43 56 am](https://user-images.githubusercontent.com/48362072/54048698-c60b3080-4197-11e9-93be-65976f7409c7.png)

**Comment by jbednar** [comment]
You should call `hv.extension('bokeh')` if you want graphical representations.

**Comment by garfield2020** [comment]
Perfect!  thank you both
