### ISSUE TITLE
Objects produced by renderer.get_plot do not display in the notebook

### ISSUE THREAD

**Issue by abourrier** [ioam/holoviews#2587]
Since holoviews 1.9.10, this code

```python
import holoviews as hv
hv.extension("bokeh")
renderer = hv.renderer("bokeh")
curve = hv.Curve(range(10))
curve_plot = renderer.get_plot(curve)
curve_plot
```

yields a text output instead of the proper figure:

> CurvePlot(apply_extents=True, apply_ranges=True, bgcolor=None, border=10, default_tools=['save', 'pan', 'wheel_zoom', 'box_zoom', 'reset'], finalize_hooks=[], fontsize={'title': '12pt'}, gridstyle={}, height=300, interpolation='linear', invert_axes=False, invert_xaxis=False, invert_yaxis=False, labelled=['x', 'y'], lod={'factor': 10, 'interval': 300, 'threshold': 2000, 'timeout': 500}, logx=False, logy=False, name='CurvePlot01090', normalize=True, projection=None, shared_axes=True, shared_datasource=True, show_frame=True, show_grid=False, show_legend=True, show_title=True, sizing_mode='fixed', title_format='{label} {group} {dimensions}', toolbar='right', tools=[], width=300, xaxis='bottom', xrotation=None, xticks=None, yaxis='left', yrotation=None, yticks=None)

It seems to work neither with matplotlib backend nor with other types of figures.

**Comment by jlstevens** [comment]
If I remember correctly, there was a thing to make the plotting classes themselves display themselves with the display hooks. I assume that will no longer work with the changes made for Jupyterlab compatibility (@philippjfr ?) ...

This was really meant as a convenience for developers and not for users. @abourrier Why not just view ``curve``?

**Comment by abourrier** [comment]
In my use case, I have (x,y,z) aggregated data that I visualize as a `DynamicMap` of `HeatMap`s ((x,y) being the `HeatMap` kdims and z being the `DynamicMap` kdim). I want to bind the click on a particular square of the current `HeatMap` to a python callback (which will load the corresponding chunk of data and represent it in detail inside a different figure). The problem with defining a `Tap` stream bound to the `DynamicMap` is that I only have access to the (x,y) information and not to the current value of z.

As a workaround to this limitation, I previously used the `renderer` feature to get a handle on the figure, so that I could access at any moment the `fig.current_key` item which would give me the current z value in my callback.

**Comment by philippjfr** [comment]
>As a workaround to this limitation, I previously used the renderer feature to get a handle on the figure, so that I could access at any moment the fig.current_key item which would give me the current z value in my callback.

Sounds like you'd be much better served by some extension to this https://github.com/ioam/holoviews/issues/604 which would make the last displayed frame and key available.

For the time being I'd be in favor of supporting Plot instances in the ``display`` function and I've opened a PR to that effect here: https://github.com/ioam/holoviews/pull/2589

I'd only recommend using that for debugging or for the time being as a workaround.

**Comment by abourrier** [comment]
Making the latest key available would indeed be sufficient and more practical in the mentioned use case.

Additionally, my colleagues and I use plot handles when we want to finely customize the plot, such as modifying xlabels fonts/colors. It is sometimes very useful to have fine-grained control over the plot to maximize the amount of information conveyed by the visualization. Therefore being able to get a handle on the plot produced by holoviews is still pretty useful to us, even though it may not be the initial intent.

**Comment by philippjfr** [comment]
>Additionally, my colleagues and I use plot handles when we want to finely customize the plot, such as modifying xlabels fonts/colors. It is sometimes very useful to have fine-grained control over the plot to maximize the amount of information conveyed by the visualization. Therefore being able to get a handle on the plot produced by holoviews is still pretty useful to us, even though it may not be the initial intent.

That's true, although we do provide a mechanism to do that via the ``finalize_hooks`` which let you define function to customize the plot, e.g.:

```python
def customize_plot(plot, element):
    plot.handles['xaxis'].major_label_text_color =  'red'
    plot.state.border_fill_color = 'gray'

hv.Curve([1, 2, 3]).options(finalize_hooks=[customize_plot])
```

**Comment by philippjfr** [comment]
The change to allow the display function to display plots is now merged so I'll close this.
