### ISSUE TITLE
Nested bar plots in mpl

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#2595]
The Bars example from http://pyviz.org/tutorial/01_Workflow_Introduction.html works well in Bokeh:

![image](https://user-images.githubusercontent.com/1695496/39082277-1a032726-4516-11e8-8146-ecd9ab10427b.png)

But gives a blank plot in Matplotlib:

![image](https://user-images.githubusercontent.com/1695496/39082279-29aadf52-4516-11e8-9fdd-d9fe5480e334.png)

Any ideas?

**Comment by philippjfr** [comment]
The matplotlib BarPlot needs a total rewrite, there's already two issues about it https://github.com/ioam/holoviews/issues/1407 and https://github.com/ioam/holoviews/issues/1047.
