### ISSUE TITLE
Is .opts required for setting widths?

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#2599]
I can't figure out how to use .options to set what seems like a simple option, i.e. the width of a single Element:

```
import pandas as pd, holoviews as hv
hv.extension('bokeh')

url     = 'https://raw.githubusercontent.com/blmoore/blogR/master/data/measles_incidence.csv'
data    = pd.read_csv(url, skiprows=2, na_values='-')
yearly  = data.drop('WEEK', axis=1).groupby('YEAR').sum().reset_index()
measles = pd.melt(yearly, id_vars=['YEAR'], var_name='State', value_name='Incidence')
heatmap = hv.HeatMap(measles).options(height=500, width=900)

heatmap
```

![image](https://user-images.githubusercontent.com/1695496/39087210-71683aea-4563-11e8-8aef-c6f3c03bbc02.png)

It works if I use the more obscure .opts version:

```
heatmap.opts(plot=dict(width=900))
```

![image](https://user-images.githubusercontent.com/1695496/39087221-9fdf6358-4563-11e8-8c85-eaa2e5599bf6.png)

I can't tell if this is my confusion, an inherent limitation of some sort, or a bug.

Also, I would have expected this call to do nothing, not to generate an error:

```
heatmap.options()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-20a23445f470> in <module>()
----> 1 heatmap.options()

/Users/jbednar/holoviews_git/holoviews/core/dimension.py in options(self, options, backend, clone, **kwargs)
   1215 
   1216         from ..util import opts
-> 1217         expanded = opts.expand_options(options, backend)
   1218         return self.opts(expanded, backend, clone)
   1219 

/Users/jbednar/holoviews_git/holoviews/util/__init__.py in expand_options(cls, options, backend)
    122         backend_options = Store.options(backend=backend or current_backend)
    123         expanded = {}
--> 124         for objspec, options in options.items():
    125             objtype = objspec.split('.')[0]
    126             if objtype not in backend_options:

AttributeError: 'NoneType' object has no attribute 'items'
```
Obviously, it's not a useful thing to do by itself, but it seems like something that could come up if someone is passing around a dictionary of options and expanding it into keyword arguments; such a dictionary could easily be empty.

**Comment by philippjfr** [comment]
Still not sure what's up with ``width`` here.

>Obviously, it's not a useful thing to do by itself, but it seems like something that could come up if someone is passing around a dictionary of options and expanding it into keyword arguments; such a dictionary could easily be empty.

Definitely a bug that I actually fixed in https://github.com/ioam/holoviews/pull/2354 but we didn't end up merging in time for 1.10.
