### ISSUE TITLE
Fix sublabels for massive numbers of figures

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#26]
For ImaGen, we are demonstrating all of the various pattern types available by dumping them all out:

from imagen import *
from imagen.random import *
from imagen.image import *
np.sum([x()[:] for x in locals().values() if isinstance(x,type)
        and issubclass(x,PatternGenerator) and not x.abstract]).cols(5)

But for enough patterns, this fails unless we turn off sublabels:

%opts Layout [sublabel_format=""] Image (cmap='gray') [show_xaxis=None show_yaxis=None show_frame=True]

because the chr() call eventually gets into unicode errors, as it goes away from alphabetic characters.  Should use modulo to go A..Z then AA, AB, etc.

**Comment by philippjfr** [comment]
Just pushed a new utility function, which will generate arbitrary length alphabetic enumerators. Probably overkill but at least we won't have a repeat of this issue if someone tries to plot a figure with 677 subplots.
