### ISSUE TITLE
hv.Text fontsize doesn't work

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#260]
```python
import numpy as np
import holoviews as hv
%reload_ext holoviews.ipython
hv.Curve(np.random.rand(10))*hv.Text(5, 0.5, 'test', fontsize=2)
```

gives
![download](https://cloud.githubusercontent.com/assets/6897215/9699496/808a2fe6-53e5-11e5-9e41-ec68f71e3107.png)

```python
hv.Curve(np.random.rand(10))*hv.Text(5, 0.5, 'test', fontsize=2)
```
gives
![download 1](https://cloud.githubusercontent.com/assets/6897215/9699499/89671638-53e5-11e5-89e6-2f8bc23787fa.png)

**Comment by basnijholt** [comment]
Fixed in #261, but might not be the solution you want.

**Comment by basnijholt** [comment]
Fixed in ddc68d3db5.

**Comment by philippjfr** [comment]
Yep, thanks. Closing now.

**Comment by vascotenner** [comment]
This breaks the ```%%opts Text (fontsize=....)``` magic
