### ISSUE TITLE
Selecting on an overlay of points

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#2600]
In http://pyviz.org/tutorial/01_Workflow_Introduction.html#Interactive-statistical-plots , there are lasso and box-select tools enabled, but they don't appear to do anything.

![image](https://user-images.githubusercontent.com/1695496/39087375-d115ee54-4565-11e8-9974-96e7558a54d5.png)

It's probably to do with having the different datasets overlaid, making it unclear what should be selected, but it would be great if selection would work properly so that we can see the same data points marked across all the different subplots.

**Comment by philippjfr** [comment]
This is not actually a bug, the issue is the ``alpha=0.7`` definition, which overrides the ``nonselection_alpha`` and ``selection_alpha`` and therefore makes it appear that the selection doesn't have an effect. I would simply fix it by setting ``nonselection_alpha=0.1``

**Comment by philippjfr** [comment]
I'm going to close since the holoviews example doesn't use the tools, and since the selection applies to each set of points separately it isn't that useful anyway.

**Comment by jbednar** [comment]
Thanks for debugging that!  For now, I'll just remove the alpha=0.7 from that example.  

However, don't we need to keep this issue open?  There is still an underlying problem, in that I would like to be able to select on an Overlay as a group of points, not just on individual sets of Points in the Overlay.

**Comment by jbednar** [comment]
Actually, now I'm confused. If I start with the unselected version:
![image](https://user-images.githubusercontent.com/1695496/39328924-802324ac-4962-11e8-9f74-22763349a4c4.png)
and draw a box that includes all three types, I can select across types:
![image](https://user-images.githubusercontent.com/1695496/39328961-95cb708e-4962-11e8-9d55-8fb1daf06db6.png)
But then if I select a region that contains only one type (blue in this case), those points are selected and only the other blue points are deselected:
![image](https://user-images.githubusercontent.com/1695496/39329030-c2976b36-4962-11e8-95b1-1471ebbd03a7.png)
So it does seem possible to select across groups of points?

**Comment by philippjfr** [comment]
>So it does seem possible to select across groups of points?

When structured as an overlay each set of points selects separately, we could probably restructure it so that all points are in the same group and simply categorically colormapped on the species. That should allow all points to be selected on at once.

**Comment by philippjfr** [comment]
To clarify the immediate issue is caused by the fact that each group selects separately and an empty selection on any group resets the selection.

**Comment by philippjfr** [comment]
>Because at the UI level I can select them together in a single action, as shown in the middle plot above.

Right, the selection is applied to each group separately. Here's the equivalent where all points are in the same group and simply colored differently. The last ``.map`` bit is a bit ugly, I'll probably add an argument to ``gridmatrix`` to easily add additional vdims to the elements.

```
%%opts Bivariate [bandwidth=0.5] (cmap=Cycle(values=['Blues', 'Reds', 'Oranges'])) Histogram (alpha=0)
%%opts NdOverlay [batched=False] Points [tools=['box_select'] color_index='species'] (cmap=hv.Cycle().values size=2 alpha=0.5 nonselection_alpha=0.1)
density_grid = gridmatrix(iris_ds.groupby('species').overlay(), diagonal_type=hv.Distribution, chart_type=hv.Bivariate)
point_grid = gridmatrix(iris_ds, chart_type=hv.Points)

density_grid * point_grid.map(lambda x: x.clone(vdims=x.vdims+['species']), hv.Points)
```
