### ISSUE TITLE
bounds on hv.Image? 

### ISSUE THREAD

**Issue by laleph** [ioam/holoviews#2605]
```
import numpy as np
import xarray as xr
import holoviews as hv
import matplotlib.pyplot as plt
hv.notebook_extension()

x = np.linspace(-6, 4, 50)
y = np.linspace(-9, 5, 60)
z = x + y[:, np.newaxis]
arr = xr.DataArray(z, coords=[y, x,], dims=['x', 'y'], name="intensity")

lim = 4
plot = hv.Image(arr, bounds=(-lim,-lim,lim,lim))
plot
```
Is this an intended behaviour in the new 1.10.1 version?
In older versions cropping the data range was working.

**Comment by philippjfr** [comment]
Definitely not intended, passing in the ``bounds`` when the data already defines coordinates should raise an error. To be clear, what was the behavior you expected here?

**Comment by laleph** [comment]
I wanted to crop the image to a specific data range by setting certain limits (lim).

**Comment by laleph** [comment]
What would be the intended way? `.redim.range()`?

**Comment by philippjfr** [comment]
>I wanted to crop the image to a specific data range by setting certain limits (lim).

The ``bounds`` define the overall range of the data and should never be used to define a cropped bounds. If you actually want to crop data I'd suggest using ``.redim.range`` or actually applying a ``.select``.

**Comment by laleph** [comment]
Thanks. Apparently I misused `bounds` before. :grin:

**Comment by jlstevens** [comment]
Isn't there an issue already about deprecating ``bounds``? If so it should be linked here. I'll have a look...
