### ISSUE TITLE
Add Contours to list of datashadable types

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#2609]
Contours isn't currently listed as doing something useful with datashader, but it actually can:

![image](https://user-images.githubusercontent.com/1695496/39150356-b076105e-4707-11e8-8323-95d6b99bc72d.png)

However, the default aggregator of `count` isn't very useful with Contours, and it should probably be `mean` instead, as without an explicitly specified aggregator all contours end up the same color.

**Comment by jbednar** [comment]
Added example of using contours with datashade in #2608.

**Comment by philippjfr** [comment]
Looking at this code I wonder if we should also support aggregating Paths by value as in this example:

<img width="926" alt="screen shot 2018-04-26 at 1 25 24 pm" src="https://user-images.githubusercontent.com/1550771/39305523-5201b474-4955-11e8-83c8-c305691fd52b.png">

**Comment by jbednar** [comment]
Supporting aggregating Paths by value sounds very useful to me!

**Comment by philippjfr** [comment]
It's already supported, the question is whether to enable it by default. Doing so might be surprising since Path itself does not enable it unless the ``color_index`` is set.

**Comment by jbednar** [comment]
Once again we come up against the conflict between plot options defining a certain sort of plot, and the datashader operations not respecting that.  I really think we have to rethink that approach.

**Comment by philippjfr** [comment]
>I really think we have to rethink that approach.

I'm sympathetic to that but I think there's many obstacles to that. What happens if different backends define clashing options? What happens to options like ``width`` and ``height`` which are only defined for certain backends?

Anyway, I'm going to close this now, please open an issue about the options thing if you want to have that discussion.
