### ISSUE TITLE
dynamic legend request

### ISSUE THREAD

**Issue by scaine1** [ioam/holoviews#2611]
It would be very useful to have legends that dynamically update depending on which elements are selected from a stream.
In order to make an example as simple as possible I have copied code from http://holoviews.org/reference/streams/bokeh/curve_selection.html
and modified it slightly.

In essence, I would like the legend on the right-hand plot to update and only show the elements that are selected from the left-hand plot.

```python
import numpy as np
import holoviews as hv
from holoviews import streams
hv.extension('bokeh')

renderer = hv.renderer('bokeh')

no_leg = "NdOverlay [legend_limit=0] Curve [tools=['tap', 'lasso_select']] (line_width=10)"

ndoverlay = hv.NdOverlay({i: hv.Curve(np.arange(10)*i) for i in range(5)}).opts(no_leg)

selection = streams.Selection1D(source=ndoverlay)
dmap = hv.DynamicMap(lambda index: ndoverlay[index] if index else ndoverlay.clone(),
                             kdims=[], streams=[selection])

with_leg = "NdOverlay [legend_limit=5] Curve [tools=['tap', 'lasso_select']] (line_width=10)"
doc = renderer.server_doc(ndoverlay + dmap.opts(with_leg))
```

I am not sure how difficult this will be to implement and how useful it will be to a wider audience.
If someone could give me some pointers on where to start I could look into tackling this problem myself

**Comment by philippjfr** [comment]
Now implemented.
