### ISSUE TITLE
Adding axis labels affects range

### ISSUE THREAD

**Issue by papahabla** [ioam/holoviews#2613]
The following demonstrates how the same plot which sets the x, and y range is changed when labels are added. It seems that the `.redim` is somehow overwritten and the specified range is not used.

* bokeh:                              0.12.15-py27_0
* holoviews:                          1.10.1-py_0                ioam

```
x = np.linspace(-20, 0, 16)
y = np.linspace(75, 96, 16)
withlabel = hv.Overlay([
    hv.Curve((x, y), 'Master Volume (dB)', 'Target SPL')
]).redim(x={'range': (vol_db[0], 0)}, y={'range': (vol_db[0]+vol_def_spl-vol_d
ef_db, 110)})

withoutlabel = hv.Overlay([
    hv.Curve((x, y))
]).redim(x={'range': (vol_db[0], 0)}, y={'range': (vol_db[0]+vol_def_spl-vol_def_db, 110)})

withlabel + withoutlabel
```

![screenshot-45](https://user-images.githubusercontent.com/10580407/39205119-ab40b0c4-47ae-11e8-9fc2-f57c0ff1b4dc.png)

**Comment by philippjfr** [comment]
@papahabla The ``redim``  method changes the parameters of any dimensions that match the keyword. When you instantiate the Curve without explicit dimension names the dimensions default to x and y, so ``redim(x=`` matches the dimension, by changing the dimension labels ``x`` and ``y`` no longer match the dimension and the range is not applied. To make this easier you can give the dimensions a name to refer to the dimension by and a label:

```python
withlabel = hv.Overlay([
    hv.Curve((x, y), ('volume', 'Master Volume (dB)'), ('spl', 'Target SPL'))
])
```

Now you can apply ``.redim.range`` on the volume and spl dimensions:

```python
with_label.redim.range(volume=(vol_db[0], 0)}, spl=(vol_db[0]+vol_def_spl-vol_def_db, 110))
```
