### ISSUE TITLE
Dimensioned.range API discussion

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#2618]
The ``Dimensioned.range`` method has been around a long time and computes the range on any object. It has one keyword argument called ``data_range`` which is a boolean and determines whether the returned range should take the actual range of the data into account or not. Unfortunately for many cases that isn't sufficient, you just want to know the range of the actual data and ignore the ``Dimension.range`` and ``Dimension.soft_range``. Changing the semantics of data_range=True/False does not seem like an option, so I wanted to brainstorm about how best to achieve these three semantics "give me just the range of the data",  "give me the combined data and Dimension ranges" and "give me just the dimension ranges".

These are the two options I'd consider, leaning towards the latter:

1. Add a third possible value for data_range, e.g. ``data_range='exclusive'``.
2. Add another keyword argument to toggle whether to include the Dimension ranges, e.g. ``data_range=True, dimension_range=False``.

**Comment by philippjfr** [comment]
Related to https://github.com/ioam/holoviews/issues/1212. I'd very much like to resolve this for 1.11 as it's a requirement to start improving normalization. @jlstevens Would you mind reading this issue and #1212 and considering which option you would prefer? My preference would be for the proposal 2. laid out in this issue.

**Comment by jlstevens** [comment]
So ``dimension_range`` would be ``True`` by default to match the current behavior? In other words, the current behavior is ``data_range=True, dimension_range=True`` whereas ``data_range=True, dimension_range=False`` would give you the range you are looking for?

Then when ``data_range=False, dimension_range=True`` it should just me the ranges specified by the dimensions and nothing else.

If that is all correct, then adding a boolean ``dimension_range`` switch seems like a reasonable proposal.

**Comment by philippjfr** [comment]
That's all correct, the only weirdness there is ``data_range=False, dimension_range=False``, which would always just return ``(None, None)``.

**Comment by jlstevens** [comment]
> That's all correct, the only weirdness there is data_range=False, dimension_range=False, which would always just return (None, None).

You could do that (which is fine) or enforce that one of those flags are ``True``. I think I prefer the latter option: if both are ``False`` then you probably made a mistake!

**Comment by philippjfr** [comment]
This has been implemented, `.range` now has data_range and dimension_range arguments.
