### ISSUE TITLE
Opts magic does not work with dictionaries with string keys and values

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#262]
The parser seems to be adding extra commas, which means you can't specify font sizes in bokeh

```python
%%opts Curve [fontsize={'title': '10pt'}]
hv.HoloMap({(i): hv.Curve(np.random.rand(10,2)) for i in range(10)})
```

```
WARNING:root:Warning: Ignoring keyword pair that fails to evaluate: 'fontsize={'title':,'10pt',}'
```

**Comment by jlstevens** [comment]
How does the fontsize parameter work with matplotlib? The idea is to keep the interfaces the same if possible. If this parameter no longer works with matplotlib (which seems unlikely) then there is a real issue with the parser.

Alternatively, feel free to try and improve the parser! Personally, I wouldn't immediately attempt this as I know that the  code is rather involved and fairly tricky. It would probably take a fair bit of effort to fix in a solid and general way. :-)

**Comment by philippjfr** [comment]
In matplotlib font sizes are always defined as numbers, so the parser doesn't end up adding the extra commas. It's only if the dictionary is all strings that you get this problem.

**Comment by jlstevens** [comment]
Ok, that's what I thought!

In that case why not make the bokeh backend behave in the same way as the matplotlib one? There are obvious reasons why this would be a good idea anyway and helps avoid having to spend time trying to improve the parser.

**Comment by philippjfr** [comment]
I've implemented the suggestion by @jlstevens to allow specifying the fontsizes as integers in bokeh. I've also opened #270 as a more general issue to gather examples where the OptsSpec parser fails. I'll close this issue now.

**Comment by jlstevens** [comment]
Ok great! I agree that a new issue for improving the parser is appropriate.

**Comment by RafalSkolasinski** [comment]
I don't know how much it is related but also with standard backend following works perfectly
```
%opts Path [fontsize={'ticks':14, 'labels':15}]
```
when 
```
%opts Path [fontsize={'ticks': 14, 'labels': 15}]
```
throws also warning
```
WARNING:root:Warning: Ignoring keyword pair that fails to evaluate: 'fontsize={'ticks':,14,'labels':,15}'
```
