### ISSUE TITLE
Difference between bokeh and mpl measles_example

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#2633]
In bokeh:

![image](https://user-images.githubusercontent.com/890576/39376590-21ccfa02-4a4a-11e8-8d3b-d856bca348c2.png)

and matplotlib:

![image](https://user-images.githubusercontent.com/890576/39376609-32577e56-4a4a-11e8-8e13-bbb1e92674f4.png)

It seems to be down to ``logz=True`` not working right for matplotlib:

![image](https://user-images.githubusercontent.com/890576/39376636-44fabb04-4a4a-11e8-8d3e-7ddd2af82534.png)

**Comment by philippjfr** [comment]
What version of matplotlib do you have? When I activate ``logz`` it seems to come out right:

![image](https://user-images.githubusercontent.com/1550771/39406460-dffe98ea-4bae-11e8-990d-625b44701198.png)

**Comment by philippjfr** [comment]
Now enabled it in https://github.com/ioam/holoviews/pull/2629, but worth figuring out why it works for me.

**Comment by jlstevens** [comment]
> What version of matplotlib do you have?

That would be '2.2.2'

**Comment by jlstevens** [comment]
If it helps, I do get these warnings:

```
/Users/jstevens/miniconda3/envs/analytics/lib/python3.6/site-packages/matplotlib/colors.py:1031: RuntimeWarning: invalid value encountered in less_equal
  mask |= resdat <= 0
/Users/jstevens/miniconda3/envs/analytics/lib/python3.6/site-packages/matplotlib/colors.py:504: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
```

**Comment by jlstevens** [comment]
Urgh. Upgrading numpy fixed it. So I guess we need to pin numpy:

```
conda install numpy
Solving environment: done

## Package Plan ##

  environment location: /Users/jstevens/miniconda3/envs/analytics

  added / updated specs:
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    numba-0.36.2               |np114py36hc2f221f_0         2.3 MB

The following packages will be UPDATED:

    numba: 0.36.2-np113py36hceb9f0c_0 --> 0.36.2-np114py36hc2f221f_0
    numpy: 1.13.3-py36ha9ae307_4      --> 1.14.2-py36ha9ae307_1
```

**Comment by jlstevens** [comment]
Very mysterious! I think we are out of ideas so @jbednar maybe it would be instructive if you could try this example and report what you see?

**Comment by jbednar** [comment]
No problem with logz with mpl for me:

![image](https://user-images.githubusercontent.com/1695496/39430117-8d9de1a6-4c52-11e8-8dab-a6476562ef09.png)

**Comment by jlstevens** [comment]
> though the colors do seem fairly different from the Bokeh version

Also, I notice that 'Alaska' has a white row at the start in the bokeh version (presumably missing data) but I don't see that in your screenshot. They do seem to be quite different.

**Comment by philippjfr** [comment]
It looks like one version (presumably matplotlib) is incorrectly inverted along the y-axis.

**Comment by jlstevens** [comment]
> It looks like one version (presumably matplotlib) is incorrectly inverted along the y-axis.

Agreed. Perhaps this issue can aim to fix that bug and ignore the logz bug as I seem to be the only one affected by it so far (with no idea why?)
