### ISSUE TITLE
Dynamic Dataset.groupby causes wrong sorting

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#2641]
When using groupby on a Dataset with ``dynamic=True`` it queries the data for the unique values along the grouped dimension and then sets ``Dimension.values``. If these values are unsorted the widgets will not behave correctly in two separate ways: 1) It will initialize on the wrong frame and 2) when updating it will do so on the unsorted keys, resulting in the wrong frame being displayed.

**Comment by jlstevens** [comment]
Is this just a matter of sorting things at the widget level?

**Comment by philippjfr** [comment]
>Is this just a matter of sorting things at the widget level?

That's a partial fix (i.e. for issue 2 above), but it still initializes on the wrong frame.
