### ISSUE TITLE
Table to errorbars

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#265]
I like to create an errorbarplot from a table, this is closely related to #103 .
```
table.to.errobars(x,y,yerr)
````

**Comment by philippjfr** [comment]
This has now been added along with a spreadfn argument to reduce/collapse/aggregate methods. You can see an example of the usage here https://github.com/ioam/holoviews/issues/103#issuecomment-157368725. If you have a Table containing an column corresponding to the error you can call ``table.to.errorbars(['x'], ['y', 'yerr'])``. I'll also be adding a new Tutorial with some examples of this.

Closing this issue now.
