### ISSUE TITLE
AdjointLayout does not layout properly in a multi-row Layout

### ISSUE THREAD

**Issue by suyang-nju** [ioam/holoviews#2652]
points = hv.Points(np.random.randn(100, 2))
    hist1 = hv.operation.histogram(points, dimension='x')
    hist2 = hv.operation.histogram(points, dimension='y')
    ad = points << hist2 << hist1

    hv.Layout([ad]*2).cols(1)

![21](https://user-images.githubusercontent.com/35547836/39640867-5d562fda-4f9a-11e8-86e8-364da8f57c24.png)

Similarly, `hv.Layout([ad]*4).cols(2)` produces
![42](https://user-images.githubusercontent.com/35547836/39640887-6cc9ba2c-4f9a-11e8-863a-a837bd7a9135.png)

When the number of columns in the Layout matches the number of AdjointLayouts, the plots are fine.

**Comment by philippjfr** [comment]
Thanks for the bug report, that's a pretty catastrophic failure of the layout code!

**Comment by jlstevens** [comment]
Would be good to fix for 1.10.3.

**Comment by philippjfr** [comment]
>Would be good to fix for 1.10.3.

Not even going to attempt that, we should get that out soon and layout bugs are too hairy and involved to fix quickly.

**Comment by philippjfr** [comment]
Probably related to https://github.com/ioam/holoviews/issues/1489.
