### ISSUE TITLE
Standalone HTML export for HoloMaps

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#267]
The notebook archive facility currently doesn't export HoloMaps by default. Currently, you can output video (or GIF) if you want but generally these formats aren't particularly useful. In contrast, a standalone HTML file that includes interactive widgets could be useful and would work across both the matplotlib and the bokeh backends.

Another advantage of this adding this support (especially if tested!) is that it would help ensure HoloViews is tied to the HTML standard as opposed to anything specific to the notebook format. It might also open the possibility of generating documents which aren't notebooks (e.g. report documents containing interactive widgets).

As a side-issue, this might make us think of how we want to store data for such documents (as opposed to base64 encoding everything in the HTML file). This is a more open problem and something I know the IPython people are also thinking about.

**Comment by philippjfr** [comment]
This has been on my radar for a while, there's nothing about our figure, video and widget rendering that's tied to the notebook and it'll be very useful to have something like this, for example I can imagine HoloViews running on a live server returning HTML to be injected into a website. As a quick demo we could have a simple web app that allows you to upload hvz files and returns the rendered HTML output.

In terms of storing the embedded data in a separate file I'd suggest sticking with a simple json file format, it's the format that the dynamic loading widgets already support and most databases can load in json files nowadays. The one issue I've had loading from json files is that only some browsers can open json files without a server (Chrome doesn't let you). One workaround is to define the json as an object in a js file, for some reason browsers trust js but not json. This is a bit of a hack but is the only way I've found to get around having a separate server to serve the json data.

**Comment by jlstevens** [comment]
JSON is definitely the format that makes the most sense.

> One workaround is to define the json as an object in a js file, for some reason browsers trust js but not json.

Sounds reasonable to me.

That said I'm not sure whether this is really the 'right thing' to do. On one hand, this is circumventing the browser's security model and on the other, people are perfectly able to  inject malicious javascript  without needing our help!

As such, I don't think this is a particularly terrible workaround. All I would ask is that the ``.js`` file is just a JSON file in disguise with no extra JavaScript (unless absolutely necessary). If the file cannot be directly be parsed as JSON, I would want the minimal wrapping necessary to make it work.

**Comment by philippjfr** [comment]
The PR #324 implementing these suggestions has now been merged. Closing.
