### ISSUE TITLE
Clarify docstrings of .opts and .options

### ISSUE THREAD

**Issue by foobarbecue** [ioam/holoviews#2689]
Currently, the docstrings for [.opts](https://github.com/ioam/holoviews/blob/cbdac8c5a0a1e4cc43eafe62f39c2843f26935df/holoviews/core/spaces.py#L76) and [.options](https://github.com/ioam/holoviews/blob/cbdac8c5a0a1e4cc43eafe62f39c2843f26935df/holoviews/core/spaces.py#L99) are identical except for subtly different examples.

These should be clarified to indicate that .options is a more user-friendly version of .opts ... if that is the case. Also, it might be worth mentioning in the docstring the relationship to cell magics.

**Comment by foobarbecue** [comment]
Also, http://holoviews.org/user_guide/Customizing_Plots.html focuses exclusively on .opts and does not mention .options . @jbednar told me on gitter that holoviews is trying to expose new users to .options rather than .opts so I guess this issue might be expanded beyond docstrings to include updating the Customizing Plots example in the user guide.

**Comment by philippjfr** [comment]
As @foobarbecue kindly pointed out:

>I just realized I learned about .opts from http://holoviews.org/user_guide/Customizing_Plots.html -- it is very ".opts forward"

We should definitely update this.

**Comment by philippjfr** [comment]
Since 1.11.0 `.opts` and ``.options`` support the same signatures and we've updated all the documentation to recommend `.opts`, so I think this can be closed.
