### ISSUE TITLE
Access node attributes when using Graph.from_networkx() method

### ISSUE THREAD

**Issue by CurtLH** [ioam/holoviews#2696]
It would be great to be able to access the node/edge attributes in a NetworkX graph when loading it into holoviews using the `Graph.from_networkx()` method.  For example, I have an attribute representing which group a node belongs to, and I want to color the nodes in the network according to that attribute.   I know that I can use bokeh to do this manually, but I'd much rather use holoviews to annotate my data and make this process much easier.

**Comment by philippjfr** [comment]
Thanks for filing this issue. This was a definite oversight when writing the from_networkx method, and should be quite straightforward to implement.

**Comment by philippjfr** [comment]
Now implemented and should land in the next release (1.10.5 due tomorrow).

**Comment by CurtLH** [comment]
Thank you!
