### ISSUE TITLE
Confusing example in getting started tutorial

### ISSUE THREAD

**Issue by ryarco** [ioam/holoviews#2703]
![screenshot_20180520-120025](https://user-images.githubusercontent.com/3829521/40275599-99088e4a-5c26-11e8-99c1-1b7c9e36ca94.png)
The page http://holoviews.org/getting_started/Customization.html

Contains the text "Notice that the representation for this object is purely textual" directly beneath a graphical plot.

**Comment by jbednar** [comment]
Yes, that's a bug in how the website was built; if you run the notebook yourself you should see the textual representation.  I believe @philippjfr had a fix for that (?), but I don't think we've updated the website yet.

**Comment by ryarco** [comment]
Thanks for the quick reply @jbednar. This looks like a great project!

**Comment by jlstevens** [comment]
Yes, it should be fixed though it is still incorrect on [dev.holoviews.org](http://dev.holoviews.org/getting_started/Customization.html). @philippjfr Hasn't there been a doc build and upload to dev.holoviews since the change the the nbpublisher extension?

**Comment by philippjfr** [comment]
There has but maybe I didn't pull the latest version of the submodule before building.

**Comment by philippjfr** [comment]
Fixed in the latest build.
