### ISSUE TITLE
Range fails for explicit datetime dimension range 

### ISSUE THREAD

**Issue by douglasmacdonald** [ioam/holoviews#2708]
This did not previously fail but I do not know exactly when this stopped working.

I think that this is important. A principle of Holoviews is to **annotate your data** but by doing so, in the case, it causes a failure.

* `holoviews.__version__` : `1.10.4`
* File: `holoviews\core\data\__init__.py`
* Class: `class Dataset(Element):`
* Method: `def range(self, dim, data_range=True):`
* Line: `elif all(v is not None and np.isfinite(v) for v in dim.range):`
* Error message: `TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''`

The `range` method of the `Dataset` class no longer works for `dim` of type `<class 'pandas._libs.tslibs.timestamps.Timestamp'>`.

It fails because of the check `np.isfinite(v)` in the line `elif all(v is not None and np.isfinite(v) for v in dim.range):`. Because I do not know the full intention of this check, ***I can not suggest a proper fix***. However, I can get it working in my application by changing the line to: `elif all(v is not None for v in dim.range):`.

Using an example, here is my understanding of what might be going on. In `range` when `get_dimension` is called then `(None, None)`  is returned and the range is inferred successfully elsewhere.

    import pandas as pd
    import holoviews as hv

    t = pd.date_range(start="2018-01-01", end="2018-01-02", freq='h')
    y =range(len(t))
    df = pd.DataFrame({'t':t, 'y':y})

    c = hv.Curve(df)
    
    c.range('t')

Whereas, if a dimension is added then these are returned by by `get_dimension` as a 2-tuple of Pandas  `datetime`. And it is this that the condition fails.

    import pandas as pd
    import holoviews as hv

    t = pd.date_range(start="2018-01-01", end="2018-01-02", freq='h')
    y =range(len(t))
    df = pd.DataFrame({'t':t, 'y':y})

    c = hv.Curve(df, kdims = [hv.Dimension(('t', 'Time')
        , unit='time'
        , range=(t[0], t[-1]))])
    
    c.range('t')

`TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
(datepicker)
`

PS. I am confused about the role and relationship between similar functionality in `dimension.py`.

**Comment by jlstevens** [comment]
Given that this used to work, it does sound like a bug to me.

**Comment by douglasmacdonald** [comment]
Thank you.

**Comment by douglasmacdonald** [comment]
Minor suggestion....

An additional test might be changing the -1 to -2 in https://github.com/ioam/holoviews/pull/2715/commits/59e920e76ad9a245ad6b0b2e978f2fa20b42d107 

This would prove that the range returned was not the default limits of the data `dt64` (index [0] and [-1]) but that set by the `range=`.

    def test_dataset_range_with_dimension_range(self):

        dt64 = np.array([np.datetime64(datetime.datetime(2017, 1, i)) for i in range(1, 4)])
        ds = Dataset(dt64, [Dimension('Date', range=(dt64[0], dt64[-2]))])
        self.assertEqual(ds.range('Date'), (dt64[0], dt64[-2]))
