### ISSUE TITLE
Misformatted help text

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#2710]
If I do `hv.help(hv.Labels)`, I  get bogus formatting for some of the parameters:

```
>>> hv.help(hv.Labels)
Parameter docstrings:
=====================

cdims:    The constant dimensions defined as a dictionary of Dimension:value
          pairs providing additional dimension information about the object.
          
          Aliased with constant_dimensions.
datatype: A priority list of the data types to be used for storage
                 on the .data attribute. If the input supplied to the element
                 constructor cannot be put into the requested format, the next
                 format listed will be used until a suitable format is found (or
                 the data fails to be understood).
extents:  Allows overriding the extents
                        of the Element in 2D space defined as four-tuple
                        defining the (left, bottom, right and top) edges.
kdims:    The label of the x- and y-dimension of the Labels element in form
          of a string or dimension object.
```

It looks like this happens when the docstring includes different spacing on the first line than on subsequent lines, as for `datatype` and `extents` below.  It would presumably be a lot of work to go through all Parameterized objects and make sure they have the same spacing on every line, so instead could we put some sort of preprocessing code into hv.help to normalize the whitespace before calling pydoc.help()?          

```
class Labels(Dataset, Element2D):
    kdims = param.List(default=[Dimension('x'), Dimension('y')],
                       bounds=(2, 2), constant=True, doc="""
        The label of the x- and y-dimension of the Labels element in form
        of a string or dimension object.""")
```

    cdims = param.Dict(default=OrderedDict(), doc="""
       The constant dimensions defined as a dictionary of Dimension:value
       pairs providing additional dimension information about the object.

       Aliased with constant_dimensions.""")

```
class Dataset(Element):
    datatype = param.List(datatypes,
        doc=""" A priority list of the data types to be used for storage
        on the .data attribute. If the input supplied to the element
        constructor cannot be put into the requested format, the next
        format listed will be used until a suitable format is found (or
        the data fails to be understood).""")
```

```
class Element2D(Element):

    extents = param.Tuple(default=(None, None, None, None),
                          doc="""Allows overriding the extents
              of the Element in 2D space defined as four-tuple
              defining the (left, bottom, right and top) edges.""")
```

**Comment by jlstevens** [comment]
>  It would presumably be a lot of work to go through all Parameterized objects and make sure they have the same spacing on every line, so instead could we put some sort of preprocessing code into hv.help to normalize the whitespace before calling pydoc.help()?

I think fixing the docstrings is the correct thing to do and the latter is both tricky to get right and also implemented in param iirc. This is more of a param issue than a holoviews issue.

**Comment by jbednar** [comment]
If you are voting to fix the docstrings, then how is it a param issue?  The docstrings are in holoviews.

**Comment by jlstevens** [comment]
> ...  then how is it a param issue

The suggestion to add some preprocessing to fix the whitespace would be a param issue. Otherwise, I agree that the docstrings need updating in holoviews.
