### ISSUE TITLE
Log scale for Images

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#272]
The logx, logy and logz options are not working very good on Images. 

# logz
The easiest to fix might be logx, for the this np.log10 has to be applied on the data, before plotting with imshow

This is wrong:
```
%%opts Image [logz=True, colorbar=True] 
dat = np.exp(np.arange(1,10))[:,np.newaxis]
h = hv.Image(dat)
````
![screenshot](https://cloud.githubusercontent.com/assets/3776190/9937935/364d221c-5d63-11e5-944c-5ea615c507f5.png)

# logx, logy
The axis in the x and y direction are scaled the right way, but the data is not scaled. Might be more problematic, as it is not directely clear how to interpolate this data.

**Comment by philippjfr** [comment]
These plot options are meant for the axes, not the values themselves so this isn't really unexpected. To get log scaling for the Image values you'll need to use a logarithmic color map. There should probably be an easier way to do this but it is unrelated to the log{x|y|z} options.

**Comment by vascotenner** [comment]
For Curveplots, also the data is displayed on different locations, not only the labels along the axes. I would expect that logz=True would apply a logarithmic colormap.

**Comment by philippjfr** [comment]
I agree it's confusing, logz was only meant to exist on 3D Elements, I see your point and if @jlstevens agrees I'll let enable logarithmic colormaps on Image types via the ``logz`` plot option.

**Comment by jlstevens** [comment]
Seems sensible enough to me! The colormap is basically the way you read off values in a raster type so effectively it has the same semantics as using logarithmic scaling on the z axis .

**Comment by philippjfr** [comment]
Implemented as part of the commit referenced above. Closing.

**Comment by philippjfr** [comment]
Note that logx and logy will never work for Image types, matplotlib won't allow it. What you can do instead is use a QuadMesh Element that is actually sampled logarithmically (like in [this example](http://holoviews.org/dev/Tutorials/Elements#QuadMesh)).

**Comment by jbednar** [comment]
The logz option appears only to work for the Matplotlib backend:

![image](https://cloud.githubusercontent.com/assets/1695496/15579832/f4d5edde-232b-11e6-90f6-577bf3897002.png)

![image](https://cloud.githubusercontent.com/assets/1695496/15579804/d5426a60-232b-11e6-9406-1ddee39d564a.png)

An error message would be helpful, as I didn't immediately realize it was a Bokeh-specific issue.  Any idea how hard this is to implement for Bokeh?

**Comment by philippjfr** [comment]
Would be easy enough I assume but I wonder if their color mappers should just support it directly.

**Comment by philippjfr** [comment]
Bokeh currently has a ``LinearColorMapper``, so I assume they were planning on implementing a non-linear version eventually.

**Comment by jbednar** [comment]
Ok, I'll follow up with the Bokeh team.

**Comment by philippjfr** [comment]
Log color mapping is now supported in matplotlib and bokeh. Closing.
