### ISSUE TITLE
cannot import holoviews because of dask/pandas

### ISSUE THREAD

**Issue by suvarchal** [ioam/holoviews#2729]
i messed up my conda environment; so had to reset it up, while importing holoviews I encountered 'pandas' has no attribute 'rolling _count'. Something obvious to you guys? 

> Traceback (most recent call last):
>   File "/home/user/miniconda3/bin/holoviews", line 11, in <module>
>     load_entry_point('holoviews==1.9.5', 'console_scripts', 'holoviews')()
>   File "/home/user/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "/home/user/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
>     return ep.load()
>   File "/home/user/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load
>     return self.resolve()
>   File "/home/user/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve
>     module = __import__(self.module_name, fromlist=['__name__'], level=0)
>   File "/home/user/miniconda3/lib/python3.6/site-packages/holoviews/__init__.py", line 11, in <module>
>     from .core import archive, config                        # noqa (API import)
>   File "/home/user/miniconda3/lib/python3.6/site-packages/holoviews/core/__init__.py", line 3, in <module>
>     from .boundingregion import *  # noqa (API import)
>   File "/home/user/miniconda3/lib/python3.6/site-packages/holoviews/core/boundingregion.py", line 12, in <module>
>     from .util import datetime_types
>   File "/home/user/miniconda3/lib/python3.6/site-packages/holoviews/core/util.py", line 46, in <module>
>     import dask.dataframe as dd
>   File "/home/user/miniconda3/lib/python3.6/site-packages/dask/dataframe/__init__.py", line 12, in <module>
>     from .rolling import (rolling_count, rolling_sum, rolling_mean, rolling_median,
>   File "/home/user/miniconda3/lib/python3.6/site-packages/dask/dataframe/rolling.py", line 200, in <module>
>     rolling_count = wrap_rolling(pd.rolling_count, 'count')
> AttributeError: module 'pandas' has no attribute 'rolling_count'

**Comment by suvarchal** [comment]
it happened with dask version dask-0.15.4 upgrading to dask-0.17.5 solved the issue.  May be set holoviews require to  to dask >0.15.4?

**Comment by suvarchal** [comment]
and bokeh> 0.12.14 otherwise holoviews could not load bokeh extension.

both these issues with dask and bokeh are reproducible by switching versions.

**Comment by philippjfr** [comment]
We need to enable optional dependencies to be able to pin dask and pandas, and should definitely do so for the next release.

>and bokeh> 0.12.14 otherwise holoviews could not load bokeh extension.

As far as I can tell https://github.com/ioam/holoviews/blob/master/conda.recipe/meta.yaml#L27 does pin bokeh > 0.12.14, so I don't know why it didn't force an update for you.

**Comment by philippjfr** [comment]
This is now covered by #2731, so I'll close.
