### ISSUE TITLE
Change deeper dimensions (ddims) in an Image

### ISSUE THREAD

**Issue by damlatien** [ioam/holoviews#273]
Hi all, 
is it possible to change deeper dimensions ('x' and 'y') in an Image instance ? I would like e.g. to change the default "-0.5 to 0.5", and the names, but I can't figure how from the tutorial and examples. I tried to change it using opts : 

    %%opts Image.A [aspect=4, fig_size=100, ddims=[Dimension('x', range=(0,1), type=float), Dimension('y', range=(0,1), type=float), Dimension('z', range=(0,1), type=float)]]

but I get a ValueError : 'ddims' is not a parameter of RasterPlot279474 ; however it seems to me that it is present in class holoviews.element.raster.Image not as a parameter, though...

Could someone help me?

Thanks!

**Comment by philippjfr** [comment]
I think there is some misunderstanding here. There's two fundamental ways to declare something about your plot, first of all you declare the actual data and metadata on the object itself. In the case of an Image you pass it the 2D array and the bounds and optionally specify the key dimensions (kdims) and value dimensions (vdims), which determine the axis labels and ranges. Then there is the options system, which allows you to declare stylistic choices about your plots, this includes things like aspects, figure sizes, colormaps etc. that is done via the options magic as you have shown above.

The deep dimensions (ddims) are only present HoloViews container types like ``HoloMaps``, ``Overlays``, ``GridSpaces`` and so on and are not settable. They simply return the dimensions of any objects contained within them.

To declare the dimensions and range of an Image  you do the following:

```python
hv.Image(np.random.rand(10,10), bounds=(-0.5, -0.5, 0.5, 0.5), kdims=[hv.Dimension('x'), 'y'])
```

The bounds is specified as a tuple of the ``(left, bottom, right, top)`` edges of the Image and ``kdims`` (and ``vdims``) should be specified as lists of Dimension objects or strings.

**Comment by philippjfr** [comment]
If you have any more questions join us on [Gitter](https://gitter.im/ioam/holoviews). I'll close the issue now since it's not a problem in HoloViews.

**Comment by damlatien** [comment]
Ok thanks a lot for your help ! Indeed, no need to change ddims, changing bounds and kdims is enough.
