### ISSUE TITLE
Add option to set active tools 

### ISSUE THREAD

**Issue by kcpevey** [ioam/holoviews#2730]
I'd like the ability to set active tools as a plot option in holoviews. The current process of creating hook seems clunky for something that I'm sure many users would like to do.   
  
The hook snippet:
```
def set_active_tool(plot, element):  
    plot.state.toolbar.active_scroll = plot.state.tools[2]  
  
hv.Curve([1, 2, 3]).options(finalize_hooks=[set_active_tool])  
```
  
Discussed originally here https://stackoverflow.com/questions/50415434/how-to-set-active-tools-in-holoviews/50416512#50416512

**Comment by kcpevey** [comment]
syntax:
`hv_element.opts(active_tools=['pan','wheel_zoom'])`

**Comment by pjvalla** [comment]
This doesn't appear to work with DynamicMaps.  Can you set the options below for overlayed DynamicMaps?

active_drag
active_scroll
active_tap
active_inspect

**Comment by kwunlyou** [comment]
please can you reopen this issue as it is not solved?

**Comment by philippjfr** [comment]
@kwunlyou Can you provide an example of something that isn't working? I just tried different combinations of Elements, Overlays and DynamicMaps without issue.

@kwunlyou The API in HoloViews is different, you simply provide the list of active tools instead of defining active_drag, active_scroll etc. tools separately.

I'll happily reopen if you provide an example that isn't working.

**Comment by kwunlyou** [comment]
@philippjfr thanks for the quick response. I prepared an example based on [this official one](http://holoviews.org/gallery/demos/bokeh/network_graph.html)

```python
import pandas as pd
import holoviews as hv
hv.extension('bokeh')

edges_df = pd.read_csv('./fb_edges.csv')
nodes_df = pd.read_csv('./fb_nodes.csv')

fb_nodes = hv.Nodes(nodes_df).sort()
fb_graph = hv.Graph((edges_df, fb_nodes), label='Facebook Circles')

colors = ['#000000']+hv.Cycle('Category20').values
fb_graph = fb_graph.redim.range(x=(-0.05, 1.05), 
                                y=(-0.05, 1.05)
                               )
fb_graph.opts(color_index='circle', width=800, height=800, show_frame=False,
                 xaxis=None, yaxis=None,node_size=10, edge_line_width=1, cmap=colors, active_tools=['pan'])
```
and here is the result

![image](https://user-images.githubusercontent.com/1352316/66999026-30406800-f0cd-11e9-8af8-bac90a0cf78b.png)

btw I am using 
```
holoviews==1.12.6
bokeh==1.3.4

```

**Comment by philippjfr** [comment]
@kwunlyou To be clear, you are expecting the tap and hover tools to be disabled? Currently the active_tools only deals with activating tools, it does not deactivate other tools.

**Comment by kwunlyou** [comment]
@philippjfr yes, I just want to activate `pan` as I noticed it is a bit slow to scroll my notebook if `hover` is active

**Comment by kwunlyou** [comment]
> Currently the active_tools only deals with activating tools, it does not deactivate other tools.
so I have to change something in `bokeh`?

**Comment by philippjfr** [comment]
>@philippjfr so I have to change something in bokeh?

I'd have to investigate how bokeh handles this and then come back with a proposal, for now you could try something like:

```python
def set_inactive_tool(plot, element):  
    plot.state.toolbar.active_inspect = None 
  
hv.Curve([1, 2, 3]).options(tools=['hover'], hooks=[set_inactive_tool])  
```

**Comment by kwunlyou** [comment]
thank you @philippjfr
