### ISSUE TITLE
No angle option for Text/Labels (bokeh backend)

### ISSUE THREAD

**Issue by kenyoneda** [ioam/holoviews#2737]
Was this intentional? Looking at the bokeh docs, the only concern I can see is this:

> Warning:

>The center of rotation for canvas and css render_modes is different. For render_mode=”canvas” the label is rotated from the top-left corner of the annotation, while for render_mode=”css” the annotation is rotated around it’s center.

Adding the ```angle``` keyword to ```text_properties``` in ```plotting/bokeh/element.py``` seems to do the trick but not sure about how to test and all. For example:

    hv.Text(0, 0, 'some_text').options(angle=45)

Using holoviews version: 1.10.4

**Comment by philippjfr** [comment]
This was simply an oversight, the ``Text`` element does have a rotation parameter, but I'm strongly in favor of eventually making that a style option. For now let's just add the angle parameter to the Labels element.

**Comment by kenyoneda** [comment]
Great, thank you. I assume you would also want ```angle_units``` to be included? I just realized the default unit is radians.

**Comment by philippjfr** [comment]
Since that's a style option I'd be okay with including it, however I would set the default to use degrees rather than radians.
