### ISSUE TITLE
Dynamically populated selects in DynamicMaps for hierarchical data

### ISSUE THREAD

**Issue by brianmingus** [ioam/holoviews#2749]
Supposing I have three levels of selects, the values of the second select would be populated when I specify the first, and the value of the third when I specify the second. I don't see an example of this in the doc - is it feasible?

Related to this? https://github.com/ioam/holoviews/issues/1056

**Comment by brianmingus** [comment]
@philippjfr Thank you.

fyi the workflow I have come up with is to use load with Dask, map/filter/reduce, call compute(), create a MultiIndex, persist to HDF and then load directly into Pandas in the future. This seems like a good path, so native support for dynamic choosers based on MultiIndexed DataFrames would be great to include.

I believe Dask will support MultiIndexes in the future. 

Some potential issues with remaining in sync, and cost of obtaining the indexes.

**Comment by philippjfr** [comment]
I'm going to close this as it is out-of-scope for HoloViews. It will be possible to express dependencies between parameters using param and parambokeh once https://github.com/ioam/param/issues/160 is implemented. If we revisit this discussion can carry on in https://github.com/ioam/holoviews/issues/301
