### ISSUE TITLE
DynamicMap returning hv.Curve and gv.Points under control of the same choosers

### ISSUE THREAD

**Issue by brianmingus** [ioam/holoviews#2751]
I could not come up with a way to have a DynamicMap return a HoloViews and GeoViews element under control of the same choosers. Is there any way to achieve this?

**Comment by brianmingus** [comment]
Is there perhaps an approach to achieving this with i.e. hmap + dmap? Any guidance appreciated.

**Comment by philippjfr** [comment]
You'll have to provide a bit more detail for me to know exactly what you're trying to accomplish and what's not working. Specifically a reproducible bit of code would be appreciated. There are no restrictions on combining HoloViews and GeoViews elements in a DynamicMap. The only guidance I can currently give that in general it is preferable to have a DynamicMap return one particular object.

**Comment by brianmingus** [comment]
@philippjfr Another issue I have had is setting the zoom based on the lon, lat extents of the data for a route. I've tried passing this in to datashader and by using extents, but it doesn't seem to work in a DynamicMap setting. Tried setting framewise to no effect.

**Comment by brianmingus** [comment]
I got this working. I updated the code above. kdims need to match.

I am still looking to:

- zoom in to the extent of the plot on the geo map when a new selection is toggled
- color gps by outlier

**Comment by philippjfr** [comment]
Good to hear you made some progress. I probably won't have time to take a look at this until tomorrow.

**Comment by philippjfr** [comment]
>zoom in to the extent of the plot on the geo map when a new selection is toggled

The problem here is that you unpacked the gf.land shape geometries so they all get included in the extent calculation, any reason you're not simply using ``gf.land`` directly? Alternatively you can set ``framewise=True`` on both the Shapeand the points.

>plot curve value outliers at appropriate gps location on map

I can't quite tell what issue you are running into here.

I'm happy to continue this discussion here, but since this is a usage question I'm going to close the issue.
