### ISSUE TITLE
Inconsistent style options

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#277]
Holoviews try to seperate the style and the way of plotting, with the () and [] syntax. 
For my feeling:
* (): the style of things
* []: the elements that should be shown (like colorbar, xaxis and log*) 

However, some elements are in [], while they feel like they should be in ().

For example:
* color_index
* fig_alpha
* bgcolor

A closer look reveals way more inconsistent items. Is there any logic that I miss? Can the be re-distributed in a more logic way?

**Comment by jlstevens** [comment]
Thanks for the feedback!

Your intuition is mostly correct and a pretty good rule-of-thumb. However, we aren't really the ones who decide the split between style options (i.e using ``( )``) or plot options (i.e using ``[ ]``) as I'll now explain...

Style options are keyword options that get passed to calls to the plotting library. For instance, the ``cmap`` option is a keyword argument you can pass to matplotlib, namely in a call to something like ``plt.image``. The style keywords are therefore defined by the underlying plotting library (i.e matplotlib or bokeh) and you can expect the applicable style keywords to depend on the backend you are using.

The plot options are things we *do* control and include everything other than the style options and are to do with how HoloViews coordinates the calls to put a plot together (hence matching your intuition that it is about the elements shown). These we do choose ourselves and we try to keep these consistent across plotting backends.

To summarize, the style options expose the API of the underlying plotting library whereas plot options are part of the HoloViews API. I do understand the issue you've raised (and I also find it a bit annoying!) but I'm not sure what the best thing to do. For instance, we could define a 'pseudo style' called ``fig_alpha`` that *we* define and that should be respected across backends but this would not be such a clean separation at the implementation level.

The only alternative I can imagine is to make things like ``fig_alpha`` and ``bgcolor`` apply to the display of an entire cell, i.e something that could be set via the ``%output`` or ``%%output`` magic. This would make some sense to me given that (if I remember correctly!) the ``fig_`` options always have to apply to the top-level object. Something like ``color_index`` would stay a plot option. 

Is this right, Philipp?

**Comment by philippjfr** [comment]
The explanation above is good, however I wouldn't be in favor of changing the ``fig_`` options around. The confusion here is largely down to naming, really what we mean when we say style options is the options supplied directly to the plotting call, which are usually related to styles. Maybe we can come up with a better name for style options?

**Comment by jlstevens** [comment]
> Maybe we can come up with a better name for style options?

Sure. Maybe we can file that as a separate issue?

Otherwise, I think we've clarified why we have had to split up the options as we have. It seems like I can  close the issue now and if there is more discussion, I am happy to reopen it again.
