### ISSUE TITLE
strange shapes in area chart

### ISSUE THREAD

**Issue by lucaNicoli88** [ioam/holoviews#2772]
Hi,

I am using holoviews for make stacked area.
When I make my chart, I find strange shapes in trend.

![image](https://user-images.githubusercontent.com/36009099/40976778-719a9c76-68cf-11e8-9420-cc7394c69687.png)

If I make the same chart in excel without magenta area, I can not find any strange issue.

![image](https://user-images.githubusercontent.com/36009099/40976822-8da66314-68cf-11e8-9987-f8e50be805fb.png)

My code for generate area chart is the following:

```
    def curves_chart_stacked_EE(data):
        delta_tot = (data['delta_load'].sum() / data['active'].sum()) * 100
        dims = dict(kdims='Hour (h)', vdims='Energy (kWh)')
        area_1 = hv.Area((data['timestamp'], data['minimum_load']), label='minimum_load', **dims)
        area_2 = hv.Area((data['timestamp'], data['base_load']), label='base_load', **dims)
        area_3 = hv.Area((data['timestamp'], data['process_load']), label='process_load', **dims)
        area_4 = hv.Area((data['timestamp'], data['season_load']), label='season_load', **dims)

        style = dict(fill_alpha=0.9)
        overlay = (area_1 * area_2 * area_3 * area_4).opts(style={'Area': style})
        chart = (hv.Area.stack(overlay) * hv.Curve((data['timestamp'], data['delta_load']), 
                     label='delta_load')).relabel("Stacked Disaggregation")
        print('Total delta load is {}%'.format(np.round(abs(delta_tot), 2)))
        return chart
```
Have you got some suggestion for this issue?

Bes regards.

**Comment by philippjfr** [comment]
@jbednar You think this might be related to https://github.com/bokeh/bokeh/pull/7956?

**Comment by lucaNicoli88** [comment]
I make another example:

![image](https://user-images.githubusercontent.com/36009099/40980436-a546f1b0-68d8-11e8-8113-238316765302.png)

I can share you data for that week.

[test.txt](https://github.com/ioam/holoviews/files/2072617/test.txt)

**Comment by jbednar** [comment]
@philippjfr, the way to tell if it's related to the above issue is to change the `line_join` to `bevel` instead of `miter`, but from the second example it's hard to say what's going on.

**Comment by lucaNicoli88** [comment]
Hi all,

I have found my problem. There is a problem with timestamp. There are duplicates hours with wrong timestamp.

Sorry for the trouble.

**Comment by philippjfr** [comment]
Glad you figured it out! Feel free to reopen if you find there is an actual issue.
