### ISSUE TITLE
Hover tool over Image does not show values

### ISSUE THREAD

**Issue by trongnguyen29** [ioam/holoviews#2788]
When using Hover tool over Image, the values of the image intensity does not show up. 

`img = hv.Image(Intensity).options(tools = ['hover'], colorbar = True)`

**Comment by philippjfr** [comment]
Could you try updating to holoviews 1.10.5?

**Comment by trongnguyen29** [comment]
I got this error: "AttributeError: type object 'Version' has no attribute 'setup_version" when I try to do: pip install git+https://github.com/ioam/holoviews.git.

**Comment by philippjfr** [comment]
Try updating ``param`` first with ``pip install param``.

**Comment by jbednar** [comment]
Just curious -- is "pip install git+https" a common way you install packages, compared to just "pip install holoviews"?  Seems like that's a good way to get not-quite-ready stuff...

**Comment by trongnguyen29** [comment]
After updating param, I can install holoviews 1.10.5, still no output image in the notebook. 
I normally just use conda or pip install holoviews. In this case, I wanted to try the not-quite-ready stuff. I am not sure if they are different.

**Comment by philippjfr** [comment]
>still no output image in the notebook.

That's extremely odd, is ``Intensity`` just a simple numpy array?

**Comment by philippjfr** [comment]
I'm afraid I'll need more detail, usually a fully reproducible example is preferred. Are you using the classic notebook or JupyterLab? Have you loaded the holoviews extension?

**Comment by trongnguyen29** [comment]
I used the notebook, not JupyterLab. If I use the holoviews 1.10.5, it only prints out the repr info. I am using 1.9.5 now, everything displays. I will keep using 1.9.5 for now to be little for proficient in holoviews. I guess I'll wait for the stable version.

**Comment by philippjfr** [comment]
>I guess I'll wait for the stable version.

1.10.5 should be a lot more stable than 1.9.5. It really would be good to work out what's going on here. Could you simply paste the full code you're trying?

**Comment by trongnguyen29** [comment]
```

import numpy as np
import holoviews as hv
hv.extension('bokeh', 'matplotlib')

Bmode = np.random.randint(1, 200, (100,100))

img = hv.Image(np.flipud(Bmode), kdims = ['Lateral distance (mm)','Axial distance (mm)']).options(tools = ['hover'], colorbar = True, invert_yaxis = True)

%%output size=200 
img
```

**Comment by trongnguyen29** [comment]
and the output of the cell is only this:
`:Image   [Lateral distance (mm),Axial distance (mm)]   (z)`

**Comment by trongnguyen29** [comment]
I figure out the problem: I needed to update ipython. I was using 5.x , I updated to 6.4. The image shows in the output cell, but the hover tool doesn't work.

**Comment by philippjfr** [comment]
@trongnguyen29 That's due to a bug in bokeh which causes the hover tool to break on a flipped yaxis (see https://github.com/bokeh/bokeh/issues/7959). Hopefully that can be fixed soon.

**Comment by philippjfr** [comment]
This has been fixed a while ago.
