### ISSUE TITLE
x,y rotation ignored

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#279]
I tried to rotate the label of one of my axes, using xrotation and yrotation.

This works for a Curve object as expected. However, it does not work for Bars or Errorbars:
# Bars
Only yrotation works
'''
%%opts Bars [yrotation=15, xrotation=45]
hv.Bars([[chr(n),n] for n in range(65,70)])
'''
![screenshot-3](https://cloud.githubusercontent.com/assets/3776190/10309752/961300ec-6c3e-11e5-9916-85e03394fd28.png)

# Errorbars
No rotation works
'''
%%opts ErrorBars [yrotation=15, xrotation=45]
hv.ErrorBars((0,1,.5,3))*hv.Scatter((0,1))*hv.ErrorBars((1,1,.5))
'''
![screenshot-2](https://cloud.githubusercontent.com/assets/3776190/10309688/31b7756a-6c3e-11e5-993f-62b7248f7c76.png)

**Comment by philippjfr** [comment]
The Bars rotation seems to be a real thing but remember that if you overlay multiple Elements you will have to set any generic plot options on the Overlay not the Element. 

```python
%%opts Overlay [yrotation=15, xrotation=45]
hv.ErrorBars((0,1,.5,3)) * hv.Scatter((0,1)) * hv.ErrorBars((1,1,.5))
```

**Comment by philippjfr** [comment]
I've now fixed the rotation on Bars. Closing.
