### ISSUE TITLE
NYC radial heatmap example not working

### ISSUE THREAD

**Issue by jzicker** [ioam/holoviews#2798]
Does the NYC taxi radial heatmap still work.  I got this error when I tried to run it.
Unexpected plot option 'start_angle' for HeatMap in loaded backend 'bokeh'.

Possible keywords in the currently active 'bokeh' renderer are: ['apply_extents', 'apply_ranges', 'bgcolor', 'border', 'clipping_colors', 'colorbar', 'colorbar_opts', 'colorbar_position', 'default_tools', 'finalize_hooks', 'fontsize', 'height', 'invert_axes', 'invert_xaxis', 'invert_yaxis', 'labelled', 'lod', 'logx', 'logy', 'logz', 'normalize', 'projection', 'shared_axes', 'shared_datasource', 'show_frame', 'show_grid', 'show_legend', 'show_title', 'sizing_mode', 'title_format', 'toolbar', 'tools', 'width', 'xaxis', 'xrotation', 'xticks', 'yaxis', 'yrotation', 'yticks']

If you believe this keyword is correct, please make sure the backend has been imported or loaded with the hv.extension.

**Comment by philippjfr** [comment]
What version of holoviews do you have?

**Comment by jbednar** [comment]
Sounds like you have an out of date HoloViews version, to me.  Radial HeatMaps were introduced in holoviews 1.10.2, and the current version is 1.10.5.

**Comment by jzicker** [comment]
yes, that was the problem.  I had version 1.9.3.  thank you

**Comment by jzicker** [comment]
now when I try to install newer version I get this
ollecting holoviews
  Downloading https://files.pythonhosted.org/packages/3b/09/a52d35bd4f59c5d62bf7baf04b2980d697fe4ceecda193c0ce8a4a3f957f/holoviews-1.10.5.tar.gz (7.3MB)
    100% |################################| 7.4MB 209kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-itpb53a4/holoviews/setup.py", line 75, in <module>
        version=get_setup_version("holoviews"),
      File "/tmp/pip-build-itpb53a4/holoviews/setup.py", line 68, in get_setup_version
        return version.Version.setup_version(basepath, reponame, archive_commit="$Format:%h$")
    AttributeError: type object 'Version' has no attribute 'setup_version'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-itpb53a4/holoviews/
sh-4.4$ pip3 install holoview

**Comment by jzicker** [comment]
param installed fine but holoviews install has the same error

**Comment by philippjfr** [comment]
You need param 1.6.1 at minimum otherwise you'll get that error. If you're still getting the error with 1.6.1 something is off.

**Comment by jzicker** [comment]
I am using param 1.6.1.  So it must be something else.

**Comment by jlstevens** [comment]
I've just uploaded a wheel for 1.10.5 so please try again - the wheel should avoid any param issues at installation time.

**Comment by jzicker** [comment]
ok... tried again...here is what I got.
Collecting holoviews
  Using cached https://files.pythonhosted.org/packages/f5/43/df660ae7f5e81a93f8d720e1d9d6da73fcd5713fb06e03f47479ea188224/holoviews-1.10.5-py2.py3-none-any.whl
Collecting numpy>=1.0 (from holoviews)
  Using cached https://files.pythonhosted.org/packages/f5/9f/c538ce62503e2b3f9d7a87e9064d580242f1d1600c002b4cab36cc357a69/numpy-1.14.4-cp35-cp35m-manylinux1_x86_64.whl
Collecting pyviz-comms (from holoviews)
  Using cached https://files.pythonhosted.org/packages/b9/95/c7408db349fa26773a3a789a2fc406bdb05a9b9164fcfdedd33b59299da3/pyviz_comms-0.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-do0r0taj/pyviz-comms/setup.py", line 33, in <module>
        version=get_setup_version("pyviz_comms"),
      File "/tmp/pip-build-do0r0taj/pyviz-comms/setup.py", line 23, in get_setup_version
        return version.Version.setup_version(basepath, reponame, archive_commit="$Format:%h$")
    AttributeError: type object 'Version' has no attribute 'setup_version'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-do0r0taj/pyviz-comms/
sh-4.4$

**Comment by philippjfr** [comment]
Seems like ``pyviz_comms`` needs a wheel too. That said it must be picking up param from somewhere else because 1.6.1 definitely has ``Version.setup_version``

**Comment by jzicker** [comment]
yeah... looks like it is pickup up param 1.5.1.  I tried upgrading it via pip3 and it says that it works and I am version 1.6.1.  However when I run my notebook it appears to be picking up a prior version 1.5.1

**Comment by jbednar** [comment]
I'd just remove all copies of param and try again.  Well, really I'd make a new clean conda environment and install in that, to avoid all problems like this, but *if* I were using pip that's what I'd do. :-)

**Comment by jlstevens** [comment]
> Seems like pyviz_comms needs a wheel too. 

The wheel is now uploaded so this shouldn't be an issue anymore.
