### ISSUE TITLE
Bug: Translation between coordinates

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#28]
Code:
XX,YY = np.mgrid[0:60,0:80]
hv.Image(XX+YY).sample(y=-0.4)

Error:
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-81-66157c3c3139> in <module>()
      1 XX,YY = np.mgrid[0:60,0:80]
----> 2 hv.Image(XX+YY).sample(y=-0.4)

/usr/local/lib/python2.7/dist-packages/holoviews/element/raster.pyc in sample(self, samples, **sample_values)
    111             # Sample data
    112             x_vals = sorted(set(self.dimension_values(dimension)))
--> 113             data = list(zip(x_vals, self.data[sample]))
    114             params['key_dimensions'] = other_dimension
    115             return Curve(data, **params)

IndexError: index 72 is out of bounds for axis 0 with size 60

**Comment by philippjfr** [comment]
Thanks for reporting this, seems as if the indices are getting reversed. I'll push a fix in the next few minutes.

**Comment by jbednar** [comment]
That was definitely something I was worried about, because our tested notebooks nearly all use square plots by default.  Not sure how to test this better in general, without supplying non-square dimensions explicitly to every example...

**Comment by philippjfr** [comment]
It's taking a bit longer as Raster and Image obviously have different coordinate spaces. I'll think about it a bit more tonight and hopefully come up with a clean fix by tomorrow.

**Comment by philippjfr** [comment]
Just pushed a fix for this, sampling of non-square Raster and Image Elements is now handled correctly. In fact the problem went a lot deeper than it appeared. Indexing of our Elements always happens by the order of dimensions so when indexing into a Raster type, the first index will map onto the x-axis. This was previously inverted. Additionally the xdensity and ydensity on Images was also inverted resulting in the index errors you see above. This should all be fixed now, the Continuous_Coordinates tutorial is updated and I added a few unit tests.

**Comment by philippjfr** [comment]
Once the associated Travis tests for these commits pass I will close this issue.
