### ISSUE TITLE
Feature request: scaling_offset

### ISSUE THREAD

**Issue by ahuang11** [ioam/holoviews#2810]
There's an option for scaling_factor which increases the size of dots through multiplication (I think?), but if the value is 0 (or np.nan), it will not be visible on the map.

For instance, here is a map of stations with size_index set to the precipitation column.
![image](https://user-images.githubusercontent.com/15331990/41578324-87064db8-7346-11e8-8be5-89a9ff183937.png)

**Comment by jbednar** [comment]
Somewhere in Alaska gets a lot of rain!  I think this is addressed by https://github.com/ioam/holoviews/pull/2152 , which I hope can be resurrected and merged someday soon!

**Comment by philippjfr** [comment]
I've made a good bit of progress on https://github.com/ioam/holoviews/pull/2152 and it should be able to land in 1.11.

**Comment by philippjfr** [comment]
I'll close this since it's covered by the ``op`` proposal.
