### ISSUE TITLE
Datashader image resampling sometimes fails if not contained in viewport

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#2817]
There appear to be various issues when datashading image not contained in current view port. A good way to reproduce this is by drawing multiple non-overlapping images:

```python
import numpy as np
import holoviews as hv
hv.extension('bokeh')

from holoviews.operation.datashader import regrid

ls = np.linspace(0, 10, 200)
xx, yy = np.meshgrid(ls, ls)
bounds_list=[(-1,-1,1,1),(0,0,2,2),(0.5,0.5,3,3)]
imgs = [regrid(hv.Image(np.sin(xx)*np.cos(yy), bounds=bounds)) for i,bounds in enumerate(bounds_list)]

hv.Overlay(imgs)
```

This raises errors originating both in datashader and holoviews.

**Comment by stevievb** [comment]
If I change the first example a bit I am seeing a similar error. @philippjfr I assume this is related?

`
import numpy as np
import holoviews as hv
hv.extension('bokeh')

from holoviews.operation.datashader import regrid, datashade

ls = np.linspace(0, 10, 200)
xx, yy = np.meshgrid(ls, ls)
bounds_list=[(-1,-1,1,1),(0,0,2,2),(0.5,0.5,3,3)]
imgs = [hv.Image(np.sin(xx)*np.cos(yy), bounds=bounds) for i,bounds in enumerate(bounds_list)]

datashade(hv.Overlay(imgs))
`

**Comment by philippjfr** [comment]
Yes, I can reproduce it.

**Comment by philippjfr** [comment]
Something going wrong in the shade operation, seems like the densities aren't being passed through. Thought I'd fixed that but apparently not.

**Comment by philippjfr** [comment]
This has been fixed in the PR referenced above.
