### ISSUE TITLE
dateshader can't handle bokeh DatetimeTickFormatter for NdOverlay

### ISSUE THREAD

**Issue by ajansenTUB** [ioam/holoviews#2819]
I'm trying to write a dashboard with jupyter to visualize several time series from sensor measurements. I stumpled across the following issue: If I use a datashader on NdOverlay with bokeh's DatetimeTickFormatter, my x-labels become 'NaN'. It works fine for a single Curve and also with NdOverlay but without a datashader for smaller data. Below you find a example. Any suggestions?

## Imports and necessary functions:

```python
import numpy as np
import pandas as pd
import holoviews as hv
import datashader as ds
from holoviews.operation.datashader import datashade, shade, dynspread, rasterize
from datashader.colors import Sets1to3 # default datashade() and shade() color cycle
from holoviews.operation import decimate
from bokeh.models import DatetimeTickFormatter

hv.extension('bokeh')
decimate.max_samples=1000
dynspread.max_px=20
dynspread.threshold=0.5

def time_series(T = 1, N = 100, mu = 0.1, sigma = 0.1, S0 = 20):  
    """Parameterized noisy time series"""
    dt = float(T)/N
    t = np.linspace(0, T, N)
    W = np.random.standard_normal(size = N) 
    W = np.cumsum(W)*np.sqrt(dt) # standard brownian motion
    X = (mu-0.5*sigma**2)*t + sigma*W 
    S = S0*np.exp(X) # geometric brownian motion
    return S

def apply_formatter(plot, element):
    plot.handles['xaxis'].formatter = DatetimeTickFormatter()
```

## Minimal example causing 'NaN' as x-labels

```
`%%opts RGB [width=800 height=450 show_grid=True finalize_hooks=[apply_formatter]]{+framewise}

nChannels=range(3)
dictCurves=dict()

start='2017-09-21 12:02:34'
end='2017-09-21 13:02:33.980000'
dates = pd.date_range(start=start, end=end, freq='0.02S')

for nChannel in nChannels:
        
        y= time_series()
        
        curve=hv.Curve((dates,time_series(N=len(dates), sigma = 1)),'Time', 'Signal')
        dictCurves[nChannel]=curve
        
ndoverlay = hv.NdOverlay(dictCurves, kdims=['k'])
 
datashade(ndoverlay, aggregator=ds.count_cat('k'),min_alpha=255)`
```

![grafik](https://user-images.githubusercontent.com/32636988/41768712-4edf4114-760d-11e8-9c30-ee70b605c6ca.png)

## For single Curve

`%%opts RGB [width=800 height=450 show_grid=True finalize_hooks=[apply_formatter]]{+framewise}
datashade(curve,min_alpha=255)`

![grafik](https://user-images.githubusercontent.com/32636988/41768763-79af8b10-760d-11e8-9707-501cbfc709f6.png)

## Without datashader for less data

![grafik](https://user-images.githubusercontent.com/32636988/41768820-a31492d4-760d-11e8-9bc9-e708951740ac.png)

**Comment by jlstevens** [comment]
Certainly seems like a bug to me and I'll tag it as such. Do you agree @philippjfr ?

**Comment by philippjfr** [comment]
#2829 will fix this, there will also not be any need to apply a custom DatetimeTickFormatter anymore.
