### ISSUE TITLE
raster is not working as expected

### ISSUE THREAD

**Issue by thoth291** [ioam/holoviews#2821]
The last cell at this [notebook](https://anaconda.org/thoth/raster-plotly-issue/notebook) illustrates an issue.
Essentially the plot is flipped.
Bokeh version:

```python
%%opts Raster [colorbar=True height=dh width=dw toolbar='above']
hv.Raster(face)
```
![image](https://user-images.githubusercontent.com/2971670/41803927-3b1549fc-7654-11e8-81b9-39bda3343cca.png)

Plotly version:

```python
%%output backend='plotly'
%%opts Raster [colorbar=True height=dh width=dw]
hv.Raster(face)
```
![image](https://user-images.githubusercontent.com/2971670/41803944-69c972a0-7654-11e8-9fb6-53ddef956deb.png)

No matter what I do - it doesn't want to be fixed.
I'm really confused.
## Any suggestion for workaround would be much appreciated

**Comment by thoth291** [comment]
Note this workaround:

```python
hv.Raster(np.flipud(face).T,extents=(0,0,dw,dh))
```

**Comment by thoth291** [comment]
And the reason I moved my bakend to plotly for this case is due to **hover tool**.
**It doesn't work in bokeh** version of the Raster.

**Comment by philippjfr** [comment]
>It doesn't work in bokeh version of the Raster.

That is due to https://github.com/bokeh/bokeh/issues/7959, which will hopefully be fixed soon

>I wish I would know where to fix it - holoviews does not look like typical codes I'm dealing with...

Presumably you just need to conditionally transpose the array here if it's a Raster type: https://github.com/ioam/holoviews/blob/master/holoviews/plotting/plotly/raster.py#L29

**Comment by thoth291** [comment]
Thank you, @philippjfr! I did this:
```python
array = element.dimension_values(2, flat=False).T[::-1,...]
```
and it worked.
But
- why you said that I need to do it "conditionally"
- and what side effects this transpose will have on other elements?

**Comment by philippjfr** [comment]
I say conditionally because this should only apply to the Raster element specifically, so something like this should work:

```python
if type(element) is Raster:
    array = array.T[::-1]
```

**Comment by thoth291** [comment]
Splending!
Thanks!

**Comment by jlstevens** [comment]
Note that I've submitted PR https://github.com/bokeh/bokeh/pull/8031 to fix https://github.com/bokeh/bokeh/issues/7959 which corrects the hover behavior for inverted ranges.
