### ISSUE TITLE
NYC Radial Heatmap change color palette

### ISSUE THREAD

**Issue by jzicker** [ioam/holoviews#2822]
I would like to change the colormapping for the radial heatmap so that the lowest value in z is red and the highest value green.   Is this possible?  thanks

**Comment by philippjfr** [comment]
Please see [the User Guide](http://holoviews.org/user_guide/Styling_Plots.html) for details on how to apply styling, in this case it should be as simple as adding ``heatmap.options(cmap=your_custom_cmap)``. Where the custom cmap can be a matplotlib colormap or a list of colors. If you want to generate a colormap by interpolating between two colors the polylinear_gradient utility will help you, e.g.:

```python
cmap = hv.plotting.util.polylinear_gradient(['#FF0000', '#00FF00'], 20)
heatmap.options(cmap=cmap)
```
