### ISSUE TITLE
Radial Heatmap display colorbar

### ISSUE THREAD

**Issue by jzicker** [ioam/holoviews#2825]
Is there an example of displaying a colorbar legend for the radial heatmap? thanks

**Comment by philippjfr** [comment]
Just add ``heatmap.options(colorbar=True)``. You can look up all the valid plot and style options for a particular backend with ``hv.help(hv.HeatMap)``. For usage questions like this we would also prefer asking on StackOverflow or on our [gitter channel](https://gitter.im/ioam/holoviews).

**Comment by jzicker** [comment]
will do that in the future.   I tried colorbar=True on the nyc example using bokeh as a background and nothing appeared
