### ISSUE TITLE
Plot size in notebooks

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#283]
The default Jupyter/IPython notebook CSS settings leave only a small amount of space available for plots.  I think that HoloViews should override these settings to reduce the margins (especially on the left) so that plots can take up a much larger area of the page.  HoloViews is about plotting, yet the plots show up so tiny!  That way fewer users will have to resort to fiddling with the output size, figure size, etc.

**Comment by philippjfr** [comment]
The problem with this is that the CSS would have to be in the users profile to be applied on startup and it would be a bit strange/rude if the notebook suddenly became wider on executing ``%load_ext holoviews.ipython``. I assume the Jupyter/IPython team will have chosen the default width very deliberately, so I don't think they'll be persuaded to change the default. 

What I can imagine is offering a function to initialize the notebook extension and embed the required JS/CSS in the notebook, which unlike ``%load_ext`` will be able to accept arguments. This will let you modify the width easily and provide options to customize whether or not to display the HoloViews logo (addressing your objection in https://github.com/ioam/holoviews/issues/258), and which bits of CSS and JS to include.

**Comment by philippjfr** [comment]
The required CSS is just this btw:

```
<style>
.container { width:100% }
</style>
```

**Comment by jbednar** [comment]
Where would that CSS be put?

**Comment by philippjfr** [comment]
Currently when executing "%load_ext holoviews.ipython`` we already inject the required JavaScript and CSS for the widgets into the cell where it's executed. This means that when the cell is deleted things will break but also saves us from having to embed this code every time a widget is displayed. By offering a function to do this we can let the user set various options, e.g. whether to include the widget code for only a specific backend, various additional JavaScript includes **and** possibly some options to customize the notebook CSS directly.

**Comment by jlstevens** [comment]
While I agree that the notebook default styling is rather unhelpful, I'm not sure changing people's entire notebooks when loading HoloViews is going to be appreciated. This would be a rather global change to people's work environment which (although I agree it is beneficial!) is not explicitly asked for.

Of course, the ideal thing would be an argument to ``%load_ext`` but we know that isn't possible. :-(

**Comment by jlstevens** [comment]
> Of course, the ideal thing would be an argument to %load_ext but we know that isn't possible. :-(

Well, it would be possible to pass arguments if we implement the latest suggestion in issue #258. If we agree on that, doing this should be easy.

**Comment by philippjfr** [comment]
This has been implemented, the margins can now be reduced by changing the width: ``hv.notebook_extension(width=90)``. Closing.
