### ISSUE TITLE
Setting the names of x axis and y axis

### ISSUE THREAD

**Issue by pedroallenrevez** [ioam/holoviews#2833]
Right now in order to change the name of the axis you have lots of ways to do it:
- Sending in a tuple (col, col_name) to any hv.Callback
- redim.label
- finalize hooks
- and possibly many others that I'm not aware of

I think it would greatly simplify things for the user if one could pass `x_label` and `y_label` to the callback.

Thanks.

**Comment by philippjfr** [comment]
xlabel and ylabel are now supported as plot options.
