### ISSUE TITLE
column alignment when using .hist() on scatter objects in a layout

### ISSUE THREAD

**Issue by bt-** [ioam/holoviews#2841]
I am trying to create a layout of scatter plots.  The layout would be 3 columns wide by an unknown number of rows.  One of the three plots is a scatter plot with a histogram using the .hist() method.

It looks like the beginning of the column for each subsequent row is using the edge of the above histogram rather than the edge of the scatter as the starting edge of the column.  This is causing an offset in the columns, which grows with each row.

Is this a bug or is there a way to fix this?

Thanks!

![image](https://user-images.githubusercontent.com/4886238/41992901-6763012a-7a0f-11e8-83b3-bc16671ee3eb.png)

**Comment by philippjfr** [comment]
Could you check which version of HoloViews you have? This should have been fixed by https://github.com/ioam/holoviews/pull/2740, which was released as part of 1.10.5.

**Comment by bt-** [comment]
I was using 1.10.4.  I just updated to 1.10.5 and that did fix the issue.  Thanks!

**Comment by philippjfr** [comment]
Great, thanks for confirming.
