### ISSUE TITLE
color_index usage

### ISSUE THREAD

**Issue by mlzeimer** [ioam/holoviews#2851]
I'm struggling to find documentation for color_index. I've got a pandas data frame and I'm using a scatter plot to display multiple different "input variables" with the same x axis variable, each input variable being a column in the data frame. The last column is a flag variable, just True or False, and I want this to be the color index, differentiating points with a True value by color. But every attempt I've made at this has failed. 

Once the data frame is instantiated, I use the following:

```python
 %output size=75
%opts Scatter [tools=['box_select', 'lasso_select']] Layout [shared_axes=True shared_datasource=True]
%opts Scatter (selection_alpha=1, nonselection_alpha=.01, selection_color='blue')
%opts Scatter [color_index='flagged']
```

and then run an algorithm to flag points and add them together so they will display simultaneously and can be selected on at the same time. 

```python
display = (hv.Scatter(data_frame, 'create_time', input_variable))
```

This is how I'm formatting the display object, with additional Scatters being added:

```python
display += (hv.Scatter(data_frame, 'create_time', input_variable))
```

The goal is to have all of the scatter plots up at the same time and to then be able to select points on one graph and have them change color on all graphs for those x values.  I have managed to do this using an overlay, where the flagged points are their own Scatter plot, 

```python
display = (hv.Scatter(data_frame, 'create_time', input_variable).options(color='black') * hv.Scatter(data_frame_flagged, 'create_time', input_variable).options(color='red')).relabel(input_variable)
```

but with this, the flagged points do not get selected in other scatter plots when selected. They stay solid red while the other black points are colored or become transparent. Using the color_index option seems like the fix for this, but if there is another fix I have no problem using that. In general, I think that explaining how color_index works in this context could be very helpful, as it is difficult to find documentation and I believe this is a very common/useful use case that would honestly be very helpful to include in the Scatter examples page as well.

Thanks!

**Comment by ahuang11** [comment]
```
%opts Scatter [tools=['box_select', 'lasso_select']] Layout [shared_axes=True shared_datasource=True]
%opts Scatter (selection_alpha=1, nonselection_alpha=.01, selection_color='blue')

import numpy as np
import holoviews as hv
hv.extension('bokeh')

from bokeh.sampledata.iris import flowers
from holoviews.operation import gridmatrix

ds = hv.Dataset(flowers)

grouped_by_species = ds.groupby('species', container_type=hv.NdOverlay)
ds.to.scatter('sepal_length', 'sepal_width', []) + ds.to.scatter('sepal_length', 'petal_length', [])
```
Is this what you're looking for?
![image](https://user-images.githubusercontent.com/15331990/42249338-917e0156-7edf-11e8-821a-5ad4b0c6dfc1.png)

**Comment by mlzeimer** [comment]
Thank you for the response!
The selection tool highlighting data in all graphs is what I am looking for, yes, but the issue is that it doesn't work for overlays. The selection only occurs on one data set. This is an example of the issue. In the top plot, data points are selected, including red outlier points, and everything is colored, In the second plot, those outlier points do not highlight, and I assume that is because they are on top of the normal points, which would be highlighted? The bottom plot shows that normal points are highlighted by the selection.

![bokeh_plot 37](https://user-images.githubusercontent.com/40704489/42328711-a02c923e-8034-11e8-8f25-273116d7b637.png)
![bokeh_plot 39](https://user-images.githubusercontent.com/40704489/42328718-a3d9221c-8034-11e8-9f84-9476db1bd889.png)
![bokeh_plot 36](https://user-images.githubusercontent.com/40704489/42328690-913ff32e-8034-11e8-813e-6fbc7eedad4f.png)

The color_index option is something I am thinking will fix that, with the points just being different colors instead of being from overlapping scatter plots. I think that if I can get color_index to work, that will solve the problem.

display = (hv.Scatter(data_frame, 'create_time', [input_variable, 'flagged']).options(color_index=2))

I use the above line of code to create the scatter object, and there is no coloring difference for the points, other than some (but not all) of the outlier points being either white or invisible but still selectable. data_frame is a pandas data frame with many columns, create_time is the first column, input_variable is the dependent variable, a column somewhere in data_frame, and flagged is the last column, with a True/False flag based on whether or not points are outliers from the distribution. I have also tried making an unflagged point have a value of 0 and a flagged point have a value of 1, 5, or 100, with no change. I understand how to use color_index with a spectrum of colors and a continuous variable included in the plot. That example has been provided in the documentation. But I do not know how to use color_index to color points based on a discrete value associated with that point's row of the data frame it comes from, and in general using color_index to color points based on a variable I've provided that is not the x or y value for the plot. Since these points are coming from a data frame, it seems that coloring them based on a flag would be one of the most natural implementations of color_index, but I haven't been able to find any use case for this.

I appreciate any and all help.

Thanks!

**Comment by philippjfr** [comment]
Sorry no one ever replied here, you were definitely on the right track. The answer to your problem was something like:

```python
hv.Points((np.random.randn(100),np.random.randn(100), np.random.randint(0, 2, 100)), vdims='z').options(color_index='z', cmap={0: 'red', 1: 'blue'})
```
