### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by ahuang11** [ioam/holoviews#2854]
http://holoviews.org/reference/elements/bokeh/Labels.html

When you click matplotlib, it leads to http://holoviews.org/reference/elements/bokeh/'../matplotlib/Labels.html'

![image](https://user-images.githubusercontent.com/15331990/42248244-6f930da8-7ed9-11e8-8e17-abceba76f918.png)

Same for reverse
http://holoviews.org/reference/elements/matplotlib/Labels.html

Clicking bokeh results in 
http://holoviews.org/reference/elements/matplotlib/'../bokeh/Labels.html'

**Comment by jlstevens** [comment]
Thanks for reporting this!
