### ISSUE TITLE
For HLine/VLine time is in UTC

### ISSUE THREAD

**Issue by ivek1312** [ioam/holoviews#2857]
For HLine/VLine time is in UTC. Same date works fine with Points and Spikes.
![image](https://user-images.githubusercontent.com/31924016/42295881-51bd6f8c-7fef-11e8-935e-17dd871be8f8.png)

**Comment by jlstevens** [comment]
I suspect this may be an issue with how bokeh handles timezones but I haven't yet checked.

**Comment by philippjfr** [comment]
Fairly sure it's down to our handling of datetimes, but I'll have to investigate.

**Comment by ivek1312** [comment]
I had this issue before with Points, but it got fixed. As workaround I used:
os.environ['TZ'] = 'UTC'
time.tzset().

**Comment by philippjfr** [comment]
Should be fixed now.
