### ISSUE TITLE
Theme has no effect on title

### ISSUE THREAD

**Issue by ahuang11** [ioam/holoviews#2871]
```
import xarray as xr
import hvplot.xarray
air_ds = xr.tutorial.load_dataset('air_temperature')
air = air_ds.air
air.hvplot.violin('air', by='lat', grid=True, title='No work')
```

(also categorical labels are squished and whiskers are black)

![image](https://user-images.githubusercontent.com/15331990/42605916-63546508-852f-11e8-824a-08e880ad4f4a.png)

**Comment by jlstevens** [comment]
Thanks for filing this issue! I've noticed this before but I think forgot to make a corresponding issue.
