### ISSUE TITLE
Omit .I from repr()?

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#2874]
Right now, the printed representation for an Overlay or Layout shows the full `group.label` index for each object, where the group defaults to the Element type and the label defaults to Roman numerals starting at I and increasing for each subsequent Element of the same type:

```
:Overlay
   .Curve.I :Curve   [Year]   (measles)
   .VLine.I :VLine   [x,y]
   .Text.I  :Text   [x,y]
```

Proposal: Can we omit the ".I" from the repr when there is only one such Element?  When there is only one Curve, `obj.Curve` is sufficient as an index to specify it, so it seems like the `.I` doesn't particularly help the user in this case. And I personally find it very distracting to have to explain the `.I` on the very first time I show a repr of an Overlay, even for very simple cases like this one.

**Comment by philippjfr** [comment]
Omitting it from the repr but not from the actual data structure would be too confusing imo. Are you suggesting that we also drop it from the data structure and nest only one level deep in that case?

**Comment by jbednar** [comment]
No, I'm not suggesting that we drop it from the data structure; I'm just pointing out that there's no need to specify ".I" when accessing it, and it's confusing to access it that way when there is only one item.  I.e., "obj.Curve" appears to work precisely the same as "obj.Curve.I" when there is only one Curve, and so the extra ".I" is redundant when addressing it unless there are multiple objects. And it's very confusing to see that until there are multiple objects, at which point it becomes very clear, so I'm proposing that the representation only show the extra level when it actually is needed, and not before, to make it much easier to explain in small chunks.

**Comment by philippjfr** [comment]
>I.e., "obj.Curve" appears to work precisely the same as "obj.Curve.I" when there is only one Curve

That is not accurate, ``obj.Curve`` is a Layout subtree and therefore a Layout in itself while ``obj.Curve.I`` returns the actual node, i.e. the element. I'm not arguing that we shouldn't change it just that it would require an actual change in the datastructure to work as you expect.

**Comment by jbednar** [comment]
The Layout with one Element in it _already_ works as I'd expect (i.e. the same as a bare Element) for the things I've tried, in that it looks the same, goes into Layouts the same, and accepts options the same (as far as I have tested). But I'm guessing that .data will work differently, and slicing or sampling?

**Comment by philippjfr** [comment]
>and accepts options the same (as far as I have tested)

I don't see how this can be true. 

>But I'm guessing that .data will work differently, and slicing or sampling?

Right all of these will behave differently too.

**Comment by jbednar** [comment]
I guess there is no way to win; it's going to be terrifically confusing either way, either from the start (with .I in the repr) or later on (as they tried to use a Layout as an Element.  Sigh.
