### ISSUE TITLE
hover tool for spikes with datetime x

### ISSUE THREAD

**Issue by ahuang11** [ioam/holoviews#2882]
```
import pandas as pd
import numpy as np
import holoviews as hv
hv.extension('bokeh')

dts = pd.date_range('2017-01-01', '2017-01-05')
y = np.arange(len(dts))

hv.Bars((dts, y)).options(tools=['hover'])
```

Bars automatically convert the time
![image](https://user-images.githubusercontent.com/15331990/42967323-be0ae53c-8b54-11e8-82c6-95da0b5e9f4f.png)

Spikes do not automatically convert the time
![image](https://user-images.githubusercontent.com/15331990/42967300-ace00580-8b54-11e8-8e3e-1ef48df6f7ce.png)

**Comment by jlstevens** [comment]
Thanks for reporting this! Definitely looks like a bug.
