### ISSUE TITLE
Inconsistent naming: matplotlib final_hooks vs bokeh finalize_hooks

### ISSUE THREAD

**Issue by ahuang11** [ioam/holoviews#2884]

**Comment by jlstevens** [comment]
Thanks for filing this! I agree it is inconsistent and we should pick one (leaving support for the discouraged version for backwards compatibility, possibly with a warning).

**Comment by philippjfr** [comment]
Now consistently renamed to ``hooks``, with both ``final_hooks`` and ``finalize_hooks`` being marked for deprecation.
