### ISSUE TITLE
Choosing which Bokeh tools are active initially

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#2888]
Bokeh appears to allow users to determine which tools are active when the plot is opened:

http://bokeh.pydata.org/en/latest/docs/user_guide/tools.html#setting-the-active-tools

I thought there was already an issue about this, but I can't find one, so... is there a way in HoloViews to choose which tool(s) should be active initially?

**Comment by marcbernot** [comment]
Duplicate of #2730

**Comment by jbednar** [comment]
That's the one I was looking for, thanks!
