### ISSUE TITLE
Main repository has grown far too large

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#289]
For everyone without a fast internet connection, the time needed to clone holoviews has become problematic. I've waited a while now and I am only 38% through having downloaded 85MB already.

I'm sure the repository doesn't need to be this big (150MB or so?) for the actual source code. I assume the issue is the website branch (i.e ``gh-pages``) which is updated daily.

We really need to find a way to automatically squash this branch!

**Edit:** I can confirm that the repository (without submodules!) is now 158MB in size.

**Comment by philippjfr** [comment]
We've deleted both gh-pages and the reference data submodule. Repository should be much smaller now. Closing.

**Comment by jlstevens** [comment]
Yay! Very glad this has finally happened.
