### ISSUE TITLE
Clickable Legends not responding for hv.Area

### ISSUE THREAD

**Issue by ahuang11** [ioam/holoviews#2893]
`hv.Area([0, 1], label='blue') * hv.Area([1, 0], label='red')`
![image](https://user-images.githubusercontent.com/15331990/43221340-7855645c-9001-11e8-8ea0-d498b97a83b3.png)

**Comment by philippjfr** [comment]
All that's missing to make this work is setting a ``muted_alpha`` value:

```python
hv.Area([0, 1], label='blue').options(muted_alpha=0.1) * hv.Area([1, 0], label='red').options(muted_alpha=0.1)
```

![bokeh_plot](https://user-images.githubusercontent.com/1550771/43456952-39078fee-94bd-11e8-8833-d7cd0fe795e9.png)

A PR adding ``muted_alpha=0.2`` [here](https://github.com/ioam/holoviews/blob/master/holoviews/plotting/bokeh/__init__.py#L176) would be greatly appreciated.

**Comment by philippjfr** [comment]
Thanks for the fix.
