### ISSUE TITLE
PolyDraw not working on bokeh server

### ISSUE THREAD

**Issue by stevievb** [ioam/holoviews#2894]
The poly_draw tool is not clickable. It looks to be flickering when I hover the mouse over it. I also see the same behavior with PolyEdit. This is on bokeh==0.13.0 and holoviews==1.10.7

```
import holoviews as hv
from holoviews import streams

renderer = hv.renderer('bokeh')
renderer = renderer.instance(mode='server')

path = hv.Path([[(1, 5), (9, 5)]])
poly = hv.Polygons([[(2, 2), (5, 8), (8, 2)]])
path_stream = streams.PolyDraw(source=path, drag=True)
poly_stream = streams.PolyDraw(source=poly, drag=True)

app = renderer.app(path * poly)
```

**Comment by philippjfr** [comment]
Thanks, this is really a bokeh issue described in https://github.com/bokeh/bokeh/issues/8032, I'll be working on fixing this before the bokeh 1.0 release. I'll close since this will be handled upstream in bokeh.
