### ISSUE TITLE
Violin plots crash when given all zeros

### ISSUE THREAD

**Issue by slinnarsson** [ioam/holoviews#2897]
I'm truly enjoying learning HoloViews - such a great visualization library!

I encountered a bug, I think. Changing the [Violin plot](http://holoviews.org/reference/elements/bokeh/Violin.html) example to give it all zeros causes an exception:

```python
>>> groups = [chr(65+g) for g in np.random.randint(0, 3, 200)]
>>> hv.Violin((groups, np.random.randint(0, 5, 200), np.zeros(200)), ['Group', 'Category'], 'Value')
(...stack trace here...)
TypeError: 'NoneType' object is not iterable
```

Most likely the kernel density estimation fails. This is an issue for visualizing many groups, when one or more groups may be all zeros. The expected result is a flat line, I suppose (this is what BoxWhisker does).

**Comment by ea42gh** [comment]
`hv.Violin([])` fails as well

**Comment by jlstevens** [comment]
Thanks @slinnarsson and @ea42gh!  I agree both those issues are bugs.
