### ISSUE TITLE
VLine timezone weirdness

### ISSUE THREAD

**Issue by lebedov** [ioam/holoviews#2898]
My computer's time zone is EDT (UTC-4). When I run the below code, the vertical line is displayed at 10h instead of 6h. Is this behavior expected?

```python
import holoviews as hv
import numpy as np
import pandas as pd
hv.notebook_extension('bokeh')

t = [pd.to_datetime('00:00:00')+pd.to_timedelta(x, unit='h') for x in range(12)]
dft = pd.DataFrame({'t': t, 'r': np.random.rand(len(t))})
l = pd.to_datetime('6:00:00')
c = hv.Curve((dft['t'], dft['r']))*hv.VLine(l).options(color='red')
line = hv.VLine(l).options(color='red')
c*line
```
![bokeh_plot](https://user-images.githubusercontent.com/218546/43398663-c9ed9a40-93d6-11e8-8d5a-f56f6cd82d62.png)

I'm using HoloViews 1.10.7, Numpy 1.14.5, Pandas 0.23.3, and Bokeh 0.13.0 with JupyterLab 0.32.1.

**Comment by lebedov** [comment]
Might be a duplicate of https://github.com/ioam/holoviews/issues/2857.

**Comment by lebedov** [comment]
Workaround for the example given:

```python
l = pd.to_datetime('06:00:00').tz_localize('utc').astimezone(tzlocal.get_localzone())
```

**Comment by philippjfr** [comment]
Suspect this is a duplicate too, I'll close for now but will make sure to test any fix against your example.
