### ISSUE TITLE
core.util.validate_regular_sampling() appears to contain redundant call to np.unique()

### ISSUE THREAD

**Issue by ceball** [ioam/holoviews#2899]
https://github.com/ioam/holoviews/blob/master/holoviews/core/util.py#L1653

I happened to notice that creating an Image becomes surprisingly slow as one dimension gets bigger (for a fixed overall Image size). That led me to notice that validate_regular_sampling() contains a call to np.unique() (which sorts). I'm not clear on the purpose of the call to np.unique().

I could demonstrate the problem I'm talking about, and fix it, but first I'm opening an issue in case there's something I'm missing about the need for unique().

**Comment by jbednar** [comment]
I don't quite get what the unique achieves here either, but if it's just about squeezing repeats rather than true uniqueness, you could do something that doesn't sort, like:

![image](https://user-images.githubusercontent.com/1695496/43408799-d814d0d2-93e7-11e8-8e98-132055556e00.png)

**Comment by philippjfr** [comment]
I think there is indeed no need for ``np.unique`` and this could simply be:

```python
diffs = np.diff(values)
return not (len(vals) > 1 and np.abs(diffs.min()-diffs.max()) > abs(diffs.min()*rtol))
```

**Comment by philippjfr** [comment]
This was fixed in https://github.com/ioam/holoviews/pull/2293
