### ISSUE TITLE
links at the end of  holoviews/doc/Tutorials/Showcase.ipynb are outdated

### ISSUE THREAD

**Issue by stonebig** [ioam/holoviews#290]
error 404 for at least two of them, when visualised through github

**Comment by jlstevens** [comment]
Thanks for pointing this out!

**Comment by jlstevens** [comment]
We are going to make the new website live shortly. It is worth running a [link validator](https://validator.w3.org/) first (presumably on the dev section of the website).

**Comment by stonebig** [comment]
great ! I shall experiment a link validator on my own site also.

**Comment by philippjfr** [comment]
Fixed, closing.
