### ISSUE TITLE
ImportError: cannot import name 'XArrayInterface'

### ISSUE THREAD

**Issue by yanbek** [ioam/holoviews#2904]
Unable to run `import holoviews.operation.datashader as hd` without getting the following error

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-56-420559647be7> in <module>()
----> 1 import holoviews.operation.datashader as hd
      2 import holoviews as hv
      3 hv.extension("bokeh")
      4 opts=dict()
      5 

~/programs/BlockSci/.env/lib/python3.5/site-packages/holoviews/operation/datashader.py in <module>()
     25 from ..core import (Operation, Element, Dimension, NdOverlay,
     26                     CompositeOverlay, Dataset, Overlay)
---> 27 from ..core.data import PandasInterface, XArrayInterface
     28 from ..core.sheetcoords import BoundingBox
     29 from ..core.util import get_param_values, basestring, datetime_types, dt_to_int

ImportError: cannot import name 'XArrayInterface'
```

**Comment by philippjfr** [comment]
Assume this was because xarray wasn't installed? If that's the case this should get a better error message (related to https://github.com/ioam/holoviews/issues/798).

**Comment by jbednar** [comment]
Conda (and I _think_ pip) should install xarray automatically when datashader is installed, so maybe datashader itself is not installed (in which case maybe we should try to import datashader in that file _before_ importing xarray)?  Datashader is something we discuss and people can deduce that they need to install, whereas we probably don't mention that xarray is important for datashader.

**Comment by philippjfr** [comment]
I already want to split the ``operation/datashader`` module into a generic resampling module for the baseclasses and perhaps some simple downsampling operations and then the datashader operations. In the process I can improve the imports to ensure we generate better error messages.

**Comment by yanbek** [comment]
I did install xarray and datashader manually via pip. The odd thing is that it got solved automatically after a while without me touching anything. That's why I closed the issue, and I don't know why how it fixed itself.

**Comment by abossenbroek** [comment]
Just got the same issue installing datashader with coda from ioam channel. It looks like datashader doesn't have the proper dependencies on ioam.

**Comment by jbednar** [comment]
I guess we should remove it from ioam; datashader is distributed on the `pyviz` channel nowadays.

**Comment by abossenbroek** [comment]
Seems fair and a better solution.

**Comment by chaseschuette** [comment]
Also getting this error and have installed both xarray and datashader with pip.

`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-133528637a3a> in <module>()
----> 1 import ion
      2 import holoviews as hv
      3 hv.notebook_extension('bokeh')

C:\miniconda\Lib\site-packages\ion_master\ion\__init__.py in <module>()
----> 1 from .model import Window, layout

C:\miniconda\Lib\site-packages\ion_master\ion\model.py in <module>()
      2 import pandas as pd
      3 
----> 4 from holoviews.operation.datashader import datashade
      5 
      6 

c:\miniconda\lib\site-packages\holoviews\operation\datashader.py in <module>()
     25 from ..core import (Operation, Element, Dimension, NdOverlay,
     26                     CompositeOverlay, Dataset, Overlay)
---> 27 from ..core.data import PandasInterface, XArrayInterface
     28 from ..core.sheetcoords import BoundingBox
     29 from ..core.util import get_param_values, basestring, datetime_types, dt_to_int

ImportError: cannot import name 'XArrayInterface'`

**Comment by chaseschuette** [comment]
@philippjfr Here's with import holoviews.core.data.xarray

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-5-175e944e533f> in <module>()
      1 import holoviews.core.data.xarray
----> 2 import ion
      3 import holoviews as hv
      4 hv.notebook_extension('bokeh')

C:\miniconda\Lib\site-packages\ion_master\ion\__init__.py in <module>()
----> 1 from .model import Window, layout

C:\miniconda\Lib\site-packages\ion_master\ion\model.py in <module>()
      2 import pandas as pd
      3 
----> 4 from holoviews.operation.datashader import datashade
      5 
      6 

c:\miniconda\lib\site-packages\holoviews\operation\datashader.py in <module>()
     25 from ..core import (Operation, Element, Dimension, NdOverlay,
     26                     CompositeOverlay, Dataset, Overlay)
---> 27 from ..core.data import PandasInterface, XArrayInterface
     28 from ..core.sheetcoords import BoundingBox
     29 from ..core.util import get_param_values, basestring, datetime_types, dt_to_int

ImportError: cannot import name 'XArrayInterface'

**Comment by philippjfr** [comment]
Hmm, that's less useful than I had hoped. Could you report your holoviews version and also try all these imports separately?

```python
import dask
import xarray
import numba
import datashader
from holoviews.core.data import XArrayInterface
```

**Comment by philippjfr** [comment]
Damn, this is **really** frustrating, especially for you I bet. I don't understand how this could work:

```python
import holoviews.core.data.xarray
```

and this not work:

```
from holoviews.core.data import XArrayInterface
```

At this point our best bet might be for me to try to reproduce it. Could you list your versions for all the packages involved, i.e. xarray, dask, numba and datashader?

**Comment by chaseschuette** [comment]
xarray.__version__ '1.10.9'
dask.__version__ '0.19.3'
numba.__version__ '0..40.0'
datashader.__version__ '.0.6.8'

This is working for one of my coworkers in his environment. I'm going to compare my package versions to his.

**Comment by chaseschuette** [comment]
Following up here.

Much like @yanbek, this also seems to be solved without changing anything. I was about to roll back several packages to old versions then had to restart my system for another reason. After the restart, this issue went away.

**Comment by philippjfr** [comment]
>Much like @yanbek, this also seems to be solved without changing anything.

How bizarre, would be great to figure out what the actual cause was but I'm glad it's now working for you. Thanks for following up in any case.
