### ISSUE TITLE
Overhaul FAQ

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#2906]
The FAQ is very outdated at this point and does not actually reflect the most frequently asked questions we get. My quick summary of the actual most commonly asked questions:

* How do I set axis ranges?
* How do I set color ranges?
* How do I export plots to files?
* How do I convert plots to bokeh/matplotlib figures?

I'm sure there are others but that's the ones that immediately came to mind.

**Comment by ea42gh** [comment]
HoloViews Cheat Sheet #2395 has a list of topics that might find their way here

**Comment by philippjfr** [comment]
@ahuang11 did a great job overhauling the FAQ so I consider this addressed.
