### ISSUE TITLE
VLines on x-axis consisting of times restricted to seconds

### ISSUE THREAD

**Issue by lebedov** [ioam/holoviews#2909]
The following code only appears to draw VLines at the resolution of seconds, i.e., the line at 12:00:01.5 is drawn at 12:00:01. Is there some way to draw VLines at a finer resolution when the x-axis variable consists of times rather than plain floats?

```python
import holoviews as hv
import pandas as pd
import tzlocal

hv.notebook_extension('bokeh')

t = [pd.to_datetime('12:00:00')+pd.to_timedelta(t, unit='ms') for t in np.arange(0, 3000, 50)]
x = np.random.rand(len(t))
t_lines = [pd.to_datetime(_).tz_localize('utc').astimezone(tzlocal.get_localzone()).replace(tzinfo=None) for _ in ['12:00:01.5', '12:00:02']]
lines = [hv.VLine(_).options(color='red') for _ in t_lines]
c = hv.Overlay([hv.Curve((t, x)).options(width=600)]+lines)
c
```
![bokeh_plot 4](https://user-images.githubusercontent.com/218546/43482386-8cc03d16-94d6-11e8-91d2-682e4e237946.png)

I'm using HoloViews 1.10.7 with Bokeh 0.13.0.

**Comment by philippjfr** [comment]
On master:

![bokeh_plot](https://user-images.githubusercontent.com/1550771/49035946-39230500-f1ae-11e8-8fbb-bff316862300.png)
