### ISSUE TITLE
Invalid keys in options dictionary are silently ignored (but should print a warning instead)

### ISSUE THREAD

**Issue by maxalbert** [ioam/holoviews#291]
Executing the two IPython notebook cells below illustrates the issue. The second one produces a plot, but the (invalid) fontsize option `labels` is silently ignored. Instead, it should at least print a warning. The current behaviour is a usability issue because it makes it much harder to experiment and discover what the invalid options are. Tested with HoloViews 1.3.2 (rev. 72d0b41).

```
%reload_ext holoviews.ipython
from holoviews import Curve
```
```
%%opts Curve [fontsize={'labels':30}]
Curve([(1, 1), (2, 2)])
```

**Comment by jlstevens** [comment]
I am fairly sure HoloViews used to warn about invalid options in the past and that we explicitly decided to get rid of this behavior. The reason is that when you switch plotting backends, the valid set of options changes too (e.g switching from matplotlib to bokeh). 

In order to allow the same notebook to work  when switching backends, we decided that invalid options would definitely not cause errors. We also decided not to generate warnings because we thought that could get annoying (switching backend and rerunning  a notebook would generate a ton of warnings). As long as the keywords don't clash, you can currently style your cell for multiple backends without too much trouble.

If you don't consider the different backends (i.e matplotlib only), I definitely agree warnings would be a good idea. Maybe there is still a good way to support this? Perhaps, we could consider a 'validation' option for the output magic? E.g ``validation=None``, ``validation='warn'`` and maybe ``validation='error'``? 

Although there is a good reason for the current behavior, that doesn't mean  we can't improve it to also address this issue (suggestions welcome!)

**Comment by philippjfr** [comment]
I don't think that's accurate, we absolutely do still warn if the style or plot option you supply is invalid. The issue here is the validation of the actual value that has been supplied, in this case the dictionary of fontsizes, apart from the direct validation we get from param, i.e. if the type doesn't match, we've never had validation for the values but probably should. This also fits in with the suggestion of tab-completing the values brough up in #16. To do both validation and completion robustly would probably be a lot of work, but it should definitely be on our roadmap.

**Comment by maxalbert** [comment]
@jlstevens Thanks for the explanation! Yes, I can see that warnings don't mix well with switching backends and can easily get annoying in this case. I also agree that invalid options should not cause errors, but I'd highly be  in favour of a good warning system. From what I can see the key use cases are:

(i) New users who are trying to get to grips with Holoviews and don't know about the valid options yet.

(ii) More experienced users who stick to a single backend and are mostly familiar with the main options.

(iii) Advanced users who change backends frequently.

For (i) warnings are absolutely essential because it can lead to a very frustrating user experience if something doesn't work but is silently ignored with no hint for the user how to fix it.

Warnings are also very much desirable for (ii) because it is unlikely that a user will always remember all the correct options, and it's nice to be able to fail fast and noisily instead of having to try lots of things (this is particularly true of the warning gives a good hint how to find the correct solution).

For (iii) warnings will be annoying. However, I'm wondering how frequent the use case of users switching backends really is. I would have guessed that most users pick a backend they are familiar with and mostly stick to it (but I may be wrong).

In any case, I'd argue that because the cases (i) and (ii) are probably much more frequent, and especially because the cost of losing users at stage (i) is very high, that warnings should be enabled by default. But having a convenient way of switching them off is certainly desirable.

I'm not familiar enough with HoloViews' options system yet to make a good suggestion for the syntax but will have a think about it.

**Comment by maxalbert** [comment]
Btw, does HoloViews attempt to have a unified interface to the various backends (at least for common options)? I.e., does it try to provide unified keywords which are "translated" to the correct keywords for the chosen backend (if they differ)? I'm not sure this is desirable (or even possible), but it might mitigate the need to change many options when switching backends.

On the other hand, it might also be nice for users if they don't need to learn yet another set of options (those for HoloViews) but can simply stick to the ones they already know for their favourite backend (matplotlib, bokeh, etc.). But for options which can be easily guessed and are somewhat universal (such as `title`, `xlabel`, etc.) it could help.

**Comment by jlstevens** [comment]
@philippjfr I stand corrected. You are right, this is about value validation for this plot option,

@maxalbert Sorry for confusing things! What I said about backends does need to be considered but Philipp is right, in this case it is about validating a particular option value. I also agree with your analysis about when warnings are appropriate for different types of user.

I think in the end, ``fontsize``is a hole in our validation and most things are either validated by us (plot options) or rejected by the backend (style options). I do think it is a good idea to validate the set of font size options by generating a warning if the key is not recognized. Note that the ``'labels'`` key isn't currently supported (I'll add it shortly) and that right now you can set the ``'xlabel'`` and ``'ylabel'`` fontsizes.

As for keeping a consistent interface, we do our best with the plot options (which we define) but there is only so much we can do to smooth over backend differences when it comes to style options. Philipp can tell you some of the things he has added to ease compatibility with the bokeh backend if you are interested.

As you point out, we don't want to add needless complexity for people already familiar with matplotlib/bokeh options as those projects already have the necessary documentation regarding the options they support.

**Comment by maxalbert** [comment]
@jlstevens Thanks for the comments and background information. I appreciate that it's a major task and tricky to get right. I had a stab at this in a much smaller context for a personal project a while ago, so I can certainly appreciate the difficulties and think you guys are doing a great job with HoloViews' design to allow both unification and individual customisation of backends. :)

Re `'labels'`, thanks a lot for adding support for it. I know that `xlabel` and `ylabel` are currently supported, but this example was more meant as illustration of an option where the natural guess is (currently) wrong but where there is no feedback for the user to realise their mistake. (This point obviously applies not just to `fontsize` but to any option where a dictionary is supported.)

**Comment by philippjfr** [comment]
In terms of validation I have the following proposals:

* Param error message should list possible options for ObjectSelectors
* We should always validate any dictionaries we use as plot options (currently very few)

In terms of cross-backend support generally we try to make sure that plot options that are supported by all backends should have shared signatures, e.g. xticks, yticks, xaxis, yaxis, logx, bgcolor etc.. We should define a minimum plotting API that any backend should by moving those parameters to the general plotting baseclass. That's just plot options though, the style options are passed directly to the backend specific plotting call and therefore do not share a common API and should correspond to what users are used to from using those libraries. The only exceptions are that I've manually added support for both color and cmap style options in bokeh, additionally I also convert matplotlib markers, colors and colormap to their equivalents in bokeh, so they can be used seamlessly.

**Comment by jlstevens** [comment]
Ok, I'll have a stab at adding support for the ``'labels'`` key now.

**Comment by jlstevens** [comment]
The ``'labels'`` key is now supported since bf23c01.

**Comment by jlstevens** [comment]
The rest of this issue is still valid so I'll switch the milestone to post 1.4

**Comment by jlstevens** [comment]
The PR above that has been merged now validates the keys of the fontsize dictionary. I don't think there any other such dictionaries within HoloViews that we can validate (i.e backend independent). For this reason, I'll close this issue now.

If we find another place such a validation is appropriate, I'm happy to reopen the issue.
