### ISSUE TITLE
Geoview Masking Point Inside Coastline

### ISSUE THREAD

**Issue by neocronomican** [ioam/holoviews#2911]
Dear all, 

I am using holoview and geoview. I want to know is it possible to keep all the value inside the coastline (masking/muting all value outside coastline)? 

![selection_007](https://user-images.githubusercontent.com/37390012/43490539-0afabeba-955c-11e8-8973-a47775e66019.png)

**Comment by jlstevens** [comment]
I think the geoviews version of this issue is more appropriate (https://github.com/pyviz/geoviews/issues/213) so I'll close the issue here. Of course, the discussion relating to geoviews might end up with a new issue/PR in holoviews but formulated to address things in a more general way.
