### ISSUE TITLE
hv.Spread no muted_alpha by default

### ISSUE THREAD

**Issue by wabu** [ioam/holoviews#2919]
hv.Spread is still shown in full alpha when muted inside the legend. This is unexpected, as muting works for all other plots. Setting muted_alpha for spread will work as expected:

```python
import numpy as np
xs = np.linspace(0, np.pi*2, 20)
err = 0.2+np.random.rand(len(xs))

hv.Overlay([hv.Spread((xs, np.sin(xs), err), label='sin')])
```
![muted but still fully visable](https://user-images.githubusercontent.com/39164/43644442-fc71ed9e-972e-11e8-9e20-281b56de949a.png)

To make muting work for spreads, setting it's muted_alpha works as expected, but it should be like this by default.
```
%opts Spread (muted_alpha=.2)
...
```

Version: 1.10.7

**Comment by philippjfr** [comment]
Thanks, this was fixed very recently in https://github.com/ioam/holoviews/pull/2912/files.
