### ISSUE TITLE
Color edges of a graph based on their weights

### ISSUE THREAD

**Issue by drorata** [ioam/holoviews#2920]
Assume having the following dictionary, which describes a graph:

```python
{('a', 'b'): 0.2,
 ('a', 'c'): 0.2,
 ('b', 'c'): 0.06666666666666667,
 ('a', 'd'): 0.2,
 ('c', 'd'): 0.2,
 ('b', 'd'): 0.13333333333333333}
```

Next, I construct an `networkx` graph out of it:

```python
G = nx.Graph()
for e, w in edges_weights.items():
    G.add_edge(*e, weight=w)
```

Lastly, I can plot it as follows:

```python
%%opts Graph [width=300 height=300, tools=['hover'], xaxis=None, yaxis=None]
padding = dict(x=(-1.2, 1.2), y=(-1.2, 1.2))
hv.Graph.from_networkx(G, nx.layout.circular_layout).redim.range(**padding)
```

As per #2696 (I'm using version 1.10.7 of holoviews) I understand that `graph` should know about the weights of `G`. However, I fail to use them for coloring of the visualization. Based on the documentation, I was expecting that something like: 

```python
%%opts Graph [width=300 height=300, tools=['hover'], xaxis=None, yaxis=None, edge_color_index='weight'] (edge_cmap='viridis')
padding = dict(x=(-1.2, 1.2), y=(-1.2, 1.2))
hv.Graph.from_networkx(G, nx.layout.circular_layout).redim.range(**padding)
```

would work but for vain.  I'm not sure whether it is related or not, but `graph.vdims` is `[]` for me.

**Comment by ea42gh** [comment]
Here is the output of your example with hv version 1.11
![bokeh_plot 1](https://user-images.githubusercontent.com/13033479/43677183-af8c0af8-97cb-11e8-9782-1079466be613.png)

**Comment by philippjfr** [comment]
Thanks @ea42gh. I also can't reproduce the issue using 1.10.7. I get exactly the same output.

**Comment by philippjfr** [comment]
Maybe down to the networkx or bokeh version? Could you report those? I've got networkx 2.0 and bokeh 0.13.

**Comment by drorata** [comment]
@philippjfr interesting. I will provide on Monday a more detailed report including all version included. You're saying that the very same code (2nd version) I shared in the OP produced the coloring?

**Comment by drorata** [comment]
Seems like indeed everything works as expected; at least after restarting the kernel. Sorry for the noise.
