### ISSUE TITLE
Reformat Text On Slider When Use dynamic = False

### ISSUE THREAD

**Issue by neocronomican** [ioam/holoviews#2921]
Hi,

I want to ask about how to reformat string on a slider to be like (Year-Month-Date)? 

I use code `my_img = ds.to(hv.Image, groupby='date', dynamic = 'False')` but the text on slider always messy. I have tried `hv.Dimension.type_formatters[np.datetime64] = '%Y-%m-%d'`. Also i try to use `my_img = my_img.clone({np.datetime64(k, 'D'): v for k, v in my_img.items()})` unfortunately it is not working to reformat string on slider.

Thank you very much

**Comment by philippjfr** [comment]
Looking into this now but I'm a bit confused about the ``dynamic = 'False'`` bit. This is a string and due to the truthiness it will evaluate to True.

**Comment by philippjfr** [comment]
This has been fixed.
