### ISSUE TITLE
Sankey diagram backend links to HexTiles

### ISSUE THREAD

**Issue by ahuang11** [ioam/holoviews#2926]
http://holoviews.org/reference/elements/matplotlib/Sankey.html

Clicking one of these links:
`Backends Bokeh , Matplotlib`

Goes to
http://holoviews.org/reference/elements/matplotlib/HexTiles.html

**Comment by jbednar** [comment]
Thanks for the heads up!  Fixed in https://github.com/ioam/holoviews/commit/5e00a9affc2c4a18590933a7bdd79239d421f437
