### ISSUE TITLE
Constructors in the Data API

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#293]
Currently the `reshape` method of the columns interfaces handles the conversion of the input data into a valid format that can be processed. This involves handling the main three formats we support (i.e numpy arrays, pandas dataframes and our simple dictionary format) but also involves handling various ad hoc literal formats.

It would be nice to make the support for these literal formats (e.g dictionaries, tuples etc) standardized across the interfaces and refactor the `reshape` method so they call some other method (`standardize_input`?) to do this step. This isn't a major priority right now but eventually it would be nice to implement to help make the code cleaner and easier to understand.

**Comment by philippjfr** [comment]
``reshape`` no longer exists, and we have robust and tested casting logic now, which allows flexible casting between supported interfaces.
