### ISSUE TITLE
Version incompatibility issue

### ISSUE THREAD

**Issue by ericmjl** [ioam/holoviews#2935]
Hello! I'm trying to use holoviews with Jupyterlab, but I have run into a versioning issue. Would you be kind enough to see where I might have gone wrong?

This is the command I tried running:

```
$ jupyter labextension install @pyviz/jupyterlab_holoviews
> /home/maer3/anaconda/envs/mpnn/bin/npm pack @pyviz/jupyterlab_holoviews
pyviz-jupyterlab_holoviews-0.5.2.tgz

Errored, use --debug for full output:
ValueError: This extension does not yet support the current version of JupyterLab.


Conflicting Dependencies:
JupyterLab              Extension        Package
>=0.17.2 <0.18.0        >=0.16.0 <0.17.0 @jupyterlab/application
>=0.17.2 <0.18.0        >=0.16.0 <0.17.0 @jupyterlab/notebook
>=3.0.3 <4.0.0          >=2.0.0 <3.0.0   @jupyterlab/services
```

Checking my conda packages:
```
$ conda list | grep jupyter
jupyter                   1.0.0                     <pip>
jupyter-client            5.2.3                     <pip>
jupyter-console           5.2.0                     <pip>
jupyter-contrib-core      0.3.3                     <pip>
jupyter-contrib-nbextensions 0.5.0                     <pip>
jupyter-core              4.4.0                     <pip>
jupyter-highlight-selected-word 0.2.0                     <pip>
jupyter-latex-envs        1.4.4                     <pip>
jupyter-nbextensions-configurator 0.4.0                     <pip>
jupyterlab                0.33.4                    <pip>
jupyterlab-launcher       0.11.2                    <pip>
```

I'm not quite sure how I can downgrade my version of jupyterlab extensions such that it works together with holoviews. Is there a command that I can run? 

Also, just wondering, is there a timeline for compatibility with the latest version of jupyterlab?

**Comment by philippjfr** [comment]
The ``jupyterlab_holoviews`` extension is no longer supported and is now called ``jupyterlab_pyviz``, which is compatible with the latest JupyterLab. So please try deinstalling the ``jupyterlab_holoviews`` and then install the latest ``jupyterlab_pyviz``.

**Comment by ericmjl** [comment]
@philippjfr many thanks!

**Comment by TonyPlaysGuitar** [comment]
Could you please also update the instructions on the website then?
http://holoviews.org/user_guide/Installing_and_Configuring.html

**Comment by philippjfr** [comment]
Thanks, I missed that one completely I'll rebuild that part of the website shortly.
