### ISSUE TITLE
The gitter link that is rendered from the README.md returns 404

### ISSUE THREAD

**Issue by canavandl** [ioam/holoviews#294]
Clicking the project glitter link in the README.md that is rendered by Github at  https://github.com/ioam/holoviews returns a 404.

**Comment by philippjfr** [comment]
Strange, seems to work for me.

**Comment by jlstevens** [comment]
Also seems to work for me. Odd.

**Comment by jbednar** [comment]
Oops; the icon link worked, but there was a bogus link in the text.  Fixed in 65eeb8c.
