### ISSUE TITLE
TriSurface Plot Z-Axis Modifications

### ISSUE THREAD

**Issue by jaredmoore** [ioam/holoviews#2964]
When working with the TriSurface plot, I cannot change the tick fontsize of the z-axis.  In the code below, I can create a TriSurface plot and modify the size of the x and y labels.  The `ticks` option changes the font size of the x and y axes, but not the z axis.  It would be nice to have ticks apply to all three axes for the plot.  It also appears there is currently not a way to change the ticksize of the z axis  through an option similar to `zticks` as it doesn't currently exist.

```
surface = hv.TriSurface(zip(x.flat,y.flat,z.flat), label="Treatment 43")\
    .options(yticks=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, 'Tiebreak')], \
             show_grid=False, shade=True, fontsize=dict(ticks=45, xlabel=35, ylabel=35),\
            fig_size=1000, azimuth=45, elevation=10)\
    .redim.label(x='Generation', y='Evaluation Depth', z='Number of Inds')
```

**Comment by ahuang11** [comment]
If you need this plot now, you could get a matplotlib figure object and adjust it natively.

```
import numpy as np
import holoviews as hv
hv.extension('matplotlib')
u = np.linspace(0, 2*np.pi, 24)
v = np.linspace(-1, 1, 8)
u, v = np.meshgrid(u, v)
u = u.flatten()
v = v.flatten()

# evaluate the parameterization at the flattened u and v
tp = 1+0.5*v*np.cos(u/2.)
x = tp*np.cos(u)
y = tp*np.sin(u)
z = 0.5*v*np.sin(u/2.)

surface = hv.TriSurface((x, y, z), label='Moebius band')
surface = surface.options(fontsize=dict(ticks=45, xlabel=35, ylabel=35),\
            fig_size=500, azimuth=45, elevation=10)
fig = hv.renderer('matplotlib').get_plot(surface).state
ax = fig.axes[0]
ax.tick_params(axis='z', labelsize=35)
fig
```

![image](https://user-images.githubusercontent.com/15331990/44798446-5b34c900-ab66-11e8-83a4-183dbfdffac2.png)

**Comment by jaredmoore** [comment]
@ahuang11 Thanks for the suggestion!  I will give that a try for now.  Hopefully we can increase the support for future in Holoviews as well.

**Comment by ahuang11** [comment]
Merged

**Comment by philippjfr** [comment]
We'll try to get a new 1.11 dev release out later today, so you can try it out.
