### ISSUE TITLE
How to get finer widget slider control? In particular for HoloMaps and DynamicMaps

### ISSUE THREAD

**Issue by Gordon90s** [ioam/holoviews#2971]
I would like to have finer control over the slider for HoloMaps and DynamicMaps. If my HoloMap is for example comprised of 500 objects, it is not possible (?) to jump from one image to another by incremental values. I would at least like to be able to manually input this value next to the slider. Is that possible in any way?

Same example as in Issue #2970, with `n_a=500`:

```
import holoviews as hv
import numpy as np
hv.extension('bokeh')

# Define line a*x+b
n = 201
a = 0.8  # slope
b = 2  # offset
x = np.linspace(0,25,n)
def fct(a,x,b):
    return a*(x-2)+b
y = fct(a,x,b)

# create HoloMap object with varying slope
n_a = 500 # number of slope changes
lower_slope_limit = 0.4
upper_slope_limit = 1.2
redim_range = np.r_[np.repeat(9.0,15),np.array([10.0,12.0, 14.0, 17.0, 21.0])]

# let a vary between lower and upper_slope_limit
a_var = np.linspace(lower_slope_limit,upper_slope_limit,n_a)
y_list = []

for i in range(n_a):
    y_list.append(hv.Curve((x,fct(a_var[i],x,b))))
# create HoloMap object    
dict_y = {i:y_list[i] for i in range(n_a)}
hmap_y = hv.HoloMap(dict_y, kdims = ['a'])

hmap_y
```

Even by heavily zooming into the Jupyter Notebook, moving the mouse by one pixel results in a jump of 4 units on the slider. Although I can highlight the slider's output values, I cannot change them with keyboard input.

Same issues with DynamicMaps.

**Comment by ahuang11** [comment]
Seems to work on my Windows machine using the arrow keys.
![test](https://user-images.githubusercontent.com/15331990/44942135-eb8a2e00-ad5f-11e8-9335-0c91c1387072.gif)

**Comment by Gordon90s** [comment]
It indeed works for me too with the arrow keys! Thanks! Not sure why I didn't think of trying it that way...
