### ISSUE TITLE
Issue "complex" dictionary for HoloMap & combination with hv.Dimension(default= )

### ISSUE THREAD

**Issue by Gordon90s** [ioam/holoviews#2979]
So, the solution to Issue #2970 was easy, but now I am not able to set the default value in `hv.Dimension` anymore.

Before the change:

```
dict_y = {i:y_list[i] for i in range(n_a)}
dim_a = hv.Dimension(('a','a'), default=8)

```

Now

```
dict_y = {a_var[i]:y_list[i] for i in range(n_a)}
dim_a = hv.Dimension(('a','a'), default=a_var[8])
```

And the code breaks (full code attached at the end, it does not break at the line level). 

`ValueError: a dimension default 0.736842105263158 is not in dimension values: []`

Although for example `dim_a = hv.Dimension(('a','a'), default=0.4)` (0.4 is the first entry in `a_var`) works.

Something like `dim_a = hv.Dimension(('a','a'), default=0.736842105263158)` does not work either. I can however try `n_a = 21 # number of slope changes` instead of `n_a = 20` to not get more round numbers for `a_var`. In this case, something like `dim_a = hv.Dimension(('a','a'), default=0.8)` kind of works. The figure does not show up straight away, but when playing a little with the widget, the graph reappears.

So seems like a bug to me. Here is the full code that breaks:

```
import holoviews as hv
import numpy as np
hv.extension('bokeh')

# Define line a*x+b
n = 201
a = 0.8  # slope
b = 2  # offset
x = np.linspace(0,25,n)
def fct(a,x,b):
    return a*(x-2)+b
y = fct(a,x,b)

# create HV object for a*x + b together and line y = x
hv_curve = hv.Curve((x,y),'x','y')

# create HoloMap object with varying slope
n_a = 20 # number of slope changes
lower_slope_limit = 0.4
upper_slope_limit = 1.2
redim_range = np.r_[np.repeat(9.0,15),np.array([10.0,12.0, 14.0, 17.0, 21.0])]

# let a vary between lower and upper_slope_limit
a_var = np.linspace(lower_slope_limit,upper_slope_limit,n_a)
y_list = []

for i in range(n_a):
    y_list.append(hv.Curve((x,fct(a_var[i],x,b))))
# create HoloMap object    
dict_y = {a_var[i]:y_list[i] for i in range(n_a)}
dim_a = hv.Dimension(('a','a'), default=a_var[8])
hmap_y = hv.HoloMap(dict_y, kdims = dim_a)

hmap_y
```

**Comment by Gordon90s** [comment]
Hmmm, that results in a list, I would like a slider. I did try the following:

``
dict_y = {round(a_var[i], 2):y_list[i] for i in range(n_a)}
dim_a = hv.Dimension(('a','a'), default=round(a_var[8], 2))
``

That works for the simple example, but it breaks my "main figure" `fix_point_viz_1` further down the road. C.f.:

<img width="1237" alt="screen shot 2018-09-03 at 9 37 24 pm" src="https://user-images.githubusercontent.com/19888075/45000004-ab29ea80-afc1-11e8-91a4-03204a594041.png">
<img width="1216" alt="screen shot 2018-09-03 at 9 37 16 pm" src="https://user-images.githubusercontent.com/19888075/45000006-ab29ea80-afc1-11e8-843c-9240b2f4abe8.png">


and

```
# visualize conditions for which a fix-point exists or not for a linear function

import holoviews as hv
import numpy as np
hv.extension('bokeh')
import bokeh.palettes as bp  # for color palettes




# Define line a*x+b
n = 201
a = 0.8  # slope
b = 2  # offset
x = np.linspace(0,25,n)
def fct(a,x,b):
    return a*(x-2)+b
y = fct(a,x,b)


# styling options
color_palette = 'Inferno'
col_1 = bp.all_palettes[color_palette][256][145]
col_2 = bp.all_palettes[color_palette][256][20]
opts_line_x_x = {'Curve':dict(color='black',line_width=0.8, line_dash='dashed', width=600, height=390)}
opts_curve = {'Curve':dict(color=col_1, width=600, height=390)}

# create HV object for a*x + b together and line y = x
hv_curve = hv.Curve((x,y),'x','y').options(opts_curve)
hv_curve_xx = hv.Curve((x,x)).options(opts_line_x_x)




# create HoloMap object with varying slope
n_a = 21 # number of slope changes
lower_slope_limit = 0.4
upper_slope_limit = 1.2

# let a vary between lower and upper_slope_limit
a_var = np.linspace(lower_slope_limit,upper_slope_limit,n_a)
y_list = []
for i in range(n_a):
    y_list.append(hv.Curve((x,fct(a_var[i],x,b))).options(opts_curve))
# create HoloMap object    
dict_y = {a_var[i]:y_list[i] for i in range(n_a)}
dim_a = hv.Dimension(('a','a'))  # would like to add `default=a_var[8]`, but that breaks the code (bug)
hmap_y = hv.HoloMap(dict_y, kdims = dim_a).options(title_format='')




# Find fixpoint (if it exists, which it doesn't if a >= 1)
x_0 = 8.0  # starting value
n_steps = 7
steps = range(0,n_steps)
hv_path_list = []
for i in range(n_a):
    hv_path_list_j = []
    x_n = x_0
    path = []
    for j in steps:
        y_n = fct(a_var[i],x_n,b)
        x_n_1 = y_n
        path = path + [(x_n,0),(x_n,x_n),(x_n,y_n),(x_n_1,y_n)]
        hv_path_list_j.append(hv.Path([path]))
        x_n = x_n_1
    hv_path_list.append(hv_path_list_j)   
    
dict_path = {(a_var[i],j): hv_path_list[i][j] for i in range(n_a) for j in steps}
hmap_path = hv.HoloMap(dict_path, kdims = [dim_a,'step']).options(title_format='')
fix_point_viz = hmap_y * hv_curve_xx * hmap_path
fix_point_viz_1 = fix_point_viz.redim.range(x=(0,9),y=(0,9))
fix_point_viz_2 = fix_point_viz
```

**Comment by jlstevens** [comment]
This does sound like a float point precision issue to me and likely to be a bug. @philippjfr ?

**Comment by ahuang11** [comment]
![image](https://user-images.githubusercontent.com/15331990/45000459-e7d1f380-af79-11e8-9e79-cc320eac9482.png)

Weirdly, I can't replicate it. Perhaps you can try rounding to three decimal points?

By the way cool viz!

**Comment by jlstevens** [comment]
That is a pretty neat viz indeed! Glad you got it working and thanks @ahuang11 for helping out here.

**Comment by Gordon90s** [comment]
P.S.: Thought maybe my Issue #2969 was related, but it was not. I still did not get it to work.
