### ISSUE TITLE
Canonical way to make Scatter/Points-like plot of two value_dimensions

### ISSUE THREAD

**Issue by poplarShift** [ioam/holoviews#2983]
So apparently we use hv.Scatter for scattering a `vdim` against a `kdim` and hv.Points for two `kdim`s.

```
import holoviews as hv
import numpy as np

d = np.random.rand(50,2)
hv.Points(d,kdims=['x','y']) + hv.Scatter(d,kdims=['x'],vdims=['y'])
```

Is there a canonical way to scatter two `vdim`s against each other, based on some existing `Dataset`? Should there be? (I know I can redefine the vdims etc. in the function call to `Points` or `Scatter`, but that should not be necessary.)

**Comment by philippjfr** [comment]
No, and I don't think there should be. If you have an existing dataset with two value dimensions you can instead specify one or both dimensions you want to plot as kdims and that should work without issue. The point (no pun intended) of Scatter vs. Points is that Scatter allows you to plot an independent against a dependent variable while points treats the data as an abstract geometry in a 2D coordinate system. It sounds like you want to use Points and treat the value dimensions in your dataset as simple geometries.

Just to be clear, what would be the benefit of having a type that allows plotting points as two value dimensions?
