### ISSUE TITLE
creating an irregular quadmesh from an xarray dataset

### ISSUE THREAD

**Issue by rabernat** [ioam/holoviews#2998]
I would like to create an irregular quadmesh from an xarray dataset.

Let's start from the cannonical quadmesh example:
```python
n = 20
coords = np.linspace(-1.5, 1.5, n)
X,Y = np.meshgrid(coords, coords);
Qx = np.cos(Y) - np.cos(X)
Qz = np.sin(Y) + np.sin(X)
Z = np.sqrt(X**2 + Y**2)

qmesh = hv.QuadMesh((Qx, Qz, Z))
```

Now let's say I want to store the data in xarray format. The way I would do so is this:
```python
da = xr.DataArray(Z, dims=['j', 'i'], name='Z',
                  coords={'Qx': (('j', 'i'), Qx),
                          'Qz': (('j', 'i'), Qz)})
```
giving
```
<xarray.DataArray 'Z' (j: 20, i: 20)>
array([[2.12132 , 2.012771, 1.911113, ..., 1.911113, 2.012771, 2.12132 ],
       [2.012771, 1.898023, 1.789861, ..., 1.789861, 1.898023, 2.012771],
       [1.911113, 1.789861, 1.674727, ..., 1.674727, 1.789861, 1.911113],
       ...,
       [1.911113, 1.789861, 1.674727, ..., 1.674727, 1.789861, 1.911113],
       [2.012771, 1.898023, 1.789861, ..., 1.789861, 1.898023, 2.012771],
       [2.12132 , 2.012771, 1.911113, ..., 1.911113, 2.012771, 2.12132 ]])
Coordinates:
    Qx       (j, i) float64 0.0 -0.156 -0.3063 -0.4472 -0.5753 -0.6873 ...
    Qz       (j, i) float64 -1.995 -1.971 -1.924 -1.853 -1.761 -1.65 -1.522 ...
Dimensions without coordinates: j, i
```

The key thing to note is that, in xarray, coordinates and dimensions are different. In this example, there are no dimensions. This works; I can convert to holoviews fine: `hv_ds = hv.Dataset(da)` gives:
```
:Dataset   [Qx,Qz]   (Z)
```
and I can do `hv_ds.to(hv.QuadMesh)`. 

But now suppose the xarray DataArray has *logical* coordiantes i, j defined:
```python
da = xr.DataArray(Z, dims=['j', 'i'], name='Z',
                  coords={'Qx': (('j', 'i'), Qx),
                          'Qz': (('j', 'i'), Qz),
                          'i': ('i', np.arange(20)),
                          'j': ('j', np.arange(20))})
```
If I convert to holoviews with no options, I get `:Dataset   [i,j]   (Z)`. I need to instead do
```python
hv_ds = hv.Dataset(da, kdims=['Qx', 'Qz'])
hv_ds.to(hv.QuadMesh)
```

This is all a bit obvious in retrospect, but it took me quite a while to figure it out. I recommend maybe adding something to the docs about how to create QuadMesh from xarray.

**Comment by philippjfr** [comment]
Thanks this should definitely be documented, we're going to try to update the reference gallery notebooks and docstrings to explain the supported formats better.

As you mentioned in the past the QuadMesh documentation should also explain the difference between supplying the edges of the mesh by supplying ``N+1 x M+1`` coordinate arrays and supplying the bin centers with ``N x M`` coordinate arrays.

**Comment by philippjfr** [comment]
Just merged a major overhaul of the Image, QuadMesh, RGB and HSV element documentation and the gridded data user guide.
