### ISSUE TITLE
Save layout as PNG's using Tools Save button - only first 10 plots are saved

### ISSUE THREAD

**Issue by gsokoll** [ioam/holoviews#3003]
I have generated a layout of multiple hv.Curve plots (approx 20 plots) in a Jupyter Lab notebook.  Using the Save button from the bokeh interactive toolbar results in only the first 10 plots being saved (with filenames of "bokeh_plot.png", "bokeh_plot (1).png", ... "boke_plot (9).png").

Is this a limitation of holoviews, bokeh, the browser, or OS ?  Any suggestions for a workaround ?

I am using Chrome browser on Win10 x64.  In case it was an OS limitation on the permitted number of simultaneous browser downloads, I increased the registry setting "MaxConnectionsPerServer" to 25, without any change.

**Comment by philippjfr** [comment]
I'm not sure what's causing this but I think this should be raised upstream with bokeh.

**Comment by philippjfr** [comment]
Should be raised upstream with bokeh, closing.
