### ISSUE TITLE
Issue with grouped bars and xticks

### ISSUE THREAD

**Issue by msalvaris** [ioam/holoviews#3007]
When using grouped bars it isn't possible to alter the text size of the outer/major ticks. See [here for example](https://files.gitter.im/ioam/holoviews/Onsb/image.png)

**Comment by philippjfr** [comment]
Thanks, I believe when this was initially implemented bokeh did not expose control over those labels but that has now changed.

**Comment by msalvaris** [comment]
Cool, that makes sense
