### ISSUE TITLE
Debug Holoviews Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by danjjl** [ioam/holoviews#3018]
Some of my users have been triggering a segmentation fault when navigating through data served by a Bokeh Server and holoviews.

Are any logging options available to debug this issue.

**Comment by jbednar** [comment]
Are they using Datashader (datashade or rasterize operations in HoloViews)?  There are known issues with datashader and floating-point precision issues that we are trying to track down and eliminate.  Apart from Datashader, any segfaults should be extremely unusual and are very worth following up.  Logging output should be on the terminal and in the browser's Javascript console (see the docs for your browser for how to show that; it's under More Tools/Developer Tools in Chrome).

**Comment by danjjl** [comment]
Yes it is using datashader.

I can check if I can see any useful browser logs.
Terminal output is minimal.
Does datashader use a logging library? Is it possible to increase the verbosity level?

**Comment by danjjl** [comment]
I will close this for the moment. If / When I have more info on the crash, I will reopen.
