### ISSUE TITLE
BoxWhisker with points plotted on top?

### ISSUE THREAD

**Issue by wmayner** [ioam/holoviews#3029]
Is it possible to plot a BoxWhisker with the individual data points visible, _e.g._ as a beeswarm plot ([example](https://www.researchgate.net/figure/Bee-swarm-box-plot-data-with-means-and-SDs-showing-the-differences-between-groups-Bee_fig2_281173626))?

I looked briefly at using `Overlay` and `Scatter` for this, but it wasn't obvious how that would work with the categorical variables on the _x_ axis of the box plot.

**Comment by ahuang11** [comment]
I think you can pass the

`your_scatter_obj.options(jitter=0.2) * your_box_obj`

**Comment by wmayner** [comment]
Awesome, thank you!

**Comment by berkunis** [comment]
what did you type afterwards to show both scatter and the boxwhisker on top of each other?
