### ISSUE TITLE
Explicit color mapping only works for string-type category labels

### ISSUE THREAD

**Issue by timstaley** [ioam/holoviews#3033]
Hi folks,
first thing first -really enjoying getting to grips with holoviews - feels like a breath of fresh air after years of matplotlib, so thanks.

Not sure if this is a proper bug or a documentation issue, but in the [styling plots examples](http://holoviews.org/user_guide/Styling_Plots.html#Explicit-color-mapping) explicit color-mapping is mentioned and an example given. However, this only works if the entries in the 'color_index' column (and equivalently, keys in the explicit mapping dictionary) are of string type so e.g. the following code:

```
categorical_points = hv.Points((np.random.rand(100), 
                                np.random.rand(100), 
                                np.random.choice(list(range(4)), 100)), vdims='Category')
explicit_mapping = {0: 'blue', 1: 'red', 2: 'green', 3: 'purple'}
categorical_points.sort('Category').options(color_index='Category', cmap=explicit_mapping, size=5, colorbar=True)
```

Gives

```
~/code/external/holoviews/holoviews/plotting/util.py in process_cmap(cmap, ncolors, provider, categorical)
    849     if not isinstance(palette, list):
    850         raise TypeError("cmap argument %s expects a list, Cycle or valid %s colormap or palette."
--> 851                         % (cmap,providers_checked))
    852     if ncolors and len(palette) != ncolors:
    853         return [palette[i%len(palette)] for i in range(ncolors)]

TypeError: cmap argument {0: 'blue', 1: 'red', 2: 'green', 3: 'purple'} expects a list, Cycle or valid matplotlib, bokeh, or colorcet colormap or palette

```

The use-case for this is that I want to set the 'color_index' to a boolean column then pick specific colors. I want to do so because If, e.g I pick 'tab10' then True/False get mapped to the extreme ends of the categorical colormap and then actually get plotted as quite similar colors - perhaps that's worth filing as a separate issue? I guess the larger issue here is that then normalization needs to handled differently for categorical vs continuous colormaps, so I can see that being a pain.

**Comment by philippjfr** [comment]
Now fixed.
