### ISSUE TITLE
Rasterize does not consistently handle NaNs

### ISSUE THREAD

**Issue by jsignell** [ioam/holoviews#3037]
I just ran into this issue with arrays containing NaN slices. I was expecting `rasterize` to work perfectly for this but the initial plot was not great:

<img width="657" alt="screen shot 2018-10-02 at 5 15 32 pm" src="https://user-images.githubusercontent.com/4806877/46377540-d823f880-c666-11e8-9a08-e855425472c4.png">

On zoom it seems to resolve:
<img width="656" alt="screen shot 2018-10-02 at 5 16 13 pm" src="https://user-images.githubusercontent.com/4806877/46377555-e40fba80-c666-11e8-8012-9bb3aef17147.png">

But there is a little bit of a stutter and sometimes it gets stuck like:
<img width="670" alt="screen shot 2018-10-02 at 5 16 44 pm" src="https://user-images.githubusercontent.com/4806877/46377582-f8ec4e00-c666-11e8-9f50-d0c9899186d8.png">

### To Reproduce:

```
import xarray as xr
import hvplot.xarray

path = 14
row = 32
pid = 'LC08_L1TP_014032_20160727_20170222_01_T1'

datasets = []

for band in [1,8]:
    url = f'https://storage.googleapis.com/gcp-public-data-landsat/LC08/01/{path:03d}/{row:03d}/{pid}/{pid}_B{band}.TIF'
    da = xr.open_rasterio(url, chunks={'band': 1, 'x': 256, 'y':256}).assign_coords(band=[band])
    datasets.append(da)
    
da = xr.concat(datasets, 'band')
da[0, 7500:7700, 7500:7700].hvplot('x', 'y', rasterize=True)
```

**Comment by philippjfr** [comment]
Given that the underlying array actually has a bunch of nans everywhere this seems like its faithfully rendering what's in the underlying data. Could you describe what you would expect to happen?

**Comment by jsignell** [comment]
I guess I expected `rasterize` to ignore nans and fill the plot area and it does seem to do that on zoom even when some of the bins have only nans in them.

**Comment by philippjfr** [comment]
I think the reason why it does that when you zoom in enough is because it dynamically adjusts the number of pixels the further you zoom in. If you enable ``upsample`` (which is usually disabled) the nans will stick around however far you zoom in:

```
from holoviews.operation.datashader import regrid
regrid(da[0, 7500:7700, 7500:7700].hvplot('x', 'y'), upsample=True)
```

**Comment by philippjfr** [comment]
I'll close this because I consider this expected behavior. If we want to support something like this we should add an interpolation operation which fills the nans, rasterize should faithfully render the underlying data.

**Comment by jsignell** [comment]
But this happens when you just zoom in a tiny bit.

**Comment by jsignell** [comment]
It should at least have consistent behavior.

**Comment by philippjfr** [comment]
You're right, I wouldn't have expected it to kick in until you've zoomed in quite far. We should try to log what happens to the width/height of array as you zoom in and out. I suspect there's something slightly off about that calculation.

**Comment by philippjfr** [comment]
If we round before casting to an int the behavior is indeed more consistent:

```
width = min([int(round((xspan/exspan) * len(coords[0]))), width])
```

That said it still depends on how the plots x_range and y_range align with the underlying grid, so you'll see it switch between seeing the nans and not seeing them whatever we do.

**Comment by jsignell** [comment]
To be clear I am not suggesting that we should interpolate in the nan areas, but rather that we should aggregate over them.

**Comment by philippjfr** [comment]
I'm still not sure that's feasible, depending on the current x_range and y_range the bins will sometimes line up in such a way that some bins contain only nans and other times will line up in a way where all the bins contain some value. This is especially true if the width and height is equal to the resolution of the underlying grid which is what we do to ensure that when you've zoomed in beyond the resolution of the underlying data it doesn't send more data than necessary to accurately convey the underlying grid.

We could instead opt to upsample slightly to avoid issues caused by the grid alignment, but in this case that would just ensure that the nans are always visible. The opposite, i.e. finding a resolution where nans aren't visible, seems orders of magnitude harder and more expensive and any such scheme would have to make assumptions about the data.

I do think the rounding is appropriate if only to ensure that as you zoom in to and beyond the resolution of the underlying array that the data sent to the browser approximates the underlying resolution as closely as possible.

**Comment by jbednar** [comment]
From the above descriptions I can't tell whether there is any issue or not.  It does sound like rounding is an improvement.  Should we discuss this in person so that all three of us can come to a shared understanding?

**Comment by jsignell** [comment]
Oh I think I finally get it @philippjfr. When you zoom in a smidge you shift the bins so they are offset from the original grid and ever cell contains some value. 

Ok so one other way to handle this is to set the min sampling to the original array resolution like:
<img width="917" alt="screen shot 2018-10-04 at 11 26 29 am" src="https://user-images.githubusercontent.com/4806877/46484860-9b701280-c7c8-11e8-94ab-100e7bdae192.png">

I haven't been using that because I have been using the `rasterize` kwarg in `hvplot` which doesn't implement xsampling and ysampling (I think it accepts them and then drops them on the floor).

**Comment by jsignell** [comment]
So I think it is fine to close this and I can open an issue on `hvplot` to get xsampling and ysampling hooked up.

**Comment by philippjfr** [comment]
>So I think it is fine to close this and I can open an issue on hvplot to get xsampling and ysampling hooked up.

Yes, please do. I think there are a few other arguments we may want to accept as well.
