### ISSUE TITLE
Matplotlib z-order problem with legends

### ISSUE THREAD

**Issue by ceball** [ioam/holoviews#304]
![screenshot from 2015-11-21 21 01 36](https://cloud.githubusercontent.com/assets/1929/11445524/a51bf8a0-9524-11e5-931a-e466e5bf8bfc.gif)

**Comment by philippjfr** [comment]
Fixed in https://github.com/ioam/holoviews/pull/434 by setting a very high zorder value. The legend code can still do with a cleanup but I'll close for now.
