### ISSUE TITLE
Confused matplotlib legends for multidimensional holomaps

### ISSUE THREAD

**Issue by ceball** [ioam/holoviews#305]
![screenshot from 2015-11-21 21 09 29](https://cloud.githubusercontent.com/assets/1929/11445615/92b96296-9525-11e5-948a-f829f77ad5a7.png)

Related to #211 ;)

**Comment by philippjfr** [comment]
Fixed in https://github.com/ioam/holoviews/pull/434, now gets the correct levels. #211 stays open though, code is still pretty hairy.
