### ISSUE TITLE
Dataset.reindex does not promote single, string kdim to list

### ISSUE THREAD

**Issue by zbarry** [ioam/holoviews#3080]
.. which results in `reindex` trying to iterate through the characters of the string as individual kdims.

Reproducible example:

```python
ds = hv.Dataset(
    {'asdf': [1, 2, 3, 4], 'b': [1, 2, 3, 4], 'c': [1, 2, 3, 4]}, 
    kdims=['asdf', 'b'], vdims='c'
)
```

`ds.reindex(kdims='asdf')` results in: 

> KeyError: "Dimension 'a' not found."

`ds.reindex(kdims=['asdf'])`, on the other hand, works.

**Comment by philippjfr** [comment]
Thanks been meaning to file a similar issue for ages, there are a few examples of this we should track down. Other examples that I know offhand include ``NdMapping.groupby`` and ``Dimensioned.traverse``.
