### ISSUE TITLE
[feature request] dvd-type widget for DynamicMap

### ISSUE THREAD

**Issue by TomBugnon** [ioam/holoviews#3086]
Hi all,
It is possible to change the type of control widgets for a HoloMap using eg `hv.output(holomap='scrubber')`. Is there a way to equivalently change the type of widgets for a DynamicMap? It seems like they only allow sliders at the moment. I'm particularly interested in the dvd-type widget, which seems like it could be naturally integrated in DynamicMaps when there is a single kdim.
Thanks ! T

**Comment by philippjfr** [comment]
Have a look at the [Panel](http://panel.pyviz.org/index.html) library which now supports the scrubber widget. Eventually we will replace our custom widgets with panel based widgets but for now you can use it directly like this:

```
pn.panel(dynamic_map, widget_type='scrubber')
```
