### ISSUE TITLE
Treat holoviews.rc like python source code and open with encoding=utf8?

### ISSUE THREAD

**Issue by ceball** [ioam/holoviews#3087]
python 3 uses utf8 for source code files. So if e.g. I write 元 as part of an axis label in my python source code, things work.

holoviews has an rc file that's python (looks like python, and gets exec'd), but the rc file is opened like this: `with open(filename) as f:` (https://github.com/ioam/holoviews/blob/63cfac9e104b134f9dcb7eb0f1b16196df16e2db/holoviews/__init__.py#L54).

I think it would make sense to open with encoding=utf8 on python 3, so things are consistent. Otherwise, stuff will get mangled (at least on windows)...

**Comment by jbednar** [comment]
I have no idea; does python open files that way normally?  See https://github.com/ioam/jupytercon2017-holoviews-tutorial/issues/5 for a related issue.

**Comment by ceball** [comment]
In python 3, "the default encoding for Python source code is UTF-8". On the other hand:

> [when opening a file] In text mode, if encoding is not specified the encoding used is platform dependent: locale.getpreferredencoding(False) is called to get the current locale encoding.

(https://docs.python.org/3.6/library/functions.html#open)

So I'm saying that because holoviews.rc is treated as python source code, it should be opened with encoding=utf8 on python 3 because that's what python does for source code files. Otherwise on some platforms (e.g. windows), it'll be confusing (things will be different for rc file vs a regular python source file).

**Comment by jbednar** [comment]
Ok, sounds like a reasonable change to make for holoviews.rc.  And then a similar change should be made to how bokeh reads served files, to address https://github.com/ioam/jupytercon2017-holoviews-tutorial/issues/5?  If so please file such an issue on Bokeh.
