### ISSUE TITLE
Silencing new matplotlib warnings

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#309]
Since upgrading to a recent matplotlib version, I am starting to get some rather annoying warnings. For instance, in the exporting tutorial:

```
/Users/jstevens/miniconda/envs/analytics/lib/python2.7/site-packages/matplotlib/collections.py:650:
 FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self._edgecolors_original != str('face'):
/Users/jstevens/miniconda/envs/analytics/lib/python2.7/site-packages/matplotlib/collections.py:590:
 FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self._edgecolors == str('face'):
```

If this was our code, we could fix it but based on the traceback, these warnings seem to be originating from matplotlib itself. Either we are passing some value into matplotlib it no longer likes, generating these messages or some code within matplotlib hasn't been updated properly.

Either way, do we decide to silence these warnings for now or allow these ugly, unhelpful warnings to appear in the notebook? I probably vote for the latter even though we are working round an issue I don't think we have much control over.

**Comment by jbednar** [comment]
I think we have to decide whether it is due to what we passed or something internal to Matplotlib.  If it's internal, we can silence it after reporting the issue to Matplotlib.  If it's due to us, we can change it.

**Comment by jlstevens** [comment]
I agree with that assessment. I'll assign this to Philipp as he knows the plotting code far better than me and is likely to find the issue (if it is us!) much quicker.

**Comment by jlstevens** [comment]
Ok, I've narrowed the warning in the Exporting tutorial:

* It occurs in  ``holoviews/plotting/mpl/plot.py`` on line 116 (``fig.patch.set_alpha(self.fig_alpha)``) when displaying ``Contours`` (uses ``PathPlot`` which uses ``LineCollection``).
* In matplotlib, the offending line is 651 in ``collections.py``:

```python
if self._edgecolors_original != str('face'):
```
* ``self._edgecolors_original`` is not the argument to ``set_alpha`` and in this case the value is ``[[ 0.  0.  1.  1.]]``

It looks like this one is out of our control so I'm going to push a commit to silence it. I'm going through the tutorials now to look for more warnings...

**Comment by jlstevens** [comment]
My attempts to silence this warning haven't succeeded yet. I do have the minimal example of something that generates a warning though:

```python
from matplotlib.collections import LineCollection
lc = LineCollection([[(0,0),(1,2),(2,3)]])
lc.set_alpha(0)
```

**Comment by jlstevens** [comment]
The first warning is also generated plotting ``ErrorBars`` (again within matplotlib) so it is appearing all over the place. Fundamentally, it generated by numpy:

```python
np.array([1,2,3])  == 'foo'
```

As I am yet to see such a warning appear due to a mistake in HoloViews, I am tempted to surpress it globally in ``holoviews.__init__.py`` (which works):

```python
import warnings
warnings.filterwarnings("ignore", message="elementwise comparison failed; returning scalar instead")
```

Can I go ahead and commit this?

**Comment by philippjfr** [comment]
Yes, we did have some of those warnings ourself but I cleaned them up. Maybe there should be an option to disable that filter for testing, but otherwise just go ahead and commit that.

**Comment by jlstevens** [comment]
Committed in 586b1c1. We can remove this one 1.4 is released (hopefully matplotlib will fix these issues soon).
