### ISSUE TITLE
Changing the size of each node in a chord plot

### ISSUE THREAD

**Issue by brettChapman** [ioam/holoviews#3097]
Hi

I've been trying to overlay additional data in a chord plot to make it more like a circos plot (see attached). However, the additional data never lines up with the nodes in the chord plot. I used Curve to plot the lines in a circle around the chord plot. I've now been considering changing the node sizes in the chord plot to represent the additional data instead. I've been trying to access the handles in the plot to change the node size with little success (based on the information at these sites: https://stackoverflow.com/questions/47838328/how-to-draw-graphs-with-vertices-and-edges-of-different-sizes-using-the-holoview, http://holoviews.org/user_guide/Plots_and_Renderers.html). Is there an easier way to do this? I've come across other plots online which I'm trying to aim for, like these (https://stackoverflow.com/questions/30708674/network-chord-diagram-woes-in-r, https://mimno.github.io/showcase/project2/got/). Is it also possible to add additional outer layers too where the nodes are, so I may have my additional data layered, much like in my circular curve plot in the original plot attached?

Thank you for any help you can provide.

Cheers

Brett

![circosplot](https://user-images.githubusercontent.com/8529807/47332254-51849900-d6b1-11e8-881a-635a133e4ce5.png)

**Comment by philippjfr** [comment]
You should now be able to add a column in the nodes data and then scale the node size by doing: ``node_size='some_column'``. Let me know if you run into issues with this.
