### ISSUE TITLE
Lists as Bounds

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#31]
Works:
```python
hv.Image(near), bounds=(-40,-30,40,30))
```
Does not work:
```python
hv.Image(near), bounds=[-40,-30,40,30])
```
Allow the bound parameter to be any iterable of lenght > 4.

**Comment by jlstevens** [comment]
Thanks for the suggestion!

I don't know a good way of doing an instance check for *any* suitable iterable but at least tuples, lists and numpy arrays are now supported in commit 9a4b7bc7

Looks like I'll be able to close this issue shortly.

**Comment by jlstevens** [comment]
Looks like I can close this issue now.
