### ISSUE TITLE
DynamicMap based on Curve element fails to redraw properly when xaxis base of the curve changes 

### ISSUE THREAD

**Issue by chris-ratcliffe** [ioam/holoviews#3125]
Here is some code to reproduce the issue:

```
import pandas as pd
import holoviews as hv

hv.extension('bokeh')
hv.renderer('bokeh')

def create_curve(timeslice="Weekly"):
    
    weekly_data = {'20171231': 10,'20180107': 15,'20180114': 11, '20180128': 45, '20180204': 33, '20180211': 55, '20180225': 13, '20180304': 31}
    weekly_series = pd.Series(weekly_data)
    weekly_series.name = "score"
    weekly_series.index.name = "YEAR_MONTH_WEEK"
    #weekly_series.index.name = "TIME"
    
    monthly_data = {'201801': 22,'201802': 36,'201803': 44}
    monthly_series = pd.Series(monthly_data)
    monthly_series.name = "score"
    monthly_series.index.name = "YEAR_MONTH"
    #monthly_series.index.name = "TIME"
    
    if timeslice == 'Weekly':
        label = 'Week'
        series = weekly_series
    else:
        label = 'Month'
        series = monthly_series
        
    kdims=hv.Dimension(series.index.name, label=label)
    vdims=hv.Dimension(series.name, label="Score", range=(0,100))
    
    curve = hv.Curve(series,vdims=vdims,kdims=kdims,group="Scores",label=timeslice).options(xrotation=50,width=800,height=400,show_title=True,show_legend=True,fontsize={'title': '15pt'})
    return(curve)

dmap = hv.DynamicMap(create_curve, kdims=['timeslice']).redim.values(timeslice=['Monthly','Weekly'])
dmap
```

In the browser console, I see the message `Error: attempted to retrieve property array for nonexistent field 'YEAR_MONTH'`

The issue seems to be that my 2 series use different index names, those  being YEAR_MONTH and YEAR_MONTH_WEEK.  When I switch series based on the timeslice value, it seems to assume that the name of the index should be the same as it was, and fails.  If I change the code to use the same name for both indexes, then it works fine.

**Comment by philippjfr** [comment]
This is trickier to handle that I had hoped. The problem is that in the notebook holoviews batches updates, which means that it sequentially applies each change to the bokeh models. In this case the data is updated, which triggers a re-render and errors. In theory it could then continue, ignoring the error and on the next re-render triggered by updating an update to the glyph column name for the x-values it would then work fine.

I'll try to get a PR into bokeh which ignores errors on each patch.

**Comment by philippjfr** [comment]
One easy fix would be to send separate comm messages for each event. Not sure how much overhead that would cause, but it's basically the default on bokeh server so maybe it's not that bad.

**Comment by philippjfr** [comment]
This should work now.
