### ISSUE TITLE
Assigning to HoloMap updates instead of assigns?

### ISSUE THREAD

**Issue by almarklein** [ioam/holoviews#313]
This kept me busy for a while. I think it's a bug. If not, it's a bit of an unexpected API (to me, anyway).

```py
import holoviews as hv

# Create structure of HoloMap -> NdLayout -> NdOverlay
compounds = hv.HoloMap()
compounds[7] = hv.NdLayout()
clusters = compounds[7]
clusters[0] = hv.NdOverlay()
clusters[1] = hv.NdOverlay()

# Reset the structure, I'd expect to see just two items in compounds[7] now ...
compounds[7] = clusters.clone({0: clusters[1]})

# But there are two
>> compounds[7].keys()
[0, 1]
```

**Comment by almarklein** [comment]
In the situation where I encountered this in the wild, there were two keys that had the same value (as in same id). Could not reproduce that situation here though.

**Comment by philippjfr** [comment]
Thanks for reporting this. I've changed this behavior in #314, since it is surprising behavior and the user should call update explicitly if that's what they want to happen. I think this was an early misfeature that should have been removed a while ago. Anyway, it's fixed now, closing.

**Comment by almarklein** [comment]
Thanks
