### ISSUE TITLE
Tap Stream and legend problem

### ISSUE THREAD

**Issue by ea42gh** [ioam/holoviews#3135]
I am guessing this is really a bokeh issue:
Clicking the legend area fires a tap with a coordinate
set to the max/min of the side the legend is on.
```
tap      = SingleTap(transient=True)

def react_to_tap(x,y):
    if x is not None: x=np.round(x,2)
    if y is not None: y=np.round(y,2)
    return hv.Scatter([])*hv.Scatter((x,y),label='{},{}'.format(x,y) ).options(legend_position='right', width=500)

hv.DynamicMap( react_to_tap, streams=[ tap ]).relabel('Clicking the legend area fires a Tap')
```

**Comment by philippjfr** [comment]
Tap events anywhere on the canvas trigger, events, we already clip the coordinate to the max coordinate of the plot. I'd be okay dropping these events altogether for the Tap stream. The clipping behavior was mostly added for the PositionXY stream where we want to know when the mouse has left the plot area and not simply drop those events.

**Comment by ea42gh** [comment]
The taps outside the plot area resulted in this type of code:
```
        def react_to_tap(x,y):
            if x is not None and y is not None and x < 5. and y < 5.:
                ....
```
