### ISSUE TITLE
select1d_tap demo issue

### ISSUE THREAD

**Issue by rsignell-usgs** [ioam/holoviews#3142]
I'm trying to run the [select1d_tap demo notebook](https://raw.githubusercontent.com/ioam/holoviews/master/examples/reference/streams/bokeh/Selection1D_tap.ipynb) shown on http://holoviews.org/reference/streams/bokeh/Selection1D_tap.html and I'm not getting the regression plot when I click on the point:
![2018-11-05_8-53-03](https://user-images.githubusercontent.com/1872600/48002258-074fde80-e0d9-11e8-8ed3-94572541f78e.png)
But I'm not getting any errors either. 

This is with:
```
# Name                    Version                   Build  Channel
bokeh                     1.0.0                 py36_1000    conda-forge
holoviews                 1.10.9                     py_0    conda-forge
```

**Comment by philippjfr** [comment]
This is down to a change in bokeh 1.0 which is being discussed here: https://github.com/bokeh/bokeh/issues/8393

There is already a fix in holoviews master: https://github.com/ioam/holoviews/pull/3119

**Comment by rsignell-usgs** [comment]
@philippjfr , excellent, thanks for the speedy response!
