### ISSUE TITLE
Standardizing holoviews as hv in the Tutorials

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#316]
I've noticed that in the tutorials we are still using ``import holoviews`` in places instead of ``import holoviews as hv``. For instance, in the Elements tutorial:

```python
import holoviews
%load_ext holoviews.ipython
from holoviews import Element
Element(None, group='Value', label='Label')
```

Importing as ``hv`` is recommended because it gives a short qualified name, avoiding the need to clutter the namespace.

**Comment by jbednar** [comment]
I agree that it's better to give consistent examples, and it's shorter because the 'from' statement can be omitted.  I think it ought to be done before the tutorials are zipped up, so it can be post v1.4.0, but very shortly thereafter.

**Comment by jbednar** [comment]
May as well change it at the same time as replacing %load_ext.  So this example would then be:

```python
import holoviews as hv
hv.notebook_extensions()
hv.Element(None, group='Value', label='Label')
```

Looks much nicer to me!

**Comment by jlstevens** [comment]
Agreed! Would just need to check for ``holoviews`` in code cells and replace it with ``hv``.

**Comment by philippjfr** [comment]
This has already been done. I'll close.
