### ISSUE TITLE
Documentation for image bounds seems incorrect

### ISSUE THREAD

**Issue by felixpatzelt** [ioam/holoviews#3165]
Hi, the documentation claims (in several places) that the `bounds` argument for `Image` is a tuple with the coordinates ordered as (left, bottom, top, right). It appears to be (left, bottom, right, top), though.

## Example:

```Python
# from http://holoviews.org/reference/elements/bokeh/Image.html
ls = np.linspace(0, 10, 200)
xx, yy = np.meshgrid(ls, ls)

# original line from docs:
#bounds=(-1,-1,1,1)   # Coordinate system: (left, bottom, top, right)

# change bounds to make them all different
bounds=(-2,-1,3,4)
img = hv.Image(np.sin(xx)*np.cos(yy), bounds=bounds)
img
```
<img width="316" alt="img" src="https://user-images.githubusercontent.com/771204/48256208-33d46500-e40f-11e8-9731-8474c5d01232.png">

**Comment by philippjfr** [comment]
Thanks for catching that.

**Comment by philippjfr** [comment]
Thanks again for catching this, can't quite believe how far this spread.
