### ISSUE TITLE
matplotlib KeyError

### ISSUE THREAD

**Issue by Berserker66** [ioam/holoviews#3169]
import holoviews as hv
    curve = hv.Curve(datarows)
    curve_opts = {"width" : 1000,
                  "height": 600}
    curve.options(**curve_opts)
    renderer = hv.renderer('bokeh')
    plot = renderer.html(curve)

```
  File "app.py", line 273, in overview_yearly
    curve.options(**curve_opts)
  File "site-packages\holoviews\core\dimension.py", line 1254, in options
    expanded = opts.expand_options(options, backend)
  File "site-packages\holoviews\util\__init__.py", line 124, in expand_options
    backend_options = Store.options(backend=backend or current_backend)
  File "site-packages\holoviews\core\options.py", line 1059, in options
    return cls._options[backend]
KeyError: 'matplotlib'
```

**Comment by philippjfr** [comment]
This desperately needs a better error message, the problem here is that you haven't imported any plotting backend. Either load the extension with:

```
hv.extension()
```

or import the matplotlib backend:

```
import holoviews.plotting.mpl
```

**Comment by philippjfr** [comment]
A recent PR has added a better error message for this, closing.
