### ISSUE TITLE
Plot multiple images from image dataframe with translations

### ISSUE THREAD

**Issue by LinuxIsCool** [ioam/holoviews#3191]
I have a hv Graph object, from which I can extract node data and join with an image dataframe. The result is to overlay each node in the graph with the logo for the respective nodes. By joining the nodes data with an image dataframe I am able to get all the right data, but am unable to overlay the images over the nodes.

I have the following nodes:

![image](https://user-images.githubusercontent.com/31582215/48922086-0b118e00-ee59-11e8-9859-638ca106d304.png)

From here I can produce a bokeh figure, but am unable to overlay that figure with my holoviews graph. I use the following code to get the resulting overlay:
```

def overlay_image_nodes(nodes):
    # For each node, draw an overlay
    p = figure(x_range=(-1,1), y_range=(-2,2))
    for coin in nodes.index:
        d = dict(nodes.loc[coin])
        d['url'] = [d['url']]
        print(d)
        p.image_url(**d)
    return p
```

![image](https://user-images.githubusercontent.com/31582215/48922183-c89c8100-ee59-11e8-81f4-692bc97db0d9.png)

Which I am trying to overly on my hv Graph:

![image](https://user-images.githubusercontent.com/31582215/48922198-e1a53200-ee59-11e8-8b7d-3e7ed933817b.png)

I see two obvious solutions. 1. Use hv functionality to render the overlay from my nodes df (How to do this?) 2. figure out how to compose an hv.Graph with a bokeh figure.

If it helps, I can also get the images as numpy arrays using the following:
`nodes['npImage'] = nodes['image'].apply(lambda x: np.array(x))`

If only  hv.Image() would take x, y parameters for translating the center of the image.

**Comment by philippjfr** [comment]
@LinuxIsCool Sorry for not replying sooner. The simplest way would simply be to load and embed the images directly using ``hv.Image``, you'd simply overlay multiple images and set the x/y location using the ``bounds`` parameter. If you do want to fall back to bokeh, you can use this to access the bokeh figure created from the graph:

```
# In released versions of holoviews
bokeh_obj = hv.renderer('bokeh').get_plot(hv_obj).state

# In holoviews master
bokeh_obj = hv.render(hv_obj)
```

Feel free to follow up with further questions, but I'll close the issue since this is a usage question.

**Comment by LinuxIsCool** [comment]
Awesome! Thanks Philip! Yes, both solutions are what I had in mind, just coudn't quite get the syntax right. Will try this now.
