### ISSUE TITLE
Image vs Raster, setting style

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#32]
In the options ipynb is showns how to show the cmap of a single image:
```python
Image(data)(style={'cmap':'Greens'})
```

This works not for Raster! Then the cmap is not changed:
```python
Raster(data)(style={'cmap':'Greens'})
```

**Comment by vascotenner** [comment]
Related to this, why does this not work?
```python
Image(data, style={'cmap':'Greens'})
```

**Comment by jlstevens** [comment]
That is very surprising! I've just tried the following code and it works fine for me:

```python
import numpy as np
%load_ext holoviews.ipython
from holoviews import Raster
Raster(np.random.rand(5,5))(style={'cmap':'Greens'})
```

Are you sure this isn't working for you?

As for the second question,  we don't support ``style`` as an argument to our ``Element`` types. We aim to keep the definition of our ``Element`` objects separate from how they are displayed. Once again, the first ``Raster`` example you mention should definitely work!

**Comment by vascotenner** [comment]
Very strange, now it also works over here!

From the tutorial I remember that 
```a=Image(data)
a()```
makes a copy of a, but with setting things again. In that sense it is strange that one can change the style while copying, but not while creating,

**Comment by philippjfr** [comment]
Calling Element objects does not create a copy. Only two types of objects support copying by calling the object, the first is hv.Dimension and the second hv.Option, allowing you to easily create copies, which share many of the same attributes. The call method on Element and Container types is reserved for setting plot and style options, while copying is done via the .clone method.

**Comment by jlstevens** [comment]
I think this issue was due to a misunderstanding of our API so I'll now close it.
