### ISSUE TITLE
Bug in warning message

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#320]
In plotting/util.py:

```python
def collate(obj):
    if isinstance(obj, HoloMap):
        display_warning.warning("Nesting %ss within a HoloMap makes it difficult "
                                "to access your data or control how it appears; "
                                "we recommend calling .collate() on the HoloMap "
				"in order to follow the recommended nesting "
				"structure shown in the Composing Data tutorial"
				"(http://git.io/vtIQh)" % vmap.type.__name__)
	return vmap.collate()
    elif isinstance(obj, (Layout, NdLayout)):
	try:
```

vmap is undefined.  Should it be 'obj'?  If so, shouldn't pyflakes have caught this?

**Comment by philippjfr** [comment]
That's already been fixed in current master as far as I can tell. I did find two other undefined references though and we definitely need to run pyflakes more consistently. Should set up a CI service for that as well.

**Comment by jlstevens** [comment]
I would like pyflakes to be run on every commit, but as a separate test so that it doesn't make it look like HoloViews is failing just because of an unused import (or similar).

**Comment by jbednar** [comment]
Ah, I'm on xic-pick; must have been fixed recently.  Thanks.
