### ISSUE TITLE
Grouped Bar Chart xlabel

### ISSUE THREAD

**Issue by MatCast** [ioam/holoviews#3207]
With a grouped holoviews.Bar() plot exactly like the one in the [example from the documentation](http://holoviews.org/reference/elements/bokeh/Bars.html).
i found no way for changing the label of the x axis? The problem is that the axis label becomes `'Index, Group'` and i can't find a way of referencing it with `redim.label()`. I can change the `'Index'` and `'Group'` label names separately with `redim.label(Index='My Label', Group='My other Label')`. But i can't get rid of the comma in the final xlabel.

**Comment by philippjfr** [comment]
Latest master exposes an explicit ``xlabel`` option you'll be able to use and that should be released later this week.
