### ISSUE TITLE
Scatter points re-jittered while panning plot in docs

### ISSUE THREAD

**Issue by zbarry** [ioam/holoviews#3209]
As discussed with @philippjfr 

Example of re-jittering: http://holoviews.org/user_guide/Plotting_with_Bokeh.html

Are the points on that scatter + error bar example a third of the way down the page supposed to rejitter themselves every update event? They dance around in my browser as I pan the plot.

Just using Bokeh, points aren't continuously jittered: https://bokeh.pydata.org/en/latest/docs/gallery/jitter.html

**Comment by philippjfr** [comment]
Thanks for filing this. I think this must have been fixed by latest bokeh, at least it doesn't seem to rejitter when I try the example locally so I'll close.
