### ISSUE TITLE
dilate kwarg for bokeh heatmaps

### ISSUE THREAD

**Issue by fmaussion** [ioam/holoviews#3220]
Sorry if I missed it (I'm new to holoviews).

Is there a way to avoid intervals between rectangles in bokeh heatmaps? I think that passing `dilate=True` to the underlying call to `rect()` would do the trick, but I couldn't find a way to pass it through.

**Comment by fmaussion** [comment]
Sorry for the rather unclear question: I'm talking about the small but perceptible white intervals between the stripes in [this plot](https://fabienmaussion.info/images/blog/bokeh-stripes/monthly-stripes-1200x600.html)

**Comment by ahuang11** [comment]
```
import numpy as np
import holoviews as hv
hv.extension('bokeh')
data = [(chr(65+i), chr(97+j),  i*j) for i in range(5) for j in range(5) if i!=j]

def _dilate(plot, element):
    plot.handles['glyph'].dilate = True

hv.HeatMap(data).sort().options(hooks=[_dilate])
```
This looks like it works.
(You may need to replace hooks (on master / soon in 1.11) -> finalize_hooks (< 1.11)

**Comment by philippjfr** [comment]
Or more simply:

```
hv.Store.add_style_opts(hv.HeatMap, ['dilate'], 'bokeh')

hv.HeatMap([(i, j, i*j) for i in range(5) for j in range(5)]).options(dilate=True)
```

I'd happily accept a PR that adds the dilate option by default and even one that sets it to True by default. To add it, simply add it to ``['cmap', 'color', 'dilate']`` here:

https://github.com/ioam/holoviews/blob/master/holoviews/plotting/bokeh/heatmap.py#L55

**Comment by fmaussion** [comment]
Thanks all for your help! As it turns out, `dilate` only partly solved the original problem. 

Whether or not the gaps are visible depend on the size of the plot output. See these examples:
- https://fabienmaussion.info/images/blog/bokeh-stripes/annual-stripes-700x300.html (not very good)
- https://fabienmaussion.info/images/blog/bokeh-stripes/annual-stripes-1200x600.html (better, but some gaps remain)

([code on binder](https://mybinder.org/v2/gh/fmaussion/bokeh-stripes/master?filepath=stripes.ipynb) if you are interested)

So I guess this has something to do with floating point issues and bokeh itself.

> I'd happily accept a PR that adds the dilate option by default

Will do - and try to see if I find the tests for this ;-)

**Comment by philippjfr** [comment]
If you want you can add a test to ``holoviews/tests/plotting/bokeh/testheatmapplot.py`` but it's not essential, since the option is passed straight to the glyph that codepath is tested pretty thoroughly already.

**Comment by philippjfr** [comment]
>Thanks all for your help! As it turns out, dilate only partly solved the original problem.

We could consider increasing slightly increasing the size of each rect at the right and top edges by 1% or so, so they don't overlap.

**Comment by ahuang11** [comment]
My initial thought would be adjusting the line_width (which I assumed to be edge width); however, although line_width doesn't error out in options(), it doesn't seem to do anything.
