### ISSUE TITLE
'bare' opt doesn't operate on nested layers

### ISSUE THREAD

**Issue by ahuang11** [ioam/holoviews#3243]
%%opts BoxWhisker [width=600 height=400 show_legend=False]
groups = [chr(65+g) for g in np.random.randint(0, 3, 200)]
hv.BoxWhisker((groups, np.random.randint(0, 11, 200), np.random.randn(200)),
              ['Group', 'Category'], 'Value').sort().options(xaxis='bare', yaxis='bare')

A half-workaround is to redim the label to be ' ' and yticks=False (xticks makes the entire plot go blank)

**Comment by ahuang11** [comment]
'left-bare' works though

**Comment by philippjfr** [comment]
Seems like 'bare' doesn't work at all right now.
