### ISSUE TITLE
Hover with large dataset

### ISSUE THREAD

**Issue by pjvalla** [ioam/holoviews#3265]
I am working with a large dataset and am using building an overlay like this:

```
opts = dict(width=self.plot_width, height=self.plot_height, xticks=10, yticks=10, xrotation=10, fontsize=dict(xlabel=20, ylabel=20), framewise=True)
opts_mesh = dict(tools=['hover'], alpha=0, hover_alpha=.2)
plot = hv.Scatter(self.df, h_var, vdims=v_var)
scatt = hv.Scatter(self.df, h_var, vdims=v_var).options(**opts_mesh)
p0_hover = decimate(scatt, dynamic=False, max_samples=10000, x_range=x_range)
ds_obj = dynspread(datashade(plot, dynamic=False, min_alpha=self.min_alpha, cmap=Sets1to3[0], x_range=x_range, y_range=None)).options(**opts)
return ds_obj * p0_hover
```

This works fine, but the issue seems to be that when I zoom in on the data the density of Hover points goes down.  What I would like is to have a near constant density of hover points.  Right now to make this work I have to drastically increase the ```max_samples`` field, which slows the responsiveness of the plots.

Is there a better way of doing this?

**Comment by philippjfr** [comment]
Apologies, seem to have overlooked this. Did you find a solution?

**Comment by pjvalla** [comment]
No problem.  I believe it is working as it should
