### ISSUE TITLE
Display figure in notebook automatically

### ISSUE THREAD

**Issue by benhid** [ioam/holoviews#3276]
Is there a way of displaying a dynamic map automatically? I'd like to avoid

    def PrettyFigure()
        def __init__(self):
            pipe = Pipe(data=[])
            ...
            self.dmap= hv.DynamicMap(hv.Scatter, streams=[pipe])

    def PrettyVisualizer()
        def __init__(self):
            self.pfigure= PrettyFigure()

    visualizer = PrettyVisualizer() 
    visualizer.pfigure.dmap

and display the figure automatically when instantiating the class `PrettyVisualizer()` (so the last statement, `visualizer.pfigure.dmap`, would no longer be necessary). Thank you!

**Comment by philippjfr** [comment]
You can use the ``display`` function which is a builtin in IPython, e.g.:

```python
def PrettyFigure()
    pipe = Pipe(data=[])
    ...
    dmap= hv.DynamicMap(hv.Scatter, streams=[pipe])
    display(dmap)
```
