### ISSUE TITLE
Font warnings

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#328]
Having recently started using a Mac and OSX instead of linux, I occasionally get font warnings, for instance, when displaying `ItemTable` in the elements tutorial:

```
Users/jstevens/miniconda/envs/analytics/lib/python2.7/site-packages/matplotlib/font_manager.py:1282: 
UserWarning: findfont: Font family [u'DejaVu Sans'] not found. Falling back to Bitstream Vera Sans
  (prop.get_family(), self.defaultFamily[fontext]))
```

It would be good to either:
1. Suppress these warnings.
2. Change the default fonts used to some mythical cross-platform configuration that works for everybody (a fair bit of work as we would still need to update tests)
3. Document how users can install the required fonts and make them available to matplotlib for their operating system.

**Comment by philippjfr** [comment]
These warnings are unrelated to HoloViews and are down to a faulty matplotlib installation. I've also not seen them in years, closing.
