### ISSUE TITLE
Streaming visualization outside notebooks

### ISSUE THREAD

**Issue by benhid** [ioam/holoviews#3280]
I have created this class that handles visualization (this is just a minimal example, in the real use case an algorithm generate points after each iteration and they should be plotted in real time):

    hv.extension('matplotlib')

    class StreamingPlot:

        def __init__(self):
            self.figure = None
            self.pipe = Pipe(data=[])

        def plot(self, points):
            self.figure = hv.DynamicMap(hv.Scatter, streams=[self.pipe])
            display(self.figure)
            self.pipe.send(points)

        def update(self, points):
            if self.figure is None:
                self.plot(front, reference_front)
                return

            self.pipe.send(points)

    plot = StreamingPlot()
    for _ in range(10):
        plot.update([...])

This works as expected when running inside a notebook, but I also want to show the figure (with either Bokeh or Matplotlib) outside Jupyther/IPython. I tried setting up a Bokeh app, but it's blocking the main thread. Any ideas?

**Comment by philippjfr** [comment]
For creating deployable apps in and outside the notebook I'd recommend working with the [panel library](https://panel.pyviz.org). It makes it easy to generate complex dashboards and smooths over the transition between notebook and bokeh server. Here's an example similar to the on you posted:

```python
import numpy as np
import panel as pn
import holoviews as hv

from bokeh.io import curdoc
from holoviews.streams import Pipe

hv.extension('bokeh')

class StreamingPlot:

    def __init__(self):
        self.pipe = Pipe(data=[])
        self.figure = hv.DynamicMap(hv.Scatter, streams=[self.pipe]).opts(framewise=True)

    def update(self, points):
        self.pipe.send(points)

plot = StreamingPlot()

def update():
    plot.update(np.random.randn(100).cumsum(axis=0))

pn.panel(plot.figure).servable()
curdoc().add_periodic_callback(update, 500)
```

Note the use of bokeh's ``curdoc`` to define a callback which is called periodically to update the plot.
