### ISSUE TITLE
Filtering help strings using regexps

### ISSUE THREAD

**Issue by maxalbert** [ioam/holoviews#331]
The help system is really awesome and comprehensive (huge thanks for documenting everything so well!). However, I find that it is sometimes difficult to find the correct piece of information in all the output. It would be fantastic if there was a quick way of only displaying those options whose name or description contain a certain keyword. For example, calling
```
hv.help(obj, regexp="ticks")
```
would display a filtered help string which only shows those options containing the pattern `"ticks"`.

This could be combined with the suggestion in #330 to quickly and succinctly find the relevant options on a composite object.

**Comment by jlstevens** [comment]
Thanks for the more detailed explanation than what I mentioned in #330. Both this issue and #330 will probably be dealt with at the same time.

**Comment by jlstevens** [comment]
This issue has been addressed in PR #370 (now merged) so I'll close the issue now.

@maxalbert Hopefully you'll find this a useful way to find the bits of the documentation you need. It even highlights your search terms which is a little detail I rather appreciate myself...
