### ISSUE TITLE
Image doesn't show anything if only one value exists

### ISSUE THREAD

**Issue by ahuang11** [ioam/holoviews#3350]
Nothing shows, but data is there:
```
import holoviews as hv
hv.Image(np.array([[np.nan, np.nan, np.nan], [1, 1, 1], [np.nan, np.nan, np.nan]]))
```

See some black
```
hv.Image(np.array([[np.nan, np.nan, np.nan], [1, 2, 1], [np.nan, np.nan, np.nan]])).options(tools=['hover'])
```

Workaround:
```
hv.Image(np.array([[np.nan, np.nan, np.nan], [1, 1, 1], [np.nan, np.nan, np.nan]])).options(tools=['hover'], cmap=['black'])
```

I think it's because the first color is white, and nan is also white?

![image](https://user-images.githubusercontent.com/15331990/50452804-3c1a2e00-08f1-11e9-8f83-963caf0645e0.png)

**Comment by philippjfr** [comment]
@jbednar This is one problem with the ``fire`` colormap as the default.

**Comment by jbednar** [comment]
Right.  There are lots of other issues with that, including that fire assumes a black background and the default for most situations is a white page, and that fire has the same issue on a black background (as it includes full black).  I think we already have an issue discussing all those problems, but I don't think we ever came to an agreement about any better approach.
