### ISSUE TITLE
holoviews.plotting.bokeh.util.date_to_integer broken for numpy.datetime64 args

### ISSUE THREAD

**Issue by lebedov** [ioam/holoviews#3368]
In HoloViews 1.11.0, [holoviews.plotting.bokeh.util.date_to_integer](https://github.com/ioam/holoviews/blob/master/holoviews/plotting/bokeh/util.py) chokes when passed a numpy.datetime64 instance. Seems to be a bug on [line 599](https://github.com/ioam/holoviews/blob/master/holoviews/plotting/bokeh/util.py#L599):

```python
        return time.astype('datetime64[ms]').astype(float)
```
should be
```python
        return date.astype('datetime64[ms]').astype(float)
```

**Comment by philippjfr** [comment]
Thanks, unfortunate oversight.
