### ISSUE TITLE
Image zlim option not working

### ISSUE THREAD

**Issue by michaelaye** [ioam/holoviews#3369]
Versions:

```
$ conda list holoviews                                                                    (py37)
# packages in environment at /Users/klay6683/miniconda3/envs/py37:
#
# Name                    Version                   Build  Channel
holoviews                 1.11.0                     py_0    conda-forge
```

Demonstration code:

```python

# Cell 1
import holoviews as hv
hv.extension("bokeh")
img = hv.Image((range(10), range(5), np.random.rand(5, 10)), datatype=['grid'])

# Cell 2
%%opts Image [colorbar=True, width=400, zlim=(0.2, 0.5)]
img
```

Screenshot:
<img width="792" alt="screenshot 2019-01-05 10 30 05" src="https://user-images.githubusercontent.com/69774/50727802-e4d84280-10d4-11e9-94d1-545d717dfebd.png">

**Comment by ahuang11** [comment]
If you need a temporary workaround:

```
import holoviews as hv
hv.extension("bokeh")
import numpy as np
img = hv.Image((range(10), range(5), np.random.rand(5, 10)), datatype=['grid'])

img.opts(colorbar=True, width=400).redim.range(z=(0.2, 0.5))
```
![image](https://user-images.githubusercontent.com/15331990/50732345-50023300-112e-11e9-976d-fdf6d7e5a655.png)

**Comment by philippjfr** [comment]
As @ahuang11 indicates, the zlim option is for the axis, for now you can use the ``.redim.range`` method, but we also just merged a general `clim` option which will be available in the next release.
