### ISSUE TITLE
No color bar or legend for chord plots

### ISSUE THREAD

**Issue by brettChapman** [ioam/holoviews#3372]
Hi

I've created the following chord plot, and have set show_legend and colorbar to true, yet I see no color bars or legend. I've set my edges to be different colors based on the correlation coeff value between the nodes. Is this a bug or something which hasn't been fully implemented yet? Do you have an ETA when the feature will be available?

Thanks

Brett

![bokeh_plot 1](https://user-images.githubusercontent.com/8529807/50810563-46064d00-1345-11e9-9cbc-166004451599.png)

**Comment by philippjfr** [comment]
I think this is merely an oversight, adding this option shouldn't be difficult.

**Comment by jbednar** [comment]
Nice plot, though!  You might try sorting the nodes based on their correlation, as there seems to be very little locality in the original ordering.
