### ISSUE TITLE
DIrected graph does not work

### ISSUE THREAD

**Issue by v0dro** [ioam/holoviews#3395]
I'm using the example specified in the [notebook](http://holoviews.org/user_guide/Network_Graphs.html) for plotting a directed graph. However, it gives the following error:
```
ValueError: Unexpected option 'directed' for Graph types across all extensions. No similar options found.
```

Here's the script that I'm using:
``` python
    start_nodes = []
    end_nodes = []
    edge_labels = []
    for d in data:
        sblock = (d['sblock']['i_abs'], d['sblock']['j_abs'], d['sblock']['level'], d['spid'])
        rblock = (d['rblock']['i_abs'], d['rblock']['j_abs'], d['rblock']['level'], d['rpid'])
        
        start_nodes.append(str(sblock))
        end_nodes.append(str(rblock))
        edge_labels.append(d['method'])
    
    graph = hv.Graph(((start_nodes, end_nodes),))
    graph = graph.relabel('hello').options(directed=True, arrowhead_length=0.05)
    graph
```

**Comment by philippjfr** [comment]
@v0dro Please report the holoviews version you are using, you will have to update to v1.11.0. I'm closing since this is almost certainly a version issue, please reopen if you do have the right version.

**Comment by v0dro** [comment]
Ah I see. Would be great if you could update the package version on conda as well! :)

**Comment by v0dro** [comment]
Btw I was using `1.10.7`.

**Comment by philippjfr** [comment]
Yeah, we'll try to update the defaults channel asap, you can always use the pyviz channel to get the latest version though:

```
conda install -c pyviz holoviews
```
