### ISSUE TITLE
Skipping lines for pyflakes

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#340]
Currently we use comments like this for pyflakes to ignore:

```python
from .core import archive                               # pyflakes:ignore (API import)
```

However, this type of comment is only ignored by a custom pyflakes script we used to use in topographica. 

We should use a standard tool for this such as [flake8](https://flake8.readthedocs.org/en/latest/) that is supposed to skip lines with the ``# noqa`` comment. Maybe we can search and replace ``pyflakes:ignore`` with ``noqa`` everywhere and suggest people use flake8?

**Comment by jbednar** [comment]
Sure, if there is now a standard tool for this, then great!  We've had to make our own solutions for so many things because we've been doing this for so long now, but anything we can offload to a standard solution is a big win for us!

**Comment by jlstevens** [comment]
The PR switching us to use flake8 has now been merged. Closing this issue.
