### ISSUE TITLE
`.options(xlim=..., ylim=...)` does not work in layout when dimension names are the same

### ISSUE THREAD

**Issue by dclong** [ioam/holoviews#3408]
The screenshot below illustrate it. When the dimension names of the 2 subplots are identical, `options` doesn't work well.

![image](https://user-images.githubusercontent.com/824507/51294869-b78b6e80-19c9-11e9-94c5-0d38e7775f41.png)
Is it possible to allow change x/y ranges without explicitly specifying dimension names?

**Comment by philippjfr** [comment]
By default axes with the same name will be shared, to disable this either give them appropriate names (strongly encouraged) or set axiswise=False.
