### ISSUE TITLE
Rendering glitch: Scatterplot with color-by-value option initially coloring all points the same

### ISSUE THREAD

**Issue by timstaley** [ioam/holoviews#3423]
Hi folks,

I'm getting a weird rendering issue. I have a simple categorical scatterplot, colored by category (actually a T-SNE embedding of the iris dataset, but that's not really important). On initial plot of the scatter, all points are the same colour (they should be coloured 3 ways). After a box zoom, it's somehow fixed, and I'm getting different colors again. 

I thought this was going to be a Bokeh JS issue, but the matplotlib render is monochrome too?

HTML / PNG outputs attached, if you think this is a novel bug I'll pull out a tidy reproducing example.

![iris-tsne](https://user-images.githubusercontent.com/1352905/51490401-1161af00-1da3-11e9-97b1-09f170ad1d37.png)
[iris-tsne.html.zip](https://github.com/ioam/holoviews/files/2779963/iris-tsne.html.zip)

**Comment by philippjfr** [comment]
That's very odd indeed. Could you provide the code used to generate the plot?

**Comment by timstaley** [comment]
Ah, happy to report that this was PEBKAC - in doing some Xarray wrangling I'd somehow performed a sort of cartesian cross-product on my data, getting a copy of every label for every datapoint. That explains the weirdness! Will close this.
