### ISSUE TITLE
Deprecated NdElement data type still being used

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#343]
I've come across this behavior which I believe is a bug:

```python
>>> hmap= hv.HoloMap({1.0:hv.Table(np.array([[0, 0], [ 1, 0]]), kdims=['ROI'], vdims=['mean'])}, 
           kdims=['Time'], vdims=[])
>>> type(hmap.table().data)
holoviews.core.element.NdElement
```

Surely this should be using the ``DictColumns`` format or maybe the ``DFColumns`` format (if pandas is available?)

**Edit:** It is now clear the issue begins in the ``table()`` method call.

**Comment by philippjfr** [comment]
Fixed in https://github.com/ioam/holoviews/commit/ebca1fc0dea50cd6e917ea4f59b2efa9a5405ab6. Closing.
