### ISSUE TITLE
A more useful error message in conversions

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#344]
This doesn't work:

```python
hv.HoloMap({t:hv.Table(np.array([[0,0],[1,1*t],[2,2*t]]), kdims=['ROI','mean']) for t in range(4)}, 
           kdims=['Time']).table().to.curve('Time', 'mean')
```

Resulting in the message:

**AttributeError**
'NoneType' object has no attribute 'name'

The reason being that ``'mean'`` should be in the vdims. This does work:

```python
hv.HoloMap({t:hv.Table(np.array([[0,0],[1,1*t],[2,2*t]]), kdims=['ROI'], vdims=['mean']) for t in range(4)}, 
           kdims=['Time']).table().to.curve('Time', 'mean')
```

This issue is to see if we can provide a more helpful error message here!

**Comment by philippjfr** [comment]
Couldn't replicate your particular error but the TableConversions did have a major bug. Both your examples work since c78fbea56a08af78b8b0d3148cd811631b8c8e51.
