### ISSUE TITLE
hover vertical 

### ISSUE THREAD

**Issue by pjvalla** [ioam/holoviews#3455]
Is there a way to have the hovertool display the closest point on a curve to a vertical line drawn from the cursor location?  I would just like a single hover output.  The plot would behave in the same way as the example given below.

https://www.highcharts.com/demo/line-time-series

**Comment by philippjfr** [comment]
You can create a custom bokeh HoverTool instance:

```python
hover = HoverTool(tooltips=[('x', '@{x}'), ('y', '@{y}')], mode='vline')
hv.Curve([1, 2, 3]).opts(tools=[hover])
```

**Comment by pjvalla** [comment]
Thanks, works great.  Do have one question when using a custom hovertool on an aggregated set of points.  

here are the column names of the points type (Notice the multi-level index): 

```
<bound method Dataset.columns of :Points   [Discrete Freq,Spectral Slice]   (PowerdB)>
```

Using the built in hover works fine.
 
![waterfall](https://user-images.githubusercontent.com/10789547/52182646-24c24080-27cd-11e9-9703-e1e2a0bcd45f.png)

But I need to round the "Spectral Slice" values.  I was going about it like this.

```
hover_water = HoverTool(tooltips=[('Discrete Freq', '@{Discrete Freq}'), ('Spectral Slice', '@{Spectral Slice}{int}'), ('Power dB', '@{PowerdB}')])
opts_hover = dict(tools=[hover_water], alpha=0, hover_alpha=0.2, fill_alpha=0)
extents = ret_extents(self.xrange, self.yrange)
agg = aggregate(self.points, width=width, height=height, dynamic=False, x_range=self.xrange, y_range=self.yrange,
                aggregator=ds.max('PowerdB'), x_sampling=self.step_size, y_sampling=1)
return hv.QuadMesh(agg, extents=extents).options(**opts_hover)
```
This returns an invalid hovertool.

![waterfall_invalid](https://user-images.githubusercontent.com/10789547/52183011-a320e180-27d1-11e9-89dd-a5146714c2b9.png)

Is there a way to reference the muli-level index?

**Comment by philippjfr** [comment]
I think the problem here is that the plotting escapes the dimension names in the HoverTool spec (so ``@{Discrete Freq}`` should work. I think holoviews should probably do that for you, mind filing an issue?

**Comment by pjvalla** [comment]
Sure.
