### ISSUE TITLE
PDF export via nbconvert

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#351]
I like to create a pdf file from my notebook. Before using holoviews I used nbconvert for that. However, hv graphs are not shown correctly, only the repr is shown.  This might have to do with all the javascript that is injected to show holoview plots.

As a semi-solution I now use the "print" function in ipython notebooks. However, in that case I loose syntax highlighting.

**Comment by jlstevens** [comment]
Although PDF can support some [sort of Javascript](http://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/js_api_reference.pdf) this is often unsupported by PDF viewers and I'm not sure the API would make exporting widgets to PDF possible.

When exporting to anything other than HTML, you need to make sure the notebook doesn't contain any widgets. If you select a single element to display from your holomaps, those should export fine as static frames and if not, that is a bug we need to look into.

I think it may be possible to automatically turn a HoloMap into a frame using an nbconvert preprocessor but this is something each user of need to configure for themselves (HoloViews has no way of hooking into nbconvert). For more information, see this [stackoverflow post](http://stackoverflow.com/questions/22037910/converting-ipython-notebook-to-html-with-separate-images) for the sort of thing that can be done.

**Comment by philippjfr** [comment]
I assume you mean plots in general not just HoloMaps? We'd have to look into supporting different reprs because currently all our output is wrapped in html, which probably doesn't export to pdf.

**Comment by jlstevens** [comment]
Ah right, yes there is already a related issue about this: #183 

@philippjfr Given that the rendering system has been refactored even further, could this be a trivial change in the display hooks at this point? Looking at it, I think changing the ``render`` method to not necessarily output HTML and setting ``raw=True`` in ``display`` might do the trick.

The only issue then is how to register the display hooks correctly. *If* HTML takes precedence over other formats (as I think it should), you could register new formatters (png, svg) and just have an option that determines the output format (default would be HTML of course). Unfortunately, you would still need to rerun the notebook with the flag set for the change to take effect...

**Comment by jlstevens** [comment]
> As a semi-solution I now use the "print" function in ipython notebooks. However, in that case I loose syntax highlighting.

@vascotenner Could you give an example of what you do here? If I understood this approach, maybe I could figure out a better solution...

**Comment by vascotenner** [comment]
notebook menu: file->print preview + browser menu->print

**Comment by philippjfr** [comment]
I've got an initial prototype working, at least for static figures, so it should be fairly straightforward.

**Comment by jlstevens** [comment]
@vascotenner I've made a PR (referenced above) to address this issue. I would be very grateful if you could test that branch (``multiple_repr``) with your export process to see if it works. The notebook will contain the data necessary for nbconvert to work but I haven't tested it myself (not tried PDF export on this system yet).

All you should need to do is this:

```python
hv.notebook_extension(display_formats=['html','png'])
```

**Comment by jlstevens** [comment]
Philipp went ahead and merged to PR so you can try it out on master. As I believe this issue has been resolved, I think it is time to close it.

**Comment by vascotenner** [comment]
This works fine. Thank you for the fast fix!

**Comment by jlstevens** [comment]
Great! Thanks for confirming.
