### ISSUE TITLE
Addition option to specify fontsize in legend

### ISSUE THREAD

**Issue by RafalSkolasinski** [ioam/holoviews#353]
So far with magics one can adjust following fontsize's:
```
fontsize:          Specifies various fontsizes of the displayed text.
                   
                   Finer control is available by supplying a dictionary where any
                   unmentioned keys reverts to the default sizes, e.g:
                   
                      {'ticks':20, 'title':15, 'ylabel':5, 'xlabel':5}
```

It would be cool to also be able to set fontsize in legends.

**Comment by jlstevens** [comment]
This issue is addressed in the PR mentioned above. I'll close this issue as soon as that PR is merged. 

If you have any issues using this feature after the merge, I'll be happy to reopen the issue.

**Comment by philippjfr** [comment]
The PR has now been merged. Closing.
