### ISSUE TITLE
Allow any plot as adjoints

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#358]
Currently, histograms (and some other types of plots?) can be used as adjoints in layouts, as in the home page example:

![holohome](https://cloud.githubusercontent.com/assets/1695496/11792952/88bcb54e-a26e-11e5-8478-ea32be48ac7b.png)

But often we want to plot some quantity that has a relationship to the x or y axis of the main plot, and it would be nice to be able to put whatever that plot is in the same position that the histogram fills.  E.g. in the home page example, the slice would actually make sense as an adjoint along the top, since it's a slice along that axis:

![holohome2](https://cloud.githubusercontent.com/assets/1695496/11792997/c09c8a0c-a26e-11e5-99cf-a50e149b5623.png)

Is this feasible?  It would make for much more effective layouts in some cases, allowing the main plot to be large while still allowing space for the adjoint plots.

**Comment by jbednar** [comment]
Alternatively, eventually we really need to have more control over the layout in general, e..g. to make some plots take twice the width of others (so that here the main plot could be big with the two other plots side by side below or above it).  But supporting any plot as an adjoint seems more feasible in the short term.

**Comment by philippjfr** [comment]
The main obstacle to that is to make sure that all plot types support inverting the axes. Should be fairly straightforward but will take some time.

**Comment by jbednar** [comment]
What would be the syntax?  Something like 
```python
((fractal * HLine(y=0)).hist().adjoin(fractal.sample(y=0)))
```
?

**Comment by philippjfr** [comment]
Currently it's:

```python
((fractal * HLine(y=0)).hist() << fractal.sample(y=0))
```

**Comment by jbednar** [comment]
Thanks. Currently that gives a fairly unhelpful "KeyError" and no other output.

**Comment by jlstevens** [comment]
We introduce the ``<<`` operator because we wanted the adjoint plots to be general (i.e what this issue is asking for). That operator is so rarely used I would like to either see it either go away or get used more often!

Given that removing the operator would require a new method (e.g ``adjoin`` above), I would hope resolving this issue will mean ``<<`` will get used more.

**Comment by philippjfr** [comment]
This also reminds me that we don't have a way to style adjoined plots separately from normal plots, so we can't expose any additional plot or style options an adjoined plot adds. Thought we had an issue about that but can't find it right now.

**Comment by vascotenner** [comment]
Furthermore, `AdjointLayouts` are not in the tutorials yet. `hv.help(hv.AdjointLayout)` points to something like: http://holoviews.org/Tutorials/Containers.html#AdjointLayout

**Comment by philippjfr** [comment]
>Furthermore, AdjointLayouts are not in the tutorials yet. hv.help(hv.AdjointLayout) points to something like: http://holoviews.org/Tutorials/Containers.html#AdjointLayout

Good point, we had originally considered deprecating them, but they are useful so we should definitely document them.
