### ISSUE TITLE
Improvement of scaling option for Points element

### ISSUE THREAD

**Issue by maxalbert** [ioam/holoviews#363]
*This is copied from a discussion on Gitter. Apologies for the length of this text, but I wanted to create a Github issue so that it's not forgotten. Unfortunately, I don't have time to to shorten it right now.*

I'm trying to plot some data as a collection of "bubbles" of varying sizes using the `Points` elements, but I'm having a hard time getting scaling to work.
The reason is that IMHO the `scaling_factor` option works in a very non-intuitive way.
Here is a small example to illustrate my point. First, let's create some random x/y positions and bubble sizes.
```
N = 100
np.random.seed(12345)
x = np.random.rand(N)
y = np.random.rand(N)
sizes = np.arange(N)
df = pd.DataFrame(dict(x=x, y=y, bubblesize=sizes), columns=['x', 'y', 'bubblesize'])
```
Let's plot this data:
```
%%opts Points [size_index=2 scaling_factor=1]
Points(df, kdims=['x', 'y'], vdims=['bubblesize'])
```
Just from looking at this cell I would read it as follows: "Plot a bunch of points at the x/y positions found in the first two columns of the data frame `df`, and set the point sizes according to the values in the third column; in doing so, use a scaling factor of 1, i.e. don't alter the values in the third column (**but still respect these values!**). I would expect that  chosing a scaling factor of 5 instead of 1 would result in every point being 5 times larger than before, but the *relative* point sizes should remain the same.

However, this is not how it works. The above cell produces a plot where all points have exactly the same size. At first I thought that this was perhaps because the scaling factor was too small and resulted in point sizes that were too small to be distingushable on screen. Thus I changed the scaling factor to 50 (the same value as in the example from the Holoviews documentation) but ended up with a plot that was uniformly blue. So I kept reducing the scaling factor to successively smaller values (10, 5, 2, 1.5, 1.2, 1.1), none of which made a difference. To be honest, at first I had no idea what was going on and tried fiddling with the plot for a good 15 minutes. Admittedly, I should have looked at the documentation much sooner but it didn't even occur to me that `scaling_factor` would do anything other than linearly scale the point size (either in terms of radius or area).

I finally ended up looking at the help string for `scaling_factor`, which at least made it clear that some sort of exponential scaling is being used (although the details of the method still escape me), although I must say that I still find the scaling behaviour rather unintuitive. But my subjective opinion aside, I think there are also significant objective drawbacks to the current behaviour.

(1) The range of values for `scaling_factor` that will result in acceptable plots can vary wildly and is highly sensitive to that range of values in the `size_index` column. When using random sizes between 0 and 1 (as in the example in the Holoviews docs), any scaling factor in the range [10, 200] results in a plot that looks resonably good. On the other hand, iff he values in the `size_index` column range from 0 to 99 (as in my example above), the acceptable range for the scaling factor is the very narrow interval [1.02, 1.06]. The potential difference in magnitude as well as in range makes it difficult for the user to guess a sensible scaling factor and requires a lot of fiddling to get a decent-looking plot.

(2) The choice of *conceptual method* used for the scaling should be separate from the *numerical value* of the scaling factor. However, currently they are intermingled: a value of 2 results in linear scaling of the point *areas* while a value of 4 results in linear scaling of the point *diameters*. This is bad for multiple reasons:

- Say you want your data values to be represented by the circle areas. This requires you to pick `scaling_factor=2`. However, depending on your data values the overall circle sizes may turn out too large or too small. But since you have already specified the value of `scaling_factor` you now have no way of tweaking these sizes any more.

- Choosing a value different from 2 or 4 results in a scaling method that has no meaningful "geometric" interpretation, and you can basically achieve any kind of "relative exaggeration" of your data points by choosing an appropriate value. (That is, if your data range doesn't require you to choose a scaling factor in a narrow interval; see point (1) above.) Rather than leading to good visualisations of your data this instead opens the door for inadvertent (or deliberate) obfuscation. Given that people already have problems comparing areas correctly (for example in pie charts), scaling circle sizes by a different power will allow no meaningful comparison whatsoever (e.g. what does it mean to scale by a power of 2.759?).

For all these reasons I would like to propose a different way of specifying scaling. I'd suggest to have a separate option called `scaling_method` which allows you to choose whether circles should be scaled by diameter or area (maybe one could allow additional methods, but I can't think of any other meaningful ones). The value of `scaling_factor` would then simply be the numerical factor by which the diameter or the area should be scaled.

**Comment by maxalbert** [comment]
If my suggestion for separating the `scaling_method` from the `scaling_factor` makes sense then I'm happy to submit a PR. (I should find some time to work on it over the Christmas period.)

**Comment by jbednar** [comment]
I agree that the current approach is very fiddly, unintuitive, and requires much trial and error.  Hope you can make something more useful!

**Comment by maxalbert** [comment]
Ok, I'll try to get an initial PR together as soon as I find the time and we can discuss and refine it from there.

**Comment by philippjfr** [comment]
Definitely agree, the ``scaling_method`` should be independent from the ``scaling_factor``. Looking forward to the PR, and let me know if you have any questions or encounter any issues.

**Comment by philippjfr** [comment]
This was addressed in https://github.com/ioam/holoviews/issues/447. Closing.
