### ISSUE TITLE
Notebooks download link on webpage broken

### ISSUE THREAD

**Issue by robintw** [ioam/holoviews#377]
The link to download the zipped package of tutorial notebooks on the tutorials page (http://ioam.github.io/holoviews/Tutorials/index.html) is broken. The link points to http://ioam.github.io/holoviews/Tutorials/notebooks-1.4.0.zip which gives a 404 Not Found error.

A similar link on the home page (http://ioam.github.io/holoviews/index.html) points to http://ioam.github.io/holoviews/Tutorials/notebooks-1.3.2.zip, which works fine.

I would have submitted a PR to fix this, but I wasn't sure whether it might actually have been an error caused by notebooks-1.4.0.zip not being uploaded properly.

(Regardless, both links should point to the same file)

**Comment by jlstevens** [comment]
Thanks for reporting this!

We are expecting to put out a 1.4.1 release tomorrow and we'll be updating the website properly. I'll make sure to upload the zip archive this time - I forgot that the version string is updated from ``setup.py`` regardless of everything else.

So we anticipate this will be fixed tomorrow and you should be able to try out the updated notebooks with the new release.

**Comment by robintw** [comment]
Perfect - thanks!

(I assume the new version of the notebooks will also fix a few of the issues I've found with the v1.3.2 notebooks - which are using old notebook file formats, and using deprecated IPython (sorry, Jupyter) functions)

**Comment by jbednar** [comment]
For a while we were using the old notebook file formats for backwards compatibility (since the newer versions of IPython could read both), but I think the new versions of IPython/Jupyter have been out long enough that we should distribute the new notebook format now.

**Comment by philippjfr** [comment]
We upgraded shortly after the 1.3.2. release and addressed the various deprecation and shim warnings that happened after "the big split" in IPython/Jupyter.

**Comment by philippjfr** [comment]
Links have been updated again. The notebook zips are now available under http://assets.holoviews.org/notebook-x.x.x.zip, where x.x.x is the version number. Closing the issue.
