### ISSUE TITLE
Annotation labels in Overlays

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#38]
When you overlay annotations, you typically lose the title as the labels of the different layers don't match so no label is set.

Although this behavior is fine for many element types, it doesn't make sense for ``Annotation`` elements where you are annotating some data that lies underneath the annotation layers. In this case, the group and labels of the annotation(s) should be ignored so that you can see the title of the data that has been annotated.

**Comment by jlstevens** [comment]
Implemented in b401761f and soon to be released!

**Comment by jbednar** [comment]
Looks good, thanks!
