### ISSUE TITLE
Data format of ItemTable

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#380]
This issue is simply a reminder to update the data format used by the `table` method of `ItemTable` to the new dictionary columns format.

**Comment by jlstevens** [comment]
@philippjfr Seems this issue is probably outdated now after the recent work on the data API.

Think this issue can be closed now?

**Comment by philippjfr** [comment]
ItemTable and the data API are unrelated, so it should probably stay open.

**Comment by philippjfr** [comment]
Turns out this indeed could have been closed back in May 2016, oh well.
