### ISSUE TITLE
warning message in Pandas_Conversion.ipynb for holoviews 1.4.1 and Pandas 0.17.1

### ISSUE THREAD

**Issue by stonebig** [ioam/holoviews#387]
for 
````
example_table = example.table(['a', 'b'], 'c')
example_table
````

i get a:
````
WARNING:root:DFrame01032: The DFrame conversion interface is deprecated and has been superseded by a real integration with pandas.
````

**Comment by stonebig** [comment]
and for:
````
`%%opts Curve (color=Palette('Set3'))
gdp_curves = macro.curve('year', 'GDP Growth')
gdp_curves.overlay('country')
````
a slightly different message
````
WARNING:root:DFrame01183: The DFrame conversion interface is deprecated and has been superseded by a real integration with pandas.
````

**Comment by philippjfr** [comment]
These are genuine deprecation warnings but I'll leave this issue open until I've added a Tutorial for the new data API.

**Comment by philippjfr** [comment]
The [Columnar Data Tutorial](http://holoviews.org/Tutorials/Columnar_Data.html) is now live and I've cut most of the stuff out of the old Pandas Conversion tutorial. Will readd some stuff to Pandas Conversion to discuss dealing tall and wide data formats and how to convert between them a little bit but for now I'll close this issue.
