### ISSUE TITLE
holoviews.info

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#39]
```
hv.help(object, visualization=True)
```
Says:

To see the options info for one of these target specifications,
which are of the form {type}[.{group}[.{label}]], do holoviews.info({type}).

But hv.info does not exists

**Comment by philippjfr** [comment]
Fixed in https://github.com/ioam/holoviews/commit/8ed3b392ec595b4ec20b3dff387a5054540c20e5. hv.info is now just hv.help, which can be called with visualization=True to get the plot and style options or visualization=False (the default) for information about the Element type itself.

**Comment by jlstevens** [comment]
Thanks for point this out! This outdated message is now fixed.
