### ISSUE TITLE
Regression: part of data in HoloMap not plotted

### ISSUE THREAD

**Issue by maxalbert** [ioam/holoviews#394]
I'm not sure under which conditions exactly this issue occurs, but below is an example illustrating the problem. `git bisect` says that this regression was introduced in rev. b42241a7182ae5acb491c71afe57dc0c8aaa0158. The commit isn't big so I hope this should make it easy to debug. Please let me know if you need any further information.

Example code to reproduce the problem:
```python
%reload_ext holoviews.ipython
from holoviews import *

import holoviews as hv
import numpy as np
import itertools

phases = np.linspace(0, np.pi, 5)
freqs = [10, 15]
shifts = [0, 0.5]
exponents = [1, 2, 3, 4]

def make_curve(phase, freq, shift, exponent):
    x = np.linspace(-0.5, 0.5, 202)
    y = np.sin((freq * x**exponent + phase)) + shift
    return Curve(zip(x, y))

keys = itertools.product(phases, freqs, shifts, exponents)
items = [(key, make_curve(*key)) for key in keys]
hmap = HoloMap(items, kdims=['Phase', 'Frequency', 'Shift', 'Exponent'])
grid = hmap.overlay('Shift').grid(['Phase', 'Frequency'])
hmap.overlay('Shift').layout(['Frequency', 'Phase']).cols(5)
```

The correct output (before rev. b42241a7182ae5acb491c71afe57dc0c8aaa0158) looks like this.
![holoviews_bug_01_good](https://cloud.githubusercontent.com/assets/2692805/12131754/a294ec44-b415-11e5-8531-20edd801ce08.png)

The wrong output (after commit b42241a7182ae5acb491c71afe57dc0c8aaa0158) looks as follows.
![holoviews_bug_02_bad](https://cloud.githubusercontent.com/assets/2692805/12131759/acf20726-b415-11e5-933f-bfb2ea1e0aa0.png)

**Comment by philippjfr** [comment]
Thanks for reporting this. There's a bug in the optimized pandas implementation I implemented. I've got a fix I'll push in the morning.

**Comment by philippjfr** [comment]
Fixed as part of the commit referenced above. Closing.

**Comment by maxalbert** [comment]
Fantastic, thanks for the quick fix!

Would this be a good time to add tests for the underlying functions `util.ndmapping_groupby_pandas()` and `util.ndmapping_groupby_python()` which would at the same time act as regression tests for this issue?

**Comment by philippjfr** [comment]
I know, I was being lazy :) There are some existing tests for groupby testing both independently but there should definitely also be tests for this case. What wasn't being tested is a groupby on nested NdMapping types. I don't have much time at the moment but maybe we should schedule a release that's mostly about tightening up testing, e.g. v1.5 could be mostly about refactoring/testing/documenting. Then after that release we can be very strict about requiring unit tests for new feature and identified bugs.

**Comment by maxalbert** [comment]
Sounds good. And apologies, I didn't mean to put any extra pressure on you. I totally appreciate the huge amount of work you and @jlstevens are putting into Holoviews and am well impressed how you're managing it alongside doing your PhD. I just thought it's worth keeping this issue in mind to have a good candidate for an additional test, but I'm totally fine adding it at a later stage. (I'd submit a PR if I wasn't so pressed for time myself at the moment. ;-) )
