### ISSUE TITLE
Export archive directory name

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#395]
Currently, the hv.archive.export system writes the export to a directory with the name ```{notebook}```, which seems as a placeholder for the actual name of the notebook. This is troublesome if multiple notebooks are exported.

**Comment by jlstevens** [comment]
How are you running the notebook? Are you using ``hv.archive.auto()``?

The name ``{notebook}`` should only appear if I cannot establish the notebook name via javascript. Last time I checked, the Exporting tutorial worked I expected - maybe this is a bug?

**Comment by vascotenner** [comment]
I am using ```hv.archive.auto()```

**Comment by vascotenner** [comment]
It works well when I define:

```
import holoviews as hv
holoviews = hv
```

**Comment by jlstevens** [comment]
Thanks! That was just the information I needed to find the problem. 

It should now be fixed in 5969e9f2. Could you have another go to see if it is fixed?

**Comment by philippjfr** [comment]
> What happens?

``` 
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-10a749498bfe> in <module>()
      1 import sys
      2 if 'holoviews' not in sys.modules:
----> 3     raise ImportError('HoloViews does not seem to be imported')
      4 matches = [k for k,v in get_ipython().user_ns.items() # noqa (get_ipython)
      5    if not k.startswith('_') and v is sys.modules['holoviews']]

ImportError: HoloViews does not seem to be imported
```

**Comment by jlstevens** [comment]
@philippjfr Could you show me your ``sys.modules``? This is after importing holoviews, right?

**Comment by philippjfr** [comment]
Ah, I think we discussed this briefly on IM, it actually works fine for me. Not sure what the issue Vasco was having is.

**Comment by jlstevens** [comment]
@philippjfr I remember now. I've not been able to reproduce this error. @vascotenner Could you have a go and see if it works? If not, I would like to see what your ``sys.modules`` looks like...

**Comment by vascotenner** [comment]
It works fine now! It is strange that I cannot reproduce this behaviour with the same notebook that showed this behaviour in the past.

**Comment by jlstevens** [comment]
Glad it is now working!

If you encounter this issue again, you know what to do to help us debug it. :-)
