### ISSUE TITLE
Homepage example problem with Bokeh

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#397]
If I use ``hv.notebook_extension('matplotlib')``, Homepage.ipynb works in the latest master, but if I do ``hv.notebook_extension('bokeh')`` with Bokeh 0.10, only the first cell runs properly.  The second cell gives:

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
//anaconda/lib/python2.7/site-packages/IPython/core/formatters.pyc in __call__(self, obj)
    335                 pass
    336             else:
--> 337                 return printer(obj)
    338             # Finally look for special method names
    339             method = _safe_get_formatter_method(obj, self.print_method)

/Users/jbednar/holoviews/holoviews/ipython/display_hooks.pyc in pprint_display(obj)
    213     if not ip.display_formatter.formatters['text/plain'].pprint:
    214         return None
--> 215     return display(obj, raw=True)
    216 
    217 

/Users/jbednar/holoviews/holoviews/ipython/display_hooks.pyc in display(obj, raw, **kwargs)
    197         html = element_display(obj)
    198     elif isinstance(obj, (Layout, NdLayout, AdjointLayout)):
--> 199         html = layout_display(obj)
    200     elif isinstance(obj, (HoloMap, DynamicMap)):
    201         html = map_display(obj)

/Users/jbednar/holoviews/holoviews/ipython/display_hooks.pyc in wrapped(element)
    112         except Exception as e:
    113             StoreOptions.state(element, state=optstate)
--> 114             frame = inspect.trace()[-1]
    115             mod = inspect.getmodule(frame[0])
    116             module = (mod.__name__ if mod else frame[1]).split('.')[0]

IndexError: list index out of range

Out[2]:
:Layout
   .Overlay.I   :HoloMap   [Y]
      :Overlay
         .Image.I  :Image   [x,y]   (z)
         .Points.I :Points   [x,y]   (z)
   .Curve.I     :HoloMap   [Y]
      :Curve   [x]   (z)
   .Threshold.I :HoloMap   [Y]
      :Image   [x,y]   (z)
   .Overlay.II  :HoloMap   [Y]
      :Overlay
         .Image.I :Image   [x,y]   (z)
         .Level.I :NdOverlay   [Levels]
            :Contours   [x,y]   (z)
```

**Comment by jbednar** [comment]
A minor problem is that the hline's default color is black in Bokeh, which isn't a good match to our default Hot colormap.  Seems like if only using the defaults, they should work together...

**Comment by jlstevens** [comment]
Ok, what is happening here is an exception within an exception.

To elaborate, there was already an exception and then the idea of using ``inspect.trace`` if to only abbreviate tracebacks if they are generated by holoviews. The fact that there is no stack frame suggests that the original exception happened at a very high level (not quite sure how).

What I can do is wrap this code in an inner try/except too so you can see the original exception should the inspect code fail. I can push this fix now but this won't fix whatever the original problem was!

**Comment by jbednar** [comment]
Yes, that's what I thought too.  But also please try this example on your own system, to see if the original error is specific to my setup.

**Comment by jlstevens** [comment]
Ok, I can do that after lunch. In the meantime I have pushed 12e6d9c which means you should at least see the original exception type and message that was raised.

If you can try it again and report the exception, I'll have a go to see if I can reproduce the same error.

**Comment by philippjfr** [comment]
I see the bug, looking into it now.

```
 File "/Users/prudiger/topographica/external/holoviews/holoviews/plotting/bokeh/element.py", line 680, in update_frame
    subplot.update_frame(key, ranges, element=el, empty=empty)
TypeError: update_frame() got an unexpected keyword argument 'empty'
```

**Comment by philippjfr** [comment]
Just found it and fixed it in e91efdc066eee439246ab2afd24d8cf111348. Was a bug in plotting nested Overlays. Will close.

**Comment by jbednar** [comment]
Thanks!  The example now runs.  However, it doesn't work for me using Bokeh 0.10 at least; the slider has no effect.  The dots also are scaled strangely compared to the mpl version, and the legend is in the way:

![image](https://cloud.githubusercontent.com/assets/1695496/12201185/6debe13a-b5e8-11e5-8d16-2bcd9b415a3f.png)

(notice that the slider's value isn't being respected).

**Comment by philippjfr** [comment]
>However, it doesn't work for me using Bokeh 0.10 at least; the slider has no effect.

I must have broken something for 0.10, works fine for me in 0.11.

>The dots also are scaled strangely compared to the mpl version

Possible that matplotlib points are scaled by area while bokeh are scaled by radius, will mention it in #390.

>  and the legend is in the way:

I guess Paths and Polygons shouldn't have legends by default. It's also incredibly slow, Bokeh doesn't deal with large images very well.

**Comment by jbednar** [comment]
Ok, yes, the slider now does work if I switch to Bokeh 0.11.  But yes, it's deathly slow.  Having the point scaling differ between backends seems like a bug rather than a cosmetic difference, to me, because it's about data rather than styling.

**Comment by philippjfr** [comment]
>Having the point scaling differ between backends seems like a bug rather than a cosmetic difference, to me, because it's about data rather than styling.

I agree, it's simply an implementation difference between matplotlib and bokeh that I didn't catch before.

**Comment by philippjfr** [comment]
Bokeh and matplotlib plots now scale in the same way and apart from the extreme slowness of plotting the large image in bokeh the two implementations should now be nearly identical, i.e. the only difference is the default point size in bokeh and matplotlib.
