### ISSUE TITLE
hv.Text color

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#40]
I want to put a Text object with a different color than black. Is this possible? 
```
hv.help(hv.Text, visualization=True)
```
Does not give clues

**Comment by philippjfr** [comment]
We'd accidentally deleted style_opts for Annotation types. I just readded them in commit https://github.com/ioam/holoviews/commit/279ce2f3d5856819e7c43a2c4e421418729b353e, including a Text color option.

**Comment by jlstevens** [comment]
Right. This was left out as an oversight and has been re-added. It is now fixed and will be part of the new release that will be out very soon!
