### ISSUE TITLE
Problem with select widgets

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#403]
When I first use the City widget in the Exploring Data tutorial, it has no effect:
<img width="1123" alt="screen shot 2016-01-09 at 11 46 11 am" src="https://cloud.githubusercontent.com/assets/1695496/12217460/da38d0d0-b6c6-11e5-8f29-d1dfb9386071.png">

Notice that it says DC in the widget, but New York in the title, and the data shown is from New York.  The correct data is shown if I then drag the Date slider, so it looks like a problem with the selection widget failing to update the displayed plot.

I'm using matplotlib 1.4.3.

**Comment by jbednar** [comment]
Also, the tutorial suggests to try "R" and "P" to play the animation, but those only animate the slider, not the displayed plot.

**Comment by jbednar** [comment]
And clicking within the slider sometimes makes the plot update (the first time I click?), but then just moves the slider.  Dragging the slider works reliably, but clicking doesn't.

**Comment by stonebig** [comment]
trying the same notebook with Python 3.4.4 / Windows, I get:
````
surface_wind.info
````

````
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-b44694d72f09> in <module>()
----> 1 surface_wind.info

D:\WinPython\basedir34\buildQt5\winpython-3.4.4.amd64\python-3.4.4.amd64\lib\site-packages\holoviews\core\ndmapping.py in info(self)
    425                 dmin, dmax = self.range(d.name)
    426                 if d.value_format:
--> 427                     dmin, dmax = d.value_format(dmin), d.value_format(dmax)
    428                 info_str += '\t %s: %s...%s \n' % (str(d), dmin, dmax)
    429         print(info_str)

D:\WinPython\basedir34\buildQt5\winpython-3.4.4.amd64\python-3.4.4.amd64\lib\site-packages\matplotlib\dates.py in __call__(self, x, pos)
    483                              'plotting dates, e.g., with ax.xaxis_date()')
    484         dt = num2date(x, self.tz)
--> 485         return self.strftime(dt, self.fmt)
    486 
    487     def set_tzinfo(self, tz):

D:\WinPython\basedir34\buildQt5\winpython-3.4.4.amd64\python-3.4.4.amd64\lib\site-packages\matplotlib\dates.py in strftime(self, dt, fmt)
    587             # Note: in python 3.3 this is okay for years >= 1000,
    588             # refer to http://bugs.python.org/issue177742
--> 589             return cbook.unicode_safe(dt.strftime(fmt))
    590 
    591         return self.strftime_pre_1900(dt, fmt)

ValueError: Invalid format string
````

**Comment by jbednar** [comment]
On the same browser (Chrome on Mac OS X), the online web page http://holoviews.org/dev/Tutorials/Exploring_Data.html has none of the above problems, so it's presumably something about my non-browser libraries installed on this machine.  I'm running:

```
You are using Jupyter notebook.

The version of the notebook server is 4.0.6 and is running on:
Python 2.7.10 |Anaconda 2.2.0 (x86_64)| (default, Oct 19 2015, 18:31:17) 
[GCC 4.2.1 (Apple Inc. build 5577)]

Current Kernel Information:

Python 2.7.11 |Anaconda 2.2.0 (x86_64)| (default, Dec  6 2015, 18:57:58) 
Type "copyright", "credits" or "license" for more information.

IPython 4.0.0 -- An enhanced Interactive Python.
```

**Comment by jbednar** [comment]
I take that back: the online web page version does have *one* of the problems: the R and P buttons still only play the slider, not animating the actual plot.  The rest works on the online web page, i.e. clicking around and selecting seem to do the right thing reliably.

**Comment by jbednar** [comment]
@stonebig, does it work if you change ``'%h %d %Y %H:%M UTC'`` to ``u'%h %d %Y %H:%M UTC'``?

**Comment by stonebig** [comment]
where ?

**Comment by jbednar** [comment]
Where that string appears, early in the notebook (cell 4 for me).

**Comment by jbednar** [comment]
I've noticed that reproducing the problem with clicking in a slider is difficult -- sometimes it works, sometimes it doesn't.  The most reliable way to reproduce it that I saw is to click at the beginning and end of the range, repeatedly alternating between those two locations.  Often that will work the first couple of clicks, but soon the slider is the only thing that is changing, with the actual plot stuck until the slider gets dragged rather than clicked.

**Comment by stonebig** [comment]
Sorry, I was stupidly looking in the code instead of the notebook.

**Comment by jbednar** [comment]
*I'm* sorry for being so ambiguous. :-)  In any case it's just a guess; I don't have Python 3 on this machine to try it myself.

**Comment by stonebig** [comment]
the hint may be good, trying a few things on that

**Comment by stonebig** [comment]
I'm lost in the documentation, but this works:
````
value_format=md.DateFormatter('%b %d %Y %H:%M:%S')
````

**Comment by stonebig** [comment]
ok, so besides that I confirm your issue + is it normal that the "date" widget is showing a number `734801.0` ?

**Comment by stonebig** [comment]
more fun: the City change when I move the date

**Comment by jbednar** [comment]
I think this was @philippjfr's tutorial, so I'll let him think about what's going on with the value_format.  Meanwhile, thanks for confirming the other issue; I wonder why it's working on the  web site.  I think I've asked before why the date widget shows a number, but I can't remember the answer.  I haven't seen the City change when moving the date.

**Comment by stonebig** [comment]
1- change the city ... no city change on the left
2- move the date cursor ... the city name changes.

It all looks like some actions events are skipped.

**Comment by jbednar** [comment]
Ah, I have seen that then; yes, it doesn't realize the city has changed until the slider changes.  I was confused, and thought you were saying that the city *widget* changes.  Sounds like we're seeing the same behavior, then.

**Comment by stonebig** [comment]
great, you can safely upgrade to Python 3 ;-)

**Comment by stonebig** [comment]
if it works for @jbednar and gives the same result, I would suggest you replace 
`'%h %d %Y %H:%M UTC'`
per  
`'%b %d %Y %H:%M UTC'`

**Comment by philippjfr** [comment]
Sounds like the dropdown widget isn't triggering events correctly. I can replace the value format if you're not doing it in #401.

**Comment by philippjfr** [comment]
>ok, so besides that I confirm your issue + is it normal that the "date" widget is showing a number 734801.0 ?

Yea it's not ideal, I could format them as strings but strings + slider widget is currently not supported. I'm not hugely happy with this Tutorial for a number of reasons and would like to eventually replace it with something simpler.

**Comment by jbednar** [comment]
I changed the date format specifier as suggested by @stonebig in commit f7670ac9e7, though "man strftime" on my machine states that %h and %b are equivalent.  Hope this helps!

**Comment by stonebig** [comment]
thanks !

**Comment by jbednar** [comment]
In any case, even if this tutorial is replaced, I don't think any of the problems (other than the string format already changed) are to do with the tutorial, but with underlying issues with the software.

**Comment by philippjfr** [comment]
True, there's still some issue in the widgets.

**Comment by philippjfr** [comment]
Okay I found two bugs in the widgets, one was in escaping the dimension values correctly (9a48349745e1bec3781c03b5b0b2e223b3325f8f) the other was the 'R'(everse) and 'P'(lay) controls for the slider widget (f47d89a0aeb4d4eac912fd84e2d2e2644722b4e2). Could you confirm it works for you?

**Comment by jbednar** [comment]
Works great, thanks!  You don't by any chance know how to stop the font warning in the original image, do you?  I think we talked about this a year ago, but I thought it was taken care of, yet is happening again.  I'll close this issue, since that warning's not really part of this issue, but it would be good to fix it.

**Comment by stonebig** [comment]
hi,

on Windows7/Python3.5/Holoviews master of now:
- the example with cities works great now
- but simpler  examples of the same notebokk don't seem to work anymore:
````
%output size=300
combined_hurricane.grid(['Date'])[::2]
````

**Comment by philippjfr** [comment]
> but other "two widgets" or "one widget" examples of the same Exploring_Data notebook don't seem to work anymore: on this one the "Date" widget isn't movable anymore ("Frame" one is ok):

This is now expected behavior, widgets now detect hierarchical orderings between dimensions and update each other appropriately, i.e. in this case there is a one to one mapping between frame and date so each time you move the frame slider it updates the date. It's a bit confusing in this 1-to-1 case but gives much more desirable for one-to-many mappings.

>on this one the "Layer_Height" seems unmovable also:

Not sure what's happening here, it shouldn't be requesting any additional data from holoviews.org once the website is loaded.

**Comment by stonebig** [comment]
Maybe should you remove the "Date" widgets from this example, when 1-to-1, to avoid GUI confusion ?

Ok, I uinderstood my `false positive` error in "Layer_Height":
- I was trying to move to the middle,
- but there is only `full left`and `full right` positions.
==> Sorry for the noise on this one. (a little bit miss-guided by the GUI, but not a true bug)

**Comment by jbednar** [comment]
Thanks, Philipp; those seem like good improvements.  I agree with @stonebig that the Date slider should only appear when there is something for it to do, and should be either invisible for the 1:1 case or greyed out.  How hard that is I'm not sure.

Also, there appears to be a small bug in the logic -- in cell 25 of the current Exploring Data tutorial, if one first clicks on the Date slider (*before* clicking on the Frame slider), the Date slider is draggable yet does nothing to the plot.  After clicking on the Frame slider, the Date slider becomes undraggable, which does not seem like consistent behavior.

**Comment by philippjfr** [comment]
Thanks for pointing that out, luckily that sounds like an issue on the Python side, just need to send the correct initial values for the date slider.
