### ISSUE TITLE
feature request: provide options for bokeh 

### ISSUE THREAD

**Issue by stonebig** [ioam/holoviews#406]
These two options would be nice in Holoviews when using bokeh backend:
- mode="inline", to use bokeh in INLINE mode:
````
# maybe not the best way, but at least it works
from bokeh.resources import INLINE
output_notebook(resources=INLINE)
````
- webgl=False, to use Bokeh in not-webgl mode

Indeed:
- you may not wish to use external javascript, (or have just no internet where you are) 
- your running Client may not support webgl.

Bokeh defaults as of 0.11.0 are:
- webgl=False,
- mode="cdn" (was mode="inline" in 0.10.0 until https://github.com/bokeh/bokeh/commit/80538305a801222e5a3876526b87f26d8aad9a70 ).

No doubts `webgl=True` will be the default option of Bokeh in 1 year, but a lot of non-capable PCs (or Client sessions) are still around.

**Comment by philippjfr** [comment]
Yes, I agree we'll expose those options. ``webgl`` will likely just be a plot option on Element types, while the Bokeh include mode should probably be an option on the Renderer.

**Comment by jlstevens** [comment]
As we want to keep the interface consistent across backends for the output magic, I think we can have 'inline' as a renderer mode. I'm not sure about webgl, I suppose it is orthogonal to inline so a plot option would be ok.

**Comment by stonebig** [comment]
Wouldn't a general option be more practical (simpler for the users) as your first move ?

Webgl is either a problem, either a speed bonus, so a general option would fit well that scenario, isn't it ?

**Comment by jlstevens** [comment]
How about switching on webgl by default and supplying documentation on how to switch it off if necessary? 

Webgl will really help performance if available so it probably makes sense to enable by default if enough people are able to use it. Are there any good reasons to switch off webgl if you have access to it and can leave it on?

**Comment by philippjfr** [comment]
Setting the inline option has to happen in ``hv.notebook_extension`` as that's where the Bokeh extension is loaded. So I think an ``inline`` option there is reasonable:

```
hv.notebook_extension(bokeh=True, inline=True)
```

I also agree that a global toggle for WebGL would be sensible as when it is available you might as well always use it. Not sure where best to set that though, we could just have it on the renderer so you'd set:

```
hv.Store.renderers['bokeh'].webgl = False
```

**Comment by stonebig** [comment]
@jlstevens I would sugget you keep  `webgl=True` being the default:
- it would valorise Almar Klein (and others) big efforts on this,
- this is the option where Bokeh, and the Python stack, will shine the most compared to pure Javascript.

**Comment by jlstevens** [comment]
Note sure about the inline suggestion yet but the second suggestion seems fine:

```python
hv.Store.renderers['bokeh'].webgl = False
```

I just had to quickly check that the output magic propagates a fixed list of parameters over to the renderer.

**Comment by philippjfr** [comment]
Just implemented these suggestions in 56ecdc4f084d4fe312d9bf3c6179d3fb5e06ab27 and 9c1879def9ad28c5f8759445072c3fa3992073f9. Let me know if that works for you so I can close the issue.

**Comment by stonebig** [comment]
ok, will try

**Comment by philippjfr** [comment]
Perfect, thanks for confirming!
