### ISSUE TITLE
Slicing Paths

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#407]
Do Paths really support 2D slicing?  The Sampling Data tutorial says that a Path can be sliced along both dimensions, and subfigure C makes it look like it does:  

![image](https://cloud.githubusercontent.com/assets/1695496/12410616/9aa1f596-be3c-11e5-8d39-8b89b6724e4e.png)

But subfigure B makes it look like C is simply cropping the plot to a certain region, rather than actually slicing the data.  Is this intentional?

**Comment by philippjfr** [comment]
There is an existing issue about this (#181) and it's something I've thinking about for a while. The issue with slicing paths is that if your path goes outside the slice it will attempt to join up the points that fall within the slice, which isn't the correct behavior. What it could do is split the path at the point where your slice breaks it, which would at least avoid paths being wrongly joined up.

**Comment by jbednar** [comment]
I think that splitting up the path at slice boundaries is the only reasonable option, and that until that's done, this example should be removed from the tutorial, since the behavior demonstrated isn't actually correct.  I guess the most desirable thing would be to find the intersection of each path segment with the bounds of the sliced region, generating a new data point to mark that position and preserve all lines within the bounds, but that seems like a lot of work to do.  Instead, just breaking the Path at the slice boundary, preserving only the actual data points that are within the slice, seems well-defined and not that difficult.

**Comment by jlstevens** [comment]
> Instead, just breaking the Path at the slice boundary, preserving only the actual data points that are within the slice, seems well-defined and not that difficult.

This is indeed the simplest thing to do but unfortunately I think the results will generally look pretty bad unless we do the more advanced and difficult thing (adding points at the boundary). I agree this example should be removed from the tutorial but I'm still not quite sure what behavior would be best.

**Comment by jbednar** [comment]
I think that first the example should be removed (if we do nothing), but then it should either do the simplest thing or have an error, if no one is ready to do the more difficult one.  Just cropping to the same full set of data isn't slicing, it's cropping, and is a plotting operation rather than a semantic operation like slicing is.  After slicing I would think users would expect that they could get only the relevant data points, but right now the'll presumably get everything after the slice, which seems like a bug rather than a defensible choice.

**Comment by philippjfr** [comment]
We definitely can't raise an exception either because then slicing an overlay containing a path breaks. Creating synthetic data points by inserting it at the intersection doesn't seem the right thing to do to me unless we have a system to specify the type of interpolation a Paths object should use. I don't know what we can do but splitting the path seems to be the only defensible choice for now, but as you say it might look bad especially if the paths are only coarsely sampled.

**Comment by jbednar** [comment]
Isn't a Path always defined to have a linear interpolation, for us at the moment?  A Spline seems a bit more complicated, but when we plot a Path, isn't it always by connecting the dots linearly?  That seems very well defined to me.  In the future it would be great to support an option for some other form of interpolation, for all continuous objects (Paths, Curve, Image, Surface), with linear/bilinear and cubic/bicubic interpolation both for plotting and for indexing.  But we can worry about that when we come to it, right?

I'm not saying we need to do the interpolation for Paths slicing now; as it seems a bit tricky, but I do think it's well defined.  The underlying plotting code is doing it already, when it crops the Paths for display; we just haven't had to do that ourselves yet.

**Comment by jbednar** [comment]
I guess we should document somewhere that we are currently inconsistent about how we handle interpolation.  For Images, we do nearest-neighbor "interpolation" (i.e., none) for both plotting and for indexing, while for Paths and Curves we do linear interpolation for plotting, but nearest neighbor for indexing, and for Surface we do bilinear interpolation for plotting, and nearest neighbor for indexing.  I think that covers the various combinations...

**Comment by jlstevens** [comment]
We've opted to address this by fixing the notebook example by removing this example for now (see the PR above). As correct slicing of Paths is a general issue we will need to address eventually, I'm setting the milestone to v1.5.

**Comment by philippjfr** [comment]
The example has been removed and there is a general issue to discuss setting extents and how it relates to slicing https://github.com/ioam/holoviews/issues/566. Closing
