### ISSUE TITLE
BoxWisker line width

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#409]
At least with the Matplotlib backend, the BoxWhisker plots are very different in their default style compared to the other Elements:

![image](https://cloud.githubusercontent.com/assets/1695496/12423067/5dc0b3bc-be8f-11e5-8c76-14c47e760632.png)

Can the default outline width on these plot items be reduced to be more visually compatible with the other Elements, like Bars?

**Comment by philippjfr** [comment]
Somehow I didn't see that issue locally and only noticed it when building the website. Should be as simple as defining a default linewidth as a style option to BoxWhisker.

**Comment by jlstevens** [comment]
I believe this has been addressed in PR #442 (now merged). I'll close the issue now but I am happy to reopen it if we feel there is more to discuss.
