### ISSUE TITLE
Bokeh backend table editing broken?

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#414]
The plot on the left disappears as soon as I click on an item in the table:

![image](https://cloud.githubusercontent.com/assets/1695496/12463173/ad4927e0-bf87-11e5-92e9-6d0e2abd4c30.png)

Maybe an issue with bokeh 0.11?

**Comment by philippjfr** [comment]
Sounds like a bug in bokeh. Will have to confirm though.

**Comment by philippjfr** [comment]
Works again as of bokeh 0.12.3:

```
%%opts Layout [shared_datasource=True]
data = pd.DataFrame(np.random.rand(10,2), columns=['x', 'y'])
hv.Points(data) + hv.Table(data)
```
