### ISSUE TITLE
Redesigning Paths and Polygons

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#416]
This is something we've been talking about for a while now and with some of our upcoming projects it will take on even more importance. Our current datastructure to store multiple paths in a single object is simply a list of Nx2 arrays, which has several major shortcomings. The major issue is that it doesn't allow for flexibility in coloring different paths according to some value or category, instead we currently have to use an NdOverlay of Paths or Polygons, which has **huge** performance penalties both during plotting and when creating the datastructures.

In our discussion about a better data format we put together three proposals:

1) A simple Columns based format where each Path is separated by a NaN entry. This would probably be simplest but is space inefficient if each path is to be assigned a different category because you'd have we'd have to add an additional column for the value.

2) In #347 I laid out a proposal for a different format, where data the data maps between multi-dimensional keys and values that match the Columns data format, e.g. for a list of polygons for each country the data format would be {'Australia': {'x': xs, 'y': ys}, 'Austria': ...}, where {'x': xs, 'y': ys} is a valid definition for an individual Curve. This would be very similar to what NdOverlay provides but without the need to nest the data and provide a much more optimized alternative for storing and plotting collections of artists. The PR also lays out how this could be made into another interface, which would be used as the basis for NdMapping, and provide an alternative implementation using indexed dataframes.

3) Stick with the current list of Nx2 arrays format and store the path indexes and categories separately. The data would become a tuple of the list of arrays and a length N list of the categories.

The Bokeh team is currently looking to improve their representation for paths and polygons as well so it's also worth looking at https://github.com/bokeh/bokeh/issues/3708 for ideas. This issue won't be solved immediately but it's important that we come up with a plan as this will be essential for proper support for geographical chloropleth plots (as outlined in #392), which is something we'll want to tackle for our next project.

**Comment by philippjfr** [comment]
I'd like to move ahead on this in the near future and am now fairly convinced we should just go ahead with the first proposal, which is to store the data in a flat format separated by rows of NaNs. It means we can use the standard column based interfaces directly, avoiding the addition of another custom format. Datashader also uses this format and I think it's common enough in general. I don't think the inefficiency of duplicating entries justifies adding extra complexity and if you want to be more efficient you can always create an NdOverlay of paths. The benefits seems clear to me:

1) Simple flat format
2) Can use existing pandas/dict/array interfaces.
3) Can support arbitrary numbers of columns both to color by category and to provide support for color gradients
4) Supported by datashader

To maintain backwards compatibility I'd do two things:

a) Continue allowing lists of arrays (or equivalent) in the constructor which get concatenated into the merged NaN separated representation.
b) Provide a method to easily access the separated paths.

**Comment by philippjfr** [comment]
So I just had a new idea, I think the whole problem can be managed neatly with two additional features.

* Support for storing scalars instead of a whole column of repeating rows in the DictInterface.
* A MultiColumnInterface, which just stores lists of valid column datastructures (arrays, dataframes, column dicts).

The MultiColumnInterface would just use the appropriate interface for each element in the list. I think this works out rather neatly for one major reason, the default format for Path and Polygons would stay unchanged and there would be zero backward compatibility issues. Since the ArrayInterface is the default and it already understands the xy-coordinate arrays stored in a list on Path types it would just work as is.

By additionally allowing scalars as columns in the DictInterface we can also have an efficient format to represent contour levels. Finally, this will also extend to paths that also vary in some other dimensions because the column interfaces handle n-dimensional data, therefore we can even represent paths with varying hue for example.

**Comment by jlstevens** [comment]
I think I quite like this proposal:

1. ``DictInterface`` allows compression.
2. ``MultiColumnsInterface`` could be quite flexible.
3. Maintaining backwards compatibility which I agree is a really strong argument for this scheme.

The main thing we need to think about is how to select paths e.g when casting to other element types or for the data analysis methods. Also, ``NaN`` separation is one scheme for casting to a single ``ColumnInterface`` but might not be the only one...

**Comment by philippjfr** [comment]
This is now finally fully implemented. Closing.
