### ISSUE TITLE
Turn off dimension label for a specific HoloMap

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#425]
I have a `HoloMap` with custom labels:
<img width="784" alt="screen shot 2016-01-28 at 16 03 47" src="https://cloud.githubusercontent.com/assets/6897215/12648141/cd545ba2-c5d8-11e5-9376-f317a7ff7f19.png">

I would like to turn off the label that is automatically generated by the `HoloMap` for this specific one, not all by doing `hv.core.dimension.title_format = ''"`.

**Comment by jlstevens** [comment]
Just to be clear, is there any reason you cannot just disable the title in the plot options?

**Comment by philippjfr** [comment]
That's true, the main problem is when you want group and label to be shown and not the dimension values. The title_format plot option should ideally provide control over that.

**Comment by jlstevens** [comment]
Seems to me this should also be done via the plot option.

The way I see it, the use of ``dim_title`` (``dim_title = self._frame_title(key, separator=separator)``) in ``GenericElementPlot._format_title`` should also be controlled via the ``title_format`` plot option.

**Comment by philippjfr** [comment]
The title_format argument now accepts a new keyword, by default it is:

```
title_format='{group} {label}\n{dimensions}'
```

By removing the dimensions part you can disable dimensions being displayed.
