### ISSUE TITLE
Bug in options set with __call__ method

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#43]
Here is a very simple adaptation of the Histogram example from the Elements tutorial:

```python
import numpy as np
from holoviews import Histogram
np.random.seed(1)
data = [np.random.normal() for i in range(10000)]
frequencies, edges = np.histogram(data, 20)
Histogram(frequencies, edges)(plot={'show_grid':True})
```

Although only a plot option is set (to show the grid), the color of the Histogram changes to the horrible default blue (instead of our cyan color). Must be a bug in the options system...

**Comment by jlstevens** [comment]
Just in case the issues are related problems in the options system, I need to investigate why this doesn't work either:

```python
from holoviews import Overlay, Curve
data = [zip(range(10),range(10)), zip(range(5),range(5))]
Overlay([Curve(c) for c in data])(plot=dict(aspect='equal'))
```

**Comment by jlstevens** [comment]
To elaborate on the bug in the closed issue:

```python
Path([zip(range(10), range(10))]) + Path([zip(range(10), range(10))])(plot=dict(aspect='equal'))
```

The path on the left is the cyan from our default colour cycle whereas the one on the left is the default matplotlib blue. Setting the plot option seems to be masking the default style options.

**Comment by jlstevens** [comment]
Well, I have found the problem with the second issue reported above. The ``Overlay`` needs a full options specification as follows (unlike what is valid for Elements). For instance, this does work:

```python
from holoviews import Overlay, Curve
data = [zip(range(10),range(10)), zip(range(5),range(5))]
Overlay([Curve(c) for c in data])({'Curve.Curve':{'plot':{'show_grid':False}}})
```

The problem in this instance is mostly one of validation and generating more useful exception messages. I suppose that for everything other than ``Elements``, I should check if the kwarg keys contain ``'plot'`` and ``'style'`` in which case it is *not* the full specification required.

**Comment by jlstevens** [comment]
The solution to third issue mentioned is very similar to the solution to the second. This works:

```python
(Path([zip(range(10), range(10))]) 
+ Path([zip(range(10), range(10))]))({'Path.Path':{'plot':{'show_grid':True}}})
```

Notice the specification is now appropriate to the overlay and has extra parentheses around the two ``Path`` elements. The reason the two plots mentions were different was because of the incorrect brackets!

That said, the fact the rightmost plot was the default matplotlib blue *is* a bug which is exactly the same one that opens this issue. I'm looking into that now.

**Comment by philippjfr** [comment]
I'd make the following suggestion for the ``__call__`` method:

1. The plot, style, norm kwargs get applied to that Element/Container in particular.
2. All other keywords will be passed to traverse to find matching objects and apply a new style to. Since .traverse can match things by type and even with functions this will be a powerful new mechanism to select objects you want to apply the style to.

This has the added benefit that we only need one implementation for the __call__ method.

**Comment by jlstevens** [comment]
I think your first point makes a lot of sense and is something we can easily implement before the next release. Having a single implementation of ``__call__`` in one place would also be an improvement.

The second point is essentially what already happens in the options system though I need to check that the requirement for strings isn't being enforced somewhere else.

**Comment by philippjfr** [comment]
This already works:

```
def test(a):
    return type(a) == hv.Image and a.range('z')[1] > 1

hv.Layout([hv.Image(np.random.rand(25,25)* i, group='Test').hist()
           for i in range(4)])({test:{'style':{'cmap': 'jet'}}}).cols(2)
```

However matching by type seems to be broken:

```python
hv.Layout([hv.Image(np.random.rand(25,25)* i, group='Test').hist()
           for i in range(4)])({hv.Image:{'style':{'cmap': 'jet'}}}).cols(2)
...
/home/philippjfr/topographica/external/holoviews/holoviews/core/tree.pyc in __getitem__(self, identifier)
    169                 return self.__dict__[identifier]
    170             else:
--> 171                 raise KeyError(identifier)
    172         path_item = self
    173         for identifier in split_label:

KeyError: "<class 'holoviews"
```

**Comment by jlstevens** [comment]
Anyway, this issue should now be fixed and I have added 6 unit tests to ensure the behaviour stays correct in future (3d59902).

I will close this issue now and open a new one regarding the proposed improvements to the ``__call__`` method.
