### ISSUE TITLE
ioam.github.io/holoviews website is old

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#431]
The new website resides here: http://holoviews.org
The old website: http://ioam.github.io/holoviews/ should be forwarded automatically to the new address.

**Comment by jlstevens** [comment]
Thanks for pointing this out. We've moved our hosting for the main website and I think a simple redirect could fix this issue. Philipp?

**Comment by philippjfr** [comment]
Not even sure why it's still online, we deleted the gh-pages branch. A simple webdirect should be straightforward though.

**Comment by philippjfr** [comment]
Done, http://ioam.github.io/holoviews/ now redirects to http://holoviews.org/. Closing.
