### ISSUE TITLE
Errorbars

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#44]
Is it possible to create plots with errorbars, like plt.errorbar does?

**Comment by philippjfr** [comment]
This has been one of our main to-do items for a long time now. Now that someone has requested them I don't think there is any excuse not to do them. We'll discuss it today and get back to you.

**Comment by jbednar** [comment]
Yes, errorbars and stream plots are sorely needed, but note that they can currently be done using the Seaborn interface (see the Seaborn and Pandas tutorial).

**Comment by philippjfr** [comment]
Just added an ErrorBars Element type. I'll rebuild the Elements tutorial now so there should be an example up on the website fairly soon.

**Comment by philippjfr** [comment]
The example is now live and can be seen [here](http://ioam.github.io/holoviews/Tutorials/Elements#ErrorBars). Let us know if it works for you and if you need any modifications or have any suggestions. I'll close this issue now.

**Comment by jbednar** [comment]
Looks good.  In the new example, shouldn't it say vertical=False for the second plot?  They certainly seem to be horizontal.

I'm not sure that vertical or horizontal is really a plotting option -- isn't this a semantic issue, i.e. declaring that the data is ranging over either x or y?  And if so, shouldn't it be a parameter for the Element, not the Element's style options?  It doesn't seem like a stylistic choice, to me, but maybe I'm confused.

**Comment by philippjfr** [comment]
I clearly didn't pay enough attention when implementing it at first but I had already renamed it to horizontal last night. I also wondered what the best way of selecting x-error bars vs. y-error bars was, initially I had separate Elements for each just like we have VLine and HLine. I don't know what the best option is but a parameter on the Element is probably it, any suggestions for naming it?

**Comment by jbednar** [comment]
Maybe key_index, to specify which key_dimension the error values apply to?  By default, key_index=0, indicating that the error bars are for values specified on the x axis, and nearly everyone would use that default (resulting in vertical error bars).  But the error bars could apply to any key_dimension in principle, which this proposal would allow.
