### ISSUE TITLE
Make Elements tutorial backend-neutral?

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#445]
The [Bokeh Elements tutorial](http://holoviews.org/Tutorials/Bokeh_Elements.html) now has nice little check marks and x's in the table of contents, showing whether that element is working properly (cool!), but the page doesn't seem to explain what they are, presumably because this page is generated from the regular Elements tutorial, which doesn't have them.

Can we add such marks to all versions of this tutorial, with a paragraph explaining the marks and explaining that this page covers the XXX backend (along with links to the other available backends)?  In the future I expect that we'll have Elements only supported by Bokeh and not Matplotlib, and it would be nice to see those show up with a red X on the Matplotlib version of the page, just as we see on the Bokeh page.  There would then be no single "Elements" page, just Matplotlib_Elements, Bokeh_Elements, Plotly_Elements, etc. (though Elements could redirect to whichever of these we are recommending as the best default, currently Matplotlib).

We could even consider having the status marked with ![image](https://cloud.githubusercontent.com/assets/1695496/12824102/24f2f362-cb35-11e5-9b42-5dd69641897e.png) and ![image](https://cloud.githubusercontent.com/assets/1695496/12824054/ec01c5ce-cb34-11e5-8753-2125e921f328.png) instead of the checks and xs, so that at a glance we could see which backends support which plots (thereby being able to select Elements that are supported across backends, if desired).

**Comment by jbednar** [comment]
BTW, could you turn of the Bokeh axis ticks and bounding box for the cases where a Matplotlib object is (apparently) being substituted for the missing Bokeh equivalent, such as Surface and Scatter3D? That would make those substitutions be more usable in practice.

**Comment by jlstevens** [comment]
I do like the idea of the little backend icons. 

In addition, I've already proposed in Philipp's PR  that we always qualify the Elements tutorials with the backend as you suggest (Bokeh_Elements, Matplotlib_Elements). 

If I understand correctly, you propose that we could then use the same index table for all the element tutorials and all these tables would all show the little backend icons to show which backend support which elements?

Seems like a good suggestion to me!

**Comment by philippjfr** [comment]
>We could even consider having the status marked with image and image instead of the checks and xs, so that at a glance we could see which backends support which plots (thereby being able to select Elements that are supported across backends, if desired).

I think that's a great idea, we could have a general Elements index page, and each of the icons would take you to the example of the Element of the corresponding backend specific tutorial. 

>BTW, could you turn of the Bokeh axis ticks and bounding box for the cases where a Matplotlib object is (apparently) being substituted for the missing Bokeh equivalent, such as Surface and Scatter3D? That would make those substitutions be more usable in practice.

Oops meant to delete those. They're not particularly usable in any case.

**Comment by jlstevens** [comment]
>  ... we could have a general Elements index page

That is what I was wondering. Would such a plage have no plots at all? 

You might not know what some of the elements look like from the name alone so you won't know if that element is actually what you want. This is why I think all the element tutorials should have the same (complete) index with all the little icons. 

Clicking the text itself will take you to an example on that page. The same thing would happen if you click on the little icon matching the backend you are currently viewing. Clicking on the icon for a different backend would then jump you to the right place in the appropriate elements notebook.

**Comment by philippjfr** [comment]
True, having it on each one is probably best.

**Comment by jbednar** [comment]
Yes, I was proposing to have the same index on all such pages, and sure, clicking on the logo may as well take you to the corresponding element on the appropriate page.  

I agree that a bare index wouldn't be very usable.  If we were ambitious we could augment our textual table of contents with a tiny sample plot of each Element, to address Jean-Luc's point that the name alone doesn't necessarily convey what it is, but that seems like a pain to set up. 

Having the matplotlib equivalents show up is a bit surprising, but it's kind of cool as well, so keeping or removing those seems equally good to me.

**Comment by jlstevens** [comment]
> If we were ambitious we could augment our textual table of contents with a tiny sample plot of each Element ... but that seems like a pain to set up

It would be a pain and I don't think it would be worth it.

The advantage of the normal element tutorial format is you can skim through to see all the plot types till you spot what you want. You'll see the element name in the headings and then you can easily jump to the top of the page to view the index which then conveys which backends support that element.

The way I see it, just having the little icons as links marking the available backends would be really useful and all we really need.

**Comment by jbednar** [comment]
I agree; having them all on one page is crucial for scrolling through to find the one you want.  Having them all on one screen at the top (linking down into the page) would be good too, for the same reason, but I agree that it would be too painful.

**Comment by jlstevens** [comment]
I've had a quick go at adding these icons. Unfortunately, I'm having trouble adding it to the bootstrap 'description list' that is currently used for the index. I've tried putting the image in various places in the HTML and it always jumps to the next line. Any suggestions?

**Comment by philippjfr** [comment]
The Element Tutorial will now be removed as we now have individual Element notebooks linking between each other.
