### ISSUE TITLE
Tutorial RGB broken

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#452]
I try to follow the steps about splitting channels from a RGB object, as shown in the tutorial: http://holoviews.org/Tutorials/Introduction.html

```python
parrot = hv.RGB.load_image('/home/a/src/holoviews/doc/assets/macaw.png', array=True)
rgb_parrot = hv.RGB(parrot, label='Macaw')
rgb_parrot[:,:,'G']
```

```
/home/a/src/holoviews/holoviews/element/raster.pyc in __getitem__(self, coords)
    769                 coords = coords[:self.ndims]
    770             else:
--> 771                 raise KeyError("Only empty value slices currently supported in RGB")
    772         return super(RGB, self).__getitem__(coords)
    773 

KeyError: 'Only empty value slices currently supported in RGB'
```

**Comment by jlstevens** [comment]
Thanks for reporting this. I'll look into it.

**Comment by jlstevens** [comment]
This exact example works for me just fine.

I suspect it might be this line:

```python
channels = [el for el in values if isinstance(el, (str, Dimension))]
```

Is 'G' unicode? Try changing line 755 of ``holoviews/element/raster.py`` to:

```python
channels = [el for el in values if isinstance(el, (str, unicode, Dimension))]
```

Does that work? I suspect this is something I should be doing anyway....

**Comment by jlstevens** [comment]
I pushed this change in ca8645c as part of #455. I *believe* that will resolve this issue so I'll close this issue. If it doesn't, do say and I'll reopen the issue.
