### ISSUE TITLE
Website broken for output of .dimensions()

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#458]
![image](https://cloud.githubusercontent.com/assets/1695496/12857333/2b0a8bf4-cc0f-11e5-92e5-3142e68f474f.png)

**Comment by jlstevens** [comment]
Odd. I assume this is to do with notebook building as I don't see this issue running in the live notebook.

We could manually edit the HTML to fix it for the release version of the website but that isn't a suitable long term solution.

**Comment by jbednar** [comment]
Isn't there a script to patch notebook links?  Seems like this fix could go in there; it's unrelated but could use the same mechanism.

**Comment by jlstevens** [comment]
Ah, ``&apos;`` which is for an apostrophe - pretty obvious now I look at it.

Could be a search and replace in the link processing script unless we actually need `&apos;` in our HTML code somewhere?

**Comment by philippjfr** [comment]
Turns out ``&apos;`` isn't valid HTML, it's an XML character. For now I've added a one line JS fix to replace them. Closing.
