### ISSUE TITLE
Dot coloring broken?

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#467]
I made a notebook with a copy of HoloViews last updated yesterday:

https://anaconda.org/jbednar/plotting_problems/notebook

but today the behavior is different:

![image](https://cloud.githubusercontent.com/assets/1695496/12879138/78d103b8-cdf4-11e5-9455-d788da282acb.png)

I.e., the "c" dimension value used to control the color, but it doesn't any more. It looks like the problem started in 954013933d86c0b94db, but I don't see anything there that should have an effect...

**Comment by philippjfr** [comment]
Thanks, definite bug.

**Comment by philippjfr** [comment]
Fixed in #472. Closing.
