### ISSUE TITLE
Out of range select on DynamicMap raises no error

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#482]
Defining a dynamic map as follows:

``` python
x,y = np.mgrid[-50:51, -50:51] * 0.1
def sine_image(phase, freq):
    return hv.Image(np.sin(phase + (freq*x**2+freq*y**2)))

dmap = hv.DynamicMap(sine_image, kdims=[hv.Dimension('phase',range=(0, np.pi)),
                                 hv.Dimension('frequency', range=(0.01,np.pi))])
```

And using `select` for an out-of-range value (frequency zero):

``` python
dmap.select(phase=0.2334, frequency=0)
```

Doesn't raise an error but simply returns the dynamic map.

**Comment by philippjfr** [comment]
This now raises a ``StopIteration`` error:

```
StopIteration: Key value 0 below lower bound 0.01
```

Not convinced that's correct, I think it should be a ``KeyError``.

**Comment by jlstevens** [comment]
I agree a ``KeyError`` with a good message would be more appropriate.
