### ISSUE TITLE
Should notebook tutorials be listed alphabetically?

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#484]
We have quite a few notebook tutorials now and I occasionally get annoyed that they aren't listed alphabetically in the sidebar under the 'Tutorials' section.

Is this just me or would putting them into alphabetical order make sense?

**Comment by jbednar** [comment]
Well, they are in the order they are covered on the Tutorials page.  In turn, that page is ordered by how we suggest people use them (except that Elements and Containers are at the end, but referred to by everything else).  I guess it would be ok to make the sidebar be alphabetical, but I would want to keep the Tutorials page organized in terms of a logical progression, as much as is feasible.

**Comment by jlstevens** [comment]
I agree the tutorial page should present them in a logical order. The thing about the sidebar is that there are so many notebooks, every time I want to specific one I have to scan the whole list.

I guess I am very familiar with all the notebooks and their names which means I know what I am looking for unlike a new user. I guess numbering to make it clear there is an ordering would be another solution? The problem is that I think there is a fuzzy ordering between the notebooks and not really a strict one!

**Comment by philippjfr** [comment]
Tutorials are now being mostly replaced by guides where we do have a clear order. Closing.
