### ISSUE TITLE
DynamicMap widgets affect _ variable

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#489]
After displaying some DynamicMaps, I _sometimes_ find that `_` which normally refers to the last executed value in IPython has an odd value:

``` python
>>> _
"<img src='data:image/png;base64,iVBORw0KGgoAAAA...
```

This doesn't seem to happen all the time though...

**Comment by jlstevens** [comment]
Apparently this happens after moving the sliders and I think it is to do with how Javascript is communicating to Python (via ``kernel.execute`` I presume).

**Comment by philippjfr** [comment]
No longer true, we don't use ``kernel.execute`` anymore.
