### ISSUE TITLE
Inconsistent behavior for option setting

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#495]
If I set up a plot in cell 2:

![image](https://cloud.githubusercontent.com/assets/1695496/12958626/338da17a-cff8-11e5-910a-8ab45f4b1997.png)

and modify it using ``%%opts`` in cell 3, it works fine:

![image](https://cloud.githubusercontent.com/assets/1695496/12958570/eb553a58-cff7-11e5-96ef-d13872a3c3dd.png)

but using the call interface in cell 4 drops the columns arrangement, and doesn't seem to apply the option:

![image](https://cloud.githubusercontent.com/assets/1695496/12958600/0e164410-cff8-11e5-9c25-63d237f7d988.png)

This doesn't *seem* correct...

Note that cell 3 isn't required here for the problem to occur, it just shows what I expected it to do.
This is for the latest revision on github, 378b29c26cf59175b.

**Comment by jbednar** [comment]
Code:

import numpy as np
import holoviews as hv
hv.notebook_extension()

pts = hv.Points((np.random.normal(size=500),np.random.normal(size=500)))
quartet = (pts + pts + pts + pts).cols(2)
quartet

%%opts Points (alpha=0.1)
quartet

quartet(style=dict(alpha=0.8))

**Comment by jbednar** [comment]
Ah, it works if I give the style info directly to the Points object:

![image](https://cloud.githubusercontent.com/assets/1695496/12958792/0124b0d8-cff9-11e5-9534-f96d6bea31ce.png)

I guess that makes sense, but in that case I don't know how to change the style for an existing object using the Python (non-magic) interface.  And I don't know why the cols() disappeared.

**Comment by philippjfr** [comment]
To style nested objects you have to tell the ``__call__`` which objects you want to customize, to do that use either of these syntaxes:

```python
quartet({'Points': {'style': dict(alpha=0.1)}})
quartet(style={'Points': dict(alpha=0.1)})
```

I guess the Options tutorial should actually document this, currently it only describes the context manager, which has a similar signature. 

>And I don't know why the cols() disappeared.

I agree that shouldn't be the case, ``_cols`` isn't being inherited in clone. Should be a separate issue though.

**Comment by jbednar** [comment]
Ugh, that's a horrible syntax, either way.  Yes, the Options tutorial should mention that.

**Comment by philippjfr** [comment]
That's why the options magic is so convenient. The only other option I see is to allow strings just like in the magic, which are fed into the parser, then you could do:

```
quartet('Points (alpha=1)')
```

Perhaps convenient, bit weird though.

**Comment by jlstevens** [comment]
> The only other option I see is to allow strings just like in the magic, which are fed into the parser...

That is possible but does require pyparsing to be installed. I agree that the syntax is horrible but honestly, we have investigated lots of formats and I've never seen a better suggestion. 

Parsing a string has pros and cons: on one hand it is a syntax that is identical to the one in the magic. On the other hand, using Python literals lets Python validate the input syntax....

**Comment by jbednar** [comment]
Never mind, as long as the tutorial gets updated to clarify...

**Comment by philippjfr** [comment]
Added in the PR above. Closing.
