### ISSUE TITLE
Testing DynamicMaps

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#498]
This includes testing the DynamicMap tutorial which needs reference data.

The general issue is that DynamicMaps tend to be empty, leaving nothing to test. And to generate data, you need a live server making the issue even more complicated...

**Comment by philippjfr** [comment]
Anything else we want here? We now have a fair number of unit tests.

**Comment by jlstevens** [comment]
> We now have a fair number of unit tests.

True but that isn't the same as testing dynamic maps in the notebook. I'm still not sure what we can do about this, or whether there is anything sane we *can* do about this...

**Comment by philippjfr** [comment]
Not sure what "testing dynamic maps in the notebook" adds over unit tests or were you talking about testing the widget code with DynamicMaps? Otherwise they don't behave any differently in a notebook and a unit test so I don't see what notebook tests would add.

**Comment by jlstevens** [comment]
> Otherwise they don't behave any differently in a notebook and a unit test so I don't see what notebook tests would add.

Unless we mirror the code in the notebooks against the unit tests (painful!) we have no way of knowing whether the dynamicmaps in the notebooks are behaving properly. That said, I don't mind seeing this issue closed as 'wontfix' as I think the problem is too difficult to solve properly.
