### ISSUE TITLE
Remove old web site

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#500]
This bogus one still shows up in searches; maybe make it redirect?

http://ioam.github.io/holoviews/Tutorials/Elements

**Comment by philippjfr** [comment]
Ugh, doozy keeps pushing it. Will have to disable holoviews building there.

**Comment by jbednar** [comment]
Good old doozy can't be stopped. :-)

**Comment by philippjfr** [comment]
I've killed the slave on Doozy because most of the other builds were failing too. We'll need to decide what to do about building the other libraries again at some point as currently they were mostly failing anyway. It would also be nice if we could update the link on pypi to holoviews.org.

**Comment by jlstevens** [comment]
> It would also be nice if we could update the link on pypi to holoviews.org.

Done - https://pypi.python.org/pypi/holoviews
