### ISSUE TITLE
HoloMap of Overlay of hv.Surface

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#504]
```
energies = np.linspace(-np.pi, np.pi, 30 * 30).reshape((30, 30))**2
plot = lambda i: holoviews.Surface(i*energies) * holoviews.Surface(-i*energies)
```

then running:
```
plot(1) + plot(4)
```
gives
![download 1](https://cloud.githubusercontent.com/assets/6897215/13008572/5fa893d2-d197-11e5-9e51-8d5147573965.png)

but
```
holoviews.HoloMap({i: plot(i) for i in range(10)})
```
gives
![download](https://cloud.githubusercontent.com/assets/6897215/13008578/632a1dc8-d197-11e5-9d48-884c232406fb.png)

I would think `holoviews.HoloMap({i: plot(i) for i in range(10)}).collate()` would do the job, but it doesn't.

**Comment by philippjfr** [comment]
Fixed in #505. Closing.
