### ISSUE TITLE
Reraise plotting exceptions with original traceback 

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#507]
Currently when a plotting call raises an exception the IPython display hook wrapper catches it and reraises the exception, but with a new traceback relative to where the error was reraised (which is not very helpful). The error should be reraised with the original traceback as described in this [StackOverflow post](http://stackoverflow.com/questions/8760267/re-raise-python-exception-and-preserve-stack-trace).

**Comment by jlstevens** [comment]
Yes, I agree the traceback is wrong and it shouldn't be hard to fix using the approach you link to.

**Comment by philippjfr** [comment]
I tested that approach and it didn't work for me, but it's definitely possible.

**Comment by jlstevens** [comment]
This has been addressed in the PR mentioned above. Closing.
