### ISSUE TITLE
Controlling specificity when setting options via __call__

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#508]
Currently when setting a plot, style or normalization option via `__call__` it makes that style as specific as possible, i.e. setting the style for the particular group and label of the object you're setting it on. This means that when you in any way relabel this object that style no longer applies.

A simple example is this:

``` python
surface = hv.Surface(np.random.rand(20,20), group='Test', label='A')
styled = surface(style=dict(cmap='Greens'))
relabeled = styled.relabel(group='Test', label='B')
```

The styling call here is basically equivalent to:

``` python
%%opts Surface.Test.B (cmap='Greens')
```

so once you apply the relabeling this style no longer applies. The current syntax to avoid this behavior is to set the `type[.group[.label]]` specification explicitly like this:

``` python
surface(style={'Surface': dict(cmap='Greens')})
```

It may be worth considering having a simpler way to control the specificity of the call with an extra argument, e.g.:

``` python
surface(style=dict(cmap='Greens'), specific=False)
```

**Comment by jlstevens** [comment]
Alternatively, you can imagine that ``relabel`` does the work necessary to find what options applied to the old names and remaps them appropriately. Probably a lot more work to implement but worth considering...

**Comment by philippjfr** [comment]
Don't think that's a good idea, you should have easy control over what you specify not rely on it to magically remap things for you in the background. In fact sometimes you'll want to relabel things precisely because that means the style no longer applies so remapping things automatically would be counter-productive.

Maybe the ``surface(style={'Surface': dict(cmap='Greens')})`` syntax is already the best way to achieve specificity but I wanted to brainstorm for some alternatives.

**Comment by jbednar** [comment]
It doesn't seem like a single boolean ``specific`` would be sufficient, wouldn't you want to decide between setting for that particular type.group.label, or type.group, or type?  That seems like three choices, not a binary choice.

**Comment by jlstevens** [comment]
I'm rather conflicted about this proposal and I'm not sure what to think. Making it as specific as possible by default always seemed to me to be the safest behavior. That said, as has been pointed out, this doesn't work well if you use relabel. Frankly relabel is really the problem as we assume group and label are constant (these parameters are declared as such) and relabel violates this. One simple solution here is to say that you need to style after relabelling though this is rather restrictive (and ``relabel`` is indeed useful).

The specific flag would complicate processing of kwargs further so I'm not sure how much more we can torture this style specification syntax - I've lost count of how many formats we already support!

As the following syntax is explicit and works already, I think any alternative needs to be very compelling before we add more complexity here:

```python
surface(style={'Surface': dict(cmap='Greens')})
```

I am open to improving the syntax but we would need to see a very convincing alternative before it is worth implementing!

**Comment by philippjfr** [comment]
>It doesn't seem like a single boolean specific would be sufficient, wouldn't you want to decide between setting for that particular type.group.label, or type.group, or type?

Agreed, I'm no longer in favor of this proposal.

>Making it as specific as possible by default always seemed to me to be the safest behavior.

Bit conflicted on this as well, but fundamentally there's nothing "safer" about making it restrictive by default, in fact it kind of makes the most sense to me, if you want to be specific, be explicit. I can't really think of any case where the unspecific thing would cause weird behavior because the id makes it specific to that particular object anyway. The only time the behavior would be different is when relabeling the object.

>Frankly relabel is really the problem as we assume group and label are constant (these parameters are declared as such) and relabel violates this.

Huh, relabel uses clone so it doesn't violate that at all, it creates a new object.

Anyway I opened this issue more for discussion than implementing any concrete proposals right away. The current behavior confused Bas (and me as well, until I thought about it a bit).

**Comment by jlstevens** [comment]
> Huh, relabel uses clone so it doesn't violate that at all, it creates a new object.

True. I got confused! 

As you say, it is worth keeping this issue open while we consider what (if anything) we want to do.

**Comment by philippjfr** [comment]
Going to close this, don't like the suggestion and we have other improvements for setting options in the works.
