### ISSUE TITLE
GridMatrix is not documented in tutorials

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#513]
Presumably it should at least be mentioned in Containers?

**Comment by philippjfr** [comment]
That's true, it is used once in the Bokeh Backend Tutorial but we can provide a simple example in Containers. While there's a number of ways it can be used it's usually constructed using the ``gridmatrix`` operation, which plots all dimensions values in an object against one another other.

**Comment by jlstevens** [comment]
If it is mentioned in containers, it should also be mentioned in the appropriate place in the nesting diagram.

**Comment by philippjfr** [comment]
Sure, as you say it just occupies the same space as a regular GridSpace.

**Comment by philippjfr** [comment]
PR merged. Closing
