### ISSUE TITLE
rc vs xy in tutorials

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#516]
Several of the examples in Elements seem to have their axes swapped, which is only ok because they happen to have symmetric patterns.  E.g. it looks ok:

![image](https://cloud.githubusercontent.com/assets/1695496/13187137/25d04e70-d70f-11e5-82b8-6ce3544bc4d8.png)

but it's not actually plotting what it says, since if you try to make it vary only in x, it's actually varying in y:

![image](https://cloud.githubusercontent.com/assets/1695496/13187208/7a1e2100-d70f-11e5-8b2c-547066989e5d.png)

Because it's also symmetric about y, it might also be flipped there, either here or in Image; not sure.  Seems like we (a) need to write y,x when using mgrid, (b) may need to flip y, and (c) should be using an example pattern that has no symmetries, to make things like this obvious.

**Comment by jbednar** [comment]
Plus isn't the Image version of this example lying about the ranges?

![image](https://cloud.githubusercontent.com/assets/1695496/13187462/c064dec8-d710-11e5-9e9a-22c427d1826b.png)

Seems like it's evaluating the function over the range (-5,5), but the bounds claim to be over the range -1,1.

**Comment by jlstevens** [comment]
For the latter bit, the ``np.mgrid`` call generates the values you evaluate ``sin`` on which ranges from -5 to 5. You then need to tell holoviews your bounds and that can be anything you want. 

If when you say it is 'lying about the ranges' you mean that technically the bounds should be ``(-5,-5,5,5)`` then yes I agree that should be changed to be more sensible. I don't think it is 'lying' because nothing is incorrect as such (we haven't really given these sine rings meaning and there are no units on the axes) but I do agree there is a more sensible/intuitive set of bounds we should probably be using instead.

**Comment by philippjfr** [comment]
>but it's not actually plotting what it says, since if you try to make it vary only in x, it's actually varying in y:

Yea, the return arguments from mgrid correspond to y, x not x, y, simply need to invert them.

**Comment by jbednar** [comment]
Well, as a plot of `hv.Image(np.sin(x**2+y**2))` it's a lie, because the value shown at e.g. -1,-1 in the plot is not the value of `sin((-1)**2,(-1)**2)`, but `sin((-5)**2,(-5)**2)`.  

> Yea, the return arguments from mgrid correspond to y, x not x, y, simply need to invert them.

but doesn't y also need to be flipped, for Image?

**Comment by philippjfr** [comment]
>but doesn't y also need to be flipped, for Image?

Yes, you're right.

**Comment by jlstevens** [comment]
> Well, as a plot of hv.Image(np.sin(x**2+y**2)) it's a lie, because the value shown at e.g. -1,-1 in the plot is not the value of sin((-1)**2,(-1)**2), but sin((-5)**2,(-5)**2).

That is true but if you think of it as an image in the general sense (e.g a very odd, boring photograph!) then the bounds don't have to mean anything. But yes, in this instance we should change the bounds to match because it will be less confusing that way.

**Comment by jbednar** [comment]
Ok, can one of you make these changes?  They'll presumably change the tests, which I'm not prepared to juggle today, but they're very confusing, so I've held off on the announcement for now.

**Comment by jlstevens** [comment]
Sure. I'll open a PR shortly.

**Comment by jlstevens** [comment]
The PR has now been merged! I'll close the issue now but feel free to add any more comments if you have any.
