### ISSUE TITLE
Return type handling for DynamicMaps

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#522]
The renderer should check if a DynamicMap returns Layout or Grid types and provide a helpful error message on how to compose DynamicMaps.

**Comment by jlstevens** [comment]
Good suggestion but can't it be done at the ``DynamicMap`` level? At least a ``Layout`` is not something that should be returned from the callback regardless of the backend/plotting system.

**Comment by philippjfr** [comment]
Yes absolutely although technically you could create a DynamicMap which returns Layouts, sample it, cast it to a HoloMap and collate.

**Comment by philippjfr** [comment]
Closing this, Layouts and grids are allowed now via collation.

**Comment by jbednar** [comment]
Great! Is this documented somewhere in an example?

**Comment by jlstevens** [comment]
As Jim says, this need to be documented. Do we have a general issue for outstanding docs tasks we could add this to?
