### ISSUE TITLE
Links to the sections of the reference manual

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#525]
One issue with writing developer documentation is that links to the reference manual don't work properly.

For instance, getting the link for ``Cycle`` (these links are available by clicking on the little icon when you hover over entries) will jump to that entry but not expand it:

http://holoviews.org/Reference_Manual/holoviews.plotting.html#holoviews.plotting.Cycle

Linking to methods is worse because you don't jump anywhere at all. For instance:

http://holoviews.org/Reference_Manual/holoviews.plotting.html#holoviews.plotting.renderer.Renderer.export_widgets

Note that these links work fine if you stay on the page and manually expand the relevant sections. It would be really helpful if it could also work with external links!

**Comment by philippjfr** [comment]
Isn't the correct thing to use a proper linking sphinxdoc referencing mechanism. Something like :class:`holoviews.core.options.Cycle`. Note sure if that works now but it should.

**Comment by jlstevens** [comment]
That is exactly what I used to discover this issue. Such a sphinx directive translates into the sort of link example I gave above.

**Comment by philippjfr** [comment]
I've implemented some javascript to ensure that the section gets expanded when you link to it both the class:

http://dev.holoviews.org/Reference_Manual/holoviews.core.html#holoviews.core.HoloMap

and the method:

http://dev.holoviews.org/Reference_Manual/holoviews.core.html#holoviews.core.HoloMap.clone

now work. Closing.

**Comment by philippjfr** [comment]
Functions still don't work. Will look at that later.

**Comment by philippjfr** [comment]
Nevermind, just realized functions aren't collapsed anyway.
