### ISSUE TITLE
Columns iterator and contains methods

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#540]
Currently the Columns iterator and contains interfaces aren't well defined. My proposal would be that Elements in general support checking whether an object contains a particular by dimension by implementing the `__contains__` method, this makes sense because we already support accessing the dimension values for a particular dimension via `element[dimension]`. Additionally I would propose that `Columns` representing a list of rows should iterate over the each row as a tuple.

**Comment by philippjfr** [comment]
I'd very much like to implementing ``__contains__`` for the objects to allow checking whether an object contains a dimension. This is consistent with the way pandas DataFrames and xarray Datasets work and is a very common operation. I'll assign this to v1.10 because it's a trivial thing to implement, if someone objects this can be closed.

**Comment by jlstevens** [comment]
So you could do things like ``'time' in histogram``?

It seems a little odd to me, I would expect to use ``__contains__`` to ask something about the data values, not the dimensions. On the other hand, I do recognize two nice things about this suggestion 1. it is simple 2. it applies in the same way to all holoviews elements/containers.

**Comment by philippjfr** [comment]
>It seems a little odd to me, I would expect to use __contains__ to ask something about the data values, not the dimensions.

Right, that's the other possibility but I see several issues with this:

1. It's not clear what it would refer to, a particular dimension, all key dimensions, the first value dimension? 

2. Testing array membership is not entirely straightforward due to float precision issues, which limits its usefulness.

3. It's not really that commonly useful in general. I can't personally recall when I've wanted to test array membership outside the context of selection (which we already handle more simply).

4. It's not consistent with pd.DataFrame or xr.Dataset (and they likely made the same considerations I laid out in 1-3).

**Comment by jlstevens** [comment]
I agree with all that and although I find it odd personally (compared to say ``__contains__`` for lists and numpy arrays), the fact that pandas also supports these semantics makes your proposal the easiest thing to do for ``__contains__`` in HoloViews.
