### ISSUE TITLE
Columns row/column based indexing API

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#541]
As we further broaden the scope of the Columns interfaces and provide support for various out-of-memory data backends it's becoming clear that the current interface isn't quite sufficient. When accessing a Columns datastructure it is sometimes necessary to do so by index, e.g. when displaying a Table and only a small subset of rows should be shown or when trying to randomly sampling from the data. Currently this requires each column to be loaded into memory in its entirety to index into them. Instead there should be an API on the Columns class to slice the row and column directly. I could imagine something like this `table.cells[0:10, 0:2]`, where cells is a small object that allows slicing by index.

**Comment by jbednar** [comment]
Would this API provide Raster-like access for Image and RGB objects?

**Comment by philippjfr** [comment]
That would also benefit from an interface to slice into the array by index but I'm not sure if the two interfaces should be shared.

**Comment by jbednar** [comment]
Seems like they ought to have the same spelling, at least...

**Comment by philippjfr** [comment]
Tabular and nd-array indexing interfaces have been added in https://github.com/ioam/holoviews/pull/1435.
