### ISSUE TITLE
Testing on Travis pinned to matplotlib 1.4.3 and numpy 1.9.3

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#545]
Right now if the numpy version is unpinned in ``.travis.yml``, you end up with numpy 1.10 and matplotlib 1.5.1 which unfortunately don't seem to play nicely together, resulting in this error:

```
ImportError: numpy.core.multiarray failed to import
```

By pinning numpy to 1.9.3, you end up with matplotlib 1.4 which works again. This issue is a reminder to unpin numpy as soon as we can so we can test using the latest numpy and matplotlib versions.

**Comment by philippjfr** [comment]
This has been fixed. Closing.
