### ISSUE TITLE
Plotting np.nan values broke in master.

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#55]
The last version at PyPi still works, but I just updated to the version on Github and suddenly plotting my data stopped working.

```
data_Image = np.random.randn(100,100)
data_Image[0,0] = np.nan
hv.Image(data_Image)
```
Before update:
![screen shot 2015-05-07 at 22 47 50](https://cloud.githubusercontent.com/assets/6897215/7525620/35ab5010-f50b-11e4-8827-6809cddb0ba0.png)

After (master):
![screen shot 2015-05-07 at 22 46 48](https://cloud.githubusercontent.com/assets/6897215/7525624/3bd45838-f50b-11e4-92e3-df7079aeccd4.png)

**Comment by philippjfr** [comment]
Thanks for reporting this, fixed in https://github.com/ioam/holoviews/commit/e6f2eb73586d3a1daf4f77bc397025cbb766bd41.
