### ISSUE TITLE
'ls' not a valid style option in hv.Path

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#551]
`holoviews.Path((np.array(range(10)), np.array(range(10))))(style={'ls': '-'})`
gives me 

```
AttributeError [Call ipython.show_traceback() for details]
Unknown property ls
```

and an empty plot, `ls` does work for `Curve` and `ls` also shows up in `hv.help(hv.Path)`

**Comment by philippjfr** [comment]
Thanks, probably just need to delete ls from ``Path`` style options. It's very annoying that matplotlib hasn't standardized the naming of various styling attributes yet.

**Comment by philippjfr** [comment]
Fixed, deleted ``ls`` as an alias for ``linestyle``.
