### ISSUE TITLE
Kernel restart upon import

### ISSUE THREAD

**Issue by osdf** [ioam/holoviews#558]
Importing holoviews in jupyter notebook leads to a kernel restart. Installed holoviews (```1.4.3-py27_0```
) via conda ```4.0.5-py27_0```. The line in question is:

```
import holoviews as hv
```

**Comment by philippjfr** [comment]
Could you confirm your OS, Jupyter version and report any output in the console where you launched the notebook right after the crash?

**Comment by osdf** [comment]
OS (Ubuntu 15.10):
```
> uname -a
Linux osdfmachine 4.2.0-23-generic #28-Ubuntu SMP Sun Dec 27 17:47:31 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

```
> jupyter --version
4.0.6
```

Relevant output after crash
```
[I 14:36:55.908 NotebookApp] Kernel started: 963b2d47-2f29-4de2-9fba-d9fcb42b43c7
*** Error in `/home/osdf/anaconda/bin/python': free(): invalid pointer: 0x00007f19e13d8ec0 ***
[I 14:37:04.909 NotebookApp] KernelRestarter: restarting kernel (1/5)
```

Importing holoview in standard ipython works. It crashes for
* ```jupyter console```,
* ```jupyter qtconsole```,
* and the already mentioned ```jupyter notebook```

with an ```invalid pointer``` error as above.

(Note for ananconda installation: I have the ```mkl``` package installed).

**Comment by philippjfr** [comment]
I found this: https://github.com/mapbox/rasterio/issues/87

That makes it sound like an issue in the freetype version. Could you confirm which version of freetype you have in conda and in Ubuntu and then try to upgrade both?

**Comment by osdf** [comment]
Conda says I have freetype 2.5.5, no more update possible :(. Same with the one installed  by Ubunut, ```2.5.2-4ubuntu2 ```.

**Comment by osdf** [comment]
Any other news on that? I quickly re-did the example in #mapbox/rasterio#87 and this works. So maybe there is a problem somewhere else?

**Comment by philippjfr** [comment]
Are you still getting this error on the HoloViews dev version? Really not sure why this would be happening now.

**Comment by philippjfr** [comment]
Any update on this?

**Comment by osdf** [comment]
Cloning from git and installing (both ```param``` and ```holoviews```) with ```python setup.py --install user``` makes the original ```import``` work now. Thanks!

**Comment by philippjfr** [comment]
I'm glad it's working for you. Thanks for closing the issue!
