### ISSUE TITLE
%%opts for combined hv.Image * hv.Curve doesn't work correctly

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#56]
When I do

```
images = {(phi, theta):
                 hv.Image(data[phi, theta])
                 for theta in range(len(thetas)) 
                 for phi in range(len(phis))}

curves = {(phi, theta):
                 hv.Curve(curve_data[phi, theta])
                 for theta in range(len(thetas)) 
                 for phi in range(len(phis))}

total = {(phi, theta): images[phi, theta] * curves[phi, theta]
                 for theta in range(len(thetas)) 
                 for phi in range(len(phis))}
```

and then:

```
%%opts Image (cmap='gist_heat_r') style(origin='lower') Curve (linewidth=1)
hv.HoloMap(total, key_dimensions=['phi', 'theta'])
```

```(origin='lower')``` doesn't work.

however when I first evaluate 

```
%%opts Image (origin='lower')
images[0,0]
```

then the evaluation of ```hv.HoloMap(total)``` does work with the options that I set.

**Comment by philippjfr** [comment]
Have a look at the [Options](http://ioam.github.io/holoviews/Tutorials/Options) Tutorial, which explains how the options system works. As a quick summary, there's three kinds of options you can set:

1. Plot options (can be specified via square brackets [ ] or plot() syntax) - sets the options on the HoloViews plotting class
2. Style options (can be specified via parentheses () or style() syntax) - sets the options passed to the matplotlib plotting function
3. Normalization options (can be specified via curly brackets {} or norm() syntax) - determines how axis ranges, luminance values etc. are shared across plots.

So () and style() are just aliases of each other, if you contract your expression to:

%%opts Image (cmap='gist_heat_r' origin='lower') Curve (linewidth=1)
hv.HoloMap(total, key_dimensions=['phi', 'theta'])

It will work.

**Comment by basnijholt** [comment]
Thanks for the recap.

It does work immediately when I use your suggested code.
 
But strange though that my code didn't...

**Comment by basnijholt** [comment]
Another thing:

```
%%opts Image (origin='lower')
diagram[0,0] + diagram[0,0] * boundaries[0,0]
``
produces:
![download 5](https://cloud.githubusercontent.com/assets/6897215/7550677/141dad06-f66b-11e4-82e4-50aa2e9d1f80.png)

```
%%opts Image [invert_yaxis=True]
diagram[0,0] + diagram[0,0] * boundaries[0,0]
``
produces:

![download 6](https://cloud.githubusercontent.com/assets/6897215/7550678/162a1b70-f66b-11e4-862d-3bc3c277c1a9.png)

**Comment by basnijholt** [comment]
I think this is related:
```
%%opts NdOverlay [show_legend=False] Image (origin='lower')
topo_bounds[0,0] + topo_bounds[0,0]*gaps[0,0]
```
produces:
![download 10](https://cloud.githubusercontent.com/assets/6897215/7553686/d20e854c-f706-11e4-83d1-a24797aef85f.png)

**Comment by philippjfr** [comment]
Both of these aren't actual issues, just surprising behavior about the options system. Options that apply to the axes generally have to applied at the highest level of nesting. We're still not sure how to get around this behavior but for now your first example should read:

```python
%%opts Image [invert_yaxis=True] Overlay [invert_yaxis=True]
diagram[0,0] + diagram[0,0] * boundaries[0,0]
```

In the same vain the second example should be

```python
%%opts Overlay [show_legend=False] Image (origin='lower')
topo_bounds[0,0] + topo_bounds[0,0]*gaps[0,0]
```

This is because if you Overlay topo_bounds (the NdOverlay) with gaps the return type is an Overlay.

**Comment by basnijholt** [comment]
Ah, that makes a lot of sense actually. Thanks!

**Comment by jlstevens** [comment]
I agree with Philipp that it can be confusing if you don't consider what you are addressing the style/plot option to. This is one of the more common mistakes I make myself! I also agree that there is no obvious way to automate the problem away while keep the semantics straight.

Anyway, I think these are separate concerns from the main point of this issue which I believe is now resolved. I'll close this issue now but I am happy to reopen it if anyone raises has an objection!
