### ISSUE TITLE
Compute framewise normalization ranges lazily

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#561]
Currently when normalization is set to ``+framewise`` the normalization ranges are still all computed at initialization of the plot. This can considerably slow down initialization when ``live`` plotting and causes issues for data interfaces which support loading data lazily. The range finding code should either be applied per frame in general (which could slow down plotting) or we should provide some way to set a normalization mode.

The actual implementation should be fairly straightforward and is already partially in place for dynamic mode.

**Comment by jlstevens** [comment]
Sounds like a good idea.

I believe we could access the normalization options in the plotting class constructor in which case couldn't we just skip normalization if ``+framewise`` is enabled (or if we are in a mode where framewise has to be applied)?

**Comment by philippjfr** [comment]
Yes, that's my first proposal, which I thought would carry performance penalties but thinking about it now, there shouldn't be any. So just doing this in general when framewise is enabled makes sense.

**Comment by philippjfr** [comment]
So to my great surprise it turns out that I already implemented this, presumably when working on dynamic mode.
