### ISSUE TITLE
Regression in support for data formats

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#569]
This code works fine with HoloViews 1.4.3:

```python
import holoviews as hv
import numpy as np
hv.notebook_extension()
hv.Points((np.random.normal(size=100), np.random.normal(size=100)) + (-1,), vdims=['c'])
#hv.Points((np.random.normal(size=100), np.random.normal(size=100)))
```

![image](https://cloud.githubusercontent.com/assets/1695496/13998423/352f7fac-f105-11e5-817b-0e7d21a04ee7.png)

but not in the latest HoloViews master (g1e32595):

![image](https://cloud.githubusercontent.com/assets/1695496/13998395/0ab786fc-f105-11e5-9d2e-2899afb6fe09.png)

Uncommenting the other Points version works fine in both.  Any ideas?

**Comment by philippjfr** [comment]
Using scalar Columns isn't currently supported. It was partially working before simply because it wasn't validated. For now we could just expand the scalar value and in future we could add support for storing the data as a scalar on the dictionary interface but we need to actually go through all the methods and make sure it's supported.

**Comment by philippjfr** [comment]
Also we need to do something about exceptions on the interfaces. Since it tries each interface in turn we can't print all the exceptions but we should find some way to at least provide feedback about shape errors.

**Comment by jbednar** [comment]
Either of these works now, so I guess it's fine:
```python
hv.Points((np.random.normal(size=100), np.random.normal(size=100), (-1,)*100), vdims=['c'])
hv.Points((np.random.normal(size=100), np.random.normal(size=100), -1.0*np.ones((100))), vdims=['c'])
```

But yes, it's definitely a problem that we can't see the exceptions.  I can see why providing them would be a problem, since you don't know which one was _supposed_ to work.

**Comment by jlstevens** [comment]
I think we might want to consider an custom ``InterfaceException`` if it helps with generating error messages. I think the idea would be that this exception is used when an interface has reason to think no other interface can handle the data and yet something is still wrong.
