### ISSUE TITLE
UnboundLocalError when using a DynamicMap

### ISSUE THREAD

**Issue by tjol** [ioam/holoviews#571]
Displaying a `DynamicMap` fails with the following error: 
  `UnboundLocalError("local variable 'value_labels' referenced before assignment",) `

The error is raised in `holoviews.plotting.widgets.SelectionWidget.get_widgets`. The fix is coming to a pull request near you in just a minute.

**Comment by philippjfr** [comment]
This has been fixed in #575, please reopen if you encounter any issues.
