### ISSUE TITLE
Fix lexicographical sort for heterogeneous types on Columns interfaces

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#580]
Currently the Columns interfaces (except DFColumns) use lexicographical sorting, which is often not desirable. We should ensure that numbers are sorted by their value not the lexicographical value or actually provide control over the kind of sorting that is applied. Note that this is not trivial as there is no efficient numpy sorting implementation that I'm aware of, which does not rely on constructing a structured array.

**Comment by jlstevens** [comment]
What is wrong with [lexical sorting](http://mathworld.wolfram.com/LexicographicOrder.html)?

It just means that the first column (kdim) is sorted, then for equal values in that first column, the second column is then sorted etc.

**Comment by philippjfr** [comment]
As you rightly point out lexicographical sorting is what we want, it's just that heterogeneous types on DictColumns doesn't currently work as they are being cast to a homogeneous array of object type, which cannot be sorted correctly.

**Comment by jlstevens** [comment]
Ok the PR is merged now so I'll close the issue.
