### ISSUE TITLE
Explicit support for categorical axes and colormaps

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#582]
Currently only certain Element types support categorical axes, including Bars, HeatMap and BoxWhisker Elements. This means it's currently not possible to easily combine these categorical types with other Element types which use continuous axes. With a smarter normalization system as proposed in #581 it would be possible to collect all the categorical values along a dimension and assign each a unique location along the corresponding axis or a color in a discrete colormap. With this support all the regular Element types like Scatter could be used to plot discrete variables.

**Comment by kindofluke** [comment]
👍 Vote for this issue. I've even had errors plotting categorical axes on very simple elements when I use the matplotlib backend (which we prefer because we do a lot of publication). 

For example: 
```
%%output backend='bokeh'
first_names = ['Sam','Jesse','Nate','Linda','Rachel']
x = [np.random.choice(first_names) for x in range(50)]
y = [y for y in np.random.rand(50)]
data = [tup for tup in zip(x,y)]
hv.Points(data)
```
works fine but
```
%%output backend='matplotlib'
first_names = ['Sam','Jesse','Nate','Linda','Rachel']
x = [np.random.choice(first_names) for x in range(50)]
y = [y for y in np.random.rand(50)]
data = [tup for tup in zip(x,y)]
hv.Points(data)
```
returns with error 
> ValueError [Call holoviews.ipython.show_traceback() for details]
could not convert string to float:

The same occurs with scatter.

**Comment by philippjfr** [comment]
Our matplotlib for categoricals is currently basically non-existent. It should be too difficult to get at least the basics of this working. The main issue occurs when combining multiple elements with partially overlapping categorical indices. IMO we should tackle this once bokeh has proper support for nested categoricals, so we can solve it all at once.

**Comment by jlstevens** [comment]
I know this issue is about categoricals in matplotlib but I would like to mention that there are improvements being made to categoricals in bokeh too. See bokeh/bokeh#6654.

**Comment by philippjfr** [comment]
Yes that's what I was talking about support for nested categoricals in bokeh above. Very glad to see this happened so soon.

**Comment by philippjfr** [comment]
As of matplotlib 2.1, categorical axes are now supported in the matplotlib backend and categorical colormapping has been supported for a while.
