### ISSUE TITLE
Renderer options set via output cell magic do not persist in live mode

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#586]
When setting a Renderer option (such as ``fig='svg'``) is set using the cell magic this persists only for the initial frame in live mode. This is because the options only get set on the Renderer temporarily and when the widget class requests another frame the cell has finished executing and all the options are reset. The Renderer should instead make a new instance of itself when creating widget, which the widget class should then use to render all the frames.

**Comment by jlstevens** [comment]
After reading it a couple of times, the problem and the cause of the problem makes sense to me. As for the solution, couldn't the renderer simply pass ``self`` (an instance) when creating the widget instead of making a new instance?

**Comment by philippjfr** [comment]
No, because self is the main instance on ``Store.renderers``, which is reset to its original settings after the cell executes.
