### ISSUE TITLE
Confusing normalization

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#593]
For the latest HoloViews master (`1.4.3-233-gb344b9a`), if I run the following code cell:

```python
import numpy as np
import holoviews as hv
hv.notebook_extension()

%opts Image (cmap="Blues")

np.random.seed(42)

def gaussians(specs=[],num=100):
    dists = [(np.random.normal(x,s,num), np.random.normal(y,s,num)) for x,y,s in specs]
    return np.hstack([d[0] for d in dists]), np.hstack([d[1] for d in dists])

def heatmap(coords,bins):
    hist,xs,ys  = np.histogram2d(coords[0], coords[1], bins=bins)
    return hv.Image(hist[:,::-1].T, bounds=(xs[-1],ys[-1],xs[1],ys[1]))

dist2 = gaussians(specs=[(2,2,0.5),(-2,-2,0.01),(0,0,3)],num=10000)
```
I can get a plot of dist2 using either Scatter or this heatmap function:

![image](https://cloud.githubusercontent.com/assets/1695496/14298649/a312a260-fb4b-11e5-8e47-32f55aa55470.png)

![image](https://cloud.githubusercontent.com/assets/1695496/14298665/b232e458-fb4b-11e5-9bf7-1f3704869738.png)

But I also can get plots where I don't understand the normalization:

![image](https://cloud.githubusercontent.com/assets/1695496/14298679/c53c0980-fb4b-11e5-9710-cb6a9af4f92a.png)

I would have expected that if an Image plot is all on its own like this, not embedded into a HoloMap or Layout, there should be at least one pixel that's at the upper end of the given colormap.  I.e., I'd only expect to see a blank plot like this for something embedded into an object that has other larger values; how can it be blank in this case?  If I load the screenshot into an image program I can see that it's not truly blank, because there is a small light-gray smudge in one location, but shouldn't that smudge have had at least one fully dark pixel?

**Comment by philippjfr** [comment]
Looks like it's simply a problem with the resolution at which matplotlib is plotting it. You're cramming 1000 pixels into a tiny area, if you up the dpi a lot you might see it, but to demonstrate that it's not a normalization issue try zooming in on this point:

```python
heatmap(dist2, 1000)[-2.5:-1.5, -3:-1]
```

![image](https://cloud.githubusercontent.com/assets/1550771/14301050/89058b58-fb8c-11e5-95f7-450ef82b5a3d.png)

This is visible:


```
heatmap(dist2, 1000)[-5:5, -5:5]
```

![image](https://cloud.githubusercontent.com/assets/1550771/14301101/e9b0e704-fb8c-11e5-8404-fdef7af38c74.png)


While this isn't:

```
heatmap(dist2, 1000)[-6:6, -6:6]
```

![image](https://cloud.githubusercontent.com/assets/1550771/14301109/f7c60982-fb8c-11e5-91ac-99f2a34af709.png)

**Comment by jbednar** [comment]
Aha. Thanks!  Matplotlib must just be doing a basic stride-based downsampling, which usually works fine but won't in this case.
