### ISSUE TITLE
Raster and reduce and axes direction

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#595]
When I reduce the x axis of a Raster object, the direction of the Y axis is swapped.

Reducing the Y axis works fine:
```
%%opts Raster [colorbar=True]
img = hv.Raster(np.rot90(np.meshgrid(*[np.arange(5)]*2)[1][::-1]))
img+img.sample(y=2)+img.reduce(y=np.mean).to.curve('x','z')
```
![download 1](https://cloud.githubusercontent.com/assets/3776190/14356591/ca57d4f8-fce5-11e5-9707-f05b60b10617.png)

While reducing the X axis fails:
```
%%opts Raster [colorbar=True]
img = hv.Raster(np.meshgrid(*[np.arange(5)]*2)[1][::-1])
img+img.sample(x=2)+img.reduce(x=np.mean).to.curve('y','z')
```
![download](https://cloud.githubusercontent.com/assets/3776190/14356590/ca552442-fce5-11e5-8273-602e3b4f1b38.png)

**Comment by philippjfr** [comment]
Fixed in #672. Closing.
