### ISSUE TITLE
Cloning HoloMaps

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#597]
I want to clone a holomap with images, and alter the data of the images of the clone. The default clone does not work:

```
h = hv.HoloMap({0:hv.Image(np.array([[1]])),
               1:hv.Image(np.array([[1]]))})
h2 = h.clone(shared_data=True)
h2[0].data[:] = 0
h[0].data
```

returns 0 instead of 1

The clone method has a parameter shared_data, that sounds like it should work, however:

```
h = hv.HoloMap({0:hv.Image(np.array([[1]])),
               1:hv.Image(np.array([[1]]))})
h2 = h.clone(shared_data=False)
h2.info
```

Results:

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-67-71efa9e46cda> in <module>()
----> 1 h2.info

/home/tenner/src/holoviews/holoviews/core/ndmapping.py in info(self)
    415         info_str = self.__class__.__name__ +\
    416                    " containing %d items of type %s\n" % (len(self.keys()),
--> 417                                                           type(self.values()[0]).__name__)
    418         info_str += ('-' * (len(info_str)-1)) + "\n\n"
    419         aliases = {v: k for k, v in self._dim_aliases.items()}

IndexError: list index out of range
```

**Comment by philippjfr** [comment]
The ``info`` output might be a bug, will have to look into it. ``clone`` does not make a copy of your data, it simply creates a new object. By default that new object has the same data, if you declare ``shared_data=False`` it will simply return an empty object. You'd have to copy the data yourself like this to make a real copy: ``h.clone(copy.deepcopy(h.data))``.

**Comment by philippjfr** [comment]
The bug in ``info`` appears to have gone and the behavior of clone is correct, so I'll close. We could consider adding support for deep clones but that would be a new feature request.
