### ISSUE TITLE
Implement overlay operator as separate operation

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#600]
The `__mul__` method has grown into a bit of a monster. It would be nice to split that functionality into a utility or operation. This would help group the code into one place to handle all the different cases, simplifying `__mul__` everywhere and potentially making it easier to see how to simplify the code.

**Comment by philippjfr** [comment]
Don't really see this happening, ``__mul__`` implementations differ vastly by the type they are implemented on and a single operation/utility would be more unwieldy than the current separation on the classes. If you insist on this please reopen.
