### ISSUE TITLE
Opts magics should validate non-existing Elements

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#625]
Currently when you accidentally request to style a non-existing Element using the opts magic it will simply accept it without question. It would be good if we could validate the opts magic specification and check that there is actually an entry in the OptsTree for the requested Element type.

**Comment by jlstevens** [comment]
Agreed. This shouldn't be hard to do but it is low priority unless you tell me otherwise.

**Comment by jlstevens** [comment]
Fixed in the PR referenced above. Closing.
