### ISSUE TITLE
Give safe_unicode a more correct name

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#632]
The `safe_unicode` utility is very important in ensuring that bytes types are correctly cast to unicode but it does not safely cast all types to unicode as the name implies. We should come up with a more appropriate name.

**Comment by jlstevens** [comment]
Thanks for filing this. I noticed the confusing name when reviewing a PR but I haven't managed to come up with a better name yet. It isn't 'safe' as there was an exception raised when using the built in ``unicode()`` was enough - what *exactly* does it do again?

**Comment by philippjfr** [comment]
If safely casts ``str`` types with various encodings to unicode in Python 2 but leaves non string types unaffected.

**Comment by jlstevens** [comment]
So it goes from string encodings to unicode? Sounds like something I would expect to find in the standard library....

**Comment by jbednar** [comment]
unicodify?  ensure_unicode?  to_unicode? promote_to_unicode?
