### ISSUE TITLE
Grid based interfaces should return sparse values by default

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#635]
So far the grid based data interfaces ``dimension_values`` method has returned the expanded key dimensions (the cartesian product) for compatibility with our internal API. However since these interfaces are still fairly new and no user code depends on them I would like to consider making our internal code explicitly request either ``expanded=False`` or ``expanded=True``. Then the ``dimension_values`` method could return the key dimensions in the format that they were supplied in rather than expanding them needlessly. 

Returning the full dot product for the outer dimensions is rarely actually useful to the user and ``dataset.dimension_values(dim, expanded=False)`` is pretty awkward just to get at the coordinates of the grid. I realize this adds some level of inconsistency but the user really should know how in what format they supplied their data and adjust accordingly.

Just a suggestion we should discuss before releasing the interfaces and being stuck with the current behavior.

**Comment by jlstevens** [comment]
I think there is a clear tradeoff between consistency and efficiency.

Expanding is consistent and even if it isn't always sensible but consistency means you can get the values from any element and immediately understand the format you receive. My inclination at the user level would be to be consistent first and efficient second: if you know what you are dealing with why not just request ``expanded=False`` explicitly when you know it makes more sense?

For the internal code, I would be happy to explicitly request ``expanded=False`` or ``expanded=True`` when appropriate  (as you suggest), but my inclination would be to leave ``expanded=True`` by default for consistency, even if it isn't always efficient.

**Comment by philippjfr** [comment]
The main question is how we treat the grid based interfaces conceptually. Are they simply more efficient formats for storing a dataset but should fundamentally still be treated as collections of individual samples OR should they conceptually be treated as a true grid based format? If it's the former then yes we should stick with the current approach of expanding by default, if it's the latter then the API should reflect that and not pretend that the data is a collection of columns.

**Comment by jbednar** [comment]
Whew, this is a tough one!  Can't we have both? :-)

I  would think that our internal code should not needlessly expand the values, so that we will have true support for gridded data.  But I would also think the user shouldn't be forced to keep track of whether the data was originally gridded or not, in most cases.  Just my boundless optimism, I guess!

**Comment by jlstevens** [comment]
Why not have a method on the interface class to support gridded data that is there if the user wants it?

**Comment by philippjfr** [comment]
This has now been decided. The default is always to expand the coordinates but using expand=False that can be suppressed.
