### ISSUE TITLE
Transpose GridInterface data format

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#637]
The current implementation of the GridInterface expects the data to be in the following format:

```python
xs = range(10)
ys = range(20)
zs = np.ones(10, 20)
data = {'x': xs, 'y': ys, 'z': zs}
```

i.e., the value arrays must match the shape of the key dimensions in the order they are specified. However in discussing the iris format and thinking about it again I realized that generally the convention is for the shape of a 2D array to be:

```python
ylength, xlength = array.shape
```

This is also more consistent with the ways we already store the array in our ``Raster`` types (although still flipped upside down). We should therefore change the ``GridInterface`` to the transposed format before we release and users officially depend on it.

**Comment by philippjfr** [comment]
@jbednar @jlstevens Thoughts on this? Need to decide on the correct orientation of the data in the grid interface before releasing 1.5.

**Comment by jbednar** [comment]
I'm not sure what approach is best; the whole world seems confused about how to store matrices and rasters.  But yes, r,c is normally how the shape is specified in numpy, i.e. len(ys),len(xs).

In any case, I also can't quite tell how to interpret your example; how does anyone know that xs came before ys, given that a Python dictionary is not ordered?

**Comment by philippjfr** [comment]
>In any case, I also can't quite tell how to interpret your example; how does anyone know that xs came before ys, given that a Python dictionary is not ordered?

When specifying in the dictionary format you always have to explicitly declare the dimensions as well. You can always supply a tuple though and it automatically expand it to the dictionary format:

```
hv.Dataset((xs, ys, zs), kdims=['x', 'y'], vdims=['z'])
```

Optionally we could also automatically infer dimensions if supplied an OrderedDict as we already do for the pandas interface.

>I'm not sure what approach is best; the whole world seems confused about how to store matrices and rasters. But yes, r,c is normally how the shape is specified in numpy, i.e. len(ys),len(xs).

The benefit of having it in the current format (column, row) is that when you flatten it, it corresponds directly to the default Column order. Using r, c instead seems to be convention elsewhere (like iris), while our raster are r, c but flipped upside down. I'm really not sure what to suggest but am tending toward regular r, c since that's generally expected, the inconsistency with our existing Rasters bothers me though.

**Comment by philippjfr** [comment]
The PR was just merged, we're now stuck with this format. I do think it is the correct format since it is what other grid based interfaces like iris and xarray will expect.
