### ISSUE TITLE
opts magic inheritance cmap

### ISSUE THREAD

**Issue by marqh** [ioam/holoviews#646]
```
import iris
import holoviews as hv
import geoviews as gv
import cube_browser
import cartopy
```

```
cube = iris.load_cube(iris.sample_data_path('rotated_pole.nc'))
```

with a specification of Dataset, the color map is preserved:
```
%%opts FilledContours.Air_pressure_at_sea_level [levels=7]

airp = hv.Dataset(cube)
airp.to.filledcontours(['grid_longitude', 'grid_latitude'], dynamic=True)  * gv.Feature(cartopy.feature.COASTLINE)
```

but, if the FilledContours does not specifiy the Air_pressure...., the colormap is overridden 
```

%%opts FilledContours.Air_pressure_at_sea_level [levels=7]

airp = hv.Dataset(cube)
airp.to.filledcontours(['grid_longitude', 'grid_latitude'], dynamic=True)  * gv.Feature(cartopy.feature.COASTLINE)
```
this last call should not alter the colormap

**Comment by philippjfr** [comment]
I can't tell the difference between your two examples.

**Comment by bjlittle** [comment]
@jlstevens says: yes, it is fine to assign it to him and you are right that the example is wrong (your version is right)

**Comment by philippjfr** [comment]
It's a pretty tricky problem and I know roughly how to fix it but actually implementing the correct solution will still be pretty difficult. Hopefully @jlstevens will have the time to tackle it this week, otherwise I'll try to spend an hour or two on it over the weekend.

**Comment by philippjfr** [comment]
This has finally been fixed in https://github.com/ioam/holoviews/pull/796. Closing.
