### ISSUE TITLE
Handle KeyboardInterrupt in Collector

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#658]
The ``Collector`` is a useful (although currently undocumented!) feature. One problem is that interrupting the kernel loses all your data, even if a lot of data has been collected.

For instance, if you run ``data = Collector()(times=[0,500,1000,5000,10000])`` and interrupt after 5000, you get no data back at all. Using the following pattern, it would be possible to return whatever data has been collected before the ``KeyboardInterrupt``.

```python
import time, sys

def loop():
    x = 1
    try:
        for i in range(20):
            print x
            time.sleep(.3)
            x += 1
        return x
    except KeyboardInterrupt:
        return x
    
data = loop()
```

**Comment by jbednar** [comment]
That seems like an excellent idea, and will save some heartache.

**Comment by jlstevens** [comment]
I'm going to implement this now although I don't know who will be using ``Collector`` other than Philipp and myself (now that we have submitted our theses!).

If anyone else is going to make use of it, it will need to be documented.

**Comment by jlstevens** [comment]
Implemented in the PR mentioned above. I'll close this issue as soon as that one is merged.

**Comment by philippjfr** [comment]
Has been merged, closing.
