### ISSUE TITLE
histogram disappears in .cols(2) of 2 by 2.

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#66]
This one is a bit strange, but the histogram disappears
```
(gaps_bounds2[0,0] + gaps_bounds2[0,0] + gaps_bounds2[0,0].hist() + gaps_bounds2[0,0]).cols(2)
```

![download 1](https://cloud.githubusercontent.com/assets/6897215/7592508/e786eb16-f8d3-11e4-9d3b-b5657d17ae57.png)

Just one row works fine:
```
(gaps_bounds2[0,0].hist() + gaps_bounds2[0,0]).cols(2)
```

![download 2](https://cloud.githubusercontent.com/assets/6897215/7592519/f5e6e684-f8d3-11e4-8b8b-6a2ca2f731fd.png)

**Comment by philippjfr** [comment]
Very strange, when you add a histogram to each they appear again. Will have to investigate in the near future.

**Comment by jlstevens** [comment]
This is one of the bugs we will want to sort-out before we do the next (bug fix) release.

**Comment by philippjfr** [comment]
Should be fixed by the commit referenced above, so I'll close this now.
