### ISSUE TITLE
unique_array broken without pandas

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#662]
I tried running some code on a fresh desktop install and I found that the ``sample`` method was broken. I was trying the following line on a ``HoloMap`` of ``Images``:

```python
 hmap.sample((11,11), bounds=(-0.45, -0.45, 0.45, 0.45))
```

And every time, this exception was raised:

```python
TypeError: 'only integer arrays with one element can be converted to an index'
```

It turns out the problem is in ``core.util.unique array``:

```python
def unique_array(arr):
    """
    Returns an array of unique values in the input order
    """
    if pd:
        return pd.unique(arr)
    else:
        _, uniq_inds = np.unique(arr, return_index=True)
        return arr[np.sort(uniq_inds)]
```

I have no idea what is going on but then I realized that it *seems* to work only because I normally have pandas installed. We aren't supposed to be depending on pandas! 

This is a good example of why we should try to set up some Travis tests without pandas installed.

**Comment by philippjfr** [comment]
This was fixed in #663, ``unique_array`` is meant to be used with arrays, which it wasn't doing in this case. Closing.
