### ISSUE TITLE
Support for discrete color maps

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#665]
As I'm currently writing up my thesis there's I've been wanting precise control over a lot of the aspects of the plot and one thing I've done quite frequently is to generate a discretized colormap. Currently I do this by doing something like this:

``` python
import matplotlib.cm as cm
cm.register_cmap('Blues_20', cm.get_cmap('Blues', 20))
```

Then I can use the discretized Blues colormap with 20 steps everywhere by referring to it by the name I gave it, i.e. 'Blues_20'. It might be nice to consider whether we should support this by default by letting you append a `_{n}` suffix to any matplotlib colormap, telling it to discretize the colormap into `n` colors. Just a thought, and very easy to implement.

**Comment by jbednar** [comment]
I'm a little worried about the potential for confusion between matplotlib and Bokeh with such an extension.  Bokeh defines various Blues palettes as:

```python
Blues3      = ["#3182bd", "#9ecae1", "#deebf7"]
Blues4      = ["#2171b5", "#6baed6", "#bdd7e7", "#eff3ff"]
Blues5      = ["#08519c", "#3182bd", "#6baed6", "#bdd7e7", "#eff3ff"]
Blues6      = ["#08519c", "#3182bd", "#6baed6", "#9ecae1", "#c6dbef", "#eff3ff"]
Blues7      = ["#084594", "#2171b5", "#4292c6", "#6baed6", "#9ecae1", "#c6dbef", "#eff3ff"]
Blues8      = ["#084594", "#2171b5", "#4292c6", "#6baed6", "#9ecae1", "#c6dbef", "#deebf7", "#f7fbff"]
Blues9      = ["#08306b", "#08519c", "#2171b5", "#4292c6", "#6baed6", "#9ecae1", "#c6dbef", "#deebf7", "#f7fbff"]
```

where the numeric suffix indicates a difference in dynamic range, not in number of discrete steps (since I think each one is interpolated between each of the discrete steps in the list).

Maybe to avoid confusion it could be `_d{n}`, where`d` indicates discrete (or `c` for colors, or something of that nature)?

**Comment by jbednar** [comment]
Actually, looking at the colors at http://bokeh.pydata.org/en/latest/docs/reference/palettes.html the different numbers indicate not just differences in dynamic range, but also in the linearity of the color map.  In any case, it's worth distinguishing your particular changes to the colormap from what Bokeh is doing.

**Comment by philippjfr** [comment]
I'm going to close this in favor of #1885. Bokeh already allows passing a list of discrete colors and with the PR matplotlib will allow the same.
