### ISSUE TITLE
Better exception message for unsupported Layout kdim combinations

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#666]
Right now we don't support a `Layout` of a `HoloMap` over one dimension (say `'Time'`) and another with a different dimension (say `'Duration'`). This is something we hope to improve in the future so it _is_ allowed but in the meantime it would really be helpful to raise a better exception when such illegal combinations are attempted.

**Comment by philippjfr** [comment]
This is now supported for ``DynamicMap`` and two ``HoloMap`` objects combined into a Layout raise this error:

```python
hv.HoloMap({i: hv.Curve([]) for i in range(3)}, kdims=['X']) +\
hv.HoloMap({i: hv.Curve([]) for i in range(3)}, kdims=['Y'])
```

>ValueError: When combining HoloMaps into a composite plot their dimensions must be subsets of each other.

**Comment by jlstevens** [comment]
I think that does address this issue. Closing.
