### ISSUE TITLE
Should open counter mode respect dimension ranges?

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#676]
If I follow the example from the Dynamic_Map tutorial for open mode but specify a concrete range, I get a series of Elements that cover the specified range:

``` python
import holoviews as hv
import numpy as np
hv.notebook_extension()

def gaussian_histogram(samples, scale):
    frequencies, edges = np.histogram([np.random.normal(scale=scale) 
                                       for i in range(samples)], 20)
    return hv.Histogram(frequencies, edges).relabel('Gaussian distribution')

def gaussian_sampler(samples=10, delta=10, scale=1.0):
    np.random.seed(1)
    while True:
        yield gaussian_histogram(samples, scale)
        samples+=delta

hv.DynamicMap(gaussian_sampler(), kdims=[hv.Dimension('step',range=(0,100))])
```

![image](https://cloud.githubusercontent.com/assets/1695496/15188983/0d65bd58-176e-11e6-8ce9-0991fb7522c2.png)

If I then leave _any_ of the range values unspecified, I get a series of elements starting at 0 and going indefinitely (past 100):

``` python
hv.DynamicMap(gaussian_sampler(), kdims=[hv.Dimension('step')])
hv.DynamicMap(gaussian_sampler(), kdims=[hv.Dimension('step',range=(0,None))])
hv.DynamicMap(gaussian_sampler(), kdims=[hv.Dimension('step',range=(None,100))])
```

This third case is suprising, since it's ignoring the specified upper bound of 100; the values happily increase indefinitely.  What's also surprising is that the lower bound, if nonzero, causes an error `Rendering process skipped: DynamicMap generator exhausted.`:

``` python
hv.DynamicMap(gaussian_sampler(), kdims=[hv.Dimension('step',range=(50,100))])
```

I would expect, and thus propose as a feature request, that:
1. Where possible the upper bound is respected (as if a StopIteration had been returned), and that 
2. The lower bound, if specified, is used as a starting point for the counter (where that is feasible) or else an error condition is raised when initially specified (if the starting point always must be zero).

**Comment by jlstevens** [comment]
Just a quick note to say you are in open 'counter' mode.

In the generator you use:

```python
yield gaussian_histogram(samples, scale)
```

That is an element without a correspond key. The relevance of ``range`` to counter mode is still something we need to discuss.

**Comment by philippjfr** [comment]
Being able to specify Dimension ranges and values in open mode is definitely a good idea. One major benefit would be that it would allow coordinating multiple DynamicMap generators. You can imagine that in a complex simulation or dashboard you would might want to update different the plots at different intervals, e.g. a simple view showing the evolving activity of a model and an analysis of the model which is more complex to compute and should only be updated every 100 steps. You could specify this simply by supplying an integer range or discrete integer samples:

```python
hv.DynamicMap(gen1, kdims=[hv.Dimension('a', range=(0, 100)) +\
hv.DynamicMap(gen2, kdims=[hv.Dimension('a', values=range(0, 100, 2)])
```

A way of specifying a step value might also be nice, as it would let you specify an unbounded number of samples:

 ```python
hv.DynamicMap(gen1, kdims=[hv.Dimension('a', range=(0, None)) +\
hv.DynamicMap(gen2, kdims=[hv.Dimension('a', range=(0, None, 2)])
```

**Comment by philippjfr** [comment]
There is no longer a DynamicMap open mode, closing.
