### ISSUE TITLE
Clarify Dynamic_Map modes

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#681]
As discussed in #677, the various modes in which a Dynamic Map can be used are very confusing:
- **Bounded mode:** All dimension ranges specified, allowing exploration within the ranges (i.e., within a bounded region of the multidimensional parameter space).
- **Sampled mode:** Some dimension ranges left unspecified, making the `DynamicMap` not viewable directly, but useful in combination with other objects or for later specifying samples or ranges.
- **Open mode:** Dimension ranges not specified, with new elements created on request using a generator.
- **Counter mode:** Dimension ranges not specified, with new elements created based on a shared counter state, e.g. from a simulation.

These are all in comparison to a HoloMap, which (one way or another) always has an enumerated list of points in some potentially multidimensional space.  For a HoloMap, Elements are defined only at those points, whereas a DynamicMap won't normally have such a finite list, instead allowing various points to be chosen interactively or dynamically as determined by the above modes.

As suggested by @philippjfr, another way to think of the modes is that really we are either in sampling mode, where we supply a function that can return any point requested by its coordinates in the multidimensional parameter space, or in generator mode, where arbitrary points cannot be requested by coordinate, only the "next" point or the point corresponding to some counter.

Thus "sampling mode" can be either what is called "bounded mode" above (if the defined region of the multidimensional parameter space has been specified fully, in which case we can pop up a visualization with sliders), or what is called "sampled mode" above (if at least one end of one range of one dimension has not been specified), in which case we cannot view the object directly.  

Similarly, in generator mode, we can either be using an actual generator (calling `next()`), called "open mode" above, or a function of one variable (e.g. time), called "counter mode" above.

One confusing bit is that counter mode doesn't actually use Python generators, even though it's being considered an option in "generator mode".

If we decide on good terminology, it seems like we could make some of these changes simply in the descriptions of the modes in the Dynamic Map tutorial.  Others would require backwards-incompatible naming changes, which are less feasible.  It looks like the most problematic of these names, i.e. sampled mode, is part of the API itself, due to `sampled=True`, but (a) I'm not sure what that declaration actually does -- why is this mode not simply deduced from the lack of ranges specified? , and (b) I'm not sure if any of the other modes involve explicit specification of this nature.

**Comment by jlstevens** [comment]
I think streams gives us a good opportunity to revisit this. I'm reconsidering whether we want to keep counter mode for instance. Sampling mode is something that also needs to be clarified.

**Comment by jlstevens** [comment]
This has been largely addressed in #1238 - almost all those modes no longer exist. I'll close this issue once the DynamicMap tutorial is updated to reflect this.

**Comment by philippjfr** [comment]
The DynamicMap tutorial was completely restructured into a user guide, closing.
