### ISSUE TITLE
Jupyterlab compatibility ?

### ISSUE THREAD

**Issue by stonebig** [ioam/holoviews#687]
is Holoviews  (especially widgets) compatible with coming soon Jupyterlab infrastructural change ?

**Comment by jbednar** [comment]
If it isn't, we'll make a version that is compatible.

**Comment by philippjfr** [comment]
Currently this is not properly supported as the widgets fail to display and comms do not work correctly.

**Comment by philippjfr** [comment]
This will get tackled in our widget code rewrite, which is scheduled for 1.8.

**Comment by stonebig** [comment]
Jupyterlab looks a little bit useless without Holoviews widgets

**Comment by stonebig** [comment]
any hope for coming 1.9.0 ?

**Comment by philippjfr** [comment]
None unfortunately, we're waiting until bokeh solves Jupyterlab comms issues so we can copy them. We've decided it's not worth getting HoloViews only partially working in JLab.

**Comment by athornton** [comment]
Can you give a pointer to the JL comm issues?  I'm interested in at least sniffing out how large a problem it is, and I'd like to get a feel for whether this is something likely to be resolved or whether it is a when-pigs-fly request.  We'd obviously prefer to use JupyterLab but if Classic is the only way it's ever gonna work, well, that's worth knowing.

**Comment by jbednar** [comment]
Oh, we'll definitely make things work well in JupyterLab, somehow!  We're focused on other things for the moment, but there is no option for not supporting JupyterLab.

**Comment by rserbitar** [comment]
Any plans to add jupyterlab support before their beta release (which is no scheduled for christmas)?

**Comment by philippjfr** [comment]
@rserbitar Very unlikely unfortunately. We're waiting on bokeh to add support for JupyterLab and that effort appears to have stalled for the time being. I'll try to revisit early next year if there's still been no progress.

**Comment by rserbitar** [comment]
I thought this was already addressed: https://github.com/bokeh/bokeh/issues/6700

**Comment by philippjfr** [comment]
Well partially, static plots can be displayed but a lot of the power in HoloViews comes from being able to dynamically update plots, which relies on Jupyter comms. Those do not yet work with bokeh in JupyterLab.

**Comment by akhmerov** [comment]
@philippjfr aren't holoviews widgets completely separate from the bokeh interaction with jlab?

**Comment by rserbitar** [comment]
Jupyterlab is in Beta now. Is there an issue on bokeh that corresponds to the features needed to make holoview compatible with jupyterlab? Can anyone point me in the right direction?

**Comment by jbednar** [comment]
See https://github.com/ioam/holoviews/pull/2368 (WIP)

**Comment by philippjfr** [comment]
JupyterLab support now landing in 1.10, we should have a dev release out soon. To try it out on master you can install the extension like so:

    conda install -c conda-forge jupyterlab
    jupyter labextension install @pyviz/jupyterlab_holoviews

**Comment by stonebig** [comment]
please make it available on pypi or in a bokeh way style

````
pip install --pre -i https://pypi.anaconda.org/holoviews/channel/dev/simple holoviews
````

**Comment by stonebig** [comment]
and don't we need a bokeh dev build too ?

**Comment by jlstevens** [comment]
> and don't we need a bokeh dev build too ?

You will do. The relevant PR isn't even merged yet!
