### ISSUE TITLE
Histogram widget for controlling colormap

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#689]
Right now, it's easy to choose a colormap for e.g. an Image plot, but it's not simple to control which numeric values are mapped into that colormap.  E.g. for the example on the homepage:

![image](https://cloud.githubusercontent.com/assets/1695496/15514381/7474c206-21ae-11e6-8475-94af8bd37cbf.png)

most of the colormap range is spent on the values above 0.2, yet most of the pixels in the plot are below 0.2.  Thus there is no color detail in the background (which is perhaps ok for this image, since the background has less texture, but that's not always true).  One can limit the z dimension range by hand, but that's awkward and not interactive.  What if we had something like Photoshop or Gimp's interactive control of the displayed range, from a histogram?

![image](https://cloud.githubusercontent.com/assets/1695496/15514301/21184952-21ae-11e6-8116-4cfce0b33070.png)

E.g. something like this mockup:

![image](https://cloud.githubusercontent.com/assets/1695496/15514328/3a15501c-21ae-11e6-82e4-f114e1b0fb97.png)

I just drew some little handles, but actually, using three little triangles as in Gimp would also let the user control the linearity, which could also be really handy.

E.g. one could have a plot option to enable those widgets, and once they are enabled one could drag them around to see specific value ranges that otherwise would not be visible, while being guided by the histogram to know where to drag them.

**Comment by jlstevens** [comment]
I think it is a really cool suggestion and I would love something like this.

My worries are 1. it would be quite difficult to do 2. it involves ``AdjointLayouts`` used for side histograms etc which is currently a system we don't like very much.

It is a great suggestion although I should note the fanciest GUIs let you distort the distribution using in the colormap instead of just setting the lower and upper limits.

**Comment by jbednar** [comment]
If you use the three triangles as in Gimp, then you can distort the distribution (what I referred to as changing the linearity above), which is indeed useful (but is only second-order useful, i.e. not quite as important as setting the range, but still very useful).

I'm not too worried about it using AdjointLayouts, as I imagine whatever we did here could be done for other side-histogram approaches as well, but I agree this seems difficult to implement.

**Comment by jbednar** [comment]
This functionality will be much easier to implement in the Bokeh backend, since we have interactive controls available there, and an open question is how much of such an implementation should go into Bokeh itself (since this functionality would be useful to all Bokeh users) and how much would go into HoloViews.  I would guess that the basic support for such interactivity would be better made part of Bokeh, and then HoloViews could integrate it into a linked-up set of plots (which could also be done using pure Bokeh, separately).

**Comment by jbednar** [comment]
Comment from Philipp:

> I agree it would be a very cool feature to have and agree with everything that was said. I could see how this could be implemented easily enough by extending the HoloViews/Bokeh SideHistogramPlot if we could add some bokeh arrows which could be draggable. A JS callback, would then update the color range with the current position of the arrow. I think this might all already be possible, I just don't know about the dragging part.

**Comment by jbednar** [comment]
Luke also suggested that we could support using the box select tool, auto-ranging to the value inside that region to set the max and min.  I agree that would also be extremely useful, because sometimes one  wants to set by color range, but other times one just wants to investigate a certain feature, effectively zooming in in color space to that region.  On the other hand, such box select support could presumably be handled using box zoom, if we make the colormap respect the current zoom level.

**Comment by philippjfr** [comment]
>Luke also suggested that we could support using the box select tool, auto-ranging to the value inside that region to set the max and min.

I agree that would be a very nice feature as well but to me independently draggable components are more useful, because setting both the min and max precisely using the box zoom tool is rather difficult. The other problem I have with that approach is that once you're zoomed in it's a bit awkward to zoom out again since both the wheel zoom and reset won't offer very precise control.

**Comment by jbednar** [comment]
I think the two approaches (box select and explicit value range) are very complementary, just depending on whether you want to select by space or by value.   

See https://github.com/bokeh/bokeh/issues/3126 for zooming out ideas, and maybe vote for one.

**Comment by philippjfr** [comment]
Adjoined histograms now provide control over the clims of the colormap in bokeh by using the ``box_select`` tool, so I'll close now.

**Comment by jlstevens** [comment]
The dynamic adjoint histograms are really great but I still find using the box select tool to interact with it rather unintuitive/weird.
