### ISSUE TITLE
Image doesn't respect extents parameter

### ISSUE THREAD

**Issue by RafalSkolasinski** [ioam/holoviews#692]
Following modification of code in continuous coordinates tutorial 

``` python
i5 = hv.Image(f5 , label="I5", bounds=region, extents=(-.2, -.2, .2, .2))
i5
```

doesn't respect extents parameter. It acts like without providing extents.

**Comment by philippjfr** [comment]
It's a legacy reason in that we often don't want to situate images in our work, but I don't think it's sensible to force that choice onto everyone else. There is a plot option to not ignore the extents called ``situate_axes``, which should presumably be deprecated.

**Comment by jbednar** [comment]
We probably shouldn't deprecate situate_axes, as it's definitely useful, but maybe switch it on by default to avoid surprising people in this way.
