### ISSUE TITLE
Forcing matplotlib to prioritize plot limits over plot ticks

### ISSUE THREAD

**Issue by RafalSkolasinski** [ioam/holoviews#693]
In current situation when setting `extents` and `ticks` for Image the `ticks` position got prioritize and therefore value given to `extents` are ignored. For example see (`image` from `Options` tutorial).

``` python
%%opts Image (clims=(0,0.072)) [situate_axes=True colorbar=True] 

img = image.clone(extents=(-.2, -.2, .2, .2))
img(style={'cmap': 'Greens'}, plot={'xticks': [-1,0,1]})
```

I checked that it is indeed the `matplotlib` behaviour when ticks are set after limits. Please see following two examples for comparision

``` python
from matplotlib import pyplot as plt
import numpy as np
%matplotlib inline

data = np.random.rand(100, 100)
plt.imshow(data)

plt.xticks([10, 30, 50]);
plt.xlim(20, 40);
```

and 

``` python
from matplotlib import pyplot as plt
import numpy as np
%matplotlib inline

data = np.random.rand(100, 100)
plt.imshow(data)

plt.xlim(20, 40);
plt.xticks([10, 30, 50]);
```

In second examples ticks are prioritized, in first one not. 

I would propose to change `holoviews` default behaviour to process first `xticks` and then `xlim`.

**Comment by philippjfr** [comment]
Fixed in https://github.com/ioam/holoviews/pull/1209.
