### ISSUE TITLE
Colormaps missing from Palette

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#696]
It seems `plt.cm.datad` is missing some colormaps:

``` python
Palette.colormaps.update({cm: plt.get_cmap(cm) for cm in plt.cm.datad})
```

For instance, I have to add 'viridis' manually.

**Comment by philippjfr** [comment]
This has been fixed in https://github.com/matplotlib/matplotlib/issues/5202 and should have land in the 1.5.2 release, which I believe is imminent.

**Comment by philippjfr** [comment]
Going to close now that 2.0 is out.
