### ISSUE TITLE
Choosing slider style for sliding in one key_dimension.

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#70]
With a ``HoloMap`` with one key_dimension you always get this type of slider:
![screen shot 2015-05-13 at 22 53 41](https://cloud.githubusercontent.com/assets/6897215/7621010/a4e56a94-f9c3-11e4-9d39-bc38c91c7554.png)

While when you have two key_dimensions and fix one by ``hv.HoloMap(..)[0,:]`` you get:
![screen shot 2015-05-13 at 23 00 30](https://cloud.githubusercontent.com/assets/6897215/7621041/e3638af8-f9c3-11e4-8c01-d67b38efa6ae.png)

Is it possible for one key_dimension to use the second slider?

**Comment by philippjfr** [comment]
Yes, we've really got to add a Tutorial for widgets, backends etc. and there's already an issue for it https://github.com/ioam/holoviews/issues/63 but I haven't gotten around to it yet. Selecting the widget type can be done via ``%output holomap='widgets'/'scrubber'/'auto'```. The 'scrubber' option gives you the play buttons, 'widgets' gives you the widgets on the side, and 'auto' gives you the default behavior you described.

**Comment by basnijholt** [comment]
Is it also possible to determine where the slider will come? In a presentation the ```'scrubber'``` orients itself nicely under the plots, although I don't actually want the buttons and the ``'widgets'`` are on the right of my plots which make the plots too small. Any easy solutions for this?

**Comment by philippjfr** [comment]
The whole widget Javascript/HTML code isn't brilliant and the layout isn't customizable yet. Unfortunately neither of us is particularly experienced with JS. Once the IPython/Jupyter widget system is more stable we may also decide to start using their widget API again. What IPython doesn't yet offer is static widgets so we'll have to maintain our version at least for now. I'm the only one who is familiar with the widget jinja templates and won't have any time to work on it in the near future. If you know anything about JavaScript I'm happy to take you through it and you could have a shot at improving the layout and/or making the position customizable.

**Comment by jlstevens** [comment]
I agree with Philipp and I think our best approach is to see if anyone is succeeding in doing anything significantly better in this regard within the IPython Notebook. If they are, we should be able to adapt their code/approach for our purposes. 

Unfortunately, neither Philipp or I are sufficiently well versed in Javascript right now to tackle a general approach for laying out the widgets  right now - although I agree it would be a nice feature!

**Comment by philippjfr** [comment]
I'll resubmit this as a feature request shortly.
