### ISSUE TITLE
Current state of DynamicMap

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#705]
Is there an easy way to get the parameters of the showed item in a DynamicMap?

dmap.keys() of dmap.cache shows all the keys available in the cache, not the current selected frame.

When using ipython.widgets.interact, one can do: object.kwargs or something.

This addition would it also make it possible to easilier to save the last state of a widget in a notebook.

**Comment by jlstevens** [comment]
I think this is a reasonable suggestion. 

The attribute could be called ``args`` as that is how arguments are passed into the callback (if not a generator), following the key dimension order. We have some plans to use ``kwargs`` for something else in future...

**Comment by jlstevens** [comment]
I've made a PR (linked above) to add an ``args`` attribute. I'll wait for @philippjfr  to review it but first I better test it works as expected...

**Comment by jlstevens** [comment]
It seems to work fine. I noticed one instance where the ``args`` didn't match the state of the sliders (a bit disturbing!) but I can't seem to reproduce that issue now...

**Comment by jlstevens** [comment]
@vascotenner This should now be addressed by PR #1453 which has been merged.

You'll find an ``args`` and ``kwargs`` attribute on ``dmap.callback`` with the information you need. Closing.
