### ISSUE TITLE
Proposal for batched plots

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#716]
In HoloViews you generally create composite plots by creating NdOverlays of Elements varying by some dimension. This is very convenient and creating overlays in this way is very simple using the ``.overlay`` method on HoloMaps. However in terms of plotting this is highly efficient, because the plotting code will generate one plot instance for each entry in the NdOverlay, which can potentially be hundreds or even thousands, which change over time. This problem is made worse by the fact that each plot will then also create a new artist (matplotlib) or glyph (bokeh) for each of the Elements, which can seriously degrade performance.

My proposal is to have a system by which NdOverlays, which have to be consistent in the types of objects they contain, can be rendered as one chunk in a single plotting call, which can provide huge performance boosts. The idea is that if the OverlayPlot encounters an NdOverlay containing an Element type it has registered it passes the NdOverlay directly to this optimized plot to render instead of expanding it into a lot of individual plots. The main requirement for these optimized plotting classes would be that they behave exactly like the unoptimized versions. I'd start with an optimized plot for NdOverlays of Curves because it's both simple and plotting a lot of curves is currently very slow.

**Comment by jbednar** [comment]
Sounds good.  I guess supporting an explicit operation like collate() that reorganizes things after the fact would negate the the performance advantage?  Maybe there could be a parameter on OverlayPlot that determines whether it does this, so that people could turn it off if it causes problems?

**Comment by philippjfr** [comment]
>I guess supporting an explicit operation like collate() that reorganizes things after the fact would negate the the performance advantage?

Not sure what you mean. What I'm describing would happen inside the plotting code so the user would never be aware of it.

>Maybe there could be a parameter on OverlayPlot that determines whether it does this, so that people could turn it off if it causes problems?

That's definitely a possibility, alternatively I'll probably need a registry for these optimized plots somewhere so the user could unregister them there.

**Comment by philippjfr** [comment]
Support for batched plotting has now been merged, closing.
