### ISSUE TITLE
Bug in Layout.clone?

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#723]
I kept getting an error while trying to work on the Collector tutorial regarding the ``_cols`` attribute on Layout in the clone method:

https://github.com/ioam/holoviews/blob/master/holoviews/core/layout.py#L431

Looking at the code, I think this is a bug as ``_cols`` doesn't seem to exist anywhere. I think it is supposed to be copying the value of ``_max_cols`` across instead.

**Comment by philippjfr** [comment]
Looking at the code it seems like this was fixed and I just tested ``Layout.clone`` without any issues. Closing.
