### ISSUE TITLE
Boolean arrays in Bokeh rasters

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#727]
Using boolean arrays in `Images` when plotting with Bokeh breaks:

``` python
/Users/jstevens/miniconda/envs/analytics/lib/python2.7/site-packages/bokeh/core/properties.pyc in prepare_value(self, cls, name, value)
    270                     break
    271             else:
--> 272                 raise e
    273         else:
    274             value = self.transform(value)

ValueError: expected a value of type Real, got True of type bool_
```

As this works fine in matplotlib and can be fixed by casting the booleans to a numeric type, I'm filing this as a bug. I suspect this will be an issue for all raster types, not just `Image`.

**Comment by philippjfr** [comment]
The PR fixing this was merged. Closing.
