### ISSUE TITLE
Improvements to the __call__ method of components

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#73]
This is a feature request based on discussion in #43. In short:

* ``__call__`` should be unified so it always behaves the same way. The shorthand of specifying ``plot`` and ``style`` keywords options without extra type/group/label specification  can always be used (refers to whatever element/container is being called).

* ``__call__`` should support all the features of traverse, including specification using types (i.e classes). Functions already appear to work though.

**Comment by jlstevens** [comment]
This suggestion was originally proposed by Philipp and it seems like a good idea. That said, I remember why currently it doesn't work this way.

### Supported specification formats

When we first factored out the logic of settings options from the %opts magic, we had to decide on a suitable format for setting options. This was tricky, so we came up with multiple variants that are all supported! These are the ways you can set options using ``StoreOptions.set_options``:

1) Complete specification for as many specifications as you want (here just 'Image'), using Python literals only (three levels of dictionary nesting):

```python
options = {'Image': {'style':dict(cmap='Blues'), 'plot':dict(fig_size=50)}
```

2) Complete specification for as many specifications as you want (here just 'Image') that only needs two levels of dictionary nesting but does need to use ``Options`` objects and therefore requires an import:

```python
options =  {'Image':[Options('style', cmap='Blues'), Options('plot', size=50)]}
```

3) Partitioned specifications that don't let you do 'style' and 'plot' options at once but requires one specification dictionary for 'style' and a separate one for 'plot'. Requires two levels of nesting and only uses Python literals. For instance:

```python
style={'Curve':{'linewidth':10 }}
```

4) With the implementation of ``__call__`` on ``Element`` the specification becomes implicit (no other possible elements to refer to) which eliminates another level of nesting:

```python
Curve(style={'linewidth':10 })
```

Currently ``__call__`` on container types support the separate 'style' and 'plot' dictionaries including the ability to address specific objects that are contained.

### Observations

Now we have had this system for a while, here are some observations:

1) Anyone using HoloViews without IPython will not have the ``%opts`` magic and will need a general way to customize all options at every level (i.e everything ``%opts`` allows). For this, there is ``__call__`` as well as three other methods:

a) The context manager:

```python
with StoreOptions.options(im, style=dict(Curve={'linewidth':10 })):
    # Render the object or do something here.
```

b) The imperative approach that acts as if there are side-affects on the object:

```python
StoreOptions.set_options(im, style=dict(Curve={'linewidth':10 })):
```

c) Applying options while saving (see the [wiki page](https://github.com/ioam/holoviews/wiki/HoloViews-without-IPython)):

```python
renderer.save(layout, 'example_I', style=dict(Image={'cmap':'jet'}))
```

2) There are times when ``__call__`` is useful, even in the notebook. You can do some really neat things with it (e.g change the azimuth of a 3D plot over a HoloMap) that would not be feasible with the magic alone. That said, we almost always use the simplest specification (version 4 shown above) for this sort of task.

3) Right now, ``__call__`` on ``Dimensioned`` supports *all* the formats listed above, including mixing them! You can mix 'options' (for most completion format) with the 'style' and 'plot' dictionaries. A single specification is generated from everything specified.

### The compromise

The suggestion is to stop ``Element`` objects from being different from other ``Dimensioned`` and have ``__call__`` such that the 'style' and 'plot' dictionaries apply only to the object being called. This would work well in general (observation 2) and be more consistent.

The reason I have written all this is to explain what this proposal will eliminate: the ability to use specification format 3) in ``__call__``, forcing the 'style' and 'plot' dictionaries to refer to the called element only. 

This does not disable specification formats 1) and 2) as they will be passed in with the keyword 'options' - or alternatively, not as a keyword at all as this complete format type is the default first (positional) argument. In other words, ``__call__`` can still support complete option specification using the a slightly bulkier syntax than the separate 'plot' and 'style' specifications.

### Proposal

On balance, I think consistency and optimizing the common case wins out, even if it means losing some succinctness for pure-Python users. The three ways of customizing in pure-Python (a-c) are still available and do not need to be changed - the new restriction is that in ``__call__``, kwargs named 'style' and 'plot' do not contain specification strings and refer to the current object only.

There is one last suggestion for a format that would still support the old style 'plot' and 'style' specifications:

5)  Checking to see if the dictionary keys are all in the option groups i.e ``['plot','style', 'norm']`` would allow this to be supported in a compatible way:

```python
options = dict(style={'Curve':{'linewidth':10 }},
               plot={'Curve':{'fig_size':50 }})
```

I think this is then the best approach by introducing format 5). As we have too many formats, I would strong discourage format 2) (i.e we should never mention our support for it!) and we are now deprecating 3) in favour of 4). So the overall result is that we have one format less (if we deprecate 2 entirely) while having a more consistent and useful approach for the common case!

As I don't think many people are going to read all this, I'm going ahead with my proposal here unless anyone objects. I would like to hear any comments though! :-)

**Comment by jlstevens** [comment]
I am mostly talking to myself here but it doesn't matter much now it is done.  A lot written for a tiny bit of new code now committed in 0b74e1f (new syntax), 50027aa (call implementation) and f4388a5 (new unit tests).

All this means you can now do this:

```python
im = Image(np.random.rand(10,10))
(im + im)(plot={'hspace':5})
```

Instead of this:

```python
im = Image(np.random.rand(10,10))
(im + im)({'Layout':dict(plot={'hspace':5})})
```

Although the latter does still work.

I will close this issue now but I am happy to reopen it is there is further discussion.

**Comment by jbednar** [comment]
I think your analysis of it makes good sense and is very reasonable.  I too strongly favor deprecating (i.e., not mentioning) the less-useful ways to set the options, leaving only a few much more useful ones for people to have to worry about.
