### ISSUE TITLE
Creating a HoloMap Image().hist() seems impossible.

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#74]
I've tried in in several ways, but it didn't work.

One (for me) obvious one:
```python
a = {1: hv.Image(np.random.randn(10,10)).hist(),
     2: hv.Image(np.random.randn(10,10)).hist()}

hv.HoloMap(a)
```

**Comment by jlstevens** [comment]
Try calling ``.hist()`` after you have created the HoloMap of ``Image`` elements.

**Comment by basnijholt** [comment]
Thanks. 

In this way it's not possible to create a ``HoloMap`` of a histogram of a ``Overlay`` of a ``Image`` and ``Path`` or ``Curve``.

While just ``Image.hist() * Contour`` works fine.

**Comment by philippjfr** [comment]
> In this way it's not possible to create a HoloMap of a histogram of a Overlay of a Image and Path or Curve.

Just tested this. It is possible but you have to set the index of the Element you want to draw the histogram from, e.g. this works:

```python
hv.HoloMap({i: hv.Image(np.random.rand(10, 10)) * hv.Path([np.random.rand(5,2)]) for i in range(3)}, key_dimensions=[hv.Dimension('$E$')]).hist(index=0)
```

**Comment by basnijholt** [comment]
Thanks, that works! 

Because it's not immediately obvious, it will be nice if Shift+Tab doesn't shows some information, or change the error message?

**Comment by jlstevens** [comment]
Better docstrings and exception messages are always a good idea. Anyway, I thought the hist method would take the bottom layer by default in an Overlay?

Either the hist method should complain in a sensible way when encountering overlays or there should be a default behaviour that can be overridden (present the histogram of the bottom layer).

**Comment by philippjfr** [comment]
The fix referenced above should address this issue. HoloMap.hist will now defult to the bottom layer if it encounters an Overlay.
