### ISSUE TITLE
Dynamic Map step size

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#742]
Feature request: Set stepsize for every dimension in a DynamicMap.

The default of 0.00001 is rather small.

**Comment by jlstevens** [comment]
I believe this would relate to the proposal in #843 - the idea is that stepsize in an example of a dimension preference.

**Comment by jlstevens** [comment]
Now that #1245 is merged, I see no reason not to allow this as a dimension parameter.

**Comment by jlstevens** [comment]
Implemented in PR #1257. Closing.
