### ISSUE TITLE
Large distance between key_dimension label and plots for two HoloMaps.

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#75]
No matter how I fiddle around with the options I can't get the distance between the key_dimension label and the plots to reduce:

```python
%%opts Layout [fig_inches=(10,10) vspace=0]
a = lambda: hv.Image(np.random.randn(10,10))
b = {(1,1): a(),
     (1,2): a(),
     (2,1): a(),
     (2,2): a()}
hv.HoloMap(b, **angles) + hv.HoloMap(b, **angles)
```
produces:
![screen shot 2015-05-15 at 11 50 41](https://cloud.githubusercontent.com/assets/6897215/7650672/108b4b3e-faf9-11e4-87cb-df32c36e26b4.png)

But this is OK:
```python
%%opts Layout [fig_inches=(10,10) vspace=0]
(hv.HoloMap(b, **angles) + hv.HoloMap(b, **angles) + hv.HoloMap(b, **angles) + hv.HoloMap(b, **angles)).cols(2)
```
![screen shot 2015-05-15 at 11 54 42](https://cloud.githubusercontent.com/assets/6897215/7650687/4026231e-faf9-11e4-8c4f-58f8b0d208b4.png)

**Comment by philippjfr** [comment]
To be honest I don't think there's any good way to fix this. You asked for a 10x10 inch figure, which means it's square. The plots will always be drawn in the middle, while the figure title will always be drawn at the top. The correct fix is to correctly compute the figure size in the first place as proposed in https://github.com/ioam/holoviews/issues/69, so you don't have to fiddle with the fig_inches manually. I'll close this issue and hopefully come up with a fix for https://github.com/ioam/holoviews/issues/69 over the weekend.

**Comment by philippjfr** [comment]
If you want a temporary fix try something like:

```python
%%opts Layout [fig_inches=(10,4) vspace=0]
```
