### ISSUE TITLE
Readd bokeh resize tool once it is supported again

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#755]
In https://github.com/ioam/holoviews/pull/754 we remove the bokeh resize tool because it is broken in bokeh 0.12. We should readd it when and if bokeh supports it again.

**Comment by jlstevens** [comment]
I've marked this 1.6 on the optimistic assumption than bokeh 1.0 will be released by then. :-)

**Comment by philippjfr** [comment]
Doesn't seem like this will happen before our 1.7 release, postponing it.

**Comment by philippjfr** [comment]
The resize tool has been removed completely from bokeh and it doesn't seem like it will be readded, closing.
