### ISSUE TITLE
labelling .hist() with unit (feature request)

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#78]
I really like the `.hist()` feature, but I'm missing the label to show what the numbers actually mean. It would be nice if it could show the unit somewhere at the top.

**Comment by philippjfr** [comment]
Agreed, there's a few changes we want to make to Histogram plots and this should be one of them. The other is improving the ticks. Currently it labels the center of bins, which isn't ideal as the outer bounds are often unnecessarily verbose, e.g. in a 0-1 range, you'll end up with ticks at 0.05 and 0.95. Both issues should be addressed soon.

**Comment by philippjfr** [comment]
The current workaround for this is:

```python
from holoviews.plotting.mpl import SideHistogramPlot
SideHistogramPlot.show_xlabel=True
```

We should at least enable this by default, if we can't find a better solution.

**Comment by jlstevens** [comment]
One of the many issues with ``AdjointLayout`` is that there is no way of addressing things like ``SideHistogram`` properly with the ``%opts`` magic. 

One day we would like to drastically improve this system but as @basnijholt noted, it is very useful functionality even if the design isn't optimal!

**Comment by philippjfr** [comment]
The adjoined histograms now show the value and unit by default, closing.
