### ISSUE TITLE
Curve, Points, and Scatter plots broken on Safari for Bokeh backend

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#782]
On the Safari browser on Mac OS X, if you use the Bokeh backend, some plot types fail to show any data:

![image](https://cloud.githubusercontent.com/assets/1695496/16768038/17787e96-4808-11e6-9dcd-6bece442249b.png)

The plot types affected appear to be those handled by WebGL, and indeed the curves come back if we turn off Bokeh's WebGL support:

![image](https://cloud.githubusercontent.com/assets/1695496/16768278/4a9fda2a-4809-11e6-991b-9fe906baa498.png)

This appears to be a known [issue in Bokeh](https://github.com/bokeh/bokeh/issues/2683).

We should presumably either turn WebGL off by default in Safari, or emit a warning.

**Comment by philippjfr** [comment]
Just double checked, this has been fixed in bokeh. Closing.
