### ISSUE TITLE
Changing the actual output size of the images in IPython notebook

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#79]
How can I control the size of the image that is put out in the notebook? 

A ``HoloMap.cols(2)`` with ``widgets`` is too small to show in IPython notebook slides.

I would think ``[fig_inches]`` would do the trick, but these are only the aspects right?

**Comment by philippjfr** [comment]
There's a number of ways of changing the size of the plot. Using ``fig_inches`` is the most explicit.

1. Setting the ``fig_inches`` plot option: the most explicit way of setting the size.
2. Setting the ``fig_size`` plot option: scales the autocomputed or explicitly supplied fig_inches as a percentage.
3. Setting ``size`` using the %output magic: Same as ``fig_size`` but applies generally.
4. Setting ``dpi`` using the %output magic: Indirectly increases the plot size by increasing the resolution.

That said I don't think the current sizing is ideal, often you have to increase your plot size or dpi disproportionately to achieve the size you want but then the generated plots are absolutely huge in memory. There should be some way of independently controlling the size of the plot as rendered in the browser independently from the actual plot rendering. Optionally allowing you to set the HTML width and height attributes would do it.

**Comment by philippjfr** [comment]
Maybe I have a better suggestion, instead of explicitly exposing another sizing option (which brings additional confusion), we could add a general ``css`` option to the %output magic, allowing you to customize the style (and therefore the sizing) of the ``<img>`` HTML element.

**Comment by philippjfr** [comment]
Just had a go at implementing the css option, it would apply to all img and video tags, which means it applies to widgets too. Here's a simply example of what it's usage looks like in practice:

```python
%%output css="width: 50%"
hv.Image(np.random.randn(10,10))
```

**Comment by jlstevens** [comment]
Python strings with any sort of code in them make me shudder and that includes CSS.!

A raw CSS string like that looks very ugly to me as it exposes the sad fact of life that we are trying to do real work in the browser - i.e an absolute mess under the hood. :-(

For this reason, I would support but discourage the raw CSS string myself and support a more pythonic looking approach to CSS: a dictionary of string attributes to string values:

```python
custom_css={'width': '50%'}
```

That way we can handle building the string and inserting the semi-colon. In addition, it should be easier to work with as a Python dictionary e.g you could use the $ sign to interpolate a Python dictionary in the namespace into the magic. For instance, you could do:

```python
%output css=$custom_css
```

I think this would be a nicer syntax in general, without removing support for raw CSS strings.

**Comment by philippjfr** [comment]
Got an implementation for the dict based approach, which will also validate the specification against a few valid keywords. Will push the commit just before the next release since all of our display tests will need to be updated.

**Comment by jbednar** [comment]
Would **custom_css be a more appropriate syntax, since it's a form of dictionary expansion?  Not sure.

**Comment by philippjfr** [comment]
The ``$object`` interpolation is an IPython thing and happens before our magic gets the string to process.

**Comment by jbednar** [comment]
Ah.

**Comment by philippjfr** [comment]
Just added the css output magic option as outlined above. Closing this issue now.
