### ISSUE TITLE
Add support for color cycles (maps?) for batched Spikes plots

### ISSUE THREAD

**Issue by canavandl** [ioam/holoviews#790]
Add support for color cycles (maps?) for batched Spikes plots.

**Comment by jbednar** [comment]
Can you provide a simple example?  Philipp tried it and found no problem colorizing batched Spikes, so something reproducible would help get this resolved.  He's probably offline for now.

**Comment by philippjfr** [comment]
This was simply because ``line_color`` wasn't handled the same way as the ``color`` argument in batched mode, I've opened a separate issue for that now: https://github.com/ioam/holoviews/issues/795, so I'll close.
