### ISSUE TITLE
Use multi-dimensional groupby in xarray interface

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#804]
Currently xarray does not support multi-dimensional groupby and aggregation operations directly. The xarray PR https://github.com/pydata/xarray/pull/924/files addresses this, so as soon as that is merged and there is a new xarray release we should replace the custom groupby and aggregation implementations with the inbuilt ones.

**Comment by philippjfr** [comment]
Doesn't seem like this will happen before holoviews 1.7, postponing.

**Comment by jlstevens** [comment]
Just to say I would prefer we leave issues with the 1.7 milestone assigned (even if we don't think they will make it) until the release is imminent. Especially for things that depend on when other packages are released relative to 1.7 (otherwise we might miss out on some easy wins).

**Comment by philippjfr** [comment]
That particular PR did not address exactly what we needed but there's nothing wrong with the current approach we're using for groupby so I'm just going to close this.
