### ISSUE TITLE
Plotting callbacks and overlays

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#806]
Plotting callbacks don't seem to work right with overlays:

``` python
import pandas as pd
import numpy as np
import holoviews as hv
hv.notebook_extension('bokeh')
```

``` python
%%opts Points [callbacks=cbs] Points.SomeGroup (color='red') 
df1 = pd.DataFrame(np.random.rand(100000,2))
df1.columns = ['a', 'b']

df2 = pd.DataFrame(np.random.rand(100000,2))
df2.columns = ['a', 'b']


hv.Points(df1, kdims=['a','b']) * hv.Points(df2, kdims=['a','b'], group='SomeGroup')
```

![image](https://cloud.githubusercontent.com/assets/890576/17367803/61ba1446-5989-11e6-8945-05a6fd5b6523.png)

There is no change to what is shown when zooming in and out. In some circumstances it seems to lock up the kernel but I'm having trouble reproducing that with a simple example.

**Edit:** I should note that it seems fine if you declare two separate callback instances and set them.

**Comment by jlstevens** [comment]
Seems like we should keep this issue in mind as we refactor the callback system...

**Comment by philippjfr** [comment]
Callbacks have been replaced with streams, closing.
