### ISSUE TITLE
Caching system to avoid re-rendering data

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#81]
This is more of a wish-list item than a feature as the problem is quite tricky to solve in a clean, general and robust way. Some of these ideas were touched upon at the end of issue #62.

The basic problem is that notebooks are not good at avoiding re-computation. One simple way to avoid this is to have a cache system whereby you can easily save objects to the cache for easy access later. 

One approach is presented by this [caching magic](https://github.com/rossant/ipycache) installed as an IPython extension. As this general sort of caching is hard to solve for everyone, I'm going to ignore it and discuss caching that is more relevant to HoloViews: caching to avoid re-rendering objects.

As HoloViews uses display hooks, matplotlib plotting will be invoked for object `x` even if object `x` has just been rendered and nothing about it has changed. Obviously, if you switch from gif output to mp4, you'll need to re-render but there are changes that can be made (e.g css properties) that do not require a complete re-render of the object. 

What we could do in HoloViews is cache the base64 encoded display data associated with an object so it can be quickly re-displayed  so long as the cache isn't stale. This is already quite tricky for several reasons:
1. How do you know if the cache is stale or not?
   1. Do you cache everything all the time (memory intensive) 
2. Does the user choose the cache individual objects or not?

What goes _some_ of the way is the existing `%capture` magic:

``` python
%%capture handle
display(object)
```

Which lets you immediately repeat the display using the chosen handle as follows:

``` python
handle.show()
```

Of course, this doesn't have the flexibility we would like: e.g display the object again with different css or perhaps using the 'display' output type instead of HTML (which renders in the GitHub's preview unlike our regular HTML output).

Hopefully, this summarises the key issues around caching display although I have no particular solution to propose right now!

**Comment by jlstevens** [comment]
Just as a quick suggestion to consider, I can imagine something like this:

```python
Store.cache(obj)  # Cache the display output of this object
```

Then the following would re-display the cached data. This should have options to display the data again with modifications that do not require re-rendering (e.g css options):

```python
Store.show(obj)
```

Then to switch off caching:

```python
Store.cache(obj, enabled=False)
```

The main issue is that Store needs a generic interface to the display system, first to get the display data to be cached and then to display the cached data appropriately.

**Comment by philippjfr** [comment]
Is this something we still want to consider? I've not wanted this since it was originally suggested and it seems out of scope. If you really want to avoid re-rendering you can already render it to HTML once and then redisplay it.

**Comment by jlstevens** [comment]
I haven't really found myself wanting this either so I am happy to close this issue.
