### ISSUE TITLE
Changing axes labels with kdims changes the data plot if 'z' is given as a label

### ISSUE THREAD

**Issue by ryanpepper** [ioam/holoviews#810]
I've got some image data that is a slice along a y axis, so I need the x-axis label to be 'x' and the y-axis label to be 'z'. However, I've found that if you give 'z' as an axis label, it changes how the plot looks. Here's a minimal working example:

Generate some random data:
> data = np.random.uniform(0, 100, (100, 100))

Then create an image object:
> a = hv.Image(data, kdims=['x axis', ''z axis'])
![image](https://cloud.githubusercontent.com/assets/8539474/17553989/aba9de66-5f00-11e6-8a09-bd98705c5581.png)

Now if we change the kdims to ['x', 'z']:

> b = hv.Image(data, kdims=['x', 'z'])
![image](https://cloud.githubusercontent.com/assets/8539474/17554007/c0b52efa-5f00-11e6-8a09-4a9b7eafbda9.png)

Oddly enough, if you combine the objects, the b object displays correctly:
> a + b
![image](https://cloud.githubusercontent.com/assets/8539474/17554066/0b1720c0-5f01-11e6-9a70-07dfd3caa86e.png)

This is using Ubuntu 16.04, Holoviews 1.6.1, Python 3.5.2, Matplotlib 1.5.1.

**Comment by jlstevens** [comment]
I believe this is because 'z' is the default name for the value dimension. For instance, if you give the value dimension a different name, it works:

```python
import numpy as np
hv.Image(np.random.uniform(0, 100, (100, 100)), kdims=['x', 'z'], vdims=['intensity'])
```

![image](https://cloud.githubusercontent.com/assets/890576/17561092/6fb30d8a-5f1c-11e6-91e6-ff19581a243b.png)

I agree this can be confusing and maybe we should consider issuing a warning if we detect multiple dimensions in the same element with the same name.

**Comment by ryanpepper** [comment]
Brill, thanks. That's a good enough solution for me for now anyway!

**Comment by philippjfr** [comment]
I agree, disallowing duplicate dimension names on elements with a helpful error message is a good idea.

**Comment by jlstevens** [comment]
I've marked this a bug and assigned myself as a reminder to implement such warnings.

**Comment by philippjfr** [comment]
Accidentally pushed this straight to master, you can see the code here:

https://github.com/ioam/holoviews/blob/master/holoviews/core/dimension.py#L601

Please reopen if there's further issues or you want to improve the error handling.

**Comment by jlstevens** [comment]
@philippjfr Thanks for the fix! I haven't tested it but the code looks fine.
