### ISSUE TITLE
Datashader Operations

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#812]
[Datashader](https://github.com/bokeh/datashader/) provides a great way to rasterize tabular data through 2D aggregation and optionally provides powerful tools for transforming and colormapping the aggregates. By providing an interface to datashader in holoviews we can make it trivial to explore very large datasets meaningfully. In HoloViews we already provide ElementOperations, which can provide parameterized interfaces to transform one or more elements into one or more other Elements. In private discussion we agreed it might make sense to add datashader operations, I'll try to outline how I propose to wrap different parts of the API by going through the different stages of the pipeline so we can discuss it.

### Aggregation

The aggregation step simply provides simple (but fast) 2D binning (at least when using the points glyph):

```python
cvs = ds.Canvas(plot_width=w, plot_height=h, x_range=x_range, y_range=y_range)
agg = cvs.points(df, 'longitude', 'latitude',  ds.count())
```

##### HoloViews API:

```python
class Aggregate(ElementOperation):

    aggregator = param.ClassSelector(class_=ds.reductions.Reduction,
                                     default=ds.count())

    height = param.Integer(default=800)

    width = param.Integer(default=600)

    x_range  = param.NumericTuple(default=(0, 1))

    y_range  = param.NumericTuple(default=(0, 1))
...
```

The idea would be that the general operation would call lower level aggregation operation that execute the aggregation that makes the most sense given the types of the Elements passed to it, i.e. Curves and Path Elements (and NdOverlays of them) are aggregated as paths while points/scatter (and every other >=2D Element) are aggregated as points. 

### Shading

The shading portion of the pipeline simply takes the 2D aggregate and provides custom color mapping.

```python
img = tf.interpolate(agg, cmap=Hot, how='eq_hist')
```

##### HoloViews API

```python
class Shade(ElementOperation):

    cmap = param.ClassSelector(class_=(basestring, bokeh.Palette, mpl.colormap, list))

    how = param.ObjectSelector(objects=['linear', 'log', 'eq_hist'])
```

Input: Image/GridImage or NdOverlay of Images (for categorical colorization)

Output: RGB

Other transforms like dynamic spreading would be exposed in similar ways.

Once we have implemented these operations they can immediately be used directly. The real value will come once we have exposed streams where it should then be possible to easily apply an operation as part of a stream for example to aggregate based on the current zoom level in a bokeh plot.

Edit: We could also consider exposing HoloViews Elements directly to datashader operations. Since datashader supports dynamic dispatching we could easily make this work, which lets datashader looks up the 'longitude' and 'latitude' dimension on a HoloViews Element:

```
agg = cvs.points(element, 'longitude', 'latitude',  ds.count())
```

**Comment by jbednar** [comment]
Sounds like a cool way to use Datashader!  We'll want a nice tutorial about this when it's ready. :-)  

x_range and y_range normally default to the ranges in the data, so they should probably be None here?  Or is that incompatible with the need to add axes in HoloViews?  (Or do we need to make that information available to HoloViews?)

For an hv.Dataset, presumably you'll create the agg by knowing the correct fields to choose from the dataframe, because those will be declared in the Element (Points, etc.)  What about when the source data is not in a Dataset, or is not based on a dataframe?  Will you create a dataframe dynamically in that case?

For Shade.how, do you want to use strings or objects?  Datashader supports either one, but the list of accepted strings is finite, while arbitrary function objects can be supplied if you use the object version.  Not sure which one fits better with the rest of HoloViews.

**Comment by philippjfr** [comment]
>x_range and y_range normally default to the ranges in the data, so they should probably be None here? Or is that incompatible with the need to add axes in HoloViews? (Or do we need to make that information available to HoloViews?)

Right, default of None and auto-ranging seems sensible most sensible here.

>For an hv.Dataset, presumably you'll create the agg by knowing the correct fields to choose from the dataframe, because those will be declared in the Element (Points, etc.). What about when the source data is not in a Dataset, or is not based on a dataframe? Will you create a dataframe dynamically in that case?

Pretty much all HoloViews Elements support the dframe method, which simply returns the data for each dimension as a column. If we decide to go with the approach of exposing HoloViews Elements to datashader operations through dynamic dispatch then we can even smooth over that without having to convert to a dataframe as an intermediate step.

>For Shade.how, do you want to use strings or objects? Datashader supports either one, but the list of accepted strings is finite, while arbitrary function objects can be supplied if you use the object version. Not sure which one fits better with the rest of HoloViews.

Currently holoviews is fairly closely tied to matplotlib colormaps, hv.Palette supports them and bokeh can use them. Maybe we should move away from that but supporting callables including matplotlib colormaps seems like a good idea. Do you think supporting lists of RGB strings/tuples, bokeh Palettes and callables with the same behavior as matplotlib colormaps is too much?

**Comment by jbednar** [comment]
Bokeh palettes *are* lists of RGB strings/tuples, so I think there are only two colormap types to support: callables (assumed to be mpl colormaps) and lists (assumed to be Bokeh palettes, i.e. lists of RGB strings/names/tuples).  That's what datashader supports in shade(), anyway.

But I was talking about the 'how' option, where we have 'log', 'eq_hist', etc., each of which corresponds to a function (looked up using tf._interpolate_lookup).  Currently only eq_hist is a real named function, but we could make them all be named, if that's a better interface at the HoloViews level.

**Comment by philippjfr** [comment]
>Currently only eq_hist is a real named function, but we could make them all be named, if that's a better interface at the HoloViews level.

Might be nice for a user to be able to define their own, what's the signature? Does datashader support custom ones?

**Comment by jbednar** [comment]
Datashader supports either a string or a function, for that reason.  The signature is 
f(d, m), where d is the data and m is a mask; it's basically a transfer function with an explicit mask.

**Comment by philippjfr** [comment]
The initial operations have now been implemented. Further discussion can happen in #908. Closing.
