### ISSUE TITLE
DynamicMap Overlay style ordering

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#815]
In HoloViews we compute a global ordering of the layers in an Overlay, which is what determines color (and other style ) cycles and the zorder. This is no problem if we know all the frames that will be plotted because we can iterate over all of them to determine the global order. However when plotting a DynamicMap we only know the ordering for all the layers that have been plotted up to that point, which means we cannot determine a consistent global ordering.

The way I see it we have two options:

1) We can maintain a global ordering that gets expanded when a DynamicMap returns a new layer. This means that color cycles can change because a frame that is requested could have a lower position in the global ordering than what was plotted in previous frames, shifting the previous order along and potentially changing the colors when you return to a previously plotted frame.

2) We compute the initial global ordering and then simply append to it such that new layers are always given a position in the global ordering that is higher than that of all layers that came before it. The problem with this approach is that the color cycle is basically determined by the order in which you scrub through the space.

These are very subtle issues which will only affect fairly limited use cases, but we have to decide on a consistent policy about this. I'd favor option 1) because it seems more correct and will converge to the correct global ordering as you explore more of the space, but it's still not without its issues.

**Comment by jbednar** [comment]
Very good questions.  Sounds to me like we'll just need to pick one option and document it, whichever one is least unpalatable.

**Comment by jlstevens** [comment]
I think I favor option 1. as well. Anyone thinking about what ``DynamicMap`` means will realize that there is an issue using color cycles and introducing overlays with more curves later on.

Is the ordering determined from the elements in the ``DynamicMap`` cache? I also think we need to be careful about holding onto state that is supposed to be dynamic.

**Comment by philippjfr** [comment]
>Is the ordering determined from the elements in the DynamicMap cache? I also think we need to be careful about holding onto state that is supposed to be dynamic.

Yes, the best it can do is work out the global ordering given all the information it has at that point. At least with option 1) it will correctly reflect that, rather than being completely dependent on the sequence of previous states.

**Comment by philippjfr** [comment]
This is done.
