### ISSUE TITLE
Add support for arbitrary unicode labels

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#819]
It would be nice to be able to easily do something like this example originally from Tony Fast:

![image](https://cloud.githubusercontent.com/assets/1695496/17745360/23ac7a02-6471-11e6-98ca-8cc4f3ba1704.png)

where each marker is a Unicode character.  This could be supported for Points by allowing something like `unicode_marker=u'xxx'` (can't use just `marker` because of ambiguity with mpl's `s`, `o`, etc. symbolic names), or `marker_index='field'` along with `markers=u'yyy'`, where 'yyy' would be a string of Unicode characters to use, in order.

**Comment by jlstevens** [comment]
I assume ``unicode=marker=u'xxx'`` is a typo and you meant ``unicode_marker=u'xxx'``. The latter approach makes sense to me, I'm not quite sure why ``marker_index`` would be better or clearer (to be honest, I don't quite understand that particular suggestion).

**Comment by jbednar** [comment]
It's two different usages; the marker_index version is for when we want a data column (e.g. category) to determine the marker shape, and the other version is if we want a separate Points() object for each category, manually setting the marker shape for each one.  Both seem like valid options in some cases.

**Comment by philippjfr** [comment]
Right, usually you'd either have an NdOverlay where each layer has a different marker (and you would use a Cycle object of different markers) or a single Points object, where you potentially want each individual point to have a different marker (where the marker can be any unicode text). This also links back to https://github.com/ioam/holoviews/issues/768 and perhaps providing a cleaner interface for the various ``X_index`` options you might want.

**Comment by jlstevens** [comment]
I understand what you mean now and yes, I would want to think about issue #768 to figure out a uniform way to handle all the index type parameters.
