### ISSUE TITLE
Make matplotlib a soft dependency of the bokeh backend

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#829]
Currently, you need matplotlib for certain functionality (e.g colormaps) to use bokeh. Even if certain features are missing without matplotlib, I feel the bokeh backend should be usable even without matplotlib installed.

**Comment by philippjfr** [comment]
Quick note, I think the matplotlib compatibility layer in bokeh is already factored out fairly cleanly, so all that has to happen is wrapping imports in try/excepts and for a small number of functions in ``holoviews.plotting.bokeh.util`` to handle the lack of matplotlib gracefully. The other missing piece are the magics, which I think currently assume matplotlib as the default backend, causing all kinds of issues when it's not available. Note a huge job and definitely worth doing.

**Comment by philippjfr** [comment]
You can now use the bokeh backend without installing matplotlib.
