### ISSUE TITLE
HoloMap key_dimension name broke

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#83]
```
a = lambda: hv.Image(np.random.randn(10,10), bounds=(0, 0, 10, 10)).relabel('test1')
hv.HoloMap({1: a(), 2: a()}, key_dimensions=['x'])
```

I just updated and something broke, I was creating a ``HoloMap`` with a ``key_dimension`` which is the same as the y-label. This is because I was taking an Overlay of ``Scatter`` and ``Image`` and I used a point to indicate the position in the graph.

**Comment by basnijholt** [comment]
One temporary solution is to call the ``key_dimensions=[' x']`` when the axis is ``x``.

**Comment by philippjfr** [comment]
This is a general issue, duplicating Dimensions anywhere in hierarchy is not allowed unless they actually share the same space. This is because if you perform a select operation on an object with duplicated Dimensions such as in your example, it will slice both the HoloMap and the Image when selecting for x.

**Comment by jlstevens** [comment]
I think this an issue worth thinking about - we need to be clear about whatever policy we are going to enforce!

Phillip's explains why duplicate names is not something we can allow in one datastructure but we should consider whether there should be a neater way of marking two key dimensions as distinct (even thought they have the same name) to allow users to get round such issues. Adding spaces in the way shown above is an unfortunate workaround.

In our own work, we have used 'x'and 'X' but that is as far as that approach can go. Unicode characters (Python 3) could probably go further to allow appropriately used symbols to denote different things.

In general, I think we recommend picking different, unique dimension labels for a couple of reasons:

1. To avoid semantic confusion: if the dimension genuinely is the same one, having the same name should result in sensible behaviour. In general, having multiple axes that mean different things have the same name can cause confusion in the reader.
2. To avoid your own confusion when using HoloViews. We use key dimension names often so you want to keep it clear and not get mixed up.
3. The technical reasons Philipp described.

In general, I suspect  the better unicode in Python 3 could help keep things distinct and clean but that  isn't to say there can't be valid reasons this situation might not arise. 

What we need to consider is whether this will be a problem in general and maybe consider some way to help the user work round such situations in a neater fashion.

**Comment by basnijholt** [comment]
Before I updated yesterday this was working though.

Let me show you an example in which this behaviour is wanted.

Here on the left I show some phase diagram and then at the left I present a graph which correspond to the parameters indicated by the blue dot.
![screen shot 2015-05-18 at 11 07 57](https://cloud.githubusercontent.com/assets/6897215/7677650/3a9fcba0-fd4e-11e4-8d17-bfc19c337f70.png)
![screen shot 2015-05-18 at 11 08 09](https://cloud.githubusercontent.com/assets/6897215/7677651/3aa0a8f4-fd4e-11e4-9b50-de16d47b367d.png)

**Comment by jlstevens** [comment]
Just to say it is very pleasing to see fairly  such pretty, animated plots being generated with HoloViews for real research. :-)

If you had some example notebooks you would like to showcase, we would be delighted to host them and present them from our main website. Our own focus is on computational neuroscience so having examples from solid-state physics would be a fantastic way to show the ways we can assist research across scientific disciplines.

Of course, we realize that you may not have any material suitable for public viewing or you may be too busy to polish any notebooks at this time. I would just like you to be aware that if you ever have any notebooks that you are happy to make publicly available, then we would be very happy to host or link to them. :-)

Back to the issue at hand: your plots look fine to me and I don't see any issue with the dimension names myself. Personally, I see no obvious reason why this shouldn't work the way you intend but Philipp is the one who knows the details. I hope we'll either be able to suggest a better approach or implement something that will help you achieve what you already had working before.

**Comment by philippjfr** [comment]
I'll have to think whether there is an easy way to support this again. The only reason why this would have worked correctly before is because select **wasn't** working correctly. One possible solution would be to make select more like .map and .traverse, where you can supply specs and/or types to apply a select to. This still wouldn't guarantee that everything works but the plotting code could then apply the selection exclusively to the HoloMaps to get the right frame.

**Comment by jlstevens** [comment]
I discussed this issue with Philipp and figured out how to generalize select to both be correct and work appropriately for plotting (the reason your example stopped working).

The commit that closed this issue should make your nice example above work correctly again. Please comment if you find it still doesn't work (we'll reopen the issue) or if you are interested in the offer of showcasing both your work and HoloViews in a publicly available notebook.

**Comment by basnijholt** [comment]
Yes is does work again, thanks a lot!

And of course I will be willing to create a nice IPython notebook full of beautiful plots! I am a big supporter of the work you guys are doing and am pretty determined in adapting HoloViews as my standard plotting tool (something you guys have probably already noted, judging by the amount of bug reports).

I'll have to wait a bit though until we've published the data, might might be a few months, but after that I'll be willing to write out a nice piece of physics with some interactive plots full of nice HoloViews features ;)

**Comment by jlstevens** [comment]
> I'll have to wait a bit though until we've published the data, might might be a few months, but after that I'll be willing to write out a nice piece of physics with some interactive plots full of nice HoloViews features ;)

That would be great! 

We have had Masters students use early versions of HoloViews in their thesis submissions but so far,  there haven't been any peer-reviewed papers completed with it yet! I am also hoping to submit a paper in the next few months so we'll find out who will be the first to publish a paper using these nice notebooks. :-)
