### ISSUE TITLE
Without nbformat package display hooks automatically archives

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#836]
The exporting/archiving code has a bug when the notebook archive is not available for whatever reason (e.g. if nbformat or nbconvert cannot be imported). The display hook always calls:

```
holoviews.archive.add(element, html=html)
```

which is a no-op if exporting hasn't been enabled on the NotebookArchive. However the regular FileArchive will always process the add event, whether or not exporting has been enabled.

**Comment by philippjfr** [comment]
I believe this has been resolved in the PR referenced above. Closing.

**Comment by jlstevens** [comment]
Yes. The referenced PR fixed this.
