### ISSUE TITLE
Consistency between matplotlib and bokeh tables

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#853]
Currently bokeh and matplotlib tables behave a bit differently: when there are many rows, matplotlib uses '...' to skip rows. Bokeh tables don't do this but they can support many more rows as you can scroll.

Should they be consistent and should bokeh tables support the same plot options (e.g `max_rows`?). Of course, we could increase the value of `max_rows` to a large number (e.g 5000) for bokeh so rows would only be skipped for very large tables.

I started making the bokeh backend more consistent with matplotlib but stopped because of two problems:
- The `_cell_value` and `pprint_value` methods would be duplicated across backends. To avoid this they could become utilities although they would be fairly ugly due to the large number of necessary arguments (that are currently on `self`).
- The more complete matplotlib approach uses `pprint_cell` on the table which is unfortunately very inefficient.`Tabular.pprint_cell` indexes into `values = self[dim.name]` at the end which create an array for every cell pretty printed (!!).

We have three options in order of increasing work:
1. Do nothing and leave the Bokeh backend with fewer options.
2. Make them consistent and accept the inefficiency.
3. Make them consistent and make `pprint_cell` less inefficient.

I assume we are aiming for option 3, just not immediately?

**Comment by philippjfr** [comment]
The main issue here is about efficiently indexing and slicing into a table by index not value. We've long discussed providing an API to do this so we should probably get that discussion started again, and then come back to this as it will resolve the inefficiency of ``pprint_cell``.

**Comment by philippjfr** [comment]
I'd like to close this, the two backends have very different limitations, in bokeh you can scroll while in matplotlib you can't. Since the introduction of ``iloc`` we also provide and easy way to index tables. Additionally bokeh cells should be formatted on the frontend to allow linking tables and plots and editing the tables. The inefficiency problem has also been solved using ``.iloc``.

If you disagree please reopen.
