### ISSUE TITLE
Allow different values types on Dimension

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#857]
Currently ``Dimension.values`` only allow lists of values, which can be annoying because often the values are originally in an array or a pandas Series. In addition it would be sensible if the widgets also ignored duplicate values so the user does not have to do explicitly ensure they supply a set of values.

**Comment by jlstevens** [comment]
I'm happy to work on this so I've assigned myself.

**Comment by jlstevens** [comment]
Hopefully, I addressed this in #859 (merged) so I'll close this issue. I'm happy to re-open if if there are any related problems/requests.
