### ISSUE TITLE
Bounds in HoloMaps don't respect visibility style option

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#86]
The following holomap is rendered with the bounds visible even though visible is set to False:

```python
%%opts Bounds (visible=False)
import holoviews as hv
penguins = hv.RGB.load_image('./doc/assets/penguins.png')

hmap = hv.HoloMap()
for i in range(0, 5):
    hmap[i] = (penguins * hv.Bounds((-0.08, -0.08, 0.08, 0.08)))
hmap
```

But if you look at a single overlay, the visibility option is respected again and the bounds aren't visible:

```
hmap.last
```

**Comment by philippjfr** [comment]
Just pushed a fix for this issue in 2ea15e8c. Will close this issue now.
