### ISSUE TITLE
deprecation warning with Matplotlib-2.0.0b4 / Holoviews-1.6.2

### ISSUE THREAD

**Issue by stonebig** [ioam/holoviews#866]
Hi,
I get this deprecation warning with Matplolib-2.0.0b4 Holoviews 1.6.2

````
import holoviews as hv
%load_ext holoviews.ipython
fractal = hv.Image(image)

((fractal * hv.HLine(y=0.16)).hist() + fractal.sample(y=0.16))
`````

````
C:\WinPython\basedir35\buildQt5\winpython-64bit-3.5.x.3\python-3.5.2.amd64\lib\site-packages\holoviews\plotting\mpl\element.py:152: MatplotlibDeprecationWarning: The set_axis_bgcolor function was deprecated in version 2.0. Use set_facecolor instead.
  axis.set_axis_bgcolor(self.bgcolor)
````
![holoviews-20160918a](https://cloud.githubusercontent.com/assets/4312421/18615166/78b8c284-7d9f-11e6-86fd-160df701ea5c.PNG)

**Comment by stonebig** [comment]
https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/axes/_base.py#L2717..L2726

**Comment by jlstevens** [comment]
Thanks for reporting this and thanks for submitting a PR!

I haven't personally tried out the matplotlib 2.0 beta yet though it is definitely we need to test properly soon.

**Comment by philippjfr** [comment]
Just merged the PRs. Thanks for making those fixes, closing.
