### ISSUE TITLE
Accept xarray DataArray

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#869]
Currently the xarray interface only supports an xr.Dataset, however a user often has a simple xr.DataArray so the interface should be able to accept a DataArray and automatically wrap it in a Dataset so it can interface with it. This avoids the user from having to do something like:

```python
hv.Dataset(xr.Dataset({'value': xarr}))
```

**Comment by jlstevens** [comment]
So after this proposal is implemented, you will simply need ``hv.Dataset({'value': xarr})`` presumably?

If so, this proposal makes perfect sense to me. Though is there anything else that might be of interest to HoloViews that is passed as an argument to the ``Dataset`` constructor?

**Comment by philippjfr** [comment]
No, it will just be:

```python
hv.Dataset(xarr)
```

where the xr.DataArray should specify the name of the data variable.

**Comment by jlstevens** [comment]
Ok, that also makes sense. If there really is no other information HoloViews needs from the ``xr.Dataset`` then I imagine that this will make things much more convenient for xarray users.

**Comment by philippjfr** [comment]
This has been supported since #894. Closing.
