### ISSUE TITLE
%%opts magic doesn't complain if you set style options on Overlays

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#87]
You don't hear any complaints from the opts magic if you try this:

``` python
%opts Overlay (foo='bar')
```

This is probably because `Overlay` doesn't take any style options at all. This isn't a priority fix because:
- Tab-completion won't lead you astray. No completion suggestions are given which does imply that no options are going to be processed.
- Nothing is broken as such; this is just a hole in our validation.

**Comment by philippjfr** [comment]
Style options on Overlays have controlled the legend for a long time, while we could decide that's a bit weird that's an issue that should be raised separately.
