### ISSUE TITLE
Tutorial for xarray support

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#870]
xarray datasets are now supported, however, there is no tutorial on this yet.

**Comment by philippjfr** [comment]
There are now guides for working with gridded data including the [Getting started guide](http://holoviews.org/getting_started/Gridded_Datasets.html), [User Guide](http://holoviews.org/user_guide/Gridded_Datasets.html) and [GeoViews Guide](http://geoviews.org/Gridded_Datasets_I.html).
