### ISSUE TITLE
Two datapoints with errorbars

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#872]
Two datapoints with errorbars does not plot with the mpl backend:
```
hv.ErrorBars(([0,1],[1,2],[0.1,0.2]))
```

Works
```
hv.ErrorBars(([0,1,1],[1,2,2],[0.1,0.2,0.2]))
```

**Comment by jlstevens** [comment]
Definitely a bug. Thanks for reporting this!

**Comment by philippjfr** [comment]
Fixed in PR referenced above. Closing.
