### ISSUE TITLE
Improving Path/Curve for easy setting of color gradient along line

### ISSUE THREAD

**Issue by RafalSkolasinski** [ioam/holoviews#877]
It would be really awesome improvement to Path/Curve if one could add additional parameter that would be used to color line according to some color map. 

Something like is done [here](http://nbviewer.jupyter.org/github/dpsanders/matplotlib-examples/blob/master/colorline.ipynb) with `Matplotlib`.

**Comment by jlstevens** [comment]
Thanks for the feature request!

I believe this relates to issues #877 and #102.

**Comment by jbednar** [comment]
#102 is clearly related, but #877 is *this* issue; did you mean to link to another one?

**Comment by jlstevens** [comment]
Oops! I think I meant #416 - well spotted!

**Comment by jbednar** [comment]
It looks like some of #416 may already be done as part of GeoViews; not sure about the rest!  @philippjfr?

**Comment by philippjfr** [comment]
This is now supported since #1991 and there is an example in the Path reference gallery entry. Closing.
