### ISSUE TITLE
``matplotlib==1.5.3``: kernel crushes without ``%matplotlib inline``

### ISSUE THREAD

**Issue by RafalSkolasinski** [ioam/holoviews#878]
Bug occured after updating to `matplotlib==1.5.3`

When working via jupyterhub (without X server) following cause restart of notebook:

``` python
import holoviews as hv
hv.notebook_extension()
```

The only way to avoid this is to set

```
%matplotlib inline
```

before calling `notebook_extension`.  However that was not necessary before.

**Comment by philippjfr** [comment]
Is this still the case for you? Can't seem to reproduce right now.

**Comment by philippjfr** [comment]
Unless you tell me you can still reproduce this issue I'm going to close.

**Comment by RafalSkolasinski** [comment]
Seems like this is not a problem anymore.
