### ISSUE TITLE
Split the Elements notebooks into pieces

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#879]
This issue summarises a discussion I've have with @jbednar and @philippjfr 

We would like to get rid of the existing elements notebooks and have an Elements section in the website sidebar which expands with a list of all the elements. At the top of this list would be a navigation page showing a grid of thumbnails for all the different backends.

Each element notebook would then show how that element is constructed across backends. This proposal has the following advantages:
1. Makes it easier to add new elements (no need to update the whole notebook)
2. Makes it easier to test elements (identify which element went wrong given a failure)
3. Makes it easier to update those notebook tests
4. Make it easier to compare elements across backends.

To generate thumbnails, we would use a notebook archive. These thumbnails would be shown in a grid and there could be buttons to toggle the thumbnails between backends (unsupported elements would be greyed out appropriately).

This could all be organized in `doc` in an Elements subdirectory. For instance, I can imagine the following file paths:

``` bash
doc/Elements/Index.html
doc/Elements/Image.ipynb
doc/Elements/thumbnails/mpl/Image.png
doc/Elements/thumbnails/bokeh/Image.png
```

**Comment by jbednar** [comment]
Thanks for the summary!

**Comment by philippjfr** [comment]
I still need to do Surface and Trisurface otherwise this is ready.

**Comment by jlstevens** [comment]
I think we also decided to do something similar for the container notebooks in the end.

**Comment by philippjfr** [comment]
Added Surface and Trisurface today, closing.
