### ISSUE TITLE
Feature request: converting HoloMap to DynamicMap

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#882]
I use `DynamicMap`s to show a lot of data, sometimes ~1000 plots with 7 variables.

I love how easy it is to compose a `HoloMap`, but it's not useful because rendering it takes a very very long time.

The `DynamicMap` offers a solution to this problem, but it's more cumbersome to write.

Putting a 1000 plots in a `HoloMap` is still quite cheap (just a couple of seconds), therefore I would like if I could just apply `hv.DynamicMap` on a `hv.HoloMap` to get the ease of use of a `HoloMap`, but at the speed of a `DynamicMap`.

**Comment by philippjfr** [comment]
You should just be able to create a DynamicMap from a HoloMap using:

```python
hv.core.operation.DynamicFunction(hmap)
```

However is there any reason not to simply use:

```python
%output widgets='live'
```

**Comment by basnijholt** [comment]
> However is there any reason not to simply use:
> `%output widgets='live'`

This is very slow and takes a few minutes before I see anything.

> You should just be able to create a DynamicMap from a HoloMap using:
> `hv.core.operation.DynamicFunction(hmap)`

That is great! I'll try it out 😄

**Comment by basnijholt** [comment]
`hv.core.operation.DynamicFunction(hmap)`

Has a few problems still, it doesn't set the `set` of the dimensions:
<img width="824" alt="screen shot 2016-09-23 at 15 11 47" src="https://cloud.githubusercontent.com/assets/6897215/18786827/24c5a638-81a0-11e6-9cb5-6515f6536190.png">

<img width="302" alt="screen shot 2016-09-23 at 15 11 52" src="https://cloud.githubusercontent.com/assets/6897215/18786831/2955c9c6-81a0-11e6-94e6-7d6c5f239405.png">

**Comment by philippjfr** [comment]
Thanks for the bug report, should be an easy fix.

**Comment by philippjfr** [comment]
This function will be moved and renamed to ``hv.util.Dynamic`` in the next release.

**Comment by philippjfr** [comment]
``hv.util.Dynamic`` now exists and the bugs described here have been resolved. I will close, please reopen if you encounter any issues.
