### ISSUE TITLE
Bokeh FuncTickFormatter signature change in 0.12.3

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#885]
In the upcoming release of bokeh the signature of the FuncTickFormatters will change requiring a change in the way they are used in holoviews.

**Comment by jlstevens** [comment]
I've assigned the v1.7.0 milestone on the assumption that this is the next HoloViews release and that these changes to bokeh will still be relevant at that time.

**Comment by stonebig** [comment]
users wanting Bokeh-0.12.3 to get matplotlib2 fixes, may also wish the Holoview fix. 

v1.7.0 seems too far away

**Comment by jlstevens** [comment]
> v1.7.0 seems too far away

We've been discussing the possibility of some sort of release before then but nothing concrete has been decided yet.

**Comment by philippjfr** [comment]
So I've just investigated this and it seems bokeh has made the function signature inconsistent with what we can support. A valid bokeh FuncTickFormatter now looks like this:

```python
def ticker():
    return "{:.0f} + {:.2f}".format(tick, tick % 1)
```

i.e. it no longer supports a first argument and instead defines ``tick`` as a special value, which is made available in the namespace of the function. I'm now not sure how we can get around this, except allowing this signature in general somehow.

**Comment by philippjfr** [comment]
This has now been fixed. Closing.
