### ISSUE TITLE
Options notebook tests are extremely fragile

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#89]
Everytime we make any change to a parameter name, parameter docstring or style option, the Options notebook tests fail (due to the `hv.help` output in that notebook). This means, we consistently have to:
- Generate updated test data (display data) for Python 2 and 3.
- Push the reference data.
- Update the submodule reference.
- Rerun the tests on Travis.

This is wasting a lot of time and causing a lot of meaningless commits (submodule reference updates). The only good thing about this situation is that when the Options notebook fails it typically means we have some API change (but it could also be a simple docstring change, e.g a typo fix!)

We would add ignore patterns to the testing code but there is too much output to try and match and ignore every time.

**Comment by jbednar** [comment]
We could add support for something like the ``pyflakes-ignore`` tags we use in the source code, such that if there is a certain keyword in a comment in the input cell (``# nb-testing ignore``?), the output cell is ignored.

**Comment by jbednar** [comment]
Oh, this is still open?  I thought this feature had been implemented ages ago.  Clearly wishful thinking! :-)

**Comment by philippjfr** [comment]
At this point I'm going to close this, we're hoping to switch to nbval at some point and I haven't actually encountered any issues with Options tests in a long time.
