### ISSUE TITLE
Switch mybinder badge

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#890]
The [holoviews-contrib](https://github.com/ioam/holoviews-contrib) repository is quite new and I hope it takes off. If all goes well, the mybinder badge should direct to the mybinder of that repository.

In addition, this issue is a reminder to link the README and the website to `holoviews-contrib` once it is in a more complete state.

**Comment by philippjfr** [comment]
@jlstevens Would you mind adding a badge to our README now that binder 2.0 is out?

**Comment by jlstevens** [comment]
Sure! I'll do that soon but it doesn't need to hold up 1.9.2 as it is just a docs change.

**Comment by philippjfr** [comment]
Sure, sounds good.

**Comment by jlstevens** [comment]
I think this issue can be closed now #2201 was merged.
