### ISSUE TITLE
Callable API for stream-enabled Bokeh overlays

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#895]
The new bokeh streams system is coming along nicely and working really well for a ton of simple examples. This issue documents discussion I've had with @philippjfr about how we can use bokeh streams in more complex examples. 

I'll start by listing the specific hole in the system we have currently:
- If you use Bokeh streams to get interaction information from the browser...
- ... and if your visualization involves overlays

... then HoloViews faces a problematic ambiguity. Alternatively, if you have two dynamic maps using streams (implicitly defined source elements) you face the same issue, even if they only return simple elements e.g:

``` python
dmap1 * dmap2
```

In essence, there HoloViews has to find the full set of applicable streams, making sure that the relevant information comes from the appropriate part of the plot and is directed to the appropriate DynamicMap.

The true core of this issue, is that a callback is a black box (code) that can return complicated datastructures (e.g overlays). We need to look into that black box to establish the relationships between the applicable streams and the various components of the output.

Our proposal is to define an API for DynamicMap callbacks (specifically callables) that enable Bokeh interactive streams to be used with composite returns (i.e Overlays). We cannot get the information we need from a regular Python function, but an appropriate callable class could expose the API that we require. The overall notion is something like `traverse` for `DynamicMap` - a way to dig into the structure that will be returned by a callback.

For instance, `dmap1 * dmap2` already returns a new `DynamicMap`. After this proposal, the callback of this DynamicMap would be an instance of `OverlayCallable` obeying the `Callable` API. This callback has something like the `traverse` method that lets you collect all the nested streams. For instance, `dmap1` might have been composed from  `dmapA * dmapB`.

 HoloViews would automatically use this `Callable` API as necessary so it is (mostly) invisible to users. Users can continue to use generators, lambda functions or any other callable they want with `DynamicMap`, but if they want to output overlays and streams with Bokeh interaction, they need to follow the `Callable` API. Note, if their callables output simple elements, `dmap1 * dmap2` would now work automatically, with HoloViews handling this machinery behind the scenes.

This could be enforced by an exception message raised by the Bokeh backend when a DynamicMap returns an `Overlay` and has streams specified. The message could be something like: 

'Callback API not found. This API is needed by DynamicMaps that have Bokeh streams enabled and that also return Overlays. For more information about this API see ....'

In addition to overlaying, operations would need to follow this API to avoid breaking the chain when things get nested. Although the concrete use case is quite specific right now (Bokeh streams with overlays), an appropriate `Callable` API could be a powerful and useful thing to have in general when working with complex, nested `DynamicMaps`.

**Edit:** This issue probably makes little sense to anyone other than the other HoloViews devs i.e Philipp!

**Comment by philippjfr** [comment]
This has now been implemented but the API still needs to be documented.

**Comment by philippjfr** [comment]
Apparently there is an existing issue to document this (https://github.com/ioam/holoviews/issues/1064), closing.
