### ISSUE TITLE
Clean up Bokeh backend when Bokeh 1.0 released

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#901]
Currently there is some ugly conditional code in the bokeh backend to maintain compatibility between bokeh versions. Once Bokeh releases 1.0, that will define a more stable API and I think we should then drop support for earlier Bokeh versions.

**Comment by philippjfr** [comment]
All our backward compatibility code was removed for bokeh 0.12.10, so I'm going to close this. It could be reopened if we add any new backward compatibility code.
