### ISSUE TITLE
Support transposing layouts?

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#909]
Right now, layouts are filled with plots in row order, i.e. left to right and then top to bottom:

![image](https://cloud.githubusercontent.com/assets/1695496/19167404/2f7874b2-8bd1-11e6-8b3a-c52fe45c111b.png)

Sometimes it makes much more sense to order the plots in column order, i.e. top to bottom and then left to right, as in this case, to align related plots.  It is possible to reorder the plots in the layout manually:

``` python
def lay_out_in_columns(_list, cols, spacer=hv.Empty()):
    """Given a list, reorder it into the number of columns specified, filling missing items with the given spacer."""
    rows = int(np.ceil(len(_list)*1.0/cols))
    padded = _list + [spacer] * (rows*cols-len(_list))
    return list(np.array(padded).reshape(cols,rows).T.flat)
```

![image](https://cloud.githubusercontent.com/assets/1695496/19167464/6e005614-8bd1-11e6-97a7-304e8d29561a.png)

This works, but it's awkward, and if subfigure labels weren't suppressed here they would still be in row order, which would be confusing.  So it would be great if there were a plot option to transpose the layout after it has been assigned subfigure labels.

**Comment by basnijholt** [comment]
Seems related to https://github.com/ioam/holoviews/issues/130.

**Comment by jlstevens** [comment]
@basnijholt Thanks for linking to issue #130!

For ``GridSpace``, using the ``reindex`` method worked as that object has its own dimensions. The difference with Layouts is that they can contain heterogeneous mixtures of different element types so I don't believe the same approach will work here.

Certainly a worthwhile comparison to make and definitely something we want to document better.

**Comment by jbednar** [comment]
The layout is essentially just an ordered list, and thus doesn't have any inherent dimensions to transpose directly.  It's only when it's laid out for display that it gets put into a row, column format.  So in the code above I'm reordering this list so that the eventual result is in column order, but really this needs to be something that the layout engine decides as it puts into a columnar shape.

**Comment by philippjfr** [comment]
The ``transpose`` plot option has now been added for all backends, closing.
