### ISSUE TITLE
Plots missing in Overlay of DynamicMap

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#914]
```
dm1 = hv.DynamicMap(lambda x: hv.Curve(np.random.rand(10)), kdims=[hv.Dimension('x', values=[0, 1, 2])])
dm2 = hv.DynamicMap(lambda x: hv.Curve(np.random.rand(10)), kdims=[hv.Dimension('x', values=[1, 2, 3])])
dm1 * dm2
```

gives only `x = [1, 2, 3]`
but

```
dm2 * dm1
```

gives `x = [0, 1, 2]`

while ideally, I would think you would expect `x = [0, 1, 2, 3]`

**Comment by jlstevens** [comment]
I agree this is a bug - this should be easy to fix as we just need to make sure that when overlaying DynamicMaps, the resulting dynamicmap has a new dimension object with the union of declared values.

This muddies things a little in terms of dimension identity, but we have a plan to address this outline in issue #843 - Dimension``values`` will be part of the dimensions preferences as opposed to their identity.

**Comment by philippjfr** [comment]
Seems appears to have been fixed as the ``values`` are now merged in the overlaying. Please reopen if you encounter issues.
