### ISSUE TITLE
Title position

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#915]
A screenshot says enough:

<img width="897" alt="screen shot 2016-10-09 at 04 20 34" src="https://cloud.githubusercontent.com/assets/6897215/19217347/b9d1a9cc-8dd8-11e6-8502-17a33c46c547.png">

Is it possible to move the title up?

**Comment by philippjfr** [comment]
It might be possible to avoid this by setting more conservative ``fig_bounds`` such as:

```python
%%opts Layout [fig_bounds=(0.1, 0.1, 0.9, 0.8)]
```

which expresses where the axes are to be drawn in unit space as a tuple of (left, bottom, right, top). You'll want to adjust the ``top``.

**Comment by philippjfr** [comment]
Going to close this as there is a workaround and it won't get addressed without rewriting the layout code (which is on the roadmap).
