### ISSUE TITLE
hv.Distribution styling wrong with Bokeh backend

### ISSUE THREAD

**Issue by mrksr** [ioam/holoviews#917]
Using the Bokeh-Backend for plotting, `hv.Distribution`-Plots only work partially and do not have proper styling.

Using this data set:

``` python
import numpy as np
import holoviews as hv
hv.notebook_extension("bokeh")

hvset = hv.Dataset({"Noise": np.random.normal(size=(1000,))}, vdims=["Noise"])
```

The outputs using matplotlib and bokeh are the following:

``` python
%%output backend="matplotlib"

hv.Distribution(hvset)
```

![Distribution with Matplotlib-Backend](http://i.imgur.com/Pw883w2.png)

``` python
%%output backend="bokeh"

hv.Distribution(hvset)
```

![Distribution with Bokeh-Backend](http://i.imgur.com/Mc5eMKU.png)

**Comment by philippjfr** [comment]
I believe this is down to the [mplexporter](https://github.com/mpld3/mplexporter) package works. I don't think there's much we can do to improve this behavior.

**Comment by jlstevens** [comment]
So seaborn elements make use of mplexporter when using the Bokeh backend? Makes sense given seaborn is designed around matplotlib.

As mplexporter isn't particularly reliable (as this issue demonstrates) I think it might be worth evaluating how many of these seaborn elements are working properly with Bokeh. Then we have five options:

1. Decide that it works well enough overall and simply acknowledge the cases where it doesn't work well  (e.g the examples in this issue).
2. Disable the bokeh backend for these elements if we decide mplexporter isn't behaving reliably enough.
3. Implement proper bokeh plotting classes to support these elements without using mplexporter. This might be tricky depending on how complicated the seaborn plots are and also means the plots are no longer directly seaborn.
4. We could decide to support seaborn-like elements without actually using seaborn/mplexporter which means implementing our own plotting classes for the matplotlib backend as well. 
5. Improve mplexporter although this doesn't seem to make much sense as development doesn't seem particularly active.

I'm not recommending any one of these options right now - I am only enumerating them!

**Comment by philippjfr** [comment]
Closing this, bokeh deprecated support for mplexporter and we removed it.
