### ISSUE TITLE
Overlayed Histograms share same color using Bokeh backend

### ISSUE THREAD

**Issue by mrksr** [ioam/holoviews#918]
Overlaying two histograms using the Bokeh backend makes them share a color. This is not the case using the matplotlib-backend.

``` python
import numpy as np
import holoviews as hv
hv.notebook_extension("bokeh")

hvset = hv.Dataset({
    "Noise": np.random.normal(size=(1000,)),
    "More Noise": np.random.normal(loc=5, size=(1000,))
}, vdims=["Noise", "More Noise"])

hv.Overlay([
    hv.operation.histogram(hvset, dimension="Noise", adjoin=False, bin_range=(-5, 5), num_bins=40),
    hv.operation.histogram(hvset, dimension="More Noise", adjoin=False, bin_range=(0, 10), num_bins=40)
])
```

![Overlayed Histograms](http://i.imgur.com/ykEBT3L.png)

**Comment by jlstevens** [comment]
Definitely a bug in the bokeh backend - whether it is just the style definitions or something else in the code. Thanks for reporting this!

**Comment by philippjfr** [comment]
Yes, this is just down to the default style definition. We should just make it match matplotlib, here's the current setting:

```
options.Histogram = Options('style', fill_color="#036564", line_color="#033649")
```

It should probably be this instead

```
options.Histogram = Options('style', line_color='black', fill_color=Cycle())
````

**Comment by jlstevens** [comment]
I would be happy to see this style change committed straight to master - in my view, this is just fixing a bug.

**Comment by philippjfr** [comment]
Now fixed, it required updating the bokeh tests.
