### ISSUE TITLE
Support for a holoviews.rc file

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#92]
This has been suggested as an idea before and cropped up recently at the end of issue #69 

Here are some good reasons I can think of to support an rc file:

* Follows a convention (i.e rc files in general) and won't contain much code. People should be able to look inside, see a relatively small amount of code and immediately understand what it is about.
* Good place to switch the matplotlib backend to 'agg' by default. An rc file is a pretty explicit way of modifying behaviour that is not rude (i.e switching the backend without making it easy for the user to override that decision).
* Good place to customize your defaults, e.g the ``rc_params`` on Plot, customize element styles to your liking etc.
* Nice *persistent* and reliable entry point for the user to customize anything they wish that should always works (e.g whether they use pure Python or IPython Notebook). 
* Much better solution than repeating some boilerplate at the top of every notebook (for instance).
* Certainly more flexible and reliable than a matplotlibrc

The main issues are to decide 1) where to look for the file 2) in what order 3) what should the file be called?

**Comment by jlstevens** [comment]
Talking to Philipp and thinking about the PyPI release I propose the following policy which (for simplicity) only execfiles either *one* or *zero* rc files (no chaining):

1. If the environment variable ``HOLOVIEWSRC`` exists and points to a file then ``execfile`` it.
2. If none of the above and there is a ``holoviews.rc`` in home  then ``execfile`` it.
3. If none of the above and there is a ``holoviews.rc`` in ``~/.config/holoviews/`` then ``execfile`` it.
4. If none of the above and there is a ``holoviews.rc`` the local directory (i.e next to the main ``__init__``) then  ``execfile`` it.
5. Otherwise skip.

This is nice because if pip users install holoviews and don't like our switching the backend (or want to customize something) they don't need to know where holoviews is installed (they can use options 1-3 inclusive.)

I was also a little worried that a fixed filename without chaining might be limiting - you could use such rc files as a cute way of carrying around collections of default settings for holoviews. This should still be possible as you could use ``holoviews.rc`` to execfile something else if you wanted!

I can imagine some creative use of such chaining e.g using ``holoviews.rc`` to execfile all the files in a 'templates' folder that contain all your favourite settings nicely factored into pieces. Of course, you would need to ship such templates together with any other code if you want reproducibility (but that is true of all user written code anyway).

**Comment by philippjfr** [comment]
I think we all agree an rc file would be very useful and I would be happy with the behavior as you describe it. Is this still targeted for the next release (v1.1.1)? If so it'd be great if we could get this committed asap so we can have the development freeze you suggested for the next few days.

**Comment by jlstevens** [comment]
I would like to have this for 1.1.1 but there are a few things I am not entirely sure about. As an rc file is for the user to customize, I am not convinced step 4. above is a good idea.

The only reason we want this step is to switch the matplotlib backend in a way the user can easily override. I am not sure if there would be problems switching the backend to agg by default in ``__init__.py`` and have the user's rc file switch it to something else (if present in locations 1-3).

If quickly switching backends back-and-forth like this is an issue, you could do things more declaratively without *encouraging* side-effects in the rc files. You could set the backend in the rc file like this:

```python
holoviews_rc = dict(
   matplotlib_backend='agg'
)
```

Then if you find an rc file, ``execfile`` it and  look for the ``holoviews_rc`` dictionary for any instructions. If you find a matplotlib backend rc file there, you can use that, otherwise just default to 'agg'. This still supports arbitrary python code in the rc file but eliminates the need to have the matplotlib backend switching code there by default. The main advantages I see of this approach:

* No need to add another (mostly empty) file to the main holoviews package.
* Good behavior when there is no rc file at all.
* No worries about users having to find the holoviews rc file somewhere in their site-packages.
* A clear distinction between the rc file and regular holoviews source code (the rc file is for user control without ever having to know where the holoviews source code is located).

Thoughts?

**Comment by philippjfr** [comment]
I do agree, shipping a mostly empty rc file seems pointless. If we did something like IPython, which ships a configuration file with a bunch of commented out options it might be worthwhile but I don't think we need to do that now.

So I agree with the revised proposal, I **think** switching backends twice shouldn't be an issue but we should test it to make sure.

**Comment by jbednar** [comment]
Eliminating such a file seems reasonable, but the proposed holoviews_rc dictionary seems confusing.  Why not just have a module attribute or class parameter for the backend, defaulting to agg, and then tell people to set this parameter to None if they would rather handle the backend themselves?  Of course, you'd have to coordinate the use of this parameter with the rc-executing mechanisms, such that the parameter is only checked after running the rc files, and only then is the backend set in matplotlib if necessary, but this seems more straightforward to me.

**Comment by jlstevens** [comment]
> Eliminating such a file seems reasonable, but the proposed holoviews_rc dictionary seems confusing.

I agree. For now I am just going to run ``execfile`` in the hope two consecutive  backend switches don't cause problems.

> Why not just have a module attribute or class parameter for the backend, defaulting to agg, and then tell people to set this parameter to None if they would rather handle the backend themselves?

Sure, that is probably a better approach if we need a more involved approach to configuration. I hope to avoid that for now!

**Comment by jlstevens** [comment]
The commit above implements support for rc files as discussed. All I did decide to do different is that I look for ``~/.holoviews.rc`` (i.e a hidden file) as this is standard for rc files in the home directory.

**Comment by jlstevens** [comment]
Other than having to use an ``execfile`` replacement for Python 3, this code seems to be fine (Travis is now passing). Is there anything else to discuss before closing this issue?

I should note that this is what you need in your ``holoviews.rc`` if you want a different backend:

```python
import matplotlib.pyplot as plt
plt.switch_backend('tkagg')
```

I am also wondering how this could be tested - you can use ``del(sys.modules["holoviews"])`` to repeatedly import holoviews in a way that forces a full reload (Python 2 and 3) but then I am not sure if it is a good idea to write to home for a test (e.g would this work on Travis?). 

It does seem that I could dafely set the environment variable and point to a ``holoviews.rc`` in the current directory but I am not entirely sure such a test is really worth it given how little code is involved.

**Comment by philippjfr** [comment]
Since Jean-Luc implemented this and it all seems to be working I'll close this issue now.

**Comment by basnijholt** [comment]
Could you give a simple example of how I could set the plotting and styling options in this file?

**Comment by jlstevens** [comment]
Here is my proposed example of a ``holoviews.rc`` file.

```python
# -*- mode: Python;-*-

# Example holoviews.rc file which may be located:

#    1. Via a path set in the HOLOVIEWSRC environment variable
#    2. In ~/.holoviews.rc (note the leading dot)
#    3. In ~/.config/holoviews/holoviews.rc

# Below are some examples to help you make your own customizations
# which you can uncomment and adapt as necessary.

# Note: Unless you share your rc file, your customizations and display
# results will not be easily reproducible by other people!

#========================================================#
# Uncomment below and adapt to switch matplotlib backend #
#========================================================#

import matplotlib.pyplot as plt
plt.switch_backend('agg')

#============================================================#
# Uncomment below for an example of plot/style customization #
#============================================================#

from holoviews import plotting       # This import defines package defaults
from holoviews import Options, Store

def custom_options(options):
    options.Image = Options('style', cmap='gray')
    options.Curve = Options('style', color='r')
    options.Curve = Options('plot', show_grid=False)


Store.option_setters.append(custom_options)
Store.register_plots()
```

We will have to make an example like this available somewhere in the documentation for people to adapt...

**Comment by basnijholt** [comment]
May I also suggest to add the folder from which you are running the ``ipynb``.

I'm working on 3 different machines and it's just annoying if I have to ``scp`` the rc file each time I made a change. If it would check for ``holoviews.rc`` in the same folder, git would solve all my problems.

**Comment by jlstevens** [comment]
> May I also suggest to add the folder from which you are running the ipynb

This sounds reasonable to me as this is something meaningful at the user level. Initially, I thought finding the current folder would be tricky but ``os.getcwd()`` does seem to return the current working directory in IPython after you ``cd`` around. This isn't quite the same as the location of the active ipynb file though (which is surprisingly hard to find!).

I am open to this suggestion, my concern is that using ``os.getcwd()`` to find the rc file isn't likely to be very robust/reliable. Also note, you could achieve a similar effect by taking the file above, naming it to ``holoviews_rc.py`` and running ``import holoviews_rc`` in your notebook which I think might be the cleaner/more explicit way to do things in this use case.

**Comment by basnijholt** [comment]
The ``import holoviews_rc`` suggestion suits my needs just fine. Thanks!
