### ISSUE TITLE
Overlaying DynamicMaps with different values in same dimension bug

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#920]
``` python
dm1 = hv.DynamicMap(lambda x, y: hv.Curve(np.random.rand(10)), kdims=[hv.Dimension('x', values=[0, 1]), hv.Dimension('y', values=[0, 1])])
dm2 = hv.DynamicMap(lambda x, y: hv.Curve(np.random.rand(10)), kdims=[hv.Dimension('x', values=[1, 2]), hv.Dimension('y', values=[0, 1])])
dm2 * dm1
```

compare with `dm1 * dm2`

Plots are being generated for `x` values, even though they don't exist.

**Comment by basnijholt** [comment]
To make it a bit more clear, I would expect:
```
hv.HoloMap({i: hv.Curve(np.random.rand(10)) for i in [0, 1]}) * hv.HoloMap({i: hv.Curve(np.random.rand(10)) for i in [1, 2]})
```

**Comment by philippjfr** [comment]
Thanks for explaining it. The behavior you describe is what I would expect as well.

**Comment by jlstevens** [comment]
I've assigned myself to this issue. Shouldn't be too hard to fix as I just need to raise an appropriate ``KeyError` in the right place.

**Comment by philippjfr** [comment]
This has now been fixed, please reopen if you encounter any issues.
