### ISSUE TITLE
QuadMesh fails to set colorbar scale in python 3

### ISSUE THREAD

**Issue by piskunow** [ioam/holoviews#942]
When updating a code from python 2 to python 3, QuadMesh stops recognizing the colorbar limits 'clim'.
The code below produces different results in python 2 than python 3.

```
import numpy as np
import holoviews as hv
hv.notebook_extension()
```
```
%%opts QuadMesh [aspect='square', colorbar=True](cmap='hot', clims=(0,0.5))
x_array = np.linspace(0,1,50)
y_array = np.linspace(0,1,50)
z_mesh = np.outer(x_array,y_array)

hv.QuadMesh((x_array,y_array,z_mesh))
```
python 2 output:
![python2](https://cloud.githubusercontent.com/assets/22959851/19561882/9ec39342-96da-11e6-8aae-17de3a62af62.png)

python 3 output:
![python3](https://cloud.githubusercontent.com/assets/22959851/19561883/a4658670-96da-11e6-9a69-500dbdc60b36.png)

**Comment by philippjfr** [comment]
The ``clims`` style option was incorrectly defined as ``clim`` which caused these issues. This has  now been fixed in the PR referenced above. If you're still encountering problems please reraise the issue.
