### ISSUE TITLE
%output bug overwrites settings

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#947]
this gives me a `svg` image

```
import holoviews as hv
hv.notebook_extension()
hv.Store.renderers['matplotlib'].fig = 'svg'
hv.Curve([0,1])
```

this gives me a `png`

```
import holoviews as hv
hv.notebook_extension()
hv.Store.renderers['matplotlib'].fig = 'svg'
%output size=120
hv.Curve([0,1])
```

**Comment by jlstevens** [comment]
Thanks for reporting this!

I am sure there is a way to make it work the way you expected. My only question is that if you are using the line magic anyway, why not just do:

```
%output size=120 fig='svg'
```

I suppose this is probably more of an issue when considering the ``%%output`` cell magic...

**Comment by basnijholt** [comment]
I am encountering this in converting ipynbs to a website for this [mooc](https://github.com/topocm/topocm_content).

Some notebooks contain `%output size=120`, and some do not. I prefern not to change ~50 notebooks, but rather I just put [this line](https://github.com/topocm/topocm_content/blob/topocondmat/code/init_mooc_nb.py#L131) in the file that is run in each notebook to do default imports and set default settings.
