### ISSUE TITLE
Confusing Histogram constructor

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#95]
If have a collection of points and want to make an equivalent ``Histogram``, I would expect to be able to do this:

```python
points = [(35, 3.7), (45, 6), (55, 12), (65, 8), (75, 15)]
Points(points)) + Histogram(zip(*points)))
```

But instead, I need to do this (i.e cast to a tuple and flip the arguments around):

```python
points = [(35, 3.7), (45, 6), (55, 12), (65, 8), (75, 15)]
Points(points)) + Histogram(tuple(zip(*points))[::-1])
```

This doesn't make much sense!

**Comment by philippjfr** [comment]
I just remembered why the constructor is so weird, it matches the output of ``np.histogram``. We could support an additional data format in the constructor. These two lines would do it:

```python
        elif isinstance(values, list):
            edges, values = zip(*values) 
```

Then you could do:

```python
points = [(35, 3.7), (45, 6), (55, 12), (65, 8), (75, 15)]
Points(points) + Histogram(points)
```

**Comment by jlstevens** [comment]
Sure! Seems reasonable to me although I think checking whether values is all tuples is a safer thing to do. I've pushed this commit in 03b5d38.

There is still scope for better error validation in the constructor but I think that should be filed as a separate issue.
