### ISSUE TITLE
%%opts delete style

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#96]
I look to two images, one of them with a group defined. For this group some style is defined. This works fine:
```python
%opts Image.Phase (cmap='bwr')
x = np.linspace(-0.5,0.5,1024, endpoint=False)
bounds = (-0.5,-0.5,0.5,0.5)
xx, yy = np.meshgrid(x,x)

hv.Image(abs(xx)) + hv.Image(np.angle(xx), group="Phase")
```

However, sometimes I want to see a colorbar:
```python
%%opts Image [colorbar=True]
hv.Image(abs(xx)) + hv.Image(np.angle(xx), group="Phase")
```
Now the cmap for both images is the same!

**Comment by philippjfr** [comment]
This is related to #93, I think @jlstevens will have a look at both of these issues later today.

**Comment by jlstevens** [comment]
Philipp's hunch was right and this was related to #93. You can see the commits used to fix the option system in that discussion. I've tried this example again and the colour maps are no longer the same and look correct to me.

Closing this issue but I am happy to reopen it if things still aren't working for you.
