### ISSUE TITLE
Adding an annotation causes bogus legend to appear

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#961]
A plot with a single Curve or other single element normally has no legend, but a legend appears when the element is overlaid with an annotation:

![image](https://cloud.githubusercontent.com/assets/1695496/19871744/2b74ee72-9fae-11e6-90ff-bd267b838341.png)

Since annotations don't show up in the legend, there's no reason that I can see to have such a legend in that case, so I would vote that the legend be suppressed if the overlay consists only of annotations on top of a single Element.

**Comment by philippjfr** [comment]
Fixed in https://github.com/ioam/holoviews/pull/3139
