### ISSUE TITLE
To small SVG in tutorial

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#97]
In the Options tutorial, first image the SVG file has almost no area for the plot, only very crowded axis:
http://ioam.github.io/holoviews/Tutorials/Options

Before, this svg plot was much larger

**Comment by philippjfr** [comment]
Thanks for reporting this. This was temporarily broken but has since been fixed. I've just updated the docs and the fixed Tutorials should be live in a few minutes.

**Comment by jbednar** [comment]
Thanks for the quick fix.  Any idea why it either (a) rebuilt the public page even though the tests were failing, or (b) the tests didn't fail for such an egregious problem?  Both possibilities are worrisome.

**Comment by philippjfr** [comment]
There's various reasons why these particular plots are untested. First of all they are SVG and svg output is not guaranteed to be the same so we have to ignore it. Secondly these plots were exported and then redisplayed using the IPython SVG display function, which again cannot be tested. It's annoying but there's no easy fix.

**Comment by jbednar** [comment]
That's a shame.
