### ISSUE TITLE
HoloMap missing a slider

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#971]
The keys are not orthogonal in this example, but there should still be two sliders:

![image](https://cloud.githubusercontent.com/assets/890576/20024475/d0c2d4d8-a2de-11e6-9f0b-cd89d4205863.png)

Here is the code as text:

```python
import numpy as np
import holoviews as hv
hv.notebook_extension()
hv.HoloMap({k:hv.Image(np.random.rand(10,10)) for k in [(10, 1.2), (20, 1.3), (30, 1.4)]}, 
           kdims=['a','b'])
```

Just to be sure, I checked orthogonal keys work fine, so there is no problem with this for instance:

```python
hv.HoloMap({(k1,k2):hv.Image(np.random.rand(10,10)) 
                for k1 in range(10) for k2 in range(5)}, kdims=['a','b'])
```

**Comment by philippjfr** [comment]
This seems to be because the hierarchical dimensional handling being broken. I'll see if it can be fixed easily otherwise I suggest we scrap it until we have a better solution.

**Comment by philippjfr** [comment]
This was fixed in https://github.com/ioam/holoviews/pull/973. Closing.
