### ISSUE TITLE
Heatmap number formatting in Continuous Coordinates tutorial

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#977]
I'm pretty sure the heatmap cells had 2 or 3 digit numbers previously, not what's currently on the website:

![image](https://cloud.githubusercontent.com/assets/1695496/20037676/9753c286-a41c-11e6-9379-8a1fe2c9275c.png)

Maybe I'm just imagining that, but in any case we probably need to specify a formatter for those values.

**Comment by philippjfr** [comment]
Fixed in https://github.com/ioam/holoviews/pull/2122.
