### ISSUE TITLE
hv.help points to non-existent website

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#978]
Example:

```python
hv.help(hv.Curve)
```

>Curve
Online example: https://ioam.github.io/holoviews/Tutorials/Elements.html#Curve
Help for the data object: holoviews.help(Curve) or holoviews.help(<curve_instance>)

**Comment by jlstevens** [comment]
I'm happy to fix this so I've assigned myself to this issue.

**Comment by philippjfr** [comment]
Assigned to 1.7, this is an easy fix and should be implemented asap.

**Comment by philippjfr** [comment]
Now fixed, closing.
