### ISSUE TITLE
Improved widget layout

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#98]
Currently the selection widget isn't great for a number of reasons. It is using various CSS hacks when it could be using a proper Bootstrap form, making the layout a lot more robust and aligning things better. I've already implemented this and I have to say at least code-wise it's much cleaner.

Additionally it addresses the following issues of the old version:

* Very inconsistent output between IPython 2 and 3 due to the updated Bootstrap dependency.
* Small screens squash the widgets to the point of being unusable.
* Long titles would squash the textbox.

The new version puts the label on a separate line from the slider/textbox or dropdown menu. 

Possible drawbacks:

* Slider is slightly shorter.

Here is the IPython2 output:

![screenshot from 2015-05-23 04 28 02](https://cloud.githubusercontent.com/assets/1550771/7782244/2470d338-0104-11e5-8856-f990ee193cf4.png)

and here the IPython3 output:

![screenshot from 2015-05-23 04 28 48](https://cloud.githubusercontent.com/assets/1550771/7782246/3b237f68-0104-11e5-8c89-e7e607a64d2b.png)

All suggestions for improvement are welcome!

**Comment by jbednar** [comment]
Seems like an improvement to me!

**Comment by jlstevens** [comment]
Looks good to me too!

I am happy for this to go in before the release though I have a list of few things we need to check:

* 1.1.0 to 1.1.1? I don't think we have enough changes to justify 1.2.0 so how about jumping to 1.1.5 to show this includes more than just a couple of bug fixes?
* We need to make sure we are happy how this looks in all our example notebooks.
* I have one bug in the options system to fix so if this is merged, I think we should wait two days before release to make sure no new problems crop up (that are relevant to the imminent release).
* In addition to looking better, is this new approach cleaner and hopefully more easily extensible in the future?

Anyway, it time for me to fix what I am hoping is the last bug before release...

**Comment by philippjfr** [comment]
I've now pushed the redesign, in addition to what you see above I've added a frame around the widgets. I'll leave this issue open for now so I can get some feedback now that you can test it in action.

**Comment by basnijholt** [comment]
I really like the new widget design, especially like them being smaller so there's more space for the plots.

Don't know whether this is a ``nbconvert`` bug or ``css`` related, but the widgets look a bit awkward when converted to html (only checked ``--to slides``).

![screen shot 2015-05-24 at 22 40 26](https://cloud.githubusercontent.com/assets/6897215/7789560/2e5e0e34-0266-11e5-909e-a94f50f40241.png)

**Comment by philippjfr** [comment]
Ah, very annoying, I did pack the text box and the widget pretty tightly. The annoying part is that this is likely only really a problem on using the reveal.js slides template because they set the default viewing area to be fairly small. I'll do a bit of testing with different templates and see what I can come up with. Don't really want to shrink the slider or text box any further.

**Comment by philippjfr** [comment]
This should be fixed since https://github.com/ioam/holoviews/commit/f51af0292bac1fc5931950925445598d3902e098. I've had to declare a bunch of margins and padding explicitly and also got rid of some pointless padding between the image and the widget box. Reveal.js still messes with the fancy border effect but it looks decent for me at least. The widget will also appear a little larger again but I haven't actually shrunk the area for the plot to be drawn in. Report back whether it works for you.

**Comment by basnijholt** [comment]
It's a bit better, still part of the slider is overlapping, but it's not a real issue for me.

**Comment by philippjfr** [comment]
Still? I tested it locally and it seemed to be fine, odd that we're getting different output. One recommendation I would make, which is what I do when I give a talk with slides is to adjust the reveal.js configuration to make the output a little larger. I haven't discovered how to do this with templates yet put if you go into your converted HTML slides you could look for the following and adjust the width and height however you like:

```javascript
Reveal.initialize({
    ...

    // The "normal" size of the presentation, aspect ratio will be preserved
    // when the presentation is scaled to fit different resolutions. Can be
    // specified using percentage units.
    width: 960,
    height: 700,  
});
```

**Comment by basnijholt** [comment]
It was indeed due to the settings of reveal.js, false alarm.

It looks good :)

**Comment by philippjfr** [comment]
Great I'll close this issue for now. Let us know if you encounter any other issues.
