### ISSUE TITLE
Hover information not displaying for Bokeh Curves

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#986]
This simple example demonstrates the issue:

![image](https://cloud.githubusercontent.com/assets/890576/20228040/57ffb4d0-a847-11e6-9ad4-44ebed8a56a6.png)

And here is the code shown in this screenshot:

```python
%%opts Curve [tools=['hover']]
hv.NdOverlay({(0,1):hv.Curve([0,1,2]), 
              (0,2):hv.Curve([3,2,1]),
              (1,1):hv.Curve([3,1,2])}, kdims=['A','B'])
```

**Comment by philippjfr** [comment]
I believe this has been at least partially fixed in #1004, such that in batched mode only the NdOverlay dimensions are displayed on hover. Need to double check it behaves correctly in non-batched mode too.
