### ISSUE TITLE
Overlaying an AdjointLayout should either error or overlay the main layer

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#987]
Currently when you overlay an AdjointLayout on top of an element you get an invalid object:

```python
print repr(hv.Points(range(10)) * hv.Points(np.random.rand(10,2)).hist())
```

```
:Overlay
   .Points.I        :Points   [x,y]
   .AdjointLayout.I :AdjointLayout
      :Points   [x,y]
      :Histogram   [x]   (Frequency)
```

If you try to display this object you get this error:

```
/Users/philippjfr/miniconda/envs/geoviews/lib/python2.7/site-packages/holoviews/plotting/plot.py in _create_subplots(self, ranges)
    818 
    819             if not isinstance(key, tuple): key = (key,)
--> 820             subplots[key] = plottype(vmap, **plotopts)
    821             if (not isinstance(plottype, PlotSelector) and
    822                 issubclass(plottype, GenericOverlayPlot)):

TypeError: __init__() takes exactly 4 arguments (2 given)
```

I would argue that attempting to overlay an ``AdjointLayout`` should simply cause the main layer to be overlaid, returning another ``AdjointLayout``. In which case executing the same code would return this instead:

```python
print repr(hv.Points(range(10)) * hv.Points(np.random.rand(10,2)).hist())
```

```
.AdjointLayout.I :AdjointLayout
   :Overlay
      :Points   [x,y]
      :Points   [x,y]
   :Histogram   [x]   (Frequency)
```

Alternatively an error should be raised when trying to overlay something with an ``AdjointLayout``.

**Comment by jbednar** [comment]
Isn't this example less about "overlaying an AdjointLayout on top of an element" and more about applying an ambiguous .hist() method call to an Overlay?  I.e., the result of it is indeed an overlay of an AdjointLayout and an element, but that's not what the user asked for; instead they asked for the .hist() of something ambiguous.  In this case the ambiguity was resolved in a way that doesn't work, and in your proposed solution it's resolved in a way that would presumably work?

In any case, it would be great to have an informative error message if using .hist() in this way is not legal.

**Comment by jbednar** [comment]
Oops; I misread the parentheses!  Never mind; it is how you described it.

**Comment by philippjfr** [comment]
>instead they asked for the .hist() of something ambiguous. In this case the ambiguity was resolved in a way that doesn't work, and in your proposed solution it's resolved in a way that would presumably work?

As you say, that's not the issue, but in any case the ``hist`` method on an Overlay supports an index argument, which resolves the ambiguity. You're right that I could have changed the bracketing to make it work correctly though.

**Comment by jbednar** [comment]
Seems like your solution would work if there is no ambiguity about what the histogram applies to in the final data structure.  But presumably there are such overlays that aren't going to work?   E.g. should overlaying an AdjointLayout with an AdjointLayout be ok (moving one of the histograms to a different location?)?

**Comment by philippjfr** [comment]
Good point, it could either overlay the adjoined plots too or add them separately (which can fail if there are already two adjoined plots). The most useful thing to do would be to check the dimensions of the adjoined plots and overlay them if they match and combine them if they don't.

**Comment by jbednar** [comment]
Sounds good.

**Comment by jlstevens** [comment]
> I would argue that attempting to overlay an AdjointLayout should simply cause the main layer to be overlaid, returning another AdjointLayout. 

That sounds reasonable to me.

> should overlaying an AdjointLayout with an AdjointLayout be ok

I think it should. I think I would expect the bottom AdjointLayout position to be maintained and the side-element of the AdjointLayout above to be moved (if necessary). Of course, you can only do this so many times before you have nowhere you can put your side-element (which would then be an error).

**Comment by philippjfr** [comment]
Now implemented.

**Comment by jbednar** [comment]
Thanks!
