### ISSUE TITLE
renderer.save with matplotlib puts legend outside figure's bbox

### ISSUE THREAD

**Issue by llvilanova** [ioam/holoviews#993]
Seems like holoviews is not accouting for the legend when calculating a figure's bounding box with the matplotlib backend. I'm using holoviews version 1.6.2, matplotlib 1.5.3 and python 2.7.12+.

Here's a minimal failing example:

<pre>
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import holoviews as hv
import holoviews.plotting.mpl
renderer = hv.Store.renderers['matplotlib'].instance(fig='svg', holomap='gif')
options={
    "Bars": dict(
        plot=dict(
            color_by=["stack"],
            legend_position="top",
        ),  
    ),  
}
data = [(("foo1", "bar1", "baz1"), 1)]
fig = hv.Bars(data,
              kdims=['Benchmark', 'Tool', ''], vdims=['Execution time [ms]'])
renderer.save(fig, "/tmp/figure", options=options)
</pre>

**Comment by philippjfr** [comment]
Could you paste the saved image here? For me the output looks correct:

<img width="367" alt="screen shot 2016-11-29 at 9 14 47 pm" src="https://cloud.githubusercontent.com/assets/1550771/20729205/ed08d478-b678-11e6-8614-12a11f81e039.png">

**Comment by llvilanova** [comment]
Here's what I get (the same happens for SVG, PNG and PDF):

![figure](https://cloud.githubusercontent.com/assets/326386/20753659/ae5cd848-b707-11e6-8ce6-d9514c4aaa63.png)

Setting this on options fixes it without me having to modify holoview's code:

<pre>
    def finalize(plot, element):
        # make sure the legend is accounted for during bbox calculation
        axis = plot.handles["axis"]
        legend = axis.get_legend()
        plot.handles["bbox_extra_artists"] += [legend]
    options={
        "Bars": dict(
            plot=dict(
                color_by=["stack"],
                legend_position="top",
                final_hooks=[finalize],
            ),
        ),
    }
</pre>

**Comment by philippjfr** [comment]
I'll keep investigating but if you've got a minute could you try it again on holoviews master?

**Comment by llvilanova** [comment]
I just tried master and it also fails (simply cloned it and prepended its directory into sys.path). See pull request #998 for a fix (I'm not sure that's the proper way to do it).
