### ISSUE TITLE
Specification of options for multiple Paths

### ISSUE THREAD

**Issue by mrksr** [ioam/holoviews#995]
Since there is currently no propagation of options for plots (see #638), I quite often find myself specifying the same plotting options for one specific element, say a `Curve`, and all elements which might wrap this element, such as `Overlay` or `Layout`. This results in quite some repetition when done using the `%opts`-magic:
```python
%opts Curve [width=900, height=500] Overlay [width=900, height=500] NdOverlay [width=900, height=500]
```

Ideally, I would like to be able to specify multiple paths at once for which the following styles should be applied, like so:
```python
%opts Curve Overlay NdOverlay [width=900, height=500]
```

This, I think, is legal right now, it just has different semantics: The options are only applied to `NdOverlay`, while for both `Curve` and `Overlay` this is a no-op. Since I do not expect the specification of no-ops to be of any use, it should not be too bad to change it.

I would be happy to get my feet wet with holoviews and implement this myself. If you can point me into the right direction, I will get started.

**Comment by jlstevens** [comment]
Thanks for filing this issue! 

This feature is one I have considered before and would be happy to support. The place I would implement this is [here](https://github.com/ioam/holoviews/blob/master/holoviews/ipython/parser.py#L257) in the ``OptsSpec`` parser. Here is a little demo of how it works currently:

```python
from holoviews.ipython.parser import OptsSpec
OptsSpec.parse('Image [width=100] (s=3) Curve [width=100] (s=3)')
{'Curve': {'plot': Options(width=100), 'style': Options(s=3)},
 'Image': {'plot': Options(width=100), 'style': Options(s=3)}}
```

What we need for this feature to work is for this to happen:

```python
from holoviews.ipython.parser import OptsSpec
OptsSpec.parse('Image Curve [width=100] (s=3)')
{'Curve': {'plot': Options(width=100), 'style': Options(s=3)},
 'Image': {'plot': Options(width=100), 'style': Options(s=3)}}
```
Currently the return value is this:

``` {'Curve': {'plot': Options(width=100), 'style': Options(s=3)}, 'Image': {}}```

You shouldn't need to worry about the pyparsing stuff in that file and can probably just copy the dictionaries as appropriate at the end of the ``parse`` method (if you detect empty dictionaries).

One worry is about the semantics as I think this is a bit of a special case:

1. This copying semantics should only apply to plot options.
2. I guess supplying style options 'interrupts' this copying behavior so if you want to copy plot options but still specify style options you would need to do something like this:

```
%%opts Image Curve [width=100] Image (s=3)
```

(note that ``Image`` is specified once for the plot options then again just for the style options)

3. Here is another example to consider:

```
%%opts Image Curve [width=100]  Spikes (lw=3)  Histogram RGB [height=200]
```

Here I would expect only ``width=100`` shared between ``Image`` and ``Curve``, ``Spikes`` would only have the ``lw=3`` style option and then ``height=200`` would be the only plot option for ``Histogram`` and ``RGB``.

Anyway, hope that gets you started! I don't think it should be too hard to implement and would be a useful feature. The main reason I wouldn't want to accept this feature is if we find it breaks backwards compatibility somehow (I don't think it does).

**Comment by mrksr** [comment]
As discussed on gitter, option grouping should work for all types of options, such that
```
%opts A B {x} [y] (z)
```
is strictly equivalent to
```
%opts A {x} [y] (z) B {x} [y] (z)
```
and also generalizes to more than two pathspecs.

Additionally, we noticed that option definitions are not properly merged right now:
```python
hv.ipython.parser.OptsSpec.parse("Image (c='b') Image (s=3)")
{'Image': {'style': Options(s=3)}}
```
While we're at it, this should also be fixed to result in
```python
{'Image': {'style': Options(c='b', s=3)}}
```

**Comment by philippjfr** [comment]
I've added the issue to the milestone so we don't forget to mention it in our release notes. But since this is now implemented I'll close.
